### PR TITLE
Patch color_sliders.py

### PR DESCRIPTION
**Pull request by crashMOGWAI**
Partially addresses #6831 by preventing non int values from being passed to hex conversion

### CODE REVIEW

**Comment by bryevdv** [comment]
Thanks for the fix! will merge when green

**Comment by bryevdv** [comment]
@crashMOGWAI the one tests failure is from our linter:
```
>       assert len(errors) == 0, "Code quality issues:\n%s" % "\n".join(errors)
E       AssertionError: Code quality issues:
E         File contains trailing whitespace: examples/plotting/file/color_sliders.py, line 65.
E       assert 1 == 0
E        +  where 1 = len(['File contains trailing whitespace: examples/plotting/file/color_sliders.py, line 65.'])
```
Once you remove the trailing whitespace on that line and push a new commit the tests will go green

**Comment by mattpap** [comment]
Although this helps with the example, this doesn't fix the underlying cause. I would rather investigate why numerical slider with integer start and step, end can return inexact values. Otherwise this issue will pop up elsewhere sooner than later.

**Comment by bryevdv** [comment]
I'm going to go ahead and merge this so the example works better for the release, but leave the issue open to solve the general problem

**Comment by bryevdv** [comment]
@mattpap this diff fixes, is OK?
```
diff --git a/bokehjs/src/coffee/models/widgets/slider.coffee b/bokehjs/src/coffee/models/widgets/slider.coffee
index 6eaa633af..a2021b5b1 100644
--- a/bokehjs/src/coffee/models/widgets/slider.coffee
+++ b/bokehjs/src/coffee/models/widgets/slider.coffee
@@ -12,7 +12,11 @@ export class SliderView extends AbstractSliderView
       step: @model.step
     }

-  _calc_from: ([value]) -> value
+  _calc_from: ([value]) ->
+    if Number.isInteger(@model.start) and Number.isInteger(@model.end) and Number.isInteger(@model.step)
+      return value|0
+    else
+      value

 export class Slider extends AbstractSlider
   type: "Slider"
```

**Pull request merged**
