### PR TITLE
correctly export unicode content with unminified resources

### LINKED ISSUE #7885: Exporting DataTable to png broken
Using bokeh master it appears that exporting a DataTable to png is broken. This appears to be a regression in 0.12.16 as it's working in 0.12.15. Here is a minimal reproducible example:

```python
from bokeh.io import export_png
from datetime import date
from random import randint

from bokeh.io import output_file, show
from bokeh.layouts import widgetbox
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn

output_file("data_table.html")

data = dict(
        dates=[date(2014, 3, i+1) for i in range(10)],
        downloads=[randint(0, 100) for i in range(10)],
    )
source = ColumnDataSource(data)

columns = [
        TableColumn(field="dates", title="Date", formatter=DateFormatter()),
        TableColumn(field="downloads", title="Downloads"),
    ]
data_table = DataTable(source=source, columns=columns, width=400, height=280)

export_png(data_table, filename="table.png")
```

>UnicodeEncodeError: 'latin-1' codec can't encode character '\ufffd' in position 879408: ordinal not in range(256)

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #7885
- [x] tests added / passed

cc @mattpap @philippjfr

### CODE REVIEW

**Comment by bryevdv** [comment]
The new tests fail with the old code and pass with the new.

**Comment by bryevdv** [comment]
FYI my best guess is that one of the BokehJS dependencies has some unicode comments that get stripped out during minification.

**Comment by bryevdv** [comment]
OK well this is failing on py2 pretty hard. I thought I had run locally but now I'm guessing I accidentally used ` py.test` from a different conda env. 

The failures seems to be what the `encode_utf8` function was for: to obtain something that could be written as unicode by `write` on either python 2 or python 3... it just has a misleading name

**Comment by bryevdv** [comment]
OK green now. @philippjfr please check this out if you get a chance. @mattpap any objections? This is the most minimally invasive solution I could find at this point.

**Comment by mattpap** [comment]
> The failures seems to be what the decode_utf8 function was for

It works now, because you are cancelling out both transforms on py 2. Looks good. Obviously PR #7889 when done, will make all this unnecessary.

**Pull request merged**
