### PR TITLE
Add box layout with widgets supported

### PR DESCRIPTION
**Pull request by birdsarah**
Continues work on #4164 

Fixes: #2504, #3346, #2344, #1710, #2451, #4180

The goal of this PR is to add the initial box layout with a `Row` and `Column`. For this PR, only widgets can be gracefully laid out in a `Row`, and `Column`.

This work builds off #4305, which should be merged first.

This PR also updates the default styling of widgets to try and give a more unified default across plots and widgets.

There may be widgets that still need small tweaks so they play nicely with the new layout.

- [ ] test DataTables
- [ ] test DataTables on server
- [ ] test on server
- [ ] test with components
- [ ] specifying width & height for a widget fixes its width/height
- [ ] fix expanding to fill width/height of window
- [ ] fix templating on button

### CODE REVIEW

**Comment by birdsarah** [comment]
Before:
screen shot 2016-05-09 at 1 44 24 pm

**Comment by birdsarah** [comment]
Where I currently am:
screen shot 2016-05-13 at 5 56 44 am

**Comment by birdsarah** [comment]
ping @bryevdv, there's still a decent amount of work to do, but you may want to start reviewing.

I may punt having two columns of widgets next to each other line-up nicely as it's tricky in interesting ways.

The current state is that widgets in a Row/Column look ok (with some tweaking to do), but they are a mess now in vplot/hplot etc e.g. https://s3.amazonaws.com/bokeh-travis/129949306/examples.html#plotting/file/python_callback

I don't particularly want to fix hplot/vplot for the sake of not breaking master so I'm not sure exactly what to do. I was hoping this was going to be an incremental PR, but that may not be possible.

**Comment by bryevdv** [comment]
Isn't the plan to have `vplot` call `Column` and `hplot` call `Row` and issue deprecation warnings?

**Comment by birdsarah** [comment]
Yes, but I was hoping not to do that in this PR, as it also means fixing up plot to work with the new layouts.

**Comment by birdsarah** [comment]
but i'm not sure i have a choice.

**Comment by birdsarah** [comment]
if we want to keep master fully functional

**Comment by bryevdv** [comment]
Hrm, I get this trying to build
```
[14:40:19] Finished 'scripts:eco' after 809 ms
Potentially unhandled rejection [2] Error: Invalid mapping: {"generated":{"line":15,"column":2},"source":"/Users/bryan/work/bokeh/bokehjs/src/vendor/bootstrap-3.1.1/less/grid.less","original":{"line":1,"column":null},"name":null}
  at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/node_modules/source-map/lib/source-map-generator.js:277:13)
  at SourceMapGenerator_addMapping [as addMapping] (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/node_modules/source-map/lib/source-map-generator.js:101:12)
  at [object Object].SourceMapOutput.add (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/source-map-output.js:88:42)
  at [object Object].Element.genCSS (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/tree/element.js:42:12)
  at [object Object].Selector.genCSS (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/tree/selector.js:104:21)
  at [object Object].Ruleset.genCSS (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/tree/ruleset.js:389:21)
  at [object Object].Directive.outputRuleset (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/tree/directive.js:124:18)
  at [object Object].Media.genCSS (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/tree/media.js:34:10)
  at [object Object].Ruleset.genCSS (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/tree/ruleset.js:414:18)
  at [object Object].SourceMapOutput.toCSS (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/source-map-output.js:126:24)
  at [object Object].SourceMapBuilder.toCSS (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/source-map-builder.js:23:35)
  at [object Object].ParseTree.toCSS (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/parse-tree.js:33:47)
  at /Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/render.js:31:40
  at /Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/parse.js:63:17
  at Object.finish [as _finish] (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/parser/parser.js:183:28)
  at Object.ImportVisitor._onSequencerEmpty (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/visitors/import-visitor.js:35:14)
  at ImportSequencer.tryRun (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/visitors/import-sequencer.js:50:14)
  at /Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/visitors/import-sequencer.js:19:25
  at fileParsedFunc (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/import-manager.js:50:17)
  at /Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/import-manager.js:113:21
  at finish (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/parser/parser.js:183:28)
  at Object.Parser.parse (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/parser/parser.js:191:24)
  at loadFileCallback (/Users/bryan/work/bokeh/bokehjs/node_modules/gulp-less/node_modules/less/lib/less/import-manager.js:112:64)

```
even after `npm update` might be why I'm not seeing changes

**Comment by bryevdv** [comment]
of course, after `rm -rf node_modules; npm install` it works fine..

**Comment by birdsarah** [comment]
The invalid mapping was that thing luke was dealing with last week I believe. Glad it's all working now.

**Comment by birdsarah** [comment]
Currently at the following state:
screen shot 2016-05-13 at 5 30 46 pm


Am going to start a new branch deprecating the old layout modules so that we can review that more easily.

**Comment by birdsarah** [comment]
This PR shouldn't be merged in its current state as it breaks things, but can be reviewed. I can't find a way to not do all of the rest of the layout work in one large chained PR way. The problem is is that widgets now must live in a Row / Column - they are messed up in VBox/HBox. But conversely Plot does not render in Row/Column. To make Plot work in Row/Column I just have to do the rest of the layout work.

This PR:
1. Adds named responsive modes `box`, `width`, `fixed`
2. Adds the new layout box and its layouts `Row` and `Column`
3. Implements widgets working within `Row` & `Column`
4. Starts setting some new styling defaults as part of an effort to make a crisper more unified default
5. Tweaks a number of widgets to work better with the new layout (there's a good amount of follow-on tweaking to do to make widgets super-awesome with layout)
6. Implements resize on document (but does not remove it from plot yet)
7. Implements a template for button widget - all widgets now need to live under a widget div for consistent layout
8. Removes default height and width for mark-up widgets because they'll play more sensibly in layouts now.

It also:
1. Has a small improvement to selenium testing
2. Cleans up a naming inconsistency in the javascript tests

Apart from `Box.coffee` everything else should have tests.

**Pull request closed without merging**
