### PR TITLE
allow arrow heads to contribute clipping regions

### LINKED ISSUE #4667: Arrow and line_width
High value of `line_width` interferes with the arrow tip. Consider this example (bokeh 0.12.0rc2-8-g9bb50c0):

``` python
from bokeh.plotting import figure, output_file, show
from bokeh.models import Arrow, OpenHead, NormalHead, VeeHead

output_file("foo.html")

p = figure(plot_width=600, plot_height=600, x_range=(-0.1,1.1), y_range=(-1,6))

p.add_layout(Arrow(end=NormalHead(line_width=3), x_start=0, y_start=0, x_end=1, y_end=0, line_width=10))
p.add_layout(Arrow(end=OpenHead(line_width=5), x_start=0, y_start=1, x_end=1, y_end=2, line_width=10))
p.add_layout(Arrow(end=VeeHead(line_width=3), x_start=0, y_start=2, x_end=1, y_end=5, line_width=10))

show(p)
```

Output:
screen shot 2016-12-15 at 9 34 33 pm

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #4667
- [x] tests added / passed

This test code

```
from bokeh.plotting import figure, output_file, show
from bokeh.models import Arrow, OpenHead, NormalHead, VeeHead

output_file("foo.html")

p = figure(plot_width=600, plot_height=600, x_range=(-0.1,1.1), y_range=(-1,6))

p.add_layout(Arrow(start=VeeHead(line_width=1, fill_color="white"), x_start=0, y_start=2, x_end=1, y_end=5, line_width=10))
p.add_layout(Arrow(start=NormalHead(line_width=1, fill_color="white"), x_start=0, y_start=0, x_end=1, y_end=0, line_width=10))
p.add_layout(Arrow(start=OpenHead(line_width=1), x_start=0, y_start=1, x_end=1, y_end=2, line_width=10))

show(p)
```

generates

screen shot 2017-01-09 at 7 36 41 pm

### CODE REVIEW

**Comment by bryevdv** [comment]
@canavandl is there an existing arrows selenium image test we could update with some wide arrows too?

**Comment by canavandl** [comment]
There seems to be a faint line orthogonal to the arrow head on the examples with wide arrow bodies. I don't know if that's easily resolvable or not though.

screen shot 2017-01-11 at 11 35 25 am

**Comment by bryevdv** [comment]
@canavandl I think extending the clip region one or two pixels would immediately solve that, let me try

**Comment by bryevdv** [comment]
@canavandl that seems to work great, I am going to force push an update, here is the code that was added to the test:

```
    # test arrow body clipping
    plot.add_layout(Arrow(start=VeeHead(line_width=1, fill_color="white"), x_start=6, y_start=4, x_end=8, y_end=5, line_width=10))
    plot.add_layout(Arrow(start=NormalHead(line_width=1, fill_color="white"), x_start=6, y_start=3, x_end=8, y_end=4, line_width=10))
    plot.add_layout(Arrow(start=OpenHead(line_width=1), x_start=6, y_start=2, x_end=8, y_end=3, line_width=10))
```

**Comment by bryevdv** [comment]
Test updated, will merge when green

**Pull request merged**
