### PR TITLE
2572 resources default cdn

### LINKED ISSUE #2572: output_notebook resources
I use gist frequently to share notebooks, code and ideas.  ``output_notebook`` uses ``INLINE`` Resources as a default and it creates an enormous file.  Files that are too large in a Gist will require the files to be edited locally and pushed to the Gist repository.

After some digging, I found how to use the ``CDN`` to render the notebooks.  Using the ``CDN`` Resource reduces the file size so that the gist can still be edited online.  

This [Gist](https://gist.github.com/tonyfast/fae0eacea79bbd28996d) describes this issue in a bit more detail.  But, ultimately the ``CDN`` reduces the file size by an order of magnitude for this particular example.

It might be valuable to consider a different default mode for the ``output_notebook`` method or at least provide a warning or message that there is a way to reduce the file size.

### PR DESCRIPTION
**Pull request by Maggie-M**
issues: closes #2572

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap @damianavila I think this can be merged (into `dev_0.10`) after one or both of you review it.

**Comment by damianavila** [comment]
There are some commits from the master branch that should not be included here... @Maggie-M I suggest only applied your changes over the dev_0.10 branch (you can do it in multiple ways, maybe the more straightforward is cherry-pick your commit into a new dev_0.10-based branch...

**Comment by bryevdv** [comment]
@damianavila I think this can just be merged as-is now? Not sure why GH is showing some of those commits, they are all in master now too afaik.

**Comment by damianavila** [comment]
This is pointing against the dev_0.10 branch... this PR should be closed as superseded and create a new one against master...

**Comment by bryevdv** [comment]
let's delete the branch after the new one is made

**Comment by damianavila** [comment]
yep... sorry about that...

**Pull request closed without merging**
