### PR TITLE
Fixed name collision in ion_range_slider example

### LINKED ISSUE #7849: IonRangeSlider example fails when adding more than one slider.
Using the code as specified in https://bokeh.pydata.org/en/latest/docs/user_guide/extensions_gallery/widget.html#userguide-extensions-examples-widget. The local variable 'input' overwrites the 'input' from core/dom if more than one IonRangeSlider is added. For example:

``` Python
ion_range_slider = IonRangeSlider(start=0.01, end=0.99, step=0.01, range=(min(x), max(x)),
    title='Ion Range Slider - Range', callback=callback_ion, callback_policy='continuous')
ion_range_slider2 = IonRangeSlider(start=0.01, end=0.99, step=0.01, range=(min(x), max(x)),
    title='Ion Range Slider - Range', callback=callback_ion, callback_policy='continuous')
```
Raises:
``` console
Error rendering Bokeh items  TypeError: dom_1.input is not a function
    at IonRangeSliderView.exports.IonRangeSliderView.IonRangeSliderView.template (ionrangeslider:68478)
    at IonRangeSliderView.exports.IonRangeSliderView.IonRangeSliderView.initialize (ionrangeslider:68498)
    at IonRangeSliderView.View [as constructor] (ionrangeslider:9175)
    at IonRangeSliderView.DOMView [as constructor] (ionrangeslider:3839)
    at IonRangeSliderView.LayoutDOMView [as constructor] (ionrangeslider:21889)
    at IonRangeSliderView.WidgetView [as constructor] (ionrangeslider:49492)
    at IonRangeSliderView.InputWidgetView [as constructor] (ionrangeslider:48486)
    at new IonRangeSliderView (ionrangeslider:68460)
    at Object.build_views (ionrangeslider:3636)
    at WidgetBoxView.LayoutDOMView.build_child_views (ionrangeslider:22073)
```

bokeh == 0.12.15
python == 3.6.5
browser == google chrome Version 64.0.3282.119 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by Karel-van-de-Plassche**
- [x] issues: fixes #7849
- [x] tests added / passed
- [x] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
Thanks for the PR @Karel-van-de-Plassche! 

@mattpap  I think converting this to TypeScript would allow for the correct scoping to leave the name as is? However, I am OK with this quick fix until the example can be ported. Do you have any objection?

**Comment by Karel-van-de-Plassche** [comment]
Maybe this needs its own issue, but are there any plans to 'officially' support IonRangeSlider? I'd add my voice to making this the default slider, as per https://github.com/bokeh/bokeh/issues/7788. Unfortunately I'm not a JS dev, otherwise I'd have a stab at it.. Might have a go at it either way ;) Right now I just use my own IonRangeSlider implementation exposing more features that I keep semi-up-to-date at https://github.com/Karel-van-de-Plassche/bokeh_ion_range_slider.

**Comment by mattpap** [comment]
> I think converting this to TypeScript would allow for the correct scoping to leave the name as is? However, I am OK with this quick fix until the example can be ported. Do you have any objection?

It would, however we need to test that coffeescript works in custom models, as long as we support it. So I'm fine with this change.

**Comment by mattpap** [comment]
> Maybe this needs its own issue, but are there any plans to 'officially' support IonRangeSlider?

What are the benefits of IonRangeSlider over range sliders we have implemented in bokeh (based on noUiSlider)? It is more likely that we would implement missing features, rather than add another implementation. Additionally, IonRangeSlider depends on jquery, which makes it a very unlikely candidate for becoming a part of bokehjs.

**Comment by bryevdv** [comment]
I would say ionRangeSlider is definitely a better slider in almost all respects than noUiSlider, in terms of appearance, configurability, and features, with the sole exception of lacking a vertical orientation. Unfortunately I don't really think we can replace it as the default slider at this point, but I would not be against adding at as another optional bundle so that users don't have to resort to copy and pasting a custom extension just to use it.

**Comment by Karel-van-de-Plassche** [comment]
To be honest I have not looked at it for a while (pre bokeh 0.12.5). The feature I missed in an older version were discrete values, custom strings as labels, formatting of numbers in labels and ticks. I don't know how much can be done in the current bokeh slider. Also, I think the IonRangeSlider looks way nicer, but maybe this can be achieved with a skin.

**Comment by Karel-van-de-Plassche** [comment]
> but I would not be against adding at as another optional bundle
I would be happy to supporting this as a bundle, I'll read up on the developer notes tomorrow.

**Comment by bryevdv** [comment]
@Karel-van-de-Plassche I doubt there is much by way of documentation on this, it's somewhat tied to our build/release process which has mostly only involved a couple of people. That said perhaps this is an opportunity to improve the dev docs. In terms of previous models, you can look to how the bokeh tables widgets bundle was split off.

**Comment by bryevdv** [comment]
Well, that happened in this PR, which was unfortunately rather large, but individual commits may point to how it worked to split things up: https://github.com/bokeh/bokeh/pull/6335

**Comment by mattpap** [comment]
If anything, this may be a good opportunity to figure out **reusable** custom models. So far we only focused to provide support for custom models at all, for individual use. To get started with that, one would have to move the custom model code to a new repository, rewrite the code in TypeScript (otherwise maintenance burden would be to high), setup CI, and we will see then what else needs to be done (implementation- or process-wise). As long as this bundle isn't a core bokehjs bundle, then the dependency on jquery doesn't have to be that strict, although the approach we use in bokeh-tables is still preferred.

**Pull request merged**
