### PR TITLE
Add color palettes to improve usability

### PR DESCRIPTION
**Pull request by karen-poon**
My friend @noraSSH and I have added 2 new color palettes which can make Bokeh more usable for people with color vision deficiencies.

We named them as `ColorblindCalm` and `ColorblindNature`. Our inspiration came from https://medium.com/cafe-pixo/inclusive-color-palettes-for-the-web-bbfe8cf2410e Palette 2 and 3. The website also showed how they would look like under 8 different types of blindness deficiencies: protanopia, protanomaly, deuteranopia, deuteranomaly, tritanopia, tritanomaly, achromatopsia, and achromatomaly.

We have also added 2 examples that would use these 2 new color palettes respectively.

 `examples/plotting/file/bar_colorblindcalm.py`:

 `examples/plotting/file/bar_colorblindnature.py`:

- [x] issues: addresses #11481

### CODE REVIEW

**Comment by bryevdv** [comment]
Hi @karen-poon thanks for the PR, I am very excited about getting some new and better (and better sourced) accessible palettes. I do think there is some related other work around this that would be best to ideally handled all at once, so let me just lay out all that I think about this, and you let us know what you think about continuing on them based on your availability to continue more on this. 

#### Related issues

* https://github.com/bokeh/bokeh/issues/11170
* https://github.com/bokeh/bokeh/issues/10974

#### Provenance

Are these new palettes directly from Allie's Blog post? If so, can you try to reach out to Allie and clarify what license these are under? All recent palettes in [`palettes.py`](https://github.com/bokeh/bokeh/blob/branch-3.0/bokeh/palettes.py) have a license statement in a comment at the top. We should make sure any new palettes going forward have such. 

#### Naming

Where did the names for these palettes come from? We have had more creative names for themes, since themes are by and large expressions of aesthetic preference. But all our existing palettes have very utilitarian and descriptive names. Unless these are names that are published somewhere and well-known, I think we should stick to more "boring" names to be consistent with other palettes (and to reduce the need to interpret english concepts in order to find the palettes). I also think we should decide on a naming scheme that could also be expanded in the future with new palettes in a natural and obvious way. 

Also is "colorblind" the best term here? (It may very well be&mdash;I am genuinely asking). We have used "Usability" in some places, I think perhaps my personal preference might be "Accessible Palettes" but OTOH "colorblind" is also very specific and searchable so maybe that is the best. cc @tcmetzger 

#### Grouping

We might want to consider creating a "Palette Group" e.g. as for the Brewer palettes

#### Documentation

We will need to update the docstring at the top of [`palettes.py`](https://github.com/bokeh/bokeh/blob/branch-3.0/bokeh/palettes.py) with information about these. The current section for [Usability Palettes](https://docs.bokeh.org/en/latest/docs/reference/palettes.html#usability-palettes) is very thread bare. We need all the following:

* ALl the new palettes should display there (using our `bokeh.sphinxext` directives for displaying palettes)
* Each palette should inculde the simulation/analsyis images i.e. same as in the blog (I think the tool is called Stark?)
* Maybe change the section name? e.g. "Accessible Palettes" or "Colorblind Palettes"
* Decide what to do with the old palettes there (see below)
* The section should link to the blog and other sources regarding accessible palette design

#### Existing palette

There is currently one colorblind palette. As mentioned #11170 is has very little provenance  information. If we are expanding the number of colorblind palettes, we need to decide what to do with this old palette so that everything can be consistent. I think the options are:

* Keep it &mdash; Need to rename to consistent with whatever general naming scheme we decided to use for accessible palettes. At a minimum a simulation/analysis should be added for it and a note that links to the page it came from (http://jfly.iam.u-tokyo.ac.jp/color/) 
* Delete it &mdash; Upcoming 3.0 release is a good place for breaking changes, could just add new palettes and discard the current one.

Either way, we could add a module `__getattr__` that prints an actionable error if anyone imports the old name.

#### Examples

We have a *lot* of bar examples already. I don't think we need to add two new bar examples just to demo these palettes, especially since the palettes will be displayed in the `bokeh.palettes` reference (see above). I would suggest to remove those, and instead, start some of the work described in #10974 Specifically, I think it would be even better to take some of the more prominent examples in the docs and gallery, and update them to use these new palettes. 

---

That may seem like a lot but I think it's mostly small individual tasks, and are happy to help along the way. But please let us know what level of continued work you are able to work on yourself, and we can adjust accordingly. 

cc @bokeh/dev @tcmetzger

**Comment by bryevdv** [comment]
Also, re: CI faillures, I think another merge/rebase will bring in the fix for those, and get things green again.

**Comment by tcmetzger** [comment]
@karen-poon Thank you for this contribution, I'm very much looking forward to this! 
@bryevdv I think "color blindness" makes sense to use (I'm happy to be corrected in case there is a better word). It would be great if we could also mention "Accessible Palettes" or "Accessibility" in the context of this. I'd like to avoid things like "color-blind palettes" because that would sound like the palettes themselves are color blind.

**Comment by mattpap** [comment]
If we're going to proceed with this, bokehjs' palettes need to be updated as well.

**Comment by ianthomas23** [comment]
I am very much in favour of adding more colorblind friendly palettes, but I would rather not have palettes taken from a blog post, or ones that are restricted to length 6.

I use Paul Tol's palettes (https://personal.sron.nl/~pault/, https://personal.sron.nl/~pault/data/colourschemes.pdf) where possible. There are many different palettes, of differing lengths, under 3-clause BSD license. They are available in R (https://cran.r-project.org/web/packages/khroma/vignettes/tol.html) so becoming known.

The website seems a better reference than a blog post, but not as good as a full academic reference. But I am not in a position to ascertain how appropriate they really are, and adding them would be a lot more work than this PR so far.

**Comment by karen-poon** [comment]
Thank you for reviewing my PR and thank you for everyone's comments! I am very happy to be involved in making Bokeh more usable.

First of all, thank you for bringing licensing up. I have been trying to contact the author of the blog but wasn't successful. I do agree with @ianthomas23, it might be better to use a reference from a more credible source. Please let me know if the team wants a full academic research reference or if Paul Tol's palettes are sufficient. I would like to cite and use a better reference in the documentations either way.

I agree with @tcmetzger that that the word `colorblind` might sound like the palettes themselves are colour blind. Originally, we created our own names by preserving the word "colorblind" and added something creative behind it, just because we didn't want to change "colorblind" into something else without your permission. I am down to change them to something more "boring", and use words like `accessible` instead. I think that having a naming scheme will be a great idea as we will be adding more palettes in the future. 

Regarding the examples, I am happy to remove our examples and change some of the existing ones to use colour blind friendly palettes (maybe not all, since I think some people might still like to see palettes like Spectral as an example?). I think that we should agree on 1) a naming convention and 2) how credible we want for the colour palettes before we make any changes.

@bryevdv I would love to help with adding more credible palettes, updating the documentations, and changing more prominent examples into using the colour blind friendly palettes once the team has made a more solid decision on the 2 items I mentioned above :)

**Comment by bryevdv** [comment]
@karen-poon I think adding the Paul Tol palettes would be fantastic. They have a clear license, and a bit more concrete documentation that can be cited. Also the fact that they have been ported to and R package is very favorable as well. That seems "credible enough" (at least for me). We could do a quick search of academic literature to see if anyone has referenced or commented on these palettes (cc @jbednar for thoughts)

I think if we want to the extra step and make these a gold standard reference in the docs, we could run all the palettes we add through the simulation tool ourselves, and include those comparison images in our own docs. 

As for naming, here is an about suggestion that mirrors how the brewer palettes are currently handled:
```
TolBright  = { 3: TolBright3, 4: TolBright4, ... }
TolHighContrast = {....}
TolVibrant = {...}

colorblind = {
    "TolBright": TolBright,
    "TolVibrant": TolVibrant,
    ....
}
```

It think Tol's  descriptive names are OK but I also think they are general enough that it's still good to keep a prefix like `Tol` in front. If we add new accessible palettes in the future, they can have their own individual scheme that makes sense, but all colorblind palettes will go in the `colorblind` dict property, which is how they can be grouped overall. 

Thoughts? cc @tcmetzger 



Thanks also for the pointer to these palettes @ianthomas23

**Comment by bryevdv** [comment]
@ianthomas23 actually regarding the license for the Tol palettes, can you point to it? I did not see the BSD licensing you mentioned.

**Comment by ianthomas23** [comment]
@bryevdv The license is at the top of the python code (https://personal.sron.nl/~pault/data/tol_colors.py) that is linked to from the "Schemes Python Code" near the top of the web page. I suppose that strictly speaking this means the code is BSD licensed rather than the palettes themselves. But if our code is derived from Tol's code and we visibly repeat the license I assume that would be acceptable.

**Comment by jbednar** [comment]
Personally, I'd push for colormaps to be made available in a library-independent way so that people can choose their tool independently of their colormap (e.g. when collaborating between people using different tools). Unfortunately, these colormaps aren't suitable for my colorcet package, which focuses on perceptually derived maps (with colors either optimally spaced for continuous perception or optimally separated for discriminability). They'd be suitable for https://github.com/pyviz/contrib_colormaps , which @jsignell started a couple of years back but has yet to attract any contributions. Your call; at least if they are in Bokeh they'll definitely get users...

BTW, colorcet has a `rainbow` map already, so I'd vote against using that name here.

**Comment by bryevdv** [comment]
> I'd push for colormaps to be made available in a library-independent way so that people can choose their tool independently of their colormap

@jbednar I would agree in principle, but I don't currently have the bandwidth or stamina for the inter-project collaboration that would be required, unfortunately. I do think this is an important priority, and especially a good to launch for 3.0, so I'm OK with adding these directly to Bokeh

 > BTW, colorcet has a rainbow map already, so I'd vote against using that name here.

We could use `TolRainbow` here, even if we don't prefix all the others. Though I think the inherent package namespacing makes it somewhat less of a concern.

**Comment by ianthomas23** [comment]
I lean towards the non-prefixed names, so `Bright` rather than `TolBright`. I think this implies a bit more of "we've made the decision for you, use these" rather than "we're open to adding many more like these in the future".

**Comment by bryevdv** [comment]
@ianthomas23 I think I agree, in any was we can start with that. @karen-poon do you want to switch this existing PR add the Tol palettes? Or would you prefer to close this PS and open a new separate PR?

**Comment by karen-poon** [comment]
@bryevdv I'm good to close this and open a new one for adding the Tol palettes :)

**Pull request closed without merging**
