### PR TITLE
Update to Bokeh example plot: accessible palette

### PR DESCRIPTION
**Pull request by Soot3**
updated color bar example from viridis palette to iridescent to make it a more accessible plot

- [ ] issues: #11481

### CODE REVIEW

**Comment by bryevdv** [comment]
@Soot3 I am not sure this example needs updating. The viridis colormap was designed especially to be the new default colormap for Matplotlib, and I believe quite a bit of effort went in to making sure it was distinguishable across a variety of color deficiencies. One overview:

https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html

> These color maps are designed to be:
> 
> * Colorful, spanning as wide a palette as possible so as to make differences easy to see,
> * Perceptually uniform, meaning that values close to each other have similar-appearing colors and values far away from each other have more different-appearing colors, consistently across the range of values,
> * Robust to colorblindness, so that the above properties hold true for people with common forms of colorblindness, as well as in grey scale printing

**Comment by bryevdv** [comment]
@tcmetzger I guess this is actually an interesting docs question: The viridis palette is considered accessible AFAIK, but it is listed under "Matplotlib Palettes" because that is where it was sourced from. What should we do here? We could duplicate the relevant palettes under "Accessible palettes" or just add a note with links to specific accessible palettes from other sections.

**Comment by Soot3** [comment]
Yeah. I have been looking through the docs since then and the d3 and colorbrewer styles in the gallery were not particularly "inaccessible" as well

**Comment by bryevdv** [comment]
@Soot3 I'd like to go ahead and close this PR and leave viridis in place since it should already be acceptable as it is. If you are looking for another example then I think this one:

https://docs.bokeh.org/en/latest/docs/examples/basic/bars/pandas_groupby_nested.html

could use some attention, since the "Spectral5" colors are probably not distinguishable under various conditions. 

I will open a separate discussion about the palette docs organization!

**Comment by Soot3** [comment]
Okay thanks. I'll get on that today

**Pull request closed without merging**
