### PR TITLE
Enable examples by default, but keep the possibility to disable by commit.

### LINKED ISSUE #3019: restore examples tests on travisci as default action
In order to speed up TravisCI we disabled running examples tests by default (see #2934 ) because it was the big bottleneck and we don't really need to run those on every commit.

The drawback is that we don't run examples test at all now so the chances to have broken examples being merged on master is quite high ATM. That's actually what happened with #2986 

I propose to:

* restore examples tests running by default
* work on the examples cleanup to reduce time and verbosity
* have a [ci disable examples] magic to disable these tests (useful in the middle of a PR when you want a rapid iteration)

### PR DESCRIPTION
**Pull request by damianavila**
Closes #3019

### CODE REVIEW

**Comment by damianavila** [comment]
ping @bokeh/core... because every dev should know about this change...

**Comment by birdsarah** [comment]
This looks like it's working great. I did a test on #3098. 

Really happy to have the option to turn off examples. Seems like it doesn't matter if people forget and the examples run when we're in a normal state, but when we're pushing hotfixes close to a freeze then the option to disable things should really speed things up.

**Comment by damianavila** [comment]
OK, merging this one now...

**Comment by fpliger** [comment]
great! thanks @damianavila

**Pull request merged**
