### PR TITLE
added new Reset event

### PR DESCRIPTION
**Pull request by nleclercq**
See bokeh issue #6876

### CODE REVIEW

**Comment by bryevdv** [comment]
FYI @nleclercq I pushed a small change to remove some trailing whitespace (linter check was failing)

**Comment by bryevdv** [comment]
@nleclercq The problem is that the trigger line needs to be this:
```
@plot_model.plot.trigger_event(new Reset())
```
the `plot_model` is actually a `PlotCanvas` not a `Plot` due to uninteresting historical reasons. If you pull (to get my whitespace change) then make that change and push, we can get this merged.

**Comment by nleclercq** [comment]
Thanks Bryan. The `Reset` event works now. Anything else to do for this new feature? You wrote : 

> It would probably be useful to report the updated plot ranges in the Reset event as well

Hum... I'm not sure to understand what it means exactly cause I don't see which one of the existing events I could fire to announce the ranges update.

**Comment by bryevdv** [comment]
Thanks @nleclercq !

**Pull request merged**
