### PR TITLE
changed plot background/border_fill arg to FillProp mixin

### LINKED ISSUE #2021: Transparent background
It would be really nice to have the option for a transparent background (and border area) in the plots. Something like a background_alpha attribute for figure().

I'm sorry I cannot contribute to fix that :(

Thank you and congratulations for this excellent library!

### PR DESCRIPTION
**Pull request by canavandl**
issues: fixes #2021, #2951 

Change plot background_fill and border_fill argument to background_ and border_ FillProps mixins, so that plot and border area have settable color and alpha attributes.

Todo: Add deprecation warns (it's unclear to me how to add deprecation warns on class variables).

cc: @birdsarah @bryevdv

### CODE REVIEW

**Comment by bryevdv** [comment]
This PR will need documentation support in the User's Guide here: 

https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/user_guide/styling.rst

For a deprecation, there are a few possibilities, none of them very good. But these things would probably suffice:

* make `border_fill` and `background_fill` into r/w properties that read and set `border_fill_color` and `background_fill_color` respectively, but also emit a `warnings.warn` about deprecations

* in the `__init__` check for `border_fill` and `background_fill` manually. If present, remove them from **kwargs** (before the call to `super`) and set the properties (so the warning fires)

* however, also check that e.g., `border_fill` and `border_fill_color` are not *both* in `kwargs`. If they are, do something... warn and use one? error?

**Comment by canavandl** [comment]
By "silence warns in sphinx build", I mean the examples use the new fill_prop spellings and don't raise the warns.

**Comment by bryevdv** [comment]
This LGTM. @mattpap any thoughts on attribute deprecation? The approach taken here was to mark them explicitly in `__deprecated_attributes__` and then the `HasProps` code will just punt to the normal `getattr`, with the idea that the deprecated attributes must define property getters/setters that warn and do whatever is appropriate. Maybe this could be automated a bit more somehow?

**Comment by bryevdv** [comment]
ping @havocp I'd like to merge this but I think your other PR that touches `HasProps` will conflict. Do you have any thoughts or preferences? Merge this first, merge the other first, suggestions on ho to handle deprecations, etc.

**Comment by havocp** [comment]
If I were going to do the work to merge both I'd merge the other one first because it looks much easier to rebase the smaller properties.py change here than to rebase the larger one.

**Comment by bryevdv** [comment]
@havocp OK I agree let's get your PR merged first.

**Comment by bryevdv** [comment]
@canavandl can you look at the merge conflicts now that the other branch is merged?

**Pull request merged**
