### PR TITLE
small fixups to make sphinx 1.5 work

### PR DESCRIPTION
**Pull request by bryevdv**
Sphinx 1.5 seems to more aggresively try to automatically create ref
targets. Two issues resulted in duplicate targets causing a build error

### CODE REVIEW

**Comment by bryevdv** [comment]
@bokeh/dev when this passes I will merge it. I will then merge some current small PRs that are only failing because of this. Larger/longer running PRs should merge this change into their branches.

**Comment by bryevdv** [comment]
another, second, different dependency change update on Travis is also now causing all BokehJS builds to fail

**Comment by bryevdv** [comment]
ping @mattpap any ideas? it seems to be a JS dependency

**Comment by bryevdv** [comment]
I can reproduce locally by blowing away `node_modules`. Manually running:
```
npm install source-map-support
``` fixes

**Comment by bryevdv** [comment]
Adding it to `packages.json` fixes the immediate problem so I will do that in this hotfix PR

**Comment by mattpap** [comment]
@bryevdv, it doesn't hurt to add it, though I would start from bumping typescript's version to `2.1.4`.

**Comment by bryevdv** [comment]
I'll leave that to you in another PR :) I need to get this merged so ~5 other PRs can go in.

**Comment by mattpap** [comment]
Sure.

**Pull request merged**
