### PR TITLE
Boilerplate for bokeh/command

### PR DESCRIPTION
**Pull request by HuntJSparra**
- [ ] issues: addresses part of #8207 
- [ ] tests added / passed

Adding/updating boilerplate in files under bokeh/command directory

### CODE REVIEW

**Comment by bryevdv** [comment]
here are the linter violations: 
```
E       AssertionError: Code quality issues:
E         File contains trailing whitespace: bokeh/command/subcommands/__init__.py, line 34.
E         File contains trailing whitespace: bokeh/command/subcommands/secret.py, line 51.
E         File does not end with a newline: bokeh/command/subcommands/tests/test_sampledata.py, line 77
E         File does not end with a newline: bokeh/command/tests/__init__.py, line 7
E         File starts with more than 1 empty line: bokeh/command/util.py, line 1
E       assert 5 == 0
E        +  where 5 = len(['File contains trailing whitespace: bokeh/command/subcommands/__init__.py, line 34.', 'File contains trailing whitesp...ne: bokeh/command/tests/__init__.py, line 7', 'File starts with more than 1 empty line: bokeh/command/util.py, line 1'])
```
FYI I like to set up a `pre-commit` hook that runs the linter before allowing a commit:

https://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html#git-hooks

**Comment by mattpap** [comment]
> FYI I like to set up a pre-commit hook that runs the linter before allowing a commit:

> E         File contains trailing whitespace: bokeh/command/subcommands/__init__.py, line 34.
> E         File contains trailing whitespace: bokeh/command/subcommands/secret.py, line 51.
> E         File does not end with a newline: bokeh/command/subcommands/tests/test_sampledata.py, line 77
> E         File does not end with a newline: bokeh/command/tests/__init__.py, line 7

At least those errors can (and should) be avoided by setting up code editor properly.

**Comment by HuntJSparra** [comment]
I will certainly get that set up my in as I should have already done. I just need to chase down a bug with argument conflicts in one environment and another bug with quality not catching errors in another.

**Comment by HuntJSparra** [comment]
@bryevdv 
The documents in the development build have already been updated to replace ``py.test -m quality`` with ``py.test -m codebase``

**Pull request merged**
