### PR TITLE
Use node compatible jsdom

### PR DESCRIPTION
**Pull request by mistakevin**
See issue https://github.com/bokeh/bokeh/issues/2629

### CODE REVIEW

**Comment by damianavila** [comment]
As I said in the issue, if you install gulp from the javascript channel, then io.js is installed and then jsdom should work ok...

**Comment by mistakevin** [comment]
Javascript developers feel more comfortable using a javascript package manager like npm to install their packages, and most already have gulp installed using npm. I'm willing to bet that javascript channel is little known (as it was to me) to new contributors. Shouldn't we try to mirror their environments as much as possible with our builds?

**Comment by damianavila** [comment]
I just merged a PR lidting the channels we are using: https://github.com/bokeh/bokeh/blob/master/conda.recipe/meta.yaml#L11

If we are getting rid of the javascript channel, we need to remove that line too...

Also, right now, id we are not installing io.js nor nodejs from conda, we are using the preinstalled version available via TravisCI, are we OK with that? @bryevdv @mattpap 
In fact, I guess I would like to control this via conda... but I don't have strong opinions yet...

**Comment by mistakevin** [comment]
Closing this in favor of https://github.com/bokeh/bokeh/pull/2696

**Pull request closed without merging**
