### PR TITLE
Updated colors of Mixed Plots

### PR DESCRIPTION
**Pull request by BhaswatiRoy**
ref: https://github.com/bokeh/bokeh/issues/11481

1. Improved color accessibility by replacing primary colors with the "TolYlOrBr" Color Palette with a contrast ratio of 7.76 : 1
2. Increased transparency(alpha) from 0.5 to 0.8
3. Added a border color Black to make the scatter markers noticeable to users.

image

Preview:

image

### CODE REVIEW

**Comment by BhaswatiRoy** [comment]
Some more color options I explored while going through the accessible color palettes section of the docs -

1. TolPRGn

image

2. MediumContrast

image

**Comment by bryevdv** [comment]
Hi @BhaswatiRoy thanks for you patience, I have been sick almost all the last two weeks. So, I have to admit, I have been pretty unpleased with this example for several reasons for a long time. I looked at your color choices, and also tried several of my own, and just did not really like any of the results. I decided to try some more drastic changes:

* similar hues, but lighter and darker
* thicker lines
* add markers to line

The current  version I got to is this:

```python
from bokeh.models import FactorRange
from bokeh.palettes import MediumContrast3
from bokeh.plotting import figure, show

quarters =("Q1", "Q2", "Q3", "Q4")

months = (
    ("Q1", "jan"), ("Q1", "feb"), ("Q1", "mar"),
    ("Q2", "apr"), ("Q2", "may"), ("Q2", "jun"),
    ("Q3", "jul"), ("Q3", "aug"), ("Q3", "sep"),
    ("Q4", "oct"), ("Q4", "nov"), ("Q4", "dec"),
)

mcolor, qcolor, _ = MediumContrast3

p = figure(x_range=FactorRange(*months), height=350, tools="",
           background_fill_color="#fafafa", toolbar_location=None)

monthly = [10, 13, 16, 9, 10, 8, 12, 13, 14, 14, 12, 16]
p.vbar(x=months, top=monthly, width=0.8, color=mcolor, alpha=0.8)

quarterly = [13, 9, 13, 14]
p.line(x=quarters, y=quarterly, color=qcolor, line_width=3)
p.circle(x=quarters, y=quarterly, size=10,
         line_color=qcolor, fill_color="white", line_width=3)

p.y_range.start = 0
p.x_range.range_padding = 0.1
p.xaxis.major_label_orientation = 1
p.xgrid.grid_line_color = None

show(p)
```

which looks like:

Screenshot 2023-04-09 at 18 19 52


What do you think? The contrast check is just above 4, which passes for large text and gui elements, so  think that is acceptable for us. 

I think I could be open to other similar-hue color pairings, so please feel free to suggest more. Or if you like this, please commit these changes, and generate new thumbnails!

**Comment by BhaswatiRoy** [comment]
Hello @bryevdv, I hope you're doing well now. 
Inspired by your idea of increasing the line size and including markers, I was wondering if we could add border colors to the bars like the following -

1. Muted5[4], Muted5[1]
image

2. TolPRGn4[2], TolPRGn4[3]
image

3. TolPRGn7[2], TolPRGn7[0]
image

**Comment by bryevdv** [comment]
Hi @BhaswatiRoy I like those, with just a tiny tweak to make the bar lines lighter:

Screenshot 2023-04-12 at 16 59 57

Here is the final code, what do you think?

```python
from bokeh.models import FactorRange
from bokeh.palettes import TolPRGn4
from bokeh.plotting import figure, show

quarters =("Q1", "Q2", "Q3", "Q4")

months = (
    ("Q1", "jan"), ("Q1", "feb"), ("Q1", "mar"),
    ("Q2", "apr"), ("Q2", "may"), ("Q2", "jun"),
    ("Q3", "jul"), ("Q3", "aug"), ("Q3", "sep"),
    ("Q4", "oct"), ("Q4", "nov"), ("Q4", "dec"),
)

fill_color, line_color = TolPRGn4[2:]

p = figure(x_range=FactorRange(*months), height=350, tools="",
           background_fill_color="#fafafa", toolbar_location=None)

monthly = [10, 13, 16, 9, 10, 8, 12, 13, 14, 14, 12, 16]
p.vbar(x=months, top=monthly, width=0.8,
       fill_color=fill_color, fill_alpha=0.8, line_color=line_color)

quarterly = [13, 9, 13, 14]
p.line(x=quarters, y=quarterly, color=line_color, line_width=3)
p.circle(x=quarters, y=quarterly, size=10,
         line_color=line_color, fill_color="white", line_width=3)

p.y_range.start = 0
p.x_range.range_padding = 0.1
p.xaxis.major_label_orientation = 1
p.xgrid.grid_line_color = None

show(p)
```

**Comment by BhaswatiRoy** [comment]
thanks, @bryevdv for the review and suggestions, I have made the changes.

**Comment by bryevdv** [comment]
Hi @BhaswatiRoy it looks like there was some errors in copying the code over
```
E         examples/basic/bars/mixed.py:13:28: F401 [*] `bokeh.palettes.TolYlOrBr4` imported but unused
E         examples/basic/bars/mixed.py:22:33: F821 Undefined name `months`
E         examples/basic/bars/mixed.py:26:10: F821 Undefined name `months`
E         examples/basic/bars/mixed.py:27:19: F821 Undefined name `fill_color`
E         examples/basic/bars/mixed.py:27:58: F821 Undefined name `line_color`
E         examples/basic/bars/mixed.py:30:10: F821 Undefined name `quarters`
E         examples/basic/bars/mixed.py:30:39: F821 Undefined name `line_color`
E         examples/basic/bars/mixed.py:31:12: F821 Undefined name `quarters`
E         examples/basic/bars/mixed.py:32:21: F821 Undefined name `line_color`
```
FYI under the checks above, any of the "codebase" jobs can be clicked on and scrolled down to the end to see the errors

**Comment by BhaswatiRoy** [comment]
Hello @bryevdv, yes there was some issue from my side, but I have fixed it now.

**Comment by bryevdv** [comment]
@BhaswatiRoy this plot is in the gallery, so we will need to also update the the thumbnails to match. I think you are familiar with that process from previous PRs but please let me know if I need to provide more context/guidance.

**Comment by BhaswatiRoy** [comment]
Hello @bryevdv, actually I got busy with college exams, which will end this week, so I will finish the remaining tasks within this week.

**Comment by pavithraes** [comment]
@BhaswatiRoy This PR looks close, would you be able to complete it? It'll be nice to get these updates merged. :)

**Comment by BhaswatiRoy** [comment]
> @BhaswatiRoy This PR looks close, would you be able to complete it? It'll be nice to get these updates merged. :)

Hello @pavithraes I have made the necessary changes.

**Review by bryevdv — APPROVED** [review]

**Pull request merged**
