### PR TITLE
Collect hotfixes and examples fixes for 0.10.0 release

### PR DESCRIPTION
**Pull request by damianavila**
Branch to collect hotfix and example fixes as well... use #2890 for docs fixes

### CODE REVIEW

**Comment by damianavila** [comment]
ping @bokeh/core

**Comment by mattpap** [comment]
@damianavila, where this workaround came from?

btw. +1 for attitude.

**Comment by damianavila** [comment]
> @damianavila, where this workaround came from?

Some investigation on packaging and discussion with people with experience dealing with setuptools. Some people were just "import setuptools" which "magically" injects the bdist_wheel if needed, but that's even worse that the present solution which I found as a suggestion is some random post in the web...

**Comment by bryevdv** [comment]
Another +1 for attitude. Maybe silly question: is this a problem with a particular new version of pip? Can we just pin the pip version?

**Comment by damianavila** [comment]
>Maybe silly question: is this a problem with a particular new version of pip? Can we just pin the pip version?

Seems to be something introduced some weeks/months ago and it seems they will stand their position, so I pinning is not a solution here...

**Pull request merged**
