### PR TITLE
Add flags for session expiration options

### LINKED ISSUE #3541: Add session expiration time options to `bokeh serve`
The Server class has 'check_unused_sessions_milliseconds', 'unused_session_lifetime_milliseconds', 'stats_log_frequency_milliseconds' but we don't have command line options to set these.

### PR DESCRIPTION
**Pull request by jbcrail**
This follows the pattern set by the keep-alive flag.

One caveat is that I assumed the unused session lifetime is positive. I found out that negative values or zero were both accepted. The other session options already checked for invalid integer values.

I didn't document the new flags in `bokeh/command/subcommands/serve.py`, nor did I add tests.

Fixes #3541

### CODE REVIEW

**Comment by bryevdv** [comment]
I've marked this WIP, @jbcrail also FYI every push kicks off TravisCI and that is something of a bottleneck for us now. Please take care to either batch updates and push less frequently, or pro-activately  stop any older builds that don't need to run because you've pushed something newer.

**Comment by bryevdv** [comment]
@jbcrail I noticed you did add docs. Is your intention to add tests when you actually implement session expiration checking? The server is one of the best-tested parts of Bokeh and we need to keep it that way.

**Comment by jbcrail** [comment]
@bryevdv I'm working on adding tests for session expiration checking, but it appears the implementation was done by @havocp in `BokehTornado.cleanup_sessions()`, which ultimately calls `ApplicationContext.cleanup_sessions()`.

For tests, is `bokeh/tests/test_client_server.py` the right place to test unused sessions? The keep-alive feature is tested there and seems like the logical place to start.

**Comment by havocp** [comment]
I'd test it in a similar way to keep alive, yep. Though I think that test would be something I should have done earlier more than strictly related to this PR. Still, it'd be appreciated! (and is probably wise if you are planning to use this feature :-) ... )

**Comment by bryevdv** [comment]
I think I just realized my disconnect with this PR. Are these Tornado parameters? Bokeh has its own Session concept (an object responsible for creating and servicing a Bokeh document for a tab) and this is the session that needs to be timed-out. @havocp can correct me if I am wrong but I think that means:

* deciding what constitutes a time out
* implementing a system to keep track of time since activity
* closing inactive sessions

That's what I was referring to when I said implementation work.

**Comment by havocp** [comment]
I already did all that I just never added command line options or tests :-) sneaky

**Comment by bryevdv** [comment]
Lovely @jbcrail can you resolve the merge conflict that that this may be merged? FYI we typically work of branches of the main repo when possible to make collaboration more efficient (e.g., I'd merge master in right quick, if I could)

**Pull request merged**
