### PR TITLE
Rewrite gloo in TypeScript and add it to bokehjs

### PR DESCRIPTION
**Pull request by mattpap**
I think that if we want to commit to improving the webgl backend, we need to stop treating its implementation as a blackbox. The first step towards this direction is to get rid of the nasty auto-generated code and replace it with something that can be actually read and modified. Thus this PR rewrites gloo auto-generated code with TypeScript and adds it to bokehjs (dropping the dependency on `@bokehjs/gloo2`). For now I just did a straight rewrite to modern ES and reasonably statically typed the code. I didn't do any attempts to simplify or improve the implementation otherwise.

### CODE REVIEW

**Comment by bryevdv** [comment]
>  we need to stop treating its implementation as a blackbox.

I agree with this 100% I have been diving into webgl to actually learn specifics and details. 

But we should discuss what eventual UX looks like for webgl too. It's fairly straighforward to write vertex and fragment shaders for markers. The fragment shader for line is already starting to get quite complicated. I *think* it would be fairly straightforward to create new shaders for all the "box" type glyphs. There are other glyphs that may require much more work.  Text is also a chore on webgl. I think the upshot is that we are going to have a hybrid situation where we render some things on a webgl canvas and then blit to to a final 2d canvas for the foreseeable future. I also think we will need to maintain canvas implementations of all renderers to support SVG output. 

Given all that, the questions in my mind are:

* just use webgl by default where possible, always? (and so fold the webgl bundle back into the main bundle, or maybe a new renderers bundle)
* how to improve the dev situation so that primary/fallback rendering is a cleaner integration. RIght now things are very bolted on and shunt of to separate wildly different codepaths at awkward points.

**Comment by bryevdv** [comment]
@mattpap if we are going to vendor this and take ownership we also might want to drop the "gloo" name

**Comment by mattpap** [comment]
>  if we are going to vendor this and take ownership we also might want to drop the "gloo" name

I dropped all references and also split up the code into multiple modules.

**Comment by mattpap** [comment]
> just use webgl by default where possible, always? (and so fold the webgl bundle back into the main bundle, or maybe a new renderers bundle)

I think that using webgl automatically when available and applicable (the cost of setting up a program and shaders may not be worth it for small data, but that needs to be benchmarked), is the best approach. This will give the right blend of flexibility and performance. I would just include the bundle (it's 50 kB after this PR, a 10kb reduction, with room for improvements, e.g. shader minification). However, at some point we want to may consider splitting off the rendering part of bokehjs into its own bundle. 

> how to improve the dev situation so that primary/fallback rendering is a cleaner integration. RIght now things are very "bolted on" and shunt of to separate wildly different codepaths at awkward points.

Not only this is awkward, but also causes design issues, because, for example in color mapping work, I needed access to masked indices, and those are not computed when webgl is used, because webgl backend does masking on its own. I'm not sure right now how to solve this in general, but I would like to have a closer integration in near future.

**Comment by bryevdv** [comment]
@mattpap Seeing this result for `line_compare.py` on Safari and Chrome on OSX

Screen Shot 2020-06-20 at 2 49 15 PM

With errors under `set_data`:
```
WebGL: INVALID_OPERATION: texSubImage2D: ArrayBufferView not big enough for request
texSubImage2D
```
Screen Shot 2020-06-20 at 2 53 32 PM

(Not seeing an issue on master)

**Comment by mattpap** [comment]
I will set up visual testing testing of various configurations in another PR.

**Comment by bryevdv** [comment]
@mattpap FYI in my continuing quest to find the right level of helper API for webgl for us a colleague pointed me at this: https://luma.gl/

It's only ~30kb minified and is still usable at a low level, but smooths over platform differences and issues, and also makes debugging much easier, e.g. pass `{debug: true}` to the context and then buffers on the GPU are inspectable with a simple `buf.getData`. That seems at least plausibly promising so I will take a look at it

**Pull request merged**
