### PR TITLE
Fix up unittests, replace INLINE with CDN as default resource

### LINKED ISSUE #2572: output_notebook resources
I use gist frequently to share notebooks, code and ideas.  ``output_notebook`` uses ``INLINE`` Resources as a default and it creates an enormous file.  Files that are too large in a Gist will require the files to be edited locally and pushed to the Gist repository.

After some digging, I found how to use the ``CDN`` to render the notebooks.  Using the ``CDN`` Resource reduces the file size so that the gist can still be edited online.  

This [Gist](https://gist.github.com/tonyfast/fae0eacea79bbd28996d) describes this issue in a bit more detail.  But, ultimately the ``CDN`` reduces the file size by an order of magnitude for this particular example.

It might be valuable to consider a different default mode for the ``output_notebook`` method or at least provide a warning or message that there is a way to reduce the file size.

### PR DESCRIPTION
**Pull request by Maggie-M**
issues: closes #2572

### CODE REVIEW

**Comment by damianavila** [comment]
LGTM

**Comment by bryevdv** [comment]
ping @birdsarah the only thing failing here appears to be the selenium test, I am not sure how to diagnose.

**Comment by birdsarah** [comment]
This is now passing, bur for the wrong reasons - it is skipping all the selenium tests. See fix in #2862 (this PR brought this to my attention, so thanks for that!) I have tested locally the fix that I have pushed and initially got the same failure and then resolved it with the switch to inline resources which is definitely what we'd want for testing.

Two options: 
1) merge #2862 into master which fixes the skipping issue, then merge master into the PR to ensure everything's working
2) merge this one and then #2862 - at some point something will break if I'm wrong on the fix.

----
Regarding this PR:

I have tested this locally and seems to work as expected. I have tested `output_notebook`, `output_file` and just a vanilla `save`. 

My question is what to do about examples:
 1. We can remove the comment  in the marriage example about using `mode='cdn'` - https://github.com/bokeh/bokeh/blob/master/examples/interactions/us_marriages_divorces/us_marriages_divorces_interactive.py#L23
 2. Should all the examples actually be using `mode='inline'`? When we're testing, do we want to be deferring to `cdn` or using local build. I know I use example when I'm developing to make sure things are working as expected and to try and make sure I haven't broken something - if they're pointing to cdn by default, this won't be so obvious. Also, given that we run our examples for testing on travis, surely that needs to be using inline so that its running against the particular local PR version of the JS.

**Comment by bryevdv** [comment]
@birdsarah those questions troubled me as well. I definitely don't want to add clutter to every single example. There is `BOKEH_RESOURCES` we may as devs simply have to have that set to `inline` all the time, and have the tests do that. Ping @bokeh/dev for ideas.

**Comment by damianavila** [comment]
>Two options: 
>1) merge #2862 into master which fixes the skipping issue, then merge master into the PR to ensure >everything's working
>2) merge this one and then #2862 - at some point something will break if I'm wrong on the fix.

Option 1

>My question is what to do about examples:
>We can remove the comment in the marriage example about using mode='cdn' - https://github.com/bokeh/bokeh/blob/master/examples/interactions/us_marriages_divorces/us_marriages_divorces_interactive.py#L23

Yep, we can remove it...

>Should all the examples actually be using mode='inline'? 

Yes, I think so...

**Comment by bryevdv** [comment]
> Yes, I think so...
 
I disagree. Examples are supposed to be examples of normal, standard usage. Apart from adding ugly clutter to 100+ files, it now makes them bad examples, demonstrating what users *shouldn't* normall do, instead of demonstrating what they *should* normally do. This is our problem to fix "behind the scenes".

**Comment by damianavila** [comment]
> This is our problem to fix "behind the scenes".

Yes, I read in a hurry... and misinterpreted the question... I agree that we need to fix this in out testing infrastructure...

**Comment by birdsarah** [comment]
> Apart from adding ugly clutter to 100+ files, it now makes them bad examples.

Agreed.

> I agree that we need to fix this in out testing infrastructure...

Yes - I think our examples folder is trying to serve too many masters. I have lots of thoughts about this :D  

> 1) merge #2862 into master which fixes the skipping issue,
> Option 1
Sorry I made #2862 more than a one-liner. I don't think its that hard to review though.

**Comment by damianavila** [comment]
>There is BOKEH_RESOURCES we may as devs simply have to have that set to inline all the time, and have the tests do that.

But, aren't we already supporting local BokehJS here: https://github.com/bokeh/bokeh/blob/master/tests/travis/test#L272

ping @mattpap

**Comment by bryevdv** [comment]
> But, aren't we already supporting local BokehJS here: https://github.com/bokeh/bokeh/blob/master/tests/travis/test#L272

Yes it looks like it, when the tests are run. My other point was about day to day dev, all devs will have to have `BOKEH_RESOURCES` set, basically all the time.

**Comment by birdsarah** [comment]
@damianavila - interesting. i have looked at one examples html and it was relative, but it didn't hold for the selenium tests - it defaulted to cdn.

**Comment by bryevdv** [comment]
I suddenly wonder if the default should not be `cdn` in built and distributed packages, and `inline` or `relative` in all other cases. Making it default to`cdn` everywhere, always presents some onerous burdens on devs that can lead easily to bad configurations/subtle problems.

**Comment by damianavila** [comment]
>Yes it looks like it, when the tests are run. My other point was about day to day dev, all devs will have to have BOKEH_RESOURCES set locally on the work machine, basically all the time.

Yes, we should add this to the devs documentation... in fact that part needs to be improved a lot... I plan to spent some time on that soon...

>@damianavila - interesting. i have looked at one examples html and it was relative, but it didn't hold for the selenium tests - it defaulted to cdn.

yes... the "relative" is "on" only for the examples we test on TravisCI...

**Comment by bryevdv** [comment]
@birdsarah that `make_env` function that sets `BOKEH_RESOURCES` is only used in the running of the  examples test.

**Comment by birdsarah** [comment]
perfect - that makes sense - thanks.

**Comment by bryevdv** [comment]
> Yes, we should add this to the devs documentation... in fact that part needs to be improved a lot... I plan to spent some time on that soon...

The problem is that then the only way to test any other configuration is to also set/change `BOKEH_RESOURCES` which I think is not reasonable. As a dev I want what I set in the code to be what happens in the common case, which implies a default for development that makes sense for development (`inline` or `relative`)

**Comment by damianavila** [comment]
> 1) merge #2862 into master which fixes the skipping issue, then merge master into the PR to ensure everything's working

#2862 was supersded by #2868 and now #2868 was merged... so I guess this branch should merge master to check everything is right...

**Comment by damianavila** [comment]
> This implies a need for a default for development that makes sense for development (inline or relative) I'd like thoughts on setting cdn as a default only in built packages. (i.e., defer to a bokeh._DEFAULT_RESOURCES) that is different inside a built/installed release.

This is interesting... you should open an issue for that... but I like the idea...

**Comment by mattpap** [comment]
> I suddenly wonder if the default should not be cdn in built and distributed packages (...)

That's something I could stand behind. Thought to note, travis-ci infrastructure (at least what I wrote) will just work (as already noted) and personally, I always use `BOKEH_DEV=true` for my daily work, so I have to issue this extra step anyway.

**Comment by bryevdv** [comment]
@damianavila if we are in agreement I'd rather update the original issue and continue work here, to be added later (`0.11`?) unless you think it is more important to merge this as-is for `0.10`

**Comment by birdsarah** [comment]
Just to note @bryevdv @Maggie-M that the selenium tests are now running and passing.

https://travis-ci.org/bokeh/bokeh/jobs/80834716#L1835

Thanks for your patience on this.

**Comment by birdsarah** [comment]
> if we are in agreement I'd rather update the original issue and continue work here, to be added later (0.11?) unless you think it is more important to merge this as-is for 0.10

i know this question wasn't for me :D but as a strong advocate of the original issue, I just wanted to say that I'd be fine with delaying this pr. I also want this to be clear and obvious for potential contributors and this isn't a bug fix.

**Comment by damianavila** [comment]
>@damianavila if we are in agreement I'd rather update the original issue and continue work here, to be added later (0.11?) unless you think it is more important to merge this as-is for 0.10

I am OK delaying this one if you want... as @birdsarah said, it is an improvement, not a bug-fix, so it can wait if necessary...

**Comment by bryevdv** [comment]
OK, this PR is currently has conflics, and will have even more with #2952 I think it will probably be easier to open a brand new PR after #2952 is merged.

**Comment by bryevdv** [comment]
Superseded by #3075

**Pull request closed without merging**
