### PR TITLE
Allow providing websocket origin if unix-socket is enabled

### LINKED ISSUE #12894: [BUG] Server does not allow websocket connection on unix socket
### Software versions

Bokeh 3.1.0dev5

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

When launching a bokeh server and binding it to a unix socket using the `--unix-socket` commandline argument I expect to be able to provide valid websocket origins because otherwise the `WSHandler` will reject my connection request. 

### Observed behavior

Current attempting to provide `--allow-websocket-origin` when also providing `--unix-socket` errors.

### Example code

```Python
bokeh serve app.py --unix-socket test.socket --allow-websocket-origin=myapp.philippjfr.com
```

### Stack traceback or browser console output

```
['address', 'allow_websocket_origin', 'ssl_certfile', 'ssl_keyfile', 'port'] args are not supported with a unix socket
```

At the same time if we try to connect to the websocket we get:

```
2023-03-03 17:46:45,429 Refusing websocket connection from Origin 'http://paneltest.xxxx.com';                       use --allow-websocket-origin=paneltest.xxxxx.com or set BOKEH_ALLOW_WS_ORIGIN=paneltest.xxxxx.com to permit this; currently we allow origins set()
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by philippjfr**
@gpjt would be great if you could test this.

- [ ] issues: fixes https://github.com/bokeh/bokeh/issues/12894
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by philippjfr** [comment]
@govinda18 I note you initially implemented unix-socket support (thank you btw!). Have you not run into issues when deploying it or did you work around this by bypassing the validation by setting the `BOKEH_WS_ORIGIN` environment variable?

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
@philippjfr I have approved modulo updating the one failing test:
```
FAILED tests/unit/bokeh/command/subcommands/test_serve.py::test_unix_socket_with_invalid_args - assert "['address', ...a unix socket" == "['address', ...a unix socket"
  - ['address', 'ssl_certfile', 'ssl_keyfile', 'port'] args are not supported with a unix socket
  + ['address', 'allow_websocket_origin', 'ssl_certfile', 'ssl_keyfile', 'port'] args are not supported with a unix socket
  ?            ++++++++++++++++++++++++++
===== 1 failed, 10141 passed, 9 skipped, 988 warnings in 191.73s (0:03:11) =====
``` 
Please feel free to merge when green..

For my own info can you provide an example of what sort of values are used in case of a unix socket? I wouldn't expect an IP address, so I am a little unsure about the usage.

**Comment by gpjt** [comment]
I'll chime in with some info about the origin values for the domain socket (and also to say that @philippjfr and I will be running a test of it separately, as he suggested above).

The specific case we're looking at is kind of complex, but stripped right down to the basics, we're running it behind an nginx proxy.  The nginx config uses `proxy_pass` to pass requests on to the server via a unix socket (let's say `/var/socket/myserver.sock`).  So let's say that we're serving `www.foo.com`; a page on that site that connects back using websockets will have on that connection request an origin of `www.foo.com`, so the server needs to be able to allow those connections despite the fact that it, itself, is listening on a unix socket.

**Comment by mattpap** [comment]
I fixed the failing unit test and will merge when tests pass.

**Comment by govinda18** [comment]
> @govinda18 I note you initially implemented unix-socket support (thank you btw!). Have you not run into issues when deploying it or did you work around this by bypassing the validation by setting the `BOKEH_WS_ORIGIN` environment variable?

Yes, I am using BOKEH_WS_ORIGIN to get around this. FWIW, our usecase is pretty much the same as that described by @gpjt, we primarily wanted a way to not allow anyone else to reach to the panel server directly as the host might be shared by multiple users. Thus, putting nginx in front helped by binding the server to a unix socket and setting proxy_pass. Finally, cname was set through the env variable.

**Pull request merged**
