### PR TITLE
Prevent header from hiding anchors in the documentation

### LINKED ISSUE #10103: [BUG] Using anchors in the API Reference hides the anchored element under the header
For example, try opening https://docs.bokeh.org/en/latest/docs/reference/models/callbacks.html#bokeh.models.callbacks.OpenURL

Expected behavior: the page is opened with `OpenURL` visible at the very top.
Actual behavior: the page is opened with `OpenURL` obscured by the header.

Related, although for regular headers and not for code: #9915

### PR DESCRIPTION
**Pull request by p-himik**
- [x] issues: fixes #10103
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
Ah thank you this has been bugging me recently but I always ran into it when I was pressed and forgot to make an issue

**Comment by bryevdv** [comment]
@p-himik this change obscures the version warning banner:

Screen Shot 2020-06-07 at 3 24 29 PM

setting the alpha to the `::before` selector lets it become visible. Does this seem like the quickest safe fix?

**Comment by bryevdv** [comment]
no nevermind that won't work since the link is still underneath and un-clickable

**Comment by bryevdv** [comment]
Also noticing the banner is not showing up at all on search results pages

**Comment by bryevdv** [comment]
More visual corruption in the dev guide:

Screen Shot 2020-06-07 at 4 48 01 PM

I'm going to go ahead and revert this change and re-open the issue for now

**Comment by p-himik** [comment]
@bryevdv I've found a better solution that fixes the "Getting Set Up" section. And fixing what you see on the "Reference" page requires one of:
- Just keep this reversed
- Patch Sphinx locally to create a wrapper for highlighted elements to exclude the pseudo-element
- Just disable highlighting for code-related anchords

What do you think? I personally lean towards the third option since we already skip highlighting anything that's not code and I think having the anchors positions fixed is more important than highlighting.

**Comment by bryevdv** [comment]
@p-himik I agree with you that the positioning is the most important thing, and tbh I have never loved the appearance of the highlighting anyway

**Comment by p-himik** [comment]
New PR: #10141

**Pull request merged**
