### PR TITLE
Changed second 0.11.1 to 0.12.0

### PR DESCRIPTION
**Pull request by cbcoutinho**
I haven't created the recreated the docs, but I think this fixes issue #4692

### CODE REVIEW

**Comment by bryevdv** [comment]
@cbcoutinho Thanks for the catch!

**Comment by bryevdv** [comment]
@cbcoutinho well, I accidentally hit the close button instead of the merge button, my apologies. It says the repo the PR came from is gone and won't let me re-open the PR to merge it. Would you like to submit a new PR? Again, my apologies, too little sleep the last few days...

**Comment by cbcoutinho** [comment]
Haha, don't worry about it. I should have probably not deleted my repo before it was merged.

**Comment by damianavila** [comment]
Superseded by #4700

**Pull request closed without merging**
