### PR TITLE
Work around various test stupidity

### PR DESCRIPTION
**Pull request by bryevdv**
ref: #7865

@mattpap this is a minimal PR that seems to get tests running again on mocha 4, I agree BokehJS unit tests need a top-to-bottom overhaul but that will have to be after this release.

### CODE REVIEW

**Comment by bryevdv** [comment]
Ok well now some later tests are failing on Travis due to edit variables (they don't fall locally)

**Comment by bryevdv** [comment]
OK changed to just restore the old mocha version. Unless you come up with some different fix I think you should merge this first thing in the morning. @mattpap

**Comment by bryevdv** [comment]
FFS this is back
```
     IOError: [Errno 9] Bad file descriptor
```

**Comment by bryevdv** [comment]
I guess we can skip that test on py2.7, it's not super important.

**Comment by bryevdv** [comment]
@mattpap any comments or should I merge this?

**Comment by mattpap** [comment]
Looks good (I mean it looks as good as it gets with the tooling at our disposal).

**Comment by mattpap** [comment]
Anyway, as I mentioned in the other PR, we should try out `--exit` with mocha 5 when proceeding with issue #7880 , because it seems like it should do the right thing.

**Comment by bryevdv** [comment]
I agree, and in fact I think `--exit` was the previous default, if I read the mocha issue thread correctly

**Pull request merged**
