### PR TITLE
Add gulp dev-build task for faster development

### PR DESCRIPTION
**Pull request by mattpap**
Add `gulp dev-build`, an equivalent to `gulp scripts:build styles:build` (no minification step).

### CODE REVIEW

**Comment by mattpap** [comment]
Stopped CI, no need for that (@damianavila, perhaps we could add a tag for this).

**Comment by bryevdv** [comment]
Should something be added to the dev guide?

**Comment by mattpap** [comment]
@bryevdv, done. Skipped CI as well.

**Comment by damianavila** [comment]
@mattpap you can skip the build if you add skip `[ci skip]` in your commit message... it is a feature from TravisCI machinery...

**Pull request merged**
