### PR TITLE
Add Callback to Tabs Widget

### PR DESCRIPTION
**Pull request by mistakevin**
includes PR https://github.com/bokeh/bokeh/pull/2648

### CODE REVIEW

**Comment by azjps** [comment]
Hi @mistakevin, I don't think setting the .active attribute in the python script updates the html view in this commit? But otherwise this looks a bit cleaner than my PR.

**Comment by mattpap** [comment]
Can't we just add `callback` at the root of the model tree and handle all cases at once? I know this is only one achievement instead of close to infinity, but we would avoid situation we have with property event listeners in bokehjs (some listen some don't, no one knows which are which). Or maybe there are good reasons I overlook to do this like it is done now?

**Comment by mistakevin** [comment]
@azjps PR #2648, I believe, directly resolves your issue. Can you test that one?

**Comment by mistakevin** [comment]
@azjps I see now the model on the front end was not listening for an `active` attribute change. Try again with this latest commit, but in your example add a callback to `obj.button2` like this
```python
button2_callback = Callback(args=dict(tabs=obj.tabs), code="""
    tabs.save({active: 2})
""")
obj.button2 = Button(label="Click here to change active tab to the third tab", callback=button2_callback)
```

**Comment by mistakevin** [comment]
@mattpap I also agree. That might want to go into it's own issue, since it would be a more widespread change.

**Comment by azjps** [comment]
Looks good. Although, let's also do a render in response to changes to the 'tabs' attribute?

**Comment by mistakevin** [comment]
We can just do a re-render on all changes to the tabs model

**Comment by azjps** [comment]
:+1: great. wasn't sure if you were trying to be more efficient by not re-creating DOM elements or something.

**Comment by canavandl** [comment]
LGTM

**Comment by birdsarah** [comment]
This'll be great fodder for a selenium test once that PR is in.

**Comment by damianavila** [comment]
OK, this LGTM too... since we have several positive views, let's get it merged now...

**Pull request merged**
