### PR TITLE
Resolve issues with headless Chromium 110

### PR DESCRIPTION
**Pull request by mattpap**
Chromium 110 comes with a new headless engine. This results in various incompatibilities that needed to be fixed, but also requires update of almost all baseline images and some `*.blf` files, because font rendering changed.

### CODE REVIEW

**Comment by bryevdv** [comment]
> font rendering changed.

Not be rendering titles, axes, etc in these, unless they are actively exercising such features, seems like it would save a huge amount of churn.

**Review by ianthomas23 — APPROVED** [review]
915 files changed; I am almost disappointed that it hasn't reached 1000!

**Comment by mattpap** [comment]
> 915 files changed; I am almost disappointed that it hasn't reached 1000!

I'm looking forward to having better test coverage.

**Comment by mattpap** [comment]
> Not be rendering titles, axes, etc in these, unless they are actively exercising such features, seems like it would save a huge amount of churn.

That can be done for some tests. However, it's not always about what's being tested in particular, but also being able to understand tests' output. This is where having labeled axes often helps. It's really little price to pay for what value we extract from those tests. Also, such massive and especially not asked for changes happen rarely. This change is fairly unique, as the entire headless engine was replaced.

**Pull request merged**
