### PR TITLE
Remove old deprecations

### LINKED ISSUE #5664: Remove old deprecations
Scale/scope TBD but several old deprecations can certainly be removed at this point.

### PR DESCRIPTION
**Pull request by mattpap**
- [x] removed deprecations since 0.11.x
- [x] removed deprecations since 0.12.0

fixes #5664

### CODE REVIEW

**Comment by mattpap** [comment]
@bryevdv, how far we want to go? Should 0.12.0 deprecations also be removed?

**Comment by bryevdv** [comment]
> how far we want to go? Should 0.12.0 deprecations also be removed?

I'm not opposed to removing at least some of them

**Comment by mattpap** [comment]
I'm not sure what's wrong, but integration tests are pretty much one big traceback. I restarted it several times with no change.

**Comment by bryevdv** [comment]
Looking at it, it seems to be some remote problem with selenium itself, but its hard to tell.

**Comment by bryevdv** [comment]
Not sure if I missed this before but this looks more like a real error:
```
INTERNALERROR> FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/bokeh/bokeh/tests/integration/annotations/screenshots/current__test_title__test_the_default_titles_settings_and_ensure_outside_any_axes.png'
```

**Comment by mattpap** [comment]
> INTERNALERROR> FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/bokeh/bokeh/tests/integration/annotations/screenshots/current__test_title__test_the_default_titles_settings_and_ensure_outside_any_axes.png'

I had enough with this testing "infrastructure". I had to modify tests and run them locally to learn that:
```
ValueError: expected an instance of type Title, got Title above - left of type str
```
is the underlying cause of integration test failure.

**Comment by bryevdv** [comment]
> . I had to modify tests and run them locally to learn that:

Thanks @mattpap that was the next step I was going to take today but you beat me to it. I will merge this now. 

Agreed (and @birdsarah agrees too) that Selenium does not "blow up" nicely, but AFAIK it's the best option available for testing interactions automatically, and has absolutely caught what would have been serious bugs before previous releases. Maybe there is some custom tooling we can add around it to make things more accessible in the reports?

**Comment by bryevdv** [comment]
@mattpap actually, will merge later today. I want to:

* add `MIGRATION` to the issue
* start and add the `0.12.5` release notes migration guide as part of this PR

**Comment by bryevdv** [comment]
Migration notes added, will merge when green

**Pull request merged**
