### PR TITLE
Streamline / modernize build system

### PR DESCRIPTION
**Pull request by bryevdv**
This PR:

* consolidates project information in `pyproject.toml`, removes `setup.cfg`  and `classifiers` (still need a hidden `.flake8` for now)
* removes `versioneer` in factor of [`setuptools-git-versioning`](https://setuptools-git-versioning.readthedocs.io/en/stable/index.html)
* removes `requirements.txt` (zero need AFAICT it just does a `pip install -e .`) 
* deletes most all of `setup.py` and removes `_setup_support.py`
* reverses conda build build process to do a repackage of the wheel

I tried other options for the conda recipe:

* `path` local source does not work, makes a copy of repo, and setuptools SCM version is not available
* `git_url` clone does not work because the clone does not have a built BokehJS
* `url` to an sdist very much should work but does not. Conda package ends up with `0.0.0` as the version. Running `pip install` in the sdist manually *does* work, so this is some conda-buld brokenness

we will also have to coordinate the version to the conda build via a an env var so the local wheel can be found, e.g. `VERSION=3.0.0.dev12 conda build ...`

We will ned to figure out what to do about `3.0.0devN` vs `3.0.0.devN`. The latter is technically the correct version but setuptools will auto-correct the former. So the python package reports the latter regardless, but that causes it to load a bad URL from CDN. We at least need to fix that up.

### CODE REVIEW

**Comment by bryevdv** [comment]
This is getting pretty close: 

* [ ] (5 tests) some issue w/ conda not found on windows
* [ ] (1 test)  sphinx bokeh-deps needs update to look at pyproject
* [ ] (3 tests) codebase tests can't load sampledata
* [ ] (1 test) screenshot JS mod resolution error in examples (cc @mattpap)
* [ ] CDN version format adjustment for dev/rc builds

**Comment by mattpap** [comment]
> (1 test) screenshot JS mod resolution error in examples 

Currently it doesn't work at all:
```
Error: Cannot find module '/usr/share/miniconda3/envs/bk-test/lib/python3.8/site-packages/bokeh/_testing/util/chrome_screenshot.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
```

**Comment by bryevdv** [comment]
@mattpap by 1 test I meant 1 test job. I saw that error on all the individual tests, I was hoping you might have some idea offhand. One thing that is different in the PR is that I forced the tests to use the installed package, not the source tree.

**Comment by mattpap** [comment]
`bokeh/_testing/util/chrome_screenshot.js` is not included in the package. Everything under `bokeh._testing` is except this one. So, why do we keep testing utilities under `bokeh._testing` and distribute it with bokeh? It seems to me having testing utilities under `tests/` would be more sensible and resolve the issue. Are there any technical reasons for the existing setup?

**Comment by bryevdv** [comment]
> bokeh/_testing/util/chrome_screenshot.js is not included in the package

Well, that's weird, since I did look in an installed package yesterday and it was there. Not sure if it was the wheel or the conda package that was installed, I'll just have to check both again. 

> Are there any technical reasons for the existing setup?

I don't know offhand. The test files need to import actual things, can they easily import from `tests` without python path gymnastics? I don't think `_testing` adds much weight to the package, but I am not opposed at all to moving it out if that can be accomplished. But there's already so much going on in this PR I don't really want to add trying to move that as well.

**Comment by bryevdv** [comment]
turns out the conda package install has never worked on windows:

https://github.com/bokeh/bokeh/runs/7865764908?check_suite_focus=true#step:3:1815

But because we ran tests on source tree (and because the sub-action did not hard fail for whatever reason) this was never noticed

**Comment by bryevdv** [comment]
@mattpap I may have a path to move `_testing` out of the package. That should lead to a fix for the codebase tests. I have no idea how your js loader interacts with or discovers arbitrary repo paths, however.

**Comment by bryevdv** [comment]
@bokeh/core I'd like to propose (again) getting rid of the top-level `environment.yml` file. I really think it is better to make users be explicit and choose a particular python version using one of the "test" files in the `ci` dir. It's one less thing for us to maintain, and if we need to ask a user with questions what they installed we will get more specific information back.

**Comment by bryevdv** [comment]
@mattpap do we actually need to save and unpack the built bokehjs anymore? I forget why we started but in this PR almost every test deletes the source tree entirely in order to force testing with the installed package. Do the examples tests need it for anything?

**Comment by mattpap** [comment]
> 'd like to propose (again) getting rid of the top-level environment.yml file.

Yeah, I'm not sure what's the purpose of that file. It seems like a dump of all dependencies: runtime, build, tests, and not up to date either. The only thing worth to consider is to move env files, at least those universally useful, under their own directory, say `envs/`, so that they aren't CI biased and could be referred to in docs, etc.

**Comment by bryevdv** [comment]
Current punchlist:
* [ ] CDN version format adjustment for dev/rc versions (.dev -> dev)
* [ ] setuptools command class to encapsulate BokehJS build
* [ ] remove built-bokehjs artifact if possible
* [ ] make deleting source optional to re-use setup action for codebase tests

>  under their own directory, say envs/, so that they aren't CI biased and could be referred to in docs, etc. 

I think this is worth considering especially if we move ci scripts under `scripts` but I will leave that for a future PR. I would be +1 to remove top level env file in this PR, though.

**Comment by mattpap** [comment]
> do we actually need to save and unpack the built bokehjs anymore?

I can see we upload the artifact (bokehjs-build), but I don't see it being unpacked anywhere. In any case, if I recall correctly, the artifact was added to allow investigating build differences in CI and locally, if any, but I don't recall ever taking advantage of this. It would also make more sense to have it in bokehjs-ci workflow, but I suppose this was done before that workflow existed. Thus I think it can be removed.

**Comment by mattpap** [comment]
> I would be +1 to remove top level env file in this PR, though.

I'm perfectly fine with removing it.

**Comment by bryevdv** [comment]
@abravalheri @pradyunsg I think this attempt at modernization is going to stick. In case you have a few cylcles to take a quick look, any advice on:
> setuptools command class to encapsulate BokehJS build

would really be appreciated. Currently `setup.py` ends with this:
```
bokehjs_action = build_or_install_bokehjs()

setup()

show_bokehjs(bokehjs_action)
```
where `build_or_install_bokehjs` consults the `BOKEHJS_ACTION` env var, and `show_bokehjs` prints out some stats and info about the JS build (file sizes, compile times, etc). I think these should be wrapped up in a command class and passed to `setup` instead? What is the best command class to inherit from at this point? Assume we can use the current latest setuptools as required min ver.

**Comment by abravalheri** [comment]
Hi @bryevdv, I believe that you can indeed convert `build_or_install_bokehjs` to a custom command, or add it directly to a specialised `build_py`/`build_ext` implementation.

I am not exactly sure about `install_js()` since now, with the implementation of PEP 660, the installation process should be completely out of the hands of setuptools (as long as you don't use `python setup.py develop`, which is advised). On the other hand you might not need to rely on `install_js()` since the build subcommand now has the means to [differentiate](https://setuptools.pypa.io/en/latest/userguide/extension.html#setuptools.command.build.SubCommand.editable_mode)  between a regular installation and an editable installation.

I have added some documentation in https://setuptools.pypa.io/en/latest/userguide/extension.html#supporting-sdists-and-editable-installs-in-build-sub-commands that covers the new capabilities and specificities for editable installs. Hopefully that can help you. During the weekend I might try to have a better look on this PR to see if I can provide some more specific advise.

**Comment by bryevdv** [comment]
@abravalheri we may have some terminology issues. The  "install" in `install_js` means copy it from the BokehJS build directry into the Python source tree. Then, actual installation (from Python's POV) is handled by the `graft` entires in `MANIFEST.in`. 

A `pip install .` of any sort should always "install" (copy) BokehJS into the source tree before processing the (Python) package build. But in case there is not already a BokehJS built, we need to do that step in addition, and it might take a few minutes. Whether or not to build BokehJS is controlled by the `BOKEHJS_ACTION` var. 

For completeness, I think all the cases are shown below (cc @tcmetzger) but please let me know if anything seems off. 

#### Non-editable install
```bash
# Build and use fresh BokehJS
pip install . 

# Use existing BokehJS without building
BOKEHJS_ACTION="install" pip install .
```

#### Editable install (editable for Python modules only)
```bash
# Build and use fresh BokehJS
pip install -e . 

# Use existing BokehJS without building
BOKEHJS_ACTION="install" pip install -e .
```

#### "Fully" editable install (editable for all files)
```bash
# Build and use fresh BokehJS
pip install -e . --config-settings editable_mode=compat

# Use existing BokehJS without building
BOKEHJS_ACTION="install" pip install -e . --config-settings editable_mode=compat
```

The last case would be useful for supporting a combined Python+JS editable workflow where a watch process continually built BokehJS and installed the result in the source tree automatically. But's also possible to use `bokeh serve` and `BOKEH_DEV` to use BokehJS resources from a local server instead, so maybe that is not so critical to promote.

**Comment by abravalheri** [comment]
Thank you very much for the in-depth explanation @bryevdv. Unfortunately I don't think I will have the chance to go through the code before the weekend and propose a concrete solution.

I have a question before I reach that point: is it correct to suppose that your objective is to do the following?
- Be able to run only once `python -m build` instead of twice, and have the javascript correctly included in the source distribution.

**Comment by bryevdv** [comment]
> Be able to run only once python -m build instead of twice, and have the javascript correctly included in the source distribution.

@abravalheri not exactly. When we build real packages, we build BokehJS manually with a `node make build` for reasons. I don't really care whether the sdist and wheel are built with one invocation or two, they *both* need to use the prebuilt BokehJS (so I would pass `BOKEHJS_ACTION="install"` to *any* `build` invocation in our actual release automation)

**Comment by bryevdv** [comment]
> Be able to run only once python -m build instead of twice, and have the javascript correctly included in the source distribution.

@abravalheri Sort of, but not exactly. When we build real release packages, we build BokehJS once with a  manual `node make build` for reasons. I don't really care whether the sdist and wheel are built with one invocation or two, they *both* need to use the prebuilt BokehJS (so I would pass `BOKEHJS_ACTION="install"` to *any* `build` invocation in our actual release automation)

**Comment by pradyunsg** [comment]
It's already been possible -- you can use cmdclass to add a build_js, and use https://github.com/jaraco/demo-custom/blob/main/setup.py#L4 to add the custom build step.

**Comment by abravalheri** [comment]
Yes, the information given by Pradyun is very relevant, you can create a custom build sub-commands in many ways, including the following:

```python
from setuptools import Command, setup
from setuptools.command.build import build

class CustomBuild(build):
   sub_commands = [("build_js", BuildJs), *build.sub_commands]

class BuildJs(Command):
    """See https://setuptools.pypa.io/en/latest/userguide/extension.html#supporting-sdists-and-editable-installs-in-build-sub-commands.
    If you list files in `get_source_files()` they should be automatically added to the sdist.
    """

setup(
    cmdclass={"build_js": BuildJs, "build": CustomBuild}
)
```

If you need to build files during the `sdist` phase, you can also create a `sdist` sub-command (but they are more limited and don't follow the same API documented for build subcommands), or overwrite the `sdist` subcommand itself.

**Comment by bryevdv** [comment]
@pradyunsg @abravalheri thank you both, I can work with that. One last quick question. Regarding:

> If you list files in `get_source_files()` they should be automatically added to the sdist.

Does that mean the `graft` statements in `MANIFEST.in` could be removed?

**Comment by abravalheri** [comment]
> Does that mean the graft statements in MANIFEST.in could be removed?

Yes, at least the ones that are redundant with the list returned by `get_source_files()` in your ***custom build*** sub-command 😄.

Please let me know if you find a problem.

**Comment by pradyunsg** [comment]
Thanks @abravalheri for filling in the blanks. You beat me to it -- I was waiting until I get hold of a laptop to post a similar code snippet. :P

**Comment by bryevdv** [comment]
@mattpap The tests are trying to access BokehJS from the build tree, but I am not sure why offhand (have not investigated yet, but if you have any quick ideas)
```
test_get_screenshot_as_png[chromium-dimensions0] failed (9 runs remaining out of 10).
	<class 'FileNotFoundError'>
	[Errno 2] No such file or directory: '/home/runner/work/bokeh/bokeh/bokeh/server/static/js/bokeh.min.js'
```

**Comment by bryevdv** [comment]
@abravalheri @pradyunsg when I try:
```python
class BuildJS(Command):
    def run(self) -> None:
        action = build_or_install_bokehjs()
        show_bokehjs(action)

class CustomBuild(build):
    sub_commands = [("build_js", BuildJS), *build.sub_commands]

setup(cmdclass={"build_js": BuildJS, "build": CustomBuild})
```
I get `  TypeError: dist must be a Distribution instance` from inside the `_distutils` that setuptools vendors.

<details>

```
dev-3.9 ❯ pip install . -vv
Using pip 22.2.2 from /Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip (python 3.9)
Non-user install because site-packages writeable
Created temporary directory: /private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-ephem-wheel-cache-467pdz_1
Created temporary directory: /private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-tracker-sixyvg0w
Initialized build tracking at /private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-tracker-sixyvg0w
Created build tracker: /private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-tracker-sixyvg0w
Entered build tracker: /private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-tracker-sixyvg0w
Created temporary directory: /private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-install-ch8_vn5v
Processing /Users/bryan/work/bokeh
  Added file:///Users/bryan/work/bokeh to build tracker '/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-tracker-sixyvg0w'
  Created temporary directory: /private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz
  Running command pip subprocess to install build dependencies
  Using pip 22.2.2 from /Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip (python 3.9)
  Collecting setuptools>=64
    Using cached setuptools-65.0.2-py3-none-any.whl (1.2 MB)
  Collecting setuptools-git-versioning
    Using cached setuptools_git_versioning-1.10.0-py3-none-any.whl (7.6 kB)
  Collecting colorama
    Using cached colorama-0.4.5-py2.py3-none-any.whl (16 kB)
  Collecting toml>=0.10.2
    Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
  Collecting packaging
    Using cached packaging-21.3-py3-none-any.whl (40 kB)
  Collecting pyparsing!=3.0.5,>=2.0.2
    Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
  Installing collected packages: toml, setuptools, pyparsing, colorama, packaging, setuptools-git-versioning
  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
  distributed 2021.7.0+764.g6765e6e9.dirty requires dask==2022.7.0, but you have dask 2021.7.0+646.gd6c08784 which is incompatible.
  distributed 2021.7.0+764.g6765e6e9.dirty requires tornado<6.2,>=6.0.3, but you have tornado 6.2 which is incompatible.
  Successfully installed colorama-0.4.5 packaging-21.3 pyparsing-3.0.9 setuptools-65.0.2 setuptools-git-versioning-1.10.0 toml-0.10.2
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  /private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/dist.py:530: UserWarning: Normalizing '3.0.0dev11+14.g3c5b3a6f.dirty' to '3.0.0.dev11+14.g3c5b3a6f.dirty'
    warnings.warn(tmpl.format(**locals()))
  /private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
    warnings.warn(msg, _BetaConfiguration)
  running egg_info
  writing bokeh.egg-info/PKG-INFO
  writing dependency_links to bokeh.egg-info/dependency_links.txt
  writing entry points to bokeh.egg-info/entry_points.txt
  writing requirements to bokeh.egg-info/requires.txt
  writing top-level names to bokeh.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 258, in <module>
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
      self.run_command(cmd)
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
      cmd_obj.run()
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 308, in run
      self.find_sources()
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 316, in find_sources
      mm.run()
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 560, in run
      self.add_defaults()
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 597, in add_defaults
      sdist.add_defaults(self)
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/command/sdist.py", line 107, in add_defaults
      self._add_defaults_build_sub_commands()
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/command/sdist.py", line 123, in _add_defaults_build_sub_commands
      missing_cmds = set(build.get_sub_commands()) - _ORIGINAL_SUBCOMMANDS
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/command/build.py", line 33, in get_sub_commands
      return super().get_sub_commands()
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 330, in get_sub_commands
      if method is None or method(self):
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 158, in __init__
      super().__init__(dist)
    File "/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-env-ybdb6cvz/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 59, in __init__
      raise TypeError("dist must be a Distribution instance")
  TypeError: dist must be a Distribution instance
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /Users/bryan/anaconda/envs/dev-3.9/bin/python /Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/tmp030f03sp
  cwd: /Users/bryan/work/bokeh
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Exception information:
Traceback (most recent call last):
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 524, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 68, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 118, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 95, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/utils/misc.py", line 685, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 172, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 322, in _call_hook
    self._subprocess_runner(
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 252, in runner
    call_subprocess(
  File "/Users/bryan/anaconda/envs/dev-3.9/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: Getting requirements to build wheel exited with 1
Remote version of pip: 22.2.2
Local version of pip:  22.2.2
Was pip installed by pip? True
Removed file:///Users/bryan/work/bokeh from build tracker '/private/var/folders/g7/86cypxt17kd122t5kg3g4rmw0000gn/T/pip-build-tracker-sixyvg0w'
Removed build tracker: '/private/var/folders/g7/86cypxt17kd122
```
</details>

**Comment by bryevdv** [comment]
cc @tcmetzger minimal docs updates in https://github.com/bokeh/bokeh/pull/12306/commits/6623e9a75728469f0145baefcc76c90588faebd0

**Comment by abravalheri** [comment]
Sorry, that was my mistake. I provided you the wrong code example. I thought that I knew it by heart at this point, but apparently I don't. 

```python
class CustomBuild(build):
    - sub_commands = [("build_js", BuildJS), *build.sub_commands]
    + sub_commands = [("build_js", None), *build.sub_commands]
```

The second element in the list is supposed to be (optionally) a predicate function that will determine whether or not the sub-command should run. The example in the link provided by Pradyun is more accurate.

I think you also need to implement a few other abstract methods of Command as well.

**Comment by bryevdv** [comment]
@abravalheri Thanks, that works like a charm! Last question I promise: I'd like the BokehJS build summary to be shown on a regular `pip install .` (it's too hard to locate int the middle with `-v`) Is there some setuptools logging api I can use instead of `print` to force that output to show up at the default verbosity level?

**Comment by abravalheri** [comment]
> I'd like the BokehJS build summary to be shown on a regular pip install . (it's too hard to locate int the middle with -v) Is there some setuptools logging api I can use instead of print to force that output to show up at the default verbosity level?

I am afraid this is not trivial... Setuptools is very verbose by default, and `pip` hides all the backend output if `-v` is not given.

The default logging level in `setuptools` can be changed with `pip install . --config-settings quiet=true` (or `python -m build -C--quiet`).

In theory you could mix things up: `pip -v install . --config-settings quiet=true`, but I don't know if that is going to give you what you want.

(With `quiet`, setuptools' logging level is set to `WARNING`).

**Comment by bryevdv** [comment]
@abravalheri I was afraid that might be the case. The output from `pip -v install . --config-settings quiet=true` is pretty much perfect, the invocation is just maybe a bit too verbose to put in our dev docs as a default

**Comment by bryevdv** [comment]
cc @bokeh/core anyone recall why we included unit tests in the package? It does not really make sense to me, so I have removed them for now. I haven't gotten any feedback or requests for time, so unless there is comment, I plan to merge this tomorrow morning PST so I can start testing and fixing up any issues with the release-build actions.

**Comment by mattpap** [comment]
> (...) why we included unit tests in the package?

I suppose this was common practice at the time, but given all the complexities of setting up a testing environment, I don't see the point in having those in the package.

**Pull request merged**
