### PR TITLE
Add support for copying canvas to clipboard

### PR DESCRIPTION
**Pull request by mattpap**
This is a fairly new API, primarily usable in Chromium-based browsers and most recent Safari. Firefox requires `dom.events.asyncClipboard.dataTransfer` flag to be enabled for it to work. The tool is available from save tool's context menu:

image

If the feature is not available, the menu item will not show (or entire menu if empty).

### CODE REVIEW

**Comment by adamwarlock** [comment]
Is it possible to get the copy to clipboard tool out of save tool's context menu as a separate tool ?

**Comment by bryevdv** [comment]
It's a non-trivial amount of overhead to add a new model, so unless there is alot of interest expressed from the community, I'd say its unlikely, especially since it is possible to add a `CustomAction` to the toolbar that executes JS code you provide (that could do the clipboard copy, e.g.)

**Comment by adamwarlock** [comment]
Can i display the icon for copy to clipboard tool next to save tool's icon or outside of the save tool's context menu?

**Comment by bryevdv** [comment]
@adamwarlock as this is not veered into support question territory, please move the discussion to the community discourse:

https://discourse.bokeh.org

**Pull request merged**
