### PR TITLE
Added flight app created for trial vm demo

### LINKED ISSUE #4115: Add app for flight delay data
This was created for the Anaconda Trial VM

### PR DESCRIPTION
**Pull request by birdsarah**
issues: closes #4115 
supersedes #3983 

@rafaelhbarros is opening this up for @bokeh/dev to help finish this off - especially with regards to the sample data stuff

### CODE REVIEW

**Comment by birdsarah** [comment]
There are comments on #3983 from @bryevdv and @birdsarah that should be incorporated

**Comment by bryevdv** [comment]
@rafaelhbarros can you answer the question about data provenance? We have to be assured we can redistribute the data

**Comment by rafaelhbarros** [comment]
The same data is being distributed with the trialvm demo, so I will take that as a yes. Let me verify yet again.

**Comment by rafaelhbarros** [comment]
We can use it based on this: https://www.transportation.gov/foia

and this: https://www.transportation.gov/web-policies/disclaimer

**Comment by bryevdv** [comment]
@bokeh/dev OK please review  There's definitely more improvements that can be made but I think this could be ok to merge now, and I can make issues outlining further improvements for the future.

**Comment by bryevdv** [comment]
Hrm, actually I guess we need to figure out what to do with the data first.

**Comment by bryevdv** [comment]
@birdsarah are there docs anywhere on how to upload to S3? If not maybe you can walk me through and we can write some up, I hate to keep asking you every time.

**Comment by birdsarah** [comment]
@bryevdv - I sent an email a while back - digging it up....

**Comment by birdsarah** [comment]
You need a continuum s3 account.

When you have this you should be able to login here: https://continuum.signin.aws.amazon.com/console

Then go to the `bokeh_data` bucket (https://console.aws.amazon.com/s3/home?region=us-east-1#&bucket=bokeh_data&prefix=)

Hit the blue upload button and upload the data.

Finally check the permissions are correct (same as all the other files in the bucket) by looking at it's permissions under the properties window.

**Comment by birdsarah** [comment]
> Hrm, actually I guess we need to figure out what to do with the data first. 

Yes, including adding an entry in `bokeh.sampledata`

**Comment by birdsarah** [comment]
Can I also suggest we just sample down / clean-up the data that's included in the upload so that we can skip this:

```diff
 +    # load airlines delays
+    airline_delays_df = pd.read_csv(os.path.join(os.path.dirname(__file__), 'data/airline_delay_causes.csv'))
+    airline_delays_df['period'] = airline_delays_df.apply(lambda row: datetime.date(month=row[' month'], year=row['year'], day=1), axis=1)
+    airline_delays_df = airline_delays_df[['period', 'airport', 'arr_flights', 'arr_del15', 'carrier_name']]
+
+    # load airport locations
+    adf = pd.read_csv(os.path.join(os.path.dirname(__file__), 'data/airports.csv'))
+    adf = adf[adf['country'] == 'United States'][['iata/faa', 'latitude', 'longitude', 'name']]
+    adf = adf[(adf.longitude < max_long) & (adf.longitude > min_long)]
+    adf.set_index('iata/faa', inplace=True)
```

**Comment by bryevdv** [comment]
I'm actually now -1 on adding this until there is better date widget support

**Pull request closed without merging**
