### PR TITLE
Fix app/spectrogram example

### LINKED ISSUE #7230: Spectrogram example image broken
Extension needs an update:

screen shot 2017-11-17 at 10 19 22

which means there may be a migration note needed?

cc @mattpap

### PR DESCRIPTION
**Pull request by mattpap**
fixes #7230

### CODE REVIEW

**Comment by bryevdv** [comment]
This is what I am seeing:

screen shot 2017-11-17 at 12 34 59

Thats what I saw after making the same change (it didn't work at all before the change)

**Comment by bryevdv** [comment]
This is after adding a pan tool and panning:

screen shot 2017-11-17 at 12 39 47

Not sure if it is being squished or truncated (not the case that it was just flipped and mostly off screen tho)

**Comment by bryevdv** [comment]
It's getting squished. If I add `console.log(sx[i], sy, sw, sh)`

then I see a height of 5px:

screen shot 2017-11-17 at 12 51 54

**Comment by bryevdv** [comment]
This change:
```
diff --git a/examples/app/spectrogram/waterfall.coffee b/examples/app/spectrogram/waterfall.coffee
index f62e4cf4a..081f96e96 100644
--- a/examples/app/spectrogram/waterfall.coffee
+++ b/examples/app/spectrogram/waterfall.coffee
@@ -48,19 +48,15 @@ export class WaterfallRendererView extends RendererView
       @image[@tile][i*@model.tile_width+@col] = buf32[i]

     sx = @xscale.v_compute(@x)
-    sy = @yscale.compute(0)
+    sy = @yscale.compute(@max_freq)
     sw = Math.ceil(@xscale.compute(@model.tile_width) - @xscale.compute(0))
-    sh = Math.ceil(@yscale.compute(@max_freq))
+    sh = Math.floor(@yscale.compute(0))

     ctx.save()

     smoothing = ctx.getImageSmoothingEnabled()
     ctx.setImageSmoothingEnabled(false)

-    ctx.translate(0, sy)
-    ctx.scale(1, -1)
-    ctx.translate(0, -sy)
-
     for i in [0...sx.length]
       if i == @tile
         cctx = @canvas[i].getContext('2d')
@@ -69,10 +65,6 @@ export class WaterfallRendererView extends RendererView
         cctx.putImageData(image, 0, 0)
       ctx.drawImage(@canvas[i], sx[i], sy, sw, sh)
```
almost gets there:

screen shot 2017-11-17 at 13 11 09


The image is flipped but least the right size AFAICT. The thing I thought would flip it correctly has not worked however.

**Comment by mattpap** [comment]
In all honesty I don't follow what this code is supposed to do.

**Comment by bryevdv** [comment]
OK, I will look at it over the weekend and we can release monday

**Comment by bryevdv** [comment]
@mattpap I pushed a fix to compute the height correctly:

screen shot 2017-11-27 at 10 18 08

I'll merge this and make an RC. I'll focus on a blog post, testing with the RC, and catching up on some support requests and emails today. We can plan on releasing first thing tomorrow morning.

**Comment by gvanem** [comment]
Funny if this is merged and working; I just d/l Bokeh and the examples. But the `spectrogram` app doesn't work for me on Windows-10 with Python 2.7.15 (32-bit). 

Doing a `bokeh serve --show main.py`, starts the server okay, but I'm getting hordes of these errors:
```
2018-07-18 13:08:06,528 Error thrown from periodic callback:
2018-07-18 13:08:06,528 Traceback (most recent call last):
  File "f:\programfiler\python27\lib\site-packages\tornado\gen.py", line 883, in callback
    result_list.append(f.result())
  File "f:\programfiler\python27\lib\site-packages\tornado\concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "f:\programfiler\python27\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "f:\programfiler\python27\lib\site-packages\bokeh\server\session.py", line 51, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "f:\programfiler\python27\lib\site-packages\bokeh\server\session.py", line 157, in with_document_locked
    return func(*args, **kwargs)
  File "f:\programfiler\python27\lib\site-packages\bokeh\document\document.py", line 1076, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "f:\programfiler\python27\lib\site-packages\bokeh\document\document.py", line 1062, in _with_self_as_curdoc
    return f()
  File "f:\programfiler\python27\lib\site-packages\bokeh\document\document.py", line 1075, in invoke
    return f(*args, **kwargs)
  File "F:\ProgramFiler\Python27\Lib\site-packages\bokeh\Github-bokeh\examples\app\spectrogram\main.py", line 72, in update
    signal, spectrum, bins = audio.data['values']
TypeError: 'NoneType' object is not iterable
```
and no plots in my Chrome browser.

The other apps (*Gapminder* etc.) works just fine. I just discovered Bokeh today; just awesome!

**Comment by bryevdv** [comment]
@gvanem This PR addressed an issue with the rendering, and did not involve a stack trace. It looks like you are seeing something different, and perhaps specific to Windows.  So it would be appropriate to make  new issue with all the relevant information.

**Pull request merged**
