### PR TITLE
Use red/yellow color scheme for example

### LINKED ISSUE #10974: [FEATURE] Use a colorblind friendly color scheme in documentation
... rather than red/green, which is hard to distinguish for Daltonian people.

Reasoning: When reading the docs, I first didn't understand the [annotations example](https://docs.bokeh.org/en/latest/docs/first_steps/first_steps_3.html#using-annotations). It seemed that the annotation was missing, since I only saw a blue line on a uniform background. Only when looking at the code did I realize that there was a red/green pattern in the background of the plot.

Note that, according to [Wikipedia]: Red–green color blindness affects up to 8% of males and 0.5% of females of Northern European descent.

I've prepared a pull request.

[Wikipedia]: https://en.wikipedia.org/wiki/Color_blindness

### PR DESCRIPTION
**Pull request by Sjlver**
... rather than red/green, which is hard to distinguish for Daltonian
people.

Reasoning: When reading the docs, I first didn't understand the
annotations example. It seemed that the annotation was missing, since I
only saw a blue line on a uniform background. Only when looking at the
code did I realize that there was a red/green pattern in the background
of the plot.

Note that, according to [1]: Red–green color blindness affects up to 8%
of males and 0.5% of females of Northern European descent.

[1]: https://en.wikipedia.org/wiki/Color_blindness

- [x] issues: fixes #10974
- [x] tests: n/a

### CODE REVIEW

**Comment by bryevdv** [comment]
Thank you for the PR @Sjlver we are very receptive to all suggestions and contributions to improve accessibility. What do you think about making things consistent with this other similar example:

https://github.com/bokeh/bokeh/blob/branch-2.4/examples/plotting/file/box_annotation.py

That example simply makes both boxes red, and adds "Red = outside range" to the title. Alternatively we could upate that example to use red and yellow to match these. 

cc @tcmetzger for thoughts

**Comment by tcmetzger** [comment]
@Sjlver Thanks for you pull request, that is a very good point! I'd suggest we keep the three boxes in the examples in question, because the middle box (currently green) serves as an example of a box that has values assigned to both, `top` and `bottom` - whereas the other boxes (currently red) serve as examples of only one property having a value (and Bokeh automatically stretching the BoxAnnotation to the edge of the plot). 

To still make sense as an example displaying glucose values: how about we leave the middle box as green, while changing the two outer boxes to yellow?

**Comment by bryevdv** [comment]
I just realized the examples in the PR are different, with three boxes. I think this can just be merged as-is without changing the glucose example (as it does not have any red and green in conjunction)

**Comment by bryevdv** [comment]
> To still make sense as an example displaying glucose values: how about we leave the middle box as green, while changing the two outer boxes to yellow?

This seems OK to me. Stock primary "green" and "yellow" are pretty blaring so my only other suggestion might be to see if there are other green and yellow shades that are a bit more muted but still accessible.

**Comment by tcmetzger** [comment]
@Sjlver Check https://docs.bokeh.org/en/latest/docs/dev_guide/documentation.html for information on contributing to the docs. You'll first need to [set up a dev environment](https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html#devguide-setup), then you can [build and preview the docs locally](https://docs.bokeh.org/en/latest/docs/dev_guide/documentation.html#setting-up-and-building-bokeh-s-documentation).

**Comment by bryevdv** [comment]
@Sjlver I also just noticed that this PR is against `main` but it will need to land on `branch-2.4` instead. I can try changing the target here in the GH web UI but it may reveal that a rebase is necessary.

**Comment by bryevdv** [comment]
@Sjlver are you still interested to continue with this PR?

**Comment by Sjlver** [comment]
Yes, sorry for the delay... It's on my task list!

**Comment by bryevdv** [comment]
Given the a amount of time that has passed, and the issue with commit history, I am going to go ahead and close this PR at this time. @Sjlver we would be very happy to consider a new fresh PR on current `branch-2.4` in case you do have time in the future to revisit things.

**Pull request closed without merging**
