### PR TITLE
Docstrings on examples\app

### PR DESCRIPTION
**Pull request by ArchaeotheriumSapienter**
Added short descriptions on examples in examples\app to tackle #11540

### CODE REVIEW

**Comment by bryevdv** [comment]
I'm not sure what is going on with the codebase tests, the results there do not make sense to me. I don't think its actually related to your PR but, will need to investigate a bit later.

**Comment by mattpap** [comment]
We need to use a version range for django. 4.0 was released today, which seems not to be compatible anymore, at least the way we use it.

**Comment by bryevdv** [comment]
Figured it must be something like that.

**Comment by bryevdv** [comment]
@ArchaeotheriumSapienter while we wait on getting that unrelated issue sorted, it looks like about half the server examples still have `.. bokeh-example-metadata::`. If you commit changes to your local branch to remove those, and then push, the updates should show up here in this PR.

**Comment by ArchaeotheriumSapienter** [comment]
Oh, you're right! I'll remove them! Sorry about that I thought I got every metadata

**Comment by ArchaeotheriumSapienter** [comment]
Hi! I created a final pull request with cleaner commits to avoid getting the history dirty with my merges. Thank you so much for your understanding!

**Comment by bryevdv** [comment]
superseded by #11872

**Comment by bryevdv** [comment]
> Hi! I created a final pull request with cleaner commits to avoid getting the history dirty with my merges.

@ArchaeotheriumSapienter we always squash merge PRs by default, so there is no concern about merge history. FYI for the future, it's definitely preferable on our end to have a single PR that gets updated, rather than opening and closing several PRs (it's more work to track and label them, and comment history is disconnected)

**Pull request closed without merging**
