### PR TITLE
bokeh 2.4.2 backports

### PR DESCRIPTION
**Pull request by bryevdv**
* [x] https://github.com/bokeh/bokeh/pull/11781
* [x] https://github.com/bokeh/bokeh/pull/11767
* [x] https://github.com/bokeh/bokeh/pull/11764
* [x] https://github.com/bokeh/bokeh/pull/11762
* [x] https://github.com/bokeh/bokeh/pull/11761
* [x] https://github.com/bokeh/bokeh/pull/11731
* [x] https://github.com/bokeh/bokeh/pull/11772
* [x]  https://github.com/bokeh/bokeh/pull/11753
* [x] https://github.com/bokeh/bokeh/pull/11783
* [x] https://github.com/bokeh/bokeh/pull/11790

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap could use your help on #11753 which was merged instead of squashed. I tried `git cherry-pick -m 1 <commit>` but there were still 4 conflicts on baseline images. I am not sur what images ar the correct images, or how to find out that, either.

**Comment by mattpap** [comment]
It's simpler to just regenerate those images instead of trying to port them between branches.

**Comment by bryevdv** [comment]
And possibly #11783 which also does not cherry-pick cleanly

**Comment by bryevdv** [comment]
OK I will add the `-m 1` result for a start

**Comment by mattpap** [comment]
> > And possibly #11783 which also does not cherry-pick cleanly

> `TypeError: Cannot read properties of undefined (reading 'pi')`

`np.pi` in integration tests has to be replaced by `Math.PI` and imports removed.

**Comment by ianthomas23** [comment]
Let me know if you want my help with the backport of #11783.

**Comment by bryevdv** [comment]
Docs issue is unrelated, due to today's Sphinx 4.3 release. I am going to go ahead and merge this and clear the "needs backport" labels while I have everything up and open  so that things don't become confused or inconsistent, and let the Sphinx issue be resolved separately.

**Pull request merged**
