### PR TITLE
Implement proper rendered finished (idle) algorithm

### LINKED ISSUE #5879: Make "bokeh finished rendering heuristic" work with non-plot examples
Currently they time out, because "finished" event isn't ever triggered.

### PR DESCRIPTION
**Pull request by mattpap**
- [x] support `ImageURL`
- [x] support `GMapPlotCanvas`
- [ ] support `TileRenderer`

fixes #5879

### CODE REVIEW

**Comment by bryevdv** [comment]
ping @jlstevens FYI once this is merged we can/should also expose as a `bokeh.events` event as well.

**Comment by bryevdv** [comment]
@mattpap AFAIK image url and gmap are by far the more common cases. So I would definitely not hold up merging this just to get the tile renderer done. We can note a known issue and make a separate GH issue to add support for it later.

**Comment by bryevdv** [comment]
@mattpap I have resolved the trivial conflict in the GH UI

**Comment by mattpap** [comment]
@bryevdv, I was experimenting with this PR over weekend and it doesn't yet work reliably (with `TileRenderer` put aside). This needs some more work.

**Comment by mattpap** [comment]
I improved this PR and merged into #6384, because it's needed there to proceed with testing.

**Pull request closed without merging**
