### PR TITLE
Update timeseries examples to use new Line chart where possible

### PR DESCRIPTION
**Pull request by birdsarah**

### CODE REVIEW

**Comment by bryevdv** [comment]
Isn't the plan to make a new `TimeSeries` chart? Maybe it would be better to just wait for that?

**Comment by birdsarah** [comment]
@fpliger @rothnic is timeseries going to be ready for 0.11? if not, maybe good to merge this for now?

**Comment by rothnic** [comment]
See #3024. I think we have timeseries, step, dot, and area most of the way there. Working through this we realized linebuilder can be more a generic seriesbuilder, which makes use of different glyph types. So we have timeseries examples with line, step, and scatter.

I'll probably have horizon mostly working in the next couple days or so. I have a rough version of it working locally. So, it depends I guess. I think the referenced pull request is a bit larger, hoping to knock the rest of them out with it, but it'll also take a bit more time to clean things up. It is also possible we could split just the line/timeseries bit off on its own, since it is more simple than the other remaining charts.

**Comment by bryevdv** [comment]
ping @birdsarah @rothnic So this can be superseded and closed?

**Comment by birdsarah** [comment]
Closing it. @rothnic re-open if you think you still want this (which I doubt)

**Pull request closed without merging**
