### PR TITLE
Circle vs Scatter API cleanup

### LINKED ISSUE #13246: Complete the consolidation of scatter markers in bokeh.plotting
cc @bokeh/dev 

Awhile back we started the process of consolidating and simplifying scatter markers by removing individual models for scatters, e.g. `Square`, `Triangle`, etc. and replacing them with a single `Scatter` glyph parameterized by marker type. IIRC we intended to continue down this path, and encourage the use of `scatter` as the primary API for scatter plots in `bokeh.plotting` as well, but never quite completed that part. 

I'd like to propose doing so now. Specifically I would deprecate all the individual scatter methods, and also finally make clean separation between `Circle` (data-radius only) and `Scatter(marker="circle")` (screen size only). Summarized:

```python
# These all emit a deprecation
p.triangle(...)
p.square(...)
p.hex(...)

# deprecate glyph-circle with a size
p.circle(..., radius=5)   # expected
p.circle(..., size=10)    # returns Scatter(..., marker="circle") and emits deprecation

# deprecate scatter-circle with a radius
p.scatter(..., marker="circle", size=10)    # expected
p.scatter(..., marker="circle", radius=5)   # returns Circle(...) and emits deprecation
```

The one corner case we would lose here is if someone called `circle(size=10)` to start and wanted to change to `circle(radius=5)` later. I'ver never see or heard of anyone wanting this, and am comfortable with this change since there would be workarounds to recommend in case it really did affect anyone. 

Along with this, we would go through all the docs and examples and use `scatter` consistently for all scatter plots with a screen-space size, or `circle` for plots with a data-space radius. 

I think it goes without saying we would not actually remove any of the deprecated methods any time soon. *Maybe* at a future 4.0 release. 

Are there any concerns or objections to my pursuing the changes above for 3.3?

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #13246
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

Still WIP, just seeing how full CI performs at this point. I will update this description when the PR is ready.

### CODE REVIEW

**Comment by bryevdv** [comment]
@bokeh/core This ended up being a bit more involved than I expected. I am not sure when I will be able to get back to the last mile. But this PR is fairly big, so rather than keep it around in perpetuity I think we should do one of these two things in the next week:

* merge this as-is as its own issue-PR and leave the original issue open to finish out hopefully soon
* close this PR and just take on the entire issue fresh at some later time 

Please let me know thoughts/preferences.

**Comment by mattpap** [comment]
I went ahead and finished this PR.

**Comment by bryevdv** [comment]
> I went ahead and finished this PR.

For some reason I thought there was quite a bit more to go, but maybe my memory is just off. Happy to merge and close with an approval.

**Review by mattpap — APPROVED** [review]

**Comment by mattpap** [comment]
It was actually quite a bit of work, given there was an API bug that hid a lot of issues and TypeScript wasn't very helpful either with some corner cases.

**Comment by bryevdv** [comment]
Thanks @mattpap I'll merge later today!

**Pull request merged**
