### PR TITLE
Add figure's plot id in DOM structure as well

### LINKED ISSUE #8384: Feature: Add Plot's root id to DOM so to allow API access to the object
I'm using Bokeh in Standalone mode, embedding a plot in a page like so:

```py
    script_tag, html = components(plot)
```

Unfortunately, the `html` does not contain any reference to the plot's ID (`root.id`), it only contains the element id (`root.elementid`), but the plot id is necessary if I want to interact with the plot through the API, for example calling:

```js
        Bokeh.index[plotId].save(plotTitle)
```

A workaround is to render the plot manually and communicate a reference to the plot ID out of band, like so:

```py
    script_tag, plot_info = components(plot, wrap_plot_info=False)
    root_el = ROOT_DIV.render(root=plot_info, macros=MACROS)
    # put plot_info.id somewhere in the dom
```

I'll push a PR for this.

### PR DESCRIPTION
**Pull request by rbu**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes #8384
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by rbu** [comment]
@bryevdv I added a test for the functionality and fixed the other test that got broken. Unfortunately, the travis build is red due to a timeout in the selenium/chrome tests. Is that related to my change or just a hickup?

**Comment by bryevdv** [comment]
@rbu apologies for the long delay, I took all of November off from OSS work, and my December has been a little personally hectic so far. The test failure was spurious and everything is green now.  I don't have any objections to adding this since there is a test for it. But we should give @mattpap a chance to chime in in case there are any considerations I may not be aware of.

**Comment by bryevdv** [comment]
My only other comment is that I would not want to encourage folks to use private attrs like `plot._id` so we might want to consider adding a read-only getter for that.

**Comment by bryevdv** [comment]
Actually, there is one other route we could consider. Models have some other user accessible fields:

* `obj.name` - can be set to an arbitrary string
* `obj.tags` - can be set to an arbitrary list of values

The `name` field is only used lightly by Bokeh, i.e. if you supply a  name it is available for templating the object by name. And the `tags` field not at all (there is a function that can query the object graph for objects with matching tags, but that is it). We could consider using these properties as a basis for adding DOM attrs instead of the model id. That way, users have explicit control over what the values will be and know them ahead of time. Thoughts?

**Comment by bryevdv** [comment]
@mattpap is there any particular objection to adding 
```
@property
def id(self): return self._id
```
to `Model`?

**Comment by mattpap** [comment]
> `@property`
> `def id(self): return self._id`

Not at all. It's peculiar to me, why this wasn't in the first place. When this is done, we should update the code base to use `id` instead of `_id`.

**Comment by bryevdv** [comment]
OK, @rbu has not responded to recent comments, so I will merge this as-is and make a follow-up PR to add the getter and make the other changes.

**Comment by rbu** [comment]
@bryevdv, thank you for merging. The changes you proposed were perfectly fine, I simply took time away from the project myself as well.

**Pull request merged**
