### PR TITLE
Add simple fuzzymatching comparison to AutocompleteInput

### LINKED ISSUE #9923: Does AutocompleteInput have a "find inside the text" option instead of "beggining with"?
For example if we type "mask" and completions contain "The mask" then it would match and display the completion.

### PR DESCRIPTION
**Pull request by slamer59**
I add a simple fuzzymatching comparison algorithm for my needs.
I think it can solve:

- [x] issue: fixes #9923
- [x] tests added. 
- [x] release document entry

The documentation is constructed directly from sources ? 

Test can be added.

### CODE REVIEW

**Comment by bryevdv** [comment]
@slamer59 there's alot of pure whitespace changes here (I'm guessing auto-appliedby your editor?) that are both unnecessary as well as flagged by our linter. All of those would need to be reverted. 

However, I also think I'd like to discuss the approach here. Adding properties directly locks us completely in to this for the future, and may make it more difficult to support other or different matching strategies. I think I would prefer to look at delegating match returns to subclasses of a`MatchingPolicy` or something like that. Then different matching policies can be made available without having to dump a bunch of mutually incompatible configuration options all on `AutoComplete`. (There could even be a `CustomJSMatchingPolicy` if someone wants to highly customize matching using an API, etc).

**Comment by slamer59** [comment]
Hello, 
thanks for your reply. This PR was more a first trial for me and open the discussion. (And for me to begin my first real integration and setup the same options than bokeh). I really like bokeh and panel but I was more an end-user than developper 😅

It can be a long journey so... I share my findings:
- Which matching algorithm ? Plenty, so difficult to choos. https://www.rosette.com/name-matching-algorithms/#common-key-method
- How to implement ? For me, the logic is more on Javascript side. But would be interesting to be able to custoimize on python side two. 
- ... 

We should consider also this on Panel side https://github.com/holoviz/panel/issues/1460

Do you want me to close it ? How do you want to procede step by step ?

**Comment by bryevdv** [comment]
@slamer59 sorry it took so long to get back to this. SInce there are now conflicts I think it's best to close this particular PR and start fresh. I have changed the OP to `feature` and also noted the "policy" based implementation plan for you (or anyone else) who works on this in the future.

**Comment by slamer59** [comment]
I agree, I just need this for a project and it was a way to deep dive in this lirabries.
No worries :)

**Pull request closed without merging**
