### PR TITLE
Update hover styling to match other bokeh elements

### PR DESCRIPTION
**Pull request by birdsarah**
Fixes: #5008

Updates the hover styling to match other bokeh elements. See #5008 for description.
Also adds a gray line between elements for when you're hovered over multiple elements.

Notebook was a big pain

### CODE REVIEW

**Comment by birdsarah** [comment]
screen shot 2016-09-01 at 12 28 23 pm

screen shot 2016-09-01 at 12 27 18 pm

screen shot 2016-09-01 at 12 28 40 pm

**Comment by bryevdv** [comment]
looks fantastic

**Comment by canavandl** [comment]
code quality issues

**Comment by birdsarah** [comment]
done.

**Comment by canavandl** [comment]
LGTM

**Pull request merged**
