### PR TITLE
ci: replace appveyor with github actions

### PR DESCRIPTION
**Pull request by ammarnajjar**
Only windows and macos pipelines are run
on github actions for now.

- [X] issues:  #9284
- [X] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by ammarnajjar** [comment]
help wanted:
- I removed all `appveyor` configurations, but how to disable continuous-integration/appveyor/pr check?
- github actions pipeline run green on my repo https://github.com/ammarnajjar/bokeh/runs/279223557, but I cannot see any actions pipelines running under https://github.com/bokeh/bokeh/actions/new, does it have anything to do with me not being a collaborator?
Screen Shot 2019-10-29 at 12 11 20

**Comment by bryevdv** [comment]
@ammarnajjar Wow, thanks for the PR! Just to set expectations about timing, we are trying to have a big release this week, so I'm not going to tempt fate by tinkering with any of the CI systems before then :) I should have some time during a conference next week to dig in to this more. If you are interested in contributing in an ongoing manner after this PR, we can certainly add you as a collaborator, just let me know.

**Comment by bryevdv** [comment]
I would as you to consider one change in the mean time: I would be preferable to follow the layout of the other systems, i.e. have all the actual scripts that the main yaml file runs be under the `scripts/ci/azure` directory

**Comment by ammarnajjar** [comment]
> we are trying to have a big release this week, so I'm not going to tempt fate by tinkering with any of the CI systems before then :)

That's reasonable 👍 

> If you are interested in contributing in an ongoing manner after this PR, we can certainly add you as a collaborator, just let me know.

I cannot promise anything really 😅 , so if there is a way for you to trigger the actions, that would be great.  
I am not sure but one way to do it might be that you (or any collaborator for that matter) push an empty commit to the PR branch:

```bash
git commit --allow-empty -m "trigger GitHub actions"
git push
```

**Comment by bryevdv** [comment]
@ammarnajjar That question was more about your interest and availability, than this PR (which we will get working one way or the other!)

I'll poke around with this very soon after the release (including trying pushing a commit)

**Comment by bryevdv** [comment]
@ammarnajjar now that the landing-2.0 branch is merged we can take a proper look at this. I am hoping to be able to take some work time next week or so. It looks like there is s small conflict and GH will not let me resolve it in the UI. Can you get everything up to date on current master?

**Comment by ammarnajjar** [comment]
> Can you get everything up to date on current master?

sure thing

**Comment by bryevdv** [comment]
I'm going to go ahead and merge this to be able to play around with things, but I have limited time today s it's possible I will need to revert and come back to it later (just setting expectations)

**Comment by bryevdv** [comment]
@ammarnajjar I'm seeing the builds now but the windows jobs are failing:

```
Using different version of bokeh, rebuilding from scratch.
Running npm install.
npm install failed with exit code 1.
---------------------------- Captured stderr call -----------------------------
npm WARN npm npm does not support Node.js v13.0.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\mingw64\bin\git.EXE ls-remote -h -t https://github.com/bokeh/SlickGrid.git
npm ERR! 
npm ERR! fatal: remote error: access denied or repository not exported: /6/nw/60/d2/f6/440826/94910591.git
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm\cache\_logs\2019-11-20T18_34_43_334Z-debug.log
```

**Comment by ammarnajjar** [comment]
🤔 
This is strange, the first master pipeline after the merge is green => [here](https://github.com/bokeh/bokeh/commit/fdeee737ac5df6d566a020e9c8bfe5f0f22a3528/checks?check_suite_id=320809768)
@bryevdv, I will try to investigate more when I get time (hopefully this weekend)

**Pull request merged**
