### PR TITLE
Improve color contrast for accessibility

### PR DESCRIPTION
**Pull request by chinmaychahar**
- [x] issues: addresses #11481 

- Changes to `examples/topics/graph/node_and_edge_attributes.py`
- Chosen color contrast from - Tol's Palette medium contrast

<table>
  <tr>
    <td>Initial color palette</td>
    <td>Updated color palette</td>
   </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
</table>

<table>
  <tr>
    <td>Initial contrast</td>
    <td>Updated contrast</td>
   </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
</table>

### CODE REVIEW

**Comment by chinmaychahar** [comment]
If approved, I can work on updating the thumbnails too

**Comment by chinmaychahar** [comment]
@bryevdv in reference to my comment [here](https://github.com/bokeh/bokeh/pull/12990#issuecomment-1476523075), I think the same would be need to done for this branch as well. Should I revert the changes from this branch which are irrelevant to this particular PR?

**Comment by bryevdv** [comment]
@chinmaychahar I am still seeing the extraneous changes in this PR. I am actually not sure about switching to a darker background for this example, either. @tcmetzger @pavithraes any thoughts?

**Comment by chinmaychahar** [comment]
Okay @bryevdv I can wait for the approval before making more changes to this PR then!

**Comment by bryevdv** [comment]
Hi @chinmaychahar alternatively, another option would be to update the example keeping the same light grey background. I think in that case that if the existing colors for nodes and regular edges are darkened a bit, then we can achieve better contrast results with a less drastic change.

**Comment by chinmaychahar** [comment]
Okay sure, I can work on that!

**Comment by chinmaychahar** [comment]
@bryevdv Would like your opinion on this palette. 

The background vs foreground contrast ratio is better and I've increased the line alpha slightly for regular edges

<table>
  <tr>
    <td>Initial</td>
    <td>Updated</td>
   </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
</table>

<table>
  <tr>
    <td>Color Contrast</td>
   </tr>
  <tr>
    <td></td>
  </tr>
</table>

**Comment by bryevdv** [comment]
I'm not sure. I have to be honest and say I find the very dark circles unpleasant, mostly because I really like to see the circle border of the nodes. and with that dark fill color, the circle border becomes indistinguishable. 

Would it suffice to keep the original colors, but increase alpha on the edges and borders, and possibly also increase the linewidth as well? As long as the circle borders have sufficient contrast, I think all the the intended meaning can still be conveyed?

**Comment by chinmaychahar** [comment]
Thank you for the feedback, I understand your concern. 

The plot looks something like this for reference when I've increased the line alpha and line width slightly. If this fits as an improvement, I can work upon the changes else I'm open to suggestions! 

updated_graph

**Comment by bryevdv** [comment]
@chinmaychahar I think this is an improvement, the nodes are distinguishable due to their black borders, and the same information is conveyed (there is no information conveyed in color variation among the nodes themselves). Since the before/after are somewhat similar, I think we can get away with keeping the old thumbnail and just need the code changes.

**Comment by chinmaychahar** [comment]
Thanks for the feedback. I've made the required code changes!

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
Thanks for the PR @chinmaychahar !

**Pull request merged**
