### PR TITLE
Fix periodic callback not stopping in Django

### LINKED ISSUE #10218: [BUG] Periodic callback don't stop in Django
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
  - bokeh=2.1.0
  - panel=0.9.6
  - django=3.0.7
  - django-channels=2.4.0

#### Description of expected behavior and the observed behavior
As first reported in holoviz/panel#1125 I have a Django site which have a widget with a periodic callback, so a plot is updated every 10 seconds. But I have noticed that when I leave the site without stopping the periodic callback it keeps running forever in Django, where Panel is running for ~30 seconds.

It was [mentioned](https://github.com/holoviz/panel/issues/1125#issuecomment-645404719) by @philippjfr that it could be related to server cleanup handlers which aren't correctly triggered when running via Django.

#### Complete, minimal, self-contained example code that reproduces the issue
See [periodic_example.zip](https://github.com/bokeh/bokeh/files/4813615/periodic_example.zip). The example is using Panel right now, I hope this is okay but if it is needed I can try to remove the Panel part from the code. 

To run the example with Django use the command `python manage.py runserver` and to run it with Panel use the command `panel serve panel_example.py` 

#### Screenshots or screencasts of the bug in action
**Panel**
panel

**Django**
django

### PR DESCRIPTION
**Pull request by Hoxbro**
- [x] issues: fixes  #10218  and https://github.com/holoviz/panel/issues/1125
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
LGTM but it would be nice to add a test, even if it is just a simple mock that maintains `session.destroy` gets invoked when `disconnect` is awaited. What do you think @Hoxbro ?

**Comment by Hoxbro** [comment]
I definitely think that a test is a good idea. I don't have that much experience in testing with Django and asyncio, so I don't know where to start.

**Comment by mattpap** [comment]
Unfortunately right now we don't have any tests of Django integration, so there isn't anything to point you to.

**Comment by bryevdv** [comment]
I was hoping a simple `@patch` test would be possible but it looks like too much surrounding context needs to be set up to make that feasible. I will go ahead and merge this as-is. Thanks, @Hoxbro

**Pull request merged**
