### PR TITLE
Make json_items ingestible by python API #10631

### LINKED ISSUE #10631: Feature Request - Load from Bokeh HTML file and overlay other shapes?
I want Bokeh to provide some file format so that I can write to it and load it back in Python and do some surgery. Even if I cannot interact with it like the existent HTML format. 

Thanks!

### PR DESCRIPTION
**Pull request by Nikhil-Chandra-Paul**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes #10631

### CODE REVIEW

**Comment by bryevdv** [comment]
HI @Nikhil-Chandra-Paul Thank you for contributing to Bokeh. A few comments:

* Please do not open and close multiple PRs just to make changes. You can push changes to an existing PR branch, and the existing PR will update on GitHub. Happy to point to some online resources if there is more questions about this workflow.

* We don't permit bare `except` in the codebase (see the LGTM warning posted above). The exception block should be narrowly scoped to the actual exception that would be expected here. Alternative, this could be accomplished by checking keys in the dict ahead of time instead of relying on an exception (this is probably preferable in fact)

* Any fix here will need some unit tests, we can help with that too if you have questions. 

Without actually trying this change out locally yet, it's also not 100% clear to me that this change is sufficient. A full solution would permit:

* exporting a plot with `json_item`
* re-ingesting in a new document
* modifying the new document (e.g. change plot title, etc)
* verify  successful export of new document with change

**Comment by Nikhil-Chandra-Paul** [comment]
This is my first ever pull request and I am new to this,thanks for helping me out.
I will change that try-except block to if-esle,and I have questions about adding unit tests.

**Comment by bryevdv** [comment]
@Nikhil-Chandra-Paul Great, happy to help. I think a good first step for a test is just to try out the steps I outlined above, i.e. export some JSON and try to read it back and use it.

**Comment by bryevdv** [comment]
@Nikhil-Chandra-Paul did you have a chance to test the steps above to see whether JSON output could be re-ingested?

**Comment by Nikhil-Chandra-Paul** [comment]
Yah, I've done the following things
-exporting a plot with json_item
-re-ingesting in a new document
-changed the plot title
-exporting the new plot
with the below python code
```
from bokeh.io import show
from bokeh.models.annotations import Title
from bokeh.embed import json_item
from bokeh.document import Document
from bokeh.plotting import figure

plot= figure(plot_width=400, plot_height=400,title='old')
plot.square([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=[10, 15, 20, 25, 30], color="firebrick", alpha=0.6)
out = json_item(plot)
#ingestion
doc = Document.from_json(out)
#changing title
doc.roots[0].title=Title(text="New")
plot=doc.roots[0]
show(plot)
```
And got this output
bokeh_plot

Is this the correct way?
Should I add any other things ?

**Comment by bryevdv** [comment]
@mattpap do we have any existing helpers for structural comparison of documents? If so I expect a test could look like
```
orig_doc = Document()

plot= figure(plot_width=400, plot_height=400,title='old')
plot.square([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=[10, 15, 20, 25, 30], color="firebrick", alpha=0.6)

orig_doc.add_root(plot)

out = json_item(plot)

new_doc = Document.from_json(out)

# assert new_doc ~ orig_doc

```

**Comment by Nikhil-Chandra-Paul** [comment]
This one is comparing the documents on _all_models :
```
from bokeh.document import Document
from bokeh.plotting import figure

orig_doc=Document()

plot= figure(plot_width=400, plot_height=400,title='old')
plot.square([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=[10, 15, 20, 25, 30], color="firebrick", alpha=0.6)
orig_doc.add_root(plot)

out = json_item(plot)
new_doc = Document.from_json(out)

#comparing orig_doc with new_doc
for i in orig_doc._all_models:
    assert orig_doc._all_models[i].struct==new_doc._all_models[i].struct
```
This one is comparing the documents  on roots :
```
from bokeh.document import Document
from bokeh.plotting import figure

orig_doc=Document()

plot= figure(plot_width=400, plot_height=400,title='old')
plot.square([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=[10, 15, 20, 25, 30], color="firebrick", alpha=0.6)
orig_doc.add_root(plot)

out = json_item(plot)
new_doc = Document.from_json(out)

#comparing orig_doc with new_doc
for i in range(len(orig_doc.roots)):
    assert orig_doc.roots[i].struct==new_doc.roots[i].struct
```
Is this the correct way?

**Comment by bryevdv** [comment]
Hi @Nikhil-Chandra-Paul Unfortunately that is not suffiecient. If you print the `.struct` values you'll see they look like:
```
{'type': 'Selection', 'id': '1270'}
{'type': 'LinearAxis', 'id': '1240'}
{'type': 'UnionRenderers', 'id': '1269'}
{'type': 'ColumnDataSource', 'id': '1258'}
{'type': 'BoxAnnotation', 'id': '1250'}
```
But that is missing all the important information, the set property values, that are actually what need to be compared Additionally these still have the `id` field present. Those need to be discarded before comparing. It's a coincidence that they will likely match, but that can't actually be relied upon to be true. Instead of `struct` you could compare something like `.to_json(include_defaults=True` which has all the prop values. But as you can see, it is a deeply nested structure and ids would need to be removed at *all* levels. I think this points to us needing to implement some APIs to facilitate structural comparisons first. AFAIK they do not exist yet (cc @mattpap please correct me if there is some recent addition I missed)

**Comment by bryevdv** [comment]
I am going to ahead an close this for lack of activity, and for the fact that it is now based against an old release branch rather than current.

**Pull request closed without merging**
