### PR TITLE
Support Input of Color Tuple for Figure Glyphs

### PR DESCRIPTION
**Pull request by rothnic**
Fixes bokeh/bokeh#2161.

Outstanding issues are to add additional tests, which depend on whether the [javascript side](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/common/properties.coffee#L123) should be updated to support the color tuple. To get this working I had to convert the tuple to Hex in the ColorSpec's to_dict method. Otherwise, I get the following error in the browser: `color property 'line_color' given invalid value: rgb(100, 100, 100)`.

### CODE REVIEW

**Comment by bryevdv** [comment]
I"m not sure I have an opinion on whether that ought to be valid on the JS side. @tswicegood any thoughts?

**Comment by rothnic** [comment]
One thing I found is that without javascript supporting the tuple, the conversion to hex doesn't support the alpha values, so I had to catch them in _materialize_colors_and_alpha to override the default alpha values.

**Comment by bryevdv** [comment]
That's a bit of the underlying API poking through. It has you specify the color and alpha separately and that is reflected in there being `fill_color` and `fill_alpha` etc. I think maybe the best thing to do is keep that on as the JS interface (otherwise there more potential for inconsistencies) and then the python side we need to find a way to convert RGBA into setting both the color and the alpha properties. Thoughts?

**Comment by rothnic** [comment]
>  I think maybe the best thing to do is keep that on as the JS interface

Keep `fill_color` and `fill_alpha` on the JS interface? If so, yeah, I'm just handling it on the python side when alpha is provided with color, line_color, or fill_color is (r, g, b, a).

> then the python side we need to find a way to convert RGBA into setting both the color and the alpha properties

If I'm understanding you correctly, then I think what you are saying is what I'm doing [here](https://github.com/bokeh/bokeh/blob/c505038697929ef1cd96ad3e2af11aa2d76104da/bokeh/plotting_helpers.py#L139). 

The main issue with the tests right now is just that when on the python side you have set the color with rgb or rgba, the to_dict method on ColorSpec has been changed to convert to hex, since JS doesn't support the rgb or rgba. That modification makes [this test](https://github.com/bokeh/bokeh/blob/master/bokeh/tests/test_properties.py#L190), which checks for the valid conversion from rgb/rgba to dict, fail.

I guess the main issue with it as is, is that the rgb/rgba isn't just handled via the python API, it is valid to store and communicate as the [specification of a Color](https://github.com/bokeh/bokeh/blob/7dc64aeb6799aabfeda3bf6601ed926cfc473e96/bokeh/properties.py#L847).

**Comment by bryevdv** [comment]
So, we might want to take a step back. When I originally wrote things, I was under the impression that you couldn't set RGBA values with, e.g., `ctx.strokeStyle`. This is why BokehJS relies on `ctx.globalAlpha` to control the alpha for fills, strokes, etc. But while it is true that you can't set RGBA *Hex* values, you can set RGBA values like:
```
ctx.strokeStyle = "rgba(255, 0, 0, 0.2)";
```
as a quick check just verifies. So, we should discuss an optimal way forward. If we want to allow RGBA values (either tuples or hex) on the python side, perhaps we just need to make sure they are converted to that "css" style above, and make sure the plumbing will accept that all the way through. then the complication is the interaction between RGBA colors, and `fill_alpha`, which is well-defined but probably unfamiliar.

**Comment by rothnic** [comment]
An update on this is that I enabled the rgb tuple value to be accepted on the javascript side, which then works as you mentioned via strokeStyle. I also implemented some of the testing on the python side, and reverted the conversion to hex on the python side, so the tests pass now.

I need to complete the testing to make sure that the alpha value are being set correctly when rgb/rgba is passed via color, line_color, and fill_color, but some of that is implemented.

**Comment by bryevdv** [comment]
We should bundle some documentation with this PR, this is a subtle but important change in how alpha is  (can be) handled. We at least need some place to link to that explains the what would happen when you set alpha *both* ways, and why.

**Comment by rothnic** [comment]
Yeah, so that is the part that would be good to hear opinions on. What takes precedence? It seems like if you passed the kwargs for alpha you really want those values and maybe just happen to have rgba on hand? I don't know, it could go either way.

**Comment by bryevdv** [comment]
It's not a matter of choosing precedence, they simply stack. If a user sets `fill_alpha` that will result in setting `ctx.globalAlpha`. If they also specify a color with alpha, that will be applied as well. I'll try to work up a fiddle to demonstrate.

**Comment by bryevdv** [comment]
See here: http://jsfiddle.net/cfscr/167/

**Comment by rothnic** [comment]
I was trying to convince myself of the behavior in relation to line alpha and noticed strange behavior. Try [this fiddle](http://jsfiddle.net/rothnic/sno3opgw/4/), and comment out the last globalAlpha statement and rerun it. The last statement affects the current and previous line and fill alphas, but it was kind of hard to tell what was going on with the order.

[This fiddle](http://jsfiddle.net/rothnic/sno3opgw/5/) appears to show that the outline is affected by global alpha in the same way as fill. It handles the outline and fill separately.

Here is my understanding:
So, when providing fill_alpha, the global alpha is set from that value, then the shape is filled with the rgb, rgba, hex, or color string provided. Rgba happens to provide a unique color that has an independent alpha set.

When providing line_alpha, the same approach is taken, but it is handled completely independent of the fill operations. It seems like another glyph is drawn, except only with as an outline. It just happens to have the same dimensions as the corresponding fill shape.

On the python side, it should be fairly straight forward. The alpha values for line and/or fill should be passed through to bokehjs, along with the rgb/rgba/hex/color string. The thing that seems less straight forward is the canvas context and how the order of operations seems to cause interactions.

**Comment by bryevdv** [comment]
Yes they are "combining" because there is no call to beginPath in between react calls, so you are actually accumulating multiple shapes to draw and the redraw (on top of one another). bokehjs always calls beginPath in the "right" places tho so his would not be an issue. The values would just stack. 

Bryan

**Comment by rothnic** [comment]
Here is an example after reverting some of the modifications I made on the python side:

[Gist for python script](https://gist.github.com/rothnic/e655dc566f848bae4246)

Screenshot of the output:
image

Here is what it looks like after adding a line_width of 5. It looks a little strange, so I'll look at it more in depth later:
image

**Comment by rothnic** [comment]
Ok, here are the intersections of the combinations, and [the gist](https://gist.github.com/rothnic/e655dc566f848bae4246/c99bdf93e56127295ba76a9b55116bb75aa8309c) that produced it. Maybe something like this would be good for documentation.

image

Note, this does exclude the case of using "conflicting" inputs of the general color keyword in combination with line or fill color, or just using a specific line/fill keyword and receiving the default values.

**Comment by bryevdv** [comment]
@rothnic I think this will be good let's plan on putting it in 0.9.1 with good docs/examples support

**Comment by pzwang** [comment]
This is lovely!  However, if I can make a small suggestion: let's choose a different color in our docs than red & green, out of consideration for color-deficient users.

**Comment by rothnic** [comment]
That's right, here is with the first two colors from the charts color cycle utility. I'll write up some documentation and tests over the next couple days.

image

**Comment by pzwang** [comment]
Very nice!

**Comment by bryevdv** [comment]
The best section is the styling -> colors section of the new user guide. Probably easiest to merge this after 0.9 release at the end of the week.

**Comment by rothnic** [comment]
@bryevdv I made sure I can build the latest version of the docs, and was going to add this in. Do you think this should go under styling -> "Specifying Colors"? 

If so, it may be a little difficult there due to not having covered the line/fill properties yet. What do you think about moving Specifying Colors down to the bottom of the Visual Properties section, as a subsection. That would put it after all of the other properties have been covered.

**Comment by bryevdv** [comment]
@rothnic I think that would be fine

**Comment by rothnic** [comment]
Is there a trick to using the dev version of bokehjs when building the docs? Maybe I need to clear things out, but I can generate the plot fine, but only when building docs do I get the error I fixed on the JS side that rejects the rgba value.

**Comment by bryevdv** [comment]
Ah, problematic. All the inline plots use CDN resources, and the version of CDN resources can be specified (to use dev builds, for instance) but there is no mechanism to specify using, say local bokeh-server resources. That would be pretty simple to add, and a nice addition. In the mean time, if the plot works "by hand" I think you can just add the code for the plot to the docs, and lets the builds catch up.

**Comment by rothnic** [comment]
Only thing I have left is to go back and look at the python tests again. I significantly expanded the testing and validation on the javascript side, so it would be good to get a review on that. It should be pretty close to complete at this point.

**Comment by rothnic** [comment]
Realized there was some input options I was missing. Here all the blue color is default color, then red is configured fill and black is configured line.

image

This still doesn't address the `color` parameter, with and without the other options.

**Comment by rothnic** [comment]
I'm going to call this ready at this point.

**Comment by bryevdv** [comment]
@rothnic great I will give it a close look tomorrow. Regarding `color` I think it should do what it currently does: just be a convenience for setting `fill_color` and `line_color` at the same time, which is really orthogonal to all of this (it's a particular region of your plot, but nothing outside that plot)

**Comment by bryevdv** [comment]
LGTM merging

**Pull request merged**
