### PR TITLE
Fix hatch pattern drawing on high DPI displays

### LINKED ISSUE #12735: [BUG] hatching scales differently on different displays
### Software versions

Python version      :  3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ]
IPython version     :  8.7.0
Tornado version     :  6.2
Bokeh version       :  3.1.0.dev1+19.g0e72ad3c
BokehJS static path :  /Users/iant/github/bokeh/src/bokeh/server/static
node.js version     :  v18.11.0
npm version         :  8.19.2
Operating system    :  macOS-12.6.2-arm64-arm-64bit

### Browser name and version

Doesn't seem to be browser-specific

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

Hatching is drawn with a different scale to other plot features on different displays. In my two examples both svg and webgl backends look OK but canvas varies.

### Observed behavior

Should have same scale (with respect to other plot features) on all displays.

### Example code

```Python
from bokeh.layouts import row
from bokeh.plotting import figure, show

ps = []
for backend in ('canvas', 'svg', 'webgl'):
    p = figure(width=200, height=200, output_backend=backend, title=backend)
    ps.append(p)

    p.quad(left=0, right=1, top=1, bottom=0, fill_color="orange",
           line_color="blue", alpha=0.5, hatch_pattern='x')

show(row(ps))
```

### Stack traceback or browser console output

_No response_

### Screenshots

Screenshot from linux laptop, pixel ratio of about 1.06:
hatch_linux

Screenshot from external monitor attached to M1 mac, pixel ratio of 2:
hatch_mac

### PR DESCRIPTION
**Pull request by mattpap**
Before:
image

After:
image

TODO:

- [x] add DPI dependent visual tests

fixes #12735

### CODE REVIEW

**Comment by ianthomas23** [comment]
I've confirmed that this fixes the problem at my end. It gives me much sharper hatch patterns overall as well.

**Comment by mattpap** [comment]
> I've confirmed that this fixes the problem at my end. It gives me much sharper hatch patterns overall as well.

@ianthomas23, was this a review?

**Comment by ianthomas23** [comment]
> @ianthomas23, was this a review?

No it wasn't, it was a comment. I would not in general review anything that is WIP as it is liable to change. But now it is labelled as ready I will indeed review it.

**Review by ianthomas23 — APPROVED** [review]

**Comment by ianthomas23** [comment]
Thanks for fixing it so quickly.

**Comment by mattpap** [comment]
> I would not in general review anything that is WIP as it is liable to change.

Understandable. I'm uncomfortable setting `ready` status on PRs that are not indeed ready, but are good enough for an early review (e.g. just missing tests as in this case). That's why I proposed a new status `RFC` for such cases (in https://github.com/bokeh/bokeh/discussions/12708). Perhaps you may want to support that, so that we don't have to work in this binary way.

**Pull request merged**
