### PR TITLE
Update to TS 4.3-dev and enable `noImplicitOverride`

### PR DESCRIPTION
**Pull request by mattpap**
TypeScript 4.3 will be released on May 25th. This PR fixes a few compatibility issues, but primarily it enables `noImplicitOverride` option in all tsconfigs, which in turn enables analysis of overridden members (requires `override` keyword when a member is being overridden). This doesn't affect third-party extensions, as this options is an opt-in.

### CODE REVIEW

**Comment by bryevdv** [comment]
Just for my own FYI, did enabling this option catch any issues or problems in the existing codebase?

**Comment by mattpap** [comment]
No, because are none, otherwise bokehjs would fail at runtime. This options is helpful during development, allowing to catch issues with class structure before running the code. It's also useful when doing refactorings, as it works both ways, overrides must be marked, but non-overrides can not (you'll get errors in both cases).

**Comment by mattpap** [comment]
Also it's just useful when reading the code. I'm very accustomed to this given my earlier experience with Scala, which supports `override` keyword.

**Comment by mattpap** [comment]
> 1551 for Syntax error

I'm guessing I can't configure TS compiler version in lgtm? For comparison, eslint (`node make lint`) doesn't know about `override` keyword, but it will at least parse the new syntax.

**Comment by bryevdv** [comment]
> I'm guessing I can't configure TS compiler version in lgtm? 

I'm not aware of one. I don't see any issues here either, but we could open one to ask 

https://github.com/github/codeql/issues?q=is%3Aissue+is%3Aopen+typescript

**Pull request merged**
