### PR TITLE
Ability to save as svg

### PR DESCRIPTION
**Pull request by birdsarah**
Partially fixes: #538 

To test:
1. Run any file example
2. Add `?svg=1` to the end of the html file
3. The canvases will go blank
4. Click the `preview/save` button - it will download the svg of the plot

To Do:
- [x] display either the original canvas or the svg'd canvas in the whitespace (not sure why this is happening)

Notes:
* canvas2svg apparently works with node-canvas, so if the other work getting node-canvas integrated works, then we should be able to programatically get out png or svg
* the addition of canvas2svg increases bokeh.js from 1649KB to 1691KB (an increase of 42KB)

### CODE REVIEW

**Comment by birdsarah** [comment]
This is ready for review and as far as I can tell is working.

Functionality notes:
* There are some glyphs that don't work due to the limitations of canvas2svg
* Interaction works although it's very slow - on each render the new svg file is rendered to the screen, as a result, you can interact with the plot and save an interacted version
* There are intermittent grey lines at the borders that come and go and are not wanted

For code review:
* This was done quickly, happy to hear what the "right" way of setting an svg mode and testing if it's on is

**Comment by birdsarah** [comment]
Given that this isn't perfect, but is a highly desired feature - we could maybe add it as "experimental" support or something like that.

**Comment by birdsarah** [comment]
To see which glyphs are (not) supported: https://rawgit.com/birdsarah/bokeh-miscellany/master/test_svg_on_glyphs.html?svg=1

To see normal bokeh performance: https://rawgit.com/birdsarah/bokeh-miscellany/master/test_svg_on_glyphs.html

**Comment by birdsarah** [comment]
Marking this as WIP because @bryevdv has much better ideas of how it should be structured and is doing some work to support that.

**Comment by bryevdv** [comment]
superseded by #3867 (reopen if I am mistaken)

**Comment by birdsarah** [comment]
:person_frowning:  you superceded this with itself?

**Comment by humm** [comment]
So I am testing the feature (great work! absolutely fantastic!), and it seems to work only when output_file is called in `inline` mode, whereas the default seems to be `cdn` (I have *no idea* what the `inline` and `cdn` are, just figured out that `inline` worked). Is that by design?

**Comment by birdsarah** [comment]
@humm - see: http://bokeh.pydata.org/en/latest/docs/reference/io.html#bokeh.io.output_file `cdn` and `inline` refer to where bokehjs gets loaded from. `cdn` would definitely not be expected to work because this branch is not in a published release of bokeh. I was going to point you to an explainer in the docs (http://bokeh.pydata.org/en/0.11.0/docs/user_guide/quickstart.html#resources) and discovered the docs are wrong (the default is now `cdn`) - so thanks for bringing this up!!!! :D

**Comment by guillochon** [comment]
This is great and I hope it makes it into the release soon!

**Comment by bryevdv** [comment]
@birdsarah I am gong to close this PR but keep the branch for reference (in anticipation of a future version of this after the layout work)

**Comment by Horta** [comment]
That is a great feature!

**Pull request closed without merging**
