### PR TITLE
add cartodb tile provider

### LINKED ISSUE #4775: [feature] add Cartodb positron tile provider
See

https://carto.com/location-data-services/basemaps/

for an example.

PR upcoming

### PR DESCRIPTION
**Pull request by sanga**
- [x] issues: fixes #4775
- [ ] tests added / passed: tile_providers aren't currently tested so far as I can tell and I'm not sure how I would test this at the moment?
- [ ] release document entry (if new feature or API change) -  would you like a release notes entry (seems kinda minor to me)?

Note: I assume retina or non-retina could be detected somehow on the fly and switched. But this is useful as it is at least for me.

### CODE REVIEW

**Comment by bryevdv** [comment]
@sanga I would suggest that a new example that exercises the new tile providers would be sufficent for testing for now. However, a new jq-ui version breaks things. I have a PR to pin to the old versions, you will need to merge master into this PR once the fix is in master, in order to get tests passing. 

Regarding docs, it would actually be nice to add doc comments to everything in `tile_providers`.  You can see an example of doc comments here:

https://github.com/bokeh/bokeh/blob/master/bokeh/core/enums.py#L80

If you have the time to add some doc comments with a few words about the module contents, it would be very nice, but I would not hold up this PR for it.

**Comment by bryevdv** [comment]
Ok, the jqui version pin PR is merged. If you merge master into your branch, expected tests should start passing.

**Comment by sanga** [comment]
Sounds all fine. To be clear: you'd rather I merge master than rebase.... (I usually always rebase to leave history cleaner)

**Comment by bryevdv** [comment]
@sanga the example actually needs to output an html file with the right name (`airports_map.html` in this case) or else the example CI test will fail. Currently there is no output file being created because you removed the `show` command. If you want to show both in one example, you'll need to put both plots in a layout of some sort (e.g. a `Row` or `Column` and `show` that).

**Comment by bryevdv** [comment]
Alternatively, could restore the original `airports_map.py` and add a completely new example to show off the cartodb tiles.

**Comment by sanga** [comment]
Let's try that. That produces the correct result when I run python airport_map.py (i.e. gives me a correct airports_map.html)

**Comment by bryevdv** [comment]
LGTM

screen shot 2016-07-09 at 4 26 50 pm

ping @jbednar FYI cartodb seems to work great

**Comment by bryevdv** [comment]
Thanks @sanga !

**Comment by jbednar** [comment]
Looks great!

**Pull request merged**
