### PR TITLE
Remove redundant toctrees

### LINKED ISSUE #10465: [TASK?] docs/{release,installation}.rst have empty toctrees, which can be removed
The empty toctree directive in docs/release.rst results in adding an empty `<ul>` element to it, which is a no-op under the current Sphinx theme. Thus this directive is a no-op and can be removed to simplify the file.

### PR DESCRIPTION
**Pull request by pradyunsg**
Fixes #10465

### CODE REVIEW

**Comment by pradyunsg** [comment]
Ooops. Sorry for the noise!

**Comment by bryevdv** [comment]
@pradyunsg apologies but our default branch was incorrectly set to `main`, can you rebase or resubmit againt `branch-2.3`?

**Comment by pradyunsg** [comment]
Hmm... I'll need to rebase as well, which needs me to pick up a laptop. I'll do that later today. :)

**Comment by bryevdv** [comment]
@pradyunsg just checking in will you be able to rebase this PR?

**Comment by bryevdv** [comment]
@pradyunsg No worries if you are not able to continue at this time, but just a heads up, I will close this PR at the end of the week as part of general repo housecleaning

**Comment by pradyunsg** [comment]
Oh hey. It's probably easier to start fresh now. Thanks for the heads up @bryevdv! ^>^

**Comment by bryevdv** [comment]
Thanks @pradyunsg !

**Pull request closed without merging**
