### PR TITLE
Fix serialization of typed arrays

### LINKED ISSUE #10153: [BUG] Typed Arrays returned as dicts
Run `examples/howto/events_app.py`. For a lasso selection the `"x"` and `"y"` arrays are returned as dicts:

```
selectiongeometry(geometry={
    "type":"poly",
    "sx":[544,533,531,527,526,526,531,534,545,555,564,570,570],
    "sy":[135,142,145,152,160,165,184,191,201,205,208,210,210],
    "x":{"0":99.67,"1":97.43,"2":97.02,"3":96.21,"4":96,"5":96,"6":97.02,"7":97.63,"8":99.88,"9":101.92,"10":103.75,"11":104.98,"12":104.98},
    "y":{"0":79.95,"1":78.6,"2":78.02,"3":76.68,"4":75.14,"5":74.17,"6":70.51,"7":69.16,"8":67.24,"9":66.47,"10":65.89,"11":65.5,"12":65.5}
}, final=false)
```

Have seen Typed Arrays get represented in this format it other contexts. I would not be surprised to learn that this is a general issue in other places as well. It would be nice to return as "ndarray" types but would also settle for plain lists. 

cc @mattpap

### PR DESCRIPTION
**Pull request by mattpap**
- [x] unit tests

fixes #10153

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap is there a reason not to put this in 2.1.1 ? This bug is actually blocking some other work for me.

**Comment by mattpap** [comment]
This depends on PR #10109, which should be merged into a patch release. If you want just the serialization part fixed in 2.1.1, then the first two commits would have to be cherry picked.

**Comment by bryevdv** [comment]
OK I will that's a little more delicate surgery than I would prefer, but it would be very good to have this fixed in 2.1.1 so I will have a go at picking the first two commits and testing it out

**Comment by bryevdv** [comment]
@mattpap do you still have this branch locally? Can you push it back up to GH so I can pick the individual commits?

**Pull request merged**
