### PR TITLE
move vbox and hbox to top since they are layouts on coffee layer

### PR DESCRIPTION
**Pull request by fpliger**

### CODE REVIEW

**Comment by mattpap** [comment]
Good catch. @fpliger, can you move this to `layout.less` and include it in `main.less`?

**Comment by fpliger** [comment]
@mattpap sure... good suggestion to keep it sane :)

Will do it push back

**Comment by canavandl** [comment]
LGTM. ping @mattpap

**Comment by mattpap** [comment]
Yes, LGTM.

**Comment by canavandl** [comment]
thanks matt

**Pull request merged**
