### PR TITLE
Fix broken werkzeug import in bokeh-server

### PR DESCRIPTION
**Pull request by ogrisel**
From: http://stackoverflow.com/questions/28241579/error-when-trying-to-run-bokeh-server

### CODE REVIEW

**Comment by damianavila** [comment]
LGTM

**Comment by damianavila** [comment]
We can probably ask newer version with the requirements... but 0.10.1 is very young yet... so I think this strategy is better for now... let's merge it!

**Comment by ogrisel** [comment]
:beers:

**Comment by damianavila** [comment]
Thanks for your contribution @ogrisel :+1:

**Pull request merged**
