### PR TITLE
Add password input

### PR DESCRIPTION
**Pull request by mauhcs**
This branch adds a Input text for passwords.

- [ ] issues: fixes ##6492
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@mauhcs thanks for the PR, there seems to be a lot of diff cruft. Can you rebase on current master?

**Comment by mauhcs** [comment]
Ah, I see. I got caught in the middle of changes in the master.
I am afraid to mess up the whole history with my not so great git skills. I am still trying to get my mind around rebase. Any specific git command I should run? (sorry)

**Comment by bryevdv** [comment]
@mauhcs actually with the PRs I just merged, there is also now a conflict. Probably easiest to just do a `git pull` on master to get up to date, then make an entirely new branch/PR, does that sound ok?

**Comment by mattpap** [comment]
This also needs a rewrite  to not use jquery and other stuff removed in PR #6335. However, looking at the proposed implementation it looks wasteful, because it fully implements new model and just changes `input`'s `type`. This can be simplified to pretty much:
```
class PasswordInputView extends TextInputView
  render: () ->
    super()
    @inputEl.type = "password"
class PasswordIInput extends TextInput
  type: "PasswordInput"
  default_view: PasswordInputView 
```

**Comment by bryevdv** [comment]
superseded  by #6534

**Pull request closed without merging**
