### PR TITLE
Render widgets and widget box correctly

### PR DESCRIPTION
**Pull request by birdsarah**
This PR takes care of some clean-up that should have been done before, and fixes a bug in widgetbox rendering. Fixes: #4601, #4636, #3346

1) All widgets should not pollute their widget wrapper. The widget wrapper looks something like this `<div id="1234" class="bk-widget bk-layout-fixed">` and may have a width/height/x/y position. All html and classes related to the widget should be inside this box for predictable widget results. I did some of this during the layout PR, but forgot to go back and clean-up the others.  (I'm leaving data_table as an exception to this as it's very complicated and I wouldn't want to break it, and I think it'll be ok).
2) I have fixed some rendering issues with the WidgetBox. Some of this was due to bugs introduced by the initialization PR, I also now set a sensible default for a fixed widgetbox (which has some implications, but is overall a good thing).

There's also some small clean-up of the `buttons_server.py` example, which could have been in a different PR, but snuck in here.

### CODE REVIEW

**Comment by birdsarah** [comment]
@bryevdv, this PR is not as bad as it looks, and I'm happy to do a pair review to talk you through it.

It does leave a known corner case: https://github.com/bokeh/bokeh/issues/4653

I think it really improves the widget layout experience. In particular, if things don't auto-magically line-up there's much better support for just setting a width/height to be what you want it to be.

@bgyarfas if you're able to take a look at this and see if we're doing better compared to your attempts with widgets yesterday, that'd be great.

**Comment by birdsarah** [comment]
I've restarted the unit tests a couple of times, am being plagued by the flaky solver stub problem in the JS tests.

**Comment by bryevdv** [comment]
@philippjfr can you evaluate this quickly wrt holoviews? I'd like to merge it but not without an assessment from you first

**Comment by philippjfr** [comment]
Just went through all our examples and encountered two small regressions, which weren't there yesterday (in 0.12.0rc2).

Here is a gridplot containing Tabs, which has shifted downwards and now overlaps a little bit:

image

And here are two Tables placed side-by-side, also now overlapping:

image

Otherwise it seems to work okay. Apologies I can't send small self-contained examples but these are generated from within HoloViews. Happy to confirm whether they are working if you come up with a fix though.

**Comment by bryevdv** [comment]
how does holoviews construct those? Maybe there is a better way

**Comment by bryevdv** [comment]
For the tables, I think they have a default size of 600 now, which is a compromise for other fixes. Maybe setting the size on the table explicitly would help with that issue

**Comment by philippjfr** [comment]
>For the tables, I think they have a default size of 600 now, which is a compromise for other fixes. Maybe setting the size on the table explicitly would help with that issue.

Our default Table width is set to 400, but they overlap no matter what I set the width to.

**Comment by philippjfr** [comment]
>how does holoviews construct those? Maybe there is a better way

HoloViews at least for now constructs all it's layouts by supplying list of lists to ``gridplot``. We are looking to improve that in future, now that bokeh supports more powerful layouts, but it seems like ``gridplot`` should just work.

**Comment by bryevdv** [comment]
@bokeh/dev if the Holoviews issues can be identified and are small, I propose this as last PR to be considered and then to evaluate an RC3 with it. The fixes here are substantial enough to warrant consideration in this otherwise quiet period.

**Comment by bgyarfas** [comment]
Probably tangential, but I'm finding myself wanting to put in `Spacer` in between widgets in the context of `row` or `column`. I realize this is probably just equivalent to being able to set the `padding` in a  `bk-grid-row` or `-column` if the children widget-boxes would inherit that parameter. For clarity, I'm just thinking in the context of `sizing_mode='fixed'`. 
What are your thoughts on being able to implement something like this?

**Comment by birdsarah** [comment]
@bgyarfas - I would use spacers for now and open an issue to discuss your use case. generally speaking things don't cascade in the bokeh layout, its a calculated, effectively absolute positioned, set of layouts.

**Comment by birdsarah** [comment]
we're pretty far out of expected use cases here, but wrapping things in widget boxes and specifying widths solves all the overlapping stuff for me. 

The alignment of a plot next to a tabbed set of plots in a grid plot is not expected to work. It had never occurred to me that someone would try to do this.

**Comment by birdsarah** [comment]
> The alignment of a plot next to a tabbed set of plots in a grid plot is not expected to work. It had never occurred to me that someone would try to do this.

I mean I think it would be cool if it did. But there are other layout issues with tabs that we'd already punted to after 0.12.0 so I would put this in that bracket too: https://github.com/bokeh/bokeh/issues/4404

**Comment by bryevdv** [comment]
OK, @philippjfr with the info above do you think you can make simple changes in Holoview to accommodate? If so, I'd say we proceed with this PR

**Comment by philippjfr** [comment]
>we're pretty far out of expected use cases here, but wrapping things in widget boxes and specifying widths solves all the overlapping stuff for me.

Yes, I've solved it too now, had to write a crazy expression that will unpack the lists of lists and get the width for each element in the plot. Doing that I can add ~10% padding to ``Tabs`` and ``Tables``, which solves the overlaps. Thanks a lot for your help!

>The alignment of a plot next to a tabbed set of plots in a grid plot is not expected to work. It had never occurred to me that someone would try to do this.

Someone will always try something crazy and in holoviews that plot can be expressed with just this:

```python
%%opts Overlay [tabs=True width=600 height=600]
x,y = np.mgrid[-50:51, -50:51] * 0.1
img = hv.Image(np.sin(x**2+y**2), bounds=(-1,-1,1,1))
img.relabel('Low') * img.clone(img.data*2).relabel('High') + img
```

which means the barrier to doing crazy things like this is low. If we can get that to work at some point I'd be very happy but definitely shouldn't hold up this release.

**Comment by bryevdv** [comment]
OK, let me check this PR out locally and do some testing. I expect to merge it in a few hours

**Comment by philippjfr** [comment]
>OK, @philippjfr with the info above do you think you can make simple changes in Holoview to accommodate? If so, I'd say we proceed with this PR

Yes, please proceed. Didn't know ``WidgetBox`` would be required for padding but I can make it all work now. Either way it's a huge improvement, couldn't even put a ``DataTable`` in a gridplot before.

**Comment by bryevdv** [comment]
OK tested all apps, several file and notebook examples, and JS api examples. All look good. Will merge this PR and cleanup PR and then cut an RC

**Pull request merged**
