### PR TITLE
Add facet tab to Crossfilter

### PR DESCRIPTION
**Pull request by rothnic**
This was quickly done in response to #1768. Basically, I'm just wrapping the previously highest level plotting method and passing down a single facet per tab, which is then getting used to filter the data further.

I want to take a better look at it to see if I can make the "getting filtered data" and "getting facets" a bit more consistent. I think I have a bug left there in the 2d one as well, but haven't tested it yet.

[Here are some screenshots](http://imgur.com/a/MemMe) of it working.

### CODE REVIEW

**Comment by rothnic** [comment]
Last couple commits have this working. A key change is that sharing the range between the faceted plots makes this look a lot more like what you'd see with ggplot. First, all are seen against the same scale, so you can spot the different subsets of data immediately. Second, empty plots look identical to non-empty ones. You can see the difference between comparing the previously linked screenshots and this one:
image

For now, bar chart doesn't yet share the range since it was handled differently than the others.

**Comment by bryevdv** [comment]
AWESOME

**Comment by damianavila** [comment]
:clap:

**Comment by bryevdv** [comment]
Maybe a smaller, bolded font or the facet subplot titles? That might make them pop out more. Also, now that everything is on the same range (been meaning to do that for ages) the axes on the interior plots could be left off. This is great!

**Comment by bryevdv** [comment]
I might also be nice to have the are where the plots are, plus the plots themselves, have some softer very light grey color? Not sure.

**Comment by bryevdv** [comment]
ping @Discalced51

**Comment by rothnic** [comment]
@bryevdv yes on hiding the internal axes. That is on my list of things to look into. I think that would make it look a lot cleaner. If we weren't wrapping, then the labels could go on the outside of the grid. Or, they could for just the 2d case.

One big change I'm working on is that I realized I need to abstract out the plot types from crossfilter, due to having to manually manage each of the three types internally so much. Instead of adding more conditional statements in Crossfilter to handle the bar chart's range for faceting, I factored out each plot into a wrapper class. 

I'm leaning towards it shouldn't be a descendent of PlotObject, so for now it is just a stand alone class called CrossFilterPlot. The reason I say it might not be is that the class is more specific to the interface of creating a plot for crossfilter, than just creating a plot. I'm definitely open to thoughts on that. 

This defines the interface for the different functionalities that are required and some default behavior, then the subclasses should be consistently usable internal to CrossFilter. This would make it much easier to integrate a new chart type into crossfilter. Hopefully, I'll commit an initial version tonight. It is working, I just need to work out some small issues.

**Comment by bryevdv** [comment]
@rothnic At one point I had barely started along an effort to re-factor the crossfilter, you are basically proposing the exact same cleanup I had in mind, but did not have time to dive into. I do think that the cross filter controller object probably does not need to be a `PlotObject`, it needs to contain and coordinate them.  Thanks for all the effort, folks are going to be very excited to see all the improvements!

**Comment by rothnic** [comment]
@bryevdv could you point me in the direction for how to hide an axis? 

I committed the referenced class to contain the plotting functionality. It might be good to put those into a separate file. I'll add some comments.

**Comment by rothnic** [comment]
This is a sketch of what I'm thinking the faceting should look like, but couldn't figure out how to leave the shared ranges as is, then only hide the internal axis ticks, borders, and labels.

**Comment by bryevdv** [comment]
@rothnic The best solution is just not to add Axes at all to the internal plots in the grid, but there is a PR open to add a `hide` attribute to axes that should be merged soon.

**Comment by bryevdv** [comment]
No worries. :)

**Comment by rothnic** [comment]
Here is the sketch of what I was thinking, with no preference on grid lines/background color. @bryevdv , the issue I had was that I looked through Figure for how I might hide the axis, but couldn't find a way to hide the axis components while leaving the grid lines.

If I pass in x_axis_location = None, I get nothing but the toolbar. If I pass in x_axis_type = None, then it still plots, just without grid lines.

grid

**Comment by bryevdv** [comment]
Ultimately this might be better to do with the lower level models interface, because it would offer more control. 

The "right" thing to do:
* add axes only to the outside plots
* add grids to all the plots, explicitly using the tickers from the outside axes

Check out: https://github.com/bokeh/bokeh/blob/master/examples/glyphs/iris_splom.py 

We can save this until later tho, for the time being we can just hide the axes, once the hide PR is ready.

**Comment by rothnic** [comment]
Gotcha, after poking around a bit more, I can also for the time being manually change the properties of the axis. For example, after plotting, if I get the x axis, then set x_axis.major_label_text_alpha = 0.0, then the text disappears. Though, this also means that the text is still there taking up space.

I think it wouldn't be too difficult to do what you are saying.

**Comment by rothnic** [comment]
Here is the 1d and 2d grid with the axis components hidden. This was done as described, by setting the alpha of the components I wanted to hide. Note: on the 1d method I had to make sure that on the second to last row that any grid positions without a plot below them did not have the x axis hidden.

image

image

**Comment by rothnic** [comment]
Latest commit includes the hidden axis as described by setting alpha. Can update to a more appropriate method when available, or reworked to use lower level plotting.

**Comment by bryevdv** [comment]
For now you might try setting the font size to 0 and min_border to 0 (or something small) that might eat up some of the space too.

**Comment by rothnic** [comment]
The only issue with making the font size 0 is that it messes up with the wrapped 1d faceting. If it isn't a perfect grid you get this:

image

**Comment by bryevdv** [comment]
You could try also having a small but non zero min border setting.

**Comment by rothnic** [comment]
I ended up just removing the axis on the "hanging" plot when wrapped after referencing [ggplot facet_wrap](http://docs.ggplot2.org/0.9.3.1/facet_wrap.html). I think it makes things too complex.

I think this is getting pretty close. There are some other things I'm looking at doing to it, but aren't related to this feature. This is what it looks like at the moment: [screenshots](http://imgur.com/a/yYL5J)

**Comment by rothnic** [comment]
This is ready for review, along with the following observations:

1. The title font is centered on the entire plot, instead of just the grid part of the plot. (good/bad?)
2. There is a grey border around each grid, except for the right side. Why is that?
3. What would be the desired behavior if I detected too many facets? What number is too much for too many facets? For example, if you use the name column as the facet column, then it pretty much doesn't come back. This could wait till later.
4. After running for some time, it seems to become exponentially slower to update. Do I need to be managing/reusing objects? Seems specific to tabbed faceting and debugging, so I don't know if it is the debugger, or just that the debugger making things slower makes it obvious earlier.
5. Brushed selection/filtering works, but isn't visible for me. I checked for the linked brushing example and it exists for that as well. I merged in latest changes and I believe that is why the build is failing.

**Comment by bryevdv** [comment]
@rothnic the "outline border" issue may be fixed on master, though I though that fix was already merged before this PR. Perhaps it was not fixed enough...

It's possible that some cleanup needs to be done, but let's make performance enhancements (and I'd lump "too many facets" in with this) a separate, dedicated PR for that. 

I am confused a bit about the last point, if selection isn't visible then it isn't working? :) Are you saying the example in `plotting/file` is broken too?

**Comment by rothnic** [comment]
@bryevdv To make sure it wasn't me, I checked out master, then rebuilt everything. I then ran bokeh-server, then ran linked_brushing.py from examples/plotting/server/. What I mean is that when I try to select, I see output from the bokeh-server process (updating, done, saving, etc.), but I don't see the visual results of the selection. I went back to the point on master where I created my initial crossfilter branch that has already been merged, and the brushing worked.

In crossfilter, I get the same results with the filter widget. However, the data is filtered because a new ColumnDataSource is created during the selection event, and the selection values are available. It just seems that the visual impact of the selection isn't applied on the view side.

**Comment by bryevdv** [comment]
OK I am not sure hat might have introduced such a problem, I will try to do a quick bisection.

**Comment by rothnic** [comment]
Yeah, I looked through the history and couldn't see what would have done it. So I went back to thinking it was me, but reproduced it on my mac laptop. The really strange thing is that if I go back far enough that it works, I don't have to rebuild bokehjs to get it to work. It appears to be on the python side, but nowhere could I find an issue with it.

**Comment by bryevdv** [comment]
Looks like it was this: https://github.com/bokeh/bokeh/commit/7af50c4dc2dd9c2335a7a8a7855a4bb2f90bc6d2

@mattpap there were a few changes to low-level machinery to support the autodocs. Does anything jump out at you as something that could cause problems on the server?

**Comment by bryevdv** [comment]
i will also not that it is odd, rebuilding BokehJS or not does not seem to matter. Older revisions work even with the newer BokehJS.

**Comment by bryevdv** [comment]
`git bisect` leads me to this:
```
bryan@laptop (git:(6f3b398...)|BISECTING) ~/work/bokeh $ git bisect good 
be5d6505355b64efa7c6b8dea13fea5eeec593bb is the first bad commit
commit be5d6505355b64efa7c6b8dea13fea5eeec593bb
Author: Bryan Van de Ven <bryanv@continuum.io>
Date:   Fri Jan 23 22:09:40 2015 -0600

    model docs, first installment

:040000 040000 c066da0deee8d04d4c2c02256997fc4a6fcc731f b4f50f5c542a7f6ae70bd72e18d6b0a56725c031 M	bokeh
``` but this is my first real attempt at using it. Still investigating. This is the apparently bad commit: https://github.com/bokeh/bokeh/commit/be5d6505355b64efa7c6b8dea13fea5eeec593bb

**Comment by bryevdv** [comment]
Yup, the `use_prefix` broke it somehow. This patch fixes:
```
diff --git a/bokeh/models/markers.py b/bokeh/models/markers.py
index 4944fc3..48c8dca 100644
--- a/bokeh/models/markers.py
+++ b/bokeh/models/markers.py
@@ -8,7 +8,7 @@ from .glyphs import Glyph
 from ..mixins import FillProps, LineProps
 from ..properties import DataSpec, Include
 
-class Marker(Glyph):
+class Marker(Glyph, FillProps, LineProps):
     """ Base class for glyphs that are simple markers with line and
     fill properties, located at an (x, y) location with a specified
     size.
@@ -34,13 +34,13 @@ class Marker(Glyph):
     "screen space" units by default.
     """)
 
-    line_props = Include(LineProps, use_prefix=False, help="""
-    The %s values for the markers.
-    """)
+    # line_props = Include(LineProps, use_prefix=False, help="""
+    # The %s values for the markers.
+    # """)
 
-    fill_props = Include(FillProps, use_prefix=False, help="""
-    The %s values for the markers.
-    """)
+    # fill_props = Include(FillProps, use_prefix=False, help="""
+    # The %s values for the markers.
+    # """)
```
@mattpap  any comment? If we have to revert the `Marker` def and leave those props out of the reference for now, I guess that's ok. Any fix for this needs a regression test.

**Comment by bryevdv** [comment]
Wel, I don't think we should hold up this PR, the other issue will be fixed separately.

**Pull request merged**
