### PR TITLE
Replace flexx.pyscript with pscript

### LINKED ISSUE #7576: Use pscript instead of flexx.pyscript
I'm in the process of spinning out a few projects from Flexx, one of which is [PScript](https://github.com/flexxui/pscript), formerly `flexx.pyscript` (I had to change the name to work around a name conflict on pypi). 

For Bokeh (and its users) this would be a much easier dependency because it still works on Python 2.7 (Flexx itself does not anymore) and is simply much smaller. Note: I have not made a conda-forge feedstock yet, but will soon.

This is meant as a heads up, but I might have a go myself if I can find the time and nobody beats me to it.

### PR DESCRIPTION
**Pull request by mattpap**
This will have to wait for @almarklein to publish a conda package for `pscript`.

fixes #7576

### CODE REVIEW

**Comment by almarklein** [comment]
I'll try to do it this week :)

**Comment by bryevdv** [comment]
Noting: will need merge/rebase on master after #7732

**Comment by almarklein** [comment]
Ok, this week then :) I have a PR on conda-forge, now only need to fix an annoying Circle CI permission issue. Hope to get it by tomorrow.

**Comment by almarklein** [comment]
The feedstock is up!

**Comment by bryevdv** [comment]
> The feedstock is up!

Does that mean it should be installable, or are there still other steps?
```
(base) ❯ conda install -c conda-forge pscript
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pscript

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://conda.anaconda.org/bokeh/osx-64
  - https://conda.anaconda.org/bokeh/noarch
```

**Comment by bryevdv** [comment]
time delay I guess, seems to be working now

**Comment by bryevdv** [comment]
FFS what now
```
tests/examples/test_examples.py::test_js_examples[/home/travis/build/bokeh/bokeh/bokehjs/examples/anscombe/anscombe.html-example0] 
[FAIL] Cannot connect to browser:  { Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }
```

@mattpap not sure why the build is on fire ten different ways today... will try to restart a old working build to see if this is isolated to this PR or not. @almarklein can you merge master and push just in case that is something?

**Comment by bryevdv** [comment]
@almarklein sorry nevermind, I thought this was your PR :)

**Pull request merged**
