### PR TITLE
Update _line_stack to enable correct work on DataFrames

### LINKED ISSUE #10067: [BUG] _line_stack() doesn't accept np.ndarray in stackers argument
**Description of problem**
`varea_stack()` and `vline_stack()` process the `stackers` argument differently: the former takes `list`, `np.ndarray`, while the latter only takes `list`. This also holds for `harea_stack()` and `hline_stack()`. 

**Possible solutions**
For `_line_stack()`, doing `stackers=list(stackers)` in `plotting/figure.py` fixes the issue.

**Additional context**
```
np.random.seed(seed=10)
df = pd.DataFrame(np.random.randint(10, 100, size=(10, 10))).add_prefix('y')
p = figure(
    x_range=(0, len(df)-1),
    y_range=(0, 800),
    height=300, 
    width=300
)
```

1. `varea_stack()` with a `pandas.core.indexes.base.Index`
```
p.varea_stack(
    stackers=df.columns,
    x='index', 
    color=brewer['Spectral'][10], 
    source=df
)
show(p)
```
image

2. `vline_stack()` with a `pandas.core.indexes.base.Index`
```
p.vline_stack(
    stackers=df.columns,
    x='index', 
    color=brewer['Spectral'][10], 
    source=df
)
show(p)
```
```
RuntimeError: 

Expected y to reference fields in the supplied data source.

When a 'source' argument is passed to a glyph method, values that are sequences
(like lists or arrays) must come from references to data columns in the source.
```

3. `varea_stack()` with `list`
```
p.varea_stack(
    stackers=list(df.columns),
    x='index', 
    color=brewer['Spectral'][10], 
    source=df
)
show(p)
```
image

4. `vline_stack()` with `list`
```
p.vline_stack(
    stackers=list(df.columns),
    x='index', 
    color=brewer['Spectral'][10], 
    source=df
)
show(p)
```
image

### PR DESCRIPTION
**Pull request by mosc9575**
- [ ] issues: fixes #10067

This change enables the stacker method for CDS and DataFrames. This method is not able to work with a Series, I think this is ok, because there is nothing to stack with information for only one line. 

Right now no tests are added, but I am interested to contribute.

### CODE REVIEW

**Comment by bryevdv** [comment]
@mosc9575 Thinking about this a little more I am slightly concerned it may have some rough cases. Specifically, something liek
```
x='index', 
```
is actually shorthand for 
```
x = {field: 'index'}
```
So if we just check for strings then that lower-level case will not be handled properly. I think would also just sit better with me to check for the *affirmative presence* of stacker types, rather than checking implicitly for non-stacker types. 

Would you mid experimenting a bit? I might suggest that instead of checks like `isinstance(y, (list, tuple))` make a new function `is_stacker(val)` that checks for those or for numpy arrays, and *optionally, if pandas is installed* for pandas series. What do you think?

**Comment by mosc9575** [comment]
Well, I know there is no rush so I can try something. In the first place I added `pd.DataFrame` to  `isinstance(y, (list, tuple))` which was also working, but I didn't know your rules on external liberies. So I thought is is better to use only build ins.

**Comment by mosc9575** [comment]
Thank you. This is very helpful.

**Comment by mosc9575** [comment]
I habe a question and I had a related one on my last issue. If I modify bokehJS source code adding some `console.log()` I can't see any prints in the console. I know I have to enable `BOKEH_RESOURCES=inline`.

I am usually using JupyterNotebooks and I tryied
```
from bokeh.settings import settings
settings.resources = 'inline'
```
and also
```
from bokeh.resources import INLINE
output_notebook(resources=INLINE)
```

What am I doing wrong?

**Comment by bryevdv** [comment]
@mosc9575 Just to be clear `console.log` show up in the browser's JavaScript console, and not e.g. in the shell console where the notebook was run. But this would be a better question to continue on the Discourse since it is not related to this issue/PR https://discourse.bokeh.org

**Comment by mosc9575** [comment]
I see your point and know this is very costly. I will learn how to test on my PC.

**Comment by mosc9575** [comment]
**Summary**
 In this post I want to summarize what has changed so far. This examples may lead to the needed tests.
For the test one DataFrame `df` and one Series `s` in defined, where `s` is the first column of `df`:
 ```
df = pd.DataFrame(np.random.randint(10, 100, size=(10, 10))).add_prefix('y')
s = df['y0']

>>>df
    y0  y1  y2  y3  y4  y5  y6  y7  y8  y9
0  91  19  47  59  70  58  78  65  98  38
1  76  50  84  41  68  88  73  67  47  93
2  84  48  11  57  43  46  68  17  57  48
3  83  45  14  54  15  75  13  66  97  54
4  33  28  10  34  25  44  90  36  36  79
5  44  39  30  20  85  74  84  62  93  34
6  10  87  75  90  49  91  91  32  79  92
7  18  38  58  10  94  83  81  84  27  90
8  50  70  49  67  17  75  92  60  11  64
9  30  79  51  58  77  47  12  79  73  75
```

I tried to allow a PandasSeries as an source. This also has an inpect on other objects not mentioned in the original post [#11244](https://github.com/bokeh/bokeh/issues/10067)

**Lines**

|No Source|DataFrame as Source|Series as Source (__new__)|
|:---|:---|:---|
|```p.line(y=s.values, x=s.index)```|```p.line(y='y0', x='index', source=df)```|```p.line(y='y0', x='index', source=s)```|

All three examples generate this figure:

Line Plot

**vline_stack**
|complete DataFrame as Source|subsample by colum names of DataFrame as Source|Series as Source (__new__)|
|:---|:---|:---|
|```p.vline_stack(stackers=df, x='index', color=brewer['Spectral'][10], source=df)```|```p.vline_stack(stackers=['y1', 'y8'], x='index', color=brewer['Spectral'][10][:2], source=df)```|```p.vline_stack(stackers='y0', x='index', source=s)```|
|stack_10|stack_2|stack_1|

**varea_stack**
|complete DataFrame as Source|subsample by colum names of DataFrame as Source|Series as Source (__new__)|
|:---|:---|:---|
|```p.varea_stack(stackers=df, x='index', color=brewer['Spectral'][10], source=df)```|```p.varea_stack(stackers=['y3','y9'], x='index', color=brewer['Spectral'][10][0:2], source=df)```|```p.varea_stack(stackers=['y0'], x='index', color=brewer['Spectral'][10][0], source=s)```|
|varea_stack_10|varea_stack_2|varea_stack_1|

Is there something which should be added?

**Comment by bryevdv** [comment]
@mosc9575I am having laptop issues and my dev environment is not set up after a full clean install. But I am not quite certain how the about code snippets show that the issue #10067 is addressed? The problem there was the line
```
stackers=df.columns
```
because `df.columns` is a pandas series and the processing of `stackers` only expected a list or tuple. That does not have anything directly to do with the contents of the CDS at all, and I am not sure how adding a convenience initializer for pandas series helps. 

The code examples above don't exercise stackers supplied in a pandas series, AFICT. Here is a complete script that needs to function for this issue to be addressed:
```python
import pandas as pd
import numpy as np
from bokeh.plotting import figure, show
from bokeh.palettes import brewer

np.random.seed(seed=10)
df = pd.DataFrame(np.random.randint(10, 100, size=(10, 10))).add_prefix('y')

p = figure(x_range=(0, len(df)-1), y_range=(0, 800))
p.vline_stack(
    stackers=df.columns,
    x='index',
    color=brewer['Spectral'][10],
    source=df
)
show(p)
```
While I am not set up to test this directly can you report whether your PR changes allow the above to function?

If not I think it's worth revisiting the earlier comments, about modifying the `isinstance` check as the path to a solution. I am not sure a convenience initializer for Pandas series is warranted.

**Comment by mosc9575** [comment]
@bryevdv Thanks for your reply. I have forgotten to push my latest changes. The example you have shared is working on my machine.

Right now the solution I want to use is a new function named `stacker_to_list`

```
def stacker_to_list(value):
    if pd:
        if isinstance(value, pd.DataFrame):
            value = value.columns.to_list()
        elif isinstance(value, pd.Series):
            value = [value.name]
        elif isinstance(value, pd.Index):
            value = value.to_list()
    if isinstance(value, str):
        value = [value]
    return value
```

in combination with 
```
source = kw.get('source', None)
if source is not None and not isinstance(source, ColumnDataSource):
    kw['source'] = ColumnDataSource(source)
```
in each stacker function. In this way I will allways have a CDS and a list, which was allready working.

**Comment by mosc9575** [comment]
The output for our example with the latest version of the code is 

stacker for df

which looks valid. I want to mention that `_line_stack` is also effected by that issue [#9568](https://github.com/bokeh/bokeh/issues/9568). If there are `NaN` values in the DataFrame `df` the stacker breaks apart.

The code block below was added 3 times ([example](https://github.com/mosc9575/bokeh/blob/c2b594d11af0c8f4c452687a551bc5f82c953076/bokeh/plotting/figure.py#L459-L461)). Whta do you think, is this a valid way of solving the problem and should be this a independent function?

```
source = kw.get('source', None)
if source is not None and not isinstance(source, ColumnDataSource):
     kw['source'] = ColumnDataSource(source)
```

**Pull request closed without merging**
