### PR TITLE
Updated colors of Band Plots

### PR DESCRIPTION
**Pull request by BhaswatiRoy**
addresses: https://github.com/bokeh/bokeh/issues/11481

Formatted colors of the Band Plot to Purple & Yellow, with a good contrast ratio

image

### CODE REVIEW

**Comment by bryevdv** [comment]
Thanks for the PR @BhaswatiRoy what do you think about the following pair? They report as PASS but are much less jarring (to me) than the bright pure primary colors

Screenshot 2023-03-07 at 22 13 39

**Comment by BhaswatiRoy** [comment]
Hello @bryevdv 
I tried to improve the contrast ratio to 13.19:1, by using these colors. 

image

And the plot looks like this

image

**Comment by bryevdv** [comment]
Hi @BhaswatiRoy thanks for your patience, we've been having some discussions about making expectations around this task more consistent. I think the latest iteration would be OK but we do have a section in the docs dedicated to some palettes that were designed with accessibility in mind:

https://docs.bokeh.org/en/latest/docs/reference/palettes.html#accessible-palettes

Would you mind try to find a set of colors from one of those palettes that also have good contrast in this plot?

**Comment by BhaswatiRoy** [comment]
Hello @bryevdv 
Did you mean choosing some color palette from the given link for the Band Plots or trying for some other plots??

**Comment by bryevdv** [comment]
@BhaswatiRoy I was suggesting experimenting to see if there were some colors form the existing palettes in the docs that could be used in this PR (for the Band example)

**Comment by BhaswatiRoy** [comment]
Thanks @bryevdv for the clarification, I will surely search for better colors.

**Comment by BhaswatiRoy** [comment]
As I was suggested to find better color combinations for Band plots in the following pr: https://github.com/bokeh/bokeh/pull/12922
I came up with the following ideas -
 Maroon & Yellow - 7.1 :  1
 Blue & Yellow - 7.22 : 1
 Purple & Green - 7.1 : 1
 Blue & Pink - 7.59 : 1
 Red & Yellow - 7.19 : 1

image
image
image
image
image

**Comment by BhaswatiRoy** [comment]
Hello @bryevdv 
I showed all 5 combinations to @tcmetzger and he suggested I should go for Blue & Yellow - 7.22: 1, since it will work well for people having Red-Green color blindness. 
I have made the respective changes!

**Comment by bryevdv** [comment]
Sounds good @BhaswatiRoy I will merge after CI finishes, thanks for the PR!

**Comment by bryevdv** [comment]
Actually @BhaswatiRoy I just realized we will also need new thumbnails for the gallery. I have a fairly streamlined system for it now so I am happy to push the new images to your branch. But you are welcome to do it yourself too, if you like! We would need two omptimized pngs, a base 300x300 image and an indentica @2 600x600 "retina" image. The current images to update are here, for reference:
```
docs/bokeh/source/_images/examples/basic/annotations/band.png
docs/bokeh/source/_images/examples/basic/annotations/band@2x.png
```
Let me know what you prefer.

**Comment by BhaswatiRoy** [comment]
Hello @bryevdv, I will generate those images, and get back to you soon!

**Comment by BhaswatiRoy** [comment]
Is there some

> Actually @BhaswatiRoy I just realized we will also need new thumbnails for the gallery. I have a fairly streamlined system for it now so I am happy to push the new images to your branch. But you are welcome to do it yourself too, if you like! We would need two omptimized pngs, a base 300x300 image and an indentica @2 600x600 "retina" image. The current images to update are here, for reference:
> 
> ```
> docs/bokeh/source/_images/examples/basic/annotations/band.png
> docs/bokeh/source/_images/examples/basic/annotations/band@2x.png
> ```
> 
> Let me know what you prefer.

Is there some website that I can use to convert normal pngs to retina images?

**Comment by BhaswatiRoy** [comment]
Hello @bryevdv 
I have updated the band.png & band@2x.png plots.

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
Thanks @BhaswatiRoy !

**Comment by bryevdv** [comment]
@BhaswatiRoy I was a little hasty, I only just noticed that the new `@2` thumbnail has dark bands at the top and the bottom:

Screenshot 2023-03-15 at 18 17 52

We should strive to avoid that, and also strive to make sure the two versions of the thumbnails are identical, except for their resolution. Generally when I make thumbnails for the gallery, I make a high resolution screenshot, and then scale the same image down to the 600x600 and 300x300 sizes so they are the same. Can you make a new PR to tweak these images?

**Comment by BhaswatiRoy** [comment]
sure, I will submit a new pr soon.

**Comment by BhaswatiRoy** [comment]
Hello @bryevdv, I fixed both the images

image

**Pull request merged**
