### PR TITLE
Enable unit tests under Python 3.6 on Travis CI

### LINKED ISSUE #5666: Python 3.6 compatibility
Verify Bokeh functions full with python 3.6 before next Anaconda release cutoff.

### PR DESCRIPTION
**Pull request by mattpap**
fixes #5666

### CODE REVIEW

**Comment by bryevdv** [comment]
LGTM

Do you happen to know if running the python unit tests requires BokehJS to be built? If not, I think the unit test jobs can be sped up considerably. (in another PR)

**Comment by mattpap** [comment]
@bryevdv, I expect that js and css bundles must be present for unit tests, but I need to verify this. This limitation could be lifted, I presume.

**Comment by bryevdv** [comment]
I just checked on the docker image, they *almost* run:
```
======================================================== FAILURES =========================================================
_____________________________________ test_functickformatter_from_coffeescript_no_arg _____________________________________

    def test_functickformatter_from_coffeescript_no_arg():
        coffee_code = dedent("""
            square = (x) -> x * x
            return square(tick)
            """)

>       formatter = FuncTickFormatter.from_coffeescript(code=coffee_code)

bokeh/models/tests/test_formatters.py:58:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
bokeh/models/formatters.py:275: in from_coffeescript
    compiled = nodejs_compile(code, lang="coffeescript", file="???")
bokeh/util/compiler.py:162: in nodejs_compile
    output = _run_nodejs([compilejs_script], dict(code=code, lang=lang, file=file))
bokeh/util/compiler.py:141: in _run_nodejs
    return _run(_nodejs, argv, input)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

app = 'node', argv = ['/home/travis/bokeh/bokeh/server/static/js/compile.js']
input = {'code': '\nsquare = (x) -> x * x\nreturn square(tick)\n', 'file': '???', 'lang': 'coffeescript'}

    def _run(app, argv, input=None):
        if _nodejs is None:
            raise RuntimeError('node.js is needed to allow compilation of custom models ' +
                               '("conda install -c bokeh nodejs" or follow https://nodejs.org/en/download/)')

        proc = Popen([app] + argv, stdout=PIPE, stderr=PIPE, stdin=PIPE)
        (stdout, errout) = proc.communicate(input=None if input is None else json.dumps(input).encode())

        if proc.returncode != 0:
>           raise RuntimeError(errout)
E           RuntimeError: b"module.js:457\n    throw err;\n    ^\n\nError: Cannot find module '/home/travis/bokeh/bokeh/server/static/js/compile.js'\n    at Function.Module._resolveFilename (module.js:455:15)\n    at Function.Module._load (module.js:403:25)\n    at Module.runMain (module.js:590:10)\n    at run (bootstrap_node.js:394:7)\n    at startup (bootstrap_node.js:149:9)\n    at bootstrap_node.js:509:3\n"

bokeh/util/compiler.py:136: RuntimeError
___________________________________ test_functickformatter_from_coffeescript_with_args ____________________________________

    def test_functickformatter_from_coffeescript_with_args():
        coffee_code = dedent("""
             return slider.get("value") // 2 + tick
             """)

        slider = Slider()
>       formatter = FuncTickFormatter.from_coffeescript(code=coffee_code, args={"slider": slider})

bokeh/models/tests/test_formatters.py:76:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
bokeh/models/formatters.py:275: in from_coffeescript
    compiled = nodejs_compile(code, lang="coffeescript", file="???")
bokeh/util/compiler.py:162: in nodejs_compile
    output = _run_nodejs([compilejs_script], dict(code=code, lang=lang, file=file))
bokeh/util/compiler.py:141: in _run_nodejs
    return _run(_nodejs, argv, input)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

app = 'node', argv = ['/home/travis/bokeh/bokeh/server/static/js/compile.js']
input = {'code': '\nreturn slider.get("value") // 2 + tick\n', 'file': '???', 'lang': 'coffeescript'}

    def _run(app, argv, input=None):
        if _nodejs is None:
            raise RuntimeError('node.js is needed to allow compilation of custom models ' +
                               '("conda install -c bokeh nodejs" or follow https://nodejs.org/en/download/)')

        proc = Popen([app] + argv, stdout=PIPE, stderr=PIPE, stdin=PIPE)
        (stdout, errout) = proc.communicate(input=None if input is None else json.dumps(input).encode())

        if proc.returncode != 0:
>           raise RuntimeError(errout)
E           RuntimeError: b"module.js:457\n    throw err;\n    ^\n\nError: Cannot find module '/home/travis/bokeh/bokeh/server/static/js/compile.js'\n    at Function.Module._resolveFilename (module.js:455:15)\n    at Function.Module._load (module.js:403:25)\n    at Module.runMain (module.js:590:10)\n    at run (bootstrap_node.js:394:7)\n    at startup (bootstrap_node.js:149:9)\n    at bootstrap_node.js:509:3\n"

bokeh/util/compiler.py:136: RuntimeError
________________________________________________ TestContents.test_license ________________________________________________

self = <bokeh.tests.test_bokeh_init.TestContents testMethod=test_license>

    def test_license(self):
        import bokeh
        try:
            bokeh.license()
        except Exception as e:
            print("If LICENSE.txt does not exist in bokeh/ subdir, one way to fix this may be to run 'python setup.py develop'", file=sys.stderr)
>           raise e

bokeh/tests/test_bokeh_init.py:27:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
bokeh/tests/test_bokeh_init.py:24: in test_license
    bokeh.license()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def license():
        ''' Print the Bokeh license to the console.

        Returns:
            None

        '''
        from os.path import join
>       with open(join(__path__[0], 'LICENSE.txt')) as lic:
E       FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/bokeh/bokeh/LICENSE.txt'

bokeh/__init__.py:64: FileNotFoundError
-------------------------------------------------- Captured stderr call ---------------------------------------------------
If LICENSE.txt does not exist in bokeh/ subdir, one way to fix this may be to run 'python setup.py develop'
-------------------------------------------------- Captured stderr call ---------------------------------------------------
If LICENSE.txt does not exist in bokeh/ subdir, one way to fix this may be to run 'python setup.py develop'
-------------------------------------------------- Captured stderr call ---------------------------------------------------
If LICENSE.txt does not exist in bokeh/ subdir, one way to fix this may be to run 'python setup.py develop'
-------------------------------------------------- Captured stderr call ---------------------------------------------------
If LICENSE.txt does not exist in bokeh/ subdir, one way to fix this may be to run 'python setup.py develop'
-------------------------------------------------- Captured stderr call ---------------------------------------------------
If LICENSE.txt does not exist in bokeh/ subdir, one way to fix this may be to run 'python setup.py develop'
-------------------------------------------------- Captured stderr call ---------------------------------------------------
If LICENSE.txt does not exist in bokeh/ subdir, one way to fix this may be to run 'python setup.py develop'
____________________________________________ test_nodejs_compile_coffeescript _____________________________________________

    def test_nodejs_compile_coffeescript():
>       assert nodejs_compile("""(a, b) -> a + b""", "coffeescript", "some.coffee") == \
            dict(code=""""use strict";\n(function (a, b) {\n    return a + b;\n});\n""", deps=[])

bokeh/util/tests/test_compiler.py:6:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
bokeh/util/compiler.py:162: in nodejs_compile
    output = _run_nodejs([compilejs_script], dict(code=code, lang=lang, file=file))
bokeh/util/compiler.py:141: in _run_nodejs
    return _run(_nodejs, argv, input)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

app = 'node', argv = ['/home/travis/bokeh/bokeh/server/static/js/compile.js']
input = {'code': '(a, b) -> a + b', 'file': 'some.coffee', 'lang': 'coffeescript'}

    def _run(app, argv, input=None):
        if _nodejs is None:
            raise RuntimeError('node.js is needed to allow compilation of custom models ' +
                               '("conda install -c bokeh nodejs" or follow https://nodejs.org/en/download/)')

        proc = Popen([app] + argv, stdout=PIPE, stderr=PIPE, stdin=PIPE)
        (stdout, errout) = proc.communicate(input=None if input is None else json.dumps(input).encode())

        if proc.returncode != 0:
>           raise RuntimeError(errout)
E           RuntimeError: b"module.js:457\n    throw err;\n    ^\n\nError: Cannot find module '/home/travis/bokeh/bokeh/server/static/js/compile.js'\n    at Function.Module._resolveFilename (module.js:455:15)\n    at Function.Module._load (module.js:403:25)\n    at Module.runMain (module.js:590:10)\n    at run (bootstrap_node.js:394:7)\n    at startup (bootstrap_node.js:149:9)\n    at bootstrap_node.js:509:3\n"

bokeh/util/compiler.py:136: RuntimeError
_____________________________________________ test_nodejs_compile_javascript ______________________________________________

    def test_nodejs_compile_javascript():
>       assert nodejs_compile("""function f(a, b) { return a + b; };""", "javascript", "some.js") == \
            dict(code=""""use strict";\nfunction f(a, b) { return a + b; }\n;\n""", deps=[])

bokeh/util/tests/test_compiler.py:41:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
bokeh/util/compiler.py:162: in nodejs_compile
    output = _run_nodejs([compilejs_script], dict(code=code, lang=lang, file=file))
bokeh/util/compiler.py:141: in _run_nodejs
    return _run(_nodejs, argv, input)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

app = 'node', argv = ['/home/travis/bokeh/bokeh/server/static/js/compile.js']
input = {'code': 'function f(a, b) { return a + b; };', 'file': 'some.js', 'lang': 'javascript'}

    def _run(app, argv, input=None):
        if _nodejs is None:
            raise RuntimeError('node.js is needed to allow compilation of custom models ' +
                               '("conda install -c bokeh nodejs" or follow https://nodejs.org/en/download/)')

        proc = Popen([app] + argv, stdout=PIPE, stderr=PIPE, stdin=PIPE)
        (stdout, errout) = proc.communicate(input=None if input is None else json.dumps(input).encode())

        if proc.returncode != 0:
>           raise RuntimeError(errout)
E           RuntimeError: b"module.js:457\n    throw err;\n    ^\n\nError: Cannot find module '/home/travis/bokeh/bokeh/server/static/js/compile.js'\n    at Function.Module._resolveFilename (module.js:455:15)\n    at Function.Module._load (module.js:403:25)\n    at Module.runMain (module.js:590:10)\n    at run (bootstrap_node.js:394:7)\n    at startup (bootstrap_node.js:149:9)\n    at bootstrap_node.js:509:3\n"

bokeh/util/compiler.py:136: RuntimeError
________________________________________________ test_nodejs_compile_less _________________________________________________

    def test_nodejs_compile_less():
>       assert nodejs_compile(""".bk-some-style { color: mix(#ff0000, #0000ff, 50%); }""", "less", "some.less") == \
            dict(code=""".bk-some-style{color:#800080}""")

bokeh/util/tests/test_compiler.py:55:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
bokeh/util/compiler.py:162: in nodejs_compile
    output = _run_nodejs([compilejs_script], dict(code=code, lang=lang, file=file))
bokeh/util/compiler.py:141: in _run_nodejs
    return _run(_nodejs, argv, input)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

app = 'node', argv = ['/home/travis/bokeh/bokeh/server/static/js/compile.js']
input = {'code': '.bk-some-style { color: mix(#ff0000, #0000ff, 50%); }', 'file': 'some.less', 'lang': 'less'}

    def _run(app, argv, input=None):
        if _nodejs is None:
            raise RuntimeError('node.js is needed to allow compilation of custom models ' +
                               '("conda install -c bokeh nodejs" or follow https://nodejs.org/en/download/)')

        proc = Popen([app] + argv, stdout=PIPE, stderr=PIPE, stdin=PIPE)
        (stdout, errout) = proc.communicate(input=None if input is None else json.dumps(input).encode())

        if proc.returncode != 0:
>           raise RuntimeError(errout)
E           RuntimeError: b"module.js:457\n    throw err;\n    ^\n\nError: Cannot find module '/home/travis/bokeh/bokeh/server/static/js/compile.js'\n    at Function.Module._resolveFilename (module.js:455:15)\n    at Function.Module._load (module.js:403:25)\n    at Module.runMain (module.js:590:10)\n    at run (bootstrap_node.js:394:7)\n    at startup (bootstrap_node.js:149:9)\n    at bootstrap_node.js:509:3\n"

bokeh/util/compiler.py:136: RuntimeError
__________________________________________________ test_working_pipeline __________________________________________________

    @pytest.mark.api_test
    def test_working_pipeline():
        first = diff_versions("0.11.0", "0.12.0").split("\n")
        with open("scripts/tests/samples/sample_diff.txt") as f:
            second = f.read().split("\n")
>       assert not set(first) - set(second)
E       assert not (set(['', 'ADDED bokeh.application.application.Application.safe_to_fork', 'ADDED bokeh.application.application.Applicat....static_path', 'ADDED bokeh.charts.attributes.AttrSpec.series', 'ADDED bokeh.charts.builder.Builder.sort_legend', ...]) - set(['', 'ADDED bokeh.application.application.Application.safe_to_fork', 'ADDED bokeh.application.application.Applicat...r.Handler.static_path', 'ADDED bokeh.charts.attributes.AttrSpec.series', 'ADDED bokeh.charts.chart.Chart.legend', ...]))
E        +  where set(['', 'ADDED bokeh.application.application.Application.safe_to_fork', 'ADDED bokeh.application.application.Applicat....static_path', 'ADDED bokeh.charts.attributes.AttrSpec.series', 'ADDED bokeh.charts.builder.Builder.sort_legend', ...]) = set(['DELETED bokeh.models.tools.PreviewSaveTool', 'DELETED bokeh.plotting.figure.Figure.axis', 'DELETED bokeh.plotting.fi...g.figure.Figure.grid', 'DELETED bokeh.plotting.figure.Figure.xaxis', 'DELETED bokeh.plotting.figure.Figure.xgrid', ...])
E        +  and   set(['', 'ADDED bokeh.application.application.Application.safe_to_fork', 'ADDED bokeh.application.application.Applicat...r.Handler.static_path', 'ADDED bokeh.charts.attributes.AttrSpec.series', 'ADDED bokeh.charts.chart.Chart.legend', ...]) = set(['DELETED bokeh.charts.stats.Bins.update', 'DELETED bokeh.charts.stats.Bins.__init__', 'DELETED bokeh.charts.data_sour...figure.Figure.ygrid', 'DELETED bokeh.plotting.figure.Figure.yaxis', 'DELETED bokeh.plotting.figure.Figure.legend', ...])

scripts/tests/test_api_report.py:13: AssertionError
-------------------------------------------------- Captured stdout call ---------------------------------------------------
No local changes to save
-------------------------------------------------- Captured stderr call ---------------------------------------------------
No stash found.
-------------------------------------------------- Captured stdout call ---------------------------------------------------
No local changes to save
-------------------------------------------------- Captured stderr call ---------------------------------------------------
No stash found.
-------------------------------------------------- Captured stdout call ---------------------------------------------------
No local changes to save
-------------------------------------------------- Captured stderr call ---------------------------------------------------
No stash found.
-------------------------------------------------- Captured stdout call ---------------------------------------------------
No local changes to save
-------------------------------------------------- Captured stderr call ---------------------------------------------------
No stash found.
-------------------------------------------------- Captured stdout call ---------------------------------------------------
No local changes to save
-------------------------------------------------- Captured stderr call ---------------------------------------------------
No stash found.
-------------------------------------------------- Captured stdout call ---------------------------------------------------
No local changes to save
-------------------------------------------------- Captured stderr call ---------------------------------------------------
No stash found.
================================================== 190 tests deselected ===================================================
======================= 7 failed, 919 passed, 1 skipped, 190 deselected, 35 rerun in 52.15 seconds ========================
```

**Comment by bryevdv** [comment]
Esp. with adding py 3.6 I think we should consider: 

* running all python unit tests in one job
* only running the bokehjs unit test once

This could maybe just be one "unit test" job that builds bokehjs once, runs those tests, then creates conda envs for all the python unit tests. That would be one ~10 minute job instead of four ~6-8 minute jobs. I'll make another issue to explore later tho

**Comment by mattpap** [comment]
@bryevdv, well, this will be more work than I thought:
```
The following specifications were found to be in conflict:
  - conda
  - conda 4.3.4* -> python 2.7*|3.4*|3.5*
  - conda-build 2.1.1* -> conda >=4.1
  - conda-build 2.1.1* -> python 2.7*|3.4*|3.5*
  - notebook ==4.2.3 -> python 2.7*|3.4*|3.5*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by bryevdv** [comment]
ping @ilanschnell can we get notebook 4.2.3 for py3.6? We need to be pinned to that version for testing currently.

**Comment by mattpap** [comment]
Almost there:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - pytest-rerunfailures -> python 2.7*
  - python 3.6*
```
Note that `pytest-rerunfailures` is provided by `bokeh` channel and uploader was @birdsarah.

**Comment by bryevdv** [comment]
I will try to upload a py3.6 package today

**Comment by mattpap** [comment]
> I will try to upload a py3.6 package today.

@bryevdv, did you have a chance to upload this?

**Comment by bryevdv** [comment]
I did, it's now missing selenium itself. Will look at that tomorrow.

**Comment by bryevdv** [comment]
Took about four hours but I got everything missing cobbled together on the bokeh channel. The old versions of MPL and ggplot and some others are getting hard to obtain for python3.6, it will be good to drop MPL support for that reason tool. 

I'm OK merging this whenever. Sometime after I will re-arrange our overall structure to do all the unit tests on on job.

**Pull request merged**
