### PR TITLE
remove output_server and support functions

### LINKED ISSUE #5989: Remove deprecated output_server
The existence of `output_server` complicates #5979 considerably. It was deprecated in `0.12.3` and although two releases is a somewhat short deprecation cycle:

* it is hardly functional to begin with
* it is not demonstrated anywhere in the docs, examples, etc.
* have not seen any questions regarding it on ML, SO, etc. anytime recently. 

Will remove, to help make #5979 simpler.

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #5989
- [x] tests added / passed
- [x] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
Travis docs build failing due to docs.scipy.org being down

**Comment by mattpap** [comment]
10 hours later and still down.

**Comment by bryevdv** [comment]
I'm inclined to just merge anyway, to unblock other work unless you have an objection.

**Comment by bryevdv** [comment]
FYI, ETA for scipy site fix is "by the end of the day"

**Pull request merged**
