### PR TITLE
Add support for passing colors as ndarrays and CSS4 color syntax

### LINKED ISSUE #5676: Encode colors as 32 bit integers by default
It is not uncommon when working with a lot of data or large images to need many different colors. At present, these colors are packed into a JSON list where each color is a string. The color strings themselves beginning with a `#` and are followed by a 6 digit hexadecimal number. However, this can end up taking up a fair bit of space, which eats into transfer time and/or storage depending on the use case.

Recently PR ( https://github.com/bokeh/bokeh/pull/5544 ) was added to provide support encoding NumPy arrays as `base64` and decoding them as the appropriate typed JavaScript arrays on the other end. Even though there is no additional compression considered beyond this encoding scheme, the result is a drastic reduction in size of data. This makes a big difference in terms of being able to distribute results and, in some cases, loading them. Various array type data are already handled very nicely by this change.

In light of the aforementioned PR, it is worth considering applying a similar strategy to colors. For instance, `Greys256` takes up ~2.5KB in its current form in an HTML document. However, if we use a 256 x 3 `uint8` NumPy array, and encode it using the `base64` scheme from PR ( https://github.com/bokeh/bokeh/pull/5544 ) the same color range takes up ~1KB. In other words, we could see a ~2.5x reduction in size where color palettes are concerned by doing nothing more than allowing NumPy arrays as a color argument and extending the encoding work from PR ( https://github.com/bokeh/bokeh/pull/5544 ) (if needed) to include this case. A rough calculation backs this up as well. Conversion back to an appropriate JavaScript color string is pretty straightforward.

To summarize, it would be really interesting to explore encoding lists of color strings into compact `base64` representations. By more compactly structuring our data, we should be able to more freely represent our data and without worrying about how to share it.

### LINKED ISSUE #9951: [BUG] Impossible to use tuples as colors
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.0.1

#### Description of expected behavior and the observed behavior
`Color` accepts 3- and 4-tuples. But it can't be used because the value is not encoded for BokehJS.

#### Complete, minimal, self-contained example code that reproduces the issue
```python
from bokeh.io import show
from bokeh.plotting import figure

p = figure(tools=[])
p.circle(x=[0, 1], y=[0, 1], fill_color=[(0, 0, 0, 1), 'red'], size=100)

show(p)
```

Even if you use a `palette` to avoid data array auto-detection or single item arrays to avoid misinterpreting `'red'` as an array, the result is similar. There won't be an error but the used color will be completely wrong.

#### Stack traceback and/or browser JavaScript console output
```
VM365:1 Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable
    at eval (eval at decode_traverse_data (serialization.js:172), <anonymous>:1:16)
    at decode_traverse_data (serialization.js:172)
    at Object.decode_column_data (serialization.js:194)
    at ColumnDataSource.initialize (column_data_source.js:137)
    at ColumnDataSource.finalize (has_props.js:162)
    at document.js:394
    at foreach_value (document.js:367)
    at foreach_value (document.js:365)
    at foreach_value (document.js:372)
    at foreach_value (document.js:365)
```

### LINKED ISSUE #10576: [FEATURE] 'transparent' as an alias for `rgba(0, 0, 0, 0)`
**Is your feature request related to a problem? Please describe.**

`color=None` usually does the job at specifying 'no color' or 'fully transparent' color
However, inside mappers such as `ColorLinearMapper` for instance, setting `high_color=None` or `low_color=None` will not result in using 'no color' but will default to extending the map to higher/lower values.

**Describe the solution you'd like**
A simple solution would be to follow Matplotlib's pattern of allowing 'none' as a color and where `color=None` clearly means 'apply default behavior' and `color='none'` means 'no color'.

**Describe alternatives you've considered**
Granted, it's easy enough to specify `low_color='rgba(0, 0, 0, 0)'` but a simple alias would be cleaner IMHO.
`'none'` and `None` can also introduce confusion but in most cases they would be fully substitutable. 'nocolor' could also be considered for the alias name.

### PR DESCRIPTION
**Pull request by mattpap**
This PR:

- adds support for passing colors as ndarrays (e.g. `uint8[N, 3]` or `uint8[N, 4]`, RGB and RGBA respectively)
- adds CSS4 color syntax (e.g. `#RRGGBBAA`, `#RGBA`, `rgb(R G B / A)`, etc.) and `transparent` keyword
- makes webgl to use uint8 instead of f32 to store colors (simpler cooperation with the rest of bokehjs; less memory usage)

- [x] fixes #5676
- [x] fixes #9951 
- [x] fixes #10576

### CODE REVIEW

**Comment by bryevdv** [comment]
> makes webgl to use uint8 instead of f32 to store colors

Can you point to an existing example that has a shader that operates on this kind of input that I can study?

**Comment by mattpap** [comment]
> Can you point to an existing example that has a shader that operates on this kind of input that I can study?

It's markers' line and fill colors:

https://github.com/bokeh/bokeh/pull/10677/files#diff-037cd7f0d6b0323c13c7aaadcf75be83857f24513211e327de973e511f82753eL60-R76

Note this code will get simplified even further, so that there will be no processing in this code path necessary. In fact, when fully implemented in this PR, if user chooses `uint8[N, 4]` array type for storing colors, this data should go straight from the client to the GPU without processing. Possibly this could work as well in other cases, e.g. `uint8[N, 3] and scalar alpha`.

**Comment by mattpap** [comment]
Also note that by uint8 I mean the data are unsigned bytes, but the buffer gets automatically normalized in `0..1` range in the shader, so that no changes to the shader are necessary.

**Comment by mattpap** [comment]
This is feature complete and tentatively ready. It needs a lot more testing and bokeh side of this needs to be further updated, to fully take advantage of changes to bokehjs. I updated `plotting/file/color_scatter` to show off RGBA ndarray support.

**Comment by bryevdv** [comment]
I'll take a look and test out tonight

**Comment by bryevdv** [comment]
OK I looked through the entire PR and only had nit comments I'm not going to bother with. Examples report and downstream tests look good. Going to merge this in order to get into a dev build ASAP tomorrow (@mattpap please kick one off before I wake up if you are so inclined)

**Comment by bryevdv** [comment]
@mattpap I kicked off the dev9 build last thing, so you should just be able to run the deploy job

**Pull request merged**
