### PR TITLE
After running npm audit fix

### PR DESCRIPTION
**Pull request by birdsarah**
Fixes: #8708

Not sure if this is all that needs to be done, but this is what updated after running `npm audit fix`

### CODE REVIEW

**Comment by bryevdv** [comment]
The only thing that caught my eye is that this seems to bring in `lodash` but maybe we will have to live with that

**Comment by mattpap** [comment]
This is introduced by a dev dependency (istanbul), so it shouldn't be a big concern.

**Comment by mattpap** [comment]
Unforunately, appveyor tests are failing all day everywhere.

**Comment by bryevdv** [comment]
Thanks @birdsarah

**Pull request merged**
