### PR TITLE
Update to Bokeh example plot: accessible palette with new images

### PR DESCRIPTION
**Pull request by Soot3**
Changed spectral5 to mediumcontrast5

Original

Screenshot (173)

How's this @bryevdv 

pandas_groupby_nested
pandas_groupby_nested@2x

- [x] issues: #11481

### CODE REVIEW

**Comment by bryevdv** [comment]
@Soot3 These look great, let's just get them in the same PR as the code changes

**Comment by Soot3** [comment]
@bryevdv added the code changes here instead.

**Comment by bryevdv** [comment]
@Soot3 It's not a blocker, but I would note that the fonts in the new `@2` image do appear a bit fuzzier in the new image. If it is possible to experiment with maybe grabbing a higher resolution image to start and scaling it down, perhaps that would help?

**Comment by Soot3** [comment]
exported better images using svgs before scaling down. Thanks.

pandas_groupby_nested

2x


pandas_groupby_nested@2x

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
Looks much better, thanks @Soot3 will merge when tests are green (modulo unrelated failing docker test)

**Comment by wenebob** [comment]
This is a good job @scoot3.
However, I think the faint yellow color (third color in the plot) against that white background is can be an is not so good. In my opinion, it's not very clear to the eyes because both  background and foreground colors are very light which is an accessibility issue. What do you think @bryevdv?

**Comment by Soot3** [comment]
@Faith-Nchifor hey. which plot are you looking at. the first one is the original plot which had yellow and clashed with the background. the change that has been merged switches the colours to deeper versions allowing for more contrast against the background

**Comment by wenebob** [comment]
It's fine if the change has been merged @scoot3. I actually expected the changes to reflect on the example gallery. It was the gallery that led me here. This is the old plot, I guess https://docs.bokeh.org/en/latest/docs/examples/basic/bars/pandas_groupby_nested.html

**Comment by bryevdv** [comment]
>  I actually expected the changes to reflect on the example gallery. 

@Faith-Nchifor the docs site is only updated at the time when releases happen, so everything that is currently going on in the repo right now, will show up (in the "latest" docs) when version 3.2 is released (probably in 6-8 weeks)

**Comment by wenebob** [comment]
Alright. Thank you for the clarification @bryevdv

**Pull request merged**
