### PR TITLE
Bug/2755 components multi

### LINKED ISSUE #2755: Components on multiple objects duplicates objects in all_models
This can causes models to be initialized more than once, which causes errors. Need to protect on both the python and JS sides.

### PR DESCRIPTION
**Pull request by bryevdv**
issues: fixes #2755

### CODE REVIEW

**Comment by bryevdv** [comment]
ping @damianavila @mistakevin @mattpap I think this is a fairly important fix to get in ASAP

**Comment by birdsarah** [comment]
Not trying to slow things down, but can this have a test?

**Comment by mistakevin** [comment]
Nice find. Code looks good to me

**Comment by bryevdv** [comment]
I will add a test and merge then, @birdsarah I think it would be easier to merge this then fix up your `raw_components` PR? Our do you think it would be better to merge yours first?

**Comment by birdsarah** [comment]
I'm fine with fixing up the `raw_components` PR.

**Comment by bryevdv** [comment]
Actually, I'm not quite sure now to test this without some refactoring, but I don't want to make the merge worse than it will already be. @birdsarah I will do that after both are merged (hold me to it!)

**Pull request merged**
