### PR TITLE
never use name as a substitute id

### LINKED ISSUE #1592: BokehJS unrecoverable errors in notebook
It seems easy to get the notebook into an unrecoverable state when using `push_notebook` and IPython interactors. Must close the session entirely and start again to regain plots. Executing all the cells in the notebook stored in this gist:

https://gist.github.com/bryevdv/b4e9eb68a6234a67a570

should reproduce the problem.

To be specific, by "unrecoverable" I mean that clearing all cells and restarting the kernel from the menu does not fix the problem. It is still impossible to generate plots. I have had to close the tab and shutdown from the IPython home notebook list, then re-open a new tab to be able to plot again. 

@damianavila this is a pretty serious bug. We should try to fix it for 0.7.1 for sure. I will take a look and add any findings but I may need your input/assistance.

### PR DESCRIPTION
**Pull request by bryevdv**
issues: fixes #1592

### CODE REVIEW

**Comment by bryevdv** [comment]
Well this can be reverted easily enough if anyone has concerns or disagrees, merging.

**Comment by damianavila** [comment]
I think it was the right thing to do... but I don't remember why we needed the `plot._id` being the `name` before... I tracked down and @bryevdv, you added this on https://github.com/bokeh/bokeh/commit/021b3df986c88f7ad99dda2b3ed08253a7fbf339, do you remember why you needed to set up it?

**Comment by hhuuggoo** [comment]
most likely so that one could specify the ID and easily debug the js objects.  This has been discussed in #444 and #340 I think we should definitely implement this change

**Comment by damianavila** [comment]
ok... thanks for the links @hhuuggoo... now I remember...

**Comment by paddymul** [comment]
I think I may have implemented this.  The reason I put it in was so that
you would have more sane diffs for generated code.  This helps a lot if you
are embedding a generated json plot specification into source control.

There might be other ways to achieve the same affect.

**Comment by paddymul** [comment]
Oops, upon further reading, my last response was exactly what I said in
#444

**Comment by bryevdv** [comment]
I think its not entirely unreasonable to allow people to provide their own ID's, but it needs to be "harder" and more explicit than setting `name` was. Basically make it an obviously "proceed at your own risk" kind of operation.

**Comment by hhuuggoo** [comment]
doesn't use simple ids remove some of the need for this?

**Comment by bryevdv** [comment]
It's an option but I'm not sure I would use if for prodcution. It simplifies the IDs but does not extend any control over them.

**Pull request merged**
