### PR TITLE
concepts file changes [ci disable examples]

### PR DESCRIPTION
**Pull request by electronwill**
[ci disable examples]

- add 'screen units' and 'data-space units' to glossary
- 'to server' -> 'to serve'
- small rewrite about high level and low level interfaces

### CODE REVIEW

**Comment by bryevdv** [comment]
I'm a little hesitant about putting this here. I was trying to keep this particular glossary very small, and restricted to very core *things*, that could be linked to linked to (which is the case for almost every entry, except "document" does not have a good landing yet). Basically so that it could act as descriptive table of contents. Units are important but they are definitely not central abstractions like everything else not the list, and there is nothing to link to from either. I'd prefer to consider other locations for this information.

**Comment by bryevdv** [comment]
Basically everything else in the list is an extremely high level concept, and then we'd be adding two extremely in-the-weeds details.

**Comment by electronwill** [comment]
That does make sense, and it's a good idea to keep the glossary consistent with regards to whether it handles details or broad concepts. I'll update this PR and https://github.com/bokeh/bokeh/pull/3950 to move the screen units and data-space units information to the Plotting page.

**Comment by electronwill** [comment]
Ready for review.

**Pull request merged**
