### PR TITLE
Add support for binary serialization

### PR DESCRIPTION
**Pull request by mattpap**
Early WIP. This adds fully binary protocol on top of existing binary serialization of buffers (ndarrays, etc.). For now this PR supports one way serialization (Python -> JS). The other three ways need to be still implemented. This implementation is based on msgpack, though potentially better bases were suggested, but require further investigation. This PR amends existing protocol, so can be merged at later time without breaking changes.

### CODE REVIEW

**Comment by hamogu** [comment]
I was just going to add a feature request about "binary serialization" and then I saw this. I *think* that this might address my use case, so I'm leaving my comment here:

I'm an astronomer. In astronomy, we are often working with with images. In a current project, I have about 100 of them taken with the Hubble space telescope. Each image has about 4000x4000 pixels. I'd love to display that image with bokeh and overplot markers for the stars I detect, be able to zoom in to see more details, add mouse-over information etc. Unfortunately, the json representation of that image it too large to reasonably handle. A binary serialization protocol would hopefully allow to present the image with much smaller file sizes.

I'm posting this here as a use case that is really only possible with a binary representation. I have not investigated the details of where the size of the json blows (e.g. reducing the precision of the numbers in the json would also save space?) nor did I check if this PR would solve the problem.

*note:* For very large astronomical images, e.g. covering the whole sky, we use a protocol similar to the tiles used for geomaps and I'm currently not aware of an implementation for that in bokeh. However, for medium-sized images like mine from Hubble I don't want to go through all that effort and just treat it as a normal image and zoom in and out. A binary protocol would vastly extend the range where I could do that with bokeh.

**Comment by philippjfr** [comment]
To be clear @hamogu, Bokeh has had binary serialization for a long time and this is mostly a generalization of existing functionality. I'd suggest posting to the [Bokeh Discourse](https://discourse.bokeh.org/) if you have questions about that.

**Comment by bryevdv** [comment]
As @philippjfr notes, binary serialization of numpy arrays was added several years ago, but there are some caveats to know:

* Only array types that have corresponding JS Type Array types can be supported. That's basically float32, float64, and int32
* Binary serialization is really mostly useful in a Bokeh server contest. There the array buffers can be send directly over the websocket into Typed arrays with minimal copies an no encoding. 

* But you mention "the size of the json blows" which makes me think you are not using a Bokeh server app? Binary serialization is not going to offer much help in that case, since ultimately there is still alot of text that has to be loaded and unencoded.

**Comment by mattpap** [comment]
I doubt there will be sensible progress on this subject until we have a Rust or C++ or similar implementation of bokeh's protocol available. I'm going to close this PR, but keep the branch.

**Pull request closed without merging**
