### PR TITLE
Apply blackbody example label edits (#12534) to the ts example as well

### LINKED ISSUE #12533: [BUG] Units in blackbody example should be upright
### Software versions

.

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

.

### Observed behavior

.

### Example code

```Python
.
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by zmoon**
Apply changes in #12534 to the ts example as well

> There's a bokehjs variant of this example that should have been updated as well.

— https://github.com/bokeh/bokeh/pull/12534#issuecomment-1301078378

- [x] issues: fixes #12533
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
Thank you @zmoon !

**Comment by zmoon** [comment]
@bryevdv wasn't sure if I was supposed to target 3.0 or 3.1 for this. Did I do the right one?

**Comment by bryevdv** [comment]
> @bryevdv wasn't sure if I was supposed to target 3.0 or 3.1 for this. Did I do the right one?

It's a matter of some preference among the team, I think. I prefer it to be `branch-3.0` as you have done.

**Comment by bryevdv** [comment]
@zmoon the "baseline" for this example will also need to be updated. When the BokehJS tests complete there should be an artifact that you can download and untar over the repository with the updated baseline from the test. You can just check that in and push it to this branch.

**Comment by bryevdv** [comment]
Thanks for the PR @zmoon !

**Review by bryevdv — APPROVED** [review]

**Pull request merged**
