### PR TITLE
Include Greys256 in Palettes enumeration

### LINKED ISSUE #5490: Some named palettes raise ValueError
When creating a `ColorMapper` or an `Image`, the `palette` keyword argument supports string reference to some of the palettes in the `palettes` module, but not all. 

For example:

```
from bokeh.plotting import figure, output_file, show
from bokeh.palettes import Greys256

output_file("test_plot.html")

palette = "Greys256" # raises `ValueError: expected an element of Seq(Color), got 'Greys256'`
palette = Greys256 # works as expected
palette = "Inferno256" # works as expected

fig = figure(x_range=[0, 5], y_range=[0, 5])
fig.image([[range(5)]*5], x=[0], y=[0], dw=[5], dh=[5], palette=palette)
show(fig)
```

Python `2.7.12` and Bokeh `0.12.3`

### PR DESCRIPTION
**Pull request by mattpap**
fixes #5490

### CODE REVIEW

**Comment by bryevdv** [comment]
flake8 failure: 
```
E       AssertionError: Flake8 issues:
E         bokeh/palettes.py:1440:161: E501 line too long (170 > 160 characters)
E         
E       assert 1 == 0
E        +  where 1 = <subprocess.Popen object at 0x7f58a9469a10>.returncode
``` 
Highly recommend adding 

http://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html#git-hooks

**Comment by bryevdv** [comment]
Also, some upstream change (I think) is causing random integration test failures all over the place

**Comment by bryevdv** [comment]
LGTM

**Comment by mattpap** [comment]
> Highly recommend adding

Yeah, but that's fairly inefficient in my opinion. I need to configure my editor to just highlight offending lines (like it does with various whitespace issues).

**Pull request merged**
