### PR TITLE
Using mappers documentation update

### PR DESCRIPTION
**Pull request by kindofluke**
fixes:  #7995

This is an update to the "Styling Visual Attributes page" to document the use of the mappers along with an example. 

A picture of the page (built locally) is attached here as well if folks just want to provide feedback on the text. 

This includes an example where 10 circles are drawn with an diverging color palette based on the y-axis. This pairs nicely with "Using Palettes" the first entry on the page. 

thanks

using mappers documentation

### CODE REVIEW

**Comment by bryevdv** [comment]
Thanks for the PR @kindofluke! There are some linter errors that need to be fixed, then when things are green we can merge this:
```
        errors = collect_errors()
>       assert len(errors) == 0, "Code quality issues:\n%s" % "\n".join(errors)
E       AssertionError: Code quality issues:
E         File does not end with a newline: sphinx/source/docs/user_guide/examples/styling_linear_mappers.py, line 26
E         File contains trailing whitespace: sphinx/source/docs/user_guide/styling.rst, line 33.
E         File contains trailing whitespace: sphinx/source/docs/user_guide/styling.rst, line 36.
E         File contains trailing whitespace: sphinx/source/docs/user_guide/styling.rst, line 46.
E         File contains trailing whitespace: sphinx/source/docs/user_guide/styling.rst, line 47.
E         File contains trailing whitespace: sphinx/source/docs/user_guide/styling.rst, line 48.
E       assert 6 == 0
E        +  where 6 = len(['File does not end with a newline: sphinx/source/docs/user_guide/examples/styling_linear_mappers.py, line 26', 'File ...guide/styling.rst, line 47.', 'File contains trailing whitespace: sphinx/source/docs/user_guide/styling.rst, line 48.'])
tests/test_code_quality.py:95: AssertionError
_________________________________ test_flake8 __________________________________
    @pytest.mark.quality
    def test_flake8():
        chdir(TOP_PATH)
    
        proc = Popen(["flake8"], stdout=PIPE, stderr=PIPE)
        out, err = proc.communicate()
    
>       assert proc.returncode == 0, "Flake8 issues:\n%s" % out.decode("utf-8")
E       AssertionError: Flake8 issues:
E         ./sphinx/source/docs/user_guide/examples/styling_linear_mappers.py:2:1: F401 'bokeh.models.Band' imported but unused
E         ./sphinx/source/docs/user_guide/examples/styling_linear_mappers.py:4:1: F401 'pandas as pd' imported but unused
E         ./sphinx/source/docs/user_guide/examples/styling_linear_mappers.py:5:1: F401 'numpy as np' imported but unused
E         
E       assert 1 == 0
E        +  where 1 = <subprocess.Popen object at 0x7fa51114c748>.returncode
tests/test_flake8.py:16: AssertionError
============= 2 failed, 3 passed, 3457 deselected in 27.55 seconds =============
```
looks like just some trailing spaces and unused imports to delete

**Comment by kindofluke** [comment]
Sounds great. I am running that test and its seems like it is passing locally and I added flake8 linting to my editor so 🤞 .

**Comment by bryevdv** [comment]
@kindofluke great! We actually have some additional checks on top of flake8, because we have lots of non-python files, and a few of those are still flagging:
```
    @pytest.mark.quality
    def test_files():
        errors = collect_errors()
>       assert len(errors) == 0, "Code quality issues:\n%s" % "\n".join(errors)
E       AssertionError: Code quality issues:
E         File contains trailing whitespace: sphinx/source/docs/user_guide/styling.rst, line 35.
E         File contains trailing whitespace: sphinx/source/docs/user_guide/styling.rst, line 44.
E         File contains trailing whitespace: sphinx/source/docs/user_guide/styling.rst, line 45.
E         File contains trailing whitespace: sphinx/source/docs/user_guide/styling.rst, line 46.
E       assert 4 == 0
E        +  where 4 = len(['File contains trailing whitespace: sphinx/source/docs/user_guide/styling.rst, line 35.', 'File contains trailing whi...guide/styling.rst, line 45.', 'File contains trailing whitespace: sphinx/source/docs/user_guide/styling.rst, line 46.'])
tests/test_code_quality.py:95: AssertionError
============= 1 failed, 4 passed, 3457 deselected in 29.19 seconds =============
```
Once that trailing whitespace is removed, tests should go green.

**Comment by bryevdv** [comment]
Thanks for the PR @kindofluke !

**Pull request merged**
