### PR TITLE
CSV Endpoint For ColumnDataSources

### PR DESCRIPTION
**Pull request by lukebarnard1**
I've added a CSV endpoint for ColumnDataSources. The URL is the same as the one for retrieving JSON, except an extra '/' and a ```<format>``` can be added to the end:
```
/bokeh/bb/<docid>/<typename>/<id>/<format>
```

### CODE REVIEW

**Comment by bryevdv** [comment]
@lukebarnard1 Looks good, but could you add an example, and either a test or a procedure for testing?

**Comment by lukebarnard1** [comment]
Of course, is there a way / place used to test backbone URLs? I have an example which uses a Button within an object_page to download the CSV of any ColumnDataSource:
```python

docid = '38a50a89-924b-490f-9310-55bbe359718e'
datasource= ColumnDataSource(data={'column1':[1,2,3,4,5],'column2':[6,7,8,9,10]})

code = 'window.location="/bokeh/bb/%s/ColumnDataSource/%s/csv"'
c = Callback(code=code % (docid, datasource._id))
self.csv_button = Button(label='Download CSV', type='link', callback=c)
```
```docid``` was tricky to find - I had to modify app.py to get it to pass docid into the function decorated with @object_page. It then gets passed into the ```create()``` method of the main PlotObject.

Is there a succinct way of doing this with BokehJS? Is there a JS variable that contains the docid?

**Comment by bryevdv** [comment]
The docid is normally communicated to the JS loader in this template:

https://github.com/bokeh/bokeh/blob/master/bokeh/_templates/autoload_server.html

by this function:

https://github.com/bokeh/bokeh/blob/master/bokeh/embed.py#L190

The JS loader uses it, but AFAIK it is not exposed elsewhere. In fact the copy-on-write semantics may mean that users get a new copy of a document with a completely new document id. Thinking about things more, I don't think that relying on the docid is going to be a robust way to move forward. Realistically, if you want to expose data sources as CSV endpoints, there probably needs to be some kind of explicit global registration of the data that any document could potentially use (modulo auth). 

ping @cpcloud Thinking about this a bit more, I wonder if this kind of interface might make much more sense in the Blaze server. Bokeh will be using the Blaze server in the near future for front ending and serving remote data, and the Bokeh server itself will become more simplified.

**Comment by damianavila** [comment]
pinging @cpcloud again :wink:

**Comment by cpcloud** [comment]
@bryevdv @damianavila Are you thinking that this should be a REST endpoint to convert a file from format X to format Y and then send that back to client in chunks?

**Comment by cpcloud** [comment]
something like `GET /retrieve/csv?source=dict_key_of_resource`?

**Comment by damianavila** [comment]
> Are you thinking that this should be a REST endpoint to convert a file from format X to format Y and then send that back to client in chunks?

It could be... but not sure if @bryevdv is exactly asking for that... btw, I think this deserves some more discussion before hitting master (if it hits master), so I would change the milestone to short-term. We could go back to 0.9.1 if we all agree to include it for the next upcoming release... thoughts?

**Comment by damianavila** [comment]
This needs more discussion, moving milestone to short-term

**Comment by bryevdv** [comment]
I'm going to close this PR, as the entire server is being re-written and replaced with a tornado and web socket based approach. It may make sense to have an optional view that can be added that can expose a similar capability, but that will require a new PR.

**Comment by bryevdv** [comment]
Thank, @lukebarnard1, for the PR and the discussion, let's figure out what makes sense with the new server when it is in a more stable state later this month.

**Pull request closed without merging**
