### PR TITLE
Add ipywidgets_bokeh documentation

### PR DESCRIPTION
**Pull request by mattpap**

### CODE REVIEW

**Comment by bryevdv** [comment]
We should not have separate Notebook and Jupyter chapters (there are already too many chapters). If we need to re-name the Notebook chapter to something more general, now (2.0) is the time to do it. But I'd suggest leaving a page at the Notebook URL that links back the new Jupyter chapter.

**Comment by mattpap** [comment]
I think it would be confusing to merge those. I split it off intentionally, to make it clear that this isn't notebook related. I also didn't see it fit under other sections (embedding, server, etc.). I think it's not that bad to have many sections, compared to nested structure.

**Comment by bryevdv** [comment]
I personally think the opposite, that people would expect and be better served by having everting Jupyter-related (which includes: notebooks, jupyterlab, and ipywidgets) in one place rather then multiple. 

cc @bokeh/dev

**Comment by philippjfr** [comment]
Honestly I can see both arguments, if you want to merge them I also suggest calling it the Jupyter chapter and linking back to it from the old Notebook URL link.

**Comment by bryevdv** [comment]
I also think that 10 sentence does not comprise enough material for a dedicated chapter.

**Comment by bryevdv** [comment]
Additionally: Having a chapter called "Jupyter" *that does not cover Jupyter Notebooks* is absolutely confusing. 

I still 1000% think that these chapters should be merged, but if they are not to be merged, I must insist that the chapter be renamed to "Ipywidgets" which is actually descriptive  of the content, and not confusingly called "Jupyter" while excluding the singular thing that everyone associates with that name (notebooks).

**Pull request merged**
