### PR TITLE
Add the new bk-root wrapper

### PR DESCRIPTION
**Pull request by birdsarah**
Fixes: #4059

### CODE REVIEW

**Comment by bryevdv** [comment]
ping @mattpap this is somewhat related to your other recent issue about preview tool I think

Should the `bk-root` class name be added back to the BB view directly? I don't quite understand why it was removed. Also ping @mistakevin

**Comment by mattpap** [comment]
Most likely there is connection between those issues. Actually I had an issue with creating the API as well, because I have to maintain `bk-root` all the time. I will look in this.

**Comment by mattpap** [comment]
As this PR is a hotfix, it's fine. We can revert this when proper solution is found.

**Comment by bryevdv** [comment]
OK, will merge when tests pass.

**Pull request merged**
