### PR TITLE
fix animated example

### LINKED ISSUE #5305: embed/animated fails with "did not find model"
`Error rendering Bokeh items  Error: Did not find model ID_HERE in session`.

### PR DESCRIPTION
**Pull request by bryevdv**
issue: fixes #5305

### CODE REVIEW

**Comment by bryevdv** [comment]
This example is not maintained under test, but it was verified locally, so merging immediately.

**Comment by mattpap** [comment]
@bryevdv, you didn't remove the outdated comment.

**Comment by bryevdv** [comment]
Oh, I thought there was just the docstring that incorrectly stated that (which I fixed last week).

**Comment by mattpap** [comment]
@bryevdv, also documentation is outdated (http://bokeh.pydata.org/en/latest/docs/user_guide/embed.html#server-data).

**Pull request merged**
