### PR TITLE
Initial boilerplate for bokeh/_testing

### PR DESCRIPTION
**Pull request by HuntJSparra**
- [X] issues: finishes #8207 
- [x] tests added / passed

Adds boilerplate for bokeh/_testing

### CODE REVIEW

**Comment by bryevdv** [comment]
@HuntJSparra is this ready?

**Comment by HuntJSparra** [comment]
It is ready unless you want me to take care of the last small bit of cleanup for #8207 in this PR as well.

**Comment by bryevdv** [comment]
Sure, let's finish everything up here at once.

**Comment by HuntJSparra** [comment]
@bryevdv, this should close #8207 unless I am missing anything.

**Pull request merged**
