### PR TITLE
Examples for Bokeh Server Widgets

### PR DESCRIPTION
**Pull request by samirak93**
Created examples for widgets using bokeh server. 

Example:

```
## Bokeh server for button click

from bokeh.io import curdoc
from bokeh.layouts import row
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import Button
from bokeh.plotting import figure

x=[3,4,6,12,10,1]
y=[7,1,3,4,1,6]

source = ColumnDataSource(data=dict(x=x, y=y))

plot_figure = figure(plot_height=450, plot_width=600,
              tools="save,reset",
              x_range=[0,14], y_range=[0,12],toolbar_location="below")

plot_figure.scatter('x', 'y', source=source, size=10)

button = Button(label="Click to set plot title", button_type="success")

def button_click():
    plot_figure.title.text = 'Button Clicked'

button.on_click(button_click)

layout=row(button,plot_figure)

curdoc().add_root(layout)
curdoc().title = "Button Bokeh Server"
```

### CODE REVIEW

**Comment by bryevdv** [comment]
(Note I have stopped CI for now, we are prepping for big release, and need all TravisCI capacity at the moment)

**Comment by samirak93** [comment]
> (Note I have stopped CI for now, we are prepping for big release, and need all TravisCI capacity at the moment)
> 
> Edit: Also just to set expectations, it will be a little later this week before I can dig into this. Thanks for the PR!

Thank you.

**Comment by bryevdv** [comment]
@samirak93 This is currently just failing some linter checks (missing end newlines):

> E         File does not end with a newline: examples/reference/models/button_server.py, line 30
E         File does not end with a newline: examples/reference/models/checkbox_button_server.py, line 46
E         File does not end with a newline: examples/reference/models/checkbox_server.py, line 43
E         File does not end with a newline: examples/reference/models/data_table_server.py, line 34
E         File does not end with a newline: examples/reference/models/dropdown_menu_server.py, line 36
E         File does not end with a newline: examples/reference/models/multi_select_server.py, line 38
E         File does not end with a newline: examples/reference/models/radio_button_group_server.py, line 41
E         File does not end with a newline: examples/reference/models/radio_group_server.py, line 41
E         File does not end with a newline: examples/reference/models/range_slider_server.py, line 40
E         File does not end with a newline: examples/reference/models/select_server.py, line 41
E         File does not end with a newline: examples/reference/models/slider_server.py, line 37
E         File does not end with a newline: examples/reference/models/tab_panes_server.py, line 27

If you fix those the tests should go green. We can then decide whether to merge as-is, and follow on with work  to integrate into docs/tests, or if you want to work on those things in this PR

**Comment by bryevdv** [comment]
cc @mattpap what's required to get these run in the examples tests? just update the top level *examples.yaml* ?

**Comment by bryevdv** [comment]
@sarahheim FYI for the future, please collect multiple similar/related commits into one push. Every push starts a CI build, so all the pushes above would take many hours to complete and monopolize CI capacity the whole time

**Comment by bryevdv** [comment]
@samirak93 OK, almost there! It seems there is also an unused import tripping the linter:

> /examples/reference/models/range_slider_server.py:2:1: F401 'pandas as pd' imported but unused

**Comment by bryevdv** [comment]
I'm going to go ahead an merge this we can sort out docs/tests later. Thanks @samirak93

**Pull request merged**
