### PR TITLE
Ensure toolbars give themselves space in complex layouts

### PR DESCRIPTION
**Pull request by birdsarah**
Fixes: #4606

### CODE REVIEW

**Comment by mattpap** [comment]
@birdsarah, did you verify that JS/TS API and `bokehjs/examples/*` still work?

**Comment by birdsarah** [comment]
was just doing that! And no is the answer.

**Comment by birdsarah** [comment]
So.....we have a problem :D

**Comment by birdsarah** [comment]
Not going to merge this before we cut a release candidate, but we need to fix this before release. Any and all suggestions as to the root cause gratefully appreciated.

**Comment by mattpap** [comment]
Most likely [1] is the cause. This hack is needed to make bokehjs work at all with `initialize` in `LayoutDOM`. Using `initialize` is the right approach (I can explain separately if this is requested). Most likely, the underlying issue is that layout (constraints) are computed way too early in a `Document` (btw. I smell a performance regression here). Alternatively, the mixture of private initialization across different types of toolbar classes may be the reason. Or a combination of both.

[1] https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/tools/toolbar_base.coffee#L98 
[2] https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/tools/toolbar_box.coffee#L142

**Comment by birdsarah** [comment]
It's not [2] because this is not affecting ToolbarBoxes which are used for multiplot toolbars.

> Most likely, the underlying issue is that layout (constraints) are computed way too early in a Document 

Makes sense to me. Any thoughts on a solution?

>  This hack is needed to make bokehjs work at all with initialize in LayoutDOM. 

Right, so this makes me think that my understanding of the problem is correct. Toolbar._sizeable is set in plot initialization. But constraints are getting pulled up to document before all this initialization is complete.

> Using initialize is the right approach (I can explain separately if this is requested).

Would love that. I copied @havocp's original layout work in a couple of places and using constructor on the layout was one of them. But if it's not important to solving this problem then it can wait till later.

> (btw. I smell a performance regression here).

Would be very interested in details on this, but can wait till later I'm guessing.

I have one idea of how to solve this that may meet all our needs - which is to add the sizeable constraint at render time. I'll try that now.

Any other suggestions - like how initializing constraints later greatly appreciated.

**Comment by birdsarah** [comment]
I think I got it. Pushing in a minute or so and would appreciate help.

**Comment by birdsarah** [comment]
@mattpap, what do you think about this. JS examples are running nicely. And toolbars are spacing themselves. Am doing other tests now.

**Comment by birdsarah** [comment]
@mattpap I'm going to merge this and cut the release candidate when the tests pass (~30 mins) if you have any more thoughts, now would be a great time.

**Comment by mattpap** [comment]
@birdsarah, LGTM.

**Pull request merged**
