### PR TITLE
Use @types/gulp 3.x with gulp 3.x

### LINKED ISSUE #6391: bokehjs' build uses gulp 3.x but @types/gulp 4.x
This causes valid gulp build files not compile, erroring with bad signatures.

### PR DESCRIPTION
**Pull request by mattpap**
fixes #6391

### CODE REVIEW

**Comment by bryevdv** [comment]
OK, cool I am not going to try to revert `rc1` I will just make a new `rc2`

**Comment by bryevdv** [comment]
@mattpap builds still failing, differently now:
```
ERROR: 'gulp build' returned the following
---- on stdout:
    
---- on stderr:
     Unable to compile TypeScript
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/browserify/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/chai/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/chalk/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/del/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/event-stream/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/glob/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/gulp-insert/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/gulp-less/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/gulp-rename/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/gulp-sourcemaps/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/gulp-task-listing/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/gulp-util/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/gulp/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/hammerjs/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/insert-module-globals/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/minimatch/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/mocha/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/node/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/orchestrator/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/proj4/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/q/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/rbush/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/resolve/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/run-sequence/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/sprintf/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/through/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/through2/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/timezone-js/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/vinyl/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/yargs/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/browserify/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/chalk/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/del/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/event-stream/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/events/events.js' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/events/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/glob/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/gulp-insert/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/gulp-less/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/gulp-rename/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/gulp-sourcemaps/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/gulp-task-listing/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/gulp-typescript/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/gulp-util/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/gulp/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/insert-module-globals/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/minimatch/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/orchestrator/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/resolve/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/run-sequence/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/through/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/through2/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/typescript/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/vinyl/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    File '/home/travis/build/bokeh/bokeh/bokehjs/node_modules/yargs/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
    
The command "scripts/travis_install" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by mattpap** [comment]
This is bizarre. For now I'm not able to reproduce this locally. I suspected new ts-node release (40 minutes ago) caused this, but it doesn't seem so.

**Comment by mattpap** [comment]
Other builds are affected as well, but still can't reproduce locally.

**Comment by mattpap** [comment]
So ts-node is actually at fault. This is truly bizarre that only travis ci is affected. Unfortunately, there are more errors:
```
/home/travis/build/bokeh/bokeh/bokehjs/node_modules/@types/gulp/index.d.ts(15,15): error TS2430: Interface 'Gulp' incorrectly extends interface 'Orchestrator'.
  Types of property 'task' are incompatible.
    Type 'AddMethod' is not assignable to type '{ (name: string): Task; (name: string, fn: TaskFunc): void; (name: string, dep: string[], fn: Tas...'.
      Type 'Orchestrator' is not assignable to type 'Task'.
        Property 'fn' is missing in type 'Orchestrator'
```

**Comment by mattpap** [comment]
@bryevdv, yes, but I needed find the right combination. Hopefully what I just pushed should work.

**Comment by mattpap** [comment]
@bryevdv, this works.

**Pull request merged**
