### PR TITLE
Fix/add autoadd setter

### PR DESCRIPTION
**Pull request by brendancol**
Related issues:
https://github.com/bokeh/bokeh/issues/3638
https://github.com/bokeh/bokeh/issues/3546

example to see in action:
```python
from bokeh.models.widgets import HBox
from bokeh.io import curdoc, curstate
from bokeh.sampledata.autompg import autompg as df
from bokeh.charts import Scatter
curstate().autoadd = False
s = Scatter(df, x='mpg', y='hp', color='cyl', marker='origin',
                          title="Auto MPG", xlabel="Miles Per Gallon",
                                            ylabel="Horsepower")
b = HBox()
b.children = [s]
doc = curdoc().add_root(b)
```
screen shot 2016-01-25 at 11 57 04 am

### CODE REVIEW

**Comment by bryevdv** [comment]
@brendancol the setter was added to `State` what's the rationale for the last commit?

**Comment by brendancol** [comment]
So the `builder.py` change was a false fix for trouble in my PR example.  PR example updated, curstate -> curdoc change reverted...

**Comment by bryevdv** [comment]
@brendancol can you elaborate? Are you saying setting `autoadd` to `False` before creating the chart does not solve the problem?

**Comment by brendancol** [comment]
No, it DOES solve the problem.  All should be good here

**Comment by bryevdv** [comment]
Leaving #3546 open pending a more comprehensive (automatic) solution.

**Pull request merged**
