### PR TITLE
isolate instantiation/initialization from json better

### LINKED ISSUE #8627: issue with bokeh.client after layout PR
@mattpap can you fill in the details here? (How to reproduce, etc). It's been awhile and this keeps falling off my radar because there has not been an issue.

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #8627
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

@mattpap if you think this seems reasonable I will add some tests and merge.

### CODE REVIEW

**Comment by bryevdv** [comment]
OK app tests run but need baselines
```
tests/test_examples.py::test_server_examples[/home/travis/build/bokeh/bokeh/examples/app/apply_theme.py-example0-config0] 
[INFO] Example rendered in 1.060s
[JS] {log} http://localhost:5006/static/js/bokeh.min.js?v=8ec2289e1baa0c3e0c0b9e018735cea5:31:52635 [bokeh] setting log level to: 'info'
[JS] {info} http://localhost:5006/static/js/bokeh.min.js?v=8ec2289e1baa0c3e0c0b9e018735cea5:31:4611 [bokeh] Websocket connection 0 is now open
[JS] {info} http://localhost:5006/static/js/bokeh.min.js?v=8ec2289e1baa0c3e0c0b9e018735cea5:31:118316 [bokeh] document idle at 65 ms
[JS] {log} http://localhost:5006/static/js/bokeh.min.js?v=8ec2289e1baa0c3e0c0b9e018735cea5:31:132810 Bokeh items were rendered successfully
[FAIL] tests/baselines/examples/app/apply_theme baseline doesn't exist
[WARN] reference image https://s3.amazonaws.com/bokeh-travis/1.1.0dev3-876d72e/examples/app/apply_theme.png doesn't exist
FAILED
```

**Comment by bryevdv** [comment]
Ok I added the baselines, we will see if they match on Travis. However, even after adding them, at least locally it says they are not found (and hence still fail):

> [FAIL] tests/baselines/examples/app/apply_theme baseline doesn't exist

(it definitely does exist)

**Comment by bryevdv** [comment]
OK, it is finding the baselines, but they don't match. I'd kind of like to get this merged, without holding up for #8645 to be fixed. Maybe you can generate baselines on linux?

**Comment by mattpap** [comment]
`app/faces` uses `cv2` module which isn't specified in test dependencies. Also, exceptions in server examples don't make tests fail, because bokeh.application just logs them. I think that at least for testing we should allow exceptions to fail a program.

**Comment by mattpap** [comment]
Actually, `cv2` is installed by `opencv`.

**Comment by bryevdv** [comment]
> I think that at least for testing we should allow exceptions to fail a program.

Certainly seems like the correct thing to me

**Pull request merged**
