### PR TITLE
added tooltip font color to avoid being masked by color:white property from outside css

### LINKED ISSUE #5726: Tooltip font color can be turned white by outside css because it's not specified by bokeh
This is to make a case for a fork with a fix.

### PR DESCRIPTION
**Pull request by DylanAlloy**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes #5726
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@DylanAlloy apologies, we had a problem to resolve with our CI testing. Can you merge / rebase master into this PR?

**Comment by bryevdv** [comment]
@mattpap @birdsarah aware of any integration tests that this small change would impact? In absence of the submitter, I'd like to just merge.

**Comment by birdsarah** [comment]
No, but I don't think this is the right color. 

#999 is pretty light. I think it should be @gray-dark (https://github.com/bokeh/bokeh/blob/master/bokehjs/src/vendor/bootstrap-3.1.1/less/variables.less#L11)

You should def test this locally.

**Comment by bryevdv** [comment]
I can change to `@gray-dark` in the GH UI, I don't think I can do the merge easily though.

**Comment by bryevdv** [comment]
@birdsarah is that the correct syntax?

**Comment by bryevdv** [comment]
Actually I replaced the no-arch packages on the bokeh channel, tests may just pass now.

**Comment by birdsarah** [comment]
should be, but do check it's working locally

**Comment by bryevdv** [comment]
CSS building seemed to fail with that change.

**Comment by bryevdv** [comment]
Trying `darkgray`

**Comment by birdsarah** [comment]
see the link above - the variable is called dark-gray - you may need to import it. If not, the quick fix is just `#333`.

**Comment by mattpap** [comment]
btw. bootstrap should not be used anymore in core bokehjs.

**Comment by mattpap** [comment]
I'm curious what's the underlying cause for color propagation in this case? Inheritance? This PR may be a quick fix, but we may want to look for more systematic solution, because we don't want to configure every CSS property for every class we have.

**Comment by birdsarah** [comment]
> btw. bootstrap should not be used anymore in core bokehjs.

good point

**Comment by bryevdv** [comment]
Tested locally, merging now

**Comment by DylanAlloy** [comment]
Just wanted to say sorry I wasn't around to do a merge request again but it looks like you folks have it figured out.

**Pull request merged**
