### PR TITLE
Fix regression in GMapPlotCanvas' initialization code

### LINKED ISSUE #7688: GMapPlot not rendering
#### Software version info
- Bokeh 0.12.15dev6
- Python 3.6.3
- Windows 10
- Tested with Chrome and Edge

#### Expected behavior and the observed behavior
- Expected GMap plot to be displayed in browser window.
- Bokeh frame and window generates correctly, but no map shown. 
- Equivalent to when an invalid API key is provided.
- Same program and API key worked in Bokeh 0.12.14

#### Tested using example shown below from Bokeh docs:
```
from bokeh.io import output_file, show
from bokeh.models import (
  GMapPlot, GMapOptions, ColumnDataSource, Circle, Range1d, PanTool, WheelZoomTool, BoxSelectTool
)

map_options = GMapOptions(lat=30.29, lng=-97.73, map_type="roadmap", zoom=11)

plot = GMapPlot(x_range=Range1d(), y_range=Range1d(), map_options=map_options)
plot.title.text = "Austin"

# For GMaps to function, Google requires you obtain and enable an API key:
#
#     https://developers.google.com/maps/documentation/javascript/get-api-key
#
# Replace the value below with your personal API key:
plot.api_key = "MY_API_KEY"

source = ColumnDataSource(
    data=dict(
        lat=[30.29, 30.20, 30.29],
        lon=[-97.70, -97.74, -97.78],
    )
)

circle = Circle(x="lon", y="lat", size=15, fill_color="blue", fill_alpha=0.8, line_color=None)
plot.add_glyph(source, circle)

plot.add_tools(PanTool(), WheelZoomTool(), BoxSelectTool())
output_file("gmap_plot.html")
show(plot)

```
#### Screen Capture
bokehcapture

### PR DESCRIPTION
**Pull request by mattpap**
fixes #7688

### CODE REVIEW

**Comment by bryevdv** [comment]
Tested locally. We could test on travis, we send an encrypted API key to the builds.

**Comment by mattpap** [comment]
>  We could test on travis, we send an encrypted API key to the builds.

The key has to be included in HTML (bokeh's JSON in particular), so encrypted keys aren't going to help here.

**Comment by OxygenLithium** [comment]
Great, thanks!
Will this be in the next dev build?

**Comment by bryevdv** [comment]
Yes, I will make one later today

**Comment by bryevdv** [comment]
FYI `dev7` is available

**Pull request merged**
