### PR TITLE
add missing date slider to widgets page

### LINKED ISSUE #12744: Built-in widgets docs page does not include DateSlider
In `docs/bokeh/source/docs/user_guide/interaction/widgets.rst` there is no `DateSlider` mentioned:

Screenshot 2023-01-16 at 11 14 24

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #12744
- [x] release document entry (if new feature or API change)

Screenshot 2023-01-25 at 10 43 29

### CODE REVIEW

**Review by ianthomas23 — APPROVED** [review]
Thanks for fixing this so quickly.

**Comment by bryevdv** [comment]
@mattpap any idea what is going on with this one examples test
```
tests/test_examples.py::test_file_examples[/home/runner/work/bokeh/bokeh/examples/models/widgets.py-example227-config227] 
[INFO] Example run in 1.739s
[INFO] Example rendered in 1.399s
[JS] {log} http://localhost:5006/static/js/bokeh.js:3621:21 [bokeh] setting log level to: 'info'
[JS] {warning} http://localhost:5006/static/js/bokeh-widgets.js:7434:41 Deprecation warning: allowHTML will default to false in a future release. To render HTML in Choices, you will need to set it to true. Setting allowHTML will suppress this message.
[JS] {warning} http://localhost:5006/static/js/bokeh-tables.js:1157:38 [bokeh] jquery-ui is required to enable DataTable.reorderable
[JS] {info} http://localhost:5006/static/js/bokeh.js:699:34 [bokeh] document idle at 736 ms
[JS] @https://unpkg.com/@tabler/icons@2.0.0/iconfont/tabler-icons.min.css
[JS] Failed to load resource: the server responded with a status of 404 ()
FAILED
```

Nothing in this PR would affect that test in any way that I can see. 


EDIT: Well, I guess this example is failing in all new PRs. Presumably the is because of the deprecation warning for choices

**Review by tcmetzger — APPROVED** [review]
This is great, thank you!

**Comment by tcmetzger** [comment]
@bryevdv @mattpap The test failure seems unrelated to the changes in this PR, so I think we can merge this!

**Pull request merged**
