### PR TITLE
Removed unnecessary calls to _recompute_all_models() to speed up adding roots

### LINKED ISSUE #11707: [BUG] Poor scaling when embedding many widgets into the Jinja template
Originally posted here: https://discourse.bokeh.org/t/poor-scaling-when-embedding-many-widgets-into-the-jinja-template/8456.

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.4.0
Python 3.9.6
MacOs Catalina 10.15.7
Google Chrome 94.0.4606.61

#### Description of expected behavior and the observed behavior
I’ve been seeing poor runtime performance with my Bokeh application. After seeing https://discourse.bokeh.org/t/bokeh-version-0-12-10-incredibly-slow/2772, and noticing that my Console is giving me a lot of warnings about layout computes taking a long time, I decided to try using Bootstrap to layout the application, embedding individual Bokeh components into it.

This greatly improved the runtime performance. However, the loading time of the website is now quite abysmal. Running Chrome’s Lighthouse Audit (https://developer.chrome.com/docs/devtools/speed/get-started/), I see that the issue is the initial server response time. Basically, it’s taking a long time for the server to deliver the HTML page.

In debugging the issue, I’ve found that this embedding method works well when there are only a few Bokeh components, but it scales poorly as the number of Bokeh components increases, getting very slow once there are a few hundred components (and in my application, there are indeed a few hundred components).

I illustrate this issue here: https://github.com/EfremBraun/bokeh-scaling-demo. I took the Movies example from https://github.com/bokeh/bokeh/tree/branch-3.0/examples/app/movies and made some changes. `original-0` was taken directly from the example, with 0 new widgets added, `original-100` added 100 additional Slider widgets, and `original-200` added 200 additional Slider widgets. `embed-0` is the original example, but using embedding/Bootstrap for the display; `embed-100` took that and added 100 additional Slider widgets, and `embed-200` added 200 additional Slider widgets.

When I run `bokeh serve original-0`, open the application in a Chrome Incognito tab, and run the Lighthouse Audit, I get a 65 performance score. `bokeh serve original-100` gets a 64, and `bokeh serve original-200` also gets a 64. However, while `bokeh serve embed-0` gets a 62 performance score (already lower than the original page, though not so bad), `bokeh serve embed-100` gets a 58, and `bokeh serve original-200` gets a 54, and the page load time is noticeably slower. Screenshots showing these details can be seen below.

Screen Shot 2021-09-30 at 4 32 07 PM
Screen Shot 2021-09-30 at 4 32 09 PM
Screen Shot 2021-09-30 at 4 32 11 PM
Screen Shot 2021-09-30 at 4 32 12 PM
Screen Shot 2021-09-30 at 4 32 13 PM
Screen Shot 2021-09-30 at 4 32 27 PM

### PR DESCRIPTION
**Pull request by EfremBraun**
- [x] issues: partially fixes #11707

### CODE REVIEW

**Comment by EfremBraun** [comment]
Ah, I see the issue. The tests directly access BokehJS's `add_root()` in `document.ts`, whereas the change I made relies on `add_root()` being accessed indirectly and then calling `recompute_all_models()` afterwards. If `add_root()` is accessed directly, then `recompute_all_models()` never gets called.

Let me think of a more elegant way to address this...

**Comment by bryevdv** [comment]
@EfremBraun Thanks for posting a PR, it's easier for me to digest proposed changes by just seeing them as a diff. Now that I have, why don't we back up a step. The purpose of the push/pop freeze functions is itself to prevent over-(re-)computation. Why don't we use that facility as intended? There is a loop for adding roots, why not try to fence the original push/pop functions around the entire loop? That should be sufficient to prevent a re-computation on on the individual roots.

**Comment by g-parki** [comment]
@EfremBraun the Windows test issue is fixed now. Can you please rebase and force push? My typical way to do so (sorry if you're already familiar with this):

1. Update your Github repository
2. From your project folder: `git pull`
3. Check out main branch: `git checkout branch-3.0`
4. Rebase `git rebase branch-3.0 your_branch_name`
5. Checkout your branch `git checkout your_branch_name`
6. Push updates to Github `git push -f`

**Comment by EfremBraun** [comment]
Done, though I used:
1. `git fetch upstream`
2. `git merge upstream/branch-3.0 branch-3.0`
3. `git push origin branch-3.0   `

**Pull request merged**
