### PR TITLE
Improve performance of widget heavy layouts

### LINKED ISSUE #8622: Input Widget heights behavior
#### Description of expected behavior and the observed behavior
I tried to fix height for widgets of type input however the input element does not fit the height specification

#### Complete, minimal, self-contained example code that reproduces the issue
```python
from bokeh.models import Slider, TextAreaInput

from bokeh.io import show, output_notebook, output_file
from bokeh.layouts import column, widgetbox
output_file('test.html')

text = TextAreaInput(value='test', height=100, rows=50, sizing_mode='fixed')
slid = Slider(value=5, start=0, end=10)
show(widgetbox(text, slid))
```
image

I would have expected this output:
image

### PR DESCRIPTION
**Pull request by mattpap**
addresses #8084
fixes #8622

### CODE REVIEW

**Comment by philippjfr** [comment]
Apologies if this is way too premature but I'm way too excited about this. First of all to say that this solves all the performance issues, thing are super snappy now. This whole layout refactor is huge step forward and I'm super excited about it.

In case it is at all helpful, my initial attempts did raise a few errors, e.g. about Select not being a valid model and this error I haven't looked into further:

```
Uncaught TypeError: (intermediate value)(...) is not a function
    at inline_js (<anonymous>:40284:7)
```

The only other issue is centering of widget titles:

screen shot 2019-02-26 at 6 53 44 pm

I'll do some more thorough testing once you've removed the WIP label.

**Comment by mattpap** [comment]
> `Uncaught TypeError: (intermediate value)(...) is not a function
    at inline_js (<anonymous>:40284:7)`

This looks like a side effect of PR #8682.

**Comment by mattpap** [comment]
@philippjfr, this is ready. Also, how did you end up with the above error?

**Comment by mattpap** [comment]
> The only other issue is centering of widget titles:

This should be fixed now. What browser do you use? I used a wrong value for alignment and both FF and Chrome rendered it correctly anyway.

**Comment by philippjfr** [comment]
I was using Chrome on OSX but it is indeed fixed now. I think the other errors must have been due to an old bokehjs sticking around or something similar because I can't reproduce them anymore. If it turns out that I can reproduce them later I'll just file an issue.

**Comment by bryevdv** [comment]
Unless there is objection I'll merge this and cut a dev build in the morning

**Pull request merged**
