### PR TITLE
Select widget optgroup feature enhancement #7150

### PR DESCRIPTION
**Pull request by memetb**
Added optgroup feature to Select widget, implemented as a Dict containing lists.

Code listing provided in Issue #7150 

I will require guidance with regards to possible tests for this feature. 

Thanks.

### CODE REVIEW

**Comment by bryevdv** [comment]
@memetb there was a problem with an upstream tool, that has since been pinned to a working version. You will need to merge/rebase on current master for the build to work again

**Comment by bryevdv** [comment]
Also, there is a small merge conflict from #7161 that will need to be resolved, let m know if there is any questions

**Comment by memetb** [comment]
I've resolved the conflict for #7161 (you're right, it was s/`options`/`contents`/) and I've merged bokeh master back in. 

There still seems to be a problem with `mocha` in the ci builds. 

Feedback welcome.

**Comment by bryevdv** [comment]
@memetb the test that is failing is the test that ensures that the default property values between python and BokehJS stay strictly in line. The actual problem is buried up at the top:
```
Select: defaults are out of sync between Python and bokehjs
    Select.options: bokehjs defaults to [] but python defaults to {}`
```
You can either explicitly provide `default=[]` on the python side, or swapping the order of the `Either` subclauses (to put the `List` type first) would probably also work.

Can you attach a small complete code sample to this  PR that demonstrates the new feature, as well as a screen shot or capture?

**Comment by memetb** [comment]
@bryevdv thanks for that. I'm sorry I didn't catch that. 

Usage and screenshots as follows:
```
from bokeh.layouts import layout, column, row
from bokeh.models.widgets import Select, PreText
from bokeh.io import curdoc


test1 = Select(title="Select (labels only)", value="1",options=["A","B", "C"])

test2 = Select(title="Select (labels and values)", value="1",options=[("1","A"),("2", "B"), ("3", "C")])


test3 = Select(title="Select (labels and numeric values)", value="1",options=[(1,"A"),(2, "B"), (3, "C")])
test4 = Select(title="Select (optgroup, labels only)", value="1",options=dict(first=["A","B", "C"],
													 second=["X", "Y", "Z"]))

test5 = Select(title="Select (optgroup, labels and values)", value="4",options=dict(first=[("1","A"),("2", "B"), ("3", "C")],
													 second=[("4","X"),("5", "Y"), ("6", "Z")]))

test6 = Select(title="Select (optgroup, labels and values #2)", value="4",
		options=dict([("First Group &<>",[("1","A"),("2", "B"), ("3", "C")]),
					("Second Group &<>", [("4","X"),("5", "Y"), ("6", "Z")])]) )

# curdoc().add_root(column(test1, test2, test3))
curdoc().add_root(column(row(test1, test2, test3),
						 row(test4, test5, test6)))
curdoc().title = "Testing select"

```

To run, simply bokeh serve the above code.

Output should look as follows:
image

image

image


(I'll keep an eye out for any CI problems)

**Comment by bryevdv** [comment]
Thanks @memetb CI is green now. @mattpap do you have any objections or comments?

**Comment by bryevdv** [comment]
I'll plan on merging this in a few hours absent comment

**Comment by bryevdv** [comment]
Thanks @memetb! FYI if you intend to continue making contributions we should discuss adding you to @bokeh/dev

**Comment by memetb** [comment]
You're welcome. 

@bryevdv : wrt @bokeh/dev, I'm not sure what that entails in terms of expectations and privileges. I will most likely be making occasional small contributions like this one as time permits. If adding me to @bokeh/dev will make that easier for you, then I guess it's fine.

Otherwise, I don't need anything from you guys (in terms of workflow access) that wasn't already available here.

**Pull request merged**
