### PR TITLE
Add support for --build-dir argument to gulp build

### PR DESCRIPTION
**Pull request by mattpap**
This will be useful when using gulp build from other build systems, like sbt. This commit also fixes the build to not use hard-coded paths. Also uses `path.join()` instead of naive path string concatenation.

### CODE REVIEW

**Comment by bryevdv** [comment]
This LGTM, @damianavila @mistakevin any comments?

**Comment by mistakevin** [comment]
Looks good, can it go in the documentation?

**Comment by mistakevin** [comment]
Also currently working on PR https://github.com/bokeh/bokeh/pull/2671 to clean up how we produce source maps. Might have some conflicts (that I'll resolve when this is merged).

**Comment by bryevdv** [comment]
I added a blurb for documentation, will merge when tests pass.

**Pull request merged**
