### PR TITLE
Traverse views function to add bk-* classes

### PR DESCRIPTION
**Pull request by mistakevin**
resolves https://github.com/bokeh/bokeh/issues/2527

### CODE REVIEW

**Comment by birdsarah** [comment]
Is it simple to add a test for this? What we really probably want is some kind of test that ensures all output has class with `bk-` prefix. Although I'm not sure that's possible.

**Comment by mistakevin** [comment]
We could test the function itself by giving it a dummy element, but I think we'd need a selenium test to test a rendered plot.

**Comment by birdsarah** [comment]
test function sounds fine. 

alternative to selenium for this particular case: ....making an example with all the widgets in it, and then just parsing the html with beautiful soup to check for the classes....

**Comment by mistakevin** [comment]
mocha test added using cheerio

**Comment by birdsarah** [comment]
@mistakevin - nice! cheerio looks awesome.

Was testing this out and mostly works. The only thing is it doesn't catch the classes that are triggered by interactions - ui-state-focus, ui-state-hover, ui-state-active. (see gif below)

I checked on 0.8.2 and these do get pre-pended by bk. Am also wondering why in 0.8.2 the slider is a `span` but in 0.9.2 it's an `a`.

screencast


I don't think this is the end of the world. This PR definitely fixes the regression.

**Comment by mistakevin** [comment]
I was able to capture those last few `ui-*` classes, but it interferes with jquery-ui's use of them, as it targets those classes. I can see us hitting more of these issues in the future. Instead of prepending `bk-*` to encapsulate ourselves everywhere, we might want to investigate [using a "scoped" stylesheet](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style#A_scoped_stylesheet)

**Comment by mistakevin** [comment]
Oops, [not yet supported by all browsers](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style#Browser_compatibility)

**Comment by damianavila** [comment]
Yep, not supported everywhere, but thanks for the `scoped` reference... interesting thing I did not know about.

**Comment by damianavila** [comment]
Are we targeting this one to 0.9.3? Or deserves more discussion?

**Comment by mistakevin** [comment]
I believe it's good to go. The classes that are added by jquery-ui are purely functional for jquery-ui and are not used for styling. It's also a pretty frustrating bug (from experience)

**Comment by mattpap** [comment]
> Am also wondering why in 0.8.2 the slider is a `span` but in 0.9.2 it's an `a`.

This may have something to do with this:
```
bokehjs$ grep jquery-ui package.json 
    "jquery-ui": "^1.10.5",
bokehjs$ ls src/vendor/ -1 | grep jquery-ui
jquery-ui-1.11.2
```
This means we use JS and CSS from different versions of jquery-ui. In 0.8.2 we used 1.11.2 for both.

**Comment by mattpap** [comment]
> The classes that are added by jquery-ui are purely functional for jquery-ui and are not used for styling.

Sadly that's not true. For example, `ui-state-hover` is visible in the gif and not prefixed:
```
$ git grep ui-state-hover bokehjs/src/vendor/jquery-ui-1.11.2/
bokehjs/src/vendor/jquery-ui-1.11.2/css/theme.css:.bk-ui-state-hover,
bokehjs/src/vendor/jquery-ui-1.11.2/css/theme.css:.bk-ui-widget-content .bk-ui-state-hover,
bokehjs/src/vendor/jquery-ui-1.11.2/css/theme.css:.bk-ui-widget-header .bk-ui-state-hover,
bokehjs/src/vendor/jquery-ui-1.11.2/css/theme.css:.bk-ui-state-hover a,
bokehjs/src/vendor/jquery-ui-1.11.2/css/theme.css:.bk-ui-state-hover a:hover,
bokehjs/src/vendor/jquery-ui-1.11.2/css/theme.css:.bk-ui-state-hover a:link,
bokehjs/src/vendor/jquery-ui-1.11.2/css/theme.css:.bk-ui-state-hover a:visited,
bokehjs/src/vendor/jquery-ui-1.11.2/css/theme.css:.bk-ui-state-hover .bk-ui-icon,
```

**Comment by mattpap** [comment]
If anyone wants a quick and easy solution, just revert jquery-ui's javascript removal (5bf2357c1e9ecec349dae1bc6ee8c85cfec6a730 is the offending commit).

**Comment by damianavila** [comment]
ok, this need to be further discussed... pushing to 0.9.4

>If anyone wants a quick and easy solution, just revert jquery-ui's javascript removal (5bf2357 is the offending commit).

That can be done as a hotfix (post freeze) if we decide it is needed or push it into the release.

**Comment by mistakevin** [comment]
I do see that there is a pretty serious disconnect between our custom jquery-ui css and the vendor js. What is the main reasoning behind adding the `bk-*` prefix? Only to isolate ourselves from a users custom stylesheet should they style their own bootstrap/jquery-ui css?

**Comment by mattpap** [comment]
@mistakevin, pretty much to completely isolate bokehjs from the environment in with it's being embedded. This means, for example, being able to use bokehjs in IPython notebook.

**Comment by bryevdv** [comment]
So, what should we do with this PR? Is it something to pursue (conflicts need resolving)? Or should we close it and table things for now? @mattpap @mistakevin

**Comment by mistakevin** [comment]
@bryevdv @mattpap Here is the example I was using to debug this issue. It would be pretty frustrating to come across, and who knows where else it's happening.
```python
from bokeh.embed import components
from bokeh.models import Slider
from jinja2 import Template
import webbrowser
import os
import six


s = Slider(start=0, end=92, value=1, step=1, title="Time")

script, div = components(s)

template = Template('''<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Slider Bug</title>
        <link rel="stylesheet" href="bokeh/bokehjs/build/css/bokeh.css" type="text/css" />
        <style>.bk-slider-horizontal{max-width:900px}</style>
        <script type="text/javascript" src="bokeh/bokehjs/build/js/bokeh.js"></script>
        {{ script }}
    </head>
    <body>
        {{ div }}
    </body>
</html>
''')

html_file = 'slider.html'
with open(html_file, 'w') as textfile:
    textfile.write(template.render(script=script, div=div))
url = 'file:{}'.format(six.moves.urllib.request.pathname2url(os.path.abspath(html_file)))
webbrowser.open(url)
```

**Comment by bryevdv** [comment]
Well, this no longer merges cleanly. @mattpap @mistakevin can you come to a decision about whether this need to be pursued? If not we should close it.

**Comment by mistakevin** [comment]
Well, do we want to support that example above? I've confirmed the issue is still there

**Comment by mattpap** [comment]
My resolution is in PR #3177.

**Comment by mistakevin** [comment]
Nice! Then we can close this PR

**Pull request closed without merging**
