### PR TITLE
Windows platform test corrections

### LINKED ISSUE #8146: Unit tests failing in Windows 7
Bokeh version 1.0.0dev5(?) (Cloned on 8/6/2018)
Platform: Win7x64, py36

I cloned the Bokeh repo and followed all of the setup instructions listed on [this page](https://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html). Without making any code changes, I then ran the following command from the top level of the cloned repo:

```
py.test -m unit
```

**Expected behavior**: All tests to pass.
**Observed behavior**: 15 test failures, details tabulated in attachments.
[bokeh_Windows_unit_test_failures.pdf](https://github.com/bokeh/bokeh/files/2270743/bokeh_Windows_unit_test_failures.pdf)
[bokeh_Windows_unit_test_failures.xlsx](https://github.com/bokeh/bokeh/files/2270744/bokeh_Windows_unit_test_failures.xlsx)

Per Bryan Van de Ven: "The majority of those [test failures] look to be related to platform specific path and line ending differences." Per his request, I am creating this issue to document which Windows tests might need to be addressed/updated.

### PR DESCRIPTION
**Pull request by xavArtley**
Python version      :  3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
IPython version     :  6.5.0
Bokeh version       :  1.0.0dev6-14-g463049309
BokehJS static path :  g:\pythonworkspace\bokeh\bokeh\server\static
node.js version     :  v8.9.3
npm version         :  6.4.1

- [ ] issues: fixes #8146
- [ ] tests: 0 added / +11 passed / +1 skipped

===== 4 failed, 2999 passed, 698 deselected, 1 warnings in 106.19 seconds =====

### CODE REVIEW

**Comment by xavArtley** [comment]
I have identified an other difference between windows and unix but I don't know how to correct it
In test_set_data_from_json_nested_base64 (from bokeh\models\tests\test_sources.py) the failure is due to the dtype return by np.arange(3)
Windows:
`np.arange(3).dtype` return ` dtype('int32')`
Linux :
`np.arange(3).dtype` return  `dtype('int64')`

So
`
array_encoding_disabled(np.arange(3))
`
return `False` on windows and `True` on unix and lead to an error in the test with windows

It's easy to change the test to force the type of data `np.arange(3).astype('int64')`
But it will just masked a potential problem in windows

Any advice to correct it?

**Comment by xavArtley** [comment]
You test work test this one instead of

```
ds = ColumnDataSource()
data = {"foo": [[np.arange(3)]]}
json = transform_column_source_data(data)
ds.set_from_json('data', json)
ds.data['foo']
```

**Comment by bryevdv** [comment]
> Any advice to correct it?

@xavArtley if NumPy behaves differently on (32bit) windows then Bokeh will behave differently (appropriately) so any test would need to take that into account. We could have different versions of the test and switch between them based on platform using the pytest decorators. 

However, it seems to me the best option is just not to use `np.arange` in the test. The test is not a tesrt of `np.arange`, it's a test that Bokeh does the right thing based on a particular dtype. If `np.arange` is not consistent across platforms, we should just create e.g. `np.array([1,2,3], dtype='int64') explicitly.

**Comment by bryevdv** [comment]
@xavArtley BTW do you have any experience with Appveyor? I really appreciate your taking the time to fix these issues on windows, once tests are running, I'd love to keep them that way, and automated.

**Comment by xavArtley** [comment]
I don't know Appveyor but I can learn.
Ok for np.arange(3, dtype='int64'). It will simplify the correction.
However the last 3 errors I don't know if I could correct it.

**Comment by bryevdv** [comment]
@xavArtley which three are failing?

**Comment by bryevdv** [comment]
@xavArtley FYI I resolved the merge conflict here in the GH UI, you'll want to do a pull

**Comment by xavArtley** [comment]
These are the 3 errors I don't know how to fix.
The last one is may be the simpliest

```
>       assert len(gc.get_referrers(mod)) == 4
E       AssertionError: assert 3 == 4
E        +  where 3 = len([[<bokeh.document.tests.test_document.Test_Document_delete_modules.test_extra_referrer_error.<locals>.FakeMod object a...s.test_document.Test_Document_delete_modules.test_extra_referrer_error.<locals>.FakeMod object at 0x000000000D199A90>]])
E        +    where [[<bokeh.document.tests.test_document.Test_Document_delete_modules.test_extra_referrer_error.<locals>.FakeMod object a...s.test_document.Test_Document_delete_modules.test_extra_referrer_error.<locals>.FakeMod object at 0x000000000D199A90>]] = <built-in function get_referrers>(<bokeh.document.tests.test_document.Test_Document_delete_modules.test_extra_referrer_error.<locals>.FakeMod object at 0x000000000D199A90>)
E        +      where <built-in function get_referrers> = <module 'gc' (built-in)>.get_referrers

bokeh\document\tests\test_document.py:120: AssertionError
```


```
>       assert handler.hooks == ["server_loaded",
                                 "next_tick_server",
                                 "timeout_server",
                                 "periodic_server",
                                 "session_created",
                                 "next_tick_session",
                                 "modify",
                                 "timeout_session",
                                 "periodic_session",
                                 "session_destroyed",
                                 "server_unloaded"]
E       AssertionError: assert ['server_load...session', ...] == ['server_loade...session', ...]
E         At index 6 diff: 'timeout_session' != 'modify'
E         Use -v to get the full diff

bokeh\server\tests\test_server.py:183: AssertionError
```

```
>       assert _open_args == (('file:///foo/bar',), {'autoraise': True, 'new': 0})
E       AssertionError: assert (('file://G:\...ue, 'new': 0}) == (('file:///foo...ue, 'new': 0})
E         At index 0 diff: ('file://G:\\foo\\bar',) != ('file:///foo/bar',)
E         Use -v to get the full diff
```

**Comment by xavArtley** [comment]
At the same time I tried to make an appveyor build
https://ci.appveyor.com/project/xavArtley/bokeh

**Comment by bryevdv** [comment]
@xavArtley 

* for the first, can you run the test with `-vv` to get more detail? That test is asserting that no unexpected things are holding references to the Bokeh app module. It's possible that there is different behavior on windows, and that is OK. Or it might not be OK. But first we need an idea of what the extra referrer is. 

* It's possible this is just a timing that needs to be tuned. The test is asserting that lifecycle hooks happen in a specified order, but if the first six take longer on windows than they do on linux, that might mean the fixed timeout callback happens before other things (which would be fine, and correct) Can you try increasing the "check unused" value here to see if it makes a difference?

    https://github.com/bokeh/bokeh/blob/a8f1ef922089d3a8d6c843ff843334a013b8b508/bokeh/server/tests/test_server.py#L144

* Third one looks like standard linux/windows path diff. Only real question, is it just an issue with the test, or does something need to change in the library itself. 

* Re: appveyor, awesome! It looks like it is getting all the install parts done. Is there any way to have it just print out all of the output of `py.test -v -m unit` ? Then there would be fine grained visibility into exactly what tests fail

**Comment by xavArtley** [comment]
for appveyor no test is passed for the moment. I think it fails trying to get version from git
git describe --tags --always HEAD

**Comment by xavArtley** [comment]
For the moment the build works and indeed the failure occur on py.test -m unit command
The last build was just a branch to test the command 
git describe --tags --always HEAD

**Comment by bryevdv** [comment]
@xavArtley my guess is that you have not changed directory to be in the "bokeh" checkout, before running the `py.test` command. I think if you do that, things will proceed.

**Comment by bryevdv** [comment]
@xavArtley OK strangely enough I am seeing the referrers test now fail on some linux builds as well. I will also investigate.

**Comment by bryevdv** [comment]
Looking more closely, it seems as though there is actually one *less* referrer, not more. Tho I would be curious to know why, that generally seems like it could only be a good thing. Perhaps the test can just become `<=4` instead of `==4`

**Comment by xavArtley** [comment]
May be version of python?
On my computer I pass test with python 3.7

**Comment by bryevdv** [comment]
I believe the referrers test failure is specific to python 3.7, I was about to ask.

**Comment by bryevdv** [comment]
@xavArtley can you merge/rebase on master when you get a chance?

**Comment by bryevdv** [comment]
@xavArtley also when you have a chance, can you run the following script on windows with python 3.7 (and 3.6 if possible) and include the outpuyt here?
```
import sys, gc
extra = []
class Document(object):
    def __init__(self): self._modules = []
class FakeMod(object):
    __name__ = "junk"
def test():
    d = Document()
    mod = FakeMod()
    assert 'junk' not in sys.modules
    sys.modules['junk'] = mod
    d._modules.append(mod)
    assert 'junk' in sys.modules
    extra.append(mod)
    referrers = gc.get_referrers(mod)
    print(len(referrers))
    print(referrers)
test()
```

**Comment by xavArtley** [comment]
Python 36
https://ci.appveyor.com/project/xavArtley/test-appveyor/build/job/b0gafek8bxisp78v
Python 37
https://ci.appveyor.com/project/xavArtley/test-appveyor/build/job/bhb2eske818eof17

**Comment by xavArtley** [comment]
I succeed to launch unit tests on appveyor 
https://ci.appveyor.com/project/xavArtley/bokeh/build/1.0.44

But I had to use this command
`py.test -m unit --diff-ref HEAD`

**Comment by xavArtley** [comment]
```
{"1": ["server_loaded", "next_tick_server", "timeout_server", "periodic_server", "session_created", "next_tick_session", "timeout_session", "periodic_session", "modify", "session_destroyed", "server_unloaded"]}
{"10": ["server_loaded", "next_tick_server", "timeout_server", "periodic_server", "session_created", "next_tick_session", "timeout_session", "periodic_session", "modify", "session_destroyed", "server_unloaded"]}
{"30": ["server_loaded", "next_tick_server", "timeout_server", "periodic_server", "session_created", "next_tick_session", "timeout_session", "periodic_session", "modify", "session_destroyed", "server_unloaded"]}
{"60": ["server_loaded", "next_tick_server", "timeout_server", "periodic_server", "session_created", "next_tick_session", "timeout_session", "periodic_session", "modify", "session_destroyed", "server_unloaded"]}
{"100": ["server_loaded", "next_tick_server", "timeout_server", "periodic_server", "session_created", "next_tick_session", "timeout_session", "periodic_session", "modify", "session_destroyed", "server_unloaded"]}
{"200": ["server_loaded", "next_tick_server", "timeout_server", "periodic_server", "session_created", "next_tick_session", "timeout_session", "periodic_session", "modify", "server_unloaded"]}
{"500": ["server_loaded", "next_tick_server", "timeout_server", "periodic_server", "session_created", "next_tick_session", "timeout_session", "periodic_session", "modify", "server_unloaded"]}
{"1000": ["server_loaded", "next_tick_server", "timeout_server", "periodic_server", "session_created", "next_tick_session", "timeout_session", "periodic_session", "modify", "server_unloaded"]}
{"5000": ["server_loaded", "next_tick_server", "timeout_server", "periodic_server", "session_created", "next_tick_session", "timeout_session", "periodic_session", "modify", "server_unloaded"]}
```

results of test__lifecycle_hooks for differents check_unused_sessions_milliseconds values

**Comment by bryevdv** [comment]
@xavArtley this is all really awesome. I want to thank you again. I am handling the `get_referrers` unit test issue in https://github.com/bokeh/bokeh/pull/8222 After that is merged, you will want to merge/rebase master. 

I will start looking into how to integrate Appveyor into the main repository checks.

**Comment by bryevdv** [comment]
Regarding the lifecycle hooks issue, I am not sure offhand. If there are problems we can't figure out in a reasonable timeframe, I am happy to mark specific tests as skip on windows for now, as long as a corresponding issue is made in the tracker to note it.

**Comment by bryevdv** [comment]
Also once https://github.com/bokeh/bokeh/pull/8224 is merged the deprecation warning about `np.fromsrtring` should all go away (after a merge/rebase)

**Comment by bryevdv** [comment]
@xavArtley it loos like there is just one code linting error on the exsiting CI:

> E         ./bokeh/util/tests/test_browser.py:8:1: F811 redefinition of unused 'os' from line 1


I'm not sure what's up with the commit history.

**Comment by xavArtley** [comment]
`import os` is declared line 1 and line 8

**Comment by bryevdv** [comment]
@xavArtley did you want to try and re-base this before merging to clear up the commit history?

**Comment by xavArtley** [comment]
I'm not that good in git.
What do you mean by rebase to clean the commit history?

**Comment by bryevdv** [comment]
If you look up above it's showing lots of extra commits from master on this branch, I was suggesting running `git rebase master` followed by a `git push -f` to force-push the new version of the branch. However, I think I will just merge this as-is, as soon as it is green

**Comment by bryevdv** [comment]
You beat me to it! :D OK I will merge this later today when green, thanks @xavArtley

**Pull request merged**
