### PR TITLE
Add viridis and related color palettes

### LINKED ISSUE #4548: Add viridis and other new color maps
Color maps from BIDS: https://github.com/BIDS/colormap/blob/master/colormaps.py

### PR DESCRIPTION
**Pull request by canavandl**
- [x] issues: fixes #4548

Add viridis, plasma, magma and inferno colormaps from matplotlib.

Discussion:
* Am i correctly citing their work? I had to derive the hexcolors from their rgb values and didn't need the mpl glue code, so none of their original code (which is [here](https://github.com/BIDS/colormap/blob/master/colormaps.py)) is actually included.

### CODE REVIEW

**Comment by canavandl** [comment]
example code
```python
import numpy as np
from matplotlib.mlab import bivariate_normal

from bokeh.plotting import figure, output_file, show
from bokeh.models import Range1d, LinearColorMapper, LogColorMapper
# from bokeh.color_map import viridis

output_file('image.html')

N = 100
X, Y = np.mgrid[-3:3:complex(0, N), -2:2:complex(0, N)]

# A low hump with a spike coming out of the top right.  Needs to have
# z/colour axis on a log scale so we see both hump and spike.  linear
# scale only shows the spike.
Z1 = bivariate_normal(X, Y, 0.1, 0.2, 1.0, 1.0) +  \
    0.1 * bivariate_normal(X, Y, 1.0, 1.0, 0.0, 0.0)

image = Z1

mapper = LogColorMapper(palette="Viridis256")

p = figure(x_range=Range1d(0,1), y_range=Range1d(0,1))

p.image(image=[image],
        color_mapper=mapper,
        # palette='Spectral11',
        dh=[1.0],
        dw=[1.0],
        x=[0],
        y=[0])

show(p)
```

yields:
screen shot 2016-06-16 at 6 23 16 pm

**Comment by bryevdv** [comment]
brilliant

**Comment by canavandl** [comment]
One sec - for some reason Magma256 is returning the Viridis256 map. Let me investigate.

**Comment by canavandl** [comment]
Magma256:

screen shot 2016-06-16 at 6 39 52 pm

Plasma256:

screen shot 2016-06-16 at 6 40 31 pm

Inferno256:

screen shot 2016-06-16 at 6 42 36 pm

**Comment by bryevdv** [comment]
@canavandl I thought we had talked about including the "generator" function too? I.e. if you wanted a 64 color palette, you could call `viridis(64)` or something similar? How much effort would that be?

**Comment by canavandl** [comment]
It should be super easy - i just had to think on it for a minute.

**Pull request merged**
