### PR TITLE
document all models completely

### LINKED ISSUE #1747: Document all model attributes
@bokeh/core After #1690 it will be possible to generate extremely thorough and useful reference documentation automatically. All model classes should have docstrings and all attributes should get a `help` argument.

### PR DESCRIPTION
**Pull request by bryevdv**
issues: closes #1747

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap a few things are falling out of this PR. In order to have the possibility to document everything:
* You can't inherit from `LineProps`, etc., you have to `Include` them (see a change I made to support not adding a prefix)
* You always have to instantiate, e.g. `Int(...)` not `Int`
So, given that, I would like to ask if it would make sense to remove support for those two use-cases (inheritance and auto-instantiation)? It seems like it would simplify the complicated properties code a little, and also reduce the documentation and testing burden. Please let me know your thoughts.

**Comment by bryevdv** [comment]
Well this is a daunting slog, but I am convinced it will be well worth it:

http://bokeh.pydata.org/en/dev/docs/reference/models.html

It might be nice to put the JSON prototypes behind an accordion of some sort. @LilaHickey do you know of any that work with sphinx easily, or if anyone at CIO is using one with Sphinx or barring all of that just what a good simple accordion lib would be.

**Comment by mattpap** [comment]
> It might be nice to put the JSON prototypes behind an accordion of some sort.

Definitively, or even move to a separate page.

**Comment by mattpap** [comment]
> You can't inherit from LineProps, etc., you have to Include them (...)

This clearly simplifies documentation generation, but otherwise I'm not so sure. Direct inheritance is simpler to understand than some meta-programming magic. But, I understand what you try to achieve here.

> You always have to instantiate, e.g. Int(...) not Int

I'm pretty we still want to support things like `Either(Int, Float, help="...")`, but I have to check which code path this uses, because definitively some logic behind this can be removed.

**Comment by bryevdv** [comment]
> I'm pretty we still want to support things like Either(Int, Float, help="...")

Oh, you are completely right about this, I somehow overlooked it (staring right at me for). 

I agree that inheritance is "simpler" to understand in some sense, on the other hand, it's a *second* thing, which is a complication of its own. But, I'd be content to just remove the documentation on using via inheritance. 

> Definitively, or even move to a separate page.

My first preference would be to keep them together, just because I think that provides the most value to any would-be language binding implementor that has to look at them. But it's alot of clutter for everyone else.

**Comment by bryevdv** [comment]
@mattpap I would like to rename `bokeh,properties.Range`, it is confusing to have a model (even it is just a base) and a property with the same name. It also slightly borks the `bokeh-autoprop` directive though I am sure it could be worked around. Mostly I think there should just be no overlap. Do you have any suggested alternative names?

**Comment by bryevdv** [comment]
I think everything except `bokeh,widgets` is done, to a pretty reasonable level. @mattpap can you take a stab at writing some of  the widgets help/doc strings, keeping the style I have used for everything else?

**Comment by bryevdv** [comment]
OK I added a ``collapsible-code-block`` directive for the JSON prototypes, and it greatly improves the models ref page: http://bokeh.pydata.org/en/dev/docs/reference/models.html

Once `bokeh.widgets` is reasonably documented this can be merged. 

@bokeh/dev I would proposed that after that, no changes under `bokeh,models` ever be merged without complete and up to date documentation.

**Comment by damianavila** [comment]
>OK I added a collapsible-code-block directive for the JSON prototypes, and it greatly improves the models ref page: http://bokeh.pydata.org/en/dev/docs/reference/models.html

Nice...

>Once bokeh.widgets is reasonably documented this can be merged.

I agree... it is getting bigger and bigger...

@bokeh/dev I would proposed that after that, no changes under bokeh,models ever be merged without complete and up to date documentation.

:+1:

**Comment by mattpap** [comment]
>  @mattpap can you take a stab at writing some of the widgets help/doc strings (...)

In this PR or after merge?

**Comment by bryevdv** [comment]
@mattpap in this PR

**Comment by mattpap** [comment]
OK, I will write this later today.

**Comment by bryevdv** [comment]
@bokeh/dev OK I am pretty much done with this PR. @mattpap as soon as you merge some docs for widgets, I may edit a little just to make sure the style and tone are consistent throughout, but otherwise this PR is ready.

**Comment by bryevdv** [comment]
@mattpap any update? Would like to merge this today.

**Comment by bryevdv** [comment]
Marking ready, pending isolated docstring contributions to `bokeh.widgets`

**Comment by mattpap** [comment]
@bryevdv, done. It took me awhile to figure out what all the options actually mean.

**Comment by bryevdv** [comment]
@mattpap Awesome! I didn't know what all the options were either, that's why I asked you. :) I am going to tweak the wording to match the style that I have used throughout the rest, then merge this in a few hours. @damianavila, any last minute comments?

**Comment by damianavila** [comment]
>@damianavila, any last minute comments?

I saw the latest changes... seems good to me but still TravisCI is failing...

**Comment by aschneiderman** [comment]
@bryevdv, looks really nice!

Any way to set it up so that when there are examples it links to the source code?  E.g., bokeh.models.glyphs has an example graph and the doc page names the source that was used to generate it -- tests/glyphs/AnnularWedge.py -- but doesn't have an HTML link to the source so you could easily swipe the code.

**Pull request merged**
