### PR TITLE
Feature/multiple processes

### LINKED ISSUE #4363: Bokeh Server w/ multiple processes
Optionally run Bokeh Server with multiple process.  This is useful when scaling an application especially when there are larger computational loads

```
bokeh serve file.py --nprocs N
```

### PR DESCRIPTION
**Pull request by quasiben**
- [x] issues: fixes #4363
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by damianavila** [comment]
@quasiben I put the ready label because I think this is ready for a first review, let me know if you think it should be still labeled as WIP. Thanks!

**Comment by quasiben** [comment]
@damianavila Thanks!  I think should add a test a two

**Comment by quasiben** [comment]
I also see failures in the CI but I think they are unrelated to this PR

**Comment by canavandl** [comment]
The unit test failures are real. It looks like `test__lifecycle_hooks` inside of test_server.py hangs on the `server.io_loop.start()` call.

**Comment by canavandl** [comment]
Needs: 

```
diff --git a/bokeh/server/application_context.py b/bokeh/server/application_context.py
index 50ee49f..773da89 100644
--- a/bokeh/server/application_context.py
+++ b/bokeh/server/application_context.py
@@ -134,7 +134,7 @@ class ApplicationContext(object):
         except Exception as e:
             log.error("Error in server unloaded hook %r", e, exc_info=True)

-        self._server_context._remove_all_callbacks()
+        self.server_context._remove_all_callbacks()

     @gen.coroutine
     def create_session_if_needed(self, session_id):
```

This must be unused, because I have no idea how it worked before (I think it's a typo)
```
diff --git a/bokeh/server/tests/utils.py b/bokeh/server/tests/utils.py
index a276e13..8a8c856 100644
--- a/bokeh/server/tests/utils.py
+++ b/bokeh/server/tests/utils.py
@@ -75,4 +75,4 @@ class ManagedServerLoop(object):
         return self._server
     @property
     def io_loop(self):
-        return self.s_server.io_loop
+        return self._server.io_loop
```

I think? The other tests fail without it.
```
diff --git a/bokeh/util/tornado.py b/bokeh/util/tornado.py
index a173844..5b10ef0 100644
--- a/bokeh/util/tornado.py
+++ b/bokeh/util/tornado.py
@@ -7,6 +7,7 @@ import logging
 log = logging.getLogger(__name__)

 from tornado import gen
+from tornado.ioloop import IOLoop

 from bokeh.document import NextTickCallback, PeriodicCallback, TimeoutCallback

@@ -81,7 +82,7 @@ class _CallbackGroup(object):

     def __init__(self, io_loop=None):
         if io_loop is None:
-            raise ValueError("must provide an io loop")
+            io_loop = IOLoop.current()
         self._loop = io_loop
         # dicts from callback to remove callable. These are
         # separate only because it's allowed to add the same
```

**Comment by quasiben** [comment]
Ah -- i didn't read the CI groupings closely.  Fixing shortly

**Comment by bryevdv** [comment]
@quasiben any update?

**Comment by bryevdv** [comment]
@quasiben this PR is on a personal fork, not on the main repo branch, so I can't really take it over

**Comment by bryevdv** [comment]
superseded by #4438

**Pull request closed without merging**
