### PR TITLE
Change text_font_size prop defaults to list-style from deprecated str

### LINKED ISSUE #3094: text_font_size props in default.yaml raise deprecated warn
The text_font_size props (of TextProps) are set as a str (e.g. ``'20pt'``) and raise a deprecation warn:

```python
DeprecationWarning: Setting a fixed font size value as a string '20pt' is deprecated, 
set with value('20pt') or ['20pt'] instead
```

### PR DESCRIPTION
**Pull request by canavandl**
issues: fixes #3094 

The default text_font_size props in default.yaml were set as deprecated string types. This PR updates them to single element lists, e.g. ``['20pt']``

### CODE REVIEW

**Comment by birdsarah** [comment]
This doesn't work - the plots won't render and the BokehJS error message is: `Error: string property 'title_text_font_size' given invalid value: 20pt`

removing the *_text_font_size from `defaults.yaml` prevents the DeprecationWarning.

**Comment by birdsarah** [comment]
have tested this locally and works.

**Comment by canavandl** [comment]
I tested it locally and it works for me too.

**Comment by havocp** [comment]
Two test failures, one is the intermittent server timeout fixed by https://github.com/bokeh/bokeh/pull/3096 and the other appears to be a (hopefully transient) broken link to an external site.

**Comment by birdsarah** [comment]
this is all passing now, @havocp if it looks good to you would you like to do the honors?

**Pull request merged**
