### PR TITLE
1450 wheel zoom off by default

### PR DESCRIPTION
**Pull request by birdsarah**
Fixes: #1450 

This fixes the second part of #1450 - the wheel tool is off by default, and can be toggled on and off by user.

### CODE REVIEW

**Comment by almarklein** [comment]
LGTM, these selenium tests are pretty awesome

**Comment by guillochon** [comment]
Is there any way to turn the wheel zoom on by default? For some use cases this is preferable...

**Comment by birdsarah** [comment]
@guillochon, not at the moment - #3054 would be the right place to discuss any suggestions you have for implementing that.

**Comment by esvhd** [comment]
+1 This would be very useful to do from Python from my side too. I was just searching for ways to do that.

**Pull request merged**
