### PR TITLE
Test Bokeh with Python 3.13 rc

### PR DESCRIPTION
**Pull request by hoxbro**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [ ] issues: fixes #xxxx
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

With the release of Pandas 2.2.3 last week, installing Bokeh in a Python 3.13 environment is now possible. And with the upcoming release of Bokeh 3.6, it could be nice to check that there aren't any major problems with it.

The jupyter ecosystem is waiting on pywin32 release. Migration can be found here: https://conda-forge.org/status/migration/?name=python313

### CODE REVIEW

**Comment by hoxbro** [comment]
Looks like macOS tests fails in test_contour.py

image

https://github.com/bokeh/bokeh/actions/runs/11009565273/job/30569692094?pr=14077#step:8:355

@ianthomas23, when you have time can you take a look at it?

**Comment by hoxbro** [comment]
Also seeing `TestClientServer::test_pull_large_document` being a bit flaky on Windows:

https://github.com/bokeh/bokeh/actions/runs/11009565273/job/30570824021?pr=14077#step:8:424

**Comment by ianthomas23** [comment]
With a rebuild of contourpy on conda-forge against the latest 3.13 RC, the macOS ARM64 tests now pass.

**Comment by hoxbro** [comment]
Thank you :+1:

**Comment by hoxbro** [comment]
Other than the flaky Windows test and packages which still need support for Python 3.13 it looks like Bokeh is in a good state with respect to Python 3.13 and will mark this as ready for review.

**Review by bryevdv — APPROVED** [review]

**Comment by mattpap** [comment]
I'm going ahead to merge this to test this with 3.7.0.dev1.

**Pull request merged**
