### PR TITLE
add debug flag to enable source maps

### LINKED ISSUE #2234: Better BokehJS debug mode
Need to enable source maps for better debugging in browser.

### PR DESCRIPTION
**Pull request by bryevdv**
issues: closes #2234

### CODE REVIEW

**Comment by bryevdv** [comment]
@tswicegood @mattpap comments welcome. Just adding this works somewhat. It balloons the size of `bokeh.js` to ~6MB, and so far I have only gotten it to work in Chrome. However, it takes several seconds for Chrome to load the "debug" versions. @tswicegood is it generating debug info for all the dependencies now too? Is there way to make this lighter/more fine grained?

**Comment by tswicegood** [comment]
Yeah -- it's doing the CoffeeScript, plus mapping the inlined JS to the individual files that were loaded at various points IIRC.  One way to solve that would be to break the dependencies into a separate file, then use global state to share them.  Not ideal, but would work.

Another option is to edit the source map to remove all non-Bokeh references.  I would suggest using [exorcist][1] too if going that route just to ensure you don't mess with the compiled code.  Probably not worth the effort, but wanted to throw it out as an option.

[1]: https://github.com/thlorenz/exorcist

**Comment by tswicegood** [comment]
Actually, as I'm thinking about this it *might* be possible to build CoffeeScript entirely, add a source map to that, then use that as the entry point for Browserify.  That *should* work, though you might need to append something to the end of the `bokeh.js` file generated by the `browserify()` function.  Easy-enough to do with gulp and an extra `pipe` though.

**Comment by bryevdv** [comment]
@tswicegood that sounds great but I'm not sure where to start. Some concrete pointers, or if it is quick and easy (for you) commits on this PR, are welcome!

**Comment by bryevdv** [comment]
@tswicegood any suggestions or pointers? Would be nice to re-enable this for 0.9 but would have to implement something soon.

**Comment by damianavila** [comment]
ping @tswicegood again for suggestions...

**Comment by tswicegood** [comment]
Thanks for the ping, @damianavila -- this fell off my radar.

---

So I just nixed a really long response because I'm pretty sure I've talked myself out of most sane ways of doing this (by sane, I mean methods that don't involve writing custom source maps).  A good place to start for generating the files with *just* bokeh is [external bundles][1] section.  My original thought was to use `--exclude`, but I don't think that will work out of the box because of custom variable names.

As soon as I say that, though, there is the possibility of using an external bundle and then routing all of your packages through `bokeh/dependencies.js`.  The key is that all other parts of bokeh should do:

```coffeescript
bkDependencies = require "./dependencies"
$ = bkDependencies.$
$$ = bkDependencies.jQueryUI
# … and so on and so forth
```

If you do that combined with `--exclude dependencies` you should be able to get a bokeh.js that is *just* bokeh-generated code, then compile just the `dependencies.coffee` file which is responsible for pulling in all of the external dependencies like Backbone, jQuery, and so on, as a [standalone][2] at `bkDependencies`.  At that point, you could concat both of those files and you're set.

---

Big, huge, gigantic caveat: this is all theory.  I'd have to experiment with it a bit to figure out for sure.  Happy to, but I haven't yet and won't have the time for a few days at least.

[1]: https://github.com/substack/browserify-handbook#external-bundles
[2]: https://github.com/substack/browserify-handbook#standalone

**Comment by bryevdv** [comment]
@tswicegood if you have any time to devote to this before moving it would be extremely valuable and appreciated!

**Comment by mistakevin** [comment]
New gulp changes will generate an external source map for bokeh.min.js, which should load automatically in the browser if "Enable JavaScript source maps" option is selected (in Chrome). I don't know if this is ultimately what we want, as it will probably just point to where in bokeh.js the error is, not in separate files. If we want to shrink the size of bokeh.js, maybe we should consider creating a bower package that will ensure dependencies will be available.
note:  Cannot test locally, so going on faith that it works

**Comment by mistakevin** [comment]
Updated to include source mapping of bokeh.min.css

**Comment by mistakevin** [comment]
So to keep valuable "debug" functionality, I've added the `--debug` flag to the `gulp build/watch` commands. This is valuable because it will actually load the individual .coffeescript files into the developer tools, but is really only supposed to be used locally in development, as it explodes bokeh.js to over 6 mb. A css equivalent for bokeh.css would probably also be valuable, as it would tell us exactly what file a particular rule came from. The source maps for bokeh.min.js and bokeh.min.css are still automatically created, though we can investigate flagging those as well with a `--map-js --map-css` flags

**Comment by bryevdv** [comment]
I still think it would be ideal to have the "debug" functionality, but with the inline source maps only generated for our code. Perhaps that could be investigated in a follow-on issue, though.

**Comment by damianavila** [comment]
@mistakevin, I think this is enough for now, and we can proceed further in another PR...

Can you please add docs about using this option here: http://bokeh.pydata.org/en/latest/docs/dev_guide/building.html#building-bokehjs-with-gulp

Just explain the whole thing as you explained here... After that, I think we can merge this one...

**Comment by mistakevin** [comment]
Added documentation @damianavila

**Pull request merged**
