### PR TITLE
Upgrade timezone and remove its copy from vedor

### LINKED ISSUE #5211: Upgrade timezone dependency and remove timezone from vendor
We have both timezone in vendor and in dependencies in package.json. Additionally we use some extremely old version.

### PR DESCRIPTION
**Pull request by mattpap**
fixes #5211

### CODE REVIEW

**Comment by mattpap** [comment]
8 travis ci build restarts so far. This needs to change soon.

**Comment by bigreddot** [comment]
It has seemed to get worse in the last few days, there are some new failure modes. I agree it needs attention in the very near future.

**Comment by birdsarah** [comment]
Agreed - I added a new issue about the python unit test that's started failing: #5230

**Comment by birdsarah** [comment]
I've run this locally. Not really sure how to know it's working, but the examples that use DatetimeTickFormatter are still running fine.

**Comment by mattpap** [comment]
@birdsarah, I tested this on daylight example.

**Comment by birdsarah** [comment]
> @birdsarah, I tested this on daylight example.

Yes, that's what I did too.

**Pull request merged**
