### PR TITLE
Add styling to bokeh apps index page and add docs

### PR DESCRIPTION
**Pull request by boylea**
Solves issue #4425 

This makes the server app index presentable

Here is a screenshot of the index page for two running applications:

screen shot 2016-06-04 at 6 33 40 pm

- [ ] issues: fixes #xxxx
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by birdsarah** [comment]
LGTM - Thanks for adding this @boylea and for adding the docs.

ping @danielfrg @bryevdv  - the docs that @boylea has added, should probably have gone in as part of #4415.

**Comment by boylea** [comment]
The integration tests are failing. I'm having trouble getting them to run at all locally, but will look into it tonight

**Comment by birdsarah** [comment]
That's because you're an external contributor (so you don't have access to SauceLabs). I thought I'd fixed this problem, but apparently not.

Basically this means that the tests are passing.

**Comment by birdsarah** [comment]
@bryevdv - I'm not sure this 100% covers all the things you had in mind for #4425.

**Comment by danielfrg** [comment]
This is great. I notice that this PR removes the redirect when there is only one app running. Is this the desired behaviour? Usually I have just one app running and in that case I thought it was nice to just open the app without the need to see the index.

**Comment by bryevdv** [comment]
I would say we could at least make that configurable e.g --index-redirect  I don't have strong opinions about whether the default is true or false.

**Comment by danielfrg** [comment]
I think defaults are important here.

In my opinion the default for one app should be redirect instead of the index page. I believe this because like I said I usually have one app running, but thats me... now I am wondering if people really run more than one app when they call the command `bokeh serve ...`. If thats the most common use case then the index page as default is probably better, with the `--index-redirect` flag.

In any case this index is much better than my ugly list and the `404` error before that :)

Personally I would remove the "To disable this index page..." message from the index page, i think docs are good enough, i think it looks weird to tell you to remove the index from the index page. Not really that important.

**Comment by quasiben** [comment]
@boylea the new styling is really great!  

My $0.02: I don't mind the message on disabling the index page and I have a slight preference for the redirect.

**Comment by bryevdv** [comment]
My preference is also for a default to redirect. My rationale is this: If there is only one app, then the only possible useful action a user can take from the "list" index page is to click the one link to view the one app. But then why make them do this superfluous action at all? I can appreciate some cases might favor uniformity, but I would suggest `disable-index-redirect` to turn off a default redirect in that case.

**Comment by bryevdv** [comment]
@boylea I think the preference is to keep the redirect as a default with an option to turn it off. Is that something you have the bandwidth to work on? As an alternative, just restoring the redirect and adding an issue to add `--disable-index-redirect` later would be fine.

**Comment by boylea** [comment]
@bryevdv reverted to using redirect. Let me know if you'd rather I squish that change into the first commit to avoid the back and forth history. 

I don't have the bandwidth to do much more for the next couple days. I could get to it Thursday/Friday so it's up to you if want to wait for me to get to it or just do it yourself

**Comment by bryevdv** [comment]
@boylea thanks! I have been experimenting with squash merges, so no need to fix anything up I don't think. We are planning to freeze for `0.12` Monday. So if you have change to work on the policy flag, great! If now, we will merge this and add an issue. Thanks so much for the PR!

**Comment by boylea** [comment]
Added the option for disabling the redirect.

**Pull request merged**
