### PR TITLE
Add ipywidgets integration examples

### LINKED ISSUE #9772: IPywidgets examples
Need at least the following examples

* server example with basic sliders, etc
* server example with ipyvolume
* server example with ipyleaflet 
* notebook example with bokeh plot in ipywidgets layotut

maybe best under a `howto/ipywidgets` directory?

@mattpap for the last I am basing on my understanding that that direction is also now possible. Can you point to some example code for how to do that?

### PR DESCRIPTION
**Pull request by mattpap**
Depends on https://github.com/bokeh/ipywidgets_bokeh/pull/6.

fixes #9772

### CODE REVIEW

**Comment by mattpap** [comment]
@bryevdv, I need this merged for 2.0.2. I will add two more examples tomorrow.

**Comment by bryevdv** [comment]
Sure, I am going to try to get an RC built tonight but this can go in after that.

**Comment by mattpap** [comment]
I'm not sure what's up with examples' tests.

**Comment by mattpap** [comment]
Adding ipyvolume to dependencies breaks examples' tests. It's not even imported anywhere.

**Comment by bryevdv** [comment]
Does it cause a change in package versions that are installed?

**Comment by mattpap** [comment]
> Does it cause a change in package versions that are installed?

`bokeh              pkgs/main/linux-64::bokeh-2.0.1-py37_0`

**Comment by bryevdv** [comment]
Well, I'm OK excluding it from the examples tests for now and filing and issue to follow up

**Comment by mattpap** [comment]
Alternatively bokeh could be installed using full version predicate, which I think we should do anyway, because if it wasn't for a lucky broken test, we would have a completely broken CI at least for a little while. I'm just not sure how to get the version (use versionneer?).

**Comment by bryevdv** [comment]
@mattpap So I don't actually fully understand what is happening from your one line response. There was not context or explanation. Which is why, given the desire to release tomorrow, I suggested to punt (for now). If you'd care to actually explain what is going on and give some context perhaps I can offer some constructive help. 

I *think* you are saying that adding this dependency is also incorrectly causing an old previous release version of bokeh to be installed? It would be nice to not have to speculate and guess. The intention on CI is that the package from the Build stage is what is used for all testing, and no version is installed from anywhere else. Getting the version is a bit of chicken and egg problem at the point of downstream jobs. I think if you want that the version, then it needs to be saved in the artifacts tarball somehow along with the package

**Comment by mattpap** [comment]
bokeh is installed with:
```
conda install --yes --quiet --use-local bokeh `python scripts/deps.py run test`
```
I propose to install it with:
```
conda install --yes --quiet --use-local bokeh=$VERSION `python scripts/deps.py run test`
```
where `$VERSION` is the locally built version of bokeh. I can derive it from `conda build conda.recipe --output`, but I suppose there's a more efficient way.

**Comment by bryevdv** [comment]
>  I can derive it from conda build conda.recipe --output, but I suppose there's a more efficient way.

Right, but conda build only happens once, in the Build job, so that's why I said it would need to be communicate from the Build job.

**Pull request merged**
