### PR TITLE
Add link to Bokeh tutorial notebooks

### PR DESCRIPTION
**Pull request by orodbhen**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: refs #7831

### CODE REVIEW

**Comment by bryevdv** [comment]
HI @orodbhen thanks for the PR. I think adding an entire section header just of a single link is a little overkill. I'd suggest we could either find a place in the existing structure to add a complete sentence that includes the link to the tutorial, or otherwise to expand the new section somewhat, to contain at least a full paragraph. If we did that we could mention/link to the source material in the `bokeh-notebook` repo and note that users can clone repo to run them locally, or otherwise that it is possible to try them out online in live notebooks on binder (with a link to the tutorial there)

**Comment by bryevdv** [comment]
@orodbhen Do you expect to be able to update this PR? If not that is fine but then I would like to close it.

**Comment by orodbhen** [comment]
I think the latter option was what I had in mind. A section where links to more examples could be added later. I'll work on adding your suggestions to the PR.

**Comment by orodbhen** [comment]
@bryevdv I've expanded the section a bit. Does that look like what you had in mind?

**Comment by mattpap** [comment]
@orodbhen, you will need remove trailing whitespace from the modified files. You can run `py.test -m quality` to verify everything is OK.

**Comment by bryevdv** [comment]
@orodbhen the changes look great, in the interest of getting this merged soon today, I went ahead and fixed up the whitespace issue and also made a tiny edit to one sentence to emphasize that the binder notebooks are "live"

**Comment by bryevdv** [comment]
Thanks @orodbhen !

**Pull request merged**
