### PR TITLE
Bryanv/cleanups

### PR DESCRIPTION
**Pull request by bryevdv**
Remove several deprecations and dead code, and add one for `responsive`. Work is outlined in individual commits. 

The only thing possibly of note:

> Glyphs methods now only accept either all sequence literals, OR all column names

i.e. mixing will trigger an error

### CODE REVIEW

**Comment by bryevdv** [comment]
cc @zjffdu This PR removes all *built-in* remains of zeppelin support, so you will want to make sure your notebook hook is providing all the necessary tasks to load and show

**Comment by bryevdv** [comment]
@canavandl please review if you have time but no worries if you do not.

**Comment by bryevdv** [comment]
I don't think there should be anything controversial here, I am going to go ahead and merge.

**Comment by zjffdu** [comment]
@bryevdv I just found that `bokeh.util.notebook._load_notebook_html` is deleted in some PR, could we expose it as public function so that zeppelin hook (bkzep) can reuse the this function to load bokeh js ?

**Comment by bryevdv** [comment]
@zjffdu Bokeh itself has no use for that function anymore so I'd suggest a better option is to copy it the old version into your project. Bokeh is a very large library, as we approach 1.0 I am trying to aggressively pare down any cruft, duplicate, or unused code to make ongoing maintenance more approachable.

**Comment by zjffdu** [comment]
Make sense, will do that.

**Comment by zjffdu** [comment]
I updated `bkzep` and bokeh still works in zeppelin. Thanks @bryevdv

**Comment by bryevdv** [comment]
Brilliant, I am glad to hear it! I think this separation of concerns will keep things more easily maintainable for everyone

**Pull request merged**
