### PR TITLE
updated links in app readme

### LINKED ISSUE #13736: App README links are all old / bad
Here:

https://github.com/bokeh/bokeh/tree/branch-3.4/examples/server/app

E.g. the first thumbnail points to https://github.com/bokeh/bokeh/tree/master/examples/app/clustering which no longer exists. 

Links need to be updated for examples re-org, and should also point to HEAD branch.

### PR DESCRIPTION
**Pull request by Mr-Spikes**
Update links to new folder structure, each link points to HEAD.
First time contribution anywhere on github! Let me know if you see any needed changes.
- [ ] issues: fixes #13736

### CODE REVIEW

**Comment by bryevdv** [comment]
Hi @Mr-Spikes thanks for the PR! I actually learned just now that there is a better URL scheme besides HEAD. The HEAD ref always resolves to a random commit but you can use `/blob/-/` to resolve to the current default branch, e.g.
```
https://github.com/bokeh/bokeh/blob/-/examples/server/app/fourier_animated.py
```
redirects to 
```
https://github.com/bokeh/bokeh/blob/branch-3.4/examples/server/app/fourier_animated.py
```
I think this is preferable. What do you think? Do you mind updating the URLs one more time to this alternative scheme?

**Comment by Mr-Spikes** [comment]
Sure! I updated blob/HEAD to blob/-. I tried changing tree/HEAD to tree/-, but that didn't work so I left it as is.

**Comment by bryevdv** [comment]
> I tried changing tree/HEAD to tree/-, but that didn't work so I left it as is.

I think they can all just be `blob/-`, includijng the directories e.g this one that's currently `tree/HEAD`, if it is changed to:
```
https://github.com/bokeh/bokeh/blob/-/examples/server/app/clustering
```
redirects to
```
https://github.com/bokeh/bokeh/tree/branch-3.4/examples/server/app/clustering
```

**Comment by Mr-Spikes** [comment]
I see. Changed those too

**Comment by bryevdv** [comment]
Thanks for the fix @Mr-Spikes !

**Pull request merged**
