### PR TITLE
Don't use spaces in JSON separators to reduce data size

### PR DESCRIPTION
**Pull request by mattpap**
This reduces size of choropleth.html by ~10% (1MB).

### CODE REVIEW

**Comment by bryevdv** [comment]
Hooray for easy wins

**Comment by bryevdv** [comment]
Looks like the "generate defaults" test is also passing in `separators`, resulting in a dupe keyword:

https://travis-ci.org/bokeh/bokeh/jobs/105940760#L1187

**Comment by mattpap** [comment]
> Hooray for easy wins

I also did a preliminary analysis of binary JSON protocols and it doesn't look promising in general and looks completely useless in static HTML case. But that's preliminary work, I will followup with this later.

**Comment by bryevdv** [comment]
@mattpap there is no need to investigate binary protocols for the web socket. I have demonstrated that it is possible to send numpy `.asarray` bytes output directly into JS typed array buffer views from web socket messages. No encoding whatsoever, so that is the way to go for sure. For standalone docs, maybe just base64. The benefit there is not so much size but real NaN/Inf

**Comment by bryevdv** [comment]
LGTM

**Pull request merged**
