### PR TITLE
Add a heuristic for determining when bokeh finished rendering

### LINKED ISSUE #4111: check JS logs in tests
Suggested in #4109 to check JS logs for output like `/error/i`, `undefined is not a function`, `TypeError`, etc.

### LINKED ISSUE #5232: intermittently failing examples tests - ggplot_density and graphs
The examples tests are occasionally failing. ggplot_density and graphs are standing out for me as ones that fail. Haven't been tracking - just noticing today.

### LINKED ISSUE #5254: Examples involving transforms using Math.random() fail image diff
It's not possible to seed `Math.random()` due to security concerns. I hoped for phantomjs to allow to configure seed (e.g. as a command line option), but didn't have any luck with that so far. We could use a custom number generator, e.g. https://www.npmjs.com/package/random-seed, instead. That's a few extra kB and we will have full control over random number generation and reliable tests.

### LINKED ISSUE #5712: Make sure examples' tests wait until bokeh finished rendering
I was pretty sure there was already an issue for this.

### PR DESCRIPTION
**Pull request by mattpap**
To test things locally, it recommend the following command line:
```
py.test -v -s --tb=line --diff-ref master --incremental test_examples.py
```
Details:
- `-v` is necessary to get inline logs
- `-s` is necessary to actually show inline logs
- `--tb=line` reduces clutter in case of failures
- `--diff-ref master` specifies the revision to compare to
- `--incremental` writes report.html after each example

You can use `-m examples` instead of `test_examples.py`, but the former is slower and can show unrelated garbage in the output given `-s` flag.

To filter examples use `-k` option, e.g. `-k 'models and not server'` will select models' file examples.

TODO:

- [ ] ~~improve heuristic for non-plot examples (e.g. `css_classes`, `slider_callback_policy`).~~

fixes #5712 
fixes #5232 
fixes #5254 
fixes #4111
fixes partially #4285

### CODE REVIEW

**Comment by mattpap** [comment]
> `requests.exceptions.TooManyRedirects: Exceeded 30 redirects.`

That's from conda-build.

**Comment by bryevdv** [comment]
@mattpap is this repeatable on re-start?

@ilanschnell any ideas? here is the stack trace
```
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 151, in main
    args_func(args, p)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 412, in args_func
    args.func(args, p)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 355, in execute
    debug=args.debug)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 534, in build
    create_env(config.build_prefix, specs, debug=debug)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 390, in create_env
    index = get_build_index(clear_cache=True)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 344, in get_build_index
    prepend=not override_channels)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/api.py", line 25, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 290, in fetch_index
    for url in urls]
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 68, in func
    res = f(*args, **kwargs)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 112, in fetch_repodata
    resp = session.get(url + filename, headers=headers, proxies=session.proxies)
  File "/home/travis/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/home/travis/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/travis/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 113, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

**Comment by mattpap** [comment]
> is this repeatable on re-start?

@bryevdv, yes, I restarted several times already with the same result.

**Comment by msarahan** [comment]
https://github.com/conda/conda/issues/4282

**Comment by bryevdv** [comment]
OK, restarting

**Comment by bryevdv** [comment]
OK, tests are running now but there are real failures

**Comment by mattpap** [comment]
`bokeh info` and bokehjs report different Python versions:
```
$ python -m bokeh info
Python version      :  2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
IPython version     :  5.1.0
Bokeh version       :  0.12.5dev11-72-g768e14f
BokehJS static path :  /home/travis/build/bokeh/bokeh/bokeh/server/static
node.js version     :  v6.6.0
npm version         :  3.10.3
```
and
```
[JS] [bokeh] Library versions: JS (0.12.5dev11)  /  Python (0.12.5dev11+72.g768e14f)
```
Notice the `+` instead of `-`. WTF? I can't reproduce this locally. I can change the code in `bokehjs/src/coffee/document.coffee` to check for `+` as well, but that's not a fix.

**Comment by bryevdv** [comment]
need a `MIGRATION` note about renamed examples

**Comment by bryevdv** [comment]
Also, as part of this PR, please (for my sake) have the results template list which column is "current" and which is "reference". I believe it's left column is "current image" and right column is "reference image" but I am always doubtful whether I am remembering correctly or not.

**Comment by mattpap** [comment]
Can someone tell me what's wrong with https://travis-ci.org/bokeh/bokeh/jobs/202203500? Don't look at the report (spoiler alert: not that helpful unless you look closer), just tell me what the log says.

**Comment by mattpap** [comment]
Interesting to note that tests take on travis ci exactly the same amount of time as locally (about 10 minutes).

**Comment by mattpap** [comment]
@bryevdv, this is ready. Further improvements (especially improved heuristic and new examples' report template) will come in smaller batches.

**Comment by bryevdv** [comment]
Future reference: I shouldn't have merged this without the migration added note added in the PR

**Comment by mattpap** [comment]
@bryevdv, I will be moving models' file example in another PR, so migration notes can be added then.

**Comment by mattpap** [comment]
btw. @bryevdv, did you have a chance to look the at first comment (regarding `+` in versions)? I hacked around this, but we want to do something more about this. I'm not sure if this is an actual issue or not.

**Comment by bryevdv** [comment]
I did, it seemed fine for now

**Pull request merged**
