### PR TITLE
Improve devtools test framework

### PR DESCRIPTION
**Pull request by mattpap**
This PR addresses various issues with bokehjs' testing:

- [x] add support for source maps
- [x] fix paths in source maps
- [x] use a progress bar to compact test output
- [x] collect failed tests at the and and use more readable format
- [x] add support for resources server (static files and test sites)
- [x] automatically start headless chrome and resources server
- [x] allow to run all dependencies of a task before failing it

Sample output from unit (or integration) test run:
```
[00:47:05] Starting 'test:unit'...
████████████████████████████████████████ 100% | 1465 of 1465 | 3 failures | 10 skipped

✗ Document
 └── should be constructable
AssertionError: expected 0 to equal 1
    at http://localhost:5777/home/mateusz/repo/bokeh3/bokehjs/build/test/unit/document/document.js:112:1
    at _run_test (http://localhost:5777/home/mateusz/repo/bokeh3/bokehjs/build/test/framework.js:94:1)
    at Object.run_test (http://localhost:5777/home/mateusz/repo/bokeh3/bokehjs/build/test/framework.js:73:1)

✗ Document
 └── has working add_root
AssertionError: expected 1 to equal 2
    at http://localhost:5777/home/mateusz/repo/bokeh3/bokehjs/build/test/unit/document/document.js:118:1
    at _run_test (http://localhost:5777/home/mateusz/repo/bokeh3/bokehjs/build/test/framework.js:94:1)
    at Object.run_test (http://localhost:5777/home/mateusz/repo/bokeh3/bokehjs/build/test/framework.js:73:1)

✗ ColorBar module
 └┬─ ColorBar
  └┬─ ColorBar._tick_coordinate_scale method
   └── LinearColorMapper should yield LinearScale instance with correct state
AssertionError: expected [ 10, 0 ] to deeply equal [ 10, 1 ]
    at http://localhost:5777/home/mateusz/repo/bokeh3/bokehjs/build/test/unit/models/annotations/color_bar.js:80:1
    at _run_test (http://localhost:5777/home/mateusz/repo/bokeh3/bokehjs/build/test/framework.js:94:1)
    at Object.run_test (http://localhost:5777/home/mateusz/repo/bokeh3/bokehjs/build/test/framework.js:73:1)
[00:47:13] Failed 'test:unit' after 8.34 s
```

addresses #9420

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap I was about to merge this but then checked the CI run. Am I missing something? It looks like the filesize test run then nothing else:

https://github.com/bokeh/bokeh/pull/9588/checks?check_run_id=399074085

**Comment by bryevdv** [comment]
See progress now, thank you!

**Comment by bryevdv** [comment]
@mattpap I am no longer able to run tests locally:
```
[14:57:42] Finished 'test:size' after 515 ms
[14:57:42] Starting 'test:start:headless'...
[14:57:42] Failed 'test:start:headless' after 4 ms
[14:57:42] Starting 'test:start:server'...
listening on 127.0.0.1:5777
[14:57:44] Finished 'test:start:server' after 1.67 s
[14:57:44] Starting 'defaults:generate'...
[14:57:44] generate_defaults.py: Wrote models_defaults.json with 179 model classes
[14:57:44] generate_defaults.py: Wrote widgets_defaults.json with 23 model classes
[14:57:45] Finished 'defaults:generate' after 758 ms
[14:57:45] Starting 'test:compile'...
[14:57:48] Finished 'test:compile' after 3.93 s
[14:57:48] Starting 'test:unit:bundle'...
[14:57:49] Finished 'test:unit:bundle' after 577 ms
[14:57:49] Starting 'test:integration:bundle'...
[14:57:49] Finished 'test:integration:bundle' after 33 ms
[14:57:49] failed: task 'test' failed
[14:57:49]     at _run (/Users/bryan/work/bokeh/bokehjs/make/task.ts:134:26)
[14:57:49]     at process._tickCallback (internal/process/next_tick.js:68:7)
```
I've tried starting Chrome headless manually, as well as leaving it not running ahead of time

**Comment by mattpap** [comment]
How do you start chrome manually, via `chromium-browser`, `chrome`? Also is the executable on the PATH?. Currently the executable is hard-coded to `chromium-browser`.

**Comment by bryevdv** [comment]
I have an alias for 
```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222 --headless
```
I'll lookin in to installing a `chromium-bowser` on the path but this should go in the dev docs too

**Comment by mattpap** [comment]
> `Google\ Chrome`

Nice, another variation. I will add an equivalent of `which`, to detect the right name.

**Pull request merged**
