### PR TITLE
Add pyflakes checking to Travis CI

### LINKED ISSUE #2078: Use PyFlakes
In  #1980 we discussed to use pyflakes to improve code quality. At first we decided to use vanilla pyflakes, but we came back to using flake8 because that allows much more configuration. This issue is to keep track of progress, which will likely be done in a few subsequent PR's:

* [x] Make all subpackages pyflakes compliant (done: server, charts, cli, ...)
* [x] Make bokeh root package pyflakes compliant
* [ ] Run pyflakes during Travis CI

### PR DESCRIPTION
**Pull request by almarklein**
issues: closes #2078

This adds pyflakes (and minor style) checking to Travis CI. This will prevent introducing new pyflakes violations and potential bugs.

WIP: need to verify that it actually works.

### CODE REVIEW

**Comment by almarklein** [comment]
This is working, waiting for #2142 to get merged so that we can make Travis pass.

**Comment by bryevdv** [comment]
@almarklein #2142 is merged

**Comment by almarklein** [comment]
@bryevdv thanks! I rebased, fixed the remaining flake errors and Travis is happy!

**Comment by bryevdv** [comment]
@bokeh/core I intend to merge this later today unless there is comment or objection.

**Pull request merged**
