### PR TITLE
Improve palettes docs and docs automation

### PR DESCRIPTION
**Pull request by bryevdv**
* re-purpose `bokeh-palette` to display single palettes inline
* add `bokeh-palette` group to display groups of palette matrices
* add `:noindex:` option to `bokeh-enum`
* add complete docstrings to `bokeh.palettes`
* streamline property creation in `bokeh.palettes`

Regarding the last, it adds a little magic, in this instance I'd very much like the palettes to be expressed as near as possible to "just the data" without alot of dressing around them.

### CODE REVIEW

**Comment by bryevdv** [comment]
adding `MIGRATION` for change in `bokeh-palette` meaning

**Comment by bryevdv** [comment]
temporary test deploy of new docs:

http://bokeh.pydata.org/en/test/docs/reference/palettes.html
http://bokeh.pydata.org/en/test/docs/reference/sphinxext.html

**Comment by bryevdv** [comment]
ping @mattpap

**Comment by mattpap** [comment]
> http://bokeh.pydata.org/en/test/docs/reference/palettes.html

This looks very nice.

**Comment by bryevdv** [comment]
Thanks! I'm going to merge this in an hour or so, unless you'd like more time to review it.

**Pull request merged**
