### PR TITLE
Support "pip install ."

### LINKED ISSUE #11658: Support "pip install" from sdist
This is needed for conda-forge to be able to use their preferred standard build process. 

As far as I know this should only be a matter of making `setup.py bdist_wheel` (from an sdist) work the same way as `setup.py install` (from an sdist) already works, i.e. it should use the existing, bundled, built BokehJS inside the sdist without needing any additional command line args. 

ref: https://github.com/conda-forge/bokeh-feedstock/pull/69

### PR DESCRIPTION
**Pull request by bryevdv**
This PR fixes argument checking to allow `setup.py bdist_wheel` to proceed FROM an sdist, using the pre-built BokehJS inside the sdist, without any additional command line arguments. As a consequence, `pip install .` now also works from inside an sdist. 

Steps have been added to confirm that all of the following function:

* `python setup.py sdist --install-js`  (what WE used to build official sdist)
* `python setup.py bdist_wheel --install-js` (what WE use  to build official wheel)
* `pip install .` from exploded sdist (what OTHERS use to re-package)

Additionally some of the extremely gorpy logic in the `setup.py` and `_setup_support.py` was streamlined and simplified. 

- [x] issues: fixes #11658
- [x] tests added / passed

cc @ocefpaf

```
~/work/bokeh/dist bryanv/11658_sdist_pip_install*
piptest ❯ cd bokeh-2.4.0+13.gf4a36c48c.dirty

~/work/bokeh/dist/bokeh-2.4.0+13.gf4a36c48c.dirty bryanv/11658_sdist_pip_install*
piptest ❯ pip install .
Processing /Users/bryan/work/bokeh/dist/bokeh-2.4.0+13.gf4a36c48c.dirty
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: tornado>=5.1 in /Users/bryan/anaconda/envs/piptest/lib/python3.9/site-packages (from bokeh==2.4.0+13.gf4a36c48c.dirty) (6.1)
Requirement already satisfied: PyYAML>=3.10 in /Users/bryan/anaconda/envs/piptest/lib/python3.9/site-packages (from bokeh==2.4.0+13.gf4a36c48c.dirty) (5.4.1)
Requirement already satisfied: pillow>=7.1.0 in /Users/bryan/anaconda/envs/piptest/lib/python3.9/site-packages (from bokeh==2.4.0+13.gf4a36c48c.dirty) (8.3.2)
Requirement already satisfied: Jinja2>=2.9 in /Users/bryan/anaconda/envs/piptest/lib/python3.9/site-packages (from bokeh==2.4.0+13.gf4a36c48c.dirty) (3.0.1)
Requirement already satisfied: packaging>=16.8 in /Users/bryan/anaconda/envs/piptest/lib/python3.9/site-packages (from bokeh==2.4.0+13.gf4a36c48c.dirty) (21.0)
Requirement already satisfied: numpy>=1.11.3 in /Users/bryan/anaconda/envs/piptest/lib/python3.9/site-packages (from bokeh==2.4.0+13.gf4a36c48c.dirty) (1.21.2)
Requirement already satisfied: typing-extensions>=3.10.0 in /Users/bryan/anaconda/envs/piptest/lib/python3.9/site-packages (from bokeh==2.4.0+13.gf4a36c48c.dirty) (3.10.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/bryan/anaconda/envs/piptest/lib/python3.9/site-packages (from Jinja2>=2.9->bokeh==2.4.0+13.gf4a36c48c.dirty) (2.0.1)
Requirement already satisfied: pyparsing>=2.0.2 in /Users/bryan/anaconda/envs/piptest/lib/python3.9/site-packages (from packaging>=16.8->bokeh==2.4.0+13.gf4a36c48c.dirty) (2.4.7)
Building wheels for collected packages: bokeh
  Building wheel for bokeh (PEP 517) ... done
  Created wheel for bokeh: filename=bokeh-2.4.0+13.gf4a36c48c.dirty-py3-none-any.whl size=18435401 sha256=244da27e8e3342611aad8ee514e1c5011788466851e09d78d401a0dfdebc421e
  Stored in directory: /Users/bryan/Library/Caches/pip/wheels/bb/99/dd/a169981d055fed11ef0ba4e587ba8a419c3e3e905e3754370d
Successfully built bokeh
Installing collected packages: bokeh
Successfully installed bokeh-2.4.0+13.gf4a36c48c.dirty

~/work/bokeh/dist/bokeh-2.4.0+13.gf4a36c48c.dirty bryanv/11658_sdist_pip_install* 15s
piptest ❯ bokeh info
Python version      :  3.9.7 (default, Sep 16 2021, 08:50:36)
IPython version     :  (not installed)
Tornado version     :  6.1
Bokeh version       :  2.4.0+13.gf4a36c48c.dirty
BokehJS static path :  /Users/bryan/anaconda/envs/piptest/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
```

### CODE REVIEW

**Comment by bryevdv** [comment]
cc @tcmetzger just as FYI in case you think `pip install .` from an sdist is worth mentioning some where explicitly.  Note that `pip install .` does not work from a bare source checkout since one of `--build-js` or `--intall-js` needs to be supplied.

**Comment by tcmetzger** [comment]
@bryevdv I don't know enough about the benefits of `pip install .` vs the usual `python setup.py` (and its options), TBH. Are there use cases/users that you think will benefit from knowing about this option?

We could add a section about using a sdist Bokeh to https://docs.bokeh.org/en/latest/docs/first_steps/installation.html, or add some information to https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html, if necessary.

**Comment by ianthomas23** [comment]
@tcmetzger There are some fundamental problems with the `python setup.py` approach which are nicely summarised in the Rationale section of https://www.python.org/dev/peps/pep-0518. There is momentum in the direction of replacing use of `python setup.py install` with `pip install .` for source/developer builds. Pure Python projects no longer need a `setup.py` at all, as its contents can be expressed in a `setup.cfg` and `pyproject.toml` instead.

Established Python projects are understandably reluctant to switch as their existing `python setup.py` approach works well. But I suspect that they will all switch eventually, ideally before the tooling breaks their builds which is most likely to happen at already stressful release times. So this change should maybe be thought of as a first step along that road rather than as an exception for building via `sdist`.

**Comment by bryevdv** [comment]
I'm not reluctant to switch because it works so well, but because Bokeh requires an entire separate toolchain for building BokehJS to be installed in working. It would be trivial to make `pip install .` just "work" even from a source checkout, all we have to do is make `--build-js` be the default. But it will fail if all the BokehJS toolchain is not installed.

**Comment by tcmetzger** [comment]
@ianthomas23 @bryevdv Thank you both for your explanations! As I understand the current situation, we seem to be OK with the docs as they are, but as things progress, that might change. Using `pip install .` with a default of `--build-js` (and a clear error message) sounds like a good step forward to me, but this all sounds like something to talk about in a GitHub Discussion: https://github.com/bokeh/bokeh/discussions/11676

**Pull request merged**
