### PR TITLE
11726 update links surface3d example

### LINKED ISSUE #11726: [BUG] Update links in example app surface3d to point to new location on visjs.org
#### Description of expected behavior and the observed behavior

The example app for surface3d in the current Bokeh codebase includes links to a non-existent examples page on VisJS.org in both python code and the index.html page.

Outdated link in repository:   https://visjs.org/graph3d_examples.html

Current link at VisJS.org:   https://visjs.github.io/vis-graph3d/examples/

PR to follow for three files under example/apps/surface3d to update the link.

### PR DESCRIPTION
**Pull request by roadswitcher**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [ ] issues: fixes #11726 
- [ ] tests added / passed   N/A? 
- [ ] release document entry (if new feature or API change)     N/A

### CODE REVIEW

**Comment by roadswitcher** [comment]
I found this while trying to use Bokeh today at work and tried to follow the link to the VisJS page.  Figured I may as well attempt to update it.

**Comment by bryevdv** [comment]
@roadswitcher I just noticed this PR is against `main` instead of the current default branch `branch-3.0`. I switched the target branch above but it's picking up some extra commits. Can you rebase the PR branch against latest `branch-3.0` and force-push?

**Comment by bryevdv** [comment]
@roadswitcher merging is still picking up the extra commits. If you are not familiar with rebasing I can provide more explicit guidance, but if it is simpler, it's also OK to just open a brand new PR. The steps locally would be something like:
```
git checkout branch-3.0
git pull upstream branch-3.0
git checkout -b 11726_update_broken links
```

That should get you a new feature branch that is up to date with the lastest `branch-3.0` Then you can make and commit changes, push, and open a new PR.

**Comment by bryevdv** [comment]
I did just realize I assumed an  "upstream" configured, in case you need a reference for that, GH has good docs:

https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-for-a-fork

**Comment by roadswitcher** [comment]
Thanks for that documentation link, I definitely need to understand more of
the finer points of Git usage.

**Pull request closed without merging**
