### PR TITLE
remove dependancy for un-needed pytz and  Websocket

### PR DESCRIPTION
**Pull request by stonebig**
https://github.com/bokeh/bokeh/issues/2530

### CODE REVIEW

**Comment by bryevdv** [comment]
I don't actually think we are using `pytz` for anything. I couldn't find an import of it anywhere. @damianavila  @mattpap ?

**Comment by stonebig** [comment]
curious: build success for 3.4 only ??

**Comment by mattpap** [comment]
It looks like we don't need `pytz`. I'm pretty sure someone just copied `pip list` or `conda list` output to `setup.py`, without filtering out transitive dependencies. On a side note, do we have to maintain two (or more) lists of dependencies?

**Comment by mattpap** [comment]
CI failures seem unrelated, but need investigation: `ImportError: No module named 'dask'`.

**Comment by ericdill** [comment]
Doesn't seem like dask is included with the conda recipe for blaze for python 3.3

```
$ conda create -n blaze python=3.3
$ source activate blaze
(blaze) $ conda install -c blaze blaze
Fetching package metadata: ..........
Solving package specifications: .............................
Package plan for installation in environment /home/edill/miniconda/envs/blaze:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cytoolz-0.7.3              |           py33_0         776 KB
    decorator-3.4.2            |           py33_0           5 KB
    enum34-1.0.4               |           py33_0          50 KB
    itsdangerous-0.24          |           py33_0          17 KB
    llvmlite-0.6.0             |           py33_0         8.0 MB
    markupsafe-0.23            |           py33_0          31 KB
    multipledispatch-0.4.7     |           py33_0          12 KB
    networkx-1.9.1             |           py33_0         994 KB
    numpy-1.9.2                |           py33_0         7.5 MB
    bcolz-0.9.0                |       np19py33_0        1017 KB
    numba-0.20.0               |       np19py33_0         1.3 MB
    numexpr-2.4.3              |       np19py33_0         332 KB
    psutil-2.2.1               |           py33_0         100 KB
    pymongo-2.8                |           py33_0         323 KB
    pytz-2015.4                |           py33_0         176 KB
    requests-2.7.0             |           py33_0         587 KB
    six-1.9.0                  |           py33_0          17 KB
    sqlalchemy-1.0.6           |           py33_0         1.4 MB
    toolz-0.7.2                |           py33_0          50 KB
    werkzeug-0.10.4            |           py33_0         417 KB
    h5py-2.5.0                 |       np19py33_3         2.4 MB
    jinja2-2.7.3               |           py33_1         367 KB
    pytables-3.2.0             |       np19py33_0         3.4 MB
    python-dateutil-2.4.2      |           py33_0         220 KB
    datashape-0.4.6            |           py33_0         100 KB
    flask-0.10.1               |           py33_1         138 KB
    pandas-0.16.2              |       np19py33_0        10.9 MB
    odo-0.3.3                  |           py33_0         162 KB
    blaze-core-0.7.3           |py33_241_g457174d         331 KB
    blaze-0.8.0                | py33_11_gaa969bd           2 KB
    ------------------------------------------------------------
                                           Total:        41.0 MB

The following NEW packages will be INSTALLED:

    bcolz:            0.9.0-np19py33_0       
    blaze:            0.8.0-py33_11_gaa969bd 
    blaze-core:       0.7.3-py33_241_g457174d
    cytoolz:          0.7.3-py33_0           
    datashape:        0.4.6-py33_0           
    decorator:        3.4.2-py33_0           
    enum34:           1.0.4-py33_0           
    flask:            0.10.1-py33_1          
    h5py:             2.5.0-np19py33_3       
    hdf5:             1.8.15.1-1             
    itsdangerous:     0.24-py33_0            
    jinja2:           2.7.3-py33_1           
    llvmlite:         0.6.0-py33_0           
    markupsafe:       0.23-py33_0            
    multipledispatch: 0.4.7-py33_0           
    networkx:         1.9.1-py33_0           
    numba:            0.20.0-np19py33_0      
    numexpr:          2.4.3-np19py33_0       
    numpy:            1.9.2-py33_0           
    odo:              0.3.3-py33_0           
    pandas:           0.16.2-np19py33_0      
    psutil:           2.2.1-py33_0           
    pymongo:          2.8-py33_0             
    pytables:         3.2.0-np19py33_0       
    python-dateutil:  2.4.2-py33_0           
    pytz:             2015.4-py33_0          
    requests:         2.7.0-py33_0           
    six:              1.9.0-py33_0           
    sqlalchemy:       1.0.6-py33_0           
    toolz:            0.7.2-py33_0           
    werkzeug:         0.10.4-py33_0          

Proceed ([y]/n)? 
```

Yeah, it would seem that dask isn't included in the yaml file for blaze for python 3.3.
Here is the yaml file that is in `linux-64/blaze-0.8.0-py33_11_gaa969bd.tar.bz2` at https://binstar.org/blaze/blaze/files

```
package:
  name: blaze
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')}}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

source:
  git_url: ../

requirements:
  run:
    - python
    - numpy >=1.7
    - blaze-core
    - h5py
    - cytoolz
    - pytables >=3.0.0
    - pymongo >=2.8
    - numba
    - bcolz
    - unittest2 [py26]

test:
  requires:
    - pytest >=2.7.0
    - dask
    - dynd-python
    - pytables

  commands:
    - py.test -vx --doctest-modules --doctest-ignore-import-errors --pyargs blaze -rsxX

about:
  home: http://blaze.pydata.org
  license: BSD
```

**Comment by ericdill** [comment]
It appears to be the same issue on python 2.7

**Comment by bryevdv** [comment]
there's an issue with the blaze build on the blaze channel. Will have to investigate. I think we can just remove pay altogether, tho.

**Comment by ericdill** [comment]
So apparently the 3.4 build doesn't have dask either. Sorry for spamming this thread with nonsense...

**Comment by damianavila** [comment]
There was a problem in the blaze build... that was solved and I retrigger out builds... altought I agree on removing pytz too...
Also, eventually we need to find a way to just have one place to list the dependencies...

**Comment by stonebig** [comment]
Do you rely on Dask or on Blaze ? current Bokeh seems ok without blaze

**Comment by damianavila** [comment]
>Do you rely on Dask or on Blaze ? current Bokeh seems ok with Dask and without Blaze, on Windows (and supports not having reddis nor mongo).

Our testing machinery (because on some specific examples) rely on those... but for a simple installation, it does not matter at all...

Can you update the PR to remove the pytz dependency?

**Comment by stonebig** [comment]
immediately

**Comment by stonebig** [comment]
also i have a curious dependancy on "websocket" showing up when trying Cgohlke wheel for python2.7. Do you confirm you need it ? (it's unclear to me, it's not required for Python 3.4)

**Comment by damianavila** [comment]
I think `websocket` was used by gevent and we no longer use gevent... so we should remove it, I think... @bryevdv do you remember if it is needed for something else? I don't think so...
We also have a test dependency called `websocket-client`, but that is only needed for tests...

**Comment by bryevdv** [comment]
We do this:
```
from tornado import websocket, ioloop
```
I don't know if whether `tornado` requires `websocket` for that import to work, or not.

**Comment by damianavila** [comment]
I think it belong to `tornado` itself: http://tornado.readthedocs.org/en/latest/websocket.html

**Comment by stonebig** [comment]
on windows, I have no package "websocket" but Tornado/Ipython obviously works

**Comment by bryevdv** [comment]
OK let's remove it.

**Comment by damianavila** [comment]
>OK let's remove it.

@stonebig can you make the honors? :wink:

**Comment by stonebig** [comment]
no problem.

**Comment by damianavila** [comment]
LGTM, merging now...

**Comment by stonebig** [comment]
thanks

**Pull request merged**
