### PR TITLE
Fix CSV Reading of Samples for Py 3

### PR DESCRIPTION
**Pull request by crwilcox**
Fixes Issue #5029 where downloading sample US_Counties data on Ubuntu 16 with an ansi preferred local encountered issues decoding the csv encoded as utf-8.

Replaces Rejected/Abandoned PR #5030

### CODE REVIEW

**Comment by crwilcox** [comment]
This should fix the issue in the old PR with flake8.

That being said, it seems flake8 may have some issue with Windows line endings/files. I had done the original edits on my windows pc. I did the second set on a mac. I added a newline as specified and ended up with two. I actually ended up undoing the change I made, to get back to one line ending. 

Seems this Travis run will pass though so at least it is fixed.

**Comment by bryevdv** [comment]
Thanks for the PR @crwilcox ! have you had a chance to test this with both python 2 and python 3? It would be great to see console output from both python 2 and python 3, importing one of the sample data sets affected by this change, and looking at the first few rows.

**Comment by crwilcox** [comment]
@bryevdv. this was tested back when I wrote it about a month ago at this point. If you need I can get you the console output of each though.

**Comment by bryevdv** [comment]
@crwilcox I looked in the other PR but did not see any captured output. It would be good to document that things are working as expected in both py2 and py3 here.

**Comment by crwilcox** [comment]
Here is output running on installed python 3.5 and the system python of 2.7.10 on a macbook. Not sure if the output is going to give much clarity though. If there are particular things you wish to see let me know and I can retrieve them.

## Python 3.5 on Mac OSX
```
Jonagold:bokeh crwilcox$ python3
Python 3.5.0 (v3.5.0:374f501f4567, Sep 12 2015, 11:00:19) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from bokeh.sampledata.us_counties import data as counties
>>> len(counties)
3233
>>> list(counties.keys())[:5]
[(53, 53), (18, 121), (26, 131), (8, 63), (38, 91)]
>>> import bokeh.sampledata.unemployment
>>> len(bokeh.sampledata.unemployment.data)
3218
>>> list(bokeh.sampledata.unemployment.data.keys())[:5]
[(53, 53), (18, 121), (26, 131), (8, 63), (38, 91)]
```

## Python 2.7.10 
```
Jonagold:bokeh crwilcox$ python
Python 2.7.10 (v2.7.10:15c95b7d81dc, May 23 2015, 09:33:12) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from bokeh.sampledata.us_counties import data as counties
>>> len(counties)
3233
>>> counties.keys()[:5]
[(53, 53), (18, 121), (8, 117), (8, 63), (38, 91)]
>>> import bokeh.sampledata.unemployment
>>> len(bokeh.sampledata.unemployment.data)
3218
>>> bokeh.sampledata.unemployment.data.keys()[:5]
[(53, 53), (18, 121), (8, 117), (8, 63), (38, 91)]
```

**Comment by bryevdv** [comment]
@crwilcox Brilliant, thanks! will merge this later tonight.

**Comment by crwilcox** [comment]
Thanks @bryevdv. Happy to get this in and improve the Python 3 story the littlest of bits. Thanks for working with me to get this in. Sorry we had a few bumps along the way!

**Pull request merged**
