### PR TITLE
document min PhantomJS version and error on bad versions

### LINKED ISSUE #7455: state and check min phantomjs version
Hello!
I have an issue with export_png function.

Using Jupyter Notebook (v.5.0.0-8734a01), running on Python 3.6.2 |Anaconda custom (64-bit)|, Bokeh (v.0.12.13).

When I run this code:
```
#Langevin vs. Nose-Hoover
p = figure(x_axis_label='Radius of compression, nm', y_axis_label='Pressure, atm', 
           plot_width=800, plot_height=600,
           x_range = (9.6, 20.4), y_range = (-20, 520))
plot = output_file('lan_nh.html', title="lan_nh")
p.xaxis.axis_label_text_font_size = "22pt"
p.xaxis.major_label_text_font_size = "18pt"
p.yaxis.axis_label_text_font_size = "22pt"
p.yaxis.major_label_text_font_size = "18pt"


files = ['VelocityVerlet_Langevin/dsDNA_4000bp_mM50/push/0.1/dsDNA_4000bp_mM50_pressure_push.dat', 
         '4000bp_concentration/dsDNA_4000bp_mM50/push_10k_steps/dsDNA_4000bp_mM50_pressure_push.dat',
         '4000bp_concentration/dsDNA_4000bp_mM50/push_100k_steps/dsDNA_4000bp_mM50_pressure_push.dat']
labels = ['Langevin',
          'Nose-Hoover 10 M steps',
          'Nose-Hoover 100 M steps']
colors = inferno(len(labels)+1)

for fname,l,c in zip(files, labels, colors):
    fname = path + fname
    radius = [float(i.split('\t')[1].strip()) for i in open(fname)]
    pressure = [float(i.split('\t')[2].strip())*1.6*9.87 for i in open(fname)]
    p.line(radius, pressure, color = c, legend=l, line_width=2)
p.legend.label_text_font_size = "18pt"
show(p)
export_png(p, filename='/home/yagafarova/lan_nh.png')
```

I get this message:
```
{"errorMessage":"'undefined' is not an object (evaluating 'window.Bokeh.documents')","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"349","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:45104","User-Agent":"Python-urllib/3.6"},"httpVersion":"1.1","method":"POST","post":"{\"script\": \"\\n// add private window prop to check that render is complete\\nwindow._bokeh_render_complete = false;\\nfunction done() {\\n  window._bokeh_render_complete = true;\\n}\\n\\nvar doc = window.Bokeh.documents[0];\\n\\nif (doc.is_idle)\\n  done();\\nelse\\n  doc.idle.connect(done);\\n\", \"args\": [], \"sessionId\": \"5992e420-0115-11e8-a323-57bffbd25446\"}","url":"/execute","urlParsed":{"anchor":"","query":"","file":"execute","directory":"/","path":"/execute","relative":"/execute","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/execute","queryKey":{},"chunks":["execute"]},"urlOriginal":"/session/5992e420-0115-11e8-a323-57bffbd25446/execute"}}
```

Does anyone know, how to solve it?

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #7455
- [x] tests added / passed
- [x] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@bokeh/dev do we need to explicitly note `packaging` as a runtime dependency? It is also used in `sphinxext`. Is it pulled in by anything else?

**Comment by bryevdv** [comment]
Does not seem to be the case:

```
(base) ❯ conda create -n test bokeh bokeh
Solving environment: done

## Package Plan ##

  environment location: /Users/bryanv/anaconda/envs/test

  added / updated specs:
    - bokeh


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    sqlite-3.22.0              |       h3efe00b_0         1.9 MB

The following NEW packages will be INSTALLED:

    bokeh:           0.12.13-py36h2f9c1c0_0
    ca-certificates: 2017.08.26-ha1e5d58_0
    certifi:         2018.1.18-py36_0
    intel-openmp:    2018.0.0-h8158457_8
    jinja2:          2.10-py36hd36f9c5_0
    libcxx:          4.0.1-h579ed51_0
    libcxxabi:       4.0.1-hebd6815_0
    libedit:         3.1-hb4e282d_0
    libffi:          3.2.1-h475c297_4
    libgfortran:     3.0.1-h93005f0_2
    markupsafe:      1.0-py36h3a1e703_1
    mkl:             2018.0.1-hfbd8650_4
    ncurses:         6.0-hd04f020_2
    numpy:           1.14.0-py36h8a80b8c_1
    openssl:         1.0.2n-hdbc3d79_0
    pip:             9.0.1-py36h1555ced_4
    python:          3.6.4-hc167b69_1
    python-dateutil: 2.6.1-py36h86d2abb_1
    pyyaml:          3.12-py36h2ba1e63_1
    readline:        7.0-hc1231fa_4
    setuptools:      38.4.0-py36_0
    six:             1.11.0-py36h0e22d5e_1
    sqlite:          3.22.0-h3efe00b_0
    tk:              8.6.7-h35a86e2_3
    tornado:         4.5.3-py36_0
    wheel:           0.30.0-py36h5eb2c71_1
    xz:              5.2.3-h0278029_2
    yaml:            0.1.7-hc338f04_2
    zlib:            1.2.11-hf3cbc9b_2
```
I will push a commit to add it as a runtime dep

**Comment by bryevdv** [comment]
@jakirkham just a heads up, this PR will add a new runtime dependency to Bokeh, not sure if C-F will need to do anything or not.

**Comment by bryevdv** [comment]
I'd like to get this in a dev build, so merging now, should be fairly uncontroversial.

**Comment by bryevdv** [comment]
@jakirkham The ground truth for the very small list of runtime dependencies is kept in `setup.py` so I think the pip package should be fine, but that's part of the reason for wanting to get a dev build out. 

Re: phantomJS I have no thoughts. This code will pick up whatever is first on the path, there's not much else we can do except provide an explicit override (which we do in an env var). That level of configuration is ultimately up to a user.

**Comment by bryevdv** [comment]
@jakirkham I think we are fine, not from `PyPI` but a pip install, brings in the correct deps:
```
(piptest) ❯ pip install --pre -i https://pypi.anaconda.org/bokeh/channel/dev/simple bokeh --extra-index-url https://pypi.python.org/simple/
Collecting bokeh
  Downloading https://pypi.anaconda.org/bokeh/label/dev/simple/bokeh/0.12.14.dev7/bokeh-0.12.14.dev7.tar.gz (15.4MB)
    100% |████████████████████████████████| 15.4MB 114kB/s
Collecting six>=1.5.2 (from bokeh)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting PyYAML>=3.10 (from bokeh)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 4.0MB/s
Collecting python-dateutil>=2.1 (from bokeh)
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 6.7MB/s
Collecting Jinja2>=2.7 (from bokeh)
  Downloading Jinja2-2.10-py2.py3-none-any.whl (126kB)
    100% |████████████████████████████████| 133kB 9.5MB/s
Collecting numpy>=1.7.1 (from bokeh)
  Downloading numpy-1.14.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.7MB)
    100% |████████████████████████████████| 4.7MB 359kB/s
Collecting packaging>=16.8 (from bokeh)
  Downloading packaging-16.8-py2.py3-none-any.whl
```

**Comment by jakirkham** [comment]
Sorry, not following @bryevdv. Is one of the dependencies bringing in PhantomJS somehow? These aren't things I would naively expect to include PhantomJS, but I could be surprised. 😄

Also pinging @bollwyvl who has done a fair bit of playing with PhantomJS in conda-forge.

Side note: We do have PhantomJS in conda-forge, but it's a repackaging of a binary ATM unfortunately. So maybe that will work.

**Comment by bollwyvl** [comment]
If "playing" is "beating head against wall". I haven't tried to make it work in a while. While it is deprecated software, it's still quite broadly used, and it would be good to have it be more robust, if possible. I think in various test scenarios, I either installed it via npm or the conda package, depending on the project, as there did seem to be small differences between them...

**Comment by bryevdv** [comment]
@jakirkham I think we are talking at odds. I was pointing out that this PR, as a side consideration, introduced `packaging` as a new runtime dependency. Then in my  last post I was merely noting that `pip` installing Bokeh appears to correctly pull in the new dependency, so the C-F package (which depends on the PyPI sdist) should be fine.

This is completely tangential to installing PahntomJS. It is an optional dependency of Bokeh and we take no strong opinion on how users install it. It happens to be available on the Bokeh channel but that's just one option. All this PR does is make sure that whatever version is install (regardless of how it was installed) is new enough.

@bollwyvl It's also possible tho not currently trivial to use Chrome headless. Plan to make that easier butter currently very resource limited so it simply has not happened yet. Will probably always need to support PhantomJS due to a client requirement.

**Comment by jakirkham** [comment]
Ah ok. Sorry. I saw the PhantomJS part with my packaging hat on and started to worry. 😨

Adding `packaging` as a dependency to `bokeh` should be trivial. So not worried about that. 😉

Though we *could* start installing PhantomJS with the package as well if it is helpful.

@bollwyvl, I think the discrepancies might be resolvable (admittedly not knowing which ones you are referring to) if we start building from source. It will at least be possible to include whatever build options we think are reasonable and it will fit better with our stack.

**Comment by mattpap** [comment]
> Though we could start installing PhantomJS with the package as well if it is helpful.

phantomjs (or any headless browser) is a heavy dependency, so it may not be desirable by default. There's a conda-forge package for phantomjs 2.1.1, though I don't know if it can be replicated with wheels.

**Comment by jakirkham** [comment]
Sorry @mattpap. Should have clarified "we" meant "conda-forge" not "bokeh". That said, otherwise agree with what you have said.

**Pull request merged**
