### PR TITLE
Use split not contains for browser compatibility

### PR DESCRIPTION
**Pull request by birdsarah**

### CODE REVIEW

**Comment by birdsarah** [comment]
Hi @bokeh/core, I've made this PR against a branch `docs_updates/0.11.0`. My proposal is this:

- we keep this branch docs_updates/0.11.0 and we use it to make ongoing improvements to the docs site that is applicable to 0.11.0
- everything in this branch will also be in master
- but not everything in master will be in this branch

My hope is that this will allow us to make ongoing improvements to things like the user guide while development continues.

**Comment by birdsarah** [comment]
I should add that I'm happy to take ownership of PRs from this branch into master.

In addition, I would imagine that we would be regularly deploying the docs manually from this branch, and each time overriding the tag (I'm not sure how to do this, but I believe you are @damianavila @bryevdv) to 0.11.0.

When 0.11.1 comes out, we would remove this branch and make a new one at the point of the release commit called `docs_updates/0.11.1` etc.

**Comment by damianavila** [comment]
The proposal sounds good to me... anyone can re-deploy but you can ping me and I can do it when you need it...

**Comment by birdsarah** [comment]
I would be more than happy to be another person who knows how to do it, so there are more available bodies.

**Comment by bryevdv** [comment]
+1

**Comment by birdsarah** [comment]
I have tested the change on Safari/Chrome/FF (OSX).

**Comment by bryevdv** [comment]
@birdsarah so this PR is ready to merge into the branch? Should I go ahead and do that or do you want to?

**Pull request merged**
