### PR TITLE
Update python idioms

### LINKED ISSUE #10289: Housekeeping: Update python idioms
I had a look through some of the source code and noticed (perfectly working) code that is using a bit out of date coding styles that are likely remnants from Python 2.6 and 2.7.

For example things like
* `IOError`/`EnvironmentError` (has been merged into `OSError` in Python 3.3+)
* `class ClassName(object):` style declarations (`object` is redundant since Python 3)
* `io.open` (once used for 2.7/3+ cross-compatibility, now redundant)
* `x = set([... for ... in ...])` which can be shortened to a set comprehension `{... for ... in ...}` (supported since Python 2.7)
* some places that are particularly amenable to f-strings (Python 3.6+)
* `super(ClassName, self).(...)` can be shortened to `super().(...)` with Python 3+

Happy to prepare a PR for this, but would like to check first if there is any interest in doing this.

### PR DESCRIPTION
**Pull request by Anthchirp**
- [x] issues: fixes #10289 
- [x] tests added / passed

* changes `class ClassName(object):` style declarations to `class ClassName:` (`object` is redundant since Python 3)
* one test class was renamed due to a typo, but the name is only used via test discovery and not referred to anywhere else
* use set comprehensions where possible
* instances of `EnvironmentError`, `IOError`, and `socket.error` are [changed to `OSError`](https://docs.python.org/3/library/exceptions.html#OSError.filename2). 
* `io.open` changed to plain `open`
* Changed some string formatting to use f-strings where it significantly improves readability
* `u"string"` changed to `"string"`, unnecessary string castings and constant string encodings removed
* change `super(ClassName, self)` to the Python 3 `super()` shorthand
* mixed bits and pieces (fix up string escaping, avoid list instantiation where not required, superfluous ()s)

I applied black-style formatting to any lines I touched and their immediate vicinity where appropriate, as it seemed the sensible thing to do given that bokeh seems to be moving towards black eventually (#9636)

### CODE REVIEW

**Comment by bryevdv** [comment]
@Anthchirp This turned out bigger than I expected. If you are willing I think it might be better to submit the updates as a series of separate PRs. Since the commits are distinct it should be fairly straighrforward to cherry-pick them on to new branches one by one. 

Regarding Black, unfortunately the core team is somewhat seriously divided over this topic. Once our decision making process is ratified we will simply have to record a formal decision on the matter. I would advise not to worry about applying any formatting at present.

**Comment by Anthchirp** [comment]
any recommendations if anything can be put together in one PR or do you want 9 separate PRs? :slightly_smiling_face:

**Comment by mattpap** [comment]
I'm fine with reviewing this PR as-is, given how well classes of changes are separated between commits.

**Comment by mattpap** [comment]
There seems to be a legitimate regression:
```
655201Z tests/test_examples.py::test_file_examples[/home/runner/work/bokeh/bokeh/examples/models/file/trail.py-example30-config30] 
2020-07-11T22:13:16.6656144Z [37m[1m[INFO][0m Example run in [37m[1m0.683s[0m
2020-07-11T22:13:16.6656723Z [33m[PY][0m Traceback (most recent call last):
2020-07-11T22:13:16.6657271Z [33m[PY][0m   File "<string>", line 13, in <module>
2020-07-11T22:13:16.6657848Z [33m[PY][0m   File "/home/runner/work/bokeh/bokeh/examples/models/file/trail.py", line 126, in <module>
2020-07-11T22:13:16.6658376Z [33m[PY][0m     data = prep_data(obiszow_mtb_xcm)
2020-07-11T22:13:16.6658936Z [33m[PY][0m   File "/home/runner/work/bokeh/bokeh/examples/models/file/trail.py", line 44, in prep_data
2020-07-11T22:13:16.6659473Z [33m[PY][0m     df["dist"] = np.concatenate(([0], np.cumsum(dist)))
2020-07-11T22:13:16.6660266Z [33m[PY][0m   File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/pandas/core/frame.py", line 2938, in __setitem__
2020-07-11T22:13:16.6661171Z [33m[PY][0m     self._set_item(key, value)
2020-07-11T22:13:16.6662205Z [33m[PY][0m   File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/pandas/core/frame.py", line 3000, in _set_item
2020-07-11T22:13:16.6662900Z [33m[PY][0m     value = self._sanitize_column(key, value)
2020-07-11T22:13:16.6663573Z [33m[PY][0m   File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/pandas/core/frame.py", line 3636, in _sanitize_column
2020-07-11T22:13:16.6664180Z [33m[PY][0m     value = sanitize_index(value, self.index, copy=False)
2020-07-11T22:13:16.6665183Z [33m[PY][0m   File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 611, in sanitize_index
2020-07-11T22:13:16.6665956Z [33m[PY][0m     raise ValueError("Length of values does not match length of index")
2020-07-11T22:13:16.6666502Z [33m[PY][0m ValueError: Length of values does not match length of index
2020-07-11T22:13:16.6667109Z [31mFAILED[0m
```

**Comment by bryevdv** [comment]
@Anthchirp since @mattpap has indicated he is OK to review this as one PR please ignore my previous suggestion. It would be helpful if you can narrow down which commit is causing the problem with `examples/models/file/trail.py`

**Comment by bryevdv** [comment]
@Anthchirp That should be it, I was actually just checking to verify ho numpy behaves:
```
In [2]: np.array([x for x in [1,2,3]])
Out[2]: array([1, 2, 3])

In [3]: np.array(x for x in [1,2,3])
Out[3]: array(<generator object <genexpr> at 0x7fd5d953aa50>, dtype=object)
```
Thanks so much for this PR is was a bug lift in a short time!

**Comment by Anthchirp** [comment]
TIL. I checked this before the initial commit but looks like I missed a nuance there. :slightly_smiling_face:

**Comment by bryevdv** [comment]
@Anthchirp I don't think there was a second regression, there are still some flaky integration tests. It passed on re-run. (Now an OSX job is also stuck but AFAIK that's some occasional issue on GH's end)

**Comment by mattpap** [comment]
I reviewed all changes and fixed some of the more "eye catching" style changes.

**Comment by mattpap** [comment]
@Anthchirp, thanks for contributing.

**Pull request merged**
