### PR TITLE
Implement WebGL multi_line glyph

### PR DESCRIPTION
**Pull request by ianthomas23**
This PR implements WebGL `multi_line` glyph, completing item 6 of #11369.

It includes support for vector and scalar visual properties, `nan` to represent missing points, dashes, `linewidth` less than one (implemented as `linewidth=1` and lower `alpha`) and selection indexes which refer to whole lines rather than the individual line segments that `line` and `step` glyphs refer to.

Existing tests have been modified to include the new functionality. There are single-pixel modifications to some test images as some calculations that occurred on the CPU now occur on the GPU with slightly different rounding.

As an example of the performance benefits, here is some test code:
```python
from bokeh.palettes import TolRainbow23
from bokeh.plotting import figure, show
import numpy as np

nlines = 100
points_per_line = 1000
rng = np.random.default_rng(1645)
xs = [rng.uniform(size=points_per_line) for _ in range(nlines)]
ys = [rng.uniform(size=points_per_line) for _ in range(nlines)]
colors = rng.choice(TolRainbow23, size=nlines)

backend = 'canvas'
#backend = 'webgl'
p = figure(width=600, height=600, output_backend=backend, title=backend)
p.multi_line(xs, ys, alpha=0.2, line_color=colors)
show(p)
``` 
Running this on my Ubuntu 20.04 laptop with an Nvidia Quadro T1000 and panning the plot in small circles whilst measuring the frames per second as a simple performance measurement gives 59 FPS using WebGL and 1 FPS using canvas. With 1000 lines of 1000 points each WebGL gives 11 FPS and canvas an unusable 0.1 FPS. Interestingly on my M1 mac there is hardly any difference which I don't fully understand yet.

## Implementation details

1. I am using a (slightly modified) pair of GLSL shaders for both single and multiple lines. There is separate `ReGL` render call to the shaders for each line. The complexity with multiple lines is that you cannot naively render multiple lines on top of each other as they will not mix colors correctly. So here I use a separate `framebuffer`, which is essentially a second WebGL canvas, to render a single line at a time to, and this is alpha-mixed in the usual manner to the default WebGL renderbuffer. This is fast, both buffers are on the GPU.

2. I am using a ragged (or offset) array approach for the buffers of points, visual properties, etc that are passed to the GPU. Hence each `multi_line` render transfers only a single set of buffers to the GPU rather than a set of buffers per constituent line. This makes the logic more complicated than before, but performant. Single `line` and `step` glyphs now use the same implementation so they are essentially single-line specialisations of the ragged array approach.

## Future work

This is functionally complete and performs well. I have identified some improvements for upcoming PRs:
1. A `multi_line` with just one line or multiple lines with the same RGB values does not need to use the accumulator framebuffer approach, it can write directly to the WebGL canvas.
2. In passing data to `ReGL` there are now two similar functions `to_attribute_config` and `to_attribute_config_divisor`. I have realised that ultimately only one of these is needed so I will refactor and explain this separately.
3. Dashed lines, if present, are always implemented as vector visual properties even if they are scalar. This is wasteful. But I will fix this at the same time as other rework of dashed lines (item 3 of #11050).

### CODE REVIEW

**Comment by ianthomas23** [comment]
Note to self: this fixes #13195, I need to add specific tests for that and similar test cases.

**Comment by ianthomas23** [comment]
This is now ready for review, assuming CI passes.

I have added a visual regression test for issue #13195 that tests for correct rendering of nonselection glyphs for both `Line` and `MultiLine` glyphs.

**Comment by mattpap** [comment]
In need to experiment with this PR a bit more, because so far webgl implementation seems to be always slower than canvas on my laptop.

**Comment by ianthomas23** [comment]
> In need to experiment with this PR a bit more, because so far webgl implementation seems to be always slower than canvas on my laptop.

On investigating I don't think it is this PR. If I use `branch-3.3` and a single `line` glyph on my LInux box with separate graphics card) webgl is much faster than canvas, but on my macbook (no separate graphics card) it is worse. In my situation the OS/browser combination is doing an extra level of software antialiasing. I can turn this off by changing line 39 of `bokehjs/src/lib/models/canvas/canvas.ts` from
```typescript
const gl = canvas.getContext("webgl", {premultipliedAlpha: true})
```
to
```typescript
const gl = canvas.getContext("webgl", {premultipliedAlpha: true, antialias: false})
```
Can you try this and see what happens?

**Comment by ianthomas23** [comment]
I've incorporated the `data_mapped` improvements of #13236. Using a dedicated graphics card the performance is excellent, but on my M1 mac with integrated graphics the performance for single line is behind that of canvas. I definitely don't want to tune the implementation to such systems, but I think it is worth me experimenting with some other ideas here that might help.

**Comment by mattpap** [comment]
It seems to work about the same for me with the recent changes. In any case, let's work incrementally on this.

**Review by mattpap — APPROVED** [review]

**Comment by ianthomas23** [comment]
@bryevdv self-requested a review so I will hold off merging for a day or two.

**Review by bryevdv — APPROVED** [review]

**Pull request merged**
