### PR TITLE
adding test case for transform model issue  #8572

### LINKED ISSUE #8572: transforms.py is missing property unit tests
Noticed today that the Transforms in `bokeh/models/transforms.py` are missing simple properties unit tests - like those in `bokeh/models/tests/test_annotations.py`

### PR DESCRIPTION
**Pull request by Nkarnaud**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes #8572 
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by Nkarnaud** [comment]
solution to issue #8572

**Comment by bryevdv** [comment]
@Nkarnaud awesome thank you! Two small changes to request:

* Can you remove the `.idea` files from the PR? We don't check in any sorts of various editor configs 

* Can you remove the formatting changes e.g. adding the space between `# ----`? We have a standard format that we use in eery file and should keep consistent

**Comment by bryevdv** [comment]
HI @Nkarnaud just checking in do you think you will be able to make the changes listed above in the next week or so (before the 2.1 code freeze)? If not do you mind if we push changes to your branch?

**Comment by Nkarnaud** [comment]
HI @bryevdv yes I will do the changes this weekend

**Comment by Nkarnaud** [comment]
just provide a new pull with correction of the above point

**Comment by bryevdv** [comment]
Thanks @Nkarnaud !

**Pull request merged**
