### PR TITLE
Simplify glyph units

### LINKED ISSUE #2087: Simplifying glyph units
I am working on #2086 at the moment, and a few thoughts about how we handle units have floated through my head. I'd like to get some feedback on some ideas and perhaps the start of a proposal too.

In theory, all of our glyphs can accept either data or screen space coordinates for basically any coordinate or distance. I say "in theory" because this capability has not been thoroughly tested, and I can imagine it has numerous bugs. In fact I am quite certain alot of the hit-testing machinery will fall over with screen units in some places. Here is the thought that occurred to me:

> "screen space" coordinates are (should be) only for annotations 

Is that right? I am trying to think of use cases for screen space coordinates for *data*, and can't. Screen space *distances* (like marker size), sure. But not really for positions. We have never used them that way, I don't think we have ever had  a single example that does this, or gotten a question about it. Anything I can think of that you would want to absolutely position is really some kind of annotation. So here is my proposal:

* Split `DataSpec` into:
 - `Coordinate` (which is always assumed to be data space values)
 - `Distance` (has a corresponding *visible attribute* for `_units`, can be either screen or data space)
 - `ScreenDistance` used for marker size, e.g. (no corresponding `_units`)
 - `DataDistance` used for circle radius, e.g. (no corresponding `_units`)
 - `Position` this is the same as `Distance`, to allow data/screen coords *just for annotations*

So then markers, for instance, would look like this:
```
class Marker:
    x = Coordinate
    y = Coordinate
    size = ScreenDistance
```

Adding these assumption and narrowing these properties would afford a huge simplification all over the BokehJS renderer logic and also lend several things to better testing because the branching is not so completely insane.

What about when you do want to put a `Rect` at some specified screen spot? I propose making new annotation types that can display glyphs at either data locations or screen locations (by accepting `Position`). That's fine and simple, because the annotation can convert the screen positions to data space at render time. I also think we can get by with just supporting a few glyphs for annotations. Of note: annotations would not participate in auto-ranging computations, and hit-testing (if it is needed) can just be done brute-force by the annotation. 

The main point of this is: ***it keeps screen space inputs completely out of normal rendering, hit-testing, and auto-ranging code paths*** and this would be a *huge, truly incredible* simplification. It would also add conceptual clarity in some places where specifications are muddy or overly general. 

Thoughts? I think this can be a significant improvement to the stability, reliability, consistency, and maintainability of the BokehJS codebase. I actually think this is one of the most important things we can do to improve the BokehJS codebase. 

ping @bokeh/core, @pzwang  and @mattpap especially

### PR DESCRIPTION
**Pull request by bryevdv**
issues: closes #2087 

New PR based off master (now that #2086 is merged in)

## Methods to test
* `conda install -c javascript gulp`
* `npm install` within the `bokehjs` directory
* Run `gulp scripts` to test CoffeeScript generation
* Run `gulp minify` to test building a minified version
* Run `gulp` to test automatically generating code and watching for changes to CoffeeScript files
* Run `gulp install-js` to test building and installing code in develop mode
* Run `gulp develop` watching code and running build and install on changes

## Outstanding Tasks
* [x] Remove vendor code / replace with bower (@tswicegood -- done in #2112) 
* [x] Fix `setup.py` so it properly relies on gulp (@tswicegood)
* [x] Build CSS from gulp file (@tswicegood)
* [x] Mocha tests (@tswicegood / @bryevdv)
* [x] Remove split JS mode (@bryevdv)
* [x] Fix outstanding glyph units issues (@bryevdv)
* [x] Fix build issues relating to jQuery UI (@tswicegood / part of bower changes above)
* [x] Burn grunt in a ceremonial funeral pyre (@tswicegood)
* [ ] Update development documentation with the new build method for bokeh.js
* [x]  Numeral.format(value, format) broken / custom numeral.js issue `bokeh/examples/glyphs//maps.py` and `bokeh/examples/glyphs//sprint.py` (@tswicegood)
* [x] missing slider / jquery-ui issue `bokeh/examples/glyphs//taylor_server.py` (@tswicegood)

## Follow-on PRs
* [ ] render order randomly such that some glyphs are obscured sometimes `bokeh/examples/compat/seaborn/violin.py` and `bokeh/examples/compat/seaborn/sinerror.py` (@tswicegood)
* [ ] missing text annotation in `bokeh/examples/glyphs//iris_splom.py` (@tswicegood)

## Nice to haves (possibly opened as separate PRs)
* [ ] Add `index.coffee` files to every module level to allow building a tree of objects
* [ ] Replace various marker code with generative metaprogramming (see [`widgets/layouts/base.coffee`][1])
* [ ] Automatically generate `Collection` objects at `base` level when no customization is present

[1]: https://github.com/bokeh/bokeh/blob/task/2087_glyph_units/bokehjs/src/coffee/widget/layouts/base.coffee

### CODE REVIEW

**Comment by tswicegood** [comment]
@bokeh/dev: @bryevdv and I spent some time this afternoon moving the CoffeeScript build over to a [browserify][1] / CommonJS-based code base.  This is a pretty sweeping change as it removes all of the require.js cruft in favor of the move straight-forward CommonJS module pattern used by Node.js and io.js.

I've updated the description with the outstanding list of tasks that @bryevdv and I came up with and assigned them appropriately.  Some may end up getting spun off into other issues / PRs.

Couple of things to note:

* This breaks any custom build code that you might have to do incremental build or custom builds outside of the traditional Grunt system.  There are options for doing incremental builds, but the first step here is to get a reliable build on the beaten path before introducing additional dependencies.
* Once all of the tasks are completed, Grunt will be going away along with the `./bokehjs/src/vendor/` directory.  The changes are in favor of Gulp + Bower for managing dependencies that can't be installed via `npm`.  Both Gulp and Bower are in the `javascript` channel on Binstar.
* The `watch` command is most likely going to end up in bokeh.js as that functionality is baked into Gulp.  It'll trigger calls to `setup.py` as necessary to do Python-specific things, but it'll be the main way to handle testing CoffeeScript changes.
* If you have any outstanding PRs against `master`, there will almost certainly be merge conflicts.  @bryevdv and I will be around to help get them sorted out, but be prepared. :sunglasses: 

----

Unfortunately, this is one of those changes that has to be done in bulk.  It touches pretty much every line of code in the CoffeeScript by virtue of the indention changing.This paves the way for bokeh.js code to be loaded as a Node.js module, allows for unit testing to happen on the server side, and hopefully will allow us to generate plots and such without a browser, though that will still require some additional testing.

If you have the bandwidth to test out this change, please do.  Report any issues you have back to here.  Also, if you have any general concerns -- let us know.

[1]: http://browserify.org/

**Comment by bryevdv** [comment]
Currently know local test issues:
```
/Users/bryan/work/bokeh/examples/charts/boxplot.py:
/Users/bryan/work/bokeh/examples/plotting/file//boxplot.py:
/Users/bryan/work/bokeh/examples/plotting/server//boxplot.py:
 outliers?


/Users/bryan/work/bokeh/examples/charts/dots.py:
/Users/bryan/work/bokeh/examples/plotting/file//categorical.py:
/Users/bryan/work/bokeh/examples/glyphs//sprint.py:
 missing dots


/Users/bryan/work/bokeh/examples/compat/ggplot//ggplot.ipynb:
/Users/bryan/work/bokeh/examples/compat/mpl//mpl.ipynb:
/Users/bryan/work/bokeh/examples/compat/seaborn/seaborn.ipynb:
/Users/bryan/work/bokeh/examples/glyphs//data_tables.ipynb:
/Users/bryan/work/bokeh/examples/glyphs//glyph.ipynb:
 bokeh load


/Users/bryan/work/bokeh/examples/compat/mpl//polycollection.py:
 not sure


/Users/bryan/work/bokeh/examples/compat/seaborn/sinerror.py:
 data points misplaced


/Users/bryan/work/bokeh/examples/compat/seaborn/violin.py:
 missing stats bars


/Users/bryan/work/bokeh/examples/glyphs//buttons_server.py:
 JS typo error

/Users/bryan/work/bokeh/examples/glyphs//gauges.py:
 missing text


/Users/bryan/work/bokeh/examples/glyphs//gears.py:
 js error


/Users/bryan/work/bokeh/examples/glyphs//glyphs.py:
 ranging, sizes


/Users/bryan/work/bokeh/examples/glyphs//iris_splom.py:
 missing text annotation


/Users/bryan/work/bokeh/examples/glyphs//maps.py:
 js error


/Users/bryan/work/bokeh/examples/glyphs//prim_server.py:
 colors? missing plot

/Users/bryan/work/bokeh/examples/glyphs//taylor_server.py:
 missing slider

/Users/bryan/work/bokeh/examples/glyphs//calendars.py:
/Users/bryan/work/bokeh/examples/plotting/file//burtin.py:
/Users/bryan/work/bokeh/examples/plotting/file//elements.py:
/Users/bryan/work/bokeh/examples/plotting/file//periodic.py:
/Users/bryan/work/bokeh/examples/plotting/file//tap.py:
/Users/bryan/work/bokeh/examples/plotting/server//burtin.py:
/Users/bryan/work/bokeh/examples/plotting/server//elements.py:
/Users/bryan/work/bokeh/examples/plotting/server//hover.py:
/Users/bryan/work/bokeh/examples/plotting/server//tap.py:
 text alignment off

/Users/bryan/work/bokeh/examples/plotting/server//abstractrender.py:
/Users/bryan/work/bokeh/examples/plotting/server//census.py:
 maybe? one plot missing


/Users/bryan/work/bokeh/examples/plotting/server//scatter_selection.py:
 flickering updates from server on every mouse move example

Backbone missing from app/embed examples
```
Many of these are probably the same problems, so I'd estimate ~10 (small) real issues

**Comment by mattpap** [comment]
Why this PR mixes two unrelated things? How we are supposed to review this?

**Comment by bryevdv** [comment]
@mattpap I understand this chuck of work strays outside the bounds of our normal process. We will make sure all the existing tests and examples work without modification. It This situation was heavily influenced by the parameters of the sprint, it's dates, and being able to get something working during that time without a truly impossible merge conflict to resolve.

**Comment by tswicegood** [comment]
@bryevdv I've moved your tasks into the description and added them as items to be completed.  The Numeral one is basically done.  I tested it and thought I committed / pushed it yesterday, but I guess not.

**Comment by tswicegood** [comment]
@mattpap (and everyone else too, for that matter), I'm happy to chat about the Browserify part of this change if you'd like since I'm the one that instigated it.  I'm trying to move the entire Continuum JS stack over to one package / build tool so people can move between projects more easily.  That coupled with the ability to run tests via node/iojs seems like a big win.

**Comment by tswicegood** [comment]
As of merge commit 43e5aaee76e2c0e72436ad92cbeea4b788b7f57a I've modified `build_views` to automatically add `bk-` prefixes to any classes that start with `ui-`.  I feel pretty confident that code works without problem ([tests here][1]), but I'm not sure if `build_views` is the only place where jQuery UI widgets would be used.  Where else should that be addressed?  Instead of dealing with it at the `build_views` layer, should I put it in the individual views that build jQuery UI widgets?

[1]: https://github.com/bokeh/bokeh/blob/66922c96ac39f5eb4365ee3f05ed7c547dede02a/bokehjs/test/test_common/test_build_views.coffee

**Comment by tswicegood** [comment]
¡¡¡ :tada: !!!

Tests pass!

**Comment by bryevdv** [comment]
@bokeh/core All tests pass, report looks good, and hand-testing has been OK. intend to merge this morning CST. Please let me know if there is something in particular you want to test/want tested, or if there is reason to wait.

**Comment by fpliger** [comment]
Great! :+1:  

@bryevdv / @tswicegood, are there any know issues (apart from the ones in "Follow-on PRs") that we can add issues for already? I agree and think we should merge and pay good attention in the next days expecting some potential instability.

**Comment by bryevdv** [comment]
I'll make some additional issues today.

**Pull request merged**
