### PR TITLE
Fixing autohide pan and wheel stutter

### PR DESCRIPTION
**Pull request by jsignell**
- [x] issues: partially #8332 
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

pan_works

```python
from bokeh.plotting import figure, show, output_file

output_file("test0.html")

p = figure(plot_width=300, plot_height=300)
p.scatter([1, 2, 3], [1, 2, 3])

p.toolbar.autohide = True

show(p)
```

### CODE REVIEW

**Comment by bryevdv** [comment]
If possible, at test that it is visible after clicking the reset tool would also be valuable I think

**Comment by bryevdv** [comment]
Also, one benefit of View Models is that they are often easier to test than views. Here e.g. we could also add a unit test to the method on the view model.

**Comment by jsignell** [comment]
> add a unit test to the method on the view model

You mean the getter for visible right?

**Comment by bryevdv** [comment]
> You mean the getter for visible right?

Yes it has internal logic that should be straightforward to directly maintain under test

**Comment by bryevdv** [comment]
TS linter failure, not exactly sure what it means:

> [21:41:26] build/js/types/models/tools/toolbar_base.d.ts(24,1): error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.

**Comment by jsignell** [comment]
ok unit test added :)

**Comment by bryevdv** [comment]
Thanks for the first PR of the post 1.0 era @jsignell :)

**Pull request merged**
