### PR TITLE
Drop support for Python 3.9 and modernize the codebase

### LINKED ISSUE #13515: CI unit-test on Python 3.9 fails systematically
Noticed on multiple recent PRs, e.g. https://github.com/bokeh/bokeh/actions/runs/6759027374/job/18371768064?pr=13512:

```py
=================================== FAILURES ===================================
___________________ test__autocreate_signed_session_autoload ___________________

cls = <class '_pytest.runner.CallInfo'>
func = <function call_runtest_hook.<locals>.<lambda> at 0x7fc4ed3c35e0>
when = 'call'
reraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)

    @classmethod
    def from_call(
        cls,
        func: "Callable[[], TResult]",
        when: "Literal['collect', 'setup', 'call', 'teardown']",
        reraise: Optional[
            Union[Type[BaseException], Tuple[Type[BaseException], ...]]
        ] = None,
    ) -> "CallInfo[TResult]":
        """Call func, wrapping the result in a CallInfo.
    
        :param func:
            The function to call. Called without arguments.
        :param when:
            The phase in which the function is called.
        :param reraise:
            Exception or exceptions that shall propagate if raised by the
            function, instead of being wrapped in the CallInfo.
        """
        excinfo = None
        start = timing.time()
        precise_start = timing.perf_counter()
        try:
>           result: Optional[TResult] = func()

/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/_pytest/runner.py:341: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/_pytest/runner.py:262: in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/pluggy/_hooks.py:493: in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/pluggy/_manager.py:115: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/_pytest/unraisableexception.py:88: in pytest_runtest_call
    yield from unraisable_exception_runtest_hook()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def unraisable_exception_runtest_hook() -> Generator[None, None, None]:
        with catch_unraisable_exception() as cm:
            yield
            if cm.unraisable:
                if cm.unraisable.err_msg is not None:
                    err_msg = cm.unraisable.err_msg
                else:
                    err_msg = "Exception ignored in"
                msg = f"{err_msg}: {cm.unraisable.object!r}\n\n"
                msg += "".join(
                    traceback.format_exception(
                        cm.unraisable.exc_type,
                        cm.unraisable.exc_value,
                        cm.unraisable.exc_traceback,
                    )
                )
>               warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
E               pytest.PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object HTTPServer.close_all_connections at 0x7fc4ec[444](https://github.com/bokeh/bokeh/actions/runs/6759027374/job/18371768064?pr=13512#step:8:445)c40>
E               
E               Traceback (most recent call last):
E                 File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/asyncio/selector_events.py", line 293, in _add_writer
E                   key = self._selector.get_key(fd)
E                 File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/selectors.py", line 193, in get_key
E                   raise KeyError("{!r} is not registered".format(fileobj)) from None
E               KeyError: '77 is not registered'
E               
E               During handling of the above exception, another exception occurred:
E               
E               Traceback (most recent call last):
E                 File "<string>", line 1, in <lambda>
E               KeyError: '__import__'

/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning
```

### PR DESCRIPTION
**Pull request by mattpap**
This PR drops support for Python 3.9 and takes advantage of the following PEPs: 634 (pattern matching), 604 (`A | B`), 613 (`TypeAlias`), 647 (`TypeGuard`). I converted a few obvious cases from `if-elif-else` to `match-case` as a trial run. I tenatatively added this PR to 3.4 milestone, but I suppose we may want to postpone this till 3.5.

fixes #13515

### CODE REVIEW

**Comment by bryevdv** [comment]
This is a nice minpy-bump, as they go. NEP 29 data for dropping Python 3.9 is Apr 05, 2024 so Bokeh 3.5 is probably ideal.

**Comment by mattpap** [comment]
> NEP 29 data for dropping Python 3.9 is Apr 05, 2024 so Bokeh 3.5 is probably ideal.

Our BEP 9 says it should be at least 3 months after the most recent Python release, which is about now. With pushing this to 3.5 I was thinking about panel.

**Comment by philippjfr** [comment]
+1 on waiting until 3.5. That said I would suggest that we amend BEP 9 to align with NEP 29 if they are indeed not synced. I would consider NEP 29 quite aggressive and would not want to be out ahead of them.

**Comment by bryevdv** [comment]
@philippjfr we can revisit, but the original rationale for the difference from NEP-29 is here https://github.com/bokeh/bokeh/issues/10558#issuecomment-709685036 It's possible NEP-29 has also been updated since then too.

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
@mattpap I'd suggest merging this sooner rather than later in order to shave some work off our CI pipeline

**Pull request merged**
