### PR TITLE
Clean up gulp source mapping

### PR DESCRIPTION
**Pull request by mistakevin**
Automatically produce external map files for bokeh.js (loads coffeescript directly into dev console) and for bokeh.min.js (points to location in bokeh.js)

CSS works in similar way, but even better. Loads LESS file directly in console when using either bokeh.css or bokeh.min.css

And for reference, source maps only load if they are activated in the developer console, and the developer console is open (in chrome).

### CODE REVIEW

**Comment by mistakevin** [comment]
may conflict with https://github.com/bokeh/bokeh/pull/2660

**Comment by damianavila** [comment]
>And for reference, source maps only load if they are activated in the developer console, and the developer console is open (in chrome).

IIRC if it is a reference to this in the docs, but if not, it has to be documented.

**Comment by bryevdv** [comment]
@mistakevin here are your conflicts :)

**Comment by mistakevin** [comment]
conflicts resolved and docs added

**Comment by bryevdv** [comment]
LGTM (tested)

**Comment by damianavila** [comment]
This seems to break master when BokejJS is loaded to the notebook, see @birdsarah report in the flow and mailing list: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/NgwanbRYJHk

**Pull request merged**
