### PR TITLE
streamline ci install for downstream

### LINKED ISSUE #11211: [BUG] Conflicting test dependencies in downstream CI build
In https://github.com/bokeh/bokeh/pull/11207 we observed that `bokeh`s own test dependencies can sometimes conflict with test dependencies of other downstream projects. For example, `flaky` (used by `bokeh`) and `pytest-rerunfailures`  (used by `dask` / `distributed`) both register their own `flaky` `pytest` marker which can lead to errors when trying to run tests.

As a temporary workaround, we're attempting to uninstall `flaky` in the downstream CI build over in https://github.com/bokeh/bokeh/pull/11207. However, it would be good to revisit this in the future with a more long-term fix.

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #11211

cc @jrbourbeau please confirm this satisfies the need on the Dask side

### CODE REVIEW

**Comment by bryevdv** [comment]
@philippjfr I think maybe one new Panel test is failing, lack of a terminal process to execute maybe?

**Review by jrbourbeau — COMMENTED** [review]
Thanks @bryevdv! This looks like it solves the original `flaky` issue. However, I noticed that none of the `distributed` tests are being collected/run

```
 +------------------------------------------------------------------------------------+
+ pytest distributed/dashboard
| Dask -- distributed/dashboard                                                      |
+------------------------------------------------------------------------------------+

============================= test session starts ==============================
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages
plugins: xdist-2.3.0, rerunfailures-10.1, forked-1.3.0
collected 0 items
```

This is almost certainly because we stopped packaging tests in `distributed` (xref https://github.com/dask/distributed/pull/5054). To handle this, we could `git clone` distributed in `ci/install_downstream_packages.sh` instead of installing from PyPI. Would that be an acceptable solution here?

**Comment by bryevdv** [comment]
@jrbourbeau doing a clone is certainly fine, that's what we do for PandasBokeh, etc. Could you provide the small patch for me to apply?

**Review by jrbourbeau — COMMENTED** [review]
The following `diff` should do it

```diff
diff --git a/ci/install_downstream_packages.sh b/ci/install_downstream_packages.sh
index 8d66a5aa2..ed40f7708 100644
--- a/ci/install_downstream_packages.sh
+++ b/ci/install_downstream_packages.sh
@@ -3,7 +3,9 @@
 set -x #echo on

 conda install --yes --quiet -c pyviz/label/dev holoviews nose scipy
-pip install dask["test"] distributed  # "test" extra installs additional testing dependencies
+git clone https://github.com/dask/dask.git
+pip install -e "./dask[test]"  # "test" extra installs additional testing dependencies
+git clone https://github.com/dask/distributed.git
 pip install pandas_bokeh
 pip install geopandas
 git clone https://github.com/PatrikHlobil/Pandas-Bokeh.git
```

**Comment by jrbourbeau** [comment]
Whoops, I forgot this too 

```diff
diff --git a/ci/run_downstream_tests.sh b/ci/run_downstream_tests.sh
index 755c2a7b1..edf36ff39 100644
--- a/ci/run_downstream_tests.sh
+++ b/ci/run_downstream_tests.sh
@@ -24,10 +24,14 @@ set +e
 pushd "$(python -c 'import site; print(site.getsitepackages()[0])')" || exit

 banner "Dask -- dask/diagnostics" 2> /dev/null
+cd dask
 pytest dask/diagnostics
+cd ../

 banner "Dask -- distributed/dashboard" 2> /dev/null
+cd distributed
 pytest distributed/dashboard
+cd ../

 banner "Panel" 2> /dev/null
 pytest panel/tests
```

This will also make sure `pytest` picks up the `conftest.py` file in the root of the `dask` and `distributed` repos

**Comment by bryevdv** [comment]
@jrbourbeau tests are (mostly) running now but I think maybe  few more packages/tweaks are needed, please lmk

**Comment by jrbourbeau** [comment]
Double whoops, hopefully this will be the last tweak needed

```diff
diff --git a/ci/install_downstream_packages.sh b/ci/install_downstream_packages.sh
index ed40f7708..d26d87627 100644
--- a/ci/install_downstream_packages.sh
+++ b/ci/install_downstream_packages.sh
@@ -3,9 +3,10 @@
 set -x #echo on

 conda install --yes --quiet -c pyviz/label/dev holoviews nose scipy
+git clone https://github.com/dask/distributed.git
+pip install -e "./distributed"
 git clone https://github.com/dask/dask.git
 pip install -e "./dask[test]"  # "test" extra installs additional testing dependencies
-git clone https://github.com/dask/distributed.git
 pip install pandas_bokeh
 pip install geopandas
 git clone https://github.com/PatrikHlobil/Pandas-Bokeh.git
```

**Comment by bryevdv** [comment]
Thanks @jrbourbeau !

**Pull request merged**
