### PR TITLE
Backports for 2.2.2

### PR DESCRIPTION
**Pull request by bryevdv**
@philippjfr @mattpap 

I get conflicts as soon as I try cherry-pick most anything from https://github.com/bokeh/bokeh/milestone/64 on to `branch-2.2` I expect that is due to the extensive changes to hundreds of files in #10433 and/or #10450 

What  do you want to do here? My own opinion is that if we have to backport those huge PRs first to be able to backport the other smaller work, we should just cut 2.3 instead.

### CODE REVIEW

**Comment by mattpap** [comment]
Pushing 2.3 would be the easiest, but we aren't ready for this. 2.2.2 is supposed to be a *patch* release, thus 2.2.2 milestone is way too big. It should contain only what is really needed to fix 2.2 branch (i.e. regressions) and not fix (non-trivial) pre-existing issues or include new developments. Thus I would just include parts of PRs #10521, #10518, and perhaps whatever else that is trivially cherry-pickable. Cherry picking should happen in merge order, to minimize the number of conflicts.

**Comment by philippjfr** [comment]
Apologies for increasing the scope of the 2.2.2 release, I agree with @mattpap's plan to include just the two main patches fixing regressions introduced in 2.2.x and only considering others if they trivial to cherry-pick.

**Comment by bryevdv** [comment]
> Cherry picking should happen in merge order, to minimize the number of conflicts.

Thanks, I was doing this already.

**Comment by bryevdv** [comment]
@mattpap @philippjfr just double checking -- this now has everything you want in 2.2.2? If I will merge and cut the release.

**Comment by mattpap** [comment]
This is the minimum we need, though it would be good if @philippjfr tested this with at least holoviews.

**Comment by philippjfr** [comment]
Not sure if this is something to do with my local build but I'm seeing errors loading Bokeh in the notebook when I build this branch:

```python
import os
os.environ['BOKEH_MINIFIED'] = 'false'
os.environ['BOKEH_RESOURCES'] = 'inline'

import bokeh.io
bokeh.io.output_notebook()
```

```
VM3472:629 Uncaught TypeError: __esModule is not a function
    at Object._ (<anonymous>:629:11)
    at require (<anonymous>:230:29)
    at Object._ (<anonymous>:284:32)
    at require (<anonymous>:230:29)
    at <anonymous>:241:22
    at <anonymous>:280:7
    at <anonymous>:168:23
    at inline_js (<anonymous>:175:9)
    at run_inline_js (<anonymous>:76159:20)
    at <anonymous>:76181:7
```

**Comment by philippjfr** [comment]
Seems to have been an issue with my local build, cleaned up and tried again and it resolved itself.

**Comment by philippjfr** [comment]
Can confirm that the issues rendering graphs have been resolved.

**Comment by mattpap** [comment]
> `VM3472:629 Uncaught TypeError: __esModule is not a function`

Due to a major upgrade of tsc, a full rebuild is required. I will need to add this to build cache invalidation logic, so that such rebuild is triggered automatically.

**Comment by bryevdv** [comment]
@mattpap the milestone needs cleaning up. The changelog is genreated from the milestone, so it needs to reflect what is actually in the release. There were various PRs moved out of it, but their associated issues seem to have been left behind. 

https://github.com/bokeh/bokeh/milestone/64?closed=1

**Comment by bryevdv** [comment]
Alternatively if you want me to clean up the milestone, that's fine but it won't be until this weekend.

**Comment by mattpap** [comment]
> Propose that in the future for point releases, we create an issue for deciding what gets backported up front, then create the milesone reactively when the PR is submitted, based on what went in the PR. Having the milestone represent both "proposed work to include" before and "work that was included" after, is hard to manage and error prone.

Sure, that would be my preferred way.

**Comment by mattpap** [comment]
I updated the milestone.

**Comment by bryevdv** [comment]
I moved #10451 in to 2.2.2 as well since it appears to be included above. I will work on a release this morning.

**Comment by bryevdv** [comment]
Just noting that we missed https://github.com/bokeh/bokeh/pull/10513 for 2.2.2 and that was a fairly serious bug that has broken Dask, for instance. I do think patch releases shoudl only contain fixes but I think we should be generous and try to include any fixes that can be cleanly/easily applied, even if they were not strictly regressions. Users want alll fixes as fast as possible and do not care about these distinctions.

**Pull request merged**
