### PR TITLE
add option to disable wheel zoom on axes

### LINKED ISSUE #2427: Make axis wheel zoom configurable
This would be nice for figures where aspect is important, but zooming is also desired. Could either turn off the individual axis zoom interactions (so only scrolling in the figure will zoom), or "link" the zooming on the axis so that zooming on x moves the y axis as well.

### LINKED ISSUE #3125: Expose the wheel zoom speed in Python
The sensitivity of the wheel zoom cannot be configured on the Python side. However, there is a `speed` property which can be set on the JS side. It would be better to expose this property to the Python side too.

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #2427 fixes #3125
- [x] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
Also added wheel zoom speed option

**Comment by chilly-and-momo** [comment]
Was this implemented already? I'm trying to limit the wheel zoom to just the plot itself, and would like to disable the x and y axis zoom on the axis or canvas area outside the plot. I've looked through the current documentation on the bokeh user and reference guides, but haven't found an obvious solution.

**Comment by bryevdv** [comment]
@chilly-and-momo 

https://bokeh.pydata.org/en/latest/docs/reference/models/tools.html#bokeh.models.tools.WheelZoomTool.zoom_on_axis

Also, if you click on "Files Changed" above you can see where this property was added.

**Comment by chilly-and-momo** [comment]
Thank you so much!

**Pull request merged**
