### PR TITLE
Add streaming OHLC and MACD indicator example

### PR DESCRIPTION
**Pull request by bryevdv**
To run, execute: 
```
bokeh serve --show ohlc
```
In the `examples/app` directory.

Note: "ready" here indicates ready enough to go into a `dev6` release. 

screen shot 2015-12-28 at 10 54 01 am

### CODE REVIEW

**Comment by fpliger** [comment]
LGTM (tested pn py2 and py3). One note that is beyond this PR is that I was getting the following error:

```
  File "/Users/fpliger/dev/repos/bokeh/bokeh/util/tornado.py", line 41, in schedule
    return gen.multi([sleep_future, callback_future])
AttributeError: 'module' object has no attribute 'multi'
```

with tornado `4.2.1` and gets fixed with tornado `4.3`. Can open a separate PR or a quick commit in this PR with the fix if you need..

**Comment by bryevdv** [comment]
@havocp @fpliger what is the fix?

**Comment by havocp** [comment]
I guess either require 4.3 or copy paste gen.multi or do our own simple version. 

that isn't introduced by this pr though right - open an issue ?

**Comment by fpliger** [comment]
yeap. I'd just use require 4.3 and, correct, not introduced in this PR..

**Comment by bryevdv** [comment]
+1 for 4.3

**Comment by bryevdv** [comment]
Merging this as-is to go in a dev build tomorrow morning (more improvements possible later)

**Pull request merged**
