### PR TITLE
0.11.0 Documentation fixes and flake8

### PR DESCRIPTION
**Pull request by canavandl**
issues: fixes 3014

Three things:
- ~~Refactor examples and chart builders to use pandas.sort_values instead of deprecated pandas.sort~~
- Change BoxPlot docstring reference section (remove broken Wikipedia image link and replace with link)
- Remove extra line return in Donut docstring

### CODE REVIEW

**Comment by bryevdv** [comment]
I think the pandas change forces users to have  the very most recent pandas, which is too new for many people.  I think we will just have to live with the warnings for awhile.

**Comment by birdsarah** [comment]
if this is really 0.11.0 fixes - should it go into `docs_updates/0.11.0` and get deployed?

**Comment by canavandl** [comment]
that's fine

**Comment by birdsarah** [comment]
i'd love to get @bryevdv's thoughts on this as there's a bunch of non docs commits in here too.

**Comment by bryevdv** [comment]
`docs_updates/0.11.0` will be merged in to master fairly soon, I'm not sure it makes a difference either way unless the docs changes here are critical to re-deploy.

**Comment by canavandl** [comment]
These don't really change any doc content, only styling (and silences a ton of the sphinx build warns). They can probably be merged separately

**Comment by bryevdv** [comment]
@birdsarah @canavandl so this should just get merged to master?

**Comment by birdsarah** [comment]
Yes, master.

**Pull request merged**
