### PR TITLE
Fixes #3596: Warn on generating static HTML with Python callbacks

### LINKED ISSUE #3596: Warn about Python callbacks when they won't run
Document should track whether there are any on_change callbacks on the doc or on any model in the doc. If there are and you publish to a static format, we should issue some type of warning and perhaps suggest using JavaScript callbacks.

### PR DESCRIPTION
**Pull request by Karel-van-de-Plassche**
Thought the safest way to check this is on static HTML generation. Does not warn when generating JSON though, but don't think it is needed. You can test this functionality with this snippet:

``` python
from bokeh.io import curdoc, show
from bokeh.plotting import figure
from bokeh.models.widgets import Button
from bokeh.models import CustomJS
from bokeh.layouts import column
from bokeh.events import ButtonClick

from IPython import embed

# Create plot and buttons
plot = figure(plot_height=400, plot_width=400)
click_button = Button()
change_button = Button()
event_button = Button()
change_js_button = Button()
event_js_button = Button()

# Define callbacks
def handler(*args):
    print('Clicked!')

def handler2(attr, old, new):
    print('Clicked!')

js_handler = CustomJS(code='console.log("JS:Click")')

# Connect callbacks
click_button.on_click(handler)
change_button.on_change('clicks', handler2)
event_button.on_event(ButtonClick, handler)
change_js_button.js_on_click(js_handler)
event_js_button.js_on_event(ButtonClick, js_handler)

# Add to layout. Run with `bokeh serve` for no warnings, or run with python or `bokeh html` for warnings
layout = column(plot, click_button, change_button, event_button, change_js_button, event_js_button)
curdoc().add_root(layout)
show(layout)
```

- [x] issues: fixes #3596
- [x] tests added / passed

Was not sure where and if to put a test for this, not very familiar with selinium, but looking into it.

### CODE REVIEW

**Comment by bryevdv** [comment]
@Karel-van-de-Plassche looking at where `standalone_docs_json_and_render_items` is used:
```
grip standalone_docs_json_and_render_items
./embed/notebook.py:
   35 : from .util import check_one_model_or_doc, div_for_render_item, find_existing_docs, standalone_docs_json_and_render_items
   82 :         (docs_json, render_items) = standalone_docs_json_and_render_items([model])
./embed/standalone.py:
   40 :                    script_for_render_items, standalone_docs_json_and_render_items, wrap_in_onload, wrap_in_script_tag)
   79 :         (docs_json, render_items) = standalone_docs_json_and_render_items([model])
  211 :         (docs_json, render_items) = standalone_docs_json_and_render_items(models)
  279 :         (docs_json, render_items) = standalone_docs_json_and_render_items(models)
./embed/util.py:
  184 : def standalone_docs_json_and_render_items(models):
```
I do think that moving the check there would be appropriate, so that all standalone output generation would benefit. 

Do you think you can move this to `standalone_docs_json_and_render_items` in the near future?

**Comment by Karel-van-de-Plassche** [comment]
Sure, I can have another look at this tomorrow or Friday. Is the new build/test system in place? Then I can also have a go at making tests etc.

**Comment by bryevdv** [comment]
@Karel-van-de-Plassche great, FYI we are looking to cut a small release next week. We did just merge a PR that updated the BokehJS build, but I am not sure how that is relevant. I think this will only require a  Python side unit test in this file

https://github.com/bokeh/bokeh/blob/master/bokeh/embed/tests/test_util.py

you could add  a new `test_callback_warning` method to the (sadly currently empty) `Test_standalone_docs_json_and_render_items` class, that uses `caplog` to catch and check the warning. Let me know if I can provide other guidance.

**Comment by Karel-van-de-Plassche** [comment]
@bryevdv It might fit even better in `check_models_or_docs`. Of course its internal API, but maybe a docstring with the intention of these functions would be nice for future devs.

``` bash
./bokeh/embed/util.py:59:            def check_models_or_docs(models, allow_dict=False):
./bokeh/embed/util.py:93:            models = check_models_or_docs(model)
./bokeh/embed/util.py:188:           models = check_models_or_docs(models)
./bokeh/embed/standalone.py:40:      from .util import (check_models_or_docs, check_one_model_or_doc, div_for_render_item, find_existing_docs, html_page_for_render_items,
./bokeh/embed/standalone.py:199:     models = check_models_or_docs(models, allow_dict=True)
./bokeh/embed/standalone.py:277:     models = check_models_or_docs(models)
./bokeh/embed/tests/test_util.py:47: class Test_check_models_or_docs(object):
```

**Comment by Karel-van-de-Plassche** [comment]
@bryevdv I just used the message you typed, without explicit newlines though. Okay like this? Tests are also added.

**Comment by Karel-van-de-Plassche** [comment]
Whoops, apparently I cannot re-use models like this. Travis fails with: 

```
bokeh/tests/test_model.py:112: in <module>
    class SomeModel(Model):
bokeh/model.py:188: in __new__
    MetaModel.model_class_reverse_map[entry]))
E   Warning: Duplicate __view_model__ or __subtype__ declaration of 'SomeModel' for class SomeModel.  Previous definition: <class 'bokeh.embed.tests.test_util.SomeModel'>
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
```

@bryevdv How would you suggest keeping the tests non-dependent? Or shall I just use/import the definitions from the other test files?

**Comment by mattpap** [comment]
@Karel-van-de-Plassche, just rename the model to something else. Currently all models are under a single global namespace, despite belonging to different python modules.

**Comment by Karel-van-de-Plassche** [comment]
@mattpap Done, thanks. Just a note, I tested with `py.test -m "not examples and not selenium and not js"` put it still seems to run the selenium tests:

```
../../.conda/envs/bokeh-dev/lib/python3.6/site-packages/pytest_selenium/pytest_selenium.py:112: UsageError
____________________________________________________________________________ ERROR at setup of test_wheel_zoom_is_deselected_by_default ____________________________________________________________________________

request = <SubRequest 'driver_class' for <Function 'test_wheel_zoom_is_deselected_by_default'>>

    @pytest.fixture
    def driver_class(request):
        driver = request.config.getoption('driver')
        if driver is None:
>           raise pytest.UsageError('--driver must be specified')
E           _pytest.config.UsageError: --driver must be specified
```

**Comment by mattpap** [comment]
>  I tested with `py.test -m "not examples and not selenium and not js"` put it still seems to run the selenium tests:

`-m selenium` refers to unit tests (under `bokeh/`) that use selenium (e.g. export tests). Other tests that use selenium are integration tests, so `-m integration`. So you would have to add `not integration` to your command line. I usually just use `py.test bokeh/` to run bokeh's unit tests.

**Comment by Karel-van-de-Plassche** [comment]
Error in Python2.7, but think this is not on my end, but in `bokeh/util/callback_manager.py:31`
``` python
=================================== FAILURES ===================================
 Test_standalone_docs_json_and_render_items.test_log_warning_if_python_event_callback 
self = <bokeh.embed.tests.test_util.Test_standalone_docs_json_and_render_items object at 0x7f6f7a9a5950>
caplog = <_pytest.logging.LogCaptureFixture object at 0x7f6f7a9a57d0>
    def test_log_warning_if_python_event_callback(self, caplog):
        d = Document()
        m1 = EmbedTestUtilModel()
        c1 = _GoodEventCallback()
        d.add_root(m1)
    
>       m1.on_event('tap', c1)
bokeh/embed/tests/test_util.py:155: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = EmbedTestUtilModel(id='b0037dfa-87fa-48d7-82ea-df2b14d2aff4', ...)
event = 'tap'
callbacks = (<bokeh.embed.tests.test_util._GoodEventCallback object at 0x7f6f7a9a5d90>,)
    def on_event(self, event, *callbacks):
>       if not isinstance(event, str) and issubclass(event, Event):
E       TypeError: issubclass() arg 1 must be a class
bokeh/util/callback_manager.py:31: TypeError
```

**Comment by bryevdv** [comment]
@Karel-van-de-Plassche you might be right but let's not try to fix things that are out of scope. For now:

* use `events.Tap` instead of `"tap"` (this is what the other event tests in https://github.com/bokeh/bokeh/blob/master/bokeh/tests/test_events.py do)

* make a follow up issue to look into `on_event` with string names in python 2

**Comment by bryevdv** [comment]
@Karel-van-de-Plassche looks great, thanks for the PR!

**Pull request merged**
