### PR TITLE
tests (and fixes) for plot resizing

### PR DESCRIPTION
**Pull request by almarklein**
issues: continuation of #2949

This refactors the plot resize logic into a separate function, and adds tests to make sure that function does what it must do. And ahum, yeah ... there was a bug in the code causing the min_size not always be taken into account when resizing in both height and weight.

Also set plot default `min_size` to 120 (from 100), to at least show *some* plot, and not only ticks.

cc @bryevdv, @birdsarah

### CODE REVIEW

**Comment by bryevdv** [comment]
@birdsarah thank you for pushing on tests, some of us have habits to break. Please merge this when you are satisfied that it is ready.

**Comment by birdsarah** [comment]
Thanks for this @almarklein, i'm just taking a look.

In #2950 you noted
> it provides a way for code that embeds bokeh plots to control resize behavior.

That sounds awesomely useful.

Can we add a small example to examples to show this in action. Maybe under embed. There's already `/examples/embed/embed_multiple_responsive.py` that I threw in there to show off responsive plots. I would love to add some more to that to show this off. I'm happy to help / do this if you're busy.

**Comment by almarklein** [comment]
Good idea, will probably have a chance to do this over the weekend.

**Comment by almarklein** [comment]
Done. I also made some small changes to `embed_multiple_responsive.py`; it took me a while to understand the difference between the red and green plot.

While playing with this I realized that when the plot takes both available height and width into account, you *might* want it to *not* maintain aspect ratio ...

**Comment by almarklein** [comment]
Ok, I added the ability to *not* maintain aspect ratio. You can play with the example to see the different "modes".

**Comment by almarklein** [comment]
ping

**Comment by bryevdv** [comment]
@almarklein this is marked WIP, that's why I didn't look at it :) Is it ready?

**Comment by almarklein** [comment]
@bryevdv  my mistake, sorry! Yes, its ready from my end.

**Pull request merged**
