### PR TITLE
Improve hit_testing and selectors/inspectors

### LINKED ISSUE #1486: Add line hit testing and hover inspection along lines
The major missing piece is a `_hit_line` method on the renderers that can return the indices of glyphs that are "hit" by a line. The primary use-cases would be horizontal and vertical lines (e.g., crosshair type inspector tools), and beginning with just these cases would be acceptable. 

Once line hit testing is in place, there simply needs to be a tool that requests a hit test against a line, and then pops up the hover when appropriate. There are a few possible paths here:

* add hit-testing as an option to existing crosshair tool 
* add line hit-testing as an option to existing hover tool
* create new tool specifically for line hit testing

### PR DESCRIPTION
**Pull request by fpliger**
Issues: fixes #1486 

This outdates #2085 (that PR started before the big JS changes merged a couple of weeks ago. Codebase is way to different and #2085 is small enough to just start a new branch/PR as easiest path). 

Glyphs hit_test methods output is now a structure like:

```
result = {
        '0d': {
          # boolean flag to indicate if the glyph was hit or not
          flag: false,
          # index of the first point of the crossed segment
          indices: []},
        '1d': {
          # index of the closest point to the crossed segment
          # useful for special glypth like line that are continuous and
          # not discrete between 2 data points
          indices: []
        },
        '2d':{
          # arrays of indexes in case of multilines
          indices: []
        }
      }
```

in order to provide more information for selectors and inspector when deciding the selection behaviour, data to show, etc..

It also defines new attributes on the HoverTool to give more power to the user when deciding where to place the tooltips and the data to show. 

This PR also adds a new _hit_span to line glyph.

More information and old discussions can be found at #2085

### CODE REVIEW

**Comment by fpliger** [comment]
@bokeh/dev would be nice to have a quick feedback about the new design before reflecting this on all other glyphs. Right now only line and circle glyphs have the new design. 

Also, not all new policies on hover

```
    mode = Enum("point", "hline", "vline", help="""
    Whether to consider hover pointer as point (x/y values), or a
    span on h or v directions.
    """)
    hit_value_mode = Enum("snap_to_data", "glyph_center", "hit_interpolate", "mouse_point")
    point_policy = Enum("snap_to_data", "follow_mouse", "none")
    line_policy = Enum("prev", "next", "nearest", "interp", "none")
    conflict_policy = Enum("line", "point", "both")
```

are not fully developed yet. Also, I need to replace the old `Hover.snap_to_data`, `hit_value_mode`, etc with the new attributes listed above we have discussed on #2085 . 

@bryevdv can you give me a hand to remember some details as my memory fails a bit? To recap:

* `point_policy` and `line_policy` regulates where the hover tooltip position
* `conflict_policy`, honestly I'm not sure about this one anymore. Was it related to the case when used both point and line policies are enabled? If so I don't see the use cases for this situation.
* `mode` regulates the it the hover should create geometry as a point or a span

in this scenario `hit_value_mode` and `snap_to_data` are to be removed.

**Comment by bryevdv** [comment]
@fpliger Yes `conflict_policy` specifies what to do if hit testing (for a specific glyph) returns hits both on a line and on a point at the same time. Do you really want two tooltips in that case? Probably not.

**Comment by bryevdv** [comment]
Maybe names could be better: `point_mode`, `line_mode` and `conflict` ?

**Comment by fpliger** [comment]
I like `point_mode` and `line_mode` more too and agree on conflict.

Here's one thing I don't get:

> Yes conflict_policy specifies what to do if hit testing (for a specific glyph) returns hits both on a line and on a point at the same time.

are you talking about a HoverTool on a single glyph with both "point" and "*line" mode on? Or maybe you mean the same hover tool inspecting a `line` and a `circle` glyph?

**Comment by bryevdv** [comment]
@fpliger I think you are thinking that `line_mode` and `point_mode` apply to the lines and points of a glyph? They don't they apply to line and point *geometries*. Perhaps the missing piece is that we had talked about allowing the hover tool to hit on any combinations of `point`, `hline`, and `vline` at a time, not just one at a time. So `conflict` was meant to specify what happens if the tool is configure to hit using both a point geometry and a line geometry at the same time.

**Comment by bryevdv** [comment]
I also think the comment in the `1d` section is inaccurate. Only `0d` (i.e., line and patch) results have to deal with segments. `1d` results are just indices of hit discrete glyphs that were hit. The 10th circle, the 27th rect.

**Comment by fpliger** [comment]
After some conversation with @bryevdv here's a short summary to capture the thoughts we share about how this should be implemented:

`hit_*` functions return the new hash object that have 3 keys:

* 0d: this is only valid for line and patch glyphs. The value of this key is an object with:
  - flag: boolean whether the line or patch was hit or not
  - indexes: array with the [smallest] index of the segment of the line that was hit
* 1d: all other glyphs apart from multilines
* 2d: applies only to multilines. Return output is a hash where the keys are the indices of the lines being hit and the values are arrays of the indexes

line policy applies to lines and multilines glyph
point policy applies to everything else

Other changes are:

* `conflict_policy`, `snapt_to_data` and `hit_value_mode` go away
* rename `mode` to `mouse`
* the value shown on the tooltip (if interpolated or actual data) is to be defined in the tootip format string

**Comment by bryevdv** [comment]
would say `2d` also applies to `Patches` (i.e. multi-patch)

**Comment by bryevdv** [comment]
Oh, I did not mean to rename `mode` I meant rename `point` mode to `mouse`, i.e.:
```
mode = Enum('mouse', 'hspan', 'vspan')
```

**Comment by fpliger** [comment]
> Oh, I did not mean to rename mode I meant rename point mode to mouse

LOL, right. It makes a lot more sense! Fever ways raising when I wrote it :-)

**Comment by fpliger** [comment]
@bryevdv as we have expected as soon as I restarted working on this I came across the case for why we though about `conflict_policy`. See the 2 attachments. They are showing many values on the tooltip because the span line is hitting the glyph on multiple points/segments. 

screen shot 2015-04-15 at 14 10 41

screen shot 2015-04-15 at 14 09 56

I'm not sure why we proposed `point` or `line` as values.

This can be a bit tricky to get "right" because the tooltip for each renderer is only one. I'm leaving this for discussion for now and will move ahead with all the _hit_* functions on the other glyphs.

**Comment by bryevdv** [comment]
@fpliger that is a different issue. That reveals the need for a "higher level" tooltip manager at the plot level that can determine what to do when there are multiple hits potentially across multiple glyphs. It would rate-limit and visually dodge hover tooltips. We should not worry about that in this work tho.

**Comment by bryevdv** [comment]
I think we had possibly discussed hit testing lines by also hit testing the points in the line (and not just the segments). In that context, a conflict policy would make sense, but I think fir now we just hit test segments, then there will be no potential conflicts when hit-testing lines.

**Comment by fpliger** [comment]
:+1:

**Comment by fpliger** [comment]
@bryevdv I've changed selectors (SelectionManager, Selector and GlyphRendererView) to reflect our discussions. Well, kind of.. because instead of passing the selector to the source on SelectionManager I've passed the new hit_test hash object result (manipulated by the selector to handle shift key). Actually, althought it's similar to previous approach I don't think it works well because it handles "append selection" when you hold shift key but not having a `selection` object on the SelectionManager level generates the issue we noticed on Scatter plots where only selection on one of the renderers actually work. Without historical knowledge on this I'd say that having a "selection" object on the SelectionManager would actually be a better choice.

Would you take a look and give your opinion?

**Comment by bryevdv** [comment]
Selections are intimately associated with data sources. The indices are indices into a *specific* set of columns, and are meaningliess/inapplicable in the context of any other set of columns (because any other source's columns are not at all guaranteed to have the same length, just to start) I don't see how we can get away with associating selections directly with sources. If there is a problem causing selection not to work with multiple renderers in some way, that's just a bug we should fix.

**Comment by fpliger** [comment]
Right. I didn't even imagine removing selection association from the sources. What I mean is that SelectionManager (that pass selections to sources) get's selections from renderers separately so if you have more the one renderer only one of the selections across renderers "win". It's a know bug (need to search for the related issue).

**Comment by bryevdv** [comment]
Ah, yes there probably needs to be some mediation/aggregation among renderers that share a data source, and the selection manager is probably the place to do it

**Comment by fpliger** [comment]
It should be ready for review. Tested most of the selections examples, OpenUrl action and DataTable widget. 
Also, tooltips (also new lines tooltip) seem to be working ok.

Better to have others to test it before merging as it changes selection on many places and I may have overlooked it somewhere...

**Pull request merged**
