### PR TITLE
update all the responsive modes

### LINKED ISSUE #4396: API - Name the responsive modes.
There are currently 5 modes: `fixed`, `box`, `width_ar`, `height_ar`, `box_ar`

@havocp @almarklein @bryevdv have all mentioned concerns with these being non-obvious.

To recap what these modes do:
* fixed - the plot is just the size of the specified width & height
* box - the plot fills the available size in it's box - causing the plot to stretch & squeeze however
*  width_ar - the plot fills the available width but maintains the aspect ratio (calculated from the specified width and height)
* height_ar - the plot fills the available height - but maintains the aspect ratio (calculated from the specified width and height)
* box_ar - the plot fills the available height or width while maintaining the aspect ratio (calculated from the specified width and height)

I would greatly appreciate naming suggestions from @bokeh/dev.

Secondly these modes are passed into the `responsive` parameter of any Layout object. Is that the right parameter name. In 0.11 we have `responsive=True/False` on Plot. I have kept and expanded this, but we don't have to keep this. We could have, for example, `mode` on the layout objects Row, Column. I think responsive is a good parameter, but just wanted to bring it up.

### PR DESCRIPTION
**Pull request by bryevdv**
issues: fixes #4396

ping @birdsarah could use some help verifying this set of change is complete, etc.

### CODE REVIEW

**Comment by bryevdv** [comment]
E.g. not sure if this also needs updating:
```
$ grin bk-layout-box 
./less/continuum.less:
  343 : .bk-toolbar-box.bk-layout-box .bk-toolbar-right {
```

**Comment by bryevdv** [comment]
OK, I am now pretty confident that all the changes that are in the PR are ones that should be there. Could use help with the converse: has anything been missed?

**Comment by mattpap** [comment]
Looking at this, I would change `responsive` to something more appropriate, e.g. `sizing_mode`.

**Comment by bryevdv** [comment]
I do think that the name "responsive" seems a bit more like a boolean flag. I don't have super strong feelings about that except that it might be hard to change correctly with confidence. Thoughts @bokeh/dev ?

**Comment by mattpap** [comment]
> except that it might be hard to change correctly with confidence

That's actually a good reason to change it now to something unique, because later on it will be even harder to distinguish from other uses.

**Comment by bryevdv** [comment]
@birdsarah any thoughts?

**Comment by birdsarah** [comment]
I like `sizing_mode`, or `responsive_mode` when writing about the new layout stuff, I have been using the word mode a lot so this feels right. I think `sizing` is probably less jargon-y than `responsive` so happy to go with that.

**Comment by birdsarah** [comment]
I like `sizing_mode`, or `responsive_mode` when writing about the new layout stuff, I have been using the word mode a lot so this feels right. I think `sizing` is probably less jargon-y than `responsive` so happy to go with that.

**Comment by bryevdv** [comment]
OK I will update to `sizing_mode` this afternoon and get this merged.

**Comment by birdsarah** [comment]
If we go with sizing_mode we'll need to deprecate `responsive` and also decide if we want to keep a True/False shortcut (I would vote for no in the short-term) until it becomes clear that there are preferred modes.

**Comment by birdsarah** [comment]
Thanks for tackling this Bryan and for everyone else contributing - it needed fresh eyes.

**Comment by bryevdv** [comment]
Yes, I would say no to `True`/`False` for `sizing_mode`, but keep the deprecation on `responsive`

**Comment by bryevdv** [comment]
OK, changing "responsive" is going to be a bit of a task. I'd like to merge this, and do that separately.

**Comment by bryevdv** [comment]
@bokeh/dev any objections to the plan for separate PRs?

**Comment by birdsarah** [comment]
No!

**Comment by birdsarah** [comment]
I never really liked stretch, and just had a mini-revelation: what about `fill_both` instead of `stretch_both`. To my mind, `fill` seems intentional, but `stretch` sounds bad. 

The correlating `fill_width` and `fill_height` would also still be correct names if we ever decide to implement them.

**Comment by bryevdv** [comment]
after more discussion in issue, decided to keep "stretch". Merging.

**Pull request merged**
