### PR TITLE
Add support for multi-gesture tools

### PR DESCRIPTION
**Pull request by philippjfr**
All the current tools in bokeh are tied to a particular gesture, e.g. pan, box_zoom, box_select all make use of the pan gesture, however more complex tools like the draw tools suggested in (https://github.com/bokeh/bokeh/issues/6370) will require responding to multiple gestures to work effectively. This PR makes it possible to create a multi tool by declaring multiple ``event_types`` as an array rather than a single string. The tool will appear in its own section of the the toolbar and toggle all other tools sharing one of the same event types as inactive when it is activated.

In the example below I've added a few multi-tools (currently they don't have their own distinct icons), and have activated the pan and tap tools. When I select a multi-tool (the one with the lasso icon) which uses the ``pan`` and  ``tap`` events, both other tools are deactivated, and when I do the inverse and select pan and tap tools the multi-tool is also inactivated:

multi_tool

This PR simply provides the support for adding multi-gesture tools but does not yet add any concrete instance of such a tool. I'm therefore not quite sure how best to test this yet. Also let me know if you want any documentation entries for this. Hopefully this will allow us to eventually merge such tools back into bokeh (if deemed general enough). 

- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by philippjfr** [comment]
I'll look into those test errors.

**Comment by mattpap** [comment]
> I'll look into those test errors.

@philippjfr, https://github.com/bokeh/bokeh/pull/7143#issuecomment-341270563.

**Comment by philippjfr** [comment]
Ah, great thanks!

**Comment by philippjfr** [comment]
@bryevdv What would it take for you to be happy to merge this? I still haven't worked out a good way to test it without a concrete multi-gesture tool implementation in bokeh itself, but it would be really nice if we didn't need to rely on a custom bokeh build for the continued development of the draw tools.

**Comment by bryevdv** [comment]
> I still haven't worked out a good way to test it without a concrete multi-gesture tool implementation in bokeh itself

Unit tests on `UIEvent` seem feasible? Also you could define a multi-tool in the test to test with? It doesn't have to be in BokehJS itself.

**Comment by philippjfr** [comment]
Sounds good, I'll get on that today.

**Comment by philippjfr** [comment]
Just added some unit tests which define a multi-gesture tool and test that other tools are toggled active and inactive correctly. I'm not entirely sure what you mean by adding ``UIEvent`` tests for this.

**Comment by bryevdv** [comment]
> I'm not entirely sure what you mean by adding UIEvent tests for this.

`register_tool` does different things if the parameter are lists vs strings, etc. Suggesting a unit test to cover the different cases.

**Comment by philippjfr** [comment]
Got you, doing that now.

**Comment by philippjfr** [comment]
Okay, I've now added a unit test that checks that multi-gesture tools receive all the gesture events they subscribe to.

**Comment by philippjfr** [comment]
Thanks @bryevdv!

**Pull request merged**
