### PR TITLE
remove cruft related to old AR implementation

### PR DESCRIPTION
**Pull request by bryevdv**

### CODE REVIEW

**Comment by bryevdv** [comment]
ping @bokeh/core

**Comment by damianavila** [comment]
:+1: I have already removed the test dependency in other [PR](https://github.com/bokeh/bokeh/commit/789cd31629f51c1ef2a7a47e3230fed789b5c866), so LGTM...

**Comment by damianavila** [comment]
TravisCI failed, but does not seems related with these changes (unless I am missing something)

**Comment by bryevdv** [comment]
No I think it was spurious, test restarted.

**Comment by birdsarah** [comment]
LGTM too. (haven't run anything locally)

**Comment by birdsarah** [comment]
I think we should also remove ServerDataSource from bokeh.models.sources (you've already removed the test for it and the coffeescript model)

**Comment by bryevdv** [comment]
good catch @birdsarah

**Comment by bryevdv** [comment]
Will merge when tests pass.

**Pull request merged**
