### PR TITLE
Remove deprecations from 0.12.7

### PR DESCRIPTION
**Pull request by mattpap**

### CODE REVIEW

**Comment by mattpap** [comment]
@bryevdv, there are still multiple references to `autoload_server()` in the docs.

**Comment by bryevdv** [comment]
I'll fix them up in this branch today or tomorrow

**Comment by bryevdv** [comment]
Been sick the last two days will try to finish and merge tonight

**Comment by mattpap** [comment]
I created #7434 for the docs.

**Comment by bryevdv** [comment]
I was working on the branch right now, now I'll have to cherry pick commits

**Pull request merged**
