### PR TITLE
Apply bokeh CSS more selectively to avoid conflicts

### LINKED ISSUE #8680: Custom Widget in doc strange display in 1.1.0dev6
I was looking at custom examples in doc for version 1.1.0
https://bokeh.pydata.org/en/dev/docs/user_guide/extensions_gallery/

and I noticed some difference in the Custom Widget example : 
 - 1.0.4 :
 
image

 - 1.1.0dev6 :

image

### PR DESCRIPTION
**Pull request by mattpap**
image

fixes #8680

### CODE REVIEW

**Comment by mattpap** [comment]
@philippjfr, if you have a chance, please test this with your code.

**Comment by philippjfr** [comment]
@mattpap I can confirm that HTML inside ``Div`` models now renders as expected, e.g. here's a list:

Screen Shot 2019-03-30 at 6 54 28 PM

**Comment by mattpap** [comment]
@philippjfr, OK. Finally a solution that universally works, though not ideal. CSS' specificity rules (among other things) are just beyond reason.

**Comment by philippjfr** [comment]
Great, there's only so much you can do, and this seems eminently reasonable.

**Pull request merged**
