### PR TITLE
Bump min sphinx version

### LINKED ISSUE #11792: Unpin Sphinx and update min version
The issue causing the breakage with Python 3.7 will be fixed when Sphinx 4.3.1 is released. We should update the min Sphinx version to 4.3.1 and unpin at that time. (I don't think it is worth back-porting)

* ref: https://github.com/sphinx-doc/sphinx/pull/9840

cc @tcmetzger

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #11792

### CODE REVIEW

**Comment by bryevdv** [comment]
OK this actually turned into a bit of a to-do. CI picked out Sphinx 4.4 which gets extra unhappy about "ambiguous" cross-references, but I discovered Sphinx 4.4 restores the ability for parallel builds on OSX (cc @tcmetzger) so it was personally imperative to get 4.4 working in order to same a *lot* of time on local builds. Notes:

* I consolidated the color classes all in `color.py` to fix the ambiguous "RGB" The code footprint here is so small that one module is fine. 
* Had to fully qualify the annotations for JSON in other places.

**Comment by bryevdv** [comment]
As an aside, I'd kind of like to remove all use of `ABCMeta` in the codebase. We apply it completely haphazardly and I don't think it really buys us anything.

**Comment by mattpap** [comment]
> Had to fully qualify the annotations for JSON in other places.

Why? Unless there's a very good reason for this and this is explained in the code, it's very likely I will be tempted to remove this next time I see this. What are the exact conditions we will need to to that instead the unqualified variant?

**Comment by bryevdv** [comment]
@mattpap Abput 800 copies of this warning (reported as error with `-W`)

> /Users/bryan/work/bokeh/bokeh/models/widgets/markups.py:docstring of bokeh.core.has_props.HasProps.set_from_json:: WARNING: more than one target found for cross-reference 'JSON': bokeh.command.subcommands.json.JSON, bokeh.core.properties.JSON, bokeh.core.property.json.JSON

I'll add a comment but i am not sinking more time in to this (I spent almost half a day getting the docs build building again aleady)

**Pull request merged**
