### PR TITLE
accept None as a placeholder for empty cells in a grid plot

### LINKED ISSUE #1635: implement blaze/remote data source to support streaming data in plots
## Blaze Server
currently implemented in this repository:  https://github.com/ContinuumIO/multiuserblazeserver
- [x] create skeleton of multiuser blaze server which mimics existing blaze server functionality
- [x] add authentication hooks to endpoints for multi user blaze server
- [x] add single user auth backend for blaze server (true multiuser backend can be done later)
- [x] add upload endpoint for blaze server, which will store data in the data directory/username
- [x] add configuration endpoint to set kwargs for blaze.resource call
- [x] create blaze server dataset catalog dictionary which unifies script loaded blaze tables with uploaded blaze tables
- [ ] add append endpoint for blaze server (only for hdfstore, bcolz, and csv file formats).  We might want to support a general update endpoint later - however that is a bit harder.  Individuals can always update the files manually on the file system anyways (postponed)
  
## Bokeh Server
-  [x] incorporate blaze blueprint in bokeh server
-  [ ] add abstract rendering endpoint (currently, the get_data function) (in progress)
  - [x] add ar_downsample functions
  - [x] line_downsample
  - [ ] image downsample

## Bokeh
- [ ] add blaze server data source (there is some code in https://github.com/bokeh/bokeh/tree/bamboo)

### LINKED ISSUE #1636: GridPlot should accept None for empty positions
Should be able to write:
```
GridPlot(Children=[a, b, c], [d, None, f])
```

### PR DESCRIPTION
**Pull request by bryevdv**
issues: fixes #1636

ping  @tr8dr also note `None` will work in grid plots in 0.7.1

### CODE REVIEW

**Comment by damianavila** [comment]
Code looks good, but the example don't... I mean, maybe is better to show the "None" capability in another way... in the current state the example seems broken although there is no problem... I am talking about a "visual" concern... 

2015-01-08-102315_1366x768_scrot

**Comment by bryevdv** [comment]
That's the desired output I am not sure what else would be done? Maybe make the plots smaller so the example is not so wide is that what you mean?

**Comment by bryevdv** [comment]
Actually best option put two grid plots on a vbox one with Nones other without.

**Comment by damianavila** [comment]
>Maybe make the plots smaller so the example is not so wide is that what you mean?

That's an option...

>Actually best option put two grid plots on a vbox one with Nones other without.

And this is probably a better option... but any of them is enough, I think...

**Comment by bryevdv** [comment]
@damianavila OK I did both :)

**Comment by damianavila** [comment]
OK... now it looks better ;-) Waiting for TravisCI for the merge...

**Comment by mattpap** [comment]
Was this tested with row/column full of `None`s?

**Comment by bryevdv** [comment]
No. Columns display fine, empty rows are not visible. Maybe not the most common use-case, can address is a follow-up issue.

**Comment by damianavila** [comment]
`p = gridplot([[l, None, aw], [None, None, None]])` is working for me but not `p = gridplot([[None, None, None], [bez, q, None]])`

**Comment by damianavila** [comment]
and here the pics for completeness....

`p = gridplot([[l, None, aw], [None, None, None]])`

2015-01-08-133546_1366x768_scrot

`p = gridplot([[None, None, None], [bez, q, None]])`

2015-01-08-133618_1366x768_scrot

Missing `bez` in the last one...

**Comment by bryevdv** [comment]
OK that's unexpected...

**Comment by bryevdv** [comment]
So, it works without the empty row (i.e., `p = gridplot([[bez, q, None]])`) Again I think a row of `None` will be an unusual case, so I would suggest merging this as-is, with an issue that describes the problems with empty rows to be addressed later.

**Comment by mattpap** [comment]
Unusual, yes, but users to a lot of unusual stuff and then flood mailing lists with questions. Anyway, this can be addressed under #1647 umbrella.

**Comment by damianavila** [comment]
> Again I think a row of None will be an unusual case, so I would suggest merging this as-is, with an issue that describes the problems with empty rows to be addressed later.

a row of None almost make no sense... so I agree with the path you mentioned

**Comment by bryevdv** [comment]
@mattpap oh I'd never make a prediction that *no-one* would ever try it, but I don't think we will get  flood over just this one particular issue, and if we do, we can point them at the GH issue.

**Comment by mattpap** [comment]
I was making a generic point with this "flooding".

**Comment by damianavila** [comment]
OK, I will merge this one as is an open an issue describing the problem... if @mattpap wants to take it under the #1647 umbrella, it is ok, because that issue will be probably splitted in several subtasks with an associated issue... so one more mark in the tiger (popular phrase here but I don't know if it is popular there too :wink:)...

**Comment by damianavila** [comment]
well... and @bryevdv beat me whereas I was writing... jeje... so forget what I said...

**Pull request merged**
