### PR TITLE
WIP Fix for conda build

### PR DESCRIPTION
**Pull request by tswicegood**

### CODE REVIEW

**Comment by bryevdv** [comment]
@tswicegood is this test PR still needed?

**Comment by damianavila** [comment]
AFAIK, some fix hit master... but @tswicegood probably get a better idea when it would be available the next release.

**Comment by tswicegood** [comment]
@bryevdv / @damianavila: you guys can merge this back in once to be on the latest conda if this next one passes.  Conda 3.8.1 should fix the issue you were having that required the older version of conda.

**Comment by damianavila** [comment]
@tswicegood, can you remove the debugging `conda info` and `conda list`? Our output is very verbose so far, so I would like to avoid adding more lines...

**Comment by damianavila** [comment]
OK, gonna merge this one and open another PR to remove the additional lines.
Thanks @tswicegood for the research (and fix) into the problem!

**Pull request merged**
