### PR TITLE
Fix units in blackbody example

### LINKED ISSUE #12533: [BUG] Units in blackbody example should be upright
### Software versions

.

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

.

### Observed behavior

.

### Example code

```Python
.
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by zmoon**
- [x] issues: fixes #12533 
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by zmoon** [comment]
image

**Comment by bryevdv** [comment]
what about 
```
\text{W} / (\text{m}^2 \cdot \text{sr} \cdot \text{Hz})
``` 
instead?

**Comment by zmoon** [comment]
Yeah that would be ok too. Though a bit uglier due to the surrounding parens IMHO. Could change to square brackets.

$[10^{-9} \ \text{W} / (\text{m}^2 \cdot \text{sr} \cdot \text{Hz})]$

**Comment by bryevdv** [comment]
@zmoon yes that looks good to me

**Comment by bryevdv** [comment]
@zmoon I'm happy with either, I leave it to you (but use square brackets on both axes if go that route)

**Comment by zmoon** [comment]
image

**Comment by bryevdv** [comment]
Thanks @zmoon I will merge when green (modulo a flaky integration test job we have not fixed yet)

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
Thanks @zmoon !

**Comment by zmoon** [comment]
Thanks for the cool and pretty example!

**Comment by zmoon** [comment]
> There's a bokehjs variant of this example that should have been updated as well.

Sorry, I can do it another PR if you want

**Comment by bryevdv** [comment]
> There's a bokehjs variant of this example that should have been updated as well.

Let's say "could have been" in these situations. 

The JS and Python examples are ultimately, separate concerns, and any number of factors (time, expertise, interest, or knowledge of) might prevent an update from happening to both in one PR.

**Pull request merged**
