### PR TITLE
Allow `SaveTool` to work with any layouts

### LINKED ISSUE #8531: Save tool in gridplot initiates multiple downloads
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh 1.0.3
Python 3.5

#### Description of expected behavior and the observed behavior

Clicking 'save' tool on `gridplot()` downloads each subplot separately. Preferably, if the tools are merged, so would the plots be merged into a single image.

#### Complete, minimal, self-contained example code that reproduces the issue

```py
import numpy as np
from bokeh.io import show
from bokeh.layouts import gridplot
from bokeh.plotting import figure


plots = []
for i in range(10):
    p = figure(plot_height=70,
               tools='save')
    p.line(np.arange(10), np.random.random(10))
    plots.append(p)

p = gridplot(plots, ncols=1)
show(p)


```
#### Screenshots or screencasts of the bug in action
screenshot_2019-01-01_05-02-18

### PR DESCRIPTION
**Pull request by mattpap**
fixes #8531

### CODE REVIEW

**Comment by mattpap** [comment]
> `sphinx.errors.ExtensionError: Handler <function _process_docstring at 0x7fb3ba4ab550> for event 'autodoc-process-docstring' threw an exception (exception: pop from an empty deque)`

It would be nice if someone could tell me what file sphinx fails on?

**Comment by bryevdv** [comment]
@mattpap can you repro this locally? Then you could run with `make ... SPHINXOPTS=-v` (or `-vv`) which might have the details you are looking for.

**Comment by mattpap** [comment]
That doesn't help (usually it doesn't). For now I pinned sphinx in PR #12265, as all PRs are currently failing like this.

**Comment by mattpap** [comment]
Good enough for now. I still need to allow users to simply configure grid toolbars as any other.

**Pull request merged**
