### PR TITLE
load BokehJS resources from https

### LINKED ISSUE #2659: Bokeh CDN doesn't support HTTPS
I just uploaded a plot rendered with `output_file('plot.html', mode='cdn')` to an HTTPS-enabled website. But the plot doesn't show up in Chrome and Firefox. Here is the error message in Chrome:
> Mixed Content: The page at '……/plot.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://cdn.pydata.org/bokeh/release/bokeh-0.9.1.min.css'. This request has been blocked; the content must be served over HTTPS.

and in Firefox:
> Blocked loading mixed active content "http://cdn.pydata.org/bokeh/release/bokeh-0.9.1.min.css"1 simple-plot-one.html

Please add support for HTTPS. Many websites have enabled HTTPS and HTTPS can't be selectively disabled for some pages.

### PR DESCRIPTION
**Pull request by bryevdv**
issues: fixes #2659

### CODE REVIEW

**Comment by bryevdv** [comment]
@bokeh/dev please review, this would be good to get into the next deb build

**Comment by guillochon** [comment]
Thanks @bryevdv! Indeed this change gets Bokeh working for me in my secure environment.

**Comment by bryevdv** [comment]
Awesome!

**Comment by bryevdv** [comment]
@damianavila I'd like to get this in at least one dev build before the release.

**Comment by bryevdv** [comment]
@bokeh/dev I plan to merge this in a few hours without objection.

**Comment by bryevdv** [comment]
No objections, merging now.

**Pull request merged**
