### PR TITLE
Fixed xwheel and xzoom tools with hard bounds (#11832)

### PR DESCRIPTION
**Pull request by florentbr**
This PR fixes issue #11832  where single axe zooming was failing if a hard bounds is set on the other axe.
With this change, the zoom operation is no longer canceled if the range equal the bound.

### CODE REVIEW

**Comment by mattpap** [comment]
This will require at least an integration test under `bokehjs/test/integration/regressions.ts`.

**Comment by florentbr** [comment]
I don't have the environemt to write/execute the regression tests, but this is what i got so far by taking example on the unit tests :
```javascript

import {ZoomInTool} from "@bokehjs/models/tools/actions/zoom_in_tool"

describe("in issue #11832", () => {
  it("should x-zoom the x-axis when the y-axis is bounded", async () => {
    const zoom_in_tool = new ZoomInTool({dimensions: "width"})

    const p = fig()
    p.add_tools(zoom_in_tool)
    p.line([0, 1], [0, 0])

    p.y_range.start, p.y_range.end = p.y_range.bounds = (-1, 1)

    const {view} = await display(p)

    const zoom_in_tool_view = view.tool_views.get(zoom_in_tool)
    zoom_in_tool_view.doit()

    const hr = view.frame.x_range
    expect([hr.start, hr.end]).to.be.equal([-0.9, 0.9])

    const vr = view.frame.y_range
    expect([vr.start, vr.end]).to.be.equal([-1.0, 1.0])
  })
})
```

**Comment by bryevdv** [comment]
@florentbr seems plausible, why don't you add it and we'll see how CI goes. That said if you want to set up a dev env, there are instructions here:

https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html

and then running these tests is `node make test:integration` in the bokehjs dir.

Hopefully in a few months there will be a simpler docker-based option for dev environments.

**Comment by florentbr** [comment]
@bryevdv, I don't want to mess with my current setup, so I'm not going to install the dev env required for this project.
I managed to commit a working regression test for this PR but the baseline images are missing.
How do I access the images generated by the CI server ?

**Comment by ianthomas23** [comment]
@florentbr The instructions on how to access the CI baseline images are at https://docs.bokeh.org/en/latest/docs/dev_guide/writing_tests.html. You should read the "BokehJS visual tests" section 3 "Generate CI baselines and commit test".

**Comment by ianthomas23** [comment]
My apologies! There are separate github action workflows for Bokeh-CI and BokehJS-CI. You want the latter. In your case this is https://github.com/bokeh/bokeh/actions/runs/1515327106 with the artifact down at the bottom of the page.

**Comment by florentbr** [comment]
@ianthomas23, thanks, I indeed missed the second workflow.

**Comment by bryevdv** [comment]
OK the one failing test is a spurious conda issue, I will ignore it.  I did want to mention the proximate cause for the issue here is this check at the bottom:
```
    if (scrolling && hit_bound && maintain_focus)
      return
```
Semantically that check should only apply to a "2d" wheel zoom in the center of the plot, but we are also applying it to this case because the zoom base tool view explicitly sets
```
this.plot_view.update_range(zoom_info, {scrolling: true, maintain_focus: this.model.maintain_focus})
```
I think setting `scrolling` to true there was maybe a hack to get bounds checking at all on this code path. Ideally this would be cleaned up some with more meaningful flags or something. But that's a wider concern unrelated to this issue, and I think the change here is also reasonable and advised on its own, so I will go ahead and merge this concrete fix now.

**Comment by florentbr** [comment]
@bryevdv, thanks for the follow up. I took another look at the code.
I think that the `scrolling` argument is not really the root cause of the issue.
I'd say it's because of `this.model.maintain_focus` argument which is set to `True` by default.
I didn't pay attention given its inexplicit naming, but this option restricts the aspect ratio.
The `xzoom` and `xscroll` tools are configured to zoom a single axis, but but at the same time it also locks the aspect ratio by default with `maintain_focus = True`, which doesn't make sense.

A better fix would be to force `maintain_focus` to `False` if the tool is meant to zoom a single axis:

```patch
--- a/bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts
+++ b/bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts
@@ -16,8 +16,11 @@ export abstract class ZoomBaseToolView extends ActionToolView {

     const zoom_info = scale_range(frame, this.model.sign*this.model.factor, h_axis, v_axis)

+    // lift restriction on aspect ratio if the scrolling is on a single axis
+    const maintain_focus = this.model.maintain_focus && dims == "both"
+
     this.plot_view.state.push("zoom_out", {range: zoom_info})
-    this.plot_view.update_range(zoom_info, {scrolling: true, maintain_focus: this.model.maintain_focus})
+    this.plot_view.update_range(zoom_info, {scrolling: true, maintain_focus: maintain_focus})
```

```patch
--- a/bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
+++ b/bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
@@ -46,8 +46,10 @@ export class WheelZoomToolView extends GestureToolView {

     this.plot_view.state.push("wheel_zoom", {range: zoom_info})

-    const {maintain_focus} = this.model
-    this.plot_view.update_range(zoom_info, {scrolling: true, maintain_focus})
+    // lift restriction on aspect ratio if the scrolling is on a single axis
+    const maintain_focus = this.model.maintain_focus && dims == "both"
+
+    this.plot_view.update_range(zoom_info, {scrolling: true, maintain_focus: maintain_focus})
```

Is it possible to revert this PR so I can better fix it ?

**Comment by bryevdv** [comment]
> I think that the scrolling argument is not really the root cause of the issue.

Well I said proximate cause, not root cause. I.e. if `scrolling` were false the condition would fail right there, and the premature exit would thus be prevented right there. It's true that another proximate cause here is `maintain_focus` being true. 

If you want to work on improving these codepaths, I won't discourage you! However, I do think a proper solution is more involved than the proposal above. Silently and implicitly changing or ignoring one property value means that the properties are not actually orthogonal / independent of one another as they should be. So there's definitely a code smell here, but the fix above is just a bandaid for it. Really improving this would involve decomposing the properties on the base differently so that all available combinations actually make sense together.  FWIW we are coming up on a new major release in the coming months, so now would be the time to make that sort of API change. 

> Is it possible to revert this PR so I can better fix it ?

That's usually a pain, and can cause headaches if you ever later want to cherry-pick any of the reverted commits. There's really no need, a new PR can just be submitted against the current HEAD as it is. But even more, as I said I think the change to the inequalities is a good one to make, regardless, so there is no reason to revert.

**Comment by bryevdv** [comment]
I should also note that I don't think this interpretation:

> But at the same time it also locks the aspect ratio by default with maintain_focus = True, which doesn't make sense.

is quite correct. `maintain_focus` does not lock the aspect ratio. It makes it so that if *any* bound is hit, then all zooming stops (even if other bounds still "have room"). The original purpose of that was to ensure that scroll zooming would always stay centered under the mouse cursor. i'm not entirely sure if it is even necessary for these non-scroll tools that have a `maintain_focus` option at all. So we could also consider just dropping the property and hard-coding the value to to false in the function call. But we'd need to do a little historical research to make sure I am not forgetting a good reason for these tools to have `maintain_focus` property.

**Comment by florentbr** [comment]
@bryevdv 

> I should also note that I don't think this interpretation: ... is quite correct.

You are right, I wrongly assumed that `maintain_focus` was to lock the aspect ratio since the doc mentions that it can causes aspect ratio to change and somehow all my troubles with the `xzoom` tool diseapeared as soon as I turned off this option.

> So we could also consider just dropping the property altogether on these tools, and hard-coding the value to to false in the function call.

I don't even see the usefullness of stopping the zooming on a hard bond whether it's with a zoom or scroll tool. So maby not remove it since it's there for a reason, but at least set it to `False` by default.

> However, I do think a proper solution is more involved than the proposal above. Silently and implicitly changing or ignoring one ...5

I agree, as you mentionened a proper solution means breaking the current API. I'm not familliar enough with this project to propose structural changes, so I'll leave this PR as it is.

**Pull request merged**
