### PR TITLE
Feature/multiuser applet support

### PR DESCRIPTION
**Pull request by hhuuggoo**

### CODE REVIEW

**Comment by hhuuggoo** [comment]
@bryevdv please review

**Comment by bryevdv** [comment]
LGTM as far as I can tell, if you have any specific questions I may need more context.

**Comment by damianavila** [comment]
>LGTM as far as I can tell, if you have any specific questions I may need more context.

I said the same, as far as I can tell, looks good. Also the documentation is really great to understand how this was thought...

**Comment by damianavila** [comment]
> if you have any specific questions I may need more context.

@hhuuggoo

**Pull request merged**
