### PR TITLE
Observe changes to offset parent and relayout

### LINKED ISSUE #8655: Loading plot in separate JupyterLab tab collapses layout
As I originally outlined in https://github.com/bokeh/bokeh/issues/8084 since the layout PR you can get into situation where a layout collapses completely when reloading a notebook window. Since then I've further narrowed it down, and figured out that this only occurs in JupyterLab when the plot is in a different tab than the current one being displayed.

Here is a screencast demonstrating the issue, in it I have two notebooks open each with a bokeh layout. When I reload the notebook (by refreshing the page) the layout of widgets in the second notebook, which is not visible during the reload, collapses.

screencast_jlab

My guess is that this occurs because non-active JupyterLab tabs render but do not correctly report their size. I'm not really sure if this will be an easy thing to fix and it may have to happen in the JupyterLab extension telling bokeh to rerender the plots in the newly activated tabs.

### PR DESCRIPTION
**Pull request by mattpap**
This fixes the problem universally (not only in jupyter). This doesn't affect performance (computing `offsetParent` is cheap, compared to other DOM APIs).

fixes #8655

### CODE REVIEW

**Comment by bryevdv** [comment]
> This doesn't affect performance (computing `offsetParent` is cheap, compared to other DOM APIs).

@mattpap can you provide an updated ETA on the performance work?  Other projects depending on it are starting to be exposed to schedule risk

**Comment by philippjfr** [comment]
Just wanted to confirm that this indeed fixes the issue I reported in #8655 for me.

**Comment by bryevdv** [comment]
@philippjfr thanks for testing things out (hopefully we can make some automated notebook testing a priority later this year)

**Comment by mattpap** [comment]
> can you provide an updated ETA on the performance work?

@bryevdv, tomorrow. I think I finally figured out all the details, I just need to finish the implementation.

**Pull request merged**
