### PR TITLE
resolve reported npm issues

### PR DESCRIPTION
**Pull request by bryevdv**
@mattpap npm was reporting several vulnerabilities, some "high" or "ciritical". All of them were in `devDependencies` as far as I could tell, but I'd still rather be visibly in front of these things. I made the changes it suggested, things seem to build fine, and tests pass. Do you have any comments?

partial for #7880

### CODE REVIEW

**Comment by mattpap** [comment]
> Do you have any comments?

Yeah, I did the same, just upgraded most of the dependencies. Did you run tests locally? A simple upgrade won't do it without changes to tests and custom model compiler's build.

**Comment by bryevdv** [comment]
@mattpap I updated the two packages in `packages.json` and I ran this command:
```
npm update hoek --depth 7
```
That resolved everything in the audit. After that I was able to build and run tests locally without issue.

**Comment by mattpap** [comment]
> After that I was able to build and run tests locally without issue.

Yeah, other packages cause problems.

> `npm update hoek --depth 7`

This is a local command. It doesn't affect `package*.json` files, so any vulnerabilities will return as soon as you run `npm install`. `npm cmd pkg-name` and npm cmd` are two completely different tools and shouldn't be used together.

**Comment by bryevdv** [comment]
I will try to install anything else that does not require other changes.

**Comment by bryevdv** [comment]
> This is a local command. It doesn't affect package*.json files, so any vulnerabilities will return as soon as you run npm install

This does not seem to be the case. After running another one, `package-lock.json` is modified, and then after an `npm install` the audit is improved:

```(base) ❯ npm install

> bokehjs@0.12.16-dev4 prepare /Users/bryanv/work/bokeh/bokehjs
> node ./prepare.js

up to date in 3.861s
[!] 11 vulnerabilities found [2682 packages audited]
    Severity: 4 low | 7 high
    Run `npm audit` for more detail
```

**Comment by bryevdv** [comment]
OK after doing those new ones, it is down to:
```
(base) ❯ npm audit

                       === npm audit security report ===



# Run `npm install gulp@4.0.0` to resolve 4 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp > vinyl-fs > glob-stream > minimatch                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/118                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp > vinyl-fs > glob-watcher > gaze > globule > glob >     │
│               │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/118                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/118                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp > vinyl-fs > glob-watcher > gaze > globule > lodash     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


# Run `npm update lodash --depth 2` to resolve 1 vulnerability
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp-uglify [dev]                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp-uglify > lodash                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘



┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp > vinyl-fs > glob-stream > glob > minimatch             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/118                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

[!] 6 vulnerabilities found - Packages audited: 2678 (2575 dev, 61 optional)
    Severity: 2 low | 4 high
```

Updating any of those remaining does seem to break the build.

**Comment by bryevdv** [comment]
All of those few are definitely dev-only dependencies so if things look good I'd be +1 to merge this as-is for now and figure the rest out after the release

**Comment by mattpap** [comment]
> This does not seem to be the case.

Well, at point I don't have any idea what npm actually does. If those changes work, lets merge.

**Comment by bryevdv** [comment]
OK, I will unlink this and make it a standalone issue, and put the remaining info in #7880

**Comment by bryevdv** [comment]
additionally `npm outdated` reports:

```
(base) ❯ npm outdated
Package                    Current    Wanted    Latest  Location
@types/chai                  3.5.2     3.5.2     4.1.3  bokehjs
@types/del                  2.2.33    2.2.33     3.0.1  bokehjs
@types/es6-promise          0.0.33    0.0.33     3.3.0  bokehjs
@types/esprima              2.1.35    2.1.35     4.0.2  bokehjs
@types/geojson            7946.0.1  7946.0.3  7946.0.3  bokehjs
@types/gulp                  4.0.3     4.0.3     4.0.5  bokehjs
@types/gulp-less            0.0.30    0.0.30    0.0.31  bokehjs
@types/gulp-rename          0.0.32    0.0.32    0.0.33  bokehjs
@types/gulp-sourcemaps      0.0.31    0.0.31    0.0.32  bokehjs
@types/gulp-task-listing    0.0.30    0.0.30    0.0.32  bokehjs
@types/mocha                2.2.44    2.2.48     5.2.0  bokehjs
@types/node                 7.0.49    7.0.64    10.0.6  bokehjs
@types/nouislider            9.0.3     9.0.4     9.0.4  bokehjs
@types/run-sequence         0.0.29    0.0.29    0.0.30  bokehjs
@types/sinon                 4.1.3     4.3.1     4.3.1  bokehjs
@types/sprintf-js           0.0.27    0.0.27     1.1.0  bokehjs
@types/yargs                 6.6.0     6.6.0    11.0.0  bokehjs
atob                         2.0.3     2.1.1     2.1.1  bokehjs
btoa                         1.1.2     1.2.1     1.2.1  bokehjs
canvas2svg                  1.0.21       git       git  bokehjs
chai                         3.5.0     3.5.0     4.1.2  bokehjs
chai-as-promised             5.3.0     5.3.0     7.1.1  bokehjs
chalk                        2.3.0     2.4.1     2.4.1  bokehjs
coffeescript                 2.0.2     2.0.2     2.3.0  bokehjs
del                          1.2.1     1.2.1     3.0.0  bokehjs
detective                    4.7.0     4.7.1     5.1.0  bokehjs
es6-promise                  3.0.2     3.0.2     4.2.4  bokehjs
escodegen                    1.9.0     1.9.1     1.9.1  bokehjs
flatbush                     2.0.4     2.0.4     3.0.0  bokehjs
gloo2                        0.0.1       git       git  bokehjs
gulp-less                    4.0.0     4.0.0     3.5.0  bokehjs
gulp-sourcemaps             1.12.0    1.12.1     2.6.4  bokehjs
gulp-tslint                  8.1.2     8.1.3     8.1.3  bokehjs
gulp-typescript              3.2.3     3.2.4     4.0.2  bokehjs
jsdom                       9.12.0    9.12.0   11.10.0  bokehjs
kiwi                         0.1.0       git       git  bokehjs
less                         3.0.2     3.0.4     3.0.4  bokehjs
merge-source-map             1.0.4     1.1.0     1.1.0  bokehjs
merge2                       1.2.0     1.2.2     1.2.2  bokehjs
nouislider                  10.1.0    10.1.0    11.1.0  bokehjs
numbro                       1.6.2       git       git  bokehjs
proj4                       2.3.17    2.3.17     2.4.4  bokehjs
run-sequence                 1.2.2     1.2.2     2.2.1  bokehjs
sinon                       1.17.7    1.17.7     5.0.7  bokehjs
slickgrid                    2.3.4       git       git  bokehjs
ts-node                      3.3.0     3.3.0     6.0.3  bokehjs
tslib                        1.8.1     1.9.0     1.9.0  bokehjs
tslint                       5.9.1    5.10.0    5.10.0  bokehjs
typescript                   2.8.1     2.8.1     2.8.3  bokehjs
uglify-es                    3.2.2     3.3.9     3.3.9  bokehjs
vinyl-source-stream          1.1.0     1.1.2     2.0.0  bokehjs
websocket                   1.0.25    1.0.26    1.0.26  bokehjs
yargs                       3.32.0    3.32.0    11.0.0  bokehjs
```

**Pull request merged**
