### PR TITLE
Make WebGL work on Safari

### LINKED ISSUE #2683: Our Webgl support does not work very well on Safari
On Safari, our webgl examples do not always work. Not sure if this is a bug of Safari or on our side. Need more datapoints.

Test pages:

* To test that webgl works: https://get.webgl.org/
* To test Bokeh webgl examples: https://dl.dropboxusercontent.com/u/1463853/bokeh/index.html 

Collecting what we know:

* On my OSX 10.6.8 (snow leopard) VM everything works as expected.
* On Sarah's machine (Mavericks) even the simple webgl example crashes Safari. (http://pastebin.com/NMg325hE)
* On Sarah's machine with intel card selected the iris example works, the others not (Program has unset variables error)
* On Sarahs' ipod (Yosemite) webgl works. Bokeh demos not sure (but might be a bit heavy ;))
* On Bryan's machine (Yosemite), webl works, but our Bokeh examples do not.
* On OSX and Chrome, everything works fine (which suggests its not purely a driver issue).

Conclusion so far: looks like something goes wrong between Safari and the driver, and the way we use webgl triggers that (in some situations).

### LINKED ISSUE #4795: WebGL line thickness scales inappropriately with browser zoom level
The line width should probably be scaled (or *not* scaled) with the HIDPI `pixel_ratio`.

### PR DESCRIPTION
**Pull request by almarklein**
Fixes #4795 
Fixes #2683 

The main fix has been applied in https://github.com/vispy/vispy.js/blob/master/scripts/gloo2.py, which is the code that generates gloo2.js. While in there I also improved the API a bit, so this PR also updates the Bokeh code accordingly. Further, I snuck in a quick fix for #4795.

Todo:
* [x] Test on other OS / browsers whether all webgl examples still work.
* [x] Test whether line width issue exists on non-retina displays as well, (and that it is now fixed).
* [x] Look into FF warning "Texture has not been initialized prior to a partial upload, forcing the browser to clear it. This may be slow."

### CODE REVIEW

**Comment by bryevdv** [comment]
Awesome.

**Comment by bryevdv** [comment]
Seems to be broken on windows tho. If I use CDN resources, it works in my VM but if I set to inline reources, it stops displaying.

**Comment by almarklein** [comment]
Strange. I just verified it to work fine on my Windows machine (except some warnings on FF that I need to look into), both with inline and relative dev. Any error messages in the console?

**Comment by bryevdv** [comment]
Well it might be an issue on my end. If it's working well for you lets get it in a dev build. That would be easier for me to test on Windows.

**Comment by bryevdv** [comment]
@almarklein more info: the error I get on my windows VM is "can't set initial ranges" if I provide explicit range tuples to `figure`, it works...

**Comment by bryevdv** [comment]
@damianavila if you have 10 minutes can you try the `examples/webgl` examples with this PR on LInux?

**Comment by caryan** [comment]
Seems #4795 is still an issue on HIDPI in Linux. Otherwise the examples seem to work fine in Chrome and Firefox.

screenshot from 2016-07-14 22-49-25

**Comment by bryevdv** [comment]
@caryan we aren't able to reproduce this anymore, maybe a config/install issue? We're going to go ahead and merge this in a bit, and then put out a dev build later today. If you can check out the issue with the dev build, and if it persists in the dev build we can re-open the issue.

**Comment by caryan** [comment]
Sorry about that.  I must have botched the local build/install. With 0.12.1dev3 it works fine.

**Comment by damianavila** [comment]
>@damianavila if you have 10 minutes can you try the examples/webgl examples with this PR on LInux?

Sorry, I just saw this... glad to see it is working.

**Pull request merged**
