### PR TITLE
Unicode fix when serving notebooks on Python 2

### LINKED ISSUE #8554: Bokeh cannot serve notebooks on Python 2
Using a notebook containing a single code cell (simply  `1+1`) in a Python 2 environment: 

`bokeh serve --show Test.ipynb`

Results in the following error:

```
SyntaxError: encoding declaration in Unicode string
```

Note that this is why the unit tests added in #8546 skip for Python 2.

### PR DESCRIPTION
**Pull request by jlstevens**
Quick PR to try to fix #8554.

### CODE REVIEW

**Comment by bryevdv** [comment]
OK now that it is local to notebook handler I will plan to merge for 1.0.4. I assume you have tested manually on both 2/3?

**Comment by jlstevens** [comment]
> I assume you have tested manually on both 2/3?

Yes, using a very simple notebook.

There is one issue I am not sure how to fix: if your notebook contains unicode characters, e.g:

```
θ=3
```

then you'll get:

``ERROR: 'ascii' codec can't encode character u'\u03b8' in position 78: ordinal not in range(128)``

This isn't surprising given the currently suggested fix and I'm trying to figure out how to get `ast.parse` to work when unicode is present.

**Comment by bryevdv** [comment]
OK well I am happy to merge whenever, since it is so localized, but I will wait for your `ready`

**Comment by bryevdv** [comment]
The uncommented test are failing on python 2.7

**Comment by jlstevens** [comment]
Actually, I've just read something suggesting that `θ=3` would always be invalid for python 2. In which case, I'll put the unicode in a string and test that instead.

**Comment by bryevdv** [comment]
Still failing Python 2.7 I would recommend running all unit tests locally before pushing, there is a huge backlog/slowdown on Travis CI and limited workers available.

**Comment by jlstevens** [comment]
Had to update the earlier unit test: all the tests on Travis are passing now. 

In the end, this PR simply removes the line `# coding: utf-8` on Python 2 as it cannot be processed when in a unicode string. In addition, line magics in the older version of IPython are now handled by removing `get_ipython().magic` - this older version is the last version that will support Python 2.

**Comment by jlstevens** [comment]
@bryevdv Ready to review/merge.

**Pull request merged**
