### PR TITLE
Bokeh Apps

### PR DESCRIPTION
**Pull request by fpliger**
This PR is aims to propose a[n easy] design to let [experienced or not] users create rich and complex applications from configuration (yaml ATM) files without too much boilerplate code.

The implementation definitely need some attention and be improved. The real focus is on the interface of `bokeh.appmaker` (specially on `YamlApp`and `bokeh_app`). Both accept:

* an application configuration yaml file that defines "an app" but supporting the following sections: `datasets`, `ui`, `layout` and `event_handlers`
* a theme configuration yaml file that defines bokeh objects style attributes and is used to style "an app"

The PR also re-writes the `sliders` app example using the new feature to show the new concept applied.

### CODE REVIEW

**Comment by pzwang** [comment]
Looks interesting so far.  A few random thoughts:

1. I recall @tonyfast had indicated some way to embed Python code within Yaml...?  Might that be useful for inlining small callbacks and such?

2. Isn't it potentially quite limiting to have a single `update_data` callback?  This is a problem that is frequently encountered in reactive programming (Traits, JS, you name it).  With web clients, an additional complexity of asynchrony is introduced.  How do we indicate that there are "groups" of values which should all be recomputed together, and therefore rapid or successive changes to any of them should all be batched together?  When using Traits, I often found that I had a set of "external" traits which could implement naive change handlers (`def _var_changed(...)`), but there was oftentimes a set of "internal" traits which all had to be "synchronize" in their updates.  So there would be some kind of internal boolean guard to make sure I didn't end up in an update loop:

    def _internal_var_A_changed(self):
        if self._internal_state_changing: return
        else: self._internal_state_changing = True
        ... do stuff ...

I think that an easier facility for expressing this pattern would be very useful, and I think it's possible.  For instance, you can imagine a `@synchronized` decorator that you put on each of the internal state change handlers, and it would make sure that it never fired any other change handlers that were also wrapped with @synchronized when values are set.

3. I know our goal here is to provide a simple mechanism for data scientists, and not necessarily an uber-system for us to use to build extremely complex interfaces, so it's fine to punt on some of the hairier problems.  But what I'm wondering is, are there hairy problems that arise even with the simple use cases?  I'm curious to hear what @sccolbert thinks about this?  (Brief thoughts would be fine, I know you are busy)

**Comment by fpliger** [comment]
Ah, shame on me for not including @sccolbert in the discussion. Definitely eager to hear your thoughts too. :-)

> 1. I recall @tonyfast had indicated some way to embed Python code within Yaml...? Might that be useful for inlining small callbacks and such?

Right. I and @tonyfast are scheduling some time to discuss and work together on some of those concepts.

My main concern is to define the "right" limit between giving users as much freedom as possible in the app configuration [yaml] file compared to "forcing" (maybe "address" is a better word) users to adopt a sane separation of application layers. You can push things to the limit into a yaml file when it'd probably make more sense to just define a function in a singly python file. 

That's a very interesting discussion. :-)

> Isn't it potentially quite limiting to have a single update_data callback? 

It is, but that'd be optional. The implementation supports both cases. You could decide either to define a main single callback or define more granular event handlers attached to single events. 

> How do we indicate that there are "groups" of values which should all be recomputed together, and therefore rapid or successive changes to any of them should all be batched together?

Oooh, right. That's definitely a tough case... ATM you could define a single event handler that is called for a group of attributes but that'd be called N times sequentially without any orchestration. That's definitely not optimal.

> When using Traits, I often found that I had a set of "external" traits which could implement naive change handlers (def _var_changed(...)), but there was oftentimes a set of "internal" traits which all had to be "synchronized" in their updates. [CUT]
> I think that an easier facility for expressing this pattern would be very useful, and I think it's possible. For instance, you can imagine a @synchronized decorator that you put on each of the internal state change handlers, and it would make sure that it never fired any other change handlers that were also wrapped with @synchronized when values are set.

Oh, that's very interesting. We should explore this concept.

@bryevdv may have some thoughts about this. I think it it'd be very tricky to explore this with the current implementation of `bokeh-server` (even the granular event handling/single attribute update is somehow "fake" as the server always updates all the attributes of a model on every call (more or less like a PUSH request rather then a PATCH)). AFAIK changing this is part of @bryevdv plan and that may be a good occasion to evaluate the @synchronized feature.

Another feature I liked a lot about traits that can be explored sometime in the future is how you could spell the conditions to enable/disable/show/hide parts of the UI and conditions to trigger events...

**Comment by sccolbert** [comment]
Peter hits on a number of good points that I've been thinking about (with no solution yet) wrt to a declarative UI specification which renders on the web.

1) I think the concept of change notification/update has to be batched at some level, otherwise the protocol will be too chatty. The option to collapse multiple successive changes where the transient values don't matter would also be nice. I think an app-level update callback is too coarse (and maybe even the wrong abstraction). We could think about or discuss this more and maybe converge on the right one.

2) Supporting the language (Python) in the yaml file is a bad idea. This is something I wish I never did in Enaml. As soon as you start down that road, you will inevitably end up supporting all (or most) of the language. Disregarding the pain of getting scoping to work right, you can easily fall into the trap of "oh, I'll just write this event handler in the yaml file", and all of a sudden your UI is no longer portable to another platform or language. I think the sweet spot here is a universally accepted grammar for binding to an attribute on some context object, the ability to compose simple expressions, and the ability to specify a function or method to execute in response to some coarse action or event (button click and form submit are coarse, mouse move is not). I don't think one should be able to "extend" the system from yaml. It should be pure glue which is used to assemble existing pieces which are written in some other language (Python, Julia, R, etc...). Forcing the separation religiously will make some people mad, but will make the library portable across backends.

3) **Don't** try to be front-end agnostic. If your target front-end is the web, let it be only the web, and don't be afraid to expose web-ism in the feature set. The lowest common denominator between desktop and web UIs might as well be zero, because the semantics of interaction are so different. Trying to target both systems will upset all users. This is a fools errand, which I unfortunately learned the hard way.

4) **Do** try to be back-end agnostic in the yaml file. See point 2. The Julia crowd is already implementing back end support for IPython widgets. It would be nice to have a simple declarative language we can use to generally describe and assemble web UIs, that is not tied to any one particular backend system. 

When thinking about batching updates, synchronized changes, computed groups, I can't help but think that all of these problems would be solved very well by assembling the objects in to a compute graph (DAG). Changing a value of an input node would invalidate a portion of the graph. Several changes could be batched and only a single recompute of the invalid portion of the graph could be performed. All changed output nodes could then be pushed to the UI. One could use a trait-like descriptor as an input value, and `@computed` method decorator for output values. Instead of doing AST parsing to assemble the graph, the descriptors could hook into a tracing mechanism to track dependencies at runtime.

This is all a bit stream of consciousness, happy to hop on a hangout at sometime with anyone who wants to discuss more.

**Comment by fpliger** [comment]
The new server work in #2794 deprecates this PR. IMO we can deprecate this PR. @bokeh/core thoughts?

**Comment by havocp** [comment]
I agree this is obsoleted by the tornado branch. I'm going to go maverick and close it :-)

**Pull request closed without merging**
