### PR TITLE
SpanSet

### LINKED ISSUE #5962: add source parameter to Span or create SpanSet
This is not a bug but rather a feature request.

The `Label` text annotation currently has a very useful corresponding `LabelSet` companion that allows to define a `ColumnDataFrame` as `source` for the text boxes.

It would be helpful to have an equivalent `SpanSet` object to draw multiple spans from a `ColumnDataFrame`. Currently, to arrive at the same result one has to hack one's way using `ray` objects bound to a data frame.

Current way:
```python
# rays used as spans, y is a large negative number for vertical spans
p.ray(x='x', y='y', color='firebrick', length=0, angle=90, angle_units='deg', alpha='alpha', source=ray_source)
```

Proposed way:
```python
spans=SpanSet(location='x', dimension='height', line_color='firebrick', alpha='alpha', source=span_source)
p.add_layout(spans)
```

```

### PR DESCRIPTION
**Pull request by lemarcantoine**
Adds a SpanSet annotation as requested in #5962. As suggested by @bryevdv, I took inspiration from Label vs. LabelSet.

With SpanSet you can specify a data source and bind it to the `location` attribute.

- [x] issues: fixes #5962
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

If I'm not wrong the reference will update itself from code but I don't know if I have to write an example for the User Guide.

### CODE REVIEW

**Comment by bryevdv** [comment]
Thanks for the PR @lemarcantoine The 3.6 on win is due to an external package issue. It may be resolved so I have restarted the tests. I'm at a conference now but will take a closer look at the PR as soon as I am able.

**Comment by lemarcantoine** [comment]
Thanks @bryevdv for your comment. I remain available to perfect the PR!

**Comment by bryevdv** [comment]
@lemarcantoine I have still only been able to take a quick look and it looks fine from a glance. I guess my suggestion would be to look and see if there are any places we might reduce duplicated code, e.g:

* intermediate base classes on the Python side, to collect common properties
* and similar JS code blocks that can be factored out (which might be by introducing intermediate classes, or by pulling things out into shared functions)

I should be able to take a close look by this weekend.

**Comment by lemarcantoine** [comment]
Ok I see how I can improve the PR:
1. Change `Span` to be a child of `SpanSet` (I'm not sure wether it's elegant or not).
2. Extract shared function (I don't know where to write it in the codebase).
3. Make an abstract intermediate class (I don't know how I could name it).

I think `SpanSet` can't directly inherit of `Span` because `Span` has a special behavior to interact with the `CrosshairTool`.

Which one of this solutions do you think would be good? Also if it's 2. or 3., I'd be happy to have a hint about how to execute them properly.

**Comment by bryevdv** [comment]
@lemarcantoine I don't think `Span` can be a child of `SpanSet` but was more thinking that `SpanSet` and `LabelSet` might share properties that could be factored out into a mixin class (just a speculation, maybe not).

I think on the JS side there is probably code that can be factored out, I will leave more detailed comments when I can take a closer look in a few days. Thanks!

**Comment by bryevdv** [comment]
@mattpap do you have any thoughts about merging this as-is, with an issue to clean up duplication later? I'm on the fence.

**Comment by mattpap** [comment]
I'm fine with merging this. I will clean it up next time I will be working on annotations.

**Comment by bryevdv** [comment]
Thanks @lemarcantoine  (and sorry for the lengthy review)

**Comment by bryevdv** [comment]
@mattpap well, this needs updates
```
   src/lib/models/annotations/span_set.ts:12:10 - error TS2305: Module '"../../../../../../../../../Users/bryan/work/bokeh/bokehjs/src/lib/styles/annotations"' has no exported member 'bk_annotation_child'.

    12 import { bk_annotation_child } from "styles/annotations"
                ~~~~~~~~~~~~~~~~~~~
    src/lib/models/annotations/span_set.ts:134:15 - error TS2339: Property 'ctx' does not exist on type 'CanvasView'.

    134       const { ctx } = this.plot_view.canvas_view
                      ~~~

```

**Comment by bryevdv** [comment]
I'd rather push a fix than revert this, @mattpap where is the PR that changed these things so I can model after it

**Comment by bryevdv** [comment]
@lemarcantoine if you are able to re-submit a new version of the PR on top of current master, we would love to have it merged

**Pull request merged**
