### PR TITLE
support for flexible datatable formatters

### PR DESCRIPTION
**Pull request by dennisobrien**
The goal here is to add support for a flexible cell formatter in DataTables.  More specific goals:

1. Support for HTML in the cells.
1. Support column sorting based on the value of the cell, not the resulting HTML.
1. Templates can reference values from other columns within the row.

This PR adds the `HTMLTemplateFormatter` class.  This object takes a `template` argument which follows the template style of Underscore.js.  http://underscorejs.org/#template

Some examples:

```Python
# Simple HTML template to format the column value as code.
# The keyword `value` refers to the column the formatter is applied to.
HTMLTemplateFormatter(template='<code><%= value %></code>')

# Use values from other columns (`manufacturer` and `model`) to build a hyperlink.
# Here `value` refers to the current column, and `manufacturer` and `model` are named columns.
HTMLTemplateFormatter(template='<a href="https:/www.google.com/search?q=<%= manufacturer %>+<%= model %>" target="_blank"><%= value %></a>')
```

This is related to issue #2923 

Any feedback would be greatly appreciated.

thanks,
Dennis

### CODE REVIEW

**Comment by bryevdv** [comment]
LGTM at a quick glance. We do use eco templates elsewhere it might make sense to standardize. Ping @mattpap

**Comment by dennisobrien** [comment]
Thanks @bryevdv 

I did see the eco templates but I assumed those were author time templates, not run time templates.  I'll take a closer look.  The use of the Underscore.js template was purely about convenience.

**Comment by bryevdv** [comment]
Yes they are not really exposed. I would say support whatever is most commonly in use.

**Comment by fpliger** [comment]
Cool! Thanks @dennisobrien for the addition!

LGTM too. Don't have strong opinions about the best way to manage the templates. Will leave other @bokeh/core devs comment on that

**Comment by bryevdv** [comment]
Ideally this could be a place for "extensible models", so you could imagine 
```
class JSTemplate(HasProperties):
    value = Any
    source = String

class EcoTemplate(JSTemplate):
    pass

class UnderscoreTemplate(JSTemplate):
    pass
```
and then you would pass whatever specific type of template you wanted (each of the subclasses would supply its own fairly trivial JS implementation "inline") But that's probably for a later day.

**Comment by dennisobrien** [comment]
Thanks @bryevdv 

I'll look into implementing another version with eco.

Underscore.js does allow passing regular expressions to override the template style (e.g., to use "{{ value }}" instead of "<%= value %>") but the change is global instead of just that template, and seemed like more trouble than it was worth.

I just realized I need to test that this works for values that have "<" or ">" in it.  It's possible _.template handles this already, but I need to test.

Also I'd like to move the line `compiled_template = _.template(template)` out of format and into a constructor so that it is done once per formatter instantiation rather each call to format.  If someone more experienced with CoffeeScript could point out how to do this, I'd appreciate the help.

thanks,
Dennis

**Comment by dennisobrien** [comment]
Hi @bryevdv - I looked at the eco templates and as I understand it these are only available at compile time and in CoffeeScript.  The cell formatter here needs template functionality at run time, and I don't think the eco template functionality is an option there.  But I could very likely be wrong here.

Regarding the name, I'm not partial to the current name of HTMLTemplateFormatter.  The "Formatter" part is helpful since it derives from CellFormatter, and the "Template" part suggests that templates are involved.  But "Underscore" would be more explicit than "HTML".  Is "UnderscoreTemplateFormatter" too unwieldy?  This would just be a name change.

```Python
class UnderscoreTemplateFormatter(CellFormatter):
    template = String
```

**Comment by bryevdv** [comment]
My main objection to `UnderscoreTemplateFormatter` is that it lets implementation detail leak out. Users will just care what syntax they need to use (which we should tell them/demonstrate), not necessarily that it is some JS library called Underscore. Given that I think my preference is `HTMLTemplateFormatter` with only a mention of Underscore in the docs .

**Comment by dennisobrien** [comment]
Great -- I'll leave it as is then.

**Comment by dennisobrien** [comment]
Here's a simple example of using templates to change font colors and include images in a DataTable.

```
from bokeh.io import output_notebook
output_notebook()

from bokeh.io import show
from bokeh.models import ColumnDataSource, DataRange1d, Plot, LinearAxis, Grid, Circle, HoverTool, BoxSelectTool
from bokeh.models.widgets import (DataTable, TableColumn, 
                                  StringFormatter, NumberFormatter, HTMLTemplateFormatter,
                                  StringEditor, IntEditor, NumberEditor, SelectEditor)

from bokeh.sampledata.periodic_table import elements

elements['name_lower'] = elements['name'].str.lower()
source = ColumnDataSource(elements)

columns = [
    TableColumn(field='atomic number', title='Atomic Number'),
    TableColumn(field='symbol', title='Symbol'),
    TableColumn(field='name', title='Name', 
                formatter=HTMLTemplateFormatter(template='<font color="<%= CPK %>"><%= value %></font>')),
    TableColumn(field='name_lower', title='Image',
                formatter=HTMLTemplateFormatter(template='<a href="http://images-of-elements.com/<%= value %>.php" target="_blank"><img src="http://images-of-elements.com/<%= value %>.jpg" style="width:20px;height:20px;border:0"></a>'))
]
data_table = DataTable(source=source, columns=columns, editable=False)

show(data_table)
```

bokeh_datatable_htmltemplateformatter_example

**Comment by mattpap** [comment]
> I looked at the eco templates and as I understand it these are only available at compile time

Previously yes, but now, due to new custom models feature, we ship coffeescript compiler with bokehjs, so we can support eco templates at runtime as well.

**Comment by bryevdv** [comment]
@bokeh/dev thoughts? At this point I am inclined to think this should be merged with just underscore template support, and it can be revisited if there is ever a pressing need for some other template facility.

**Comment by havocp** [comment]
I am planning to suggest moving the coffee script compiler from client side to the SpellingHandler fwiw, though elaborating on that idea is probably out of scope for a 2am comment on this PR :-)

**Comment by bryevdv** [comment]
OK then I think this can go in as-is for now.

**Comment by bryevdv** [comment]
Thanks @dennisobrien !

**Comment by farscape2012** [comment]
Hi, 
I am trying to use HTMLTemplateFormatter and thought this would be a good example. I tried to reproduce the result with slide modification.  I just removed hyperlink columns as the link may not work. But this did not work either. But if I remove both columns which use HTMLTemplateFormatter, then it works. Can someone show me how to use HTMLTemplateFormatter?
 
`from bokeh.io import show
from bokeh.models import ColumnDataSource, DataRange1d, Plot, LinearAxis, Grid, Circle, HoverTool, BoxSelectTool
from bokeh.models.widgets import (DataTable, TableColumn, 
                                  StringFormatter, NumberFormatter, HTMLTemplateFormatter,
                                  StringEditor, IntEditor, NumberEditor, SelectEditor)

from bokeh.sampledata.periodic_table import elements

elements['name_lower'] = elements['name'].str.lower()
source = ColumnDataSource(elements)

columns = [
    TableColumn(field='atomic number', title='Atomic Number'),
    TableColumn(field='symbol', title='Symbol'),
    TableColumn(field='name', title='Name', 
                formatter=HTMLTemplateFormatter(template='<font color="<%= CPK %>"><%= value %></font>'))
]
data_table = DataTable(source=source, columns=columns, editable=False)

show(data_table)`

Screenshots are attached.
With CPK. It was supposed to have colors
image

Without any HTMLTemplateFormatter
image

**Pull request merged**
