### PR TITLE
add tab completion for splattable lists

### LINKED ISSUE #2335: tab completion for splattable lists
When splattable lists contain only models of a single type, provide a `__dir__` to return the common set of attribute names. 

Reference: https://ipython.org/ipython-doc/dev/config/integrating.html

### PR DESCRIPTION
**Pull request by bryevdv**
issues: closes #2335

### CODE REVIEW

**Comment by bryevdv** [comment]
This is the behaviour:
```
In [7]: foo = p.select(tag="junk")

In [8]: foo.
foo.append   foo.clear    foo.copy     foo.count    foo.extend   foo.index    foo.insert   foo.pop      foo.remove   foo.reverse  foo.sort     

In [8]: p.axis.
p.axis.append                          p.axis.changed_vars                    p.axis.major_label_orientation         p.axis.minor_tick_line_cap             p.axis.reverse
p.axis.axis_label                      p.axis.class_properties                p.axis.major_label_standoff            p.axis.minor_tick_line_color           p.axis.select
p.axis.axis_label_standoff             p.axis.clear                           p.axis.major_label_text_align          p.axis.minor_tick_line_dash            p.axis.select_one
p.axis.axis_label_text_align           p.axis.clone                           p.axis.major_label_text_alpha          p.axis.minor_tick_line_dash_offset     p.axis.session
p.axis.axis_label_text_alpha           p.axis.collect_plot_objects            p.axis.major_label_text_baseline       p.axis.minor_tick_line_join            p.axis.set
p.axis.axis_label_text_baseline        p.axis.copy                            p.axis.major_label_text_color          p.axis.minor_tick_line_width           p.axis.set_select
p.axis.axis_label_text_color           p.axis.count                           p.axis.major_label_text_font           p.axis.minor_tick_out                  p.axis.setup_events
p.axis.axis_label_text_font            p.axis.dataspecs                       p.axis.major_label_text_font_size      p.axis.name                            p.axis.sort
p.axis.axis_label_text_font_size       p.axis.dataspecs_with_refs             p.axis.major_label_text_font_style     p.axis.on_change                       p.axis.tags
p.axis.axis_label_text_font_style      p.axis.dump                            p.axis.major_tick_in                   p.axis.plot                            p.axis.ticker
p.axis.axis_line_alpha                 p.axis.extend                          p.axis.major_tick_line_alpha           p.axis.pop                             p.axis.update
p.axis.axis_line_cap                   p.axis.finalize                        p.axis.major_tick_line_cap             p.axis.pprint_props                    p.axis.visible
p.axis.axis_line_color                 p.axis.formatter                       p.axis.major_tick_line_color           p.axis.properties                      p.axis.vm_props
p.axis.axis_line_dash                  p.axis.get_class                       p.axis.major_tick_line_dash            p.axis.properties_containers           p.axis.vm_serialize
p.axis.axis_line_dash_offset           p.axis.index                           p.axis.major_tick_line_dash_offset     p.axis.properties_with_refs            p.axis.x_range_name
p.axis.axis_line_join                  p.axis.insert                          p.axis.major_tick_line_join            p.axis.properties_with_values          p.axis.y_range_name
p.axis.axis_line_width                 p.axis.layout                          p.axis.major_tick_line_width           p.axis.ref                             
p.axis.bounds                          p.axis.load_json                       p.axis.major_tick_out                  p.axis.references                      
p.axis.changed_properties              p.axis.location                        p.axis.minor_tick_in                   p.axis.remove                          
p.axis.changed_properties_with_values  p.axis.lookup       
```

i.e., if the splattable list contains exactly one type, it defers `__dir__` to that type, otherwise it just uses the standard default (list) implementation. I can't think of any better thing to do, however thoughts welcome @bokeh/core

**Comment by bryevdv** [comment]
We could potentially make it *more* restrictive, removing things like `collect_plot_objects` but I think I'd rather not do that (maybe make them private methods instead)

**Comment by bryevdv** [comment]
ping @ijstokes

**Comment by damianavila** [comment]
>  but I think I'd rather not do that (maybe make them private methods instead)

Yep, I think the same...

LGTM

**Pull request merged**
