### PR TITLE
don't use --rerun

### LINKED ISSUE #7734: remove pytest-rerunfailures from CI tests
Tests are more stable now, and removing will allow deletion of the package from the bokeh channel as well.

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #7734
- [x] tests added / passed

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap the image export tests still seem to fail with some regularity on travis with a "Bad file descriptor" message that re-running seems to fix.

**Comment by mattpap** [comment]
Well, lets investigate. I can do it later.

**Comment by bryevdv** [comment]
FWIW seems to be the py2.7 job, at least that's the one I've seen fail twice in a couple of days now

**Comment by bryevdv** [comment]
I'd be ok to merge this and investigate later if it keeps happening enough. I haven't seen it in last several jobs so maybe it's not as common as I imagined. If it happens again we can capture the log output and open a new issue. Sound OK?

**Comment by mattpap** [comment]
Yes, sounds good.

**Comment by mattpap** [comment]
Also, I'm pretty sure we will have to increase timeouts in JS tests (I've been noticing this sporadically locally, so it should happen eventually on travis ci).

**Pull request merged**
