### PR TITLE
[DOCS] update bokeplots, gitter and mailing-list links

### LINKED ISSUE #9080: [DOCS] Update links to bokehplots.com, gitter and mailing-list
Dev documentation still points to https://bokehplots.com/pages/contact.html.  bokehplots.com has out-dated information and is being deprecated.  On the gitter @bryevdv said he want's those links to point to bokeh.org instead.

### PR DESCRIPTION
**Pull request by timsnyder**
* removed some pages that now exist on bokeh.org and relinked
* relinked bokehplots.com targets to updated locations
* replaced mailning-list and gitter links with Discourse

fixes #9080

### CODE REVIEW

**Comment by timsnyder** [comment]
I don't understand why https://travis-ci.org/bokeh/bokeh/jobs/558758725 failed.  So, I closed and reopened to see if it was a transient issue with travis.

**Comment by timsnyder** [comment]
I'm going to dig into this failure more tonight.  Seems like scripts/ci/install.test may have a bit of broken logic in it because it's trying to remove packages that don't exist in the conda env it created.

**Comment by bryevdv** [comment]
> Seems like scripts/ci/install.test may have a bit of broken logic in it because it's trying to remove packages that don't exist in the conda env it created.

A few days ago this was because a new min version was set for `pyyaml` and checked in to master, that evidently did not exist for python 3.5 on conda. But I fixed that by having pyyaml pip installed for now, and it seems like your build is doing the pip install, so I am not sure what's going on offhand.

**Comment by bryevdv** [comment]
I fixed the issue for PRs against the main repo but the problem persisted for external PRs. Will push a fix presently.

**Comment by bryevdv** [comment]
@timsnyder actually can  you make this change on this PR, so it will actually get tested:
```
diff --git a/scripts/ci/install.build b/scripts/ci/install.build
index c4e7c1135..631b1f4c0 100755
--- a/scripts/ci/install.build
+++ b/scripts/ci/install.build
@@ -17,6 +17,9 @@ bash scripts/ci/install
 BUILD_DEPS=`python scripts/deps.py build`
 conda install -n testenv --yes --quiet ${BUILD_DEPS}

+# Need pyyaml>=5.1 but it is only only conda for Python>=3.6
+pip install "pyyaml>=5.1
+
 npm install -g npm

 # install NPM dependencies
```

**Comment by timsnyder** [comment]
Sure.  I'll make it later this morning.  Thanks!

**Comment by bryevdv** [comment]
So still not working:

* pip installs good verion
* a conda install downgrades is
* pip refuses to reinstall, says req is already satisfied 

This is a bit of a mess, unfortunately. If there is a "force" option for pip I suppose we could try that next.

**Comment by timsnyder** [comment]
@bryevdv Should we build pyyaml 5.1.1 for py35 and put it in the bokeh channel?  I can get it into the tsnyder channel on anaconda.org.  

What does your roadmap look like for ending support for python 3.5?

**Comment by bryevdv** [comment]
> Should we build pyyaml 5.1.1 for py35 and put it in the bokeh channel? 

I guess we could, I've just been trying to avoid adding channels since maintaining separate channels in the past turned out to be a huge pain. The other alternative is we can do a version check in `deps.py` and not pass the loader argument at all for 3.5. (Or try to use the loader and fallback on exception) Would you ming trying that? (And removing both pip installs)

**Comment by timsnyder** [comment]
Sure.  I can try to change deps.py and remove pip.  

I completely agree that maintaining separate channels can be a headache.

**Comment by timsnyder** [comment]
Just for posterity, the loader argument requirement is explained at https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

**Comment by timsnyder** [comment]
le sigh... I think I see what's happening now.  Need to add pyyaml back to the initial conda create.  doing that now.

**Comment by bryevdv** [comment]
Thanks @timsnyder !

**Pull request merged**
