### PR TITLE
Move toolbar to right of plots

### LINKED ISSUE #4399: Make toolbar right by default?
With the new toolbar and title set-up, there's an increased chance that the title and toolbar might clash with each other. 

If that clash does happen, a user can set `toolbar_sticky=False`.

None-the-less, I wanted to propose moving the toolbar default position to the right side of a plot.

See examples/charts/file/scatter_multi.py for an example where a default right toolbar would be more pleasing.

### PR DESCRIPTION
**Pull request by Maggie-M**
issues: fixes #4399

screen shot 2016-06-10 at 10 04 11 am

The new toolbar location leaves the top of the y-axis flush with the top of the browser window

screen shot 2016-06-10 at 10 05 18 am

### CODE REVIEW

**Comment by bryevdv** [comment]
ping @bokeh/dev @birdsarah thoughts? This seems OK and allows a default sticky toolbar to exist and not overlap titles which are usually at the top. 

Only issue:  seems like we might want to increase the min border a bit? that "10" tick label has basically no space above it and abuts the window edge directly. Or maybe there are other ideas.

**Comment by Maggie-M** [comment]
Changed the toolbar places where it was set explicitly on the left in examples because it would overlap the y-axis

screen shot 2016-06-10 at 10 28 59 am

**Comment by bryevdv** [comment]
@birdsarah I guess the options are update the image, or update the test to put the mostly empty toolbar on top explicitly?

**Comment by bryevdv** [comment]
OK, tests green now. I am +1 on merging this, tho it should definitely be called out in the release notes. @bokeh/dev any comments?

**Comment by bryevdv** [comment]
@bokeh/dev I'll merge this later today unless there's comment or objection. We can always revert it...

**Comment by birdsarah** [comment]
Happy to see this went through :D

**Pull request merged**
