### PR TITLE
Landing 2.0

### PR DESCRIPTION
**Pull request by bryevdv**
All previously accepted PRs

### CODE REVIEW

**Comment by mattpap** [comment]
@bryevdv, so you did rebase?

**Comment by bryevdv** [comment]
@mattpap yes I had to, the only conflicts were in the sphinx conf.py

**Comment by mattpap** [comment]
Yeah, but now I have to rebase a dozen or so branches. I will resubmit this without a rebase.

**Comment by bryevdv** [comment]
> Yeah, but now I have to rebase a dozen or so branches. I will resubmit this without a rebase. 

Oh I missed why you were asking about that. Sure, I will cancel the build.

**Pull request closed without merging**
