### PR TITLE
Document lack of serialization support for decimal.Decimal under Serializer class

### LINKED ISSUE #12729: [BUG] [docs] Serializer cannot serialize decimal.Decimal
### Software versions

Python version      :  3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.1
Bokeh version       :  3.0.3
BokehJS static path : \env\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19044-SP0

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

Serialization of the Decimal class worked fine in version 2.4.3.

### Observed behavior

In version 3.0.3, trying to serialize the Decimal class throws an error: `bokeh.core.serialization.SerializationError: can't serialize <class 'decimal.Decimal'>`

### Example code

```Python
from bokeh.core.serialization import Serializer
from decimal import Decimal

ser = Serializer()

ser._encode(10.18) # Works fine
ser._encode(Decimal('10.18')) # Throws error
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by benrussell80**
- [x] issues: fixes #12729

### CODE REVIEW

**Comment by bryevdv** [comment]
@benrussell80 I think perhaps this needs a rebase on latest `branch-3.2` ?

**Comment by mattpap** [comment]
@benrussell80, do you need help with this rebase? btw. `git rebase --onto origin/brach-3.2 FIRST_COMMIT_SHA~1` is the command to use. You will have to remove the four new unrelated commits first.

**Comment by benrussell80** [comment]
Thanks @mattpap would you mind telling me what the command for removing those four commits would be too :grimacing: sorry

**Comment by bryevdv** [comment]
@benrussell80 personally I would do an [interactive rebase](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history#interactive-rebase) and delete the unwanted commits in the editor session for the rebase. If you are interested in doing that but want more guidance we could hop on a quick call sometime. Given the changes are small, it's also fine if you just want to open a new PR on a fresh branch off off current `branch-3.2`.

**Comment by mattpap** [comment]
I cleaned this up. For future reference, the sequence of commands was:
```sh
git reset --hard HEAD~3
git rebase --onto origin/branch-3.2 HEAD~4 # or use SHA_OF_FIRST_COMMIT~1
git push -f
```
However, there are many ways to do it. As mentioned interactive rebase can be used, or the branch can be reset to origin (`git reset --hard origin/branch-3.2`) and your commits cherry-picked individually or by range (that's in principle what rebase `--onto` does).

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
The codebase issue was fixed elsewhere, I will go ahead and merge this, thanks @benrussell80 !

**Pull request merged**
