### PR TITLE
Always clip frame in _paint_levels() despite output backend

### LINKED ISSUE #6787: SVG output bleeds past axis
Bokeh: 0.12.6
Python: 3.6.0
OS: MacOS 10.12.6
Browser: Safari 10.1.2 (12603.3.8) (also tried Chrome 60.0.3112.101 (Official Build) (64-bit) and FireFox 55.0.2 (64-bit))
Selenium: 3.5.0 (same issue in 3.3.3)
Pillow: 4.2.1-py36_0 (same issue with 4.0.0-py36_0)
phantomjs: 2.1.1
olefile: 0.44-py36_0

Description:
Items like lines and annuli(? plural of annulus) stay within axes normally, but they don't respect my boundaries with the svg backend. I've tried playing with background and border colors to no avail.

Possibly related, but in more elaborate examples the order of rendering is reverse from how I added things to the plot.

Minimal working example:
```
from bokeh.plotting import figure, show

p = figure(plot_width=400, plot_height=400, output_backend = 'svg')
p.annulus(x=[1, 2, 3], y=[1, 2, 3], inner_radius=0.1, outer_radius=0.25,
					color="orange", alpha=0.6)
show(p)
```

With backend='svg':
rogueannuli

With backend='canvas':
containedannulicanvasbackend

### LINKED ISSUE #6867: rect shape gets out of figure when panned or zoomed with WebGL
Anaconda, bokeh 0.12.7
rect shape gets out of figure when panned or zoomed.  See figure:

screen shot 2017-09-01 at 8 30 12 pm

	fig = figure(
		plot_width = DIM[2,0][0],
		plot_height= DIM[2,0][1],
		x_range = main_fig.x_range,
		y_range = (-3.5,2),
		tools=['reset,tap,xwheel_zoom',a_hover],
		toolbar_location=None,
		active_scroll="xwheel_zoom",
		output_backend="webgl",
		logo=None,
	)
	fig.xgrid.grid_line_color = None
	fig.xaxis.axis_label_text_font_style = "normal"
	fig.xaxis.axis_label_text_font_size = "14pt"
	fig.xaxis[0].formatter = NumeralTickFormatter(format="0")
	fig.ygrid.grid_line_color = None
	fig.yaxis.visible = False

	fig.rect(
		x = 'x',
		y = 'y',
		width = 'width',
		height = 'height',
		color = 'color',
		fill_alpha = 'fill_alpha',
		line_alpha = 'line_alpha',
		line_width = 'line_width',
		nonselection_color = 'color',
		width_units = 'data',
		height_units = 'data',
		name = 'gene_product',
		source = source
	)

### PR DESCRIPTION
**Pull request by mattpap**
I'm not sure why clipping depended on output backed, but that definitively can't work when `webgl` and `canvas` glyphs are mixed together. In fact this also resolves clipping issues with SVG (not surprisingly).

fixes #6867
fixes #6787

### CODE REVIEW

**Comment by mattpap** [comment]
I'm going to add tests for this issue.

**Comment by bryevdv** [comment]
Is there a way we can maintain this under test? If not can you attach some screenshots here for documentation.

**Comment by mattpap** [comment]
Perfect timing.

**Comment by mattpap** [comment]
Yeah, with chrome support merged, this is definitively possible now.

**Comment by mattpap** [comment]
Looks like I found another bug:

image

`annulus` glyphs doesn't show up with `webgl` backend.

**Comment by bryevdv** [comment]
I think this possibility actually occurred to me when I was looking through the code to add the hex marker and I forgot to follow up. Unless it's a trivial fix I'd make a new issue and move on

**Comment by mattpap** [comment]
I fixed one problem, another appeared. There was a bogus annulus marker in webgl implementation. Now bokeh can render annulus glyph, but the z-order is wrong. I think I will need to fix this one in a separate issue.

**Comment by mattpap** [comment]
image

**Comment by bryevdv** [comment]
@mattpap this only affects annulus? Or is more general?

**Comment by mattpap** [comment]
All glyphs, because webgl glyphs are copied from gl canvas to the main canvas out of order (in one batch).

**Comment by bryevdv** [comment]
If this has always been the case (I'm guessing it has?) then yes we should just get this merged and make a separate issue

**Comment by mattpap** [comment]
Yes, that's my point.

**Comment by bryevdv** [comment]
OK I was just checking, will merge when green.

**Comment by mattpap** [comment]
There is one image difference:

- https://s3.amazonaws.com/bokeh-travis/358578572/examples.html#integration/webgl/multiple_webgl_plots

but it doesn't seem to be significant.

**Comment by mattpap** [comment]
Actually it makes sense, after all previously was no clipping for underalys (grids) and differences coincide with grid lines (endings).

**Pull request merged**
