### PR TITLE
Add 0.12.2 release notes

### PR DESCRIPTION
**Pull request by canavandl**
add 0.12.2 release notes

### CODE REVIEW

**Comment by bryevdv** [comment]
FYI Here are all the issues/PRs marked `MIGRATION` that need a mention:

https://github.com/bokeh/bokeh/pulls?utf8=✓&q=label%3AMIGRATION%20

I believe #4887 is the first that needs mentioning in the release notes.

**Comment by canavandl** [comment]
Yup - I think I've mentioned all of the ones relevant to this release, plus a couple of features.

**Comment by bryevdv** [comment]
@canavandl I'm missing something? the Migration Guide is it's own section in the release notes, and has detailed information about the changes, see e.g.

https://raw.githubusercontent.com/bokeh/bokeh/master/sphinx/source/docs/releases/0.12.0.rst

Let me know of you have questions about what needs to be said about any of the migrations.

**Comment by bryevdv** [comment]
At a bare minimum, for instance, the `show`/`push_notebook` should have an example code line showing how `show`should be called with `notebook_handle=True`

**Pull request merged**
