### PR TITLE
Jan 1st display incorrect - Changed %G to %Y

### LINKED ISSUE #6926: DateRangeSlider incorrect value displayed
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 0.12.9

#### Description of expected behavior and the observed behavior
When using DateRangeSlider, 2017-01-01 00:00:00 through 2017-01-01 23:59:59 displays as 01 Jan 2016. When slider reaches January 2nd, the year changes to 2017.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from datetime import datetime
from bokeh.models.widgets import DateRangeSlider, PreText
from bokeh.layouts import layout
from bokeh.io import curdoc

start = datetime(2017, 1, 1, 0, 0)
end = datetime(2017, 1, 4, 0, 0)

def date_update(attrname, old, new):
    debug.text = str(date_slider.value_as_datetime)

date_slider = DateRangeSlider(value=(start, end), start=start, end=end)
date_slider.on_change('value', date_update)

debug = PreText(text=str(date_slider.value_as_datetime), width=800)

l = layout([date_slider, debug])
curdoc().add_root(l)
```

Code saved as slider.py and run with bokeh serve --show slider.py

#### Stack traceback and/or browser JavaScript console output
solver.js:8 [bokeh] setting log level to: 'info'
client.js:218 [bokeh] Websocket connection 0 is now open
widget_box.js:131 [bokeh] WidgetBox mode is fixed, but no width specified. Using default of 300.
main.js:9 Bokeh items were rendered successfully

#### Screenshots or screencasts of the bug in action
snip_sliderbug1_17-9-12
snip_sliderbug2_17-9-12
snip_sliderbug3_17-9-12

### PR DESCRIPTION
**Pull request by pallgj**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

This is my first pull request, please let me know if I did something wrong.

- [x]  issues: fixes #6926 
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@pallgj we have tests that ensure the python and JS sides stay in sync, the default value will need to be update here as well to get the failing test passing:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/widgets/sliders.py#L122

**Comment by bryevdv** [comment]
@pallgj I'm traveling today and it was a one character change, so I went ahead and made the edit on the PR branch. Hope that's ok, I'd like to get this merged before leaving. :) Thanks for the contribution!

**Comment by bryevdv** [comment]
OK fingers crossed this change fixes. There are two date based sliders, I updated a different one than you at first. But they should all be in agreement now.

**Comment by pallgj** [comment]
Thanks @bryevdv glad to be able to contribute, even though it was just one letter! Hopefully I can help out some more in the future. I've been using Bokeh for a few months now and love it, you guys have done a great job.

**Comment by bryevdv** [comment]
Thanks @pallgj !

**Pull request merged**
