### PR TITLE
Canavandl/4614 range update callbacks

### LINKED ISSUE #4614: Reset tool does not trigger x/y_range callback events
The reset tool obviously changes the extents of the axes, which should trigger any callback events attached to them but it does not appear to. I could swear there was an issue about this that was closed recently, but I can't find it now so I'm probably misremembering. I've tested it as part of 0.12rc1 and it still appears to be an issue there. This functionality is important for downsampling or any other callbacks that depend on the zoom level such as we make use of in datashader.

### PR DESCRIPTION
**Pull request by canavandl**
This PR moves the range callback execution handling inside of the range models themselves (previously PlotCanvasView would change range attributes then execute the callbacks manually). This has the benefit of simplifying callback handling (#4614 reported some cases where callbacks weren't being handled) and makes the callback handling testable/tested.

- [x] issues: fixes #4614 
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

supercedes #5140

### CODE REVIEW

**Comment by canavandl** [comment]
ping @schlichtanders

if you have the time to test your example using this PR branch, that'd be awesome

**Comment by schlichtanders** [comment]
That sounds really good. Next week Monday or Tuesday I will have time to
test. I hope that is enough

Thanks a lot for trying to fix this part!

**Comment by canavandl** [comment]
There's a real test failure: test_reset_triggers_range_callback

It appears that the reset tool isn't triggering the range callback.

**Comment by schlichtanders** [comment]
I tried to test it to in my example, but I could not compile the bokehjs from this pull-request commit. I get the following error:

```
Bokeh includes a JavaScript library (BokehJS) that has its own
build process. How would you like to handle BokehJS:
1) build and install fresh BokehJS
2) install last built BokehJS from bokeh/bokehjs/build
Choice? 1
Building BokehJS... Failed.
ERROR: 'gulp build' returned the following
---- on stdout:
    [11:40:21] Using gulpfile ~/GitProjects/bokeh/bokehjs/gulpfile.js
    [11:40:21] Starting 'build'...
    [11:40:21] Starting 'scripts'...
    [11:40:21] Starting 'scripts:coffee'...
    [11:40:21] Starting 'scripts:js'...
    [11:40:21] Starting 'scripts:eco'...
    [11:40:21] Starting 'scripts:ts'...
    [11:40:21] Starting 'styles'...
    [11:40:21] Starting 'styles:build'...
    [11:40:21] Finished 'scripts:js' after 249 ms
    [11:40:22] Finished 'scripts:eco' after 1.58 s
    [11:40:23] src/coffee/api/typings.d.ts(1,1): error TS1084: Invalid 'reference' directive syntax.
    [11:40:23] src/coffee/api/typings.d.ts(2,1): error TS1084: Invalid 'reference' directive syntax.
    [11:40:23] Finished 'scripts:ts' after 2.43 s
    [11:40:24] Finished 'styles:build' after 3.55 s
    [11:40:24] Starting 'styles:minify'...
    [11:40:25] Finished 'styles:minify' after 354 ms
    [11:40:25] Finished 'styles' after 3.9 s
    [11:40:27] Finished 'scripts:coffee' after 6 s
    [11:40:27] Starting 'scripts:compile'...
    [11:40:27] Finished 'scripts:compile' after 3.75 s
    [11:40:27] Starting 'scripts:build'...
    

---- on stderr:
    module.js:341
        throw err;
        ^
    
    Error: Cannot find module '/home/stephan/GitProjects/bokeh/bokehjs/node_modules/@types/jquery/package.json'
      at Function.Module._resolveFilename (module.js:339:15)
      at Function.Module._load (module.js:290:25)
      at Module.require (module.js:367:17)
      at require (internal/module.js:20:19)
      at requireFromModuleRoot (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/root-require/index.js:16:9)
      at /home/stephan/GitProjects/bokeh/bokehjs/gulp/labeler.coffee:57:14
      at DestroyableTransform._transform (/home/stephan/GitProjects/bokeh/bokehjs/gulp/labeler.coffee:14:22)
      at DestroyableTransform.Transform._read (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
      at DestroyableTransform.Transform._write (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
      at doWrite (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
      at writeOrBuffer (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
      at DestroyableTransform.Writable.write (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
      at Deps.ondata (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/module-deps/node_modules/readable-stream/lib/_stream_readable.js:572:20)
      at emitOne (events.js:90:13)
      at Deps.emit (events.js:182:7)
      at readableAddChunk (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/module-deps/node_modules/readable-stream/lib/_stream_readable.js:195:16)
      at Deps.Readable.push (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/module-deps/node_modules/readable-stream/lib/_stream_readable.js:162:10)
      at Deps.Transform.push (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/module-deps/node_modules/readable-stream/lib/_stream_transform.js:145:32)
      at done (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/module-deps/index.js:417:18)
      at resolve (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/module-deps/index.js:405:36)
      at fromDeps (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/module-deps/index.js:406:11)
      at fromSource (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/module-deps/index.js:377:19)
      at /home/stephan/GitProjects/bokeh/bokehjs/node_modules/module-deps/index.js:370:17
      at ConcatStream.<anonymous> (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/concat-stream/index.js:36:43)
      at emitNone (events.js:85:20)
      at ConcatStream.emit (events.js:179:7)
      at finishMaybe (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:460:14)
      at endWritable (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:469:3)
      at ConcatStream.Writable.end (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:436:5)
      at DuplexWrapper.onend (/home/stephan/GitProjects/bokeh/bokehjs/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_readable.js:537:10)
      at DuplexWrapper.g (events.js:273:16)
      at emitNone (events.js:85:20)
      at DuplexWrapper.emit (events.js:179:7)
      at /home/stephan/GitProjects/bokeh/bokehjs/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_readable.js:934:16
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```
I hope this error is not due to a local configuration issue.

Furthermore, I have to change the paths to the javascript files manually in my generated bokeh plot. Is there a way to say bokeh it shall use the locally build bokehjs and not those from ``cdn.pydata.org``?

**Comment by mattpap** [comment]
@schlichtanders, I suggest reading http://bokeh.pydata.org/en/latest/docs/dev_guide.html to get full developer experience. In this particular case, you will have to run `npm install` in `bokehjs/` (TypeScript compiler is in wrong version (< 2.0)) and then run python code with `BOKEH_DEV=true` environmental variable (this will use local, non-minified `*.js` and `*.css` files, among other things).

**Comment by bryevdv** [comment]
I propose merging this, then @schlichtanders could do further testing more easily with a dev build. Unless there is objection I will merge later today.

**Comment by schlichtanders** [comment]
sounds really good!
is it already merged? I cannot see something saying so in this pull request

**Comment by bryevdv** [comment]
Not yet I should be able to get to it today

**Comment by bryevdv** [comment]
This has been merged and a build has been started. `0.12.4dev4` should be available on the bokeh dev channel in ~30 minutes.

**Comment by schlichtanders** [comment]
I tested my application now with the new build and checked that it in fact uses the CDN for 0.12.4dev4
it works brilliant and solves both my previous problems:

1. reset tool
2. initial set up (by initial range update)

thanks so much!

**Comment by canavandl** [comment]
@schlichtanders thanks for reviewing

**Pull request merged**
