### PR TITLE
Replace numpy.bool8 with numpy.bool_

### LINKED ISSUE #7422: py.test distributed fails with "DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`"
`py.test distributed --verbose` fails with the following errors on `2022.12.1` branch.

```text
ERROR distributed/dashboard/tests/test_components.py - DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
ERROR distributed/dashboard/tests/test_scheduler_bokeh.py - DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
ERROR distributed/dashboard/tests/test_worker_bokeh.py - DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
```

## Steps to reproduce

```console
$ git branch --show-current
2022.12.1

$ conda env create --file continuous_integration/environment-3.10.yaml
...
Successfully installed dask-2022.12.1+2.g0570a08a fsspec-2022.11.0+13.g0974514 keras-2.11.0 s3fs-2022.11.0+4.g5917684
done

$ conda activate dask-distributed

$ python --version
Python 3.10.8

$ python -m pip install -e .
...
Successfully installed dask-2022.11.1 distributed-2022.11.1+1.g856d403b

$ py.test distributed --verbose
...
ERROR distributed/dashboard/tests/test_components.py - DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
ERROR distributed/dashboard/tests/test_scheduler_bokeh.py - DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
ERROR distributed/dashboard/tests/test_worker_bokeh.py - DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
```

### LINKED ISSUE #12689: [BUG] numpy.bool8 is deprecated
### Software versions

.

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

.

### Observed behavior

We received this issue in Dask, reporting that `numpy.bool8` is now deprecated.  Here is a traceback:

```python
____________________ ERROR collecting distributed/dashboard/tests/test_worker_bokeh.py ____________________
distributed/dashboard/tests/test_worker_bokeh.py:15: in <module>
    from distributed.dashboard.components.worker import (
distributed/dashboard/components/__init__.py:5: in <module>
    from bokeh.core.properties import without_property_validation
../../mambaforge/envs/dask-distributed/lib/python3.10/site-packages/bokeh/core/properties.py:273: in <module>
    from .property.auto import Auto; Auto
../../mambaforge/envs/dask-distributed/lib/python3.10/site-packages/bokeh/core/property/auto.py:24: in <module>
    from .enum import Enum
../../mambaforge/envs/dask-distributed/lib/python3.10/site-packages/bokeh/core/property/enum.py:27: in <module>
    from .primitive import String
../../mambaforge/envs/dask-distributed/lib/python3.10/site-packages/bokeh/core/property/primitive.py:37: in <module>
    bokeh_bool_types += (np.bool8,)
../../mambaforge/envs/dask-distributed/lib/python3.10/site-packages/numpy/__init__.py:260: in __getattr__
    warnings.warn(msg, DeprecationWarning, stacklevel=2)
```

### Example code

```Python
.
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes https://github.com/bokeh/bokeh/issues/12689
Fixes https://github.com/dask/distributed/issues/7422

### CODE REVIEW

**Comment by mattpap** [comment]
@mrocklin, thanks.

**Comment by bnavigator** [comment]
Just a note that this does not fix dask until dask supports bokeh 3
https://github.com/dask/distributed/issues/7327
https://github.com/dask/dask/pull/9673
https://github.com/dask/distributed/pull/7329

**Comment by bryevdv** [comment]
I'm not sure I understand, all of the technical issues that were brought to our attention were resolved in Bokeh 3.0.3.

**Comment by bnavigator** [comment]
dask and distributed still pin to bokeh <3. This fix is only for bokeh >= 3.1

That's all I am saying.

**Comment by bryevdv** [comment]
This fix is not required for Dask to function, AFAIK it is merely to clear a deprecation warning in Dask CI? Bokeh 3.1 or 3.0.4 will be released soon in any case, but Dask could lift that version limit to 3.0.3 any time as far as I know.

**Comment by mrocklin** [comment]
> This fix is not required for Dask to function, AFAIK it is merely to clear a deprecation warning in Dask CI? Bokeh 3.1 or 3.0.4 will be released soon in any case, but Dask could lift that version limit to 3.0.3 any time as far as I know.


Yup

**Pull request merged**
