### PR TITLE
explict legend kwargs

### LINKED ISSUE #9135: Be able to order legend items when using GroupBy Legend [FEATURE]
Ordering legend items can be done very easily by [reordering the elements of `p.legend`](https://discourse.bokeh.org/t/legend-ordering/2224). However, when [using a GroupBy Legend, this isn't so straightforward](https://discourse.bokeh.org/t/cant-order-legend-entries-in-hbar-plot/3816/5?u=arturomoncadatorres), since the order is computed on the JS side, which can lead to [lengthy and manual workarounds](https://discourse.bokeh.org/t/cant-order-legend-entries-in-hbar-plot/3816/8?u=arturomoncadatorres).

It would be great if the GroupBy Legends could also be ordered using the same syntax as for non-GroupBy ones.

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #9135
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

@bokeh/dev before I finish up with docs, I would appreciate any review/comments. This PR implements the proprosal in https://github.com/bokeh/bokeh/issues/9135#issuecomment-517880760 namely:

* deprecate `legend` keyword (will stay working in until at least 3.x)
* `legend_label` will always make a string label
* `legend_field` will perform an automatic groupby on the JS side (one legend item)
* `legend_group` will group on the python side (multiple legend items)

are these the best names for the args?

### CODE REVIEW

**Comment by bryevdv** [comment]
Running before updating examples to inspect the examples report with not-updated examples.

**Comment by bryevdv** [comment]
OK I updates all the examples and tests. Current plan is to update docs tomorrow night and merge wednesday, unless there are comments.

**Comment by bryevdv** [comment]
@bokeh/dev this is ready for review. I would like to merge late tomorrow.

**Comment by jbednar** [comment]
Looks good to me, though without the docs, I can't tell how legend_group and legend_field differ or whether those are good names.

**Comment by jbednar** [comment]
(Or at least some screenshots.)

**Comment by bryevdv** [comment]
@jbednar docs were added in https://github.com/bokeh/bokeh/pull/9235/commits/44ed40589ab83c8fd1c0aa1805499727df56df01 ?

**Comment by philippjfr** [comment]
The names sound appropriate to me and I'm glad to see this.

**Comment by jbednar** [comment]
Ah, I had an old browser tab open that didn't update with the new commits.  The docs look fine, thanks.

**Pull request merged**
