### PR TITLE
Hotfix/box selection for mobile

### PR DESCRIPTION
**Pull request by birdsarah**
Box selection / zoom for touch was a bit wonky.

This PR doesn't fix it all, but does get it back to the state described in #2997 

I took the opportunity to write an integration test for box selection with mouse, but I can't write a similar test for touch as we don't have selenium setup with browserstack (or equivalent) to run tests against a mobile device.

You can try the before, after here:

Before: https://rawgit.com/birdsarah/bokeh-miscellany/master/tests/touch/box_touch_broken_1de22.html
After: https://rawgit.com/birdsarah/bokeh-miscellany/master/tests/touch/box_touch_hotfix_9b7b.html

### CODE REVIEW

**Comment by canavandl** [comment]
Improved box select on Android 6.0

LGTM

**Comment by bryevdv** [comment]
@birdsarah the last chart in your "after" link is not working on IOS for some reason. The box is drawing outside the main plot area. Not sure whats different about that one chart.

**Comment by birdsarah** [comment]
@bryevdv - yes - that's to be expected. My testing on earlier version of Bokeh indicated that this was always the case. See notes in #2997.

**Comment by bryevdv** [comment]
In that case, LGTM, merging.

**Pull request merged**
