### PR TITLE
11726 Updated links to visjs.org Graph3d examples

### LINKED ISSUE #11726: [BUG] Update links in example app surface3d to point to new location on visjs.org
#### Description of expected behavior and the observed behavior

The example app for surface3d in the current Bokeh codebase includes links to a non-existent examples page on VisJS.org in both python code and the index.html page.

Outdated link in repository:   https://visjs.org/graph3d_examples.html

Current link at VisJS.org:   https://visjs.github.io/vis-graph3d/examples/

PR to follow for three files under example/apps/surface3d to update the link.

### PR DESCRIPTION
**Pull request by roadswitcher**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes #11726 
- [ ] tests added / passed  
- [ ] release document entry (if new feature or API change)

Changed 3 files to update link to VisJS Graph3D examples gallery.

### CODE REVIEW

**Comment by roadswitcher** [comment]
Once more, with feeling and fewer missteps.

**Comment by bryevdv** [comment]
Looks great, will merge when green!

**Comment by bryevdv** [comment]
Thanks @roadswitcher !

**Comment by g-parki** [comment]
> Once more, but with fewer missteps.

@roadswitcher most of my PRs go about like that 😄 Thanks for the contribution!

**Pull request merged**
