### PR TITLE
Implement cloneable interface in ndarrays

### LINKED ISSUE #13226: [FEATURE] make bokehjs ndarrays cloneable to enable client-side image transforms
### Problem description

I’d like to show an Image to which an image transform is applied client-side before rendering. The parameters of the transform are controlled by UI widgets.   When writing a CustomJSTransform for this, I ran into the following issue: how do I correctly allocate a “blank” array to hold the results?   The xs variable in this case holds an array of one Float64Array2d, so the output should be the same type and dimensions, but there is currently no stable API to deep-clone an input image, or to create a blank new image of the same size/type as a given one.

### Feature description

 Make ndarray implement the cloneable protocol.

Also, it would be useful to add some stable/official documentation for the classes used to represent images as stored in ColumnDataSource, for inter-operation with libraries like [image-js](https://github.com/image-js/image-js).

Thanks a lot!

### Potential alternatives

I worked around the issue by passing two copies of my images in separate columns of the ColumnDataSource; but this somewhat defeats the purpose of sending less data and doing more in the client.

### Additional information

Related discussions: 
https://discourse.bokeh.org/t/client-side-image-transforms/10575
https://github.com/bokeh/bokeh/discussions/13224

### PR DESCRIPTION
**Pull request by mattpap**
fixes #13226

### CODE REVIEW

**Comment by bryevdv** [comment]
Are users expected to use `Cloner` directly? If that's the case we would at least need an example that demonstrates this usage, otherwise there is no way users would know about it. I guess I was expecting a `.clone()` method (which would still need to be demonstrated explicitly)

**Comment by mattpap** [comment]
I don't expect many users to currently use this at all. This is an internal API right now, though users can import and use it. So currently it is the expectation to use `Cloner` class. There is no `.clone()` method, because there is no need to make bokehjs' classes heavier than they already and also cloning is a very expensive operation, so forcing explicit usage may make the user of this API reflect whether this is what they really ought to do. Of course at some point it would be good to expose this as a part of a public API, under the broad umbrella of TS/JS API.

**Comment by bryevdv** [comment]
@mattpap I ask because the issue this PR claims to fix was an unfulfilled need brought by a user. What is the guidance to give to that user to solve their problem? 

If this PR does not offer them a solution then it should not close the issue.

**Comment by mattpap** [comment]
Contradicting my earlier statement, there's already `HasProps.clone()` method, which invokes `Cloner` class, so this PR ineed fixes the issue. I forgot this method actually exists.

**Comment by bryevdv** [comment]
@mattpap 👍 if you can also give a line or two of specific guidance to the OP I am sure it would be appreciated

**Review by ianthomas23 — APPROVED** [review]

**Pull request merged**
