### PR TITLE
Force "use strict" in CustomJS and related models

### LINKED ISSUE #6306: Force strict mode for CutomJS, etc. written in pure JS
We use strict mode everywhere beside this case. For the sake of consistency we should change that.

### PR DESCRIPTION
**Pull request by mattpap**
fixes #6306

### CODE REVIEW

**Comment by bryevdv** [comment]
We have to do this in stages: 

* update all the examples
* add strict as an optional mode (off by default)
* add a validation warning if strict mode is off
* turn strict mode on

The first three can happen all at once, but turning it on (and breaking every js callback out in the wild) has to happen later.

**Comment by bryevdv** [comment]
Noting: will need merge/rebase on master after #7732

**Comment by mattpap** [comment]
Given the extent of this change so far, I would like to get this merge, and I will add deprecation in another PR.

**Comment by bryevdv** [comment]
> Given the extent of this change so far, I would like to get this merge, and I will add deprecation in another PR. 

OK, should get a release note in that PR too

**Pull request merged**
