### PR TITLE
py35 in TravisCI

### PR DESCRIPTION
**Pull request by damianavila**
Let's see how much it takes...

### CODE REVIEW

**Comment by birdsarah** [comment]
From travis.

Hint: the following packages conflict with each other:
  - python 3.5*
  - ipython ==3.2.1

**Comment by birdsarah** [comment]
Why are we pegged to old ipython?

**Comment by damianavila** [comment]
>Why are we pegged to old ipython?

Because I did not have time to update it :wink:, working on that on #3123

**Comment by damianavila** [comment]
This one is running the examples for py27, py34 and py35... I think we can avoid py35 andwhenI ask in the flow there was some kind of agreement on that... but I would like formal feedback @bokeh/core. Also, this should be ready for review after merging #3123

**Comment by mattpap** [comment]
I updated this with `master`. Per @damianavila's https://github.com/bokeh/bokeh/pull/3048#issuecomment-157901993, I used code from PR #3048.

**Pull request merged**
