### PR TITLE
Update license and copyright statements to 2024

### PR DESCRIPTION
**Pull request by mattpap**
Updated with:
```sh
sed -i -e 's/2012 - 2023/2012 - 2024/' $(git ls-files)
```

### CODE REVIEW

**Review by bryevdv — APPROVED** [review]
For large automated updates like this is would be nice to have the command(s) that were invoked given in the OP

**Comment by mattpap** [comment]
Codebase test failures are addressed in PR #13633.

**Comment by sloria** [comment]
I recently learned that updating copyright years is unnecessary: https://hynek.me/til/copyright-years/ . I've removed the copyright years from a number of my projects. Cheers to fewer chores 🎉

**Comment by bryevdv** [comment]
cc @bokeh/core I'd be willing to make this switch based on the argument presented and the citations of other very large orgs having done this.

**Pull request merged**
