### PR TITLE
Use libmamba solver in CI

### LINKED ISSUE #12914: Disable miniconda-setup Post step on Windows
Normally miniconda-install removes all cached packages in a post-install step. Ostensibly this is to help with (GitHub) cache sizes. But these deletions are taking 6-7 minutes on windows jobs, resulting in 25-30 extra CI minutes per run. I made and issue and got some info about how to disable the post-install step, at least, as a potential short term workaround:

https://github.com/conda-incubator/setup-miniconda/issues/280

Ideally we only disable for Windows, since it is only very slow on Windows. Need to investigate whether any (GitHub) caching settings may also need adjustment at the same time.

### PR DESCRIPTION
**Pull request by mattpap**
fixes #12914

### CODE REVIEW

**Comment by mattpap** [comment]
This consistently shaves off 3-8 minutes from jobs.

**Comment by bryevdv** [comment]
There is supposedly a config setting for both these, though. I think a comparison could be made before resorting to manual `conda env update`

**Comment by mattpap** [comment]
As far as I can tell, it's possible to switch from conda to mamba via a configuration option in `setup-miniconda`, but there is no option for setting up the solver. If we don't want to switch to mamba (not sure about this), then this is the way to do it. The additional benefit of this change is the ability to disable conda's progress bar (`--quiet`). The existing installation logs are very sparse and hard to work with.

**Comment by bryevdv** [comment]
@mattpap OK I am not too pressed about it, and the gains are huge. However, I think you may still need to set the option to disable post-install as described in the linked issue in the OP

edit: https://github.com/conda-incubator/setup-miniconda/issues/280#issuecomment-1458551579

**Comment by mattpap** [comment]
> https://github.com/conda-incubator/setup-miniconda/issues/280#issuecomment-1458551579

I've noticed overall performance improvements with libmamba, not just with the solver, so I will see if there's improvement with this alone. If not, I will follow up with setting `run-post: false`.

**Comment by bryevdv** [comment]
@mattpap even with this change, the post install on windows takes a huge amount of time:

Screenshot 2023-04-05 at 11 16 37

c.f. with a few seconds on linux The problem is that the files cleanup, which presumably `setup-miniconda` handles itself, regardless of solver, is incredibly slow on Windows. You can sit and watch each individual file tick off slowly one at a time on Windows. 

If you don't want to set `run-post: false` in this PR that's fine, but then please don't close the linked issue (which concerned the windows post step specifically)

**Review by bryevdv — APPROVED** [review]

**Pull request merged**
