### PR TITLE
Add some new Marker types

### LINKED ISSUE #9863: [FEATURE] Add "dot" marker variants
Dear bokeh developers,

there are `_cross` versions of `circle`, `square`, and `diamond`. But not for `triangle`. I tried to add a `triangle_cross` marker to my plot and got an error. Is there a particular reason for this and if no, could you add it?

Keep up the good work!
Ben

### LINKED ISSUE #9890: Some new markers
Looking at other libraries:

* https://matplotlib.org/api/markers_api.html
* https://plotly.com/python/marker-style/
* https://plotly.com/python/marker-style/

we could add some new marker types

* filled "plus"
* "Y"
* "hash"
* "squishy" square and triangle

possibly others, e.g. dot variants for #9863 

It might also be good to name some more rotational variants as that makes more things usable with a marker mapper.

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #9890 fixes #9863
- [x] tests added / passed
- [x] release document entry (if new feature or API change)

This is still WIP. I intend to re-vamp the docs for markers:

* provide a visual index/TOC of all the marker types
* add simple examples in addition to the complicated "reference" ones

Work so far:

Screen Shot 2020-04-26 at 6 07 32 PM

Note there are also two small slightly "breaking" changes that I consider bug-fixes:

* "scatter" was part of the `marker_types` dict, but this is a mistake, as scatter is not a marker type in that sense

* the circle_x and diamond_cross markers have been fixes so that the x/cross part does not extend outside the main marker.

### CODE REVIEW

**Comment by bryevdv** [comment]
I have for now used `square_pin` and `triangle_pin` for the "pin-cushion" variants. Happy to consider other names.

**Comment by bryevdv** [comment]
@mattpap HOw do I disable these selctively 
```
[20:54:35]   298:24  error  There should be no space after this paren  space-in-parens
[20:54:35]   299:24  error  There should be no space after this paren  space-in-parens
[20:54:35]   300:24  error  There should be no space after this paren  space-in-parens
```
I want to preserve this ailgnment:
```
  ctx.quadraticCurveTo( 0, -a,  r, -r)
  ctx.quadraticCurveTo( a,  0,  r,  r)
  ctx.quadraticCurveTo( 0,  a, -r,  r)
  ctx.quadraticCurveTo(-a,  0, -r, -r)
```

**Comment by mattpap** [comment]
```ts
/* eslint-disable space-in-parens */
ctx.quadraticCurveTo( 0, -a,  r, -r)
ctx.quadraticCurveTo( a,  0,  r,  r)
ctx.quadraticCurveTo( 0,  a, -r,  r)
ctx.quadraticCurveTo(-a,  0, -r, -r)
/* eslint-enable space-in-parens */
```
https://eslint.org/docs/2.13.1/user-guide/configuring#disabling-rules-with-inline-comments

**Comment by bryevdv** [comment]
@bokeh/dev I was thinking of making another small visual correction: The "X" is really slightly too big. It goes from corner to corner I would suggest changing it to be an X that fits inside a circle of radius `r`, to match `circle_x` and also `asterisk`. Any objections?

**Comment by bryevdv** [comment]
OK I would like to eventually do more for he docs but this is enough for now.

**Pull request merged**
