### PR TITLE
Fix row ordering and date formatting in DataTable

### LINKED ISSUE #10749: [BUG] Plaintext copy-pasted from DataTable has a different order
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.2.3
Python 3.9.1rc
Debian sid
Vivaldi/Chrome, same behaviour on both browsers

#### Description of expected behavior and the observed behavior
I have an app that generates a DataTable based on lasso-ed points on the main plot. I've always felt that selecting text from DataTable was a bit cumbersome, as it was hard to select-all, but to my absolute surprise, I found that there was a checkbox method to select rows, i.e.

``DataTable(..., selectable='checkbox')``

This solved my need for a quick way to select-all (by clicking the checkbox on the header row), but selecting the rows + CTRL--C + CTRL-V elsewhere produces text that is ordered in an unexpected fashion. I hope these pictures suffice to illustrate the expected/observed behaviour:

image
Instead of being sorted numerically, the row indexes are sorted character... ally?

image
This is harder to explain. I sorted the same table by "Selected peptide", so it's now ordered alphabetically by peptide sequence instead of numerically by index number. Copy-pasting it out shows an order that, I think, suffers from the same problem as the previous one. The third row (with index 16) is located at line 13 of the pasted text output, which is the same as the previous table. Previously, the third row (index 2), is also located at line 13 of the output.

#### Complete, minimal, self-contained example code that reproduces the issue
Uh, it's a bit of a spaghetti... if you cannot reproduce the same behaviour on a typical DataTable, let me know and I'll try to condense my code into something minimal/shareable.

Thanks!

### LINKED ISSUE #10769: [BUG] Dates in DataTables appear as zero-epoch
As requested by @bryevdv on issue #10749.

Dates in DataTables all appear as zero epoch (1970-01-01), despite them actually having valid dates in those table cells. Best illustrated by the DataTable section in the official widget documentation
https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html
(I hope this skips the need for a minimal repro code :D)

Copy-pasting the values out of the table DOES produce valid dates, so it's just the appearance that is faulty.

Screenie to illustrate fault:
image

Cheers!

### PR DESCRIPTION
**Pull request by mattpap**
fixes #10749 
fixes #10769

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap FYI there is a real copy-paste test for data tables in the integration / selenium tests. Evidently it was too simple to catch this condition but it could be extended to a more sophisticated example.

**Comment by bryevdv** [comment]
@mattpap is this just marked WIP in order to add a test? If so I can help out with that.

**Comment by mattpap** [comment]
The problem with this PR is that it gives different outcomes on different systems (timezone issues). I'm not sure if the approach is flawed or just incompatible with the formatting library. I didn't put too much thought into this PR.

**Comment by mattpap** [comment]
`DataTable` has many issues, but there is not point for this PR to rot, so rebased and finalized this particular fix.

**Review by bryevdv — APPROVED** [review]

**Pull request merged**
