### PR TITLE
Move tests out of bokeh module, clean-up warnings, only one test_serialization.py, clean-up pytest-selenium parameters.

### PR DESCRIPTION
**Pull request by birdsarah**
If you look at #2844 test results:
https://travis-ci.org/bokeh/bokeh/jobs/80318985#L1820 all the selenium
tests are actually being skipped because of the new pytest-selenium parameters.

This cleans out old fixture overrides that are no-longer needed and uses
the new sensitive-url parameter to ensure they all run (which is just one
running and one xfailing for now)

ping @damianavila @bryevdv - this should go in as soon as possible.

### CODE REVIEW

**Comment by bryevdv** [comment]
Not sure what is going on here: https://travis-ci.org/bokeh/bokeh/jobs/80583237#L2375

**Comment by birdsarah** [comment]
OK. This isn't a quick fix any more but I think is an appropriate clean-up of our tests. The PR now does the following:
* implements the --sensitive-url=None and clears up other unnecessary things from original pytest-selenium implementation 
* move all tests out of bokeh module into tests module (as a result these tests are no longer installed in site-packages when you install/build bokeh)
* cleans up tests as a result of this move
* combines the tests from two files called test_serialization.py (py.test does not like having test files of the same name)
* fixes the pytest warnings that we were seeing e.g. https://travis-ci.org/bokeh/bokeh/jobs/80747688#L1785

**Comment by birdsarah** [comment]
The root problem here is that we've build bokeh so it's in site-packages but there's also the module bokeh and py.test doesn't know where to import from.

There are other alternatives to this grand move. Removing all __init__.py files and being careful about imports in test files is an option.

One thing I like about this is that you have to be nice and explicit in your test files to import from bokeh vs your test module. So, for example, in the case of server tests: there's a bokeh.server.models and a bokeh.models - the tests were just using relative imports e.g. from .. import models - now you have to be explicit and say from bokeh.server.models or bokeh.models. Relative imports can still be used amongst your test files, which is handy for test utils etc. but the concerns are nicely separated.

I think this is harder to get wrong than the other alternative.

I have been influenced by this: http://pytest.org/latest/goodpractises.html#choosing-a-test-layout-import-rules

**Comment by birdsarah** [comment]
This is all passing. The important things with this review I believe are:

 1. 402 tests are still being collected
 2. They're all passing
 3. Are we ok with no longer installing tests in the bokeh package?

**Comment by bryevdv** [comment]
I am -1 on any change that results in the tests not shipping with the built package, or that removes that ability to do `import bokeh; bokeh.test()`

**Comment by bryevdv** [comment]
> One thing I like about this is that you have to be nice and explicit in your test files to import from bokeh vs your test module. So, for example, in the case of server tests: there's a bokeh.server.models and a bokeh.models - the tests were just using relative imports e.g. from .. import models - now you have to be explicit and say from bokeh.server.models or bokeh.models.

This is a good thing, I always do this anyway, but we should make it a policy.

**Comment by bryevdv** [comment]
Is there a compromise that moves just the selenium tests outside the package? That I could support.

**Comment by birdsarah** [comment]
> Is there a compromise that moves just the selenium tests outside the package but leave the unit tests shipped? That I could support. 

I don't believe this is a problem with the selenium tests. If you look at the error you linked to, for example, it's the charts tests that are failing.

>  It is important that anyone packaging bokeh (including us, for conda) be able to run the test suite on the built package directly to make sure the packaged version is correctly and complete. 

OK. That makes perfect sense.

The problem is coming on our travis tests because we're building bokeh, so it's in our site-packages, and then running tests from it.

I will re-work this.

**Pull request closed without merging**
