### PR TITLE
Fix new typings failures

### PR DESCRIPTION
**Pull request by bryevdv**
Not sure what test dep changed but there are several new flake8 errors regarding files under `typings` cc @mattpap

### CODE REVIEW

**Comment by mattpap** [comment]
@bryevdv, what were the errors? I see nothing for 0.920 and the most recent 0.931.

**Comment by mattpap** [comment]
`List[T]` and `list[T]` types are equivalent. We also specify language version 3.8, so mypy should not promote the newer approach (i.e. `list[T]`).

**Comment by mattpap** [comment]
I should have read the comment, it's flake not mypy. Still, I updated to flake8 4.0 and there are no errors for me.

**Comment by bryevdv** [comment]
@mattpap yah I'm not sure, I did also update to Python 3.9.9 in a new env maybe that's it 🤷 In any case I think this CI run should pass

**Pull request merged**
