### PR TITLE
removed unnecessary for loop on source data update

### LINKED ISSUE #5699: not necessary loop in weather example?
see the update plot method below in the [main.py](**url**)
```
def update_plot(attrname, old, new):
    city = city_select.value
    plot.title.text = "Weather data for " + cities[city]['title']

    src = get_dataset(df, cities[city]['airport'], distribution_select.value)
    for key in STATISTICS + ['left', 'right']:
        source.data.update(src.data)
```

Why do we need the for loop over key ?
Isn't a single `source.data.update(src.data)` enough?

### PR DESCRIPTION
**Pull request by chanansh**
issues: fixes #5699

### CODE REVIEW

**Comment by mattpap** [comment]
@chanansh, code quality issues have to be fixed (usage of tabs instead of spaces).

**Comment by bryevdv** [comment]
@chanansh will you be able to merge/rebase master (we had a CI issue to resolve) and also fix up the whitespace issues causing the linter to complain?

**Comment by bryevdv** [comment]
have updated white space as a maintainer, will merge when green

**Comment by bryevdv** [comment]
tested locally will merge when green

**Pull request merged**
