### PR TITLE
server lifecycle hooks feature

### PR DESCRIPTION
**Pull request by havocp**
This has some TODOs and is missing unit tests.

The idea of the feature is that application handlers
can take actions when the server starts, stops, and when
sessions are created and destroyed. These actions can
manually manage document locks, instead of always being inside
the lock like code in session callbacks.

We could implement develop mode file watching in these handlers.
We could also support adding hooks from applications themselves.

See also https://github.com/bokeh/bokeh/wiki/Server-lifecycle-hooks

### CODE REVIEW

**Comment by havocp** [comment]
the idea is that this PR would add the hooks to Handler, but wouldn't yet make ScriptHandler support hooks in an application. However, we could implement develop mode in a handler like:

```python
class ScriptHandler(Handler):
  @gen.coroutine
  def _check_for_changes(self, server_context):
    files_have_changed = #... todo ...
    if not files_have_changed:
       raise gen.Return(None)
    for session in server_context.sessions:
       with (yield session.locked_document()) as doc:
           # make changes to the document here,
           # some changes can probably be done
           # incrementally such as a new theme.yaml
           # could just set doc.theme
    # if the actual main.py changes we can't just modify the doc, we have
    # to trigger a full recreation of the doc, which will require an API
    # like server_context.reload_document() I guess
 
  def on_server_loaded(self, server_context):
     if server_context.develop_mode:
         server_context.add_periodic_callback(lambda: self._check_for_changes(server_context), poll_interval)
```

**Comment by havocp** [comment]
Fixes #3352, fixes #3310 to its full original intent

**Comment by bryevdv** [comment]
ping @mrocklin @birdsarah just FYI

**Comment by havocp** [comment]
Oh, I forgot an important piece of this :-) I have to add the ability to put the hooks in your script, right now they are only internal to the server!

Three API options.

1. In your main.py or sliders.py or whatever, have a global function with the right name:
```python
def on_session_created(session_context):
   # this function is called on each session create
   pass
```
Weird thing: curdoc() won't work inside the hook functions, because the doc locks aren't held in these hooks, which is the whole point.

2. In your main.py or whatever, have decorated functions
```python
@bokeh.application.hooks.session_created
def on_session_created(session_context):
   pass
```
Weird thing persists here: curdoc() won't work inside the hook functions.

3. Separate file, hooks.py or something, with either of the above two options... curdoc() still won't work but maybe it would be more expected that it doesn't. hooks.py would not be able to share globals with the main script.

Anyway - I like 1 mostly because it is the simplest. We can make curdoc() if called explain what the issue is and what to do instead.

**Comment by mrocklin** [comment]
Agree that the bare `on_session_created` function would be pleasant.  This is also familiar to people used to the setup/teardown functions in test frameworks

**Comment by bryevdv** [comment]
I have a slight pref for the decorator, but only slight. I'm just averse to things that remind me of `Traits`.  

Unrelated, this reminds me we need to fix "imports" in directory app scripts (by fixing up the package path or whatever)

**Comment by havocp** [comment]
hmm, ugh no this won't work because we treat the whole file as a big doc-init function so we can't define the hook functions without initializing the doc. I think it has to be a separate hooks.py or we have to allow the file to contain a "doc initializer" function or something. (if you had the doc initializer function we'd call it to init new docs instead of calling the entire file, if you didn't have it we assume the whole file is a doc initializer... I don't know)

thinking more. there must be a nice way.

**Comment by bryevdv** [comment]
In that case I'd prefer just the sidecar file and keeping `main.py` usage simple and un-variegated , I'm not sure about the name `hooks.py` tho.

**Comment by havocp** [comment]
I went with `server_lifecycle.py` which can contain the four conventionally-named functions.
Better ideas welcome.

You could actually write a whole app without main.py, though I didn't allow that for now (you could use the `on_session_created` to fill in the document, rather than main.py). For now it's an error to be missing main.py.

**Pull request merged**
