### PR TITLE
3.0 -> 2.4.3 backports

### PR DESCRIPTION
**Pull request by ianthomas23**
See discussion #12125.

New functionality:

  * #12113
  * #12034
  * #12084
  * #12121

Changes to/for CI:

  * #11906 (code changes but not removal of baseline images)
  * #11867
  * #11971
  * #12094
  * #11823

Also bugfixes:

  * https://github.com/bokeh/bokeh/pull/12036
  * https://github.com/bokeh/bokeh/pull/11751
  * https://github.com/bokeh/bokeh/pull/12051
  * https://github.com/bokeh/bokeh/pull/12106
  * https://github.com/bokeh/bokeh/pull/11989
  * https://github.com/bokeh/bokeh/pull/11834
  * #11814
  * #11819
  * #12065 
  * #11938 
  * #12098

### CODE REVIEW

**Comment by bryevdv** [comment]
Python tests are just a single SVG failure, we can verify by hand if need be, I am not sure what it would take to fix in CI

**Comment by ianthomas23** [comment]
There's a lot going on here in terms of CI failures. I'll start with bokehjs failures as this passes locally for me on ubuntu 20.04 using chromium 95, so I'll grab some of #11906 to remove MacOS and Windows baseline testing and pin the chromium snap to 95. I won't cherry pick the whole PR as there are ~2700 file changes, mostly deletions of baseline images, and I'd rather keep the changes to a minimum for this release.

**Comment by mattpap** [comment]
>  I won't cherry pick the whole PR as there are ~2700 file changes, mostly deletions of baseline images, and I'd rather keep the changes to a minimum for this release.

Yes, just apply changes to `bokehjs/make/tasks/test.ts` (`baselines_root` specifically), this will disable testing without need for repo churn.

**Comment by bryevdv** [comment]
The build is picking up django 4 which is causing several codebase test failures

**Comment by ianthomas23** [comment]
I'm getting errors when running `mypy bokeh` both locally and in CI:
```
$ mypy bokeh
typings/IPython/core/interactiveshell.pyi:1: note: In module imported here,
typings/IPython/core/getipython.pyi:1: note: ... from here,
typings/IPython/__init__.pyi:1: note: ... from here,
bokeh/io/notebook.py:110: note: ... from here:
typings/IPython/core/history.pyi:1:1: error: Module "typing" has no attribute "Literal"; maybe "_Literal"?  [attr-defined]
    from typing import Literal, overload
    ^
```
The contents of the directory `typings/IPython/core` is the same in this PR as `branch-3.0` now.

Any ideas? `mypy` config perhaps?

**Comment by mattpap** [comment]
2.4 is still on Python 3.7. You will have import missing types from `typing_extensions`.

**Comment by mattpap** [comment]
> `TypeError: Object of type DatetimeRangeSlider is not JSON serializable` in integration tests

This is most likely due to the backported tests depending on changes to integration tests done as part of serialization redesign. You will have to rewrite those tests, specifically element selectors, to how this was done in 2.4.

**Comment by bryevdv** [comment]
@mattpap I think you will need to provide more detailed guidance, or else given this is a terminal 2.4.x release, these tests can be disabled and testing results can be recorded manually.

**Comment by bryevdv** [comment]
```
bokeh/util/hex.py:239: error: Unused "type: ignore" comment
        rx = np.round(x) # type: ignore[no-untyped-call]
```

newer versions of numpy added typings hat were missing before so that is why these are no longer needed.

**Comment by bryevdv** [comment]
Pushed a fix for last codebase issues in https://github.com/bokeh/bokeh/pull/12126/commits/84390ebb239e10d68db29b512b8b9d130cec4462

@ianthomas23 FYI for the future, probably best to avoid `branch-x.y.z` branch names for these in the future. If you have pre-commit hooks installed, it makes it harder to push

```
Protect Git branches.....................................................Failed
- hook id: protect-branches
- exit code: 1

You were about to push to `branch-2.4.3`, which is disallowed by default.
If that's really what you intend, run the following command:

        SKIP=protect-branches git push
```

**Comment by bryevdv** [comment]
Mypy is being pretty infuriating right now. These were not in the last run log
```
tests/unit/bokeh/embed/test_server__embed.py:20: note: In module imported here:
typings/bs4.pyi:2:1: error: Module "typing" has no attribute "Literal"; maybe
"_Literal"?  [attr-defined]
    from typing import IO, Any, Literal
    ^
typings/bs4.pyi: note: In member "__init__" of class "BeautifulSoup":
typings/bs4.pyi:[17](https://github.com/bokeh/bokeh/runs/6414275763?check_suite_focus=true#step:8:17):5: error: Argument 3 to "__init__" becomes "Optional[Any]"
due to an unfollowed import  [no-any-unimported]
        def __init__(self, markup: str | IO[str] = ..., features: _Feature...
        ^
tests/test_examples.py: note: In function "_run_example":
tests/test_examples.py:285:39: error: Argument 2 to "signal" has incompatible
type "Callable[[int, FrameType], NoReturn]"; expected
"Union[Callable[[int, Optional[FrameType]], Any], int, Handlers, None]" 
[arg-type]
            signal.signal(signal.SIGALRM, alarm_handler)
```

**Comment by bryevdv** [comment]
I've skipped the one failing SVG unit test for now (which was in fact previously skipped in the past, before being re-enabled at some point). I checked several SVG examples manually and they all looked good.

**Comment by bryevdv** [comment]
@ianthomas23 Here's a list in no particular order, of bugfix PRs that seem like they would be nice and might apply cleanly. Let me know what you think. I might go ahead and apply some of the really trivial docs/typo ones just to get them out of the way. 

* https://github.com/bokeh/bokeh/pull/11717
* https://github.com/bokeh/bokeh/pull/12051
* https://github.com/bokeh/bokeh/pull/12106
* https://github.com/bokeh/bokeh/pull/11938
* https://github.com/bokeh/bokeh/pull/11918
* https://github.com/bokeh/bokeh/pull/11783
* https://github.com/bokeh/bokeh/pull/11751
* https://github.com/bokeh/bokeh/pull/11674
* https://github.com/bokeh/bokeh/pull/11772
* https://github.com/bokeh/bokeh/pull/11834
* https://github.com/bokeh/bokeh/pull/12098
* https://github.com/bokeh/bokeh/pull/11989
* https://github.com/bokeh/bokeh/pull/12036
* https://github.com/bokeh/bokeh/pull/12004
* https://github.com/bokeh/bokeh/pull/12081

Lastly there is this one, which is a bit larger, but it is from back in Nov so there is a chance it might apply cleanly. Would really be nice if possible, but will have to see. 

* https://github.com/bokeh/bokeh/issues/11803

**Comment by bryevdv** [comment]
Well, as ever, I am too optimistic. I have merged the trivial cases but most of the above do not apply cleanly. The top few just have test conflicts that seem like they might be simple to resolve. The rest are probably not worth effort.

**Comment by bryevdv** [comment]
I built the docs locally with all the current changes and everything looks really great, no issues that I saw in any of the gallery, user guide, or first steps steps sections (included testing various interactions). @tcmetzger if you are inclined, in seems like the Latex custom extensions example could get a note saying that it may not be necessary for many cases.

**Comment by ianthomas23** [comment]
CI passing!

@bryevdv Thanks for all of your help with this. I regretted using the `branch-x-y-z` branch name once I had created the PR and won't make the mistake again. I usually have pre-commit hooks enabled but this week have switched from ex-work laptop to personal one which evidently doesn't have them enabled yet...

**Comment by ianthomas23** [comment]
I've added 3 WebGL bug fixes that weren't too difficult to cherry pick, and also the 3 other bug fixes that Bryan identified as simple to solve. That just leaves the "probably not worth the effort" bug fixes that are in `branch-3.0`.

There are 2 open bug fix PRs that might be worth considering?
  * #12067
  * #12124

**Comment by bryevdv** [comment]
@ianthomas23 Both those seem reasonable to try to port. Why don't you merge this, then kick off a dev build (Actions -> Release Build ->  Run workflow  then enter "2.4.3dev1") and then start a new PR with the wedge hit test (it also needs to be merged)

**Comment by ianthomas23** [comment]
@bryevdv It looks like you'll have to start the dev build:
```
Run if echo "$RELEASE_MAINTAINERS" | grep -qE "^ianthomas23$"; then

User is NOT authorized to build releases, aborting...

Please contact @bokeh/core about conducting releases.
Error: Process completed with exit code 1.
```

**Pull request merged**
