### PR TITLE
Update elements.csv 

### PR DESCRIPTION
**Pull request by Luke-in-the-sky**
First row in elements.csv was one column short: the data has an 'id' column, but the header row is missing the 'id' key.

Adding a comma at the beginning of the whole file does the trick

### CODE REVIEW

**Comment by bryevdv** [comment]
Him, I guess I am curious why this was not breaking things in the past.

**Comment by bryevdv** [comment]
In any case, is there are reason not to name the first column "id" ?

**Comment by Luke-in-the-sky** [comment]
Sure, that would be nice too :) I just thought of introducing the smallest change possible, that's why I limited the edit to introducing a single comma. 
Actually, IMHO, the whole 'id' column should go, it's just redundant info. Do you think that would be too much of a change if a whole column where to be removed?

**Comment by bryevdv** [comment]
I think that would be fine, just need to verify that the (two? elements.py and periodic.py) examples that use it display correctly.

**Comment by bryevdv** [comment]
@Luke-in-the-sky Just FYI we are planning to release `0.11.1` early next week. If you'd like this PR to be included then it will need to be finished/merged by Friday or so.

**Comment by mattpap** [comment]
btw. Erbium is missing CPK (according to wikipedia should be `#00E675`).

**Comment by Luke-in-the-sky** [comment]
@bryevdv Sorry, I'm new to this. Could you tell me a bit more of what needs to be done when you say 'need to be finished/merged'? Thanks

**Comment by fpliger** [comment]
@Luke-in-the-sky thanks for taking care of this..

'need to be finished/merged' means that all the changes you have in mind have been done, commited and pushed. You can add the `ready` label to the PR (or just comment that it's ready if you prefer ) and we will know that it's ready for a review. We will take care of merging and closing it if everything looks good.

**Comment by bryevdv** [comment]
@Luke-in-the-sky I got the impression you wanted to remove the first column, so I have been waiting on that to merge this PR.

**Comment by Luke-in-the-sky** [comment]
Thanks for explaining: it's done now

**Comment by bryevdv** [comment]
@Luke-in-the-sky awesome thanks! If I can trouble you for one last edit as long as we are working on this file can you update the CPK value for erbium as @mattpap described:

> btw. Erbium is missing CPK (according to wikipedia should be #00E675).

Then we will get this merged!

**Comment by Luke-in-the-sky** [comment]
sorry, forgot that one. `ready` now

**Comment by bryevdv** [comment]
Thanks @Luke-in-the-sky !

**Pull request merged**
