### PR TITLE
pan/zoom working with categorical range

### LINKED ISSUE #987: Pan and Zoom in categorical plots.
This seems a feature that people are asking for... related with #601 where a little discussion started.

### PR DESCRIPTION
**Pull request by bryevdv**
issues: closes #987

### CODE REVIEW

**Comment by damianavila** [comment]
OK, this is really great, code looks good to me and I tested without problem in the example you touch and also in some charts so :+1:

**Comment by bryevdv** [comment]
Will merge as soon as tests pass.

**Comment by fpliger** [comment]
Tried with a few examples and works. AWESOME! :+1:

**Comment by bryevdv** [comment]
@bokeh/core tests should pass now, more testing would be welcome

**Comment by damianavila** [comment]
OK, tested again with several examples, working ok, let's get it merged.

**Comment by timelyportfolio** [comment]
added to my local rbokeh and this works

**Pull request merged**
