### PR TITLE
More 3.0 -> 2.4.2 backports

### PR DESCRIPTION
**Pull request by bryevdv**
* [x] #11793 
* [x] #11797
* [x] #11802 
* [x] #11807
* [x] #11808
* [x] #11469

### CODE REVIEW

**Comment by bryevdv** [comment]
not sure why the CI actions did not run 🤷

**Comment by bryevdv** [comment]
@mattpap thoughts on the BokehJS-CI failure? The CI tests did not run yesterday or some reason so this didn't show up until today

**Comment by mattpap** [comment]
> ✗ Bug
 └┬─ in issue #11803
  └── makes properties containing ndarrays always dirty
TypeError: source.get_length is not a function

The test assumes PR #11773. As that can't be back ported, this test has to be modified for 2.4, to include explicit `CDSView` (two instances) configured with the source.

**Comment by bryevdv** [comment]
Makes sense, I won't have time to work on that today, so unless you will, we should just disable the test on `branch-2.4` for now.

**Comment by mattpap** [comment]
I already fixed this locally. I will update the PR together with PR #11469.

**Pull request merged**
