### PR TITLE
Include `Circle` glyph radius in computation of bounds

### LINKED ISSUE #11704: [FEATURE] Include glyph sizing in plot range calculations
A nice convenience would be to take the glyph size into account for auto ranged plots. In the example below, the circles in the left plot are out of range because the plot is apparently scaled to the x/y coordinates (black).

A tangential observation... The inconsistent sizing/overlap can be partially addressed with `circle.radius_dimension` (see #626), but it doesn't seem robust for a packed circle application like this...

**Screenshot of auto ranged output vs desired**
image

**Example Code**
```
from bokeh.plotting import figure
from bokeh.layouts import row
from bokeh.io import show

x = [0.4595279480396895, -0.6065711356206639, -0.0687886392916304, -0.07637863162673651, -0.5244521855365748, 0.46832138015416175]
y = [0.604836077992458, 0.5442297884573969, -0.6203208740702811, 0.624789852804971, -0.08487633209696635, -0.08487633209696635]
r = [0.16571899322942416, 0.16571899322942416, 0.23436204776786676, 0.37055893402381984, 0.4687240955357335, 0.5240494701550029]

#Auto ranging
a = figure(width=500, height=500, title="Auto Ranged Figure")
a.circle(x=x, y=y, radius=r, radius_units='data')
a.circle(x=x, y=y, radius=.01, radius_units='data', color="black")

#Manually ranging
global_min = min([min((y-r, x-r)) for (x, y, r) in zip(x,y,r)]) - 0.1
global_max = max([max((y+r, x+r)) for (x, y, r) in zip(x,y,r)]) + .1
range = (global_min, global_max)

p = figure(width=500, height=500, y_range=range, x_range=range, title= "Manually Ranged Figure")
p.circle(x=x, y=y, radius=r, radius_units='data')
p.circle(x=x, y=y, radius=.01, radius_units='data', color="black")

show(row(a,p))
```

### PR DESCRIPTION
**Pull request by mattpap**
fixes #11704

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap see also https://github.com/bokeh/bokeh/issues/11082

**Comment by mattpap** [comment]
I've been looking for that issue.

**Comment by g-parki** [comment]
I think this is a step in the right direction. One possible issue is the unnecessary white space around smaller, outlying circles because they're demanding space as if they are the largest circle.

png

**Comment by bryevdv** [comment]
If we really want to improve this I think we would have to  split `Circle` in to the circle scatter marker (that only accepts a pixel size, like all other scatter markers) and a circle glyph (that only accepts a radius in data-space units). Presently `Circle` tries to do both and that is what complicates things, especially hit testing and auto-ranging. I think we would have to find a long-term deprecation path rather than just have a break at 3.0 because `p.circle(size=...)` is probably very common. E.g. if `size` is passed, issue a warning and actually call `p.scatter("circle", ...).`

**Comment by mattpap** [comment]
I changed the approach. Instead of overriding `_bounds`, I changed `_index_data` for the `use_radius == true` case. This way precise bounds can be computed. This approach doesn't seem to negatively affect performance.

**Comment by mattpap** [comment]
image

**Comment by mattpap** [comment]
> (...) see also the older issue (...)

I will leave that for 3.1, and make sure all such glyphs participate in auto-ranging and have reasonably tight bounds.

**Pull request merged**
