### PR TITLE
Adding bokeh_tile_provider.py

### LINKED ISSUE #9704: [FEATURE] need to add tile provider demo
This Issue is to request a tile provider demo to showcase all Bokeh tile providers.

In particular, it would be nice to compare the newly added OSM, WIKIMEDIA, and ESRI_IMAGERY tile providers to each other and the existing STAMEN and CARTODBPOSITRON tile providers.

This tile provider demonstration will allow Bokeh to provide open-source alternatives to Google Maps with Open Street Maps as the standard basemap with streets, buildings and other features along with the ESRI_IMAGERY for the satellite view of the same location.

bokeh_tile_demo_screenshot

### PR DESCRIPTION
**Pull request by comperem**
I'm uncertain how to contribute a new example code.
This is my attempt after discussing here: https://discourse.bokeh.org/t/how-to-contribute-documentation/4699/2?u=comperem

- [ X ] issues: fixes #9704 
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@comperem can you rebase/merge on current master? There were some updates to tests (e.g. removing the "unit" mark and adding type annotations) that are causing conflicts with this PR.

**Comment by comperem** [comment]
> @comperem can you rebase/merge on current master? There were some updates to tests (e.g. removing the "unit" mark and adding type annotations) that are causing conflicts with this PR.

@bryevdv, I'm not sure. I'm getting lost. Does the rebase mean making a new fork? I've hunted all the buttons on the existing PR and also a new PR and there's no obvious rebase option.

**Comment by bryevdv** [comment]
@comperem are you familiar with the `git` command line tool? This would be something to do on the command line. 

I think the following might work for you:
```
git pull upstream master
```
That will merge the current master branch of the main repo into your local repo. 

FYI just for the future: it's usually advised to make changes and PR from branches on your fork of the repo, rather than on your master branch. If there are ever any issues or problems it's easier to just blow away a branch and start over. (I have certainly had to on occasion :))

**Comment by bryevdv** [comment]
Another option: you can hit the "Resolve Conflicts" button at the bottom of this PR. That will take you to a diff editor where you can make the file look like what is should, and then the change will be committed from the web UI. 

Alternatively, if you wanted to "start over" then it's probably simplest to delete your fork, and then make and clone the new fork. (Then you could also make a new PR from a branch)

Let me know if I can help further, we can have a quick video call, etc. next week if needed.

**Comment by comperem** [comment]
Ok, @bryevdv , thanks for the help. I'm most comfortable with the command line. I tried the `git pull upstream master` and it barfed because of no upstream. I `git remote add`'ed the upstream branch, which worked, but it still wasn't right on the wen interface.

I deleted the fork, remade the fork, cloned locally, put the `bokeh_tile_demo.py` file in `./examples/plotting/file`, then committed and submitted a new pull request referencing the same issue.

That seemed to work.

This PR can be closed. The other is most relevant.

**Comment by bryevdv** [comment]
superseded by #9710

**Pull request closed without merging**
