### PR TITLE
mpl - accept logscaled axes

### PR DESCRIPTION
**Pull request by keflavich**
bokeh will fail with an `UnboundLocalError` for `laxis` if it is fed a plot with log-scaled axes.  This fixes that.

### CODE REVIEW

**Comment by keflavich** [comment]
This might be related?  https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/cNb948tfEes

**Comment by damianavila** [comment]
I will try it... although I don't think the google group link is related, because he is never using the `mpl` capabilities...

**Comment by bryevdv** [comment]
If scale is log wouldn't it be better to create a log axis?

**Comment by damianavila** [comment]
Yes, a log axis should work better...

**Comment by damianavila** [comment]
@keflavich do you have any example where this is working? Because I tried with semilogx, semilogy and loglog mpl functions and I can not see the log property in the axis... thanks!

**Comment by keflavich** [comment]
@damianavila No, sorry - I only got as far as "not breaking", not "working".  If I am able to find such an example I'll post it and/or fix this PR otherwise.

**Comment by damianavila** [comment]
We can continue working on this PR to figured out why is not using the proper scale.

**Comment by damianavila** [comment]
I investigate a little bit last week... seems to we some weird problems with ranges... I will try to take a new look today/monday

**Comment by damianavila** [comment]
With this diff I have the right equally-spaced tick interval on the y axis, but the line is missed and I don't see any warn in the js console using debug

```diff
(py34devel)[bokeh](pr/2271) git diff
diff --git a/bokeh/mpl.py b/bokeh/mpl.py
index 31b9c68..4c31901 100644
--- a/bokeh/mpl.py
+++ b/bokeh/mpl.py
@@ -277,6 +277,10 @@ class BokehRenderer(Renderer):
             laxis = LinearAxis(axis_label=ax.get_label_text())
         elif scale == "log":
             laxis = LogAxis(axis_label=ax.get_label_text())
+            if location == "below":
+                self.plot.x_mapper_type = "log"
+            elif location == "left":
+                self.plot.y_mapper_type = "log"
         elif scale == "date":
             laxis = DatetimeAxis(axis_label=ax.get_label_text())
```

and this is the example:

```python
import numpy as np
import matplotlib.pyplot as plt
from bokeh import mpl
from bokeh.plotting import show

x = np.arange(0, 10);
y = x**2

plt.semilogy(x, y)
plt.title("Matplotlib semilogy figure in Bokeh")

#plt.show()
show(mpl.to_bokeh(plt.gcf(), name="semilogy"))
```

@bryevdv, do you have any ideas?

**Comment by bryevdv** [comment]
Best guess: mapper type is a figure init arg, not an actual plot property. So setting plot.x_mapper_type probably has no effect. You'll need to create the correct mapper I think

**Comment by bryevdv** [comment]
To elaborate I think you are probably getting a plot with a LogAxis, but a LinearMapper. A quick look at the JSON should confirm or disconfirm that.

**Comment by damianavila** [comment]
This will not hit 0.9.1, we should discuss a better way to support the mpl compat, changing the milestone to short-term

**Comment by bryevdv** [comment]
This PR should probably be superseded and the work go in #2543 The two won't merge cleanly and #2543 is bigger and more comprehensive and changes more.

**Comment by damianavila** [comment]
I agree... closing as superseded by #2543, I will include this there... 
Thanks @keflavich for your work here...

**Pull request closed without merging**
