### PR TITLE
Color mapping improvements

### PR DESCRIPTION
**Pull request by mattpap**
This is a cleaned up version of PR #8765. @jlstevens, I started implementing some of the changes we discussed on Friday.

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap @jlstevens can #8743 and #8765 be closed in favor of this, then?

**Comment by jlstevens** [comment]
@bryevdv I think so, although afaik there are still some fundamental issues with how data can be made accessible to colorbars (unless @mattpap has figured out a suitable approach?)

**Comment by bryevdv** [comment]
@jlstevens @mattpap can you two confer and figure out which if any of these three PRs should still be open?

**Comment by bryevdv** [comment]
@jlstevens @mattpap what is the plan here? I do think it would be remiss not to fix some o the log mapper issues before 2.0

**Comment by bryevdv** [comment]
closing old PR (left branch intact)

**Pull request closed without merging**
