### PR TITLE
Make slider handles updatable from arrow keys

### LINKED ISSUE #6862: Slider keyboard arrows no longer work 0.12.7
The Slider in v0.12.7 no longer responds to keyboard arrows. Confirmed with 0.12.6 it was working.
System: Mac OSX, El Capitan 10.11.6, Chrome 60.0 64-bit

### PR DESCRIPTION
**Pull request by agoodm**
- [x] issues: fixes #6862 

This was adapted from this [example](https://refreshless.com/nouislider/examples/#section-keyboard) in the nouislider documentation.

Tested this with the sliders example app and it works well, but I have yet to try this for sliders with multiple handles.

image

### CODE REVIEW

**Comment by bryevdv** [comment]
cc @mattpap

**Comment by bryevdv** [comment]
@agoodm what happens if the slider has focus and you press something besides an arrow? At a glance, it looks like the property setting and callback code will get called unconditionally. Perhaps the `keypress` function should first check that `e` is ` left or right arrow, and if not, return immediately.

**Comment by agoodm** [comment]
@bryevdv From the python side I couldn't see callbacks being fired from non-arrow keypresses. Nonetheless I think your suggestion is sensible, so I have implemented it.

**Comment by bryevdv** [comment]
@agoodm thanks, there was a linter issue with trailing whitespace, I should have fixed it with a quick edit. 

@mattpap I will plan to merge this tomorrow before a dev build unless you object

**Pull request merged**
