### PR TITLE
Modernized DataTable styling

### PR DESCRIPTION
**Pull request by philippjfr**
The default SlickGrid DataTable CSS styling looks like something straight out of the 90s. In this PR I've tried to update the styling to something more minimal and modern borrowing a little bit from the default styling of Pandas DataFrame reprs in notebooks:

Before:

Screen Shot 2020-08-04 at 1 08 38 PM

After:

Screen Shot 2020-08-04 at 12 39 35 PM

- [ ] issues: fixes #xxxx
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by philippjfr** [comment]
Cc @bryevdv @mattpap

**Comment by mattpap** [comment]
The header has too much contrast in my opinion. I would use a darker shade of gray instead of black.

**Comment by philippjfr** [comment]
Yeah, solid point, think I'd agree. I'll let @bryevdv chime in and then apply all the feedback at once.

**Comment by bryevdv** [comment]
I agree with the lighter get fit the header. I also think a very light grey dotted vertical column separator is ok. Maybe that would actually be worth making configurable through a property though.

**Comment by jbednar** [comment]
By "header", do you mean the dividing line after the column headings? If so, then sure, a lighter line would be nice. 

I'd want more contrast between the rows; the grey-row backgrounds seem too light to be visible (at least on my Retina laptop screen) once the borders are taken away.

**Comment by mattpap** [comment]
> By "header", do you mean the dividing line after the column headings?

Yes.

> I'd want more contrast between the rows; (...)

A lot depends on the screen, because on my main I can see them fairly clearly, but on my laptop almost not at all. But in any case, I would increase that by at least a notch.

**Comment by bryevdv** [comment]
Also agree the bands could get slightly more contrast. If I were to make a short list of the highest value things that we could make configurable in future work it would be:

* vertical sep
* band color
* index column color
* selection row color
* header color
* fonts

**Comment by philippjfr** [comment]
What I settled on:

Screen Shot 2020-08-13 at 7 12 11 PM

**Comment by bryevdv** [comment]
LGTM @philippjfr  I have updated the images and fixed the linter error. I am not sure whats up with the integration tests trying to load that header bg gif

**Comment by philippjfr** [comment]
Yeah, that's very odd, especially since it explicitly no longer references that image. Will try to dig into that now.

**Comment by mattpap** [comment]
> (...) especially since it explicitly no longer references that image.

It still does and requires `background-image: none` to work. This isn't limited to integration tests. I need to make sure that bokehjs tests report this as well in near future. I fixed the issue in the most recent commit.

**Comment by bryevdv** [comment]
Great I will merge this when green and then cut rc1 later this afternoon

**Comment by bryevdv** [comment]
Three similar failures for `header-columns-over-bg.gif`

**Comment by mattpap** [comment]
Fixed again. Hopefully it's the last one.

**Pull request merged**
