### PR TITLE
Temporary fix for Django server resource handling

### LINKED ISSUE #9924: [BUG] Django server resources are not working
As first reported in https://github.com/holoviz/panel/issues/1205 the Django server integration experienced a regression in Bokeh 2.0.1 when the server resources handling was refactored. We will have to update it to serve the JS and CSS resources correctly when the Resources mode='server'. As a quick fix we can instead make the default mode='cdn' for Django server.

### PR DESCRIPTION
**Pull request by philippjfr**
Temporary fix until we can work out how to serve JS and CSS resources correctly when `Resources(mode="server")`.

- [x] issues: fixes #9924
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by mattpap** [comment]
Test failure is unrelated. I will give now a look if the proper fix can be implemented quickly.

**Comment by bryevdv** [comment]
> Test failure is unrelated. I will give now a look if the proper fix can be implemented quickly.

This is cryptic and ambiguous. What do you want to happen? Is this:

> Test failure is unrelated. ***(so this PR should be merged now)*** I will give now a look if the proper fix can be implemented quickly ***(in addition)***

or is it

> Test failure is unrelated. ***(But)*** I will give now a look if the proper fix can be implemented quickly ***(so this PR should not be merged)***

**Comment by philippjfr** [comment]
My interpretation was that @mattpap would see if he could quickly implement a proper fix instead of, not in addition to this PR since if a proper fix is possible the change in this PR should be reverted anyway.

**Comment by mattpap** [comment]
Superseded by PR #9926.

**Pull request closed without merging**
