### PR TITLE
Server section on User Guide

### PR DESCRIPTION
**Pull request by fpliger**
Following #2257 to add missing server sections:

* [x] Authentication/Authorization/Publishing chapter
* ~~[ ] Minimal deployment/server chapter~~
* [x] Add "Streaming Data" chapter
* ~~[ ] Add "Handling large data" chapter~~

### CODE REVIEW

**Comment by bryevdv** [comment]
ping @mcdonc just to be aware of this PR

**Comment by damianavila** [comment]
@fpliger do you want to add more things here? I suppose you want, but not sure in this PR or another one...

**Comment by damianavila** [comment]
@fpliger are you agree with merging this as is for 0.9.1? Or you want to add more thing here?

**Comment by fpliger** [comment]
@damianavila yes.. It's not as desired but better then not adding it, it probably makes sense to merge.

**Comment by damianavila** [comment]
OK, I will fix some typos and minor corrections and merge it.

**Comment by damianavila** [comment]
I just correct typos and formatting... this should be ready to be merge with the current content...

**Comment by fpliger** [comment]
LGTM

**Pull request merged**
