### PR TITLE
Use explicit bs4 HTML parser and fix tests

### PR DESCRIPTION
**Pull request by mattpap**
Fixes failing travis ci's jobs.

### CODE REVIEW

**Comment by bryevdv** [comment]
I already just merged a fix of for this.

**Comment by bryevdv** [comment]
I thought about doing it this way but bs4 regards `lxml` as the "best" parser so I opted to just ensure it is always installed.

**Comment by mattpap** [comment]
@bryevdv, on my computer and on travis ci, bs4 considers `html5lib` the default (you don't have to even specify the dependencies), which is correct because HTML5 is the current web standard. You can also see that our tests are incorrect and that's why they were failing when the default parser in bs4 changed. Also those test could be just rewritten to not consider insignificant whitespace.

**Comment by bryevdv** [comment]
It's debatable that these tests should be sensitive to non-significant whitespace. They should test the DOM structure. If you want to improve the tests, I'd support a PR that compares `div.text.strip()` to the empty string. But please note that I made other fixes to the tests that should be preserved (e.g. a vacuous `AssertTrue` that should have been `AssertEquals`

**Pull request closed without merging**
