### PR TITLE
Adding 2 more themes: night_sky, contrast [ci disable examples]

### LINKED ISSUE #10028: [FEATURE] More default theme for Bokeh
During the PyCon Hatchery Mentories sprint, it has been mentioned that currently There's only 3 default theme and it would be great to have more.

### PR DESCRIPTION
**Pull request by Cheukting**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes #10028
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

No tests added for the themes.

Here are the previews:

**Contrast**
contrast preview 1
contrast preview 2

**Night Sky**
night sky preview1
night sky preview2

### CODE REVIEW

**Comment by bryevdv** [comment]
@Cheukting Cool! Can you add some screen shots to the top of the PR as well?

**Comment by Cheukting** [comment]
working on it, adding pictures is not that easy with github

**Comment by Cheukting** [comment]
Preview pictures added (don't know why some tests failed though)

**Comment by bryevdv** [comment]
@Cheukting it looks like the only failure is just a linter issue about import order:
```
E          # Bokeh imports
E         -from . import _caliber, _dark_minimal, _light_minimal, _night_sky, _contrast
E         +from . import _caliber, _contrast, _dark_minimal, _light_minimal, _night_sky
E          from .theme import Theme
```
If you change the line as shown above (to be in alphabetical order) and push a new commit, then the tests should go green! Let me know if anything is unclear or needs more context

**Comment by Cheukting** [comment]
Sorry I forced push to change the commit message to exclude the example tests

**Comment by bryevdv** [comment]
Thanks for the PR @Cheukting !

@bokeh/dev @birdsarah @hyles-lineata @pavithraes  Any comments or thoughts?

**Comment by pavithraes** [comment]
I like the themes! Thanks @Cheukting :)

**Comment by birdsarah** [comment]
Very nice. I haven't tested, but screenshots look good and I'm in favor of adding and iterating. I would expect iteration to generally be covering more items if needed, as opposed to tweaking core scheme.

**Comment by bryevdv** [comment]
Sounds like 👍 all around, I will go ahead and merge now, thanks @Cheukting !

**Pull request merged**
