### PR TITLE
add Scalar versions of property mixins

### LINKED ISSUE #5648: Line renderer raises the "without value specification" when a ColumnDataSource is used
bokeh 0.12.3

Line renderer raises the JS error, while Circle renderer works as expected. There's probably a workaround to define a separate source column for each value of width (highly inefficient).

```python
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure, show
from bokeh.io import output_notebook, push_notebook

output_notebook(hide_banner=True)

source = ColumnDataSource(dict(x=[1.2, 3.4], y=[3.2, 4.5], sz=[20.5, 40.1], lw=[1.1, 2.2]))

plot = figure()
plot.circle('x', 'y', source=source, size='sz') # This line works fine
plot.line('x', 'y', source=source, line_alpha2='sz') # This line raises 
# Uncaught Error: attempted to retrieve property value for property without value specification
show(plot)
```

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #5648
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

@mattpap if you agree with this general approach, I will:

* add a real `FontSize` prop instead of `String`
* apply these scalar props other places to reduce code dupe (some annotations)
* add more tests
* general clean up

### CODE REVIEW

**Comment by bryevdv** [comment]
FWIW I think we should just go this route rather than try to add a flag to make dataspecs scalar or vector, they are already too complicated, and also have different documentation requirements. Just cleaving by making scalar versions of mixins covers all the cases I can think of without disturbing existing working but complicated code.

**Comment by mattpap** [comment]
In need to look closer at this, but this is pretty much how I would (or will) do this in typescript. One shouldn't view this kind of code as duplication, but as precise specification.

**Comment by bryevdv** [comment]
> I need to look closer at this, but this is pretty much how I would (or will) do this in typescript. One shouldn't view this kind of code as duplication, but as a precise specification.

I think I communicated poorly, I agree with this 100%. My comment about duplication was that some annotations currently do this "by hand" so adding these scalar versions of mixing will reduce duplication there.

**Comment by bryevdv** [comment]
In any case since I have your tentative approval I will finish things up

**Comment by bryevdv** [comment]
Going to save more work for later PRs this is `ready` for review

**Comment by bryevdv** [comment]
I'll merge this this afternoon unless there is objection

**Pull request merged**
