### PR TITLE
Gloo2 typo in Int32Array/Uint32Array

### LINKED ISSUE #4884: BokehJS Fails to load for INLINE in notebook due to duplicated Int32Array
There is a duplicated Int32Array field in Texture2D.prototype._types on line 656 of gloo2.js. I believe this should be Uint32Array. This results in a failure to load BokehJS in the following situation

    from bokeh.resources import INLINE
    from bokeh.io import output_notebook
    output_notebook(resources=INLINE)

### PR DESCRIPTION
**Pull request by lmcinnes**
Fixes #4884 

A very small change.

### CODE REVIEW

**Comment by mattpap** [comment]
@almarklein, perhaps this could be reported upstream?

**Comment by bryevdv** [comment]
ping @almarklein

**Comment by almarklein** [comment]
Thanks, great catch!

**Comment by almarklein** [comment]
Fixed [upstream](https://github.com/vispy/vispy.js/commit/f5b23a587df30b6c1c22fa6c16d0b5fc6751c310)

**Pull request merged**
