### PR TITLE
Fix rendering of arrow with broad lines

### LINKED ISSUE #4667: Arrow and line_width
High value of `line_width` interferes with the arrow tip. Consider this example (bokeh 0.12.0rc2-8-g9bb50c0):

``` python
from bokeh.plotting import figure, output_file, show
from bokeh.models import Arrow, OpenHead, NormalHead, VeeHead

output_file("foo.html")

p = figure(plot_width=600, plot_height=600, x_range=(-0.1,1.1), y_range=(-1,6))

p.add_layout(Arrow(end=NormalHead(line_width=3), x_start=0, y_start=0, x_end=1, y_end=0, line_width=10))
p.add_layout(Arrow(end=OpenHead(line_width=5), x_start=0, y_start=1, x_end=1, y_end=2, line_width=10))
p.add_layout(Arrow(end=VeeHead(line_width=3), x_start=0, y_start=2, x_end=1, y_end=5, line_width=10))

show(p)
```

Output:
screen shot 2016-12-15 at 9 34 33 pm

### PR DESCRIPTION
**Pull request by hargup**
fixes #4667

### CODE REVIEW

**Comment by hargup** [comment]
Now it works when there is arrow head on both sides
good_arrow_head

**Comment by bryevdv** [comment]
@hargup I think this will only work with a completely filled triangle arrow head? With `Vee` arrowhead e.g. I think the line would stop short and leave a gap?

**Comment by hargup** [comment]
> I think this will only work with a completely filled triangle arrow head?

That's True, we discussed this during the sprints and the solution you proposed was to clip the boundary of the arrow head but I couldn't manage to do that.

**Comment by bryevdv** [comment]
@hargup no worries, it's a non-trivial task, especially if the relevant canvas drawing APIs and Bokeh code are not familiar. I am going to close this PR, but will try to work myself on a fix with the clipping idea in the near future. Please keep making other contributions, if you have time, however, thanks!

**Pull request closed without merging**
