### PR TITLE
resolve various deprectations

### LINKED ISSUE #8607: Importing ABCs from collections is deprecated
And will stop working in Python 3.8

Unfortunately `six` has still nor merged a PR to add a move for this. 

```
(base) ❯ grip collections
./_testing/plugins/bokeh.py:
  129 :         from collections import namedtuple
./core/json_encoder.py:
   56 : import collections
  242 :         elif isinstance(obj, collections.deque):
./core/property/container.py:
   24 : import collections
   97 :         return ((isinstance(value, collections.Sequence) or cls._is_seq_like(value)) and
  102 :         return (isinstance(value, (collections.Container, collections.Sized, collections.Iterable))
  104 :                 and not isinstance(value, collections.Mapping))
./core/tests/test_json_encoder.py:
   20 : from collections import deque
./document/document.py:
   37 : from collections import defaultdict
./embed/standalone.py:
   24 : from collections import Sequence
./embed/tests/test_standalone.py:
   21 : from collections import OrderedDict
./embed/util.py:
   24 : from collections import Sequence, OrderedDict
./models/ranges.py:
   26 : from collections import Counter
./plotting/helpers.py:
   21 : from collections import Iterable, OrderedDict, Sequence
./util/tornado.py:
   25 : from collections import defaultdict
```

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #8607
- [x] tests added / passed

### CODE REVIEW

**Comment by mattpap** [comment]
This fixes almost everything, except one tornado and some jupyter/nbconvert related:
```
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nbconvert/exporters/exporter_locator.py:28
  /home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nbconvert/exporters/exporter_locator.py:28: DeprecationWarning: `nbconvert.exporters.exporter_locator` is deprecated in favor of `nbconvert.exporters.base` since nbconvert 5.0.
    DeprecationWarning)
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nbconvert/preprocessors/regexremove.py:41
  /home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nbconvert/preprocessors/regexremove.py:41: DeprecationWarning: Traits should be given as instances, not types (for example, `Int()`, not `Int`). Passing types is deprecated in traitlets 4.1.
    patterns = List(Unicode, default_value=[r'\Z']).tag(config=True)
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/traitlets/traitlets.py:2367
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/traitlets/traitlets.py:2367
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/traitlets/traitlets.py:2367
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/traitlets/traitlets.py:2367
  /home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/traitlets/traitlets.py:2367: DeprecationWarning: Traits should be given as instances, not types (for example, `Int()`, not `Int`). Passing types is deprecated in traitlets 4.1.
    super(Set, self).__init__(trait, default_value, minlen, maxlen, **kwargs)
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/tornado/web.py:1747
  /home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/tornado/web.py:1747: DeprecationWarning: @asynchronous is deprecated, use coroutines instead
    DeprecationWarning)
```
To resolve nbconvert's warnings, we would need to either wait for notebook to update its dependencies or pin nbconvert to version >= 5.4.

**Comment by bryevdv** [comment]
I'll try the pin later today

**Comment by mattpap** [comment]
I'm not sure if this isn't a bug in conda, because I get this weird behavior:
```
$ conda create -n test001 notebook
The following NEW packages will be INSTALLED:
nbconvert          pkgs/main/linux-64::nbconvert-5.3.1-py37_0
```

```
$ conda create -n test001 notebook nbconvert
The following NEW packages will be INSTALLED:
nbconvert          pkgs/main/linux-64::nbconvert-5.4.0-py37_1
```
`notebook` has just a generic dependency on `nbconvert` (no version number, etc.).

**Comment by bryevdv** [comment]
I think we are stuck with the jupyter/tornado ones until there is upstream work

**Pull request merged**
