### PR TITLE
Add DataCube (DataTable with aggregations and expanding/collapsing groups)

### LINKED ISSUE #8100: [Feature Request] Option to collapse DataTable rows
Please refer to [this thread](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/AgWWxSUJuzQ) on Google Groups.

It would be nice to have this feature for tree data structure.

Thanks.

### PR DESCRIPTION
**Pull request by jburgy**
- [x] issues: fixes #8100
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

This PR brings [SlickGrid example: Grouping](http://mleibman.github.io/SlickGrid/examples/example-grouping) to bokeh.  I chose to sub-class DataTableProvider and DataTable rather than inject grouping logic all over the place.  It makes the code easier to grok at the expense of some duplication.  I have added an example and a unit test.  I'm sure there's a better way than 8cabf73 and am open to suggestions.

### CODE REVIEW

**Comment by bryevdv** [comment]
@jburgy The linked example seems compelling (I have not had a chance to check out the PR itself yet). However, I will say that I would be much more comfortable with a new feature of this size if it came with a maintainer. Would you be willing to be added to @bokeh/dev  and also listed as the Code Owner for these new files?

https://github.blog/2017-07-06-introducing-code-owners/

**Comment by bryevdv** [comment]
FYI Here are the currently failing tslint checks:
> [23:30:44] ERROR: 83:3   return-type  expected 'initClass' to have an explicit return type
[23:30:44] ERROR: 125:3  return-type  expected 'extractGroups' to have an explicit return type
[23:30:44] ERROR: 158:3  return-type  expected 'calculateTotals' to have an explicit return type
[23:30:44] ERROR: 172:3  return-type  expected 'addTotals' to have an explicit return type
[23:30:44] ERROR: 190:3  return-type  expected 'flattenedGroupedRows' to have an explicit return type
[23:30:44] ERROR: 205:3  return-type  expected 'refresh' to have an explicit return type
[23:30:44] ERROR: 219:3  return-type  expected 'getLength' to have an explicit return type
[23:30:44] ERROR: 223:3  return-type  expected 'getItem' to have an explicit return type
[23:30:44] ERROR: 233:3  return-type  expected 'getItemMetadata' to have an explicit return type
[23:30:44] ERROR: 269:3  return-type  expected 'collapseGroup' to have an explicit return type
[23:30:44] ERROR: 276:3  return-type  expected 'expandGroup' to have an explicit return type
[23:30:44] ERROR: 288:3  return-type  expected 'render' to have an explicit return type
[23:30:44] ERROR: 342:3  return-type  expected 'initClass' to have an explicit return type
[23:30:44] 
[23:30:44] /home/travis/build/bokeh/bokeh/bokehjs/src/lib/models/widgets/tables/row_aggregators.ts:32:3
[23:30:44] ERROR: 32:3   return-type  expected 'initClass' to have an explicit return type
[23:30:44] ERROR: 49:3   return-type  expected 'initClass' to have an explicit return type
[23:30:44] ERROR: 62:3   return-type  expected 'initClass' to have an explicit return type
[23:30:44] ERROR: 75:3   return-type  expected 'initClass' to have an explicit return type

**Comment by bryevdv** [comment]
Additionally the example itself fails in our examples test:
```
[FAIL] /home/travis/build/bokeh/bokeh/bokeh/_testing/util/chrome_screenshot.js:89
    const text = args.map(({value}) => value.toString()).join(" ")
                                             ^
TypeError: Cannot read property 'toString' of undefined
    at args.map (/home/travis/build/bokeh/bokeh/bokeh/_testing/util/chrome_screenshot.js:89:46)
    at Array.map (<anonymous>)
    at Chrome.Runtime.consoleAPICalled (/home/travis/build/bokeh/bokeh/bokeh/_testing/util/chrome_screenshot.js:89:23)
    at Chrome.emit (events.js:182:13)
    at Chrome._handleMessage (/home/travis/build/bokeh/bokeh/bokehjs/node_modules/chrome-remote-interface/lib/chrome.js:266:18)
    at WebSocket._ws.on (/home/travis/build/bokeh/bokeh/bokehjs/node_modules/chrome-remote-interface/lib/chrome.js:230:22)
    at WebSocket.emit (events.js:182:13)
    at Receiver.receiverOnMessage (/home/travis/build/bokeh/bokeh/bokehjs/node_modules/ws/lib/websocket.js:792:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage (/home/travis/build/bokeh/bokeh/bokehjs/node_modules/ws/lib/receiver.js:422:14)
FAILED
```

**Comment by jburgy** [comment]
@bryevdv yes, I would be willing to be added to @bokeh/dev and also listed as the Code Owner for these new files.  I addressed the tslint issues but am unable to reproduce the other test failures locally, which makes it difficult to address them.  As a matter of fact, I can't seem to run
```
py.test -m examples --report-path=examples.html
```
Is it because I'm running python 3.7?  What version should I use or what module should I install?

```
(bokeh-dev) smtp:bokeh jburgy$ py.test -m examples --report-path=examples.html
================================================================================================== test session starts ===================================================================================================
platform darwin -- Python 3.7.3, pytest-4.4.0, py-1.8.0, pluggy-0.9.0
rootdir: /Users/jburgy/Documents/Jan/bokeh, inifile: setup.cfg
plugins: xdist-1.26.1, metadata-1.8.0, html-1.20.0, forked-1.0.2, cov-2.6.1
collected 4466 items / 4079 deselected / 387 selected                                                                                                                                                                    

Bokeh selenium tests using 'chrome' driver (no-console-error assertions: ON)

tests/test_examples.py FFFFFFsFFFFFFFFFFFFFFFFFFFFFFFFFFF..FFFF
```

> @jburgy The linked example seems compelling (I have not had a chance to check out the PR itself yet). However, I will say that I would be much more comfortable with a new feature of this size if it came with a maintainer. Would you be willing to be added to @bokeh/dev and also listed as the Code Owner for these new files?
> 
> https://github.blog/2017-07-06-introducing-code-owners/

**Comment by bryevdv** [comment]
@jburgy That's awesome to hear. You should have an invite to join @bokeh/dev now. I am going to go ahead and close this PR, so that you can re-submit a new PR on a branch of the main repo (i.e. not on a personal fork). The reason for this is that the full CI tests can only run against branches of this repo, not on forks. 


When you resubmit the new PR, please make sure that the examples.html file and the .vscode config are not checked in. And if you would like to run the codebase tests before you submit:
```
pytest -m codebase 
```
at the top level will run them. 

Once there is a new PR we can sort of the examples test issue, it might be something in the test machinery. Those are the hardest tests to run so maybe this can be an opportunity to better document the process.

**Pull request closed without merging**
