### PR TITLE
Skip pandas_dataframe test

### LINKED ISSUE #4194: disable pandas_dataframe test temporarily
This one test is failing consistently, disabling until a more thorough investigation can be carried out.

### PR DESCRIPTION
**Pull request by birdsarah**
issues: closes #4194

This has caused me a lot of problems in the past and is causing problems again.

### CODE REVIEW

**Comment by birdsarah** [comment]
ping @bryevdv

**Comment by bryevdv** [comment]
Sure, merge when green. Can you also add an issue to investigate? I've also seen this one particular example fail over and over tho I can't figure out what is interesting or different about it.

**Comment by bryevdv** [comment]
So this never actually removed the test, since there was no `.py` extension on the filename in the `yaml` file

**Comment by birdsarah** [comment]
doh! good to know for next time - thanks!

**Pull request merged**
