### PR TITLE
Expose stylesheet model API publicly

### PR DESCRIPTION
**Pull request by mattpap**
This adds the following new models:

- `InlineStyleSheet`
- `ImportedStyleSheet`
- `GlobalInlineStyleSheet`
- `GlobalImportedStyleSheet`

which can be used like this:

```py
from bokeh.models import InlineStyleSheet
stylesheet = InlineStyleSheet(css=".bk-slider-title { background-color: lightgray; }")

slider = Slider(value=10, start=0, end=100, step=0.5, stylesheets=[stylesheet])
```

Global variants are appended to `<head>` and only once, so that the same stylesheet model can be shared between various UI components efficiently. 

I will try to implement #12450 on top of this next. I will leave documentation and examples for #12675, after this is tested in panel. I will follow with a dev release after this is merged.

### CODE REVIEW

**Comment by philippjfr** [comment]
Hurrah! As soon as this is available could we cut a dev release?

**Comment by mattpap** [comment]
@philippjfr, that's been my goal, but I've been unable to start build/deploy workflows (for an unknown reason). I will try again in the morning.

**Comment by m-guggenmos** [comment]
@mattpap  Since I don't have the time for a proper bug report right now, allow me to note here that while `ImportedStyleSheet(url='path/to/file.css')` worked for me, i.e. resulting in `<link rel="stylesheet" href="path/to/file.css">` nested in the shadow root of my component, `GlobalImportedStyleSheet(url='path/to/file.css')` did not work. Inspection of the resulting header showed that the global variant inserts the following code into the header:
```
<style type="text/css">css/plain.css</style>
```
which obviously doesn't work. Tested with Bokeh 3.3.0.

**Comment by bryevdv** [comment]
@m-guggenmos we will need a new issue with a minimal reproducer in order to investigate anything.

**Pull request merged**
