### PR TITLE
support regexes as URL paths in django's bokeh_apps. Fixes #9946.

### LINKED ISSUE #9946: [FEATURE] support regexes as URL paths in Django
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh Project Discourse](https://discourse.bokeh.org).

**Is your feature request related to a problem? Please describe.**
Django server integration only supports fixed-string URL paths in `myproject.urls.bokeh_apps`. This makes it impossible to customize those apps based on URL arguments - I'd like to construct app instances using database objects referenced in URL slugs. 

**Describe the solution you'd like**
Support regexes in `bokeh_apps` as URL patterns.

**Describe alternatives you've considered**
Bypassing `bokeh_apps` entirely and constructing channel's routing by hand everywhere I need it. This would be sad.

Similar behaviour was requested in #9666.

**Additional context**
PR forthcoming. Also tweaks `bokeh.server.contexts._RequestProxy` to better support Django-style request dictionaries.

### PR DESCRIPTION
**Pull request by PeteFein**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes #9946 
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
Given this will have to wait for 2.1 regardless, @PeteFein do you think you can work with @mattpap and/or @philippjfr to add some tests. The Django integration is currently under-tested and we should start being more strict about including at least basic unit tests on PR

**Comment by PeteFein** [comment]
> can work with @mattpap and/or @philippjfr to add some tests. The Django integration is currently under-tested and we should start being more strict about including at least basic unit tests on PR

I'm generally happier to have tests with my PRs, but given that there's very little in the way of existing tests, it wasn't feasible on this one - better Django tests are probably deserve their own standalone issue IMO. I can ask my client if they'd be willing to fund some of my time to work on testing. 

> Given this will have to wait for 2.1 regardless,

Is there a roadmap or rough timeline for 2.1?

**Comment by RyanRio** [comment]
Hey @PeteFein , I'm the creator of bokeh/bokeh-django#4 , happy to see this change. Quick question, what's the purpose of the change in `bokeh/server/contexts.py` for you? It allows one to circumvent the point of the RequestProxy which is to say you can now access `request['_name']` whereas you used to not be able to. (From the documentation - 
image). This will probably not give the desired behavior due to the issues described there also (https://docs.bokeh.org/en/latest/docs/user_guide/server.html#accessing-the-http-request)

**Comment by PeteFein** [comment]
> Quick question, what's the purpose of the change in `bokeh/server/contexts.py` for you? It allows one to circumvent the point of the RequestProxy which is to say you can now access `request['_name']` whereas you used to not be able to.

@RyanRio Under Django, the bokeh `request` is [Channel's scope](https://channels.readthedocs.io/en/latest/topics/consumers.html#scope) which is just a dict (or more specifically, an [AttrDict](https://github.com/bokeh/bokeh/blob/master/bokeh/server/django/consumers.py#L76))... After some poking prompted by your question, it seems I can get what I need from `doc.session_context.request.url_route["kwargs"]["slug"]`, which is the parsed-out value from the matching group in my regex: `bokeh_apps = [ autoload(f"dashboards/(?P<slug>[-a-zA-Z0-9_]+)/", dashboards_views.bokeh_app)]`

More documentation would sure be useful here, as you note in your original ticket. 

It'd also be nice to support Django `path` style patterns, but that's a more complex change to `RoutingConfiguration`, which is constructing several URLs via string manipulation (Django `path`s are complex objects)

**Comment by RyanRio** [comment]
Wouldn't this already work with standard django urls (like <str:example>) because the function being called inside `__add_new_routing` is `url` which according to django docs is 
image, i.e. would support standard django urls, and the routing.url is no longer being escaped, etc. so we shouldn't be breaking it?

Ohhh I see, you were using it to access the url arguments, to put it in perspective the way I currently make do is by using `autoload("perf/table/compare/", tv.compare_handler)` and then in the actual django view I just pass all the args along to `server_document` like so: 
```python
script = server_document(request.build_absolute_uri("/perf/table/compare/"), arguments=kwargs)
kwargs['script'] = script
return render(request, self.template_name, kwargs)
```
and then in `compare_handler` I can access the args on:
` doc.session_context.request.arguments`

So I suppose the simplification here is I can just pass the full url to server_document which is nice :)

**Comment by PeteFein** [comment]
@RyanRio I didn't realize you could pass arguments to `server_document` like that... I think that's cleaner than what I proposed in my PR TBH.  Sure, it's an ugly URL with query parameters, but no one ever really sees it anyway (since it's usually the Django view that gets exposed).

So now I'm not sure if this patch is needed at all.... thoughts?

**Comment by RyanRio** [comment]
@PeteFein Yeah tbh I've gotten used to the 'this url directs to this bokeh app and I'll just pass it whatever arguments it needs instead of having it figure them out from the url' mentality, but I think your change is still helpful! especially to people incoming to bokeh-django and they just want to copy paste their django urls and have it work similar.

**Comment by PeteFein** [comment]
> especially to people incoming to bokeh-django and they just want to copy paste their django urls and have it work similar.

Maybe we should provide a `BokehViewMixin` CBV that adds a `bokeh_script` to the Django context vars and deals with the wiring of passing through arguments, etc.?

I don't totally love the solution I cooked up, it's subtly different from standard Django URLs b/c of the need to construct URLs in `routing.py`.

**Comment by RyanRio** [comment]
@PeteFein `it's subtly different from standard Django URLs b/c of the need to construct URLs in routing.py.` What do you mean? Are you referring to `bokeh_app_config.routes.get_http_urlpatterns()`? If so, the main thing I don't like about this personally is that bokeh basically takes over the entirety of routing and you have to have the knowledge of what bokeh is doing in `get_http_urlpatterns` and `get_websocket_urlpatterns` to add your own http and websocket consumers, or you might mix up the routing. For instance the result of `get_http_urlpatterns` is `self._http_urlpatterns + [url(r"", AsgiHandler)]` - note that it adds in the default `AsgiHandler` already! You do still construct the bokeh urls in `urls.py`, however in the project `urls.py`, not in the application(s).

I do agree with you that it would be great if there was a django-esque way bokeh could add itself in here, like providing a context-processor, etc. for users! Would you mind elaborating on
`Maybe we should provide a BokehViewMixin CBV that adds a bokeh_script to the Django context vars and deals with the wiring of passing through arguments, etc.?` 😄

**Comment by bryevdv** [comment]
@PeteFein  there is currently just a small linter error causing the build fail:

> E         bokeh/server/django/routing.py:20:1: F401 're' imported but unused

Beyond that I have very little/no experience with Django, so I am content to defer to what you and @RyanRio  (and @philippjfr) deem most useful for Django users

**Comment by bryevdv** [comment]
@PeteFein can you fix the unused import? GitHub is not letting me edit the PR directly, so I can't push a quick fix (alternatively you can enable the setting to allow maintainers to edit your PR themselves).

@RyanRio @philippjfr any thoughts or comments about this as is?

**Comment by wearpants** [comment]
I guess this is fine as is, though the overall approach currently in use is kinda janky IMO, and it'd be preferable to cook up something a little more like standard Django as @RyanRio & I discussed [here](https://github.com/bokeh/bokeh/pull/9947#issuecomment-618458084) and [here](https://github.com/bokeh/bokeh/pull/9947#issuecomment-617851756)... a bit busy ATM but can maybe try to rough something out later this week

**Comment by wearpants** [comment]
Actually I don't think this patch is necessary at all, as it's possible to [pass info as query parameters](https://github.com/bokeh/bokeh/pull/9947#issuecomment-617247062) and users never see these URLs to begin with...

**Comment by RyanRio** [comment]
Yeah perhaps this isn't necessary, @PeteFein have you tried using `pull_session`? It appears that if you try to use it in the initial get request, i.e. before autoload.js has done it's thing in the browser it fails to work properly. However if you do it later on, for instance in an ajax request it'll work. The error I get is 'io loop should already have been set'

**Comment by bryevdv** [comment]
Thanks @PeteFein @RyanRio , I am going to go ahead and close this since there is a fair amount of doubt about. @PeteFein if you do work on a "more standard Django" improvement we'd love to review it in a new PR

**Pull request closed without merging**
