### PR TITLE
checking for extra_patterns kwarg and forwarding to BokehTornado

### PR DESCRIPTION
**Pull request by brendancol**
small fix to forward on `extra_patterns` argument from `Server` to `BokehTornado`

### CODE REVIEW

**Comment by bryevdv** [comment]
merge master, should fix TravisCI builds

**Comment by brendancol** [comment]
damn sorry saw comment and also merged. should be no harm done.

**Comment by bryevdv** [comment]
LGTM

**Comment by birdsarah** [comment]
code lgtm (haven't tested locally)

**Pull request merged**
