### PR TITLE
Merges the hipdi work into the layout PR

### PR DESCRIPTION
**Pull request by almarklein**
Works!

### CODE REVIEW

**Comment by almarklein** [comment]
@birdsarah

**Comment by birdsarah** [comment]
@almarklein - there are two defaults files from the bokehjs tests that have been accidentally added to this PR. Suggest squashing after removing so we don't end up with a large addition and removal.

**Comment by birdsarah** [comment]
Fixed it.

**Comment by almarklein** [comment]
Sorry about that! Thanks for the fix.

**Comment by birdsarah** [comment]
Sorry for the delay @almarklein.

**Pull request merged**
