### PR TITLE
Update baselines for Chromium 90

### PR DESCRIPTION
**Pull request by mattpap**

### CODE REVIEW

**Comment by bryevdv** [comment]
Is it time to start looking at something like https://git-lfs.github.com/ ?
 
Aside, what is the criteria for kicking off updates like this?

**Comment by mattpap** [comment]
> Aside, what is the criteria for kicking off updates like this?

Whenever tests break for no good reason other than new version of Chromium was released. It would be much better if we used a fixed version of Chromium and update when we intend to not when we are forced to, but this would require figuring out how to install a specific version Chromium on all three platforms in CI.

**Comment by bryevdv** [comment]
Well the reason I mention `git-lfs` is because is would be nice to easily split out baseline versions by chrome version. CI can always run the latest but we could run older versions manually with whatever version of Bokeh in order to actually observe what changes are

**Comment by mattpap** [comment]
> Is it time to start looking at something like https://git-lfs.github.com/ ?

We have a lot of files but they use little space:
```
$ git ls-files bokehjs/test/baselines/ | wc -l
3348
(mattpap/chromium_90) ~/repo/bokeh
$ du -hcs bokehjs/test/baselines/
27M	bokehjs/test/baselines/
27M	total
```
(that's an upper bound due to how `du` measures sizes).

Perhaps lfs does offer more than just handling large files, but I need to learn what it actually does.

**Pull request merged**
