### PR TITLE
Use premultiplied alpha in WebGL

### PR DESCRIPTION
**Pull request by ianthomas23**
Revert to using premultiplied alpha in WebGL.  It has better cross-platform support and is almost definitely a better approach anyway.

Should fix task 1 of issue #11052, the incorrect rendering of the 10k examples that occurs in CI but annoyingly works fine on my dev machine in both firefox and chrome.

WIP as I need to check the example outputs carefully after CI has run.

### CODE REVIEW

**Comment by mattpap** [comment]
All `examples/webgl` seem to work as expect on Linux (Chromium/FF).

**Comment by bryevdv** [comment]
Also look good on OSX/Safari

**Comment by mattpap** [comment]
However, when testing line10k example, I noticed that the more points there are, the different webgl output is from canvas and svg, though even at 10k there are artifacts, e.g.:
image

```py
import numpy as np
np.random.seed(1)

from bokeh.plotting import figure, save
from bokeh.layouts import row, column

def f(N, backend):
  x = np.linspace(0, 10*np.pi, N)
  y = np.cos(x) + np.sin(2*x+1.25) + np.random.normal(0, 0.001, (N, ))
  p = figure(
    width=400, height=400,
    title=f"A line consisting of {N//1000}k points ({backend})",
    output_backend=backend,
    lod_threshold=None,
  )
  p.line(x, y, color="#22aa22", line_width=3)
  return p

N0 =  10_000
N1 = 100_000

g = lambda N: column([f(N, "canvas"), f(N, "svg"), f(N, "webgl")])

save(row([g(N0), g(N1)]))
```

**Comment by mattpap** [comment]
This wasn't the case on 2.3, but the output wasn't free of artifacts there either.

**Comment by ianthomas23** [comment]
I'd expect things that were wrong before this fix to be differently wrong now.  There are 3 things I know I need to change for short, wide, overlapping lines to be correct.  But worst case now should be that the edges of the lines are filled out with higher alpha than they should have.  This is what I get with 100k points:

Screenshot_2021-03-17 Bokeh Plot

The line is more solid than it should be but otherwise not too bad.  I'd like to be able to reproduce @mattpap's png output.  What OS/browser platform did you use?

**Comment by ianthomas23** [comment]
Scrap my previous comment, I was using the wrong branch.  I can reproduce the problem, and will look into it.

**Comment by ianthomas23** [comment]
I understand the regression now.  If you add `line_join="round"` to the `p.line()` call the output is reasonable.  The maths I am using for bevel joins (the default join type) evidently isn't correct if the line segments are nearly parallel.  If you specify `miter` joins you still see the problem as miters are rendered as bevels if their size exceeds the `miter_limit`.

Either my equations to work out the vertex positions are ill-formed if the segments are nearly parallel, or the reduced floating point precision of the shaders is rounding badly.  Essentially I have tried to be too smart and have been caught out.  Either way it should be a localised fix so I may as well include it in this PR.

Note to self: add new test with nearly-parallel line segments.

**Comment by mattpap** [comment]
> Note to self: add new test with nearly-parallel line segments.

Also when designing such test, make sure to make them run as fast as possible (usually meaning using a small, but representative dataset), because every few milliseconds here and there addup when there are hundreds or thousands of test cases.

**Comment by ianthomas23** [comment]
So for this a good test would be a horizontal line over ~95% of the width of the plot then a couple of up and down swings over the last few pixels to obtain the nearly parallel line segments.

**Comment by bryevdv** [comment]
IIUC you plan to do more work here so I moved back to `WIP` just set back to `ready` whenever is appropriate!

**Comment by ianthomas23** [comment]
On further consideration fixing the regression is more complicated than I thought, so I'd prefer to merge this now and add the regression to the WebGL line rendering issue (#11050).  If others devs agree that is.

**Pull request merged**
