### PR TITLE
add sphinx directive to create versioned links into the repo

### PR DESCRIPTION
**Pull request by bryevdv**
issues: ref #3186 

And update the "examples" link in the main gallery to use it to point to the correct checkout for the actual docs version being viewed.

### CODE REVIEW

**Comment by mattpap** [comment]
We should upload more stuff to S3, so that we could inspect the results.

**Comment by mattpap** [comment]
I tried to check this locally and got:
```
Sphinx error:
Unable to generate reference docs for bokeh.charts.chart_options.ChartOptions, couldn't import module 'bokeh.charts.chart_options'
Makefile:47: recipe for target 'html' failed
```

**Comment by bryevdv** [comment]
> We should upload more stuff to S3, so that we could inspect the results. 
Certainly

Regarding the other maybe I have some junk hanging around, I will try on a clean checkout later.

**Comment by bryevdv** [comment]
@mattpap any objection if I do any minor cleanup required on this PR?

**Comment by mattpap** [comment]
> any objection if I do any minor cleanup required on this PR?

Sure. Thought I would recommend, if you have a finalized, working PR, to just merge it and start another one with the unrelated changes.

**Comment by bryevdv** [comment]
@mattpap I just meant any cleanup needed to get the docs working again (if any) and nothing else

**Comment by bryevdv** [comment]
Actually those errors are simple to fix but I have another open PR that's actually about updating docs, so I'm going to fix on that PR and merge this one as-is.

**Pull request merged**
