### PR TITLE
Update Arrow when the data source is changed

### LINKED ISSUE #9436: [BUG] Arrow glyph does not update
#### software version info
- Bokeh 1.4.0
- Python 3.7.5
- Tornado 6.0.3
- node.js 12.12.0

#### Description of expected behavior and the observed behavior
Arrow should change its length when updating its data via `cds_arrow.data = dict(xS=[0], yS=[1], xE=[new], yE=[1])`.
This worked in Bokeh version 1.0.2  (and Python 2.7).

Using `cds_arrow.stream(dict(xS=[0], yS=[1], xE=[new], yE=[1]),rollover=1)` the update works in both versions.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, Slider, Arrow, OpenHead
from bokeh.layouts import column
from bokeh.io import curdoc

cds_arrow = ColumnDataSource(dict(xS=[0], yS=[1], xE=[1], yE=[1]))
cds_line  = ColumnDataSource(dict(x=[0,1], y=[3,3]))

def slider_callback_data(attr,old,new):
    cds_arrow.data = dict(xS=[0], yS=[1], xE=[new], yE=[1])
    cds_line.data  = dict(x=[0,new], y=[3,3])
    #print(cds_arrow.data) # data is updated but not plotted

def slider_callback_stream(attr,old,new):
    cds_arrow.stream(dict(xS=[0], yS=[1], xE=[new], yE=[1]),rollover=1)
    cds_line.stream(dict(x=[0,new], y=[3,3]),rollover=2)


slider_data = Slider(title="cds.data", value=1.0, start=0.0, end=5.0, step=0.1, width=400)
slider_data.on_change('value',slider_callback_data)

slider_stream = Slider(title="cds.stream", value=1.0, start=0.0, end=5.0, step=0.1, width=400)
slider_stream.on_change('value',slider_callback_stream)

figure_test = figure(title="Example Figure", x_range=(-1,6), y_range=(-0.5,4.5), height=300, width=400, tools="")
figure_test.line(x='x', y='y', source=cds_line)
arrow_glyph = Arrow(end=OpenHead(), x_start='xS', y_start='yS', x_end='xE', y_end='yE',source=cds_arrow)
figure_test.add_layout(arrow_glyph)


curdoc().add_root(column(figure_test, slider_data, slider_stream))

```

#### Screenshots or screencasts of the bug in action

arrow_no_update
When moving the upper slider, only the line updates.
Moving the lower slider, both update correctly.

### PR DESCRIPTION
**Pull request by p-himik**
- [x] issues: fixes #9436
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@p-himik just an FYI: In order to automate release processes with the new branching strategy is to keep track of PRs on milestones as well as issues (simple "time since last release" query will not do in general, will need to query things by milestone to validate proper labeling, etc.)  I've added this to the 2.2 milestone. I'll be going through and adding more recent closed PRs to milestones soon, but go ahead and add milestones to future PRs yourself.

**Comment by p-himik** [comment]
@bryevdv Not sure I follow. I didn't read that discussion mainly because I'm waiting for a proper BEP.
I guess my main question is: if the milestone cannot be put there automatically for whatever reason, how can I possibly determine what to put there? And if it can be put there automatically, why does it have to be a manual process?

**Comment by p-himik** [comment]
GitHub timestamp says that I've been thinking about it for whole 5 minutes, so here's an additional thought piece. When I create a PR I cannot possibly know when it will be merged, if at all. Only the person that merges the PR into master can know what's the version that will have the changes. Is it not correct?

**Comment by bryevdv** [comment]
I should have been more clear: it should be a retrospective addition at the time of merge, that reflects what release branch the PR landed on at the time of merge. I don't see how that can be automated, but am open to any suggestions.

**Comment by p-himik** [comment]
> it should be a retrospective addition at the time of merge
This sentence is perfectly aligned with what I said - the person that merges a PR should be responsible for setting the required label.

> it should match the milestone of any related issue
Doubly that - if an issue has an incorrect (outdated) label, it should be fixed at the time of merging by the same person. Simply because I do not control when and where my PRs are merged.

> I think if the related issue has a milestone, the PR can just start off with the same
> We have tools to check to ensure that all PRs and issues are properly labeled
What is the merit for unmerged PRs? If a PR is not merged and still has some potential for being closed without merging, why force a milestone on it?
If it's just the limitation of some particular tooling that it doesn't distinguish between merged and unmerged PRs, then maybe we should replace/modify the tooling?

> They only want to extract what PRs are specifically for "release x.y.z" is if we put the PRs in a milestone for x.y.z
Please correct me if I'm wrong, but a PR should be merged only into the relevant release branch(es). Thus, after the merge you can easily tell in what release(s) a particular PR ends up. E.g. by `git tag --contains %commit-hash%`.

A higher-level note - the problem of finding out what new changes are in a particular release is common for all Git and not specific to GitHub. But Git itself has no milestones. How do people fare there without GitHub?

Regarding automating it - here's a discussion about it with some links to tools and examples. But no off-the-shelf solution, it seems. https://lab.civicrm.org/infra/gitlab/-/issues/3

**Pull request merged**
