### PR TITLE
Remove `CDSView.source` and infer the source from `CDSView`'s parent

### PR DESCRIPTION
**Pull request by mattpap**
Having a `GlyphRenderer` and its `CDSView` use different data sources is currently technically possible, but doesn't make sense. There is quite a bit of code making sure everything is configured correctly. All of that is unnecessary. This PR removes `CDSView.source` and adds a view for `CDSView` which infers the source from its parent.

### CODE REVIEW

**Comment by bryevdv** [comment]
I'll have to go back and re-cvisit for details but noting that there was a lengthy discussion of view/filter syntax here that should be considered https://github.com/bokeh/bokeh/discussions/11560

**Comment by p-himik** [comment]
I'd have to look at it with quite more care and also go back to the work I've been doing in the context of that view/filter discussion to provide any useful comments, but FWIW right now having a view for a view sounds like a step backwards - right into the uncanny valley of OOP.

**Comment by mattpap** [comment]
> FWIW right now having a view for a view sounds like a step backwards - right into the uncanny valley of OOP.

This has nothing to do with OOP, just the design of bokehjs (having models and views).

**Comment by p-himik** [comment]
Ah, after a more careful pass over the code I see that the two words "view" have different meaning in there.

With that being said, I still can't quite say if I would've done it the same way. But seems like this change is at the very least not detrimental to the ideas in #11560 and actually is probably beneficial.

**Review by bryevdv — APPROVED** [review]

**Pull request merged**
