### PR TITLE
Address leaking memory

### LINKED ISSUE #7468: Increasing memory consumption of bokeh server
mprof

After noticing, that the memory was not released when the session document was destroyed, I tested it with above memoryprofiler on the bokeh example app slider.py and it seems that the memory is not released. (similar to #6744)

My packages are:
asn1crypto 0.22.0 py36h265ca7c_1
biopython 1.69 np113py36_0 anaconda
bleach 2.0.0 py36h688b259_0
bokeh 0.12.13 py36h2f9c1c0_0
bzip2 1.0.6 3 anaconda
ca-certificates 2017.08.26 h1d4fec5_0
certifi 2017.11.5 py36hf29ccca_0
cffi 1.10.0 py36had8d393_1
chardet 3.0.4 py36h0f667ec_1
click 6.7 py36h5253387_0
cloudpickle 0.4.0 py36h30f8c20_0
colorcet 1.0.0 py36h86301b6_0 bokeh
conda 4.4.7 py36_0
conda-env 2.6.0 h36134e3_1
cryptography 2.0.3 py36ha225213_1
cycler 0.10.0 py36h93f1223_0
dask 0.15.4 py36h31fc154_0
dask-core 0.15.4 py36h7045e13_0
datashader 0.6.2 py36_0 bokeh
datashape 0.5.4 py36h3ad6b5c_0
dbus 1.10.22 h3b5a359_0
decorator 4.1.2 py36hd076ac8_0
distributed 1.19.1 py36h25f3894_0
entrypoints 0.2.3 py36h1aec115_2
expat 2.2.5 he0dffb1_0
fontconfig 2.12.4 h88586e7_1
freetype 2.8 hab7d2ae_1
glib 2.53.6 h5d9569c_2
gmp 6.1.2 hb3b607b_0
gst-plugins-base 1.12.2 he3457e5_0
gstreamer 1.12.2 h4f93127_0
h5py 2.7.1 py36h3585f63_0
hdf5 1.10.1 h9caa474_1
heapdict 1.0.0 py36h79797d7_0
holoviews 1.9.1
html5lib 0.999999999 py36h2cfc398_0
icu 58.2 h211956c_0
idna 2.6 py36h82fb2a8_1
imageio 2.2.0 py36he555465_0
intel-openmp 2018.0.0 h15fc484_7
ipykernel 4.6.1 py36hbf841aa_0
ipython 6.1.0 py36hc72a948_1
ipython_genutils 0.2.0 py36hb52b0d5_0
ipywidgets 7.0.0 py36h7b55c3a_0
jedi 0.10.2 py36h552def0_0
jinja2 2.9.6 py36h489bce4_1
jpeg 9b h024ee3a_2
jsonschema 2.6.0 py36h006f8b5_0
jupyter 1.0.0 py36h9896ce5_0
jupyter_client 5.1.0 py36h614e9ea_0
jupyter_console 5.2.0 py36he59e554_1
jupyter_core 4.3.0 py36h357a921_0
krb5 1.14.2 hcdc1b81_6 anaconda
libedit 3.1 heed3624_0
libffi 3.2.1 h4deb6c0_3
libgcc 7.2.0 h69d50b8_2
libgcc-ng 7.2.0 h7cc24e2_2
libgfortran-ng 7.2.0 h9f7466a_2 anaconda
libpng 1.6.32 hda9c8bc_2
libpq 9.6.6 h4e02ad2_0 anaconda
libsodium 1.0.13 h31c71d8_2
libstdcxx-ng 7.2.0 h7a57d05_2
libtiff 4.0.8 h90200ff_9
libxcb 1.12 h84ff03f_3
libxml2 2.9.4 h6b072ca_5
llvmlite 0.20.0 py36_0
locket 0.2.0 py36h787c0ad_1
lzo 2.10 h49e0be7_2 anaconda
markupsafe 1.0 py36hd9260cd_1
matplotlib 2.1.0 py36hba5de38_0
memory_profiler 0.47 py36_0 chroxvi
mistune 0.8.1 py36h3d5977c_0
mkl 2018.0.0 hb491cac_4
msgpack-python 0.4.8 py36hec4c5d1_0
multipledispatch 0.4.9 py36h41da3fb_0
nbconvert 5.3.1 py36hb41ffb7_0
nbformat 4.4.0 py36h31c9010_0
ncurses 6.0 h06874d7_1
networkx 2.0 py36h7e96fb8_0
nodejs 6.11.2 h3db8ef7_0
notebook 5.2.1 py36h690a4eb_0
numba 0.35.0 np113py36_10
numexpr 2.6.2 py36hc561933_2 anaconda
numpy 1.13.3 py36ha12f23b_0
olefile 0.44 py36h79f9f78_0
openssl 1.0.2n hb7f436b_0
pandas 0.21.0 py36h78bd809_1
pandoc 1.19.2.1 hea2e7c5_1
pandocfilters 1.4.2 py36ha6701b7_1
param 1.5.1 py36_0 ioam
paramnb 2.0.2 py36_0 ioam
partd 0.3.8 py36h36fd896_0
pcre 8.41 hc71a17e_0
pexpect 4.2.1 py36h3b9d41b_0
phantomjs 1.9.7 0 bokeh
pickleshare 0.7.4 py36h63277f8_0
pillow 4.2.1 py36h9119f52_0
pip 9.0.1 py36h8ec8b28_3
prompt_toolkit 1.0.15 py36h17d85b1_0
psutil 5.4.0 py36h84c53db_0
psycopg2 2.7.3.2 py36h2b1659c_0 anaconda
ptyprocess 0.5.2 py36h69acd42_0
pycosat 0.6.3 py36h0a5515d_0
pycparser 2.18 py36hf9f622e_1
pygments 2.2.0 py36h0d3125c_0
pyopenssl 17.2.0 py36h5cc804b_0
pyparsing 2.2.0 py36hee85983_1
pyqt 5.6.0 py36h0386399_5
pysocks 1.6.7 py36hd97a5b1_1
pytables 3.4.2 py36h3b5282a_2 anaconda
python 3.6.3 hc9025b9_1
python-dateutil 2.6.1 py36h88d3b88_1
pytz 2017.2 py36hc2ccc2a_1
pywavelets 0.5.2 py36he602eb0_0
pyyaml 3.12 py36hafb9ca4_1
pyzmq 16.0.2 py36h3b0cf96_2
qt 5.6.2 h974d657_12
qtconsole 4.3.1 py36h8f73b5b_0
readline 7.0 hac23ff0_3
requests 2.18.4 py36he2e5f8d_1
ruamel_yaml 0.11.14 py36ha2fb22d_2
scikit-image 0.13.1 py36h14c3975_1
scikit-learn 0.19.1 py36h7aa7ec6_0
scipy 1.0.0 py36hbf646e7_0 anaconda
selenium 3.0.2 py36_0 bokeh
setuptools 36.5.0 py36he42e2e1_0
simplegeneric 0.8.1 py36h2cb9092_0
sip 4.18.1 py36h51ed4ed_2
six 1.10.0 py36hcac75e4_1
sortedcontainers 1.5.7 py36hdf89491_0
sqlite 3.20.1 h6d8b0f3_1
tblib 1.3.2 py36h34cf8b6_0
terminado 0.6 py36ha25a19f_0
testpath 0.3.1 py36h8cadb63_0
tk 8.6.7 h5979e9b_1
toolz 0.8.2 py36h81f2dff_0
tornado 4.5.2 py36h1283b2a_0
traitlets 4.3.2 py36h674d592_0
urllib3 1.22 py36hbe7ace6_0
wcwidth 0.1.7 py36hdf4376a_0
webencodings 0.5.1 py36h800622e_1
wheel 0.29.0 py36he7f4e38_1
widgetsnbextension 3.0.2 py36hd01bb71_1
xarray 0.9.6 py36_0
xz 5.2.3 h2bcbf08_1
yaml 0.1.7 h96e3832_1
zeromq 4.2.2 hbedb6e5_2
zict 0.1.3 py36h3a3bf81_0
zlib 1.2.11 hfbfcf68_1

on
Debian GNU/Linux 8 (jessie)

I build up the example in a dictionary format for the bokeh server, and started as follows:

mprof run bokeh serve --check-unused-sessions 5000 --unused-session-lifetime 5000 --log-level debug testApp

where testApp is the folder containing main.py with the code from slider.py (https://github.com/bokeh/bokeh/blob/master/examples/app/sliders.py)

After monitoring the memory used without any active session for a few minutes, I established ~ 10 sessions which I then disconnected after a few minutes. The bokeh server log showed that bokeh had deleted the documents. However, even after waiting for 40/50 minutes the memory was not released.

### PR DESCRIPTION
**Pull request by bryevdv**
This PR adds a `destroy` method to Document, that removes several places where there might be circular references. However, this alone does not (yet) solve the problem, and a call to `gc.collect()` is required to fully release memory. A fuller solution down the road might be to implement a `destroy` protocol on all models so that they can be responsible for cleaning up any cycles.

- [x] issues: addresses #7468
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
When testing using the code at:

https://groups.google.com/a/continuum.io/d/msg/bokeh/ERe91s9E5bM/hC07xylSAgAJ

Memory is allocated at a rate of ~450MB per session, and after unused sessions are destroyed the memory use returns to reflect only active sessions.

**Comment by bryevdv** [comment]
@LEMUEGGE is it possible for you to test things out with this PR?

**Comment by LEMUEGGE** [comment]
Sure I was following your comments in the issue I filed! I'll probably only have time next week but I'm excited to test it! Thanks a lot in advance :-)

**Comment by bryevdv** [comment]
@LEMUEGGE great, thanks, the user on the ML should be joining to help out. Also I plan to add some fairly extensive memory logging options still, so there is no hurry.

**Comment by jbeanland** [comment]
@bryevdv 

Tested this a bit with a (crappier, pre-optimisation) version of my code and can give you some numbers. This is pulling from pandas.read_sql_query() or pandas.read_pickle() into a dataframe and then assorted widget related plotting fun from there. Here's the memory used from a couple of test runs, I ran each twice with basically identical results.

```operation:      size of 'bokeh' in system memory (MB)
                from sql        from pickle

None:           50.7            50.8
load 1:         222.0           131.2
close 1:        110.9           64.4
load 2:         225.4           164.5
close 2:        124.5           59.8
load 3:         225.5           164.4
close 3:        124.7           60.3
load 4:         225.5           164.4
close 4:        124.7           60.5

open from pd.read_sql() then
engine, conn, df = None; gc.collect:    109.6

open from pr.read_pickle() then
df = None; gc.collect:                  63.9
```
Definitely an improvement. Some weird differences between reading the same dataframe from a pickle and from mysql. Does all lend to the idea that it may be largely a pandas/numpy issue.

Jack

**Comment by bryevdv** [comment]
@mattpap can you look over this today if possible? I'd like to get it merged soon

**Comment by mattpap** [comment]
I don't have anything additional to contribute here. Looks good.

**Comment by ashleygritzman** [comment]
Is anyone still having issues with pandas dataframes and memory continuously increasing? Or am I the only one...?

**Comment by bryevdv** [comment]
@ashleygritzman there have not been any other recent comments about anything. At this point, I would suggest opening a new issue ***with a complete, minimal reproducer***

**Comment by epifanio** [comment]
I am hitting a similar problem, not sure if the reason is the way how I coded my app or a hidden issue within hvplot and xarray - I tried to build a MRE for it, using the following url parameter:

`ncplot?url=https://data.iadc.cnr.it/erddap/tabledap/cct_soil_d2`

After opening 6 tabs, memory consumption reaches almost 2 GB - but after closing them -  the memory is not released. 

What am I doing wrong?

I was  hoping to use the `on_session_destroyed` method, to remove the loaded dataset or the hv plot, but obviously I am using it the wrong way.

the method gets executed, as I can see the print statments in the log but memory is not released - 

with  `/ncplot has 0 sessions with 0 unused` 
docker stats shows: MEM USAGE =1.989GiB 

```python

import hvplot.xarray
import xarray as xr
import panel as pn
import holoviews as hv
import sys
from bokeh.layouts import column, Spacer
import gc

pn.param.ParamMethod.loading_indicator = True
ds = None

def on_server_loaded():
    print("server loaded")
    print("")
    sys.stdout.flush()
    
def on_session_created(session_context):
    print("session created")
    print("")
    sys.stdout.flush()

def on_session_destroyed(session_context):
    print("session destroyed")
    print("")
    print(dir(session_context))
    try:
        del ds
        gc.collect()
    except UnboundLocalError:
        pass
    try:
        del plot_widget
        gc.collect()
    except UnboundLocalError:
        pass
    plot_widget = None
    gc.collect()
    sys.stdout.flush()
    
    
def load_data(url):
    try:
        del ds
        gc.collect()
    except UnboundLocalError:
        pass
    ds = None
    try:
        # attempt to load the dataset via xarray with decode_times=True
        ds = xr.open_dataset(str(url).strip())
    except ValueError as e:
        # attempt to load the dataset via xarray with decode_times=False
        ds = xr.open_dataset(str(url).strip(), decode_times=False)
        print(e)
    except OSError as e:
        print(e)
    if ds and not ds.coords:
        del ds
        gc.collect()
        # the following hack is used when the dataset is served as a tabledap via erdap
        erdapp_uglyness = list(dict(xr.open_dataset(url).dims).keys())[0]
        renamed_vars = {i:i.replace(erdapp_uglyness+".", "") for i in list(xr.open_dataset(url).variables.keys())}
        new_nc_url = url+'?'+'time,'+','.join(list(xr.open_dataset(url).variables)).replace(f"{erdapp_uglyness}.", "").replace(f"time,", "")
        ds = xr.open_dataset(new_nc_url)
        ds = ds.set_coords(f"{erdapp_uglyness}.time")
        ds = ds.swap_dims(s=f"time")
        ds = ds.set_xindex(f"{erdapp_uglyness}.time")
        ds = ds.rename_vars(renamed_vars)
    return ds


        
def plot(var, title=None):
    try:
        del plot_widget
        gc.collect()
    except UnboundLocalError:
        pass
    plot_widget = None
    try:
        del ds
        gc.collect()
    except UnboundLocalError:
        pass
    
    gc.collect()
    ds = load_data(url)
    var = var[0]
    print(f'plotting var: {var}')
    if not title:
        try:
            title = f"{ds[var].attrs['long_name']}"
        except KeyError:
            title = f"{var}"
    else:
        title=title
    if 'featureType' in ds.attrs:
        featureType = ds.attrs['featureType'].lower()
    elif 'cdm_data_type' in ds[var].attrs:
        featureType = ds[var].attrs['cdm_data_type'].lower()
    else:
        featureType = None
    is_monotonic = False
    if featureType == 'timeseries':
        axis_arguments = {'grid':True, 'title': title, 'responsive': True}
        plot_widget =  ds[var].where(ds[var] != 9.96921e36).hvplot.line(**axis_arguments)
        return plot_widget
    if featureType != "timeseries":
        axis_arguments = {'x': ds[var], 'grid':True, 'title': title, 'widget_location': 'bottom', 'responsive': True}
        try:
            plot_widget =  ds[var].where(ds[var] != 9.96921e36).hvplot.line(**axis_arguments)
        except TypeError:
            axis_arguments = {'grid':True, 'title': title, 'widget_location': 'bottom', 'responsive': True}
            plot_widget =  ds[var].where(ds[var] != 9.96921e36).hvplot.line(**axis_arguments)
        except ValueError:
            axis_arguments = {'x': var, 'grid':True, 'title': title, 'widget_location': 'bottom', 'responsive': True}
            plot_widget =  ds[var].where(ds[var] != 9.96921e36).hvplot.line(**axis_arguments)
        return plot_widget        


def on_var_select(event):
    var = event.obj.value
    result = [key for key, value in mapping_var_names.items() if value == var]
    with pn.param.set_values(main_app, loading=True):
        plot_container[-1] = plot(var=result, title=var)
        print(f'selected {result}')


def safe_check(var):
    try:
        ds[var].values
        return var
    except Exception as e:
        # Handle the exception (e.g., log it, return False, etc.)
        print(f"Error processing {var}: {e}")
        return False
    

pn.state.onload(callback=on_server_loaded)
# pn.state.on_session_created(callback=on_session_created)
pn.state.on_session_destroyed(callback=on_session_destroyed)
url = pn.state.session_args.get('url')[0].decode("utf8")

print("++++++++++++++++++++++++ LOADING ++++++++++++++++++++++++++++++++++++")
print(str(url))
print("++++++++++++++++++++++++ +++++++ ++++++++++++++++++++++++++++++++++++")
ds = load_data(url)

if ds:
    plottable_vars = [j for j in ds if len([value for value in list(ds[j].coords) if value in list(ds.dims)]) >= 1]
    plottable_vars = [i for i in plottable_vars if safe_check(i)]
    print("plottable_vars:", plottable_vars )
    mapping_var_names = {}
    for i in plottable_vars:
        if int(len(list(ds[i].coords)) != 0):
            try:
                title = f"{ds[i].attrs['long_name']} [{i}]"
            except KeyError:
                title = f"{i}"
            mapping_var_names[i] = title
            
    # add a select widget for variables, uses long names
    variables_selector = pn.widgets.Select(options=list(mapping_var_names.values()), name='Data Variable')
    variables_selector.param.watch(on_var_select, parameter_names=['value'])
    selected_var = [key for key, value in mapping_var_names.items() if value == variables_selector.value]
    plot_plot = plot(selected_var, title=variables_selector.value)
    plot_container = pn.Column(pn.Row(variables_selector), plot_plot, sizing_mode='scale_both') # , sizing_mode='scale_both'
    main_app = pn.Row(plot_container, Spacer(width=10))
    main_app.servable()

```

**Comment by bryevdv** [comment]
@epifanio I don't use Panel and am not familiar with its implementation or how it makes use of Bokeh. It is a separate project, maintained by a different group of people. If you can post a pure-Bokeh MRE, that is something we can investigate. Otherwise, I can only suggest making an issue on the Panel GH issue tracker since they would be in a position to invetigate starting from a basis of Panel code.

**Comment by epifanio** [comment]
Thanks @bryevdv , I can try to serve the same code using `holoviews` + `bokeh serve`  --  I will replace the drop down menu and the layout with plain bokeh -- working on it :)

**Comment by bryevdv** [comment]
> After opening 6 tabs, memory consumption reaches almost 2 GB - but after closing them - the memory is not released.

> What am I doing wrong?

BTW there is AFAIK no guarantee that system memory stats will go down immediately from a high water mark, absent pressure for the system to actually reclaim it for other uses. There's a more lengthy discussion of this elsewhere that I can't find at the moment but you'll also need to clarify exactly what you are measuring, and most especially whether this is a real issue that is causing real observable problems (i.e. actual OOMs or similar) or just a theoretical worry based on some reported stat. 

Edit: requested smoke check on your end: After all the sessions are destroyed, do something else that will require most of the system memory, and see if the "reported" memory bokeh process does finally go down.

**Comment by epifanio** [comment]
I am close to have a working MRE, but got stuck on how to embed the hv.curve inside a bokeh layout:  https://gist.github.com/epifanio/4bf5368b77c65b07ec112556c2f93a86 

I noticed this issue on a production server, the app consumed all the available memory; I had to shut it down and restart setting a memory limit in the deploy section of docker compose.

**Comment by bryevdv** [comment]
> stuck on how to embed the hv.curve inside a bokeh layout

I can't help with that, maybe @philippjfr @jbednar

**Comment by philippjfr** [comment]
Probably not the right venue for this but you can try using `hv.render(curve)`, which should give you a bokeh model.

**Comment by epifanio** [comment]
Thanks @philippjfr  - that worked :) @bryevdv - here is a working  MRE:
```python
import hvplot.xarray
import xarray as xr
import holoviews as hv
from bokeh.layouts import column
from bokeh.models import Select
from bokeh.io import curdoc
import gc
# hv.extension('bokeh')

 
def safe_check(var):
    try:
        ds[var].values
        return var
    except Exception as e:
        # Handle the exception (e.g., log it, return False, etc.)
        print(f"Error processing {var}: {e}")
        return False

                   
def load_data(url):
    try:
        del ds
        gc.collect()
    except UnboundLocalError:
        pass
    ds = None
    try:
        # attempt to load the dataset via xarray with decode_times=True
        ds = xr.open_dataset(str(url).strip())
    except ValueError as e:
        # attempt to load the dataset via xarray with decode_times=False
        ds = xr.open_dataset(str(url).strip(), decode_times=False)
        print(e)
    except OSError as e:
        print(e)
    if ds and not ds.coords:
        del ds
        gc.collect()
        # the following hack is used when the dataset is served as a tabledap via erdap
        erdapp_uglyness = list(dict(xr.open_dataset(url).dims).keys())[0]
        renamed_vars = {i:i.replace(erdapp_uglyness+".", "") for i in list(xr.open_dataset(url).variables.keys())}
        new_nc_url = url+'?'+'time,'+','.join(list(xr.open_dataset(url).variables)).replace(f"{erdapp_uglyness}.", "").replace(f"time,", "")
        ds = xr.open_dataset(new_nc_url)
        ds = ds.set_coords(f"{erdapp_uglyness}.time")
        ds = ds.swap_dims(s=f"time")
        ds = ds.set_xindex(f"{erdapp_uglyness}.time")
        ds = ds.rename_vars(renamed_vars)
    return ds


def update_plot(attr, old, new, var=None, title=None):
    print('update plot')
    if var is None:
        var = new
        title = new
    if 'featureType' in ds.attrs:
        featureType = ds.attrs['featureType'].lower()
    elif 'cdm_data_type' in ds[var].attrs:
        featureType = ds[var].attrs['cdm_data_type'].lower()
    else:
        featureType = None
    if featureType == 'timeseries':
        axis_arguments = {'grid':True, 'title': title, 'responsive': False}
        plot_widget =  ds[var].where(ds[var] != 9.96921e36).hvplot.line(**axis_arguments)
        #return plot_widget
    if featureType != "timeseries":
        axis_arguments = {'x': ds[var], 'grid':True, 'title': title, 'widget_location': 'bottom', 'responsive': False}
        try:
            plot_widget =  ds[var].where(ds[var] != 9.96921e36).hvplot.line(**axis_arguments)
        except TypeError:
            axis_arguments = {'grid':True, 'title': title, 'widget_location': 'bottom', 'responsive': False}
            plot_widget =  ds[var].where(ds[var] != 9.96921e36).hvplot.line(**axis_arguments)
        except ValueError:
            axis_arguments = {'x': var, 'grid':True, 'title': title, 'widget_location': 'bottom', 'responsive': False}
            plot_widget =  ds[var].where(ds[var] != 9.96921e36).hvplot.line(**axis_arguments)
        #return plot_widget
    try:
        container.children[1] = hv.render(plot_widget)
    except NameError:
        return plot_widget
    

    
ds = load_data(curdoc().session_context.request.arguments['url'][0].decode('utf-8'))

if ds:
    plottable_vars = [j for j in ds if len([value for value in list(ds[j].coords) if value in list(ds.dims)]) >= 1]
    plottable_vars = [i for i in plottable_vars if safe_check(i)]
    print("plottable_vars:", plottable_vars )
    mapping_var_names = {}
    for i in plottable_vars:
        if int(len(list(ds[i].coords)) != 0):
            try:
                title = f"{ds[i].attrs['long_name']} [{i}]"
            except KeyError:
                title = f"{i}"
            mapping_var_names[i] = title

select = Select(title="Select a variable:", value=plottable_vars[0], options=plottable_vars)
select.on_change('value', update_plot)
container = column(select, hv.render(update_plot(attr=None, old=None, new=None, var=select.value, title=select.value)))

curdoc().add_root(container)

```

https://gist.github.com/epifanio/7101870f0ffa5e8d9267f7adc247364d


I can see two issues in the code above:

- loading multiple times the app in several browser's tabs (using sane data url) i.e.:  http://localhost:7000/bkplot?url=https://data.iadc.cnr.it/erddap/tabledap/cct_soil_d2 - after closing the browser, memory is not being teleased
- when loading multiple tabs, the "next" tab will start loading and rendering the app only after the "previous" tabs have completed the rendering

**Comment by bryevdv** [comment]
> when loading multiple tabs, the "next" tab will start loading and rendering the app only after the "previous" tabs have completed the rendering

Well let's take care of the easy one immediately: this is fully expected. The Bokeh server is asynchronous, but not multi-threaded. If you do expensive blocking work... it will block. There may be situation-specific strategies to adopt [1] but the general approach if expensive blocking work cannot be avoided, especially on session startup, is to run multiple Bokeh servers behind a load balancer [as described in the documentation](https://docs.bokeh.org/en/latest/docs/user_guide/server/deploy.html#load-balancing). This kind of horizontal-scaling is the explicit design goal for this scenario. 

[1] E.g. if every session just needs read-only access to the same giant data set then that expensive load could just happen once in a server-start callback, rather than on every single session creation. Or if the blocking work happens in a callback after the session load, users can [delegate it to their own threads](https://docs.bokeh.org/en/latest/docs/user_guide/server/app.html#updating-from-threads). These days, some work that previously had to be done at session creation, might now conceivably be handled in a similar way with threads in a [`DocumentReady`](https://docs.bokeh.org/en/latest/docs/reference/events.html#bokeh.events.DocumentReady) event callback instead.

**Comment by bryevdv** [comment]
BTW there also really needs to be a new issue or discussion for all of this at this point. The OP was closed more than six years ago and it's actually a huge headache to try and follow issues that span multiple years of discussion.

**Comment by epifanio** [comment]
@bryevdv thanks for your comment, the objective of this code is to buiild an app that can take any netcdf  (as a url parameter, pointing to an opendap datasource storing a time series/time series profile) and plot it 
- thus the urls can vary  and the app should be usable by many users at the same time. 

I tried to tie the code into a single method, but I failed in implementing the link between variable selector and plot_update, without re-loaded the data at each variable selection.  I will look into the docs to see if I can improve the MRE and open a new issue - for discussing those two points.

**Comment by bryevdv** [comment]
@epifanio I might not have been clear—there is nothing to discuss *here* for the second point, the Bokeh server is working 100% as intended and expected. The relevant fact of the situation, i.e. that the Bokeh server is asynchronous but not multi-threaded, is not going to change, at all. If you want to discuss ways to make your specific use case work optimally within those expectations, then that is a support question that should be discussed on the community support forum, not the issue tracker: https://discourse.bokeh.org

But please open a new fresh issue for the first point. Besides the stale discussions from years ago, I am already not getting reliable updates about this old closed issue and it is a pain to search for it anew every time.

**Comment by bryevdv** [comment]
@epifanio @philippjfr I cannot repro *any* issue with pure-Bokeh code that allocates a huge array:
```
import numpy as np
from bokeh.plotting import figure, curdoc
p = figure()
p.scatter([1,2,3], [6,4,5])
a = np.arange(100_000_000)
curdoc().add_root(p)
```
Opening up two tabs chews up 1.6 GB as seen in mem logs and in OSX activity monitor:

Screenshot 2024-10-21 at 20 18 47

But after closing both tabs and waiting for the session cleanup to happen, all of the relevant ojbects are all gone:
Screenshot 2024-10-21 at 20 25 57

Note that these stats are reported directly out looking through all of the output of `gc.get_objects()` so if they did exist there is no way they could not show up.



HOWEVER, with the code above, there _are_ objects left ofter:

Screenshot 2024-10-21 at 20 30 19

What I would very much like to see in a new issue is a reproducer that that does not use holoview or hvplot because until there is some evidence otherwise, it is my suspicion that any problems may come from there.

**Comment by epifanio** [comment]
@bryevdv  thank you so much for your time, I reduced the MRE to a simpler example that doesn't involve `holoview` - It uses a combination of `bokeh` and `xarray ` (I tried both bokeh serve and panel serve) - the code below:

```python
import xarray as xr
from bokeh.plotting import figure, curdoc
from bokeh.models import Div

def load_data(url):
    try:
        # attempt to load the dataset via xarray with decode_times=True
        ds = xr.open_dataset(str(url).strip())
    except ValueError as e:
        # attempt to load the dataset via xarray with decode_times=False
        ds = xr.open_dataset(str(url).strip(), decode_times=False)
        print(e)
    except OSError as e:
        print(e)
    if ds and not ds.coords:
        del ds
        # the following hack is used when the dataset is served as a tabledap via erdap
        erdapp_uglyness = list(dict(xr.open_dataset(url).dims).keys())[0]
        renamed_vars = {i:i.replace(erdapp_uglyness+".", "") for i in list(xr.open_dataset(url).variables.keys())}
        new_nc_url = url+'?'+'time,'+','.join(list(xr.open_dataset(url).variables)).replace(f"{erdapp_uglyness}.", "").replace(f"time,", "")
        ds = xr.open_dataset(new_nc_url)
        ds = ds.set_coords(f"{erdapp_uglyness}.time")
        ds = ds.swap_dims(s=f"time")
        ds = ds.set_xindex(f"{erdapp_uglyness}.time")
        ds = ds.rename_vars(renamed_vars)
    return ds


def safe_check(ds, var):
    try:
        ds[var].values
        return var
    except Exception as e:
        # Handle the exception (e.g., log it, return False, etc.)
        print(f"Error processing {var}: {e}")
        return False
    

ds = load_data(url = 'https://data.iadc.cnr.it/erddap/tabledap/cct_soil_d2')
plottable_vars = [j for j in ds if len([value for value in list(ds[j].coords) if value in list(ds.dims)]) >= 1]
plottable_vars = [i for i in plottable_vars if safe_check(ds, i)]
attributes = Div(text=str(plottable_vars))
curdoc().add_root(attributes)
```


After loading a number of tabs, refresh them, then waiting for the datasource attributes to display as text in a `bokeh.models` `Div`.  I then close all the tabs and wait for sessions to be discarded. At the end I have:

```
api_hvplot.1.zj5nduyd0vu9@wps.met.no    | 2024-10-22 12:56:27,575 [pid 7] 0 clients connected
api_hvplot.1.zj5nduyd0vu9@wps.met.no    | 2024-10-22 12:56:27,575 [pid 7]   /hvplot has 0 sessions with 0 unused
api_hvplot.1.zj5nduyd0vu9@wps.met.no    | 2024-10-22 12:56:27,575 [pid 7]   /bkplot has 0 sessions with 0 unused
api_hvplot.3.8u4omvsx5f53@wps.met.no    | 2024-10-22 12:56:27,615 [pid 7] 0 clients connected
api_hvplot.3.8u4omvsx5f53@wps.met.no    | 2024-10-22 12:56:27,615 [pid 7]   /hvplot has 0 sessions with 0 unused
api_hvplot.3.8u4omvsx5f53@wps.met.no    | 2024-10-22 12:56:27,615 [pid 7]   /bkplot has 0 sessions with 0 unused
api_hvplot.2.m2jwkpartqqo@wps.met.no    | 2024-10-22 12:56:27,672 [pid 7] 0 clients connected
api_hvplot.2.m2jwkpartqqo@wps.met.no    | 2024-10-22 12:56:27,672 [pid 7]   /hvplot has 0 sessions with 0 unused
api_hvplot.2.m2jwkpartqqo@wps.met.no    | 2024-10-22 12:56:27,672 [pid 7]   /bkplot has 0 sessions with 0 unused
```

but the memory consumption does't get release:

```
CONTAINER ID   NAME                                          CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O        PIDS
75a56c18658a   api_hvplot.2.m2jwkpartqqo9dj4v5ue73kig        0.00%     1.124GiB / 8GiB       14.05%    50.3MB / 964kB    0B / 307kB       33
fb075e329f46   api_hvplot.3.8u4omvsx5f535gnb9wgld3c9h        0.00%     1.661GiB / 8GiB       20.77%    40.3MB / 802kB    0B / 246kB       33
3ec04456a02c   api_hvplot.1.zj5nduyd0vu9et54kd93fjwc1        0.00%     2.212GiB / 8GiB       27.65%    80.3MB / 11.8MB   586kB / 315kB    33
```

Note, there are 3 replicas, as suggested I tried to scale the app a little bit, so to decrease the waiting on user-side.
At this point I believe the issue is within the use of `xarray` I am not aware of xarray API methods which I can use in some sort of `on_session_close()` method.

May I open a new issue, related to `bokeh` and `xarray`? or continue on discourse?  what do you suggest?

**Comment by bryevdv** [comment]
@epifanio yes, again, for the memory issue there should be a new fresh issue. 

That said, I also cannot reproduce anything with the new code either:

* 3 tabs open, activity monitor reports 543MB in use:

   Screenshot 2024-10-22 at 09 03 54

* tabs closed, after session cull: activity monitor reports memory gone down, `gc.get_objects` reports all objects released:

  Screenshot 2024-10-22 at 09 05 07

I am still skeptical that there is actually an issue with Bokeh itself, rather than something else. Here's where you can add some additional logging for some of the types you are using:

https://github.com/bokeh/bokeh/blob/949d7956f9caaeb78f47d37db2a2f2894bb10afd/src/bokeh/server/tornado.py#L745

i.e. add code there (just edit your local install if thats simplest) to print out any un-reclaimed xarrays or or numpy arrays or netcdf objects ([like the current code does with pandas dataframes](https://github.com/bokeh/bokeh/blob/949d7956f9caaeb78f47d37db2a2f2894bb10afd/src/bokeh/server/tornado.py#L774-L776)) and then open and close tabs, and then *wait for the closed sessions to be culled* and see if there are any unexpected objects left. If there are not, then that means Python itself is telling us that there are no objects of that type, and the memory number that is concerning you is just wrong or else has a different interpretation than expected. If there are unexpected objects left, then that is something to investigate, but any issue still might possibly lie either way those libraries rather than Bokeh itself. This is the kind of info that should go in the new issue. 

FYI this is the invocation to use to get the more detailed logging:
```
 bokeh serve --mem-log-frequency 5000 --stats-log-frequency 5000 --log-level=trace
```

**Comment by epifanio** [comment]
@bryevdv   After a long debug I came to the conclusion that what I experienced is a "docker issue" - I tested both bokeh and panel serve - within my docker swarm containers and outside from a simple python virtual environment - the server running in the venv slowly release the whole memory while the same code with the same load but running under docker doesn't release it. 
The docker behavior is quite weird, if I open a number of tabs to fill some memory (as example: 2GB Ram == 5 Tabs open), after I close and wait .. the 2 GB are not released even if all the session are discarded ( I also let the server running without load for more than 1h) -  After waiting,  if I start to open new tabs, the occupied memory will not increase  until I reach a bigger value (> 2GB which happens after the 6th tab is open) at this point the occupied memory starts to rise ...
 
it looks like the docker container is acting like an expandable drive in a virtual machine (where space is occupied upon request and never released even after delating the files that increased it) -- however, you are super correct that the problem was elsewhere. Thank you for your support and thanks for pointing me to the tornado code, it has been very helpful to debug the isse and know more about how the server works.

**Comment by bryevdv** [comment]
Thanks for the follow-up @epifanio if you do think of anything that could be helpful on our end based on your experiments, please let us know

**Pull request merged**
