### PR TITLE
fix dev fingerprint check on version

### PR DESCRIPTION
**Pull request by bryevdv**

### CODE REVIEW

**Comment by bryevdv** [comment]
Unfortunately, we are also using the binstar API incorrectly somehow. We get this in the build:
```
Using binstar api site https://api.binstar.org
damianavila82's [error] It appears you are already logged in from host testing-worker-linux-docker-fdcb80d2-3232-linux-7 
[error] Logging in again will remove the previous token. 
[error] Otherwise you can login again and specify a different hostname with "--hostname" 
Would you like to continue [Y|n]: 
```

**Comment by damianavila** [comment]
This is probably because it is getting the same travis_build number... which is weird unless you re-run the build from the travisci site... I have set up the --hostame in the .travis.yaml file (iirc) mmm...

**Comment by bryevdv** [comment]
ping @srossross

**Comment by srossross** [comment]
Using binstar login will create a login token on binstar.org for every build.  `binstar login` limits this by removing existing login tokens that were issued on the same machine and username.

I would recommend creating one token that is used for every build.

For example

Run this once:
```sh
binstar auth -n "Travis CI Builds" --scope 'api:write api:read' --out ./tokenfile 
```

Then in your builds do

```
binstar -t $TOKEN upload ....
```

**Comment by srossross** [comment]
You can also give binstar-build a try. The linux has been very stable so far. (Windows and OSX are still in beta)

**Comment by damianavila** [comment]
@srossross, I generated the token with:

`binstar auth --create -n "Travis CI Builds" --scope "api:write api:read" --out ./tokenfile 

and use the token as you suggested:

`binstar -t $TOKEN upload ....`

But I am getting The action you are performing requires authentication, please sign in:
```Using binstar api site https://api.binstar.org
Username: 
```

So still it is asking me the username... I need to set up the username with the token?

**Comment by damianavila** [comment]
OK, I guess I know the problem... it is `binstar -t TOKEN upload`... not `binstar upload -t TOKEN`, 
I will try that change...

**Comment by bryevdv** [comment]
@srossross we will get to using `binstar-build` but that needs to be a scheduled and planned chunk of work. We really need to get a dev build out immediately before @damianavila is diverted to other tasks in the short term.

**Comment by damianavila** [comment]
OK, all seems to be working well know: http://bokeh.pydata.org/en/dev/docs/gallery/iris.html
Using a token is better because it prevent us to have failed builds when we restart it on TravisCI, this is ready for review now...

**Comment by damianavila** [comment]
@bryevdv has looked into it... so merging now...

**Pull request merged**
