### PR TITLE
Custom Tooltip Example #6634.

### PR DESCRIPTION
**Pull request by jordanfreedmanPM**
Adds example to example plotting library utilising the custom tooltip.

image

### CODE REVIEW

**Comment by bryevdv** [comment]
@jordanfreedmanPM This is a nice example! I realized I after we spoke I was a unclear in my description, it's actually custom formatters that are undemonstrated:

http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#formatting-tooltip-fields

I think perhaps one could be added to this example, for example a format on the atomic mass that fixes the number of digits of precision, etc? What do you think?

**Comment by jordanfreedmanPM** [comment]
@bryevdv Sure - sounds good. See updated version:

image

**Comment by bryevdv** [comment]
Thanks @jordanfreedmanPM !

**Comment by jordanfreedmanPM** [comment]
@bryevdv no problem. Let me know if there's any other functionality which is missing in the examples!

**Pull request merged**
