### PR TITLE
only make CORS origin header explicit if origin is known

### LINKED ISSUE #13987: [BUG] If Origin is missing from cookie, autoload js handler fails with Tornado KeyError: 'Origin'
### Software versions

Python 3.10 Bokeh 3.5

### Browser name and version

Fails on both Chrome and Safari

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

The below fail when browser doesn't send Origin cookie in an embedded scenario

bokeh/server/views/autoload_js_handler.py
```python
    async def get(self, *args, **kwargs):
        if self.request.cookies:
            self.set_header("Access-Control-Allow-Origin", self.request.headers["Origin"])
```

### Observed behavior

Potential solution:

bokeh/server/views/autoload_js_handler.py
```python
    async def get(self, *args, **kwargs):
...
origin = self.request.headers.get("Origin")
if origin:
    self.set_header("Access-Control-Allow-Origin", origin)
else:
    self.set_header("Access-Control-Allow-Origin", "*") 
```

### Example code

```Python
Embedded bokeh
```

### Stack traceback or browser console output

host='...', method='GET', uri='/.../app/autoload.js?bokeh-autoload-element=c1fca0ee-4e8e-4073-90b1-53b6fc256bb9&bokeh-app-path=/.../app&bokeh-absolute-url=.../app&resources=none', version='HTTP/1.1', remote_ip='127.0.0.6')\nTraceback (most recent call last):\n  File \"/home/ubuntu/.local/lib/python3.10/site-packages/tornado/web.py\", line 1790, in _execute\n    result = await result\n  File \"/home/ubuntu/.local/lib/python3.10/site-packages/bokeh/server/views/autoload_js_handler.py\", line 63, in get\n    self.set_header(\"Access-Control-Allow-Origin\", self.request.headers[\"Origin\"])\n  File \"/home/ubuntu/.local/lib/python3.10/site-packages/tornado/httputil.py\", line 219, in __getitem__\n    return self._dict[_normalize_header(name)]\
KeyError: 'Origin'

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by pmeier**
- [x] issues: fixes #13987
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

cc @hakan-77

### CODE REVIEW

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
Thanks @pmeier

**Comment by bryevdv** [comment]
@mattpap I added `NEEDS BACK PORT` on the assumption there were will probably be a 3.5.2 at some point

**Comment by mattpap** [comment]
Sure, I already created 3.5.2 milestone. I expect to release patch versions more often from now on.

**Comment by jmargus** [comment]
Would love to get 3.5.2 with this one, breaks the embedding for us at the moment.

**Comment by hakan-77** [comment]
@jmargus same here, we had to downgrade.

**Comment by bryevdv** [comment]
@jmargus @hakan-77 this fix is now available in 3.5.2

**Comment by hakan-77** [comment]
@bryevdv it works. Thanks!

**Pull request merged**
