### PR TITLE
add support for rotating group and subgroup categorical tick labels

### LINKED ISSUE #7643: Option to rotate additional categorical ticks
Currently only the categorical ticks immediately next the axis can be rotated. Add options to rotate higher level categories as well. 

This has come up several times now on SO and the ML list, I can't find that anyone has made an issue yet, though I have asked.

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #7643
- [x] tests added / passed
- [x] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
Here is output:

screen shot 2018-04-02 at 09 01 19

With this code:
```

from bokeh.io import show, output_file
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.plotting import figure
from bokeh.palettes import Spectral5
from bokeh.sampledata.autompg import autompg_clean as df
from bokeh.transform import factor_cmap

output_file("bar_pandas_groupby_nested.html")

df.cyl = df.cyl.astype(str)
df.yr = df.yr.astype(str)

group = df.groupby(('origin', 'cyl', 'mfr'))

source = ColumnDataSource(group)
index_cmap = factor_cmap('origin_cyl_mfr', palette=Spectral5, factors=sorted(df.cyl.unique()), start=1, end=2)

p = figure(plot_width=800, plot_height=300, title="Mean MPG by # Cylinders and Manufacturer",
           x_range=group, toolbar_location=None, tools="")

p.vbar(x='origin_cyl_mfr', top='mpg_mean', width=1, source=source,
       line_color="white", fill_color=index_cmap, )

p.y_range.start = 0
p.x_range.range_padding = 0.05
p.xgrid.grid_line_color = None
p.xaxis.axis_label = "Manufacturer grouped by # Cylinders"
p.outline_line_color = None

p.xaxis.major_label_orientation = "vertical"
p.xaxis.subgroup_label_orientation = "normal"
p.xaxis.group_label_orientation = 0.8


p.add_tools(HoverTool(tooltips=[("MPG", "@mpg_mean"), ("Origin, Cyl, Mfr", "@origin_cyl_mfr")]))

show(p)
```

I am not sure about adding an image test just yet I think some of the positioning of the labels can be improved still.

**Comment by bryevdv** [comment]
@mattpap This is pretty simple and straightforward, I will plan to merge tonight (CST) unless you request otherwise.

**Comment by mattpap** [comment]
@bryevdv, can you add this (or another; perhaps simplified) example as a test to `examples/integration`?

**Comment by bryevdv** [comment]
@mattpap OK will do

**Comment by mattpap** [comment]
OK, when done, LGTM.

**Comment by bryevdv** [comment]
Added test:

screen shot 2018-04-03 at 09 01 41

**Pull request merged**
