### PR TITLE
Update plot palette (#11481)

### LINKED ISSUE #11481: Improve usability with color vision deficiencies
As discussed in https://github.com/bokeh/bokeh/issues/10974, there are several aspects of Bokeh that should be improved to make Bokeh more usable to people with color vision deficiencies:

- [ ] Update the colors/palettes used in Bokeh's documentation, examples, and gallery
- [ ] Review the [palette section in the reference guide](https://docs.bokeh.org/en/latest/docs/reference/palettes.html?highlight=palettes#module-bokeh.palettes) and add more palettes and information on how to accommodate differences in color-vision 
- [ ] Review all of Bokeh's assets (website, docs, etc) and update colors/information where necessary

### PR DESCRIPTION
**Pull request by AnishereMariam**
I updated the linear_cmap plot palette to a more suitable colour

issues: ref #11481

cmap
.

### CODE REVIEW

**Comment by bryevdv** [comment]
Hi @anisheremariam I think I would suggest we actually keep this example as-is. The viridis colormap was especially researched and designed to be the latest matplotlib colormap, on the basis of it being perceptually uniform as well as usable against various color deficiences:

https://www.youtube.com/watch?v=xAoljeRJ3lU

The "cividis" colormap is considered an incremental improvement of viridis, but AFAIK viridis is regarded to be more than adequate in terms of accessibility. Given that, and given that we would have to update many associated project resources (this viridis hexbin has been used in many project materials), I think it is best to just let it stay. 

cc @bokeh/dev

**Comment by ianthomas23** [comment]
Yes, this example has particular significance for Bokeh as it forms part of our brand in some situations. The plot is the background to our submissions to SciPy 2023 so I think it would be best if we kept it as viridis.

**Comment by bryevdv** [comment]
Thanks for the PR @anisheremariam ! I am going to go ahead and close this one for the reasons above

**Comment by AnishereMariam** [comment]
@bryevdv, I understand perfectly.

**Pull request closed without merging**
