### PR TITLE
Add support for scale_alpha argument (make scale alpha configurable)

### LINKED ISSUE #4993: ColorBar - setting outline_line_alpha=0 on Plot causes bar to not appear
This is very odd, but the axes appear but the colorbar doesn't.

Sorry, don't have any sample code.

### PR DESCRIPTION
**Pull request by canavandl**
- [x] issues: fixes #4993
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

Wrap plot_canvas outline draw in ctx save/restore to not poison ctx object.

### CODE REVIEW

**Comment by birdsarah** [comment]
add screenshot test based on the test case.

**Comment by birdsarah** [comment]
tested locally and it works - nice!

**Comment by canavandl** [comment]
here's the screenshot:

screen shot 2016-08-22 at 4 02 13 pm

**Comment by birdsarah** [comment]
brilliant - will merge when green.

**Pull request merged**
