### PR TITLE
Add Colorblind friendly and D3 Category palettes

### LINKED ISSUE #5317: Add a colorblind and D3 palettes
I am interested in adding the seaborn color palettes, particularly the colorblind one.  I find these useful to load in then iterate through when plotting different curves.  Some of the palettes already included (Dark2, Set1, and Set2 from ColorBrewer) work reasonably well, but it would be good to have a better color blind option, and more options in general.  These are the 6 from seaborn I would like to add:

```
SEABORN_PALETTES = dict(
    deep=["#4C72B0", "#55A868", "#C44E52",
          "#8172B2", "#CCB974", "#64B5CD"],
    muted=["#4878CF", "#6ACC65", "#D65F5F",
           "#B47CC7", "#C4AD66", "#77BEDB"],
    pastel=["#92C6FF", "#97F0AA", "#FF9F9A",
            "#D0BBFF", "#FFFEA3", "#B0E0E6"],
    bright=["#003FFF", "#03ED3A", "#E8000B",
            "#8A2BE2", "#FFC400", "#00D7FF"],
    dark=["#001C7F", "#017517", "#8C0900",
          "#7600A1", "#B8860B", "#006374"],
    colorblind=["#0072B2", "#009E73", "#D55E00",
                "#CC79A7", "#F0E442", "#56B4E9"]
)
```

I have little experience with licensing, but looking at [seaborn BSD license](https://github.com/mwaskom/seaborn/blob/master/LICENSE) I believe we can use these as long as we copy the license in as a comment.  I have emailed Michael Waskom to confirm.

Thoughts?

### PR DESCRIPTION
**Pull request by StevenCHowell**
This PR superseeds #5359.

I added 5 palettes, category10, category20, category20b, and category20c from D3 and a [colorblind friendly palette](http://jfly.iam.u-tokyo.ac.jp/color/).  I originally thought the D3 palettes were from vega but they were just pulled in.  I did not find a license for the colorblind friendly plot, but it is also referenced by [ggplot2](http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/) and they just provide the url hyperlink.

As mentioned by @birdsarah and @mattpap, I updated both of the pertinent bokehjs files in addition to the python files:
https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/api/typings/palettes.d.ts
https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/api/palettes.ts

Where is the release document?  I expect an entry related to the added palettes should be added.

- [x] issues: fixes #5317 
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@stvn66 it looks like the `gulp build` is failing on TravisCI and it also fails for me locally. 
```
[11:14:04] Finished 'scripts:compile' after 1.99 μs
[11:14:04] Starting 'scripts:bundle'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Invalid number
```

My guess is that all the RGB hex color numbers need `0x` in front

**Comment by stvn66** [comment]
Good catch, hopefully that fixed it.  Otherwise I may have to try building it and debug it tonight.

**Comment by bryevdv** [comment]
@StevenCHowell Looking good, I think there is probably a typo or some copy-pasta causing the last test failure on the JS side:
```
[16:55:23] Using gulpfile ~/build/bokeh/bokeh/bokehjs/gulpfile.js
[16:55:23] Starting 'defaults:generate'...
[16:55:24] generate_defaults.py: Wrote ./test/common/generated_defaults/models_defaults.coffee with 129 model classes
[16:55:24] generate_defaults.py: Wrote ./test/common/generated_defaults/widgets_defaults.coffee with 19 model classes
[16:55:24] Finished 'defaults:generate' after 933 ms
[16:55:24] Starting 'test'...
[16:55:29] 'test' errored after 4.76 s
[16:55:29] ReferenceError in plugin 'gulp-mocha'
Message:
    Category10_3 is not defined
Stack:
ReferenceError: Category10_3 is not defined
```

**Comment by mattpap** [comment]
As this touches `palettes.ts`, it would be nice to know if TS doesn't complain. Issue:
```
gulp examples --tsjs=palettes.ts
```
This will compile everything, show any errors in `palettes.ts` file, and then compile examples.

**Comment by StevenCHowell** [comment]
I should be able to look at this tonight.  @mattpap, would I run that from the `bokehjs/src/coffee/api/` directory?

**Comment by StevenCHowell** [comment]
Just had a look at `palettes.ts` and saw I did not label the list correctly.  I will fix that then see if the tests pass.export const Category10  = [0x1f77b4, 0xff7f0e, 0x2ca02c]
export const Category10  = [0x1f77b4, 0xff7f0e, 0x2ca02c, 0xd62728]
export const Category10  = [0x1f77b4, 0xff7f0e, 0x2ca02c, 0xd62728, 0x9467bd]
export const Category10  = [0x1f77b4, 0xff7f0e, 0x2ca02c, 0xd62728, 0x9467bd, 0x8c564b]
export const Category10  = [0x1f77b4, 0xff7f0e, 0x2ca02c, 0xd62728, 0x9467bd, 0x8c564b, 0xe377c2]
export const Category10  = [0x1f77b4, 0xff7f0e, 0x2ca02c, 0xd62728, 0x9467bd, 0x8c564b, 0xe377c2, 0x7f7f7f]
export const Category10  = [0x1f77b4, 0xff7f0e, 0x2ca02c, 0xd62728, 0x9467bd, 0x8c564b, 0xe377c2, 0x7f7f7f, 0xbcbd22]
export const Category10  = [0x1f77b4, 0xff7f0e, 0x2ca02c, 0xd62728, 0x9467bd, 0x8c564b, 0xe377c2, 0x7f7f7f, 0xbcbd22, 0x17becf]

**Comment by mattpap** [comment]
@StevenCHowell, from `bokehjs/`, so as usual.

**Comment by StevenCHowell** [comment]
@bryevdv @mattpap,  looks like that was it.

**Comment by bryevdv** [comment]
Brilliant, merging now.

**Comment by bryevdv** [comment]
Thanks @StevenCHowell !

**Pull request merged**
