### PR TITLE
Attempt to make layout less fragile

### PR DESCRIPTION
**Pull request by mattpap**
I'm submitting this to run examples' and integration tests. There will be obvious unit failures.

fixes partially #5518

### CODE REVIEW

**Comment by mattpap** [comment]
Integration tests' output is fun (https://travis-ci.org/bokeh/bokeh/jobs/206983743).

**Comment by bryevdv** [comment]
I'm not sure what's going on. I thought this was related to the AWS outage, there was a service warning on Travis. It's gone now, though. Maybe SauceLabs is experiencing problems?

**Comment by mattpap** [comment]
@bryevdv, I'm pretty sure this is an actual test failure. It's not the first time I see this.

**Comment by mattpap** [comment]
Or maybe not, because other builds are failing as well.

**Comment by bryevdv** [comment]
> Or maybe not, because other builds are failing as well.

All itnregration tests in all builds are currently failing.  AFAICT the "new" screenshot is not getting generated, or can't be saved:
```
INTERNALERROR> FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/bokeh/bokeh/tests/integration/annotations/screenshots/current__test_color_bar__test_color_bar_with_scale_alpha.png'
```

I am going to push a hotfix PR to disable them until I can set aside an entire day to look at what's really wrong (I can't do it today)

**Comment by bryevdv** [comment]
merge/rebase master now

**Comment by bryevdv** [comment]
@mattpap if this is a partial fix, please describe what is fixed by this, and what is left to fix

**Comment by bryevdv** [comment]
Since this doesn't fully fix any other issue, I am making it a standalone "issue PR"

**Comment by bryevdv** [comment]
I"m not too keen on this immediate change as a long term solution but I suppose it will do for a stopgap improvement.

**Comment by mattpap** [comment]
@bryevdv, the first part of this PR (replacing `reduce()`) is an actual fix and allows you to initialize empty layouts. Previously this resulted in an error, which resulted in half-initialized layout, yet allowed to proceed with rendering. The other part is a hack, but at least you know what and why is hacked, instead of silencing everything in a `try-catch` block. The proper solution requires changing how constraints are maintained across layout, but that's a lot of work.

**Pull request merged**
