### PR TITLE
kill node.exe and phantom phanomjs.exe before quitting selenium webdr…

### LINKED ISSUE #8737: Windows phantomjs not killed on selenium termination
I reinstalled a fresh python environment on windows with python 3.7 and pythonenv
I use only pip for package dependencies
When I tried to run tests some failed because temp files were locked.
win32error
test_failures

When driver terminate phantomjs is not correctly killed:
proc_pantomjs

### PR DESCRIPTION
**Pull request by xavArtley**
- [x] issues: fixes #8737

### CODE REVIEW

**Comment by bryevdv** [comment]
@xavArtley we would need to add `psutil` as a dependency for this, so first we would need to make sure it is available both pip and conda installable on all platforms.  Or possibly we could protect the import inside `kill_proc_tree` and conditionally only add the dependency on windows (then still need to verify package availability on windows). Or, if there is some way to do this without `psutil` that's probably ideal.

**Comment by xavArtley** [comment]
I'm not able to retrieve childs pid without `psutils`.
Seems a tricky problem on windows
I'll make a test on `psutils` in sys.modules

**Comment by bryevdv** [comment]
OK, to be clear I am not opposed to just adding `psutils`, as long as it is easily obtainable. On the one hand we already have some optional dependencies for image export, so that'd be OK as well, we just need to document them and use `import_optional` appropriately

**Comment by bryevdv** [comment]
Just for reference, Bokeh's current dependency list is fairly light by my standards, and `six` will disappear later this year

https://github.com/bokeh/bokeh/blob/7e2bff4a66b22ed4743edee365d4f9d7da46283a/setup.py#L89-L98

**Comment by philippjfr** [comment]
I'd certainly prefer it if it was a optional dependency, ``psutils`` is easy to install on conda but it doesn't seem trivial to install when you're using pip, unless I'm mistaken.

**Comment by bryevdv** [comment]
Though, I only see wheels on PyPI for windows:

https://pypi.org/project/psutil/#files

So I suppose optional dependency (i.e. use `import_optional` inside the function) may be the way to go

**Comment by bryevdv** [comment]
@xavArtley this LGTM is it `ready`?

**Comment by xavArtley** [comment]
yes

**Comment by bryevdv** [comment]
Thanks!

**Pull request merged**
