### PR TITLE
Configured Dependabot

### LINKED ISSUE #10263: Configure a Github native Dependabot
**Is your feature request related to a problem? Please describe.**
Dependencies are a headache to manage in any project. Since open source projects depend on other libraries and tools, it becomes a necessity to stay up to date. At the same time we must ensure that a dependency upgrade does not break our code.  Regular updates may need an automated setup to get the best results. Up until now, dependabot had a plug and play version which supported security version updates. Now, after dependabot has moves to github natively, we could leverage its immense potential by configuring it for bokeh. 

**Describe the solution you'd like**
Configure a Github native Dependabot to do the same for us.

**Additional context**
* https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
* https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

### PR DESCRIPTION
**Pull request by nimishbongale**
Fixes #10263

The Github native Dependabot has been successfully configured in my fork.

dependabotbokeh

If there are any custom setting you would like to have, such as who the PR should be assigned to, and if certain dependencies should not be touched or anything of this sort, they can be configured as well. 

Do let me know!

### CODE REVIEW

**Comment by bryevdv** [comment]
@nimishbongale I think there first needs to be a discussion of whether we want this at all. cc @bokeh/core

**Comment by nimishbongale** [comment]
> @nimishbongale I think there first needs to be a discussion of whether we want this at all. cc @bokeh/core

@ byredvd

Alright! Since it was a simple commit, I just decided to raise the PR. I have described the issue in greater detail just now.
Thanks!

**Comment by bryevdv** [comment]
Let's go ahead and close/table this for now @nimishbongale please report back on the issue in ~1-2 months with how frequent individual update PRs come in.

**Comment by nimishbongale** [comment]
> Let's go ahead and close/table this for now @nimishbongale please report back on the issue in ~1-2 months with how frequent individual update PRs come in.

Alright! Will do.

**Pull request closed without merging**
