### PR TITLE
Fix packaging

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/bokeh/bokeh/issues/6113

* Excludes `scripts` and `tests` when looking for packages to install.
* Packages the `tests` so they remain accessible from PyPI packages.

### CODE REVIEW

**Comment by jakirkham** [comment]
Not sure why some of the CI builds are failing, but am nearly certain they have nothing to do with this change.

**Comment by canavandl** [comment]
@jakirkham there's some non-deterministic behavior in our CI tests related layout constraint solver that causes the builds to fail. I've restarted them.

**Comment by jakirkham** [comment]
Thanks. Looks like they come back clean now.

**Comment by bryevdv** [comment]
LGTM

**Pull request merged**
