### PR TITLE
Feature: Added bokehjs disc analyzer to gulp

### PR DESCRIPTION
**Pull request by mistakevin**
We don't have to merge this, but can be useful.
Running `gulp scripts:analyze` will produce an interactive graph like so:
screen shot 2015-08-19 at 1 55 54 pm

### CODE REVIEW

**Comment by bryevdv** [comment]
There is a small irony in not dogfooding Bokeh to generate this...

**Comment by mistakevin** [comment]
Haha, I actually found it while researching the best way to analyze a browserify bundle for a bokeh graph. I'm still thinking about making it in bokeh.

**Comment by damianavila** [comment]
I would like to see a Bokeh version as well... so my proposal would be either:
* delay the merge until we agree on ship it
* actually close it... we can not ship visualization made in other libraries...
I am toward the second option...

@bokeh/core

**Comment by mistakevin** [comment]
I started working on a bokeh version. I'm ok with closing/suspending this PR until I've finished it.

**Comment by damianavila** [comment]
I changed the milestone to short-term, lets close it when you submit the bokeh version so people can play with this a little bit :wink:

**Comment by damianavila** [comment]
And yes, I change my mind quickly if I see some additional value like people divertissement :wink:

**Comment by bryevdv** [comment]
Let's definitely dogfood some code analytics tools. Closing this particular PR tho.

**Pull request closed without merging**
