### PR TITLE
Add note on LaTeX support to wrapped extension examples (katex)

### LINKED ISSUE #11870: Remove katex example, test and docs
Now that we have LaTeX labels, etc, working, we no longer need to demonstrate the use of katex. There is an example, a test and some mentions in the docs about it.

I tried to remove it as part of PR #11869 when I converted the katex Bessel function example, but I ended up with a number of sphinx errors that I didn't understand so I am hoping that @tcmetzger might want to deal with this.

### PR DESCRIPTION
**Pull request by tcmetzger**
This PR adds notes to the wrapped extension examples using katex (`wrapped_extension_full` and `wrapped_extension_base`). 

- [x] issues: fixes #11870

### CODE REVIEW

**Comment by bryevdv** [comment]
I'd really like to just remove these entirely I think their continued presence will be confusing. But then I guess we need some new examples to illustrate the different levels of extensions authoring.  @mattpap do you have any suitable replacements on hand?

**Comment by tcmetzger** [comment]
I agree the goal should definitely be to change the example to something that does not involve LaTeX at all. 

How about in the meantime we merge this PR (and close the original issue), and I’ll create a follow up issue to change the two extension examples. This way we can keep the example in the branch, as a pattern for someone to update it. 

Or just delete it, of course, I’d also be happy to update my PR to do that!

**Comment by bryevdv** [comment]
I'd personally rather just delete them now and make a new milestone-3.0 issue to replace them with something else later

**Comment by bryevdv** [comment]
@tcmetzger I think everyone is agreed on "just remove them entirely immediately"

**Comment by tcmetzger** [comment]
Thanks, I'll update this PR soon!

**Comment by tcmetzger** [comment]
Superseded by #11894

**Pull request closed without merging**
