### PR TITLE
Undeprecate HBox and VBox and add docstrings

### LINKED ISSUE #4496: Undeprecate VBox and HBox
I would like names `VBox` and `HBox` to stay, because they are more meaningful to from UI point of view than the new counterparts.

### PR DESCRIPTION
**Pull request by canavandl**
- [ ] issues: fixes #4496 
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

Undeprecate HBox and VBox and add docstrings explaining behavior and return value (instances of Row and Column).

### CODE REVIEW

**Comment by birdsarah** [comment]
Interesting. I was imagining that if we're keeping them as synonyms then we should re-implement the classes, but they just inherit from Row/Column and don't do anything else. 

@mattpap, how were you thinking the undeprecation would be implemented? I'm fine with what luke's done if it meets your needs.

**Comment by canavandl** [comment]
@birdsarah 's recommendation is probably a better solution. I'll make the change in the AM

**Comment by bryevdv** [comment]
That would require subclassing or model subtyping which is even more obscure. Offhand I think my reference is for the simple functions.

**Comment by bryevdv** [comment]
@mattpap do you have thoughts? we need to come to a decision.

**Comment by bryevdv** [comment]
ping @mattpap we are intending to have an RC today. Do you have any input? AFAICT it meets your request but it would be good for you to confirm this.

**Comment by mattpap** [comment]
@bryevdv, looks good.

**Comment by bryevdv** [comment]
Thanks, merging now

**Pull request merged**
