### PR TITLE
Docs Refs Cleanup (part 4)

### PR DESCRIPTION
**Pull request by bryevdv**
OK I got a little side-tracked by low-level mess in our (internal) callback system. I would appreciate a quick look over this PR since it did involve some test changes. Here is a summary of the commits:

#### Get rid of half-backed cb clone

There was an obscure private abstract API for "cloning"  session callback objects. A simple `copy.copy` will suffice, so I ripped all that out. 

There is still some things to consider here. As it stands, session callbacks like `NextTickCallback` are partially constructed, later modified in some places, and copied and modified in other places. It's very convoluted. In another PR I will try find a better, clearer pattern for the lifecycle and ownership of these objects, but this change at least trims the codepaths a bit.

#### remove callback cruft on server contexts

There were mandatory abstract APIs for e.g. `add_next_tick_callback` on `ServerContext` and I could not find any reason for them to exist! They were used in some tests, but nowhere else. I updated the test to actually use the APIs that users would use, e.g. `doc.add_next_tick_callback` in a `modify_doc` and I think that actually improves the tests, more closely modeling actual usage. 

I think the original point of the test with the context was to somehow maintain that session callbacks happened in `bokeh.client`sessions outside the server. We have deprecated and removed `session.loop_until_closed` so I 100% do not care about dealing with or maintaining any of that. 

#### callback ids mandatory except user-facing APIs

There are several layers of APIs like "add periodic callback", e.g. at the user facing `Document` level and down to the tornado callback groups. Previously, an ID could be omitted and one would be generated at any level. This is confusing and potentially a problem because the ID is necessary for being able to remove the callback later. So the only place that should generate default IDs automatically is the top-level user-facing API, to guarantee that the `callback.id` on the returned callback is always the right one to pass to the the "remove" methods.

### CODE REVIEW

**Comment by bryevdv** [comment]
I should add: I actually think storing callbacks on e.g. a `SessionContext` for a session instead of directly on the `Document` for a session might make very good sense in terms of reducing the complexity of `Document`. But that's tangential to the callback API removal here, which was on *Server* contexts (I can't really think of any good reason for that)

**Comment by bryevdv** [comment]
The *version* test is suddenly failing for some reason
```
tests/unit/bokeh/util/test_version.py F.........                         [100%]

=================================== FAILURES ===================================
_________________________ Test___version__.test_basic __________________________

self = <test_version.Test___version__ object at 0x7f34f89f8b90>

    def test_basic(self) -> None:
        assert isinstance(buv.__version__, str)
>       assert buv.__version__ == get_versions()['version']
E       AssertionError: assert '50a0a40' == '50a0a40-dirty'
E         - 50a0a40-dirty
E         + 50a0a40

tests/unit/bokeh/util/test_version.py:45: AssertionError
```

why would the CI checkout be dirty?

**Comment by bryevdv** [comment]
OK other PRs are failing the same way so this must be some change in the CI environment.

**Comment by bryevdv** [comment]
Ok there were some panel issues, and pulling on some mypy strings helped fix I think. But sometimes the panel test discovery randomly fails with this:
```
panel/widgets/file_selector.py:19: in <module>
    from .select import CrossSelector
panel/widgets/select.py:210: in <module>
    if bokeh_version < '2.3.0':
../distutils/version.py:52: in __lt__
    c = self._cmp(other)
../distutils/version.py:337: in _cmp
    if self.version < other.version:
E   TypeError: '<' not supported between instances of 'str' and 'int'
```
any idea @philippjfr  ?

**Comment by philippjfr** [comment]
Honestly no, never seen that running the panel tests. It's just using `distutils.version.LooseVersion` for the comparison.

**Comment by bryevdv** [comment]
You can get that error with versions that `LooseVersion` does not understand
```python
>>> LooseVersion("v2") < "2.3.0"
TypeError: '<' not supported between instances of 'str' and 'int'
```
But I am really at a loss as to why `bokeh.__version__` could or would ever be something that `LooseVersion` does not understand, when looked at in CI. I will try to add some diagnostic printing in the job to see if anything turns up.

**Comment by bryevdv** [comment]
@mattpap @philippjfr this would be the problem then:
```
+ python -c 'import bokeh; print(bokeh.__version__)'
0ab43d5
```

Is this because we do a shallow clone? If so, why does it ever work sometimes at all?

**Comment by bryevdv** [comment]
@philippjfr OK with the other PR merged, panel tests are running now. It looks like  all the same unrelated failures we ahve previously identified 👍 It will be good to get those skipping or running clean to help with evaluating downstream impact.

**Comment by bryevdv** [comment]
Local testing with dask also all seems to be functioning exactly as expected, so I will go ahead and merge this to move on. I'll plan to cut a new dev build tonight or tomorrow.

**Pull request merged**
