### PR TITLE
Make Bokeh work in frozen scripts

### PR DESCRIPTION
**Pull request by severinsimmler**
This PR fixes a bug concerning the interaction between Bokeh and PyInstaller by using Jinja2's `FileSystemLoader` instead of `PackageLoader` (which is currently not supported by PyInstaller), and adjusting the path to the `_templates` folder. It should also fix issues with other freezing tools (like py2exe in #799). However, PyInstaller is probably the most widely used freezing tool and is still actively maintained (unlike e.g. py2exe, whose last release is almost four years old).

Since the changes are in an `if getattr(sys, 'frozen', False)` block (as described in the [PyInstaller documentation](http://pyinstaller.readthedocs.io/en/stable/runtime-information.html)), this PR shouldn't break anything for the "live" use.

PyInstaller itself does not copy the `bokeh/core/_templates` folder (which contains files to be loaded by `bokeh/core/templates.py`). When a bundled app starts up, the bootloader stores the absolute path to the bundle folder in `sys._MEIPASS` – and this is where I tell Jinja2 to look for the `_templates` folder.

If you now freeze the script with PyInstaller, the `_templates` folder must be explicitly copied with `--add-data _templates:_templates` (or in the `.spec` file), but that's something the PyInstaller people should mention in their documentation (if my PR is merged, I can get this going).

I'm not sure how to test this (for continuous integration). Creating a bundled app and check if it works seems to be a bit too much for this, well, pretty special use case?

The changes are tested locally on my machine with Bokeh 0.12.16 and PyInstaller 3.3.1 on Ubuntu 18.04 and Python 3.6.5. This is the minimal example that worked:

```python
from bokeh.plotting import figure, output_file, show

# prepare some data
x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]

# output to static HTML file
output_file("lines.html", title="line plot example")

# create a new plot with a title and axis labels
p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')

# add a line renderer with legend and line thickness
p.line(x, y, legend="Temp.", line_width=2)

# show the results
show(p)
```

If there is anything else I can do, let me know!

### CODE REVIEW

**Comment by bryevdv** [comment]
> Creating a bundled app and check if it works seems to be a bit too much for this

Thanks for the PR @severinsimmler  I'm going to go ahead and merge this now, since I'd like it to be in the release coming up, but I do think making a bundled app and testing it would be the best approach. That kind of test could go in the informational `downstream` build. I'd definitely be happy to accept a PR for tests later and I think that would be the best guarantee that this stays maintained.

**Comment by axil** [comment]
I've found and fixed two more issues when freezing the bokeh with pyinstaller, see bokeh PR8038 and pyinstaller PR3607.

**Comment by lukasz-migas** [comment]
Sadly this broke the not-maintained `py2exe `compiler which does not use `sys._MEIPASS`

**Comment by bryevdv** [comment]
@lukasz-migas if you have a way to make it work with both, I'm happy to accept a PR. Otherwise this is a very low on the priority already, and if we have to choose between an supporting an unmaintained tool, and a maintained on, we will go with the latter.

**Pull request merged**
