### PR TITLE
add update docker-tools (resubmit)

### LINKED ISSUE #9581: Update dockertools
@bryevdv @Karel-van-de-Plassche 

Following up on the [discussion how to use Docker for deployments](https://discourse.bokeh.org/t/deploying-bokeh-app-on-google-app-engine-gae-with-docker/4469/10) I am planning to update `docker-tools`.

Looking at the current Dockerfiles, I see `alpine` is used as the base image. Assuming that many Bokeh apps requires `pandas`, and following [these recommendations as to which Docker image is best for Python deployments](https://pythonspeed.com/articles/base-image-python-docker-images/) may plan is to:

- [X] add short explanation on the pro's and cons of different images
- [X] add a table on the various Dockerfiles to summarize their intent (as examples, with different approaches)
~~- [ ] add `Dockerfile-from-pip`, which~~

~~  - is based on `python:3.7-slim` for apps requiring numpy/scipy/pandas~~
~~  - can serve as a template for other Bokeh deployments via `requirements.txt`~~
~~  - uses `demo.bokeh.org` as an example~~
- [x] add `docker-tools/debian/Dockerfile` for building images using `debian-slim` and `conda`
~~- [ ] add `docker-tools/debian/Dockerfile-dev` for building image for development following [the developers guide for getting set up](https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html#devguide-setup)~~
- [x] add a section on how to deploy on Google App Engine

`Dockerfile-from-pip`
```
FROM python:3.7-slim

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
WORKDIR /some_app

RUN apt-get update \
    && apt-get install gcc -y \
    && apt-get clean
    
COPY . .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

EXPOSE 8080
bokeh serve --port 8080 \
   ...
```

Please let me know what your thoughts are on this, after which I wil submit a PR.

### PR DESCRIPTION
**Pull request by dkapitan**
- [ ] issues: fixes #9581 

* add new folder structure
* add background in README.md
* add new Dockerfiles

Please disregard previous PR. Too many changes since my last pull (messed up my forked repo). This PR is based on a fresh fork.

### CODE REVIEW

**Comment by bryevdv** [comment]
@dkapitan  I will take a look at the details as soon as I am able, in the mean time, here are the linter issues that are failing the build:
```
E       AssertionError: Code quality issues:
E         File contains trailing whitespace: docker-tools/README.md, line 89.
E         File does not end with a newline: docker-tools/debian/Dockerfile, line 87
E         File does not end with a newline: docker-tools/debian/Dockerfile-pip, line 47
E         File does not end with a newline: docker-tools/debian/app.yaml, line 2
```

**Comment by bryevdv** [comment]
@dkapitan will you be able to make the linter fixes?

**Comment by dkapitan** [comment]
@bryevdv 
done! figured out running `pytest tests/codebase/test_code_quality.py` is what I need to run before PR ... :-)

**Comment by bryevdv** [comment]
@dkapitan is this ready for merge or fif you want to work on the TODO's in this PR?

**Comment by dkapitan** [comment]
@bryevdv it's ready for merge. The open todo pertains to setting up the development workflow which requires a lot more thinking. At least for me :-)

**Pull request merged**
