### PR TITLE
Add custom code quality analytics

### LINKED ISSUE #4168: Apply basic code quality rules to all source files
Currently we only inspect `*.py` files, but leave `*.coffee`, `*.ts`, `*.rst`, .., ..., ... alone.

### PR DESCRIPTION
**Pull request by mattpap**
fixes #4168

- [x] add custom code quality checks
- [x] exclude `bokeh/server/static/{js,css}`
- [ ] ~~use `.gitignore` to exclude files, e.g. `bokehjs/examples/*/*.js`~~
- [x] fix all errors
- [ ] ~~clean up `setup.cfg`~~

### CODE REVIEW

**Comment by bryevdv** [comment]
@Maggie-M can  probably help with the "fix all errors" part once the script is working fully.

**Comment by mattpap** [comment]
> use .gitignore to exclude files, e.g. `bokehjs/examples/*/*.js`

That would be fun, but for now it's too much work.

**Comment by mattpap** [comment]
I had to disable max_line_length test, because there are too many failures to fix now. Additionally, there are cases where long lines are acceptable, e.g. inline base64-encoded images in less files (thought those should be replaced with proper tooling that less gives us).

**Comment by mattpap** [comment]
@bokeh/dev, please review this today.

**Comment by almarklein** [comment]
LGTM

However, we are already using flake8, for which we currently ignore [all errors and warnings except a few](https://github.com/bokeh/bokeh/blob/master/setup.cfg#L14-L15). Why not simply include more tests there, or remove the global excludes and exclude all the tests that we don't care about?

>  had to disable max_line_length test, because there are too many failures to fix now.

We have the max line length set to 160 for now.

**Comment by mattpap** [comment]
@almarklein, flake8 works only (as far I can tell) with python files. This is the reason for this PR. Ultimately we will have one set of rules across all files and then use domain specific tools (like flake8).

**Comment by bryevdv** [comment]
@mattpap it's checking (and failing) `bokeh/__conda_version__.py` which should probably be excluded:

https://travis-ci.org/bokeh/bokeh/jobs/134439611#L2571

**Comment by bryevdv** [comment]
I made the change, will merge when green.

**Comment by bryevdv** [comment]
@mattpap OK just adding the file to the exclusions did not work, it seems the exclusions have to be directories?

**Comment by birdsarah** [comment]
Only had the opportunity for a quick look as I'm at pycon, but looks good. Thanks for doing this.

**Comment by bryevdv** [comment]
OK, added support for file exclusions. I also added a main check at the end so it can just be run, my local pytest is completely borked and I can't spend any more time trying to fix it today.

**Comment by bryevdv** [comment]
Tests appear to be passing now. Will merge when green. The file exclusion stuff could probably be removed when/if you come back to add `.gitignore` support, but it should do for now. As you said, the PR should be merged sooner rather than later.

**Pull request merged**
