### PR TITLE
try specify nvm explicitly

### LINKED ISSUE #2878: nvm install failing on TravisCI
```
$ nvm install stable
Version 'stable' not found - try `nvm ls-remote` to browse available versions.
The command "nvm install stable" failed and exited with 3 during .
Your build has been stopped.
```

### PR DESCRIPTION
**Pull request by bryevdv**
issues: closes #2878

### CODE REVIEW

**Comment by bryevdv** [comment]
Observed JS build and tests passing, merging

**Comment by bryevdv** [comment]
@mistakevin @birdsarah this might need to be revisited but I am merging this to get unblocked right now

**Comment by bryevdv** [comment]
ping @damianavila for long term solution too

**Comment by damianavila** [comment]
working on it now...

**Comment by mistakevin** [comment]
This looks good to me.

**Pull request merged**
