### PR TITLE
to_mpl fix for DateTimeAxis

### PR DESCRIPTION
**Pull request by jfrydendall**
I tried to make fix as less intrusive as possible. If I had to pass the complete props dictionary to make_axis the code needed restructuring. As **bryevdv** mentioned in #2973 the code is a bit hackish anyways. 

Please review the change

### CODE REVIEW

**Comment by bryevdv** [comment]
@bokeh/dev this LGTM by inspection, @jfrydendall can you post a small code example that exercises this?

**Comment by jfrydendall** [comment]
Sure - I have tested for the linear axis and the datetime axis. Bokeh does not support mpl log axis as far as I understand. Therefore only a test for the two above axes.

```python
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from bokeh import mpl
from bokeh.plotting import output_file, show

def test_datetime_axis():
    ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))
    ts = ts.cumsum()
    
    df = pd.DataFrame(np.random.randn(1000, 4), index=ts.index, columns=list('ABCD'))
    df = df.cumsum()
    df.plot(legend=False)
    
    output_file("dataframe.html")
    
    show(mpl.to_bokeh())

def test_linear_axis():
    x = np.linspace(-2 * np.pi, 2 * np.pi, 100)
    y = np.sin(x)
    z = np.cos(x)
    
    plt.plot(x, y, "r-", marker='o')
    plt.title("Matplotlib Figure in Bokeh")
    
    # dashed lines work
    plt.plot(x, z, "g-x", linestyle="-.")
    
    output_file("sincos.html")
    
    show(mpl.to_bokeh())
    
if __name__=="__main__":
    test_linear_axis()
    test_datetime_axis()
```

**Comment by damianavila** [comment]
I will review this afternoon...

**Comment by damianavila** [comment]
Sorry for the delay, LGTM

**Comment by bryevdv** [comment]
Thanks @jfrydendall !

**Pull request merged**
