### PR TITLE
Slider demo - animated bubble

### PR DESCRIPTION
**Pull request by birdsarah**
Things to consider:
* [x] data needs to be put on S3 and downloaded with sampledata.download
* [x] notebook does not explain where data came from
* [x] there isn't a plain python script version of this
* [x]  includes custom templating and paired down css - uses new template_variables option on file_html

### CODE REVIEW

**Comment by birdsarah** [comment]
You can see the notebook on nbviewer here: http://nbviewer.ipython.org/github/birdsarah/bokeh/blob/gapminder_animated_bubble_example/examples/glyphs/animated_bubble/Gapminder%20-%20animated%20bubble%20plot.ipynb

**Comment by birdsarah** [comment]
Note that Gapminder's policy on the data is "They can be reused freely but please attribute Gapminder." - http://www.gapminder.org/data/

**Comment by damianavila** [comment]
Are we targeting to include this demo in 0.9.1? BTW, it is a really nice example.

@mattpap can you point us to the process to upload data to s3?

@birdsarah, a plain py examples would be nice too, but probably without all the explanations you can have in the notebook... also you probably should explain more about the templating stuff in the notebook itself...

**Comment by bryevdv** [comment]
Yes I think it should absolutely go in 0.9.1

**Comment by damianavila** [comment]
@birdsarah, do you really have time to work on this for 0.9.1?
Thanks!

**Comment by birdsarah** [comment]
Yes. I can do that this week. Should I keep it all in a folder under glyphs as it currently is?

**Comment by damianavila** [comment]
>Should I keep it all in a folder under glyphs as it currently is?

mmm... not sure where to put this... @bokeh/core ideas??

**Comment by birdsarah** [comment]
Test is failing: https://travis-ci.org/bokeh/bokeh/jobs/68599218#L1105

This will continue to happen until files are uploaded to s3.

Otherwise, I think this is ready to for review.

Although, I noticed that examples/glyphs/interactive_bubble/gapminder.py is not being run when nosetests runs.

**Comment by damianavila** [comment]
LGTM... merging now...

**Pull request merged**
