### PR TITLE
[feature] Feature/dataframe

### PR DESCRIPTION
**Pull request by cloudformdesign**
# Pandas Dataframe Plotter
The purpose of this code is to automatically plot scaled dataframes containing any level of weird data.

It is intended to speed up visualization of pandas dataframes

## Goals
- Plot labeled dataframe data (done)
 - properly colorize all data so it is easily viewable (completed for < 12 columns)
- remove any NaN's on it (done)
- determine it's variability. If it is highly variable (with data going all over the place), use a rolling box-whisker plot instead (done)
- Add trend lines. For box-whisker this is the movement of the mean. Otherwise it is a linear fit to each bin (done)
- Scale data on at least two axis. Detect data ranges and match the best data with the correct axis. If a new axis has to be created to view scale, create it. (not done, having issues getting access and re-scalling figure)
 - potentially support more y axis in the future (future)

### CODE REVIEW

**Comment by damianavila** [comment]
Sorry to not give you early feedback, I will take a look on this today...

**Comment by damianavila** [comment]
This is very interesting... pinging @bryevdv and @fpliger... because it seems a good candidate for a chart implementation in the long term??

Btw, @cloudformdesign 

About the get_axis thing... I don't know what are you trying to do... you can easily access the xaxis and yaxis from a figure, or you can eventually use the query system to do it... in any case, for your function, something like this will work:

```
def get_axis(fig):
    yaxis = fig.yaxis
    assert len(yaxis) == 1
    # I am having issues getting the axis here.
    return yaxis[0]
    
f = figure()
ax = get_axis(f)
ax.[whatever]

To fix the range issue you have to make something like this:

`f = figure(y_range=[df.vardata.min(), df.vardata.max()])`

**Comment by fpliger** [comment]
> This is very interesting... pinging @bryevdv and @fpliger... because it seems a good candidate for a chart implementation in the long term??

Definitely good candidates and material to include. With the builders design it should be really straightforward to add those...

There's one thing I'm not sure though is if `dataframe` should be considered as a chart `builder` (like for the `whisker` implementation) or it should be considered more like a `composer`.

**Comment by cloudformdesign** [comment]
Ok, I've started a github project to work on this. I made some changes to the above notebook and it is coming together well.

https://github.com/cloudformdesign/dataframe

Please take a look and make any comments. I am going to continue to improve this as I work on it

**Comment by cloudformdesign** [comment]
@damianavila the problem is that I prefer having the user pass in the figure. Because of that, I cannot change the settings on the figure through instantialization.

I have managed to change the range correctly with `fig.y_range = Range1d(start=total_min, end=total_max)`

**Comment by cloudformdesign** [comment]
Some features I want to add:
 - Support for different kinds of plots, especially histograms. I think for this I will need to support both separate x and y axis (so that highly variable data can be plotted alongside non-variable)
 - Add in buttons to turn on/off data and redraw the plot. It looks like this can be easily done through http widgets, so I will be working on that
   - Related, switch between histogram and line graph with a toggle button
   - Maybe have a button so the whole suit of graphs are drawn? I've seen some video presentations on the power of bokeh for selecting data and dynamically plotting it. Any input on how this could be done would be appreciated
- Add a `head` spreadsheet view of the data that you can select and play with interractively
  - I have seen this done in a video
  - Selecting data highlights data on the chart
  - filtering data removes it.

The overall goal is to be able to just call
```
bokeh.charts.dataframe(fig, df)
show(fig)
```
And for you to have an interactive UI that you can use to play with and explore any dataset, using a variety of charts.

Is this currently feasible with the tools available? From what I have seen it totally is. Someone just needs to put time into (aka me!)

**Comment by bryevdv** [comment]
Closing per BEP-1

**Pull request closed without merging**
