### PR TITLE
Bryanv/8397 sri script tags

### LINKED ISSUE #8397: Using Subresource Integrity with CDN URLs
Would be nice for all CDN URLs provided by Bokeh in HTML documents to use [Subresource Integrity (SRI)]( https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity ). At this point basically [all browsers support SRI]( https://caniuse.com/#feat=subresource-integrity ) with the exception of IE (though Edge supports it). This would ensure that browsers checksum content from these CDN URLs and only use content if the checksums match.

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #8397
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

@mattpap this is fairly quick and dirty, and I don't love it. But in light of #9615 my main goal was to be as unobtrusive as possible to existing codepaths. Once things are re-founded on that work, I would like to add considerably more tests. 

As an aside I would like to stop using pytest "implicit mark". It is too easy for tests to be skipped, and now that all unit tests are under a single `tests/unit` directory, it is not needed.

### CODE REVIEW

**Comment by mattpap** [comment]
It will be easier for me to incorporate those changes into PR #9614 than rebase. I intend to finish that PR in the evening.

**Comment by bryevdv** [comment]
I don't disagree, I was not sure if you intended for the other PR to go in to 2.0 or not. Of the two, this capability definitely needs to be included even if the other is not. I'll leave it open for now just in case.

**Comment by mattpap** [comment]
> As an aside I would like to stop using pytest "implicit mark" (...)

That's fine. I actually never relied on this marker, viewing it as unreliable. I always run `pytest tests/unit`.

**Comment by bryevdv** [comment]
Great, I'll work up another PR to get rid of it later this week.

**Pull request merged**
