### PR TITLE
Switch resource ordering

### LINKED ISSUE #5021: Render js_raw before js_files
I had a situation where I had custom models with external resources.

I wanted to use bokeh with `resources=local` but because in the template for bokeh_js - https://github.com/bokeh/bokeh/blob/master/bokeh/core/_templates/js_resources.html - files are rendered before raw, my document didn't load because I need bokeh loaded first.

I can't see any harm in switching the order.

### PR DESCRIPTION
**Pull request by birdsarah**
- [x] issues: fixes #5021

### CODE REVIEW

**Comment by mattpap** [comment]
I have to give this a thought, but this shouldn't work.

**Comment by mattpap** [comment]
With this change, e.g. setting `log_level` will fail with `Bokeh is not defined`. There is an assumption that `js_raw` may depend on `Bokeh`. This is also nicely visible in `autoload_js` template.

**Comment by mattpap** [comment]
> I had a situation where I had custom models with external resources.

Can I get some specifics (maybe some code)? This may need to be resolved as part of PR #4946.

**Comment by birdsarah** [comment]
> With this change, e.g., setting log_level will fail with Bokeh is not defined.

Yep - discovered that - happy to close this.

> Can I get some specifics (maybe some code)? This may need to be resolved as part of PR #4946.

I'll try and rustle something up on the original issue #5021

**Pull request closed without merging**
