### PR TITLE
pytest-selenium 1.0b1 does not use the --destructive argument

### PR DESCRIPTION
**Pull request by birdsarah**
pytest-selenium is now on pypi: https://pypi.python.org/pypi/pytest-selenium/1.0b1

ping @damianavila

### CODE REVIEW

**Comment by birdsarah** [comment]
The fact that this is passing is erroneous - no tests ran. This needs to be re-run when @damianavila has a chance to build the new pytest-selenium packages.

Marking as WIP until then.

**Comment by damianavila** [comment]
I will be building the packages on Monday morning... then I will re-trigger the tests.

**Comment by birdsarah** [comment]
awesome sauce. thanks so much

**Comment by damianavila** [comment]
We are green... let merge this one...

**Pull request merged**
