### PR TITLE
CSS styling docs / Updates for 3.1

### LINKED ISSUE #12675: User guide section for CSS stying
As far as I know there is not any actual User Guide documentation regarding `styles`, `stylesheets`, etc. There is currently a *Styling plot elements*  section in the *Appearance* chapter that covers using Bokeh properties for plot things. I think I would suggest a  corresponding *Styling DOM elements* section that covers applying CSS styles, using `css_classes`, etc. 

cc @tcmetzger for thoughts

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #12675
- [x] release document entry (if new feature or API change)

@bokeh/dev how does this look structure wise?

### CODE REVIEW

**Comment by tcmetzger** [comment]
@bryevdv This looks great!

**Comment by bryevdv** [comment]
@mattpap what about this, I guess I expected this simplified version of `css_classes.py` to work:
```
from bokeh.io import save
from bokeh.layouts import column
from bokeh.models import Div

template = """
{% block postamble %}
<style>
    :host(.custom) {
        border-radius: 0.5em;
        padding: 1em;
    }
    :host(.custom-1) {
        border: 3px solid #2397D8;
    }
    :host(.custom-2) {
        border: 3px solid #14999A;
        background-color: whitesmoke;
    }
</style>
{% endblock %}
"""
p = Div(text="The divs below were configured with additional <code>css_classes</code>:")

div1 = Div(text="""
<p>This Bokeh Div adds the style classes:<p>
<pre>
:host(.custom) {
    border-radius: 0.5em;
    padding: 1em;
}
:host(.custom-1) {
    border: 3px solid #2397D8;
}
</pre>
""")
div1.css_classes = ["custom", "custom-1"]

div2 = Div(text="""
<p>This Bokeh Div adds the style classes:<p>
<pre>
:host(.custom) {
    border-radius: 0.5em;
    padding: 1em;
}
:host(.custom-2) {
    border: 3px solid #14999A;
    background-color: whitesmoke;
}
</pre>
""")
div2.css_classes = ["custom", "custom-2"]

save(column(p, div1, div2), template=template)
```

If there is really, truly no way for `css_classes` to be useful *without any other programmatic interventions* (e.g. all styles are *in the template* even if they need `:host`, and there is no`InlineStyleSheet`) then I think we just need to deprecate `css_classes` entirely, as it cannot perform the useful function people have come to expect of it (i.e. being the *single* point of contact between their template and our output embedded in the template)

**Comment by bryevdv** [comment]
There were also some validation errors in the examples I fixed. There is one more I have not been able to track down

```
reading sources... [ 61%] docs/examples/topics/hex/hex_tile .. docs/examples/topics/timeseries/missing_dates
ERROR:bokeh.core.validation.check:E-1001 (BAD_COLUMN_NAME): Glyph refers to nonexistent column name. This could either be due to a misspelling or typo, or due to an expected column being missing. : text_font='Helvetica' [no close matches] {renderer: GlyphRenderer(id='p21668', ...)}
```

**Comment by bryevdv** [comment]
@bokeh/dev I plan to merge this tomorrow morning PST and call for 👍 / 👎 to release, at the wednesday meeting. Please let me know any comments here ASAP.

**Comment by mattpap** [comment]
```py
template = """
{% block postamble %}
<style>
    :host(.custom) {
        border-radius: 0.5em;
        padding: 1em;
    }
</style>
{% endblock %}
"""
```
`:host` or `:host(sub-selector)` have no meaning and function outside shadow DOM. If this is applied at the top-level, then those declarations will be dropped. The best approximation for having a single stylesheet for all components, is to add it to a theme, like this:
```py
curdoc().theme = Theme(json=dict(
  attrs=dict(
    UIElement=dict(stylesheets=[InlineStyleSheet(css="...")]),
  ),
))
```
I started PR https://github.com/bokeh/bokeh/pull/12907 with a complete example.

**Pull request merged**
