### PR TITLE
Update to Bokeh example plot: accessible palette

### PR DESCRIPTION
**Pull request by Soot3**
Changed spectral5 to mediumcontrast5

Original

Original

New
New

@bryevdv 
- [x] issues: #11481

### CODE REVIEW

**Comment by bryevdv** [comment]
@Soot3 Thanks for the PR can you attach a before/after screenshot to the OP?

**Comment by Soot3** [comment]
@bryevdv done.

**Comment by bryevdv** [comment]
@Soot3 That looks fantastic! We will need new thumbnails for the gallery. I have a fairly streamlined system for it now so I am happy to push the new images to your branch. But you are welcome to do it yourself too, if you like! We would need two omptimized pngs, a base 300x300 image and an indentica `@2` 600x600 "retina" image. The current images to update are here, for reference:
```
docs/bokeh/source/_images/examples/basic/bars/pandas_groupby_nested.png
docs/bokeh/source/_images/examples/basic/bars/pandas_groupby_nested@2x.png
```

 Let me know what you prefer.

**Comment by Soot3** [comment]
@bryevdv I am to help. I'll get right on the images.

**Comment by bryevdv** [comment]
@Soot3 Did you mean to close this PR? I would suggest adding the new images to this existing PR. Should I re-open it?

Edit: just in case it was not clear, we need both the code changes in this PR, *and* the new thumbnail images, and it would be preferable to have both updated at the same time in one PR since the changes are related to one another.

**Comment by Soot3** [comment]
I didn't. I renewed the fork because of some duplicated changes. Just saw your edit. let me try that

**Comment by bryevdv** [comment]
👍 I have re-opened, you should be able to push new changes to the branch even from a new but you may need to fiddle with git remotes or fetch the branch  manually.

**Comment by Soot3** [comment]
Hmm. yeah. looking at it now. the exact patch I made this pull request from doesn't exist on github or locally.
@bryevdv I can make the code change on my new request easily.
Apologies for any inconvenience

**Comment by bryevdv** [comment]
superseded by #12953

**Pull request closed without merging**
