### PR TITLE
image glyph has standard palette Greys9

### LINKED ISSUE #1928: image glyph method should warn if no palette or color mapper supplied
reference: https://twitter.com/BokehPlots/status/568153221228670976

### PR DESCRIPTION
**Pull request by almarklein**
issues: closes issue #1929, closes #1928

Question: we don't currently have any code that does *not* provide a palette to an image, so this change will not be tested anywhere. Should I add an example for this?

### CODE REVIEW

**Comment by mattpap** [comment]
> Question: we don't currently have any code that does not provide a palette to an image, so this change will not be tested anywhere. Should I add an example for this?

No, that would be too heavy weight. This will get tested when our new testing infrastructure is ready.

**Comment by mattpap** [comment]
Looks good.

**Comment by damianavila** [comment]
LGTM, I think we can include this one in 0.8.1 too, thoughts?

**Comment by bryevdv** [comment]
I think so

**Pull request merged**
