### PR TITLE
Fix rendering of webgl line containing NaN (#8489)

### PR DESCRIPTION
**Pull request by ianthomas23**
This is a partial fix for issue #8489.

If you pass a non-finite `x` or `y` coordinate to `line`, i.e. a nan, inf or -inf, the webgl backend correctly doesn't render the non-finite coordinate location, but it does mess up subsequent line joins as shown in the final image of issue #8489.  The problem isn't the non-finite coordinate itself but it is the tangents and angles of line segments that are calculated in the JS code and passed to the webgl shaders.  If tangents and angles are finite there is no problem, but if they are non-finite this propagates along the line to mess up subsequent line joins.

The fix offered here is to treat the non-finite coordinates as zero for the tangent and angle calculations and only afterwards to set the coordinates to non-finite.  After the fix, the final image of issue #8489 is

Screenshot_2020-11-24 Bokeh Application

It is only a partial fix or workaround really, which is easily demonstrated by using a large linewidth.  The webgl backend does not render the line joins correctly anyway (with or without non-finite coordinates), and gaps in lines due to non-finite numbers require extra end caps.  A full solution will therefore require modification of the JS code to split a `line` into multiple sub-`lines` at each non-finite number and call the webgl code once for each sub-`line`, and also the webgl code needs to correctly render the line joins so that they are identical/similar to the canvas backend.

I have looked at the webgl `line` shaders and think they can be improved and simplified at the same time.  I will take a look at this but I cannot promise anything!

This is my first contribution to bokeh.

### CODE REVIEW

**Comment by bryevdv** [comment]
@ianthomas23 Thanks for your contribution! Regarding the to failures above, those are from missing test reference files for those platforms. If you download the CI artifact bundle and unzip it, you will find the files for those two platforms that you can check in to your branch. 

Would love to have any help with updating/improving webgl support. FWIW I had been planning to look at the approach below for instanced line rendering:

https://wwwtyro.net/2019/11/18/instanced-lines.html

**Comment by ianthomas23** [comment]
@bryevdv Thanks for the information about the missing baseline test images; I have now added them.

> https://wwwtyro.net/2019/11/18/instanced-lines.html

This is a useful link.  It is similar to the approach that I was thinking about, but  at first glance we may have to be slightly cleverer with the line joins to deal with `alpha < 1` and line dashes.  I am not familiar with regl but I can see that it removes the need for quite a lot of webgl boiler plate code so I will look into it further.

**Comment by mattpap** [comment]
>  (...) we may have to be slightly cleverer with the line joins to deal with alpha < 1 and line dashes (...)

I think that's the (or at least on of) hard part of all the gl glyph implementations. The goal of webgl backend was to simulate HTML5 canvas' behavior (to the pixel) while allowing several orders of magnitude more data points to be rendered in the same span of time.

**Comment by bryevdv** [comment]
> to the pixel

I don't consider this to be a goal. Canvas and webgl can draw different things and still both be drawing something that reasonably represents
```
p.line(x, y, color="red", line_dash=[2, 4], ...)
```
at the same time. I think it is fine to frame webgl as an explicit distinct choice with its own trade-offs or unique features, rather than merely "canvas but faster".

**Pull request merged**
