### PR TITLE
Binary array transport

### LINKED ISSUE #5984: Improve data transfer, using a binary transfer protocol
Currently data is transfered between Bokeh-Server and client as a JSON structure.
While JSON is a established format for AJAX, JSON is not capable as high performance data transfer mechanism for scientific applications.

Currently NP-Arrays that could be transfered in binary mode, were base 64 encoded and transfered as text embedded in a JSON structure.
On the JS side the decoding of base64 and a byte wise shuffling into JS typed Arrays takes lot of time and RAM.

As an example we implemented our own **binary** protocol for data transfer and it is much faster than Bokeh.
Our home-brew-data-structure to transfer data between Bokeh Server and client is crude but at least a order of magnitude faster than Bokeh.

From the user perspective one defines targets and associates data in a meta data dict:

    data_map = {
            'source.data.x': x_data,
            'source.data.index': x_data,
            'source.data.y': y_data,
            'source.data.y_above': y_above,
            'source.data.y_below': y_below,
        }

We align it in a binary data structure:

Length of Metadata
Metadata
dataset1
dataset2

0) The pos/length of all data structures to be submitted is calculated
1) The length of the meta data is coded into a string with 8 digits. So we beat endianess problems.
2) The metadata is JSON coded and added binary.
3) The metadata maps a Target (Plot1.source.data.X) to a Dataset defined by its position and length in the binary data structure. 
4) A Dataset is a binary representation of a numpy array fit for being 1:1 mapped to as JS typed array. 

On the JS side we disentangle the metadata first. Then we can map the binary data of the NP-Arrays to their targets JS typed arrays very fast, while respecting endianess.

This works quite well and we like to implement is to Bokeh.

Volker

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #5984
- [x] tests added / passed
- [x] release document entry (if new feature or API change)

Comments:

This PR adds support for transporting arrays as pure binary data from the server to clients, when the array type is compatible with JavaScript typed array type. The following sorts of updates to a column data source will trigger binary transport:

```
# replacing an entire data dict
source.data = dict(x=x, y=y)

# setting a single column
source.data[x] = x

# updating multiple columns
source.update(x=x, y=y)
```
Additionally, in the latter two cases, all updates now only send the columns there were actually set, instead of always sending the entire data dict (whether binary transport is available or not).

Since the many various functions involved in serialization were geared towards *returning* JSON or JSON strings, the implementation approach take was to add an optional **out-paramter** to collect binary buffers in to the functions, and to propagate it through the call chain when present. When not supplied, the default behaviour remained identical to the previous behaviour, making this approach reasonably non-intrusive. 

On the JS side, few changes were needed apart from providing an option to circumvent old/new value equality testing on ` ColumnDataChangedEvent` since it is a given that the update should take place. This results in a considerable performance improvement. 

Some limitations:

* base64 encoding still used for initial page load, hopefully can fix in a follow-on effort
* binary transport TO the server is not supported (including from python clients)
* ~~~no detection or correction for byte order is undertaken. Binary data is sent out as-is~~~

Finally, code under `bokeh.client` has been split up and refactored with additional tests added.

### CODE REVIEW

**Comment by bryevdv** [comment]
Here is a specific example that tries to minimize compute for the image
```
from __future__ import division

import numpy as np

from bokeh.io import curdoc
from bokeh.layouts import column
from bokeh.models import ColumnDataSource, Slider
from bokeh.plotting import figure

N = 512
img = np.empty((N,N), dtype=np.uint32)
view = img.view(dtype=np.uint8).reshape((N, N, 4))
for i in range(N):
    for j in range(N):
        view[i, j, 0] = int(i/N*255)
        view[i, j, 1] = 0
        view[i, j, 2] = int(j/N*255)
        view[i, j, 3] = 255

def compute(G):
    view = img.view(dtype=np.uint8).reshape((N, N, 4))
    view[:, :, 1] = G
    return img

source = ColumnDataSource(data=dict(img=[compute(0)]))

def update(attr, old, new):
    source.data=dict(img=[compute(new)])

p = figure(x_range=(0,10), y_range=(0,10))

p.image_rgba(image='img', x=0, y=0, dw=10, dh=10, source=source)

slider = Slider(start=0, end=255, value=0, step=10)
slider.on_change('value', update)

curdoc().add_root(column(p, slider))
```

**Comment by philippjfr** [comment]
Here are my profiling results using a periodic callback:

bokeh_plot

**Comment by bryevdv** [comment]
@philippjfr are you using the code above? Have you subtracted out any of the time to actually compute the new array?

**Comment by philippjfr** [comment]
>@philippjfr are you using the code above?

A slight modification that uses a periodic callback instead.

>Have you subtracted out any of the time to actually compute the new array?

As far as I can tell that time is negligible (<1ms).

**Comment by bryevdv** [comment]
Can you run a range of sizes from N=100 to 1000?

**Comment by bryevdv** [comment]
@philippjfr also check with the change I just pushed, it seems to make a pretty huge difference, I can scrub a 1000x1000 image with very little lag.

**Comment by philippjfr** [comment]
Here's what I'm seeing, maybe I need to find a better way to profile though:

bokeh_plot

bokeh_plot

**Comment by philippjfr** [comment]
Separately, if I push too much data, too quickly across the socket (1000x1000 image with a low periodic timeout) I frequently see this:

    2017-09-08 15:09:04,094 Write error on <socket.socket fd=13, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 5006, 0, 0), raddr=('::1', 58854, 0, 0)>: [Errno 22] Invalid argument

**Comment by bryevdv** [comment]
> Here's what I'm seeing, maybe I need to find a better way to profile though:

Yah that does not seem to agree with my subjective experience at least. 1000x1000 is almost smooth when scrubbing a slider with the new code, and basically unusable without.

As for date rate limit, yes there seems to be one, I doubt we can do much about but it would be nice to know what it is.

**Comment by bryevdv** [comment]
@philippjfr Here is slider interactive with 1000x1000

screenflow


Without the change it basically does not work or function at all. What are you actually measuring? Can you share your benchmark code?

**Comment by bryevdv** [comment]
@bokeh/dev I am going to try to add more tests but this is otherwise ready.

**Comment by bryevdv** [comment]
OK, limited capability is one thing, I wouldn't be able to live with myself leaving that endianness oversight. New code works on my laptop, should work on big endian and across one to the other, but will need to track down a big endian resource to test for sure (will add any unit tests I am able to tomorrow)

**Comment by bryevdv** [comment]
OK, I am going to merge this when green and make dev build

**Pull request merged**
