### PR TITLE
9064 - static typing - bokeh.ext.py

### LINKED ISSUE #9064: Add static typing to bokeh
This is a meta issue for adding static typing to bokeh:

- [x] `bokeh.palettes`
- [ ] `bokeh.embed.standalone`
- [ ] `bokeh.util.string` @mborus

### PR DESCRIPTION
**Pull request by w0rdsm1th**
bokeh.ext.py: 
- added mypy typing to function inputs and return values.
- added keyword only argument restriction to init and build function

setup.cfg: reference the ext.py module for mypy testing

- [X ] issues: fixes #9064 
- [ ] tests added / passed
N/A test using mypy

- [ ] release document entry (if new feature or API change)
N/A

### CODE REVIEW

**Comment by mattpap** [comment]
This was wrongly submitted against `master`. Please change the base or resubmit the PR.

**Comment by mattpap** [comment]
Actually, I was able to do this myself.

**Comment by bryevdv** [comment]
@mattpap What's your preference for these? We could merge `landing-2.0` and change the base of these PRs to `master`? I'd like to merge `landing-2.0` ASAP

**Comment by mattpap** [comment]
@bryevdv, go ahead. I will update these and my other PRs when that's done. Just let's make sure that `landing-2.0` doesn't undergo any further rebases, if possible, to ease the work.

**Comment by bryevdv** [comment]
I'll merge it not, it should not need any rebases AFAIK

**Pull request closed without merging**
