### PR TITLE
Backports for 3.3.2

### PR DESCRIPTION
**Pull request by mattpap**
This PR collects bug-fixes and tasks for a 3.3.2 release:

- [x] https://github.com/bokeh/bokeh/pull/13543
- [x] https://github.com/bokeh/bokeh/pull/13468
- [x] https://github.com/bokeh/bokeh/pull/13534 
- [x] 3.3.2 release notes

### CODE REVIEW

**Comment by mattpap** [comment]
If we can get PR #13468 reviewed, then the plan is release 3.3.2 today.

**Comment by bryevdv** [comment]
> If we can get PR https://github.com/bokeh/bokeh/pull/13468 reviewed, then the plan is release 3.3.2 today.

If there is a hurry, that's fine with me, otherwise I'd have a quick look at these as well

* https://github.com/bokeh/bokeh/pull/13549
* https://github.com/bokeh/bokeh/pull/13528
* https://github.com/bokeh/bokeh/pull/13527
* https://github.com/bokeh/bokeh/pull/13514
* https://github.com/bokeh/bokeh/pull/13501
* https://github.com/bokeh/bokeh/pull/13496

**Comment by mattpap** [comment]
> If there is a hurry, that's fine with me, otherwise I'd have a quick look at these as well

Yes, we need a release for tomorrow, thus I included only must have PRs.

**Comment by bryevdv** [comment]
Just a heads up that @Azaya89 and I plan to release 3.3.2 around 8:30am (PST) tomorrow.

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
@mattpap is there any reason to hold off merging this PR?

**Comment by mattpap** [comment]
> is there any reason to hold off merging this PR?

I'm not aware of any. Let's get 3.3.2 out.

**Comment by mattpap** [comment]
Remind me, do squash merge or merge backport PRs?

**Comment by bryevdv** [comment]
Ideally merge keeping commits, but I have forgotten at least once. The merge rule has to be temporarily changed in settings

**Pull request merged**
