### PR TITLE
Add streaming circle test for issue #5046

### PR DESCRIPTION
**Pull request by ianthomas23**
This PR adds a regression test for issue #5046 that was fixed by PR #11686. The test exercises all 3 output_backends even though only webgl had a problem.

Test image before the fix (commit 0cadaff30)
before
and after
after

### CODE REVIEW

**Comment by mattpap** [comment]
This will have to wait until baselines are updated to Chrome 94.

**Comment by ianthomas23** [comment]
@mattpap Your bokehjs ndarray additions are really nice. Given that the quantity of your changes is hard for others to follow, it would be good if there was some way that changes like that could be flagged or communicated to other devs as important additions that could make their lives easier.

**Comment by mattpap** [comment]
I suppose weekly and CZI meetings are a good sources of such information. Otherwise, PR review or updates (as in this case) is another source. In this particular case, I wanted to see how it will look like when using this new API. I'm not actually sure if I want to keep using this API outside examples or not.

**Comment by mattpap** [comment]
Also, it would make it easier, if you could push your future PR branches to the repository and not a fork (using `username/issuenum_description`; `issuenum` if applicable) (you should have access to do that by now).

**Comment by ianthomas23** [comment]
> I suppose weekly and CZI meetings are a good sources of such information.

Yes, that is fine now. I was thinking longer term, beyond the end of the CZI grant as we won't have CZI meetings then and I suspect you won't get all of us from makepath turning up to the weekly meetings.

> Also, it would make it easier, if you could push your future PR branches to the repository and not a fork.

I can do that. Although I am not entirely happy about making it easier for others to modify my PRs!!!

**Pull request merged**
