### PR TITLE
Add metadata to Google Maps-related examples (#11765)

### PR DESCRIPTION
**Pull request by ramanshah**
* Add metadata to examples/models/maps.py

* Add metadata to examples/models/maps_cities.py

* Add metadata to examples/models/trail.py

* Add metadata to examples/topics/geo/gmap.py

* Change handling of Google Maps API keys in these examples to take the API key as a command-line argument, so that examples can run without needing to change source code

All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [X] issues: partially addresses #11765
- [ ] tests added / passed (N/A - just documentation)
- [ ] release document entry (if new feature or API change) (N/A - just documentation)

### CODE REVIEW

**Comment by bryevdv** [comment]
@bokeh/dev any thoughts on changing to using `argv[1]` for the API key? Unfortunately every option here is bad in some way or other:

* Env vars are easy to detect unset and won't pollute shell history but are not so easy to set on windows
* argv also avoids needing to edit source, works well on windows, but is clunkier to check if it is missing
* placeholder requires editing source (but maybe that's ok?)

Either way, detecting a missing key and providing a sensible, actionable warning/error mens adding 5-10 lines that muddy up the example ☹️ 

Edit: are there any common characteristics that Google API keys share? I supposed we could add a helper function to see if an API key looks valid and warn if not. The the demos only have to make a function call to get more actionable warnings:
```python
API_KEY = os.getenv("GOOGLE_API_KEY", None)  # or
API_KEY = sys.argv.pop()

check_google_api_key(API_KEY)
```

**Comment by ramanshah** [comment]
Happy to implement whatever you choose to inject the API key and add API key validation (`sys.argv.pop()` is slick; hadn't used that before!). I just implemented the simplest thing I could think of where someone else could potentially run the example without modifying source.

I don't know the formal rules for this API key; mine is 39 characters belonging to `[a-zA-Z0-9_]`.

**Comment by bryevdv** [comment]
I can't find anything concrete that seems like it could be reliably used to check whether string values are plausible keys. So maybe something like this (untested)?

```python
import sys 

def google_api_key_helper(*, argv: bool = True, env_name: str | None = "GOOGLE_API_KEY") -> str:
    ''' Try to locate a Google API key from sys.arg or an environment variable. 

    '''
    if argv and len(sys.argv) == 2:
        return sys.argv[1]
    
    if env_name is None or api_key := os.getenv(env_name, None) is None
        raise MissingGoogleAPIKey(argv, env_name)

    return api_key
```

Then scripts can do 
```
API_KEY = google_api_key_helper()
```
The `MissingGoogleAPIKey` exception can provide detailed and actionable information about how to obtain a google API key, and how the example expects it to be set. 

@ramanshah what do you think? Would you be up for adding a cleaned up version of this function under `bokeh.util`? It would also need some basic/minimal unit tests.

**Comment by ramanshah** [comment]
Sounds like a great plan, @bryevdv - I'll implement this, which will be a nice chance to write my first lines of Bokeh library code. (I'll have to get my old dev stack working again, in the process.) Stay tuned :)

**Comment by bryevdv** [comment]
@ramanshah checking in, did you still intend/expect to be able to continue this PR?

**Comment by ramanshah** [comment]
@bryevdv Yes, I do want to finish this! Just got drowned the last month - December is always extremely heavy between client work, closing my books, and the holidays. Thanks for reminding me of this and for your patience.

**Comment by bryevdv** [comment]
@ramanshah Checkin in again, we are planning to have a 3.1 release in a few weeks. Do you expect to return to this in that time frame? If not I will close this current PR to clear out the PR list some, and then open a new issue with the proposed API/changes instead.

**Comment by ramanshah** [comment]
Ugh so sorry @bryevdv - yeah I've ended up busier than expected this winter, and I keep not building enough energy to stand up a working Bokeh dev environment so that I can write real application code and unit tests.

In the interest of not having to duplicate effort, I'm making a note in 7 days to circle back with you. If I fail to push the needed commits in that timeframe, we can close this. Is that ok? Thanks!

**Comment by bryevdv** [comment]
Thanks @ramanshah sounds good

**Comment by ramanshah** [comment]
@bryevdv I made a little time to lean on this today. It seems that my Bokeh dev environment is pretty far from being able to run tests against new library code (I don't touch web stuff in my day-to-day and am not good yet with npm.)

Given that this branch has fallen pretty far behind, let's close this PR. I'm saving a patch file of this commit locally so that I can retry a Bokeh dev environment from scratch after the new version drops while easily resurrecting the metadata work.

Thanks for all your help!

**Comment by bryevdv** [comment]
Thanks for the update, @ramanshah

**Pull request closed without merging**
