### PR TITLE
fix Rect with log axis (and don't break them with FactorRanges)

### LINKED ISSUE #5336: Strange behaviour of Rect-Glyph
Hello,
It looks like the `Rect` glyph has buggy behavior somewhere!!!
See attached example where you can `draw` a rectangle via `Selectbox`. After selecting the CustomJS will update the source of the `Rect` and the `Scatter`. The `Scatter`-Points and the `Rect`-Corner-Points do not match when using logarithmic scale.
Is this a bug?

```
from bokeh.plotting import figure, show
from bokeh.models.tools import BoxSelectTool
from bokeh.models.sources import ColumnDataSource
from bokeh.models.callbacks import CustomJS
from bokeh.io import output_file
from bokeh.models.glyphs import Rect


plot = figure(plot_width=600, plot_height=600,
              x_range=(0,20), y_range=(0,20),
              y_axis_type="log"
              )

# Initial Data
x = [10, 15]
y = [10, 15]

# Scatter
sc_source = ColumnDataSource(data=dict(x=x, y=y))
plot.scatter(source=sc_source, x='x', y='y', size=20)

# Rect
rect_source = ColumnDataSource(data=dict(x=[(x[0]+x[1])/2], y=[(y[0]+y[1])/2], width=[[x[1]-x[0]]], height=[y[1]-y[0]]))
rect = Rect(x='x',
            y='y',
            width='width',
            height='height',
            dilate=True,
            fill_alpha=0.3)
plot.add_glyph(rect_source, rect)

callback = CustomJS(args=dict(rect_source=rect_source, sc_source=sc_source), code="""
            var geometry = cb_data['geometry'];
            console.log(geometry);

            var width = geometry['x1'] - geometry['x0'];
            var height = geometry['y1'] - geometry['y0'];
            var x = geometry['x0'] + width/2;
            var y = geometry['y0'] + height/2;

            console.log(width, height, x, y);
            rect_source.data = {'x': [x], 'y': [y], 'width': [width], 'height': [height]};
            rect_source.trigger('change');

            sc_source.data = {'x': [geometry['x0'], geometry['x1']], 'y': [geometry['y0'], geometry['y1']]};
            sc_source.trigger('change');

""")
t = BoxSelectTool(callback=callback)
plot.add_tools(t)
plot.toolbar.active_drag = t


output_file('select_log.html')
show(plot)
```

Have a nice week,
Raphael

### PR DESCRIPTION
**Pull request by clairetang6**
New PR to address issue #5336 and fix Rects plotted with a log axis. The original merged and reverted [PR](https://github.com/bokeh/bokeh/pull/5669) fixed the issue but introduced new bugs with Rects and categorical axes. 

This PR fixes the new bugs so Rects work with linear, log, and categorical axes. 

- [x] issues: fixes #5336, #2058
- [x] tests added / passed

### CODE REVIEW

**Comment by clairetang6** [comment]
https://s3.amazonaws.com/bokeh-travis/195758973/examples.html

fixed most of the examples, but there are still problems with histograms:

image

**Comment by clairetang6** [comment]
And there's still an issue with reversed ranges: 

image

**Comment by bryevdv** [comment]
@clairetang6 thanks for the status update, let me know if there's anything I can help with.

**Comment by clairetang6** [comment]
Examples look good now! https://s3.amazonaws.com/bokeh-travis/196061838/examples.html

**Comment by clairetang6** [comment]
This PR also fixes issue [2058](https://github.com/bokeh/bokeh/issues/2058) ("Point hit testing for rects broken with screen space widths").

**Comment by bryevdv** [comment]
@clairetang6 I verified the examples report, and also that the #2058 is fixed! Looks very good, my one suggestion, what about factoring those two big blocks of code into something like this (untested)
```
_dist_center: (mapper, vmapper, coord, dim) ->
  if isString(coord[0]) and mapper instanceof CategoricalMapper
    synthetic_pt = mapper.v_map_to_target(coord, return_synthetic=true)
    synthetic_pt0 = (synthetic_pt[i] - dim[i]/2 for i in [0...coord.length])
    vpt0 = mapper.v_map_to_target(synthetic_pt0)
    dist = @sdist(mapper, coord, dim, 'center', @model.dilate)
  else
    pt0 = (coord[i] - dim[i]/2 for i in [0...coord.length])
    pt1 = (coord[i] + dim[i]/2 for i in [0...coord.length])
    vpt0 = mapper.v_map_to_target(pt0)
    vpt1 = mapper.v_map_to_target(pt1)
    if vpt1[0] < vpt0[0]
      vpt0 = vpt1
    dist = @sdist(mapper, pt0, dim, 'edge', @model.dilate)
  return [dist, vmapper(vpt0)]
```
Then could have:
```
canvas = @renderer.plot_view.canvas
[@sw, @sx0] = _dist_center(@renderer.xmapper, canvas.v_vx_to_sx, @_x, @_width)
[@sh, @sy0] = _dist_center(@renderer.ymapper, canvas.v_vy_to_sy, @_y, @_height)
```

**Comment by clairetang6** [comment]
I factored out the code, but there needed to be some dimension checking. The x and y axes have to be dealt with differently because:
1. rendering rects takes the left x0 point versus the top y1 point.
2. vy and sy are flipped while vx and sx are not.

**Comment by mattpap** [comment]
> `synthetic_pt = mapper.v_map_to_target(coord, return_synthetic=true)`

This isn't semantically valid syntax in neither coffeescript nor javascript. What you wrote is equivalent to:
```
return_synthetic = true
synthetic_pt = mapper.v_map_to_target(coord, return_synthetic)
```
This may seem harmless, but you can easily shadow a variable this way. This "named argument" syntax works, because assignment is an expression.

**Comment by clairetang6** [comment]
@mattpap, Ok I see what you mean and I'll keep that in mind, thanks.

**Comment by bryevdv** [comment]
Examples  report looks good on latest changes. Thanks @clairetang6 !

**Pull request merged**
