### PR TITLE
Change name of FuncTickFormatter to CustomJSTickFormatter

### LINKED ISSUE #11642: Rename FuncTickFormatter
Every other model in Bokeh that can process JS is a "CustomJS"-something. I'd like to propose renaming `FuncTickFormatter` (which is an awful name, my fault) to `CustomJSTickFormatter` for 3.0. which will bring its naming in line with everything else. 

cc @bokeh/dev

### PR DESCRIPTION
**Pull request by benrussell80**
Rename FuncTickFormatter to CustomJSTickFormatter for consistency.

- [x] issues: fixes #11642 
- [ ] tests passed
- [ ] tests added
- [x] release document entry (if new feature or API change)

I'm unsure if this constitutes an API change.

### CODE REVIEW

**Comment by mattpap** [comment]
This will require an entry in [3.0 migration guide](https://github.com/bokeh/bokeh/blob/branch-3.0/sphinx/source/docs/releases/3.0.0.rst).

**Comment by bryevdv** [comment]
@benrussell80 let me know if there are any questions about adding to the migration guide. It's standard Sphinx/ReST syntax but I am happy to answer any questions. The content should be a new subheading and a sentence or two describing the change/rename.

**Comment by benrussell80** [comment]
I went ahead and added a simple line to the migration guide. I can add more if that would be preferred.

As far as writing tests, I've more or less copied the unit tests that were in test_callback__models. Would integration tests be good here for the formatter? To check to see if the ticks get created correctly based on the code supplied? I do see that that is checked in the bokehjs tests, though.

**Comment by bryevdv** [comment]
@benrussell80 more tests are always good but it's really up to your time availability. Given that the work is a straight rename I would merge without any new tests at all, but of course this would be a great time to increase coverage if you have the bandwidth. 

I think all that is really needed here is BokehJS unit test, e.g. like the ones under `bokehjs/test/unit/models` that are run with `node make test:unit`

**Comment by bryevdv** [comment]
@mattpap the failing BokehJS tests are baselines, is this a chrome version issue?

**Comment by g-parki** [comment]
Thanks @benrussell80 and congrats on your first Bokeh PR! 🎉

**Pull request merged**
