### PR TITLE
Fix dask related regressions

### LINKED ISSUE #10935: Dask compat issues w/ nullable
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh 2.3.0rc2, dask 2021.2.0

#### Stack traceback and/or browser JavaScript console output

Screenshot 2021-02-23 at 1 56 30 AM

### PR DESCRIPTION
**Pull request by mattpap**
fixes #10935

### CODE REVIEW

**Comment by bryevdv** [comment]
Thanks @mattpap 🙏

**Comment by bryevdv** [comment]
cc @quasiben just to align across teams:

* we will add temporary easings to avoid breaking dask
* dask issues to stop configuring None values here
* we can revert the temporary dask-fixes for 2.4

**Comment by bryevdv** [comment]
@mattpap I know is late where you are, would you like to me to complete this with some `accepts` for `Select.value` and `Select.options` ?

**Comment by mattpap** [comment]
I already done that locally. I'm just waiting for CI to fail before pushing changes, to make sure that we are actually testing something.

**Comment by bryevdv** [comment]
Yup, all the failures are showing up now 🤦

**Comment by mattpap** [comment]
Works now. Still produces:
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
ValueError: I/O operation on closed file.
Call stack:
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/distributed/utils_perf.py", line 204, in _gc_callback
    100 * self._warn_over_frac,
Message: 'full garbage collections took %d%% CPU time recently (threshold: %d%%)'
Arguments: (37.79238678047966, 10.0)
```

**Comment by mattpap** [comment]
Holoviews fails with:
```
FAIL: test_element_font_scaling (holoviews.tests.plotting.bokeh.testelementplot.TestElementPlot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/holoviews/tests/plotting/bokeh/testelementplot.py", line 43, in test_element_font_scaling
    self.assertEqual(fig.title.text_font_size, {'value': '24pt'})
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/holoviews/element/comparison.py", line 79, in assertEqual
    asserter(first, second)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/holoviews/element/comparison.py", line 56, in simple_equality
    raise cls.failureException(msg or standardMsg)
AssertionError: '24pt' != {'value': '24pt'}
```
but that seems to be just a testing issue and otherwise @philippjfr already updated holoviz packages for bokeh 2.3.

**Comment by bryevdv** [comment]
OK looks like all the dask downstream tests are passing for real now, I will merge this and cut rc3 when everything is green. Thanks for the quick turnaround @mattpap 

@philippjfr Just FYI now that downstream tests are actually running on the right package, some HV failures are showing up:

https://github.com/bokeh/bokeh/pull/10936/checks?check_run_id=1957064869

But I know you are planning to release an update anyway (also I am not sure they matter as they are e.g. `"foo"` vs `{"field": "foo"}` type) so I do not plan to hold anything up due to them.

**Comment by bryevdv** [comment]
@mattpap I checked, the gc perf warning has been going on since before `branch-2.3` so we should just make an issue to look at it some other time soon.

**Comment by bryevdv** [comment]
one macos failure was conda install, I will merge now

**Review by bryevdv — APPROVED** [review]

**Pull request merged**
