### PR TITLE
Use Line for steps chart

### LINKED ISSUE #1815: Step chart should use Line, not Segment
ref: #1773

### PR DESCRIPTION
**Pull request by bryevdv**
issues: closes #1815

### CODE REVIEW

**Comment by fpliger** [comment]
LGTM

**Comment by bryevdv** [comment]
@fpliger can you test it with some other input types just to make sure it works with those?

**Comment by fpliger** [comment]
Works with dicts, DataFrames, lists and arrays... also working ok for the different inputs on the notebook example.

**Comment by damianavila** [comment]
LGTM... and I like the path you are suggesting to eliminate the `set_and_get` method... I will merge it after Travis CI

**Comment by damianavila** [comment]
some tests are failing @bryevdv

**Comment by damianavila** [comment]
ok, looks green now... merging...

**Pull request merged**
