### PR TITLE
simplify autoranging implementation 

### LINKED ISSUE #1517: Change DataRange objects to query renderers for preferred bounds
Instead of configuring `DataRange` objects with data sources, they should be configured with `Plot` object, and then query all the renderers on that plot for their preferred bounds, unioning them together to get the actual bounds to set for the plot. The reason for this is that for glyphs that have "extent' (i.e., non-marker glyphs), the current model of auto-computing bounds based solely on data falls over. 

Some notes:

* Should be possible to explicitly override bounds by setting them
* Should be possible to specify a subset of renderers to query

### PR DESCRIPTION
**Pull request by bryevdv**
issues: closes #1517

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap this is WIP but I would appreciate some early review/feedback. Here is the basic idea:
* `DataRange1d` have no more source configuration (this greatly simplifies glyph functions, btw)
* at render, `Plot` asks all renderers for their preferred bounds
* then `Plot` communicates these bound prefs to any data ranges
* data ranges compute their auto range by coalescing only the preferred  bounds for their configured renderers (by default, all renderers)

There is still a fair bit of plumbing to fit in, and also need to make all renderers report their bounds but any comments or suggestions welcome.

**Comment by fpliger** [comment]
@bryevdv if I understand the idea... `DataRange1d` becomes very similar to `Range1d` with the difference that it delegates range (`start`, `end`) to `Plot` that lazily computes those by querying it's renderers. Right?

**Comment by bryevdv** [comment]
That's pretty close, it is the `Plot` that is querying renderers (it's just easier that way) but the `DataRange1d` does still have an important function: it takes all the `individual` renderer bounds, and unions them into a single overall set of bounds, based on the renderers it is configured with (so you could have a `DataRange1d` that only auto-ranges bases on on glyph if you want, but by default it will range everything automatically).

**Comment by bryevdv** [comment]
OK, many more glyphs work at least as well as they did before. Remaining: image glyphs, bezier, gear, and possible improvements to text and ray

**Comment by bryevdv** [comment]
@mattpap if you have some way of computing a max radius for gears that would be helpful

**Comment by bryevdv** [comment]
@bokeh/core I think this is very close to passing the sense that the image report will be complete and reasonable and all unit tests will pass. I am not completely happy with everything in the current PR, but as we are postponing a release (and as this PR is pretty big), I am inclined to merge this sooner and get it into a dev build to allow it to "bake out" for a longer. Thoughts?

**Comment by bryevdv** [comment]
Tests are consistently hanging on:
```
 Testing /home/travis/build/bokeh/bokeh/examples/compat/mpl/subplots.py ...
```
but this example runs fine locally. @mattpap  @damianavila any ideas on how to diagnose?

**Comment by bryevdv** [comment]
Seems to be ping-ponging updates when a `DataRange1d` is shared between multiple plots.

**Comment by bryevdv** [comment]
OK latest push fixed event issue. Here are the two main issues I know remaining:
* auto-ranging only happens once (not again when data is updated)
* auto-ranging of shared ranges is "last plot wins" 

I have good ideas how to fix these, but they  could probably come in follow on PRs to keep this one simpler.

**Comment by bryevdv** [comment]
Ajax realtime and blaze server examples not working, but I believe everything else is. Will work on those, but other wise this is ready for review. Would like to merge soon.

**Comment by bryevdv** [comment]
@damianavila my current thinking: Put out a 0.8.2 release with what we have very soon (this week?) and then merge this immediately after for a 0.9 release. My upcoming sprint with @tswicegood will also be BokehJS heavy, so it will be good to collect all these changes into a 0.9 release.  Thoughts?

**Comment by bryevdv** [comment]
OK all tests passing and image-diff report looks good. The only missing piece I can think of ATM is that gears are not currently auto-ranged. @mattpap if you can provide a function that yields a minimum bounding box for a gear (as specified in bokeh) then I will add it.

**Comment by damianavila** [comment]
>@damianavila my current thinking: Put out a 0.8.2 release with what we have very soon (this week?) and then merge this immediately after for a 0.9 release. My upcoming sprint with @tswicegood will also be BokehJS heavy, so it will be good to collect all these changes into a 0.9 release. Thoughts?

I agree on this idea, I prefer to have a point release before merging this one... I think we can chat about the date at the meeting... but if we are releasing this week, I will target tagging on Thursday, ANN on Friday... so we have Tue and Wed to test... The other option is Thu and Fri for testing and release on Mon-Tue next week. Let's chat this on the meeting tomorrow...

**Comment by bryevdv** [comment]
@damianavila The problem is I am traveling Thursday to CA to work with @tswicegood on converting BokehJS to browserify. That will have to build upon this work (and #2092) to avoid impossible merge conflicts. But having 3-4 open PRs chained off each other is a situation I would much prefer to avoid. We might just have to forego another point release entirely if it can't be put out by Thursday morning.

**Comment by damianavila** [comment]
> We might just have to forego another point release entirely if it can't be put out by Thursday morning.

So you want to release on Wed at late... I can do the release on Wed if the well tested today and tomorrow...

**Comment by fpliger** [comment]
Good also to see some comments landing on the JS side. If possible I think it'd be positive to start adding docstrings to new JS functions/logic.

Anyway, this PR is really nice as is, so LGTM

Reminder to self: this PR will conflict with #2088 when it gets merged..

**Pull request merged**
