### PR TITLE
Docs updates/0.11.0

### PR DESCRIPTION
**Pull request by birdsarah**

### CODE REVIEW

**Comment by birdsarah** [comment]
This is already accepted into docs_updates/0.11.0 and am deploying now.

@damianavila what do you think the tagging strategy should be - this has generated two PRs for the same piece of code - should only the ones that go into master have resos and milestones etc?

**Comment by birdsarah** [comment]
@bokeh/core - the 2.7 examples keep failing and I'm not sure why. I've restarted them at least 3 times now.

**Comment by almarklein** [comment]
>>> Testing /home/travis/build/bokeh/bokeh/examples/glyphs/glyphs.py ...
    Wrote glyphs.html
    Shutting down bokeh-server ...
    Shutting down jupyter-notebook ...
    Traceback (most recent call last):
    File "/home/travis/build/bokeh/bokeh/tests/travis/test", line 606, in <module>
        result = test_example(example, flags)
    File "/home/travis/build/bokeh/bokeh/tests/travis/test", line 366, in test_example
        result = json.loads(proc.stdout.read().decode("utf-8"))
    File "/home/travis/miniconda/lib/python2.7/json/__init__.py", line 339, in loads
        return _default_decoder.decode(s)
    File "/home/travis/miniconda/lib/python2.7/json/decoder.py", line 367, in decode
        raise ValueError(errmsg("Extra data", s, end, len(s)))
    ValueError: Extra data: line 2 column 1 - line 20 column 1 (char 662 - 2228)
    F

**Comment by almarklein** [comment]
The glyphs.py example works fine for me. Except it reports a 404 in the console for http://bokeh.pydata.org/en/latest/_static/bokeh-transparent.png, but I suspect thats unrelated.

**Comment by damianavila** [comment]
>@damianavila what do you think the tagging strategy should be - this has generated two PRs for the same piece of code - should only the ones that go into master have resos and milestones etc?

I added `task` and `accepted` labels... this should be `reso:completed` after merging...

**Comment by birdsarah** [comment]
@bokeh/dev I've restarted the py27 examples at least 10 times now. What to do?

**Comment by damianavila** [comment]
I guess this is a symptom of https://github.com/bokeh/bokeh/issues/3636

**Comment by damianavila** [comment]
Please merge master in... fix is on master now...

**Comment by birdsarah** [comment]
HAH! It passed!!!

**Pull request merged**
