### PR TITLE
Include Dask testing dependencies in downstream CI

### PR DESCRIPTION
**Pull request by jrbourbeau**
I noticed there are some `pytest` setup errors related to testing `dask` / `distributed` in the downstream CI build. See, for example, [this CI build](https://github.com/bokeh/bokeh/pull/11176/checks?check_run_id=2433271983). This PR updates how we install `dask` and `distributed` to include extra testing dependencies (e.g. `pytest-rerunfailures`).

I should note that while `dask` has an `extras_require` for installing testing dependencies, `distributed` does not. That said, the change here will resolve the errors we're hitting today as `pytest-rerunfailures`, which is causing setup errors when running `distributed` tests, is included in the `dask["test"]` extra. 

- [ ] ~~issues: fixes #xxxx~~
- [ ] tests added / passed
- [ ] ~~release document entry (if new feature or API change)~~

### CODE REVIEW

**Comment by bryevdv** [comment]
A new black version today broke our CI. I have a PR to address but this will need a rebase later today FYI

**Comment by jrbourbeau** [comment]
Sounds good, thanks for the heads up. FWIW while having `pytest-rerunfailures` (and other downstream testing dependencies) installed is still a good thing to do, it looks like the actual issue is that `pytest-rerunfailures` and `flaky` both register a `flaky` `pytest` marker which can lead to errors like the one below

```python
 ____________________ ERROR at setup of test_compute_per_key ____________________

self = <flaky.flaky_pytest_plugin.FlakyPlugin object at 0x7f9b808d2290>
item = <Function test_compute_per_key>

    def pytest_runtest_setup(self, item):
        """
        Pytest hook to modify the test before it's run.
    
        :param item:
            The test item.
        """
        if not self._has_flaky_attributes(item):
            if hasattr(item, 'iter_markers'):
                for marker in item.iter_markers(name='flaky'):
>                   self._make_test_flaky(item, *marker.args, **marker.kwargs)
E                   TypeError: _make_test_flaky() got an unexpected keyword argument 'reruns'
```

**Review by bryevdv — DISMISSED** [review]

**Comment by bryevdv** [comment]
> which can lead to errors like the one below

Well, that's pretty grating. I guess the proper solution is another env file customized to downstream tests. @jrbourbeau can you:

* rebase on latest `branch-2.4`
* try a `pip uninstall flaky` as a stopgap in here  in  `install_downstream_packages.sh`
* make and issue for us to follow up with a real fix later?

**Comment by bryevdv** [comment]
🤞 will merge when green

**Comment by bryevdv** [comment]
The one integration test is an occasionally flaky failure, it can be ignored. However @jrbourbeau if you wanted to see those version related failures they are in the latest run: https://github.com/bokeh/bokeh/pull/11207/checks?check_run_id=2442129134

**Comment by bryevdv** [comment]
Having a pretty aggravating Monday's Monday of endless build/CI issues. I genuinely have no idea what might cause versioneer to return this 
```
self = LooseVersion ('e4e5b8c'), other = LooseVersion ('0.12.10')
```
Since it seems to be intermittenet I'm not opposed to just running the jobs again 🎲 🎲 or even just merging as-is

**Comment by bryevdv** [comment]
Ahhhh, it's the commit on *your* fork: https://github.com/bokeh/bokeh/commit/e4e5b8c

Perhaps this points to a problem that only affects PRs from forks. I am definitely OK to "merge and see" if the issue shows up again in a main repo branch PR I will open an issue.

**Comment by bryevdv** [comment]
@jrbourbeau it does look like the flaky uninstall needs a `--yes` or something tho:
```
+ pip uninstall flaky
Found existing installation: flaky 3.7.0
Uninstalling flaky-3.7.0:
  Would remove:
    /usr/share/miniconda3/envs/bk-test/lib/python3.7/site-packages/flaky-3.7.0.dist-info/*
    /usr/share/miniconda3/envs/bk-test/lib/python3.7/site-packages/flaky/*
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.7/site-packages/pip/_internal/commands/uninstall.py", line 86, in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 653, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.7/site-packages/pip/_internal/req/req_uninstall.py", line 380, in remove
    if auto_confirm or self._allowed_to_proceed(verbose):
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.7/site-packages/pip/_internal/req/req_uninstall.py", line 423, in _allowed_to_proceed
    return ask('Proceed (y/n)? ', ('y', 'n')) == 'y'
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 203, in ask
    response = input(message)
EOFError: EOF when reading a line
```

**Comment by jrbourbeau** [comment]
Whoops, thanks for adding the `--yes` flag @bryevdv!

**Pull request merged**
