### PR TITLE
Corrected docs for `dimensions` parameter to BoxZoomTool

### PR DESCRIPTION
**Pull request by kevinsa5**
Closes https://github.com/bokeh/bokeh/issues/8000.  Nothing fancy, just cleaning up some docs.  Current version lives [here](bokeh.pydata.org/en/latest/docs/user_guide/tools.html)

### CODE REVIEW

**Comment by bryevdv** [comment]
Thanks for the PR @kevinsa5 only one small comment, the value can also be `"both"`

**Comment by bryevdv** [comment]
Awesome, thanks for the catch and the fix @kevinsa5 !

**Comment by kevinsa5** [comment]
@bryevdv happy to help!  Thank you for your tireless efforts here -- we have several "business-critical" tools implemented in Bokeh at my workplace in the clean energy industry.  Wouldn't have happened without you guys.

**Comment by bryevdv** [comment]
@kevinsa5 that's a nice testimonial to hear! If you ever have something you can publicly share or showcase we are always happy to have guest blogs on https://bokeh.github.io (or tweet out links to write-ups elsewhere) I do understand things are often confidential/proprietary though. Alternatively if your company is in a position to directly support OSS, Bokeh is now a NumFocus project and donations can be made to NF in the projects name. 

In any event thanks again for the PR, we are having some spurious TravisCI fails but we will get this merged when things are green!

**Pull request merged**
