### PR TITLE
Fix issues with placeholder formatting in hover tool

### LINKED ISSUE #1920: examples/plotting/file/hover.py broken after 0.8 release
All other examples with hover seem to be working. 
There are 2 different issues with the mentioned example:

```
("foo", "@foo"),
("bar", "@bar"),
``` 
lines are raising the following exception on JS side:

```Uncaught [sprintf] expecting number but found array```

and

```("(x,y)", "($x, $y)"),```

is raising:

```Uncaught ReferenceError: x is not defined```

### PR DESCRIPTION
**Pull request by mattpap**
fixes #1920

### CODE REVIEW

**Comment by damianavila** [comment]
OK, this LGTM... and I tested successfully, so merging soon so I can trigger a devel build with the fix

**Comment by mattpap** [comment]
@damianavila, did you test this on multiple examples? If not I would suggest looking into `glyphs/sprint` as well. I'm just checking, because slipping a bug like this, shows that our reviews aren't as good as we think they are.

**Comment by damianavila** [comment]
I checked several ones... at least five of them, including the `sprint` one and I did not see any issues...
BTW, the failure seems spurious...
and finally, I think this solve the issue, otherwise, I will not merge it... I can have errors, but if I merge something is convinced that is the correct fix for the "status quo" :wink:

**Comment by damianavila** [comment]
@bryevdv, can you make a review too?

**Comment by mattpap** [comment]
> I checked several ones

OK, as I said, just checking.

**Comment by bryevdv** [comment]
@mattpap @damianavila I tried this on every example in `glyphs` and `plotting/file` and they all worked except perhaps, `trail.py` but the plot only has a map and line renderer so I would not expect it to work.

**Pull request merged**
