### PR TITLE
#6960: Derive ResizeTool from Tool not object

### LINKED ISSUE #6960: The deprecated ResizeTool is meant to be NO-OP, but fails validation Python-side
`bokeh 0.12.7`

Repro:
```python
from bokeh.plotting import Figure
from bokeh.models import ResizeTool, Tool

print(issubclass(ResizeTool, Tool))  # False
Figure(tools=[ResizeTool()])  # ValueError as expected Seq(Either(String, Instance(Tool)))
```

Should be derived from `Tool` not `object`: https://github.com/bokeh/bokeh/blob/master/bokeh/models/tools.py#L273

### PR DESCRIPTION
**Pull request by rs2**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes #6960 
- [x] tests added / passed
- [x] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
Deriving from `Tool` means that a corresponding empty `ReizesTool` would have to be added back to BokehJS, since we have tests to maintain 100% parity between the python and JS models. I'm definteily -1 on that, especially since `ResizeTool` will probably be removed after the next release. The intent of the loud warning is to get people to not add a `ReszieTool` any more at all, so I 'm not sure what benefit there is to making the `issubclass` check "work" for a tool that doesn't really exist.

**Comment by rs2** [comment]
Oh well, nice try. It is unfortunate that the error message is not clear when `ResizeTool` is added among other tools.

**Comment by bryevdv** [comment]
@rs2 I want to make sure I understand, are you getting an actual error/exception instead of just a warning/no-op? It's not clear to me if you want the `isinstance` check to work because *you* are want to be able to to that, or because the Bokeh codebase is doing so somewhere?

**Comment by rs2** [comment]
@bryevdv Sure, do you think the following traceback that is produced by the snippet below is sufficient to understand which of the tools is deprecated (or what the problem is, in the first place)?

```python
from bokeh.plotting import Figure
from bokeh.models import HoverTool, ResetTool, ResizeTool

Figure(tools=[HoverTool(), ResizeTool(), ResetTool()])
```

This results in
```
ValueError: expected an element of either String or Seq(Either(String, Instance(Tool))), got [HoverTool(id='7e420722-4735-4b93-8f9e-e024ae02a297', ...), <bokeh.models.tools.ResizeTool object at 0x000001B825BC2048>, ResetTool(id='16a98af5-b6b6-4982-bbb0-92c4b8098031', ...)]
```
You can kind of find the odd one in the list (`bokeh.models.tools.ResizeTool object`), but a bit more clarity would certainly help...

Please feel free to re-close this ticket...

**Comment by bryevdv** [comment]
@rs2 No, it's not supposed t do that, it's supposed to just print a loud warning and simply ignore the tool. I think this could be fixed in this function:

https://github.com/bokeh/bokeh/blob/master/bokeh/plotting/helpers.py#L494

with an explicit filter to remove any resize tools. I would support such a change if you are interested in making a small PR to do that. Alternatively we could simply accelerate removing the tool entirely. I would be OK with either.

**Comment by bryevdv** [comment]
I think at this point I'd favor just removing the tool entirely. It's technically a short deprecation cycle but we have not demonstrated its use in a vey long time. At this point I think the priority for getting to the 1.0 stabilized API (i.e. jettisoning anything we ever want to be able to jettison) is to get there *quickly*.

**Comment by bryevdv** [comment]
I will just go ahead an close this, and make the removal PR along with the necessary release notes.

**Pull request closed without merging**
