### PR TITLE
limit heavyweight imports to only when used

### LINKED ISSUE #5060: Limit imports of client/server code to only when necessary
Hi,

I try to import a module Bar module using

```
from bokeh.charts import Bar
```

then I got SyntaxError

```
Traceback (most recent call last):
  File "bokeh_func.py", line 2, in <module>
    from bokeh.charts import Bar 
  File "/usr/local/lib/python2.7/dist-packages/bokeh/charts/__init__.py", line 10, in <module>
    from ..plotting.helpers import DEFAULT_PALETTE
  File "/usr/local/lib/python2.7/dist-packages/bokeh/plotting/__init__.py", line 7, in <module>
    from ..io import curdoc; curdoc
  File "/usr/local/lib/python2.7/dist-packages/bokeh/io.py", line 29, in <module>
    from .core.state import State
  File "/usr/local/lib/python2.7/dist-packages/bokeh/core/state.py", line 46, in <module>
    from ..client import DEFAULT_SESSION_ID
  File "/usr/local/lib/python2.7/dist-packages/bokeh/client/__init__.py", line 6, in <module>
    from .session import ClientSession, pull_session, push_session, show_session, DEFAULT_SESSION_ID
  File "/usr/local/lib/python2.7/dist-packages/bokeh/client/session.py", line 10, in <module>
    from ._connection import ClientConnection
  File "/usr/local/lib/python2.7/dist-packages/bokeh/client/_connection.py", line 11, in <module>
    from tornado import gen, locks
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1243, in <module>
    import tornado.platform.asyncio
  File "/usr/local/lib/python2.7/dist-packages/tornado/platform/asyncio.py", line 33, in <module>
    import asyncio # type: ignore
  File "/usr/local/lib/python2.7/dist-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/usr/local/lib/python2.7/dist-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
```

There is asyncio installed on my system. When I uninstalled asyncio, there is no error.

Bokeh info

```
Python version      :  2.7.6 (default, Jun 22 2015, 17:58:13) 
IPython version     :  1.2.1
Bokeh version       :  0.12.1
BokehJS static path :  /usr/local/lib/python2.7/dist-packages/bokeh/server/static
```

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #5060
- [x] tests added / passed

Open to suggestions for more places to remove or testing strategies

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap are you aware of any others that might be good to limit?

**Comment by mattpap** [comment]
@bryevdv, on top of my head, no.

This could be somehow tested, because it's very easy to regress to previous state of the art. E.g. in sympy we have additional test run in a dependency-limited environment.

**Comment by bryevdv** [comment]
Right, I will add a test before merging.

**Comment by bryevdv** [comment]
Added a test, will merge when green

**Pull request merged**
