### PR TITLE
Add `search_option_limit` to `MultiChoice` widget

### LINKED ISSUE #10525: [Feature] Support full text search for MultiChoice and  auto complete input
Bokeh 2.1.1, Python 3, Windows 10, Chrome 

#### Description of expected behavior and the observed behavior

**1. Bokeh  Multichoice search is not working as expected. When type a string suggestion list in dropdown is not showing correct results** 
For example Dropdown list has around 7 elements containing 'ca' as a substring but when i type 'ca' only 4 elements shows up in the drop down instead of 7. 
Bokeh_drop_down_search_error_1
Bokeh_drop_down_search_error_2

**2. Bokeh auto complete is not showing results for sub string. It only shows when we type string from start. I tried using modified version of bokeh-widget-2.2.1.js but for some reason bokeh is still able acess bokeh-widget.min.js** 

_2.1. Sub String search is not working which very essential thing when we talk about search. 
2,2 I added bokeh-widgets-2.1.1.js JS file in my code as :_ 
```
 <script src="/bokeh_app/static/js/jquery.min.js"></script>
    **<script src="/bokeh_app/static/js/bokeh-widgets-2.1.1.js"></script>**
    <script src="/bokeh_app/static/js/jquery-ui.min.js"></script>
<script src="/bokeh_app/static/js/bokeh-2.1.1.js"></script>
<script src="/bokeh_app/static/js/bokeh-api.min.js"></script>
<script src="/bokeh_app/static/js/bokeh-gl.min.js"></script>
<script src="/bokeh_app/static/js/bokeh-tables.min.js"></script>

```

H**owever Bokeh is accessing **bokeh-widgets.min.js**  instead of modified ``` **<script src="/bokeh_app/static/js/bokeh-widgets-2.1.1.js"></script>**``` which is not there in my project structure at all.**  
Bokeh_minJS_error

Any help regarding these two issues is very critical and appreciated

### PR DESCRIPTION
**Pull request by ingebert**
- [x] issues: fixes #10525
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap are there any good ways/places to test this? I note that most widgets are not covered by tests to maintain property default values (there is the Python<->JS parity tests to make sure defaults stay equal, but no tests to maintain they don't change together). I'll make a separate issue about that, though.

**Comment by bryevdv** [comment]
Well, in a addition to a pytho default test, I guess there are integration tests that could be updated to check the actual DOM structure:

Screen Shot 2021-09-20 at 10 14 35

@ingebert do you have availability to continue working on completing this with tests? If not we will at least need a follow-on issue created by you so that someone else can track that work.

**Comment by mattpap** [comment]
Perhaps some inspiration (for a visual test) can be found here:
https://github.com/bokeh/bokeh/blob/80172f6fb3746b28bc744a08f44afc76c4421ffe/bokehjs/test/integration/regressions.ts#L760-L813

**Comment by ingebert** [comment]
@bryevdv @mattpap I'm afraid I don't have the skills/experience to put up those tests, in particular on JS side. Sorry! But I hope someone can finish this.

**Comment by bryevdv** [comment]
I'll plan to merge this tomorrow unless there is comment. I'll try to work on the follow-on tests soon.

**Comment by bryevdv** [comment]
Thanks @ingebert !

**Comment by ingebert** [comment]
@bryevdv it looks like this pull request was bad timing thoug it was released with 2.4.1(too late for 2.4.0. and all the other PR for 2.4.1 were backported from 3.0.0 branch. I think it might get lost for 3.0 release (at least I can't see it right now), I just want to make sure you have it on the radar. Maybe you have mechanisms to consider it, in this case I'm sorry for annoying you with this 😀

**Comment by mattpap** [comment]
It wasn't marked as `NEEDS BACK PORT` at the time of merging, so was lost in the shuffle.

**Comment by bryevdv** [comment]
did you mean `NEEDS FORWARD PORT`? This was merged against `branch-2.4`

**Comment by bryevdv** [comment]
Forward port to `branch-3.0` is complete

**Comment by bryevdv** [comment]
re-milestoning to 2.4.3 since we are making a new 2.4 release after all.

**Pull request merged**
