### PR TITLE
Backports for 3.0.2

### PR DESCRIPTION
**Pull request by bryevdv**
This PR performs backports for a 3.0.2 release. The critical bugfixes are for `importlib.metadata` cleanup and unguarded `numpy.typing` imports, both of which can result in runtime crashes. 

Additionally other small bugfixes were included in order to increase the value of this point release for users. Non-user-facing testing and CI PRs were also brought in as necessary to make the cherry-picks clean. 

I will add release notes and `switcher.json` update in dedicated PR as always, after this one. I intend to release 3.0.2 by Wednesday next week. 

* https://github.com/bokeh/bokeh/pull/12550
* https://github.com/bokeh/bokeh/pull/12561
* https://github.com/bokeh/bokeh/pull/12563
* https://github.com/bokeh/bokeh/pull/12570
* https://github.com/bokeh/bokeh/pull/12569
* https://github.com/bokeh/bokeh/pull/12566
* https://github.com/bokeh/bokeh/pull/12484
* https://github.com/bokeh/bokeh/pull/12571
* https://github.com/bokeh/bokeh/pull/12573
* https://github.com/bokeh/bokeh/pull/12579
* https://github.com/bokeh/bokeh/pull/12581
* https://github.com/bokeh/bokeh/pull/12580
* https://github.com/bokeh/bokeh/pull/12588
* https://github.com/bokeh/bokeh/pull/12589
* https://github.com/bokeh/bokeh/pull/12593
* https://github.com/bokeh/bokeh/pull/12572
* https://github.com/bokeh/bokeh/pull/12586

Once this PR is merged I will updated the milestone for all the linked PR/issues above.

### CODE REVIEW

**Comment by bryevdv** [comment]
Noting that of the 157 file changes, the only changes to library source files were in these six files:

* [bokehjs/src/lib/models/glyphs/line.ts](https://github.com/bokeh/bokeh/pull/12597/files#diff-02a0eec9c1b2c5314b6bc1ad2feb1aebfbe85cb25be344e37646a9079f918f86)
* [bokehjs/src/lib/models/glyphs/webgl/line_gl.ts](https://github.com/bokeh/bokeh/pull/12597/files#diff-a7b2c8959acd7a609e688c7c94e79495ace6a032fe25ee1032541d17371ee9ed)
* [bokehjs/src/lib/models/text/math_text.ts](https://github.com/bokeh/bokeh/pull/12597/files#diff-91cd3cd6a1b212ffa7dfb461618dda97e594e243c61c348f8e213e5448a10c5d)
* [bokehjs/src/lib/models/tools/inspectors/hover_tool.ts](https://github.com/bokeh/bokeh/pull/12597/files#diff-7b603a711787d5f18924d83a9edfae23e0287b20a9d7d3316e2e7b8d3e7bf9cc)
* [bokehjs/src/lib/models/tools/tool_button.ts](https://github.com/bokeh/bokeh/pull/12597/files#diff-c7002fd52d834ef4bfdf5dbd0001964f3f425aebdfd3bdf3e9b52903c9a8dab8)
* [bokehjs/src/lib/models/tools/tool_proxy.ts](https://github.com/bokeh/bokeh/pull/12597/files#diff-39a2b7291946149dffece138bf6b5287436f3a903e875b3e47d63d99552bf1a9)

**Comment by bryevdv** [comment]
@mattpap I just realized I did not ask you about including #12580 I do personally think it should be included, but I also think primary discretion for non-CI/test/build PRs should lie with the PR authors. I did ask @ianthomas23 about including his PRs beforehand, so my apologies to you for failing to do so for #12580. If you would me to remove it, please let me know ASAP.

**Comment by mattpap** [comment]
> (...) about including https://github.com/bokeh/bokeh/pull/12580 (...)

It's a major regression in 3.0, so it should be included. It's also a simple fix barring any type fiddling and testing.

**Comment by bryevdv** [comment]
Noting that https://github.com/bokeh/bokeh/pull/12604 was overlooked earlier. For expediency it was cherry-picked directly to `branch-3.0`

**Pull request merged**
