### PR TITLE
Redesign set_data() and set_visuals()

### PR DESCRIPTION
**Pull request by mattpap**
Early work in progress. The goals of this work are:

- bring initialization of coordinate and visual data under one code path
- cleanly separate scalar visuals from vector
- allow to redefine non-visual properties in selection glyphs, etc.
- allow to use glyphs of similar (not exact) type as selection glyphs, etc.

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap there is lots of good stuff here. I would however ask:

* Work through and merge #10278 first
* After this, take a breather on this part of the code base and focus on other areas for awhile

Re: the second point: you have a dozen plus open WIP PRs open all over the codebase making it increasingly difficult for others to contribute to any of these areas without generating conflicts. It's going to take me several weeks (at least) to work on incorporating ReGL and and I will need a stable base to work from.

**Comment by mattpap** [comment]
> After this, take a breather on this part of the code base and focus on other areas for awhile (...). It's going to take me several weeks (at least) (...)

If I read this correctly, you are saying that I should stop doing my work for the foreseeable future, because you are unable organize your work in a way that would allow both improvements to webgl support and other data/rendering related changes to happen simultaneously. I already hinted in another PR, perhaps not vocally enough, how you should approach this, that the initial webgl improvements should happen within the confines of the existing bokehjs <-> webgl integration design, and then we will be able to work on a new, sound integration design, considering more than just the narrow webgl side of things. What I don't need right now, are unrelated changes, especially rearranging the code with no clear objective in mind (aside from changing things for the sake of it).

> the second point: you have a dozen plus open WIP PRs open all over the codebase making it increasingly difficult for others to contribute to any of these areas without generating conflicts. (...)

Making difficult to whom exactly? I recall a similar argument regarding an unnamed "colleague" who doesn't approve my approach to tooling and my position regarding thirdparty libraries. I've been doing the majority of work on bokehjs for the past year or more, with some substantial contributions from the holoviz team and some from you and external contributions, and I don't recall any major conflicts. I don't like having so many PRs open, but it takes time to come up with a sound design and it often takes even more time to tests things properly. Having backwards compatibility and legacy support vaguely and/or fluidly defined, among other issues, doesn't help with this either.

**Comment by bryevdv** [comment]
@mattpap Perhaps I should be more explicit. I'm trying to coordinate effort around the renderers and glyphs directories for about one month. ReGL is a very different API from what we have currently and while I will work to make minimal changes, my judgment is that it is not possible to make *no changes* in other codepaths. BokehJS is very large and there is more than enough to keep you busy even, avoiding those places so I don't regard this as an unreasonable ask. 

Since the objectives are unclear to you, let me elaborate some of them:
* various current webgl examples are broken on OSX and have been for a very long time
* want to add gl rects (this will be very helpful for Dask Dashboard)
* want to eventually add gl multi-polygons (for detailed cartograms)
* improve code organization so that shaders, etc. for a glyph are stored with the glyph

So I will ask again, for you to collaborate and afford a little breathing room around this corner of the codebase.

**Comment by bryevdv** [comment]
@mattpap I've looked over this again and I'd really like to have some more up-front design discussion. The "base glyph" approach here with sub-glyphs, where a base being present sets a flag causing "map "data" to be a no-op elsewhere, seems complicated in a way that could be avoided. Right now alot of the tension and complication arises because:
* mapped data values are stored on glyphs themselves (or their visuals), but
* we want to avoid duplication of effort/space due to sub-glyphs

If were are going to revamp this, then with the benefit of hindsight, I think we should explore something like pulling data storage off glyphs (and visuals) entirely. A glyph renderer would coordinate using all the sub-glyphs to map data in to a single data store (something like an internal CDS) then all the sub-glyphs get passed this same data store to actually do rendering with. 

One potential way I could imagine this working to avoid duplication is that in a sequence like this:
```
    this.decimated_glyph.map_data(this.mapped_data)
    this.selection_glyph.map_data(this.mapped_data)
    this.nonselection_glyph.map_data(this.mapped_data)
    this.hover_glyph?.map_data(this.mapped_data)
    this.muted_glyph?.map_data(this.mapped_data)
```
each call to `map_data` looks to see if a computed field it requires is already in the `mapped_data` data store. If not, it computes it and adds it. If it is, then no work is done. 

To make this completely flexible, the keys of the mapped data store will need to be composites, derived from the canonical property name, as well as other information. E.g. for a marker size to be different between normal and hovered, the key(s) for `size` property in the mapped data store could be `ssize:<glyph_field name>`. If all the sub-glyphs use the same field name, then there is only one mapped size column is ever computed, and they all use it. But if some sub-glyph wants to use a different column, it can. 

It probably should be mentioned that this mapped data store handles both mapped columns and mapped scalar values. This responsibility can be relieved from "visuals", simplifying them as well. The main idea is to have one single place for all mapped data values. This would be great for supporting webgl work, but additionally simplifies glyphs and visuals an relieves them of dealing with data storage (which they also do in different ways, which is complicating in and of itself)

This is a pretty hand-wavy sketch of ideas in my head. Perhaps we can figure out a time/way to have a "whiteboarding" session to discuss and flesh things out more.

**Comment by bryevdv** [comment]
I guess I should add explicity: I agree 100% with all the stated goals in the OP, I only think that a key part of making those improvements is to consicate all responsibility for containing mapped (scalar and array) data in to one place.

**Pull request closed without merging**
