### PR TITLE
Unify orientations and anchors

### PR DESCRIPTION
**Pull request by mattpap**
This changes `Legend(orientation=...)` to `Legend(anchor=...)`, which I think makes more sense. It also adds more anchor points and unifies this with `Image*.anchor`. No backwards compatibility yet.

### CODE REVIEW

**Comment by bryevdv** [comment]
Not sure about this. Images, etc. have a position, and then the image anchor point is located in that position. For legends, no position is given, but instead the anchor is interpreted as a general area on the plot that the legend should go, as opposed to an anchor on the legend itself. I think that is confusing. 

Before proceeding, there are questions to consider:
* How would this be extended to handle absolute positioning of legends: in data space? in screen space?
* Also to handle positioning legends outside the main plot area?
* How can we provide a deprecation path?

For the first question I would suggest perhaps splitting things out, i.e `position` is the location in the plot, and `anchor` is the position on the legend:
```
Legend(position=(x,y), anchor="center") # anchor refers to the legend, the same as images

Legend(position=(x,y), position_units="data") # data units

Legend(position="top_left")  # no anchor when non-absolute position is provided

Legend(position="auto")
```

**Comment by pzwang** [comment]
Agreed with most of Bryan's points here.  Also note that orientation does have significant meaning for a Legend - some visuals and graphics have legends that are oriented vertically.  (It's very seldom that they are at an angle.)

Something unrelated but also good to keep in mind is that thus far our notions of orientation etc. are Anglocentric.  When we use languages that are read right-to-left, then orientation can also be used to override whether the origin should default to the left or the right of the text.  (Then again, maybe this should be a separate `TEXT_ORIENTATION` property that is defined at the top-level stylesheet...?)

**Comment by damianavila** [comment]
>Agreed with most of Bryan's points here.

Me too...

>Something unrelated but also good to keep in mind is that thus far our notions of orientation etc. are Anglocentric. When we use languages that are read right-to-left, then orientation can also be used to override whether the origin should default to the left or the right of the text. 

This is certainly and interesting issue to keep in mind... 

>(Then again, maybe this should be a separate TEXT_ORIENTATION property that is defined at the top-level stylesheet...?)

Probably it has to be defined at the top to get unified behaviour in all the elements...

**Comment by bryevdv** [comment]
Let's plan this a bit more, moving to 0.9

**Comment by mattpap** [comment]
> Let's plan this a bit more, moving to 0.9

Sure. It wasn't exactly thought through, more a side effect of working on tests.

**Comment by damianavila** [comment]
Closing according to BEP-1. Please, reopen it when it is ready again.

**Pull request closed without merging**
