### PR TITLE
Add star and star_dot markers

### LINKED ISSUE #10836: [FEATURE] Add new star marker
Currently, Bokeh offers several markers such as asterisk, circle, diamond, square, triangle, and variations of these. However, the typical star shape is not included, so I tried to add this feature.

The star border's path I'm using in ```bokehjs/src/lib/models/glyphs/defs.ts``` is

```
const SQ5 = Math.sqrt(5)

function _one_star(ctx: Context2d, r: number): void {
    const a = Math.sqrt(5-2*SQ5)*r
    const c36 = (SQ5+1)/4
    const s36 = Math.sqrt((5-SQ5)/8)
    const c72 = (SQ5-1)/4
    const s72 = Math.sqrt((5+SQ5)/8)
    
    ctx.moveTo(0, -r)
    ctx.lineTo(a*c72, -r+a*s72)
    ctx.lineTo(a*(1+c72), -r+a*s72)
    ctx.lineTo(a*(1+c72-c36), -r+a*(s72+s36))
    ctx.lineTo(a*(1+2*c72-c36), -r+a*(2*s72+s36))
    ctx.lineTo(0, -r+a*2*s72)
    ctx.lineTo(-a*(1+2*c72-c36), -r+a*(2*s72+s36))
    ctx.lineTo(-a*(1+c72-c36), -r+a*(s72+s36))
    ctx.lineTo(-a*(1+c72), -r+a*s72)
    ctx.lineTo(-a*c72, -r+a*s72)
    ctx.closePath()
}

function star(ctx: Context2d, i: number, r: number, visuals: VectorVisuals): void {
    _one_star(ctx, r)

    if (visuals.fill.doit) {
        visuals.fill.set_vectorize(ctx, i)
        ctx.fill()
    }

    if (visuals.hatch.doit) {
        visuals.hatch.set_vectorize(ctx, i)
        ctx.fill()
    }

    if (visuals.line.doit) {
        visuals.line.set_vectorize(ctx, i)
        ctx.stroke()
    }
}
```
and for the (I suppose) size of the marker in ```bokehjs/src/lib/models/glyphs/webgl/markers.frag``` I copied the code for the hex case, i.e.

```
#ifdef USE_STAR
// star
float marker(vec2 P, float size)
{
    vec2 q = abs(P);
    return max(q.y * 0.57735 + q.x - 1.0 * size/2.0, q.y - 0.866 * size/2.0);
}
#endif
```

Then I added "star" in all the files where other markers were written, for example in all the bokehjs codes ```bokehjs/src/lib/api/plotting.ts```, ```bokehjs/src/lib/core/enums.ts```, ```bokehjs/src/lib/models/glyphs/webgl/markers.ts```, ```bokehjs/test/integration/glyphs/markers.ts```, ```bokehjs/test/integration/regressions.ts```, ```bokehjs/test/unit/core/enums.ts```, but also in examples, documentation, etc.

Unfortunately, I can't pass the integration test

```
✗ Bug
 └┬─ in issue #10457
  └── prevents rendering marker glyphs with reversed ranges
diff --git a/bokehjs/test/baselines/Bug__in_issue_#10457__prevents_rendering_marker_glyphs_with_reversed_ranges b/bokehjs/test/baselines/Bug__in_issue_#10457__prevents_rendering_marker_glyphs_with_reversed_ranges
index 9779355..3a5dcdf 100644
--- a/bokehjs/test/baselines/Bug__in_issue_#10457__prevents_rendering_marker_glyphs_with_reversed_ranges
+++ b/bokehjs/test/baselines/Bug__in_issue_#10457__prevents_rendering_marker_glyphs_with_reversed_ranges
@@ -1,4 +1,4 @@
-Column bbox=[0, 0, 400, 1300]
+Column bbox=[0, 0, 400, 1350]
   Row bbox=[0, 0, 400, 50]
     Plot bbox=[0, 0, 100, 50]
     Plot bbox=[100, 0, 100, 50]
@@ -129,3 +129,8 @@ Column bbox=[0, 0, 400, 1300]
     Plot bbox=[100, 0, 100, 50]
     Plot bbox=[200, 0, 100, 50]
     Plot bbox=[300, 0, 100, 50]
+  Row bbox=[0, 1300, 400, 50]
+    Plot bbox=[0, 0, 100, 50]
+    Plot bbox=[100, 0, 100, 50]
+    Plot bbox=[200, 0, 100, 50]
+    Plot bbox=[300, 0, 100, 50]


✗ Marker glyph
 └── should support 'star' marker type
missing baseline
diff --git a/test/baselines/Marker_glyph__should_support_'star'_marker_type b/test/baselines/Marker_glyph__should_support_'star'_marker_type
new file mode 100644
index 0000000..10abf94
--- /dev/null
+++ b/test/baselines/Marker_glyph__should_support_'star'_marker_type
@@ -0,0 +1,7 @@
+Row bbox=[0, 0, 450, 150]
+  Plot bbox=[0, 0, 150, 150]
+    Title bbox=[5, 0, 140, 28]
+  Plot bbox=[150, 0, 150, 150]
+    Title bbox=[5, 0, 140, 28]
+  Plot bbox=[300, 0, 150, 150]
+    Title bbox=[5, 0, 140, 28]

[02:36:45] Finished 'test:integration' after 33.54 s
[02:36:45] failed: tests failed
[02:36:45] failed: tests failed
[02:36:45] failed: task 'top-level' failed because 'test:integration' failed
[02:36:45] failed: task 'top-level' failed because 'test:integration' failed
[02:36:45] failed: task 'top-level' failed because 'test:lib' failed
[02:36:45] failed: task 'top-level' failed because 'test:lib' failed
[02:36:45] failed: task 'top-level' failed because 'test' failed
[02:36:45] failed: task 'top-level' failed because 'test' failed
Error: Process completed with exit code 1.
```

I think this marker is a nice addition to the current collection and an easy implementation. I don't understand why the test is not being passed, do you have any idea? Is there something I'm not considering?

Thanks!

### PR DESCRIPTION
**Pull request by sebacastroh**
This pull request adds two new star shaped markers: a single five pointed star and a dotted five pointed star.

- [ ] issues: fixes #10836
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

Currently I just modified the bokehjs codes, with the following results

Marker_glyph__should_support_'star'_marker_type
Marker_glyph__should_support_'star_dot'_marker_type
Marker_glyph__should_support_glyph_methods_and_rotation

I'm still learning how to implement the changes to the python section.

(There's another PR I created yesterday, please do not consider it, I was still understanding how PR work)

### CODE REVIEW

**Comment by mattpap** [comment]
This needs to be added on bokeh (Python) side as well (enum, marker methods and update unit test if required).

**Comment by sebacastroh** [comment]
Now is working in Python too, but only for the canvas and svg cases. 

image

I'm trying to understand the codes related to webgl. What is the value that you return in ```bokehjs/src/lib/models/glyphs/webgl/markers.frag```?

**Comment by mattpap** [comment]
> I'm trying to understand the codes related to webgl. What is the value that you return in (...)

I think no one really knows. Most markers either don't have webgl implementation or their implementation is wrong. If you can't figure it out, that's perfectly fine, we will get that sorted out when we get to improve the webgl backend. However, if I understand that code at all, `marker()` should return distance from marker's origin (center) to each of its points up to its border. You will have to start with a pentagram and cut out triangles from it to form a star. In any case, I will merge this as-is. Feel free to figure this out in another PR.

**Comment by bryevdv** [comment]
> I think no one really knows. 

The current implementation uses a technique referred to as distance fields, here is a reference that may be useful:

https://iquilezles.org/www/articles/distfunctions2d/distfunctions2d.htm

Thanks for the thorough PR @sebacastroh !

**Comment by mattpap** [comment]
> The current implementation uses a technique referred to as distance fields, here is a reference that may be useful:

I can finally attach a name to this. Yeah, that's pretty useful. So what's stopping us from filling in the rest of marker implementation, except spare time? I presume that markers will work mostly the same, regardless of what happens to webgl backend in general. Or is there a better approach for markers?

**Comment by ianthomas23** [comment]
As @bryevdv said, distance fields are a common technique in modern OpenGL and you can have antialiasing quite easily by using an appropriate smoothing function at the edge of a graphics primitive rather than a step function.

If someone else wants to update the WebGL markers then please go ahead, otherwise I will deal with them as part of the switch to regl that I am working on.  My WebGL regl lines PR is only a few days away.

**Comment by bryevdv** [comment]
@ianthomas23 just noting, you you should probably be aware of #10788 if you are not already, as it significantly overhauls some areas that are tangentially related to the webgl. It will be merged or 2.3 release.  I'd also probably suggest that for something like this its valuable to make a WIP/Draft PR earlier rather than later so others can be aware of the work and any potential impacts or conflicts

**Comment by bryevdv** [comment]
> So what's stopping us from filling in the rest of marker implementation, except spare time?


More or less. For more complicated markers it's not always obvious how to construct the appropriate distance field (maybe there is some first-principles procedure to derive them but if so I am not aware of it)

> I presume that markers will work mostly the same, regardless of what happens to webgl backend in general. Or is there a better approach for markers?

My best current understanding is that this is probably the ideal way to go for point markers but perhaps @ianthomas23 can offer perspective here as well.

**Comment by ianthomas23** [comment]
> @ianthomas23 just noting, you you should probably be aware of #10788 if you are not already, as it significantly overhauls some areas that are tangentially related to the webgl.

Wow, 196 files changed!  I am sure that will make some difference to what I am trying to do, but I will deal with that when it is merged.

> I'd also probably suggest that for something like this its valuable to make a WIP/Draft PR earlier rather than later so others can be aware of the work and any potential impacts or conflicts. Looking forward to seeing what you've been developing!

It will be a WIP.  I was originally aiming for it to be production ready code, but it has exceeded my 'scary threshold' so I do need to get seasoned Bokeh developers to look it over as soon as possible.

**Comment by ianthomas23** [comment]
> My best current understanding is that this is probably the ideal way to go for point markers but perhaps @ianthomas23 can offer perspective here as well.

Yes, distance fields are the recommended approach.  Future webgl developers will expect it to be done this way and will understand it if it is.

One thing I have realised whilst rewriting the webgl line code is that the algorithm needs some documentation, particularly diagrams, to help other people understand the code in the future.  I have put some ascii art in, but that really isn't good enough to explain the approach and define the terms.  I can't think of a way of including this with the code, so perhaps a blog article is the way to go.  It will only be of interest to developers rather than end users, and needs to be somewhere that will survive for a few years.  It will necessarily include a basic guide to distance fields.  What I will need is a world-class rendering library to draw the diagrams :smiley:

**Comment by sebacastroh** [comment]
Oh, wow, I didn't expect all your responses. It's very interesing reading all you said, even though I don't understand.

> Thanks for the thorough PR @sebacastroh !

You're welcome! Actually, I should thank you for this powerful library. The original issue I published is because I'm doing a [Strong Motion Database](https://siberrisk.ing.puc.cl/StrongMotionDatabase) using Bokeh and I want to mark earthquake's epicenters with a star that is the typical symbol that we use in seismic engineering.

> The current implementation uses a technique referred to as distance fields, here is a reference that may be useful:
>
> https://iquilezles.org/www/articles/distfunctions2d/distfunctions2d.htm

I checked this page and, I'm not going to lie, I don't know what I'm doing but now I'm able to plot the star marker using webgl

image

The code I'm using is

    const float IN_ANGLE = 0.6283185307179586; // PI/5. = 36 degrees (star of 5 spikes)
    //const float OUT_ANGLE = PI/2. - IN_ANGLE; // External angle for regular stars // Not sure if regular is the correct name
    const float COS_A = 0.8090169943749475; // cos(IN_ANGLE)
    const float SIN_A = 0.5877852522924731; // sin(IN_ANGLE)
    const float COS_B = 0.5877852522924731; // cos(OUT_ANGLE)
    const float SIN_B = 0.8090169943749475; // sin(OUT_ANGLE)
    
    #ifdef USE_STAR
    // star
    float marker(vec2 P, float size)
    {
        float bn = mod(atan(P.x, -P.y), 2.0*IN_ANGLE) - IN_ANGLE;
        P = length(P)*vec2(cos(bn), abs(sin(bn)));
        P -= size*vec2(COS_A, SIN_A)/2.;
        P += vec2(COS_B, SIN_B)*clamp(-(P.x*COS_B + P.y*SIN_B), 0.0, size*SIN_A/SIN_B/2.);
    
        return length(P)*sign(P.x);
    }
    #endif

I wrote in the comments of the code the generalization if you want to use more spikes.

I will open a new PR adding this.

**Pull request merged**
