### PR TITLE
minor dataspec cleanup

### LINKED ISSUE #8356: DataTable crashes layout if 'field' is key in ColumnDataSource data
Bokeh 0.13.0
Mac OS 10.13.3
python 2.7.10
Safari 11.0.3

If 'field' is a key in the data of ColumnDataSource, bokeh serve cannot generate a layout including a DataTable using this ColumnDataSource.  This only fails if the DataTable is in the layout, the DataTable may exist if not in the layout.

The following code will fail.  If you replace 'field' in variables with almost anything else, the code works.

```
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import TableColumn, DataTable
from bokeh.io import curdoc
from bokeh.layouts import column


variables = ['x', 'y', 'field']
source = ColumnDataSource(data={v: [i] for i, v in enumerate(variables)})
table = DataTable(source=source, columns=[TableColumn(field=v, title=v) for v in variables])
curdoc().add_root(column(table))
```

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #8356
- [x] tests added / passed

Much more modest PR. Makes the simple one line change to fix the linked issue:

screen shot 2018-10-27 at 10 08 12

and also adds a unit test to explicitly check that `{field: "field"}` works.

Also cherry picks a few of the smaller cleanup commits from the other PR just so that they are done/out of the way for later.

### CODE REVIEW

**Comment by bryevdv** [comment]
I also went ahead and converted the test file `properties.coffee` to TypeScript.  There appeared to be some broken tests, and a broken validator for `Color` when the input was not a string.

**Comment by mattpap** [comment]
It looks good, but I will have a closer look when I'm done with PyCon DE sprint.

**Comment by bryevdv** [comment]
Great, there are some tslint errors about const that I already have a commitment for. I will push it later when I get home.

**Comment by bryevdv** [comment]
@mattpap I'd like to merge this today. 

FYI I would also like to try and have no more than 10-15 small PRs per point release, so I'd like to cut 1.0.1 before I take time off.

**Comment by bryevdv** [comment]
I'm going to go ahead and merge this, all existing tests were preserved plus some new ones were added. The meat of this PR is pretty trivial, mostly the only place that could use improvement would be the test file itself, but that can happen later when scalar props on the JS side happens.

**Pull request merged**
