### PR TITLE
Financial dashboard

### PR DESCRIPTION
**Pull request by caseyclements**
bokeh-server example of financial trading dashboard. 
(apologies for including the xl binary. could switch to csv easily enough..)

### CODE REVIEW

**Comment by bryevdv** [comment]
I wonder if the new `bokeh-demos` repo might not be a better place. Thoughts @bokeh/core ?

**Comment by canavandl** [comment]
I would both convert the xl binary to csv and submit the PR to bokeh-examples. But thanks for the demo @caseyclements, it looks awesome

**Comment by damianavila** [comment]
I agree on moving this to `bokeh-demos`...

**Comment by bryevdv** [comment]
@caseyclements is your intent with the `.xl` file to specifically demonstrate that Bokeh can be used to to plot from Excel? That seems like a reasonable thing to show off in a t least one place.

**Comment by caseyclements** [comment]
@bryevdv This doesn't directly plot excel data, but the tiny excel includes the dashboard that i was targeting. it also shows, to the novice, how easy it is to link to excel (via pandas).

**Comment by caseyclements** [comment]
Ok - I'll close this, move to bokeh-demos and resubmit.

**Pull request closed without merging**
