### PR TITLE
population example legend position -> "bottom_right"

### PR DESCRIPTION
**Pull request by xavArtley**
#8319

> populatation: legend position bad

### CODE REVIEW

**Comment by bryevdv** [comment]
How does `top_left` look across a sampling of the data sets?

**Comment by xavArtley** [comment]
image

**Comment by bryevdv** [comment]
Hrm not great, I wonder if we could make extra space for it on the right by explicitly setting the x_range.end to 2200 (or whatever works) then putting the legend `center_right` ?

**Comment by xavArtley** [comment]
image

**Comment by bryevdv** [comment]
Better I think? If the legend orientation is changed to vertical (default) then it can take up less horizontal space

**Comment by xavArtley** [comment]
image

**Comment by bryevdv** [comment]
@xavArtley looks much better! Thanks, merging now

**Pull request merged**
