### PR TITLE
Allow automodule to correctly document Bokeh models classes

### LINKED ISSUE #1690: sphinx autoprops dependency for Bokeh models
Currently generate `reference/models.rst` by hand with `json_ref.py` script. Should create a sphinx plungin that exposes an `autoprops` directive that can automatically document properties on Bokeh models. 

Reference: http://sphinx-doc.org/extdev/tutorial.html

Note, included in this is:

* ability to have per-property documentation
* ~~ability to condense line, fill, and text properties~~
* improve JSON prototype output

EDIT: punting on summarization of line props, etc. for now

### PR DESCRIPTION
**Pull request by bryevdv**
issues: closes #1690

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap I know you'd rather have the contents of `models.rst` auto-generated but I think this is a reasonable compromise for now, since I don't think modules will be added or renamed there often, if at all. In fact there is no autodoc facility for documenting anything larger than a single module, so that would be new territory.

**Comment by bryevdv** [comment]
Note also, comments like this work:
```
    #: this describes an x_range
    x_range = Instance(Range1d)
```
however, it replaces the auto "type" information I was also adding. Would like to get both to work, then we can comment/doc all attributes and have exceptional reference docs.

**Comment by bryevdv** [comment]
Dev docs re-deployed, can see examples here: http://bokeh.pydata.org/en/dev/docs/reference/models.html

**Comment by bryevdv** [comment]
@bokeh/core this is ready for review.

OK, got this working with a better implementation, that also works with comment docs. Check out:

http://bokeh.pydata.org/en/dev/docs/reference/models.html#bokeh.models.axes.Axis

And compare to the source:

https://github.com/bokeh/bokeh/blob/task/1690_autoprops/bokeh/models/axes.py#L21

NOTE: the `pass` statements in `bokeh_model.py` and `bokeh_prop.py` need to be replaced with a line that returns a `nodes.error` but I will do that tonight. Everything else is ready.

**Comment by bryevdv** [comment]
Idea for future improvement: right now things like `Either(Auto, Enum(...))` link back just to `properties.Either` would be nice to lightly parse the type to provide links for args too, when appropriate.

**Comment by bryevdv** [comment]
implemented idea above, also fixed small bug in `bokeh-plot` preventing plot generation. Re-deployed dev docs.

**Comment by damianavila** [comment]
OK, I have taken a look and as far as I know about sphinx directives (which is just a little bit), this seems good to me...

**Comment by bryevdv** [comment]
OK one more additional change. @pzwang really wanted help docs to also play better with ipython help, etc. Things are not perfect yet, but this is an OK start, and it will require this approach to even have a chance at working at all. So, how docs are passed as a `help` parameter to the property. I would say this makes the source a little uglier, but the generated reference output and ipython help are quite nice. 

@mattpap can you review the small change to `properties.py` that allows for "template" help strings for `Include` props?

FYI you can see the entire `Axis` class documented here:

http://bokeh.pydata.org/en/dev/docs/reference/models.html#bokeh-models-axes

**Comment by mattpap** [comment]
@bryevdv, so why do we need `help` on `Include`? It doesn't seem to be propagated to the documentation. As I recall, I omitted `help` on purpose.

**Comment by mattpap** [comment]
I saw methods, e.g. `get_class()` added to the generated documentation as well. Is this intentional? If, so maybe it could be somehow separated, because right now it's a little confusing in my view, especially given JSON repr below docs.

**Comment by bryevdv** [comment]
@mattpap we can remove `get_class` with the standard autodoc excludes. Some day I would like to split method from properties but this will do for now. 

The `help` for `Include` is so that we can (optionally) provide a parameterized docstring, so that we can have nice things like:

http://bokeh.pydata.org/en/dev/docs/reference/models.html#bokeh.models.axes.Axis.axis_label_text_font_size

**Comment by mattpap** [comment]
OK, now I see it (regarding `Include`). I don't like too much the implementation because it duplicates some effort with the later code, but I think that's fine for the moment. Also, catching `TypeError`, although I understand the intention, it can have unintentional consequences (hiding bugs).

**Comment by bryevdv** [comment]
@mattpap do you have a suggestion for improvement? There is probably a check we could do instead.

**Comment by mattpap** [comment]
Yes, see line 510 and below (in the new revision) (that's btw. the duplication I mentioned). Anyway, this can be fixed later.

**Comment by bryevdv** [comment]
I can't seem to kick this automation fever :) Added `bokeh-issue`, etc. roles. I will update the docs for the sphinx code tonight, then merge.

**Comment by damianavila** [comment]
Jeje... this `bokeh-issue` is really nice...

**Comment by bryevdv** [comment]
Gah, found (and fixed) a small bug in inline plot saving for `bokeh-plot` (was re-using the same script filenames in different places). Added example of using `bokeh-plot` in a docstring!

http://bokeh.pydata.org/en/dev/docs/reference/plotting.html#bokeh.plotting.Figure.line

Will have @Maggie-M add examples like this to all glyph functions in another PR.

**Comment by damianavila** [comment]
> Added example of using bokeh-plot in a docstring!

This is great @bryevdv... really nice...

**Pull request merged**
