### PR TITLE
Don't allow user agent styles to overwrite ours

### LINKED ISSUE #8645: Use cross-browser compatible CSS for testing
Detected during #8636 

Running on OSX, differences pop up frequently (but not all the time):

```
tests/test_examples.py::test_file_examples[/Users/bryanv/work/bokeh/examples/models/file/anscombe.py-example0-config0]
[INFO] Example run in 0.973s
[INFO] Example rendered in 1.180s
[JS] {log} file:///Users/bryanv/work/bokeh/bokeh/server/static/js/bokeh.js:3481:21 [bokeh] setting log level to: 'info'
[JS] {info} file:///Users/bryanv/work/bokeh/bokeh/server/static/js/bokeh.js:7592:34 [bokeh] document idle at 92 ms
[FAIL] BASELINE DOESN'T MATCH (make sure to update baselines before running tests):
[FAIL] diff --git a/tests/baselines/examples/models/file/anscombe b/tests/baselines/examples/models/file/anscombe
[FAIL] index b6f4e621e..6d0b5a762 100644
[FAIL] --- a/tests/baselines/examples/models/file/anscombe
[FAIL] +++ b/tests/baselines/examples/models/file/anscombe
[FAIL] @@ -1,6 +1,6 @@
[FAIL] -Column bbox=[0, 0, 984, 871]
[FAIL] -  Div bbox=[5, 5, 974, 61]
[FAIL] -  GridBox bbox=[0, 71, 984, 800]
[FAIL] +Column bbox=[0, 0, 984, 923]
[FAIL] +  Div bbox=[5, 5, 974, 65]
[FAIL] +  GridBox bbox=[0, 123, 800, 800]
[FAIL]      Plot bbox=[0, 0, 400, 400]
[FAIL]        LinearAxis bbox=[24, 376, 371, 24]
[FAIL]        LinearAxis bbox=[0, 29, 24, 347]
[WARN] generated and reference images differ: 51.23% of pixels
```

Chrome was run with
```
/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary --headless --remote-debugging-port=9222 --disable-gpu https://chromium.org
```

Version : `Google Chrome 69.0.3489.0 canary`

And tests were run with:
```
py.test -s -v -m examples --tb line --diff-ref origin/master -k examples
```

### PR DESCRIPTION
**Pull request by mattpap**
addresses #8645

### CODE REVIEW

**Comment by bryevdv** [comment]
I'm still seeing some discrepancies on OSX even with this PR

**Comment by mattpap** [comment]
But does it fail? There are known xfailures.

**Comment by bryevdv** [comment]
Yes I see a couple of actual failures. I will post another diff when things are done.

**Comment by bryevdv** [comment]
@mattpap 

[diff2.txt](https://github.com/bokeh/bokeh/files/2861748/diff2.txt)

**Comment by mattpap** [comment]
> +++ b/tests/baselines/bokehjs/examples/charts/charts
> +Column bbox=[0, 0, 2400, 1225]
> 32 +  ToolbarBox bbox=[0, 0, 2400, 23]
> 33 +    ProxyToolbar
> 34 +  GridBox bbox=[0, 25, 2400, 1200]

The first failure looks like old code pre-layout PR was run. There should be no toolbar in this example. Other failures look like nothing has changed with this PR.

**Comment by mattpap** [comment]
Note that `node make build` doesn't compile neither tests nor examples. I think I will change that so that everything is built with this command.

**Comment by bryevdv** [comment]
I did a build from `setup.py` if there is a different command that needs to be issued let me know

**Comment by mattpap** [comment]
`node make examples` and if you could also run `node make test` (specifically for `test:integration`).

**Comment by mattpap** [comment]
And if you could repeat yesterday's test to see if `system-ui` is still present (just to make sure).

**Comment by bryevdv** [comment]
@mattpap  `system-ui` appears to be gone:

screen shot 2019-02-13 at 14 09 43

`node make test:integration` reports some diffs but these look like they could be rounding:

```
diff --git a/bokehjs/test/baselines/Widgets__should_allow_Slider b/bokehjs/test/baselines/Widgets__should_allow_Slider
index 561cf11ee..69961ed99 100644
--- a/bokehjs/test/baselines/Widgets__should_allow_Slider
+++ b/bokehjs/test/baselines/Widgets__should_allow_Slider
@@ -1 +1 @@
-Slider bbox=[0, 0, 300, 30]
+Slider bbox=[0, 0, 300, 31]

  should allow DateSlider
diff --git a/bokehjs/test/baselines/Widgets__should_allow_DateSlider b/bokehjs/test/baselines/Widgets__should_allow_DateSlider
index 6c448e4f3..358780a0b 100644
--- a/bokehjs/test/baselines/Widgets__should_allow_DateSlider
+++ b/bokehjs/test/baselines/Widgets__should_allow_DateSlider
@@ -1 +1 @@
-DateSlider bbox=[0, 0, 300, 30]
+DateSlider bbox=[0, 0, 300, 31]

  should allow RangeSlider
diff --git a/bokehjs/test/baselines/Widgets__should_allow_RangeSlider b/bokehjs/test/baselines/Widgets__should_allow_RangeSlider
index 20143277f..d2315bb5c 100644
--- a/bokehjs/test/baselines/Widgets__should_allow_RangeSlider
+++ b/bokehjs/test/baselines/Widgets__should_allow_RangeSlider
@@ -1 +1 @@
-RangeSlider bbox=[0, 0, 300, 30]
+RangeSlider bbox=[0, 0, 300, 31]

  should allow DateRangeSlider
diff --git a/bokehjs/test/baselines/Widgets__should_allow_DateRangeSlider b/bokehjs/test/baselines/Widgets__should_allow_DateRangeSlider
index c4089ace0..f93c0371a 100644
--- a/bokehjs/test/baselines/Widgets__should_allow_DateRangeSlider
+++ b/bokehjs/test/baselines/Widgets__should_allow_DateRangeSlider
@@ -1 +1 @@
-DateRangeSlider bbox=[0, 0, 300, 30]
+DateRangeSlider bbox=[0, 0, 300, 31]

  should allow DatePicker
  should allow Div
diff --git a/bokehjs/test/baselines/Widgets__should_allow_Div b/bokehjs/test/baselines/Widgets__should_allow_Div
index 4dfe80a6a..22d8085c9 100644
--- a/bokehjs/test/baselines/Widgets__should_allow_Div
+++ b/bokehjs/test/baselines/Widgets__should_allow_Div
@@ -1 +1 @@
-Div bbox=[0, 0, 58, 15]
+Div bbox=[0, 0, 59, 16]

  should allow Paragraph
diff --git a/bokehjs/test/baselines/Widgets__should_allow_Paragraph b/bokehjs/test/baselines/Widgets__should_allow_Paragraph
index 1d1eeb6c5..9905296d2 100644
--- a/bokehjs/test/baselines/Widgets__should_allow_Paragraph
+++ b/bokehjs/test/baselines/Widgets__should_allow_Paragraph
@@ -1 +1 @@
-Paragraph bbox=[0, 0, 58, 15]
+Paragraph bbox=[0, 0, 59, 16]

  should allow PreText
[14:08:35] failed: tests failed
```

**Comment by mattpap** [comment]
@bryevdv, can you try this out again. I doubt there will be any difference, but I would like to see the effect regardless.

**Comment by bryevdv** [comment]
@mattpap seems better, actually:
```
(base) ❯ node make test:integration
[09:11:33] Starting 'test:compile'...
[09:11:39] Finished 'test:compile' after 6.26 s
[09:11:39] Starting 'test:integration'...
Row
  should allow to expand when child policy is max
  should allow to expand when column policy is max
3x3 GridBox
  fixed spacers 50px x 50px
  fixed spacers 50px x 50px, spacing 5px
  fixed spacers 50px x 50px, hspacing 5px, vspacing 10px
  fixed and 1 x-max spacers, c2 auto
  fixed and 2 x-max spacers, c2 auto
  fixed and 2 x-max spacers, c2 flex=2
  fixed and 3 x-max spacers, c2 flex=2
  fixed and 3 x-max spacers, c2 flex=2 align=end
  fixed, inconsistent width/height, row/col auto align=start
  fixed, inconsistent width/height, row/col auto align=center
  fixed, inconsistent width/height, row/col auto align=end
Plot
  should allow no toolbar
  should allow toolbar placement above
  should allow toolbar placement below
  should allow toolbar placement left
  should allow toolbar placement right
  should allow fixed x fixed plot
  should allow max x fixed plot
  should allow fixed x max plot
  should allow max x max plot
  should allow max x fixed plot, aspect 0.8
  should allow fixed x max plot, aspect 0.8
  should allow max x max plot, aspect 0.8
  should allow max x fixed plot, aspect 1.0
  should allow fixed x max plot, aspect 1.0
  should allow max x max plot, aspect 1.0
  should allow max x fixed plot, aspect 1.25
  should allow fixed x max plot, aspect 1.25
  should allow max x max plot, aspect 1.25
  should allow fixed frame 300px x 300px
ToolbarBox
  should allow placement above a figure
  should allow placement below a figure
  should allow placement left of a figure
  should allow placement right of a figure
gridplot()
  should align axes when toolbar_location=null
  should align axes when toolbar_location=above
  should align axes when toolbar_location=right
  should align axes when toolbar_location=left
  should align axes when toolbar_location=below
GridBox
  should allow 20x20 grids of 25x25 px spacers
Widgets
  should allow Button
  should allow Toggle
  should allow Dropdown
  should allow split Dropdown
  should allow CheckboxGroup
diff --git a/bokehjs/test/baselines/Widgets__should_allow_CheckboxGroup b/bokehjs/test/baselines/Widgets__should_allow_CheckboxGroup
index dd8a8a42a..8c1c422f7 100644
--- a/bokehjs/test/baselines/Widgets__should_allow_CheckboxGroup
+++ b/bokehjs/test/baselines/Widgets__should_allow_CheckboxGroup
@@ -1 +1 @@
-CheckboxGroup bbox=[0, 0, 66, 57]
+CheckboxGroup bbox=[0, 0, 65, 57]

  should allow RadioGroup
diff --git a/bokehjs/test/baselines/Widgets__should_allow_RadioGroup b/bokehjs/test/baselines/Widgets__should_allow_RadioGroup
index af49874d0..e4fadc282 100644
--- a/bokehjs/test/baselines/Widgets__should_allow_RadioGroup
+++ b/bokehjs/test/baselines/Widgets__should_allow_RadioGroup
@@ -1 +1 @@
-RadioGroup bbox=[0, 0, 66, 57]
+RadioGroup bbox=[0, 0, 65, 57]

  should allow CheckboxButtonGroup
  should allow RadioButtonGroup
  should allow TextInput
  should allow AutocompleteInput
  should allow Select
  should allow MultiSelect
  should allow Slider
  should allow DateSlider
  should allow RangeSlider
  should allow DateRangeSlider
  should allow DatePicker
  should allow Div
  should allow Paragraph
  should allow PreText
[09:11:43] failed: tests failed
```

**Comment by mattpap** [comment]
OK, so this actually works for heights, just not widths. I pushed a temporary commit fixing font-family to a specific font (the default on linux and windows, given our configuration). @bryevdv, can you try again and in particular test `models/files/widgets`? I think this should finally give uniform results across platforms. If so, we will have to fix the font in testing somehow.

**Comment by bryevdv** [comment]
Here is the output for *examples/models/file/widgets.py*

```
(base) ❯ test_examples -k examples/models/file/widgets.py
======================================================================= test session starts =======================================================================
platform darwin -- Python 3.7.1, pytest-3.9.1, py-1.6.0, pluggy-0.7.1 -- /Users/bryanv/anaconda/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.7.1', 'Platform': 'Darwin-18.2.0-x86_64-i386-64bit', 'Packages': {'pytest': '3.9.1', 'py': '1.6.0', 'pluggy': '0.7.1'}, 'Plugins': {'xdist': '1.23.2', 'metadata': '1.7.0', 'html': '1.19.0', 'forked': '0.2', 'cov': '2.6.0'}}
rootdir: /Users/bryanv/work/bokeh, inifile: setup.cfg
plugins: xdist-1.23.2, metadata-1.7.0, html-1.19.0, forked-0.2, cov-2.6.0
collecting 3814 items                                                                                                                                             bokeh.__version__: 1.1.0dev6-13-gadc20a837-dirty
collected 4408 items / 4407 deselected

Bokeh selenium tests using 'chrome' driver (no-console-error assertions: ON)

tests/test_examples.py::test_file_examples[/Users/bryanv/work/bokeh/examples/models/file/widgets.py-example33-config33]
[INFO] Example run in 0.993s
[INFO] Example rendered in 1.521s
[JS] {log} file:///Users/bryanv/work/bokeh/bokeh/server/static/js/bokeh.js:3492:21 [bokeh] setting log level to: 'info'
[JS] {warning} file:///Users/bryanv/work/bokeh/bokeh/server/static/js/bokeh-tables.js:885:38 [bokeh] jquery-ui is required to enable DataTable.reorderable
[JS] {info} file:///Users/bryanv/work/bokeh/bokeh/server/static/js/bokeh.js:7624:34 [bokeh] document idle at 269 ms
[FAIL] BASELINE DOESN'T MATCH (make sure to update baselines before running tests):
[FAIL] diff --git a/tests/baselines/examples/models/file/widgets b/tests/baselines/examples/models/file/widgets
[FAIL] index 90e9780da..d5b770d9a 100644
[FAIL] --- a/tests/baselines/examples/models/file/widgets
[FAIL] +++ b/tests/baselines/examples/models/file/widgets
[FAIL] @@ -5,8 +5,8 @@ Column bbox=[0, 0, 920, 857]
[FAIL]        Toggle bbox=[5, 46, 300, 31]
[FAIL]        Dropdown bbox=[5, 87, 300, 31]
[FAIL]        Dropdown bbox=[5, 128, 300, 31]
[FAIL] -      CheckboxGroup bbox=[5, 169, 66, 57]
[FAIL] -      RadioGroup bbox=[5, 236, 66, 57]
[FAIL] +      CheckboxGroup bbox=[5, 169, 65, 57]
[FAIL] +      RadioGroup bbox=[5, 236, 65, 57]
[FAIL]        CheckboxButtonGroup bbox=[5, 303, 300, 31]
[FAIL]        RadioButtonGroup bbox=[5, 344, 300, 31]
[FAIL]      Column bbox=[310, 0, 310, 447]
[WARN] reference image https://s3.amazonaws.com/bokeh-travis/1.1.0dev6-8ab9651b2/examples/models/file/widgets.png doesn't exist
FAILED
```

**Comment by mattpap** [comment]
Well, I guess this is not a font issue. I don't know, I will need to find a way to debug this.

**Comment by mattpap** [comment]
I will merge this PR anyway, because those changes will be useful in my other work. I will keep the issue open for further investigation regarding the source of the differences.

**Comment by bryevdv** [comment]
> I will merge this PR anyway, because those changes will be useful in my other work. I will keep the issue open for further investigation regarding the source of the differences.

Just to be clear, integration tests will fail locally on OSX for the time being? FWIW some light investigation online suggests people typically have to resort to per-platform results for comparisons.

**Comment by mattpap** [comment]
> (...) have to resort to per-platform results for comparisons.

That's understandable if comparing different browsers. If we are going to do baseline tests in other browsers in the future, we will have to have a set of baselines for each one. However, testing the same browser with the same significant settings (possibly, though I may be overlooking a more or less obscure property affecting size computation) should work with a single set of baselines. I'm pretty sure that figuring this out would be a minute of work if I had access to OSX. Otherwise I'm blindly poking at stuff, though I learnt a lot about CSS, fonts, etc. in the process.

**Comment by mattpap** [comment]
> (...) integration tests will fail locally on OSX for the time being?

Yes, but as I said, I will be investigating further. It's obviously wrong to not be able to update baselines on one of the major platforms.

**Pull request merged**
