### PR TITLE
added accessible color palette

### PR DESCRIPTION
**Pull request by chinmaychahar**
- [x] issues: addresses #11481

Updated the color palette used in examples/styling/mathtext/latex_schrodinger.py referencing docs [here](https://docs.bokeh.org/en/latest/docs/reference/palettes.html#accessible-palettes)

<table>
  <tr>
    <td>Initial color palette</td>
    <td>Updated color palette</td>
   </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
</table>

### CODE REVIEW

**Comment by bryevdv** [comment]
Hi @chinmaychahar can you update the OP with before/after screenshots? Also we will need to update both gallery thumbnails to go along with this change. Some of the recent merged PRs for accessible palettes would be a good place to look for the required changes e.g. https://github.com/bokeh/bokeh/pull/12946 Let me know if you need a more detailed reference!

**Comment by chinmaychahar** [comment]
HI @bryevdv I've updated the PR with the before/after screenshots. As for the thumbnail, I have the original png but resizing it to the desired 300x300 is leading to reduced quality. Any suggestions on how I can tackle that?

**Comment by bryevdv** [comment]
cc @ianthomas23 just to wiegh in on the new colors 

> As for the thumbnail, I have the original png but resizing it to the desired 300x300 is leading to reduced quality

Can you post it for us to examine? The images are just for gallery thumbnails so they are intended to be small / low quality.

**Comment by chinmaychahar** [comment]
@bryevdv I just updated the new thumbnails. Let me know if they need any changes! 

Also, if there are any changes required to the palette too.

**Comment by bryevdv** [comment]
I wonder if swapping the colors (having the dark blue under the l line, and orange over) would be slightly more aesthetically pleasing.

**Comment by chinmaychahar** [comment]
Sure @bryevdv that looks something like this: 

<table>
  <tr>
    <td></td>
  </tr>
</table>

**Comment by ianthomas23** [comment]
> cc @ianthomas23 just to weigh in on the new colors

I am happy with the new colors. The original colors were taken from wherever I took the original idea from, and the new colors seem much better.

**Comment by bryevdv** [comment]
@chinmaychahar seeing the swapped version, I don't actually have any preference. Whichever you want to use is fine!

**Comment by chinmaychahar** [comment]
I'm fine with the current version if that's alright. I've updated both the code as well as the thumbnails!

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
Thanks @chinmaychahar !

**Pull request merged**
