### PR TITLE
Data range fixes

### LINKED ISSUE #3408: Improve DataRange updating policies re: server usage
Reference: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/common/client.coffee#L232

In the above ML discussion it was discovered that the auto-ranging that `DataRange1d` does was causing a huge spike in traffic back to the server from the browser (every render, basically) when there was no need for it. In general, BokehJS should be examined for such inadvertent and "magic" updates triggering pushes to the server. But `DataRange1d` seems to be a big culprit, and just switching to  explicit ranges in the example offered dramatic performance improvements. So, for a "quick fix" I'd like to modify `DataRange1d` to play more nicely. Here is my initial proposal:

* Add properties `start_policy` and `end_policy` that accept: `never`, `once`, `always`

The default would be `once` which would mean that auto-ranging would only happen once, on first load, and not again subsequently. Should there also be a way to "reset" the state so that ranging happens once (again)?

I'd also like to take the opportunity to get rid of the compute properties on `DataRange1d` so that it can be reflected simply to the server like any other model:

* `start` and `end` are simple normal properties inherited from `Range1d`

The `DataRange1d` would update `start` and `end` as described by the policy, so no computed props would be needed. 

Thoughts, @bokeh/core and esp. @mattpap @havocp @birdsarah ?

It think I can have this work done in under a day (including tests) once there is agreement on a plan, but time is short for `0.11` so we would need to come to agreement very soon.

### PR DESCRIPTION
**Pull request by bryevdv**
issues: fixes #3408 

This builds on #3416 and #3419 (unfortunately for the diff, commits for this PR start with https://github.com/bokeh/bokeh/commit/09a6bb3862c08ea472749d221ce1d9a96d41c7aa)

I would like to add UG docs after the code freeze. 

ping @mattpap @havocp @pzwang 

`examples/interaction/ajax_source.py` is a good example to run to see the follow mode in action.

I am not 100% happy with testing internal interfaces but it's still a large improvement over what was there previously (almost no tests). Suggestions for improving the tests welcome. 

ping @birdsarah too this might affect your range bounds work.

### CODE REVIEW

**Comment by bryevdv** [comment]
@bokeh/dev OK I just tested every example on OSX/Safari/Python 3.4, here is the complete list of problems:
```
../../examples/charts/file/boxplot_multi.py:
 marker, whisker color ignored

../../examples/glyphs/iris_splom.py:
 missing text labels

../../examples/glyphs/tile_source.py:
 resize canvas resets plot bounds

../../examples/plotting/file/box_annotation.py:
 missing box annotations

../../examples/plotting/file/burtin.py:
 border did not resize

../../examples/plotting/file/line_select.py:
 selection crashes call stack exceeded

../../examples/plotting/server/hover.py:
 no points (layout problem, edit_variable... increase border to back 50?)
```

Some of these are trivial, and all of them should be fixable in the next few days. I intend to continue testing this branch on other platforms, but I believe this is as stable as anything has been in some time. In particular, except for two non-server related problems, ***all** of the app/server examples work really well.

**Comment by bryevdv** [comment]
@pzwang @bokeh/core  here is a GIF of the "follow" mechanism:

ezgif com-video-to-gif-3

**Comment by bryevdv** [comment]
ezgif com-video-to-gif-4

@pzwang Here's a basic pausable/restartable OHLC ticker. It's 60 lines of code, most of which is the simulation: https://gist.github.com/bryevdv/205840c34c07ecf11f84

**Comment by bryevdv** [comment]
@havocp one thing I think we do need is a way to batch updates, is there any thing right now that could do that?

**Comment by bryevdv** [comment]
One thing we don't do (yet) is let one auto ranging axis be informed by the current extend of the other range. E.g., here the y-axis grows to accommodate all the data in the current buffer, even if it is off screen.

**Comment by bryevdv** [comment]
OK, last version: 

screen shot 2015-12-27 at 11 18 29 pm

76 lines, adds four different moving averages

**Comment by pzwang** [comment]
Very nice!

> One thing we don't do (yet) is let one auto ranging axis be informed by the current extend of the other range. E.g., here the y-axis grows to accommodate all the data in the current buffer, even if it is off screen.

Ironic, Chaco had the opposite problem!

**Comment by bryevdv** [comment]
OK, Adding the second MACD indicator chart was good, there's a little fix needed to handle "during interactions" when data ranges are linked. I will do that tomorrow.

screen shot 2015-12-28 at 12 14 26 am

**Comment by bryevdv** [comment]
@bokeh/core @havocp @mattpap I plan to merge #3416 #3419 and this PR very soon, last call.

**Comment by bryevdv** [comment]
Ok, the last commit lets pause/resume on updating ranges work when ranges are shared as well. It's  not amazing but its simple and comprehendible, enough for now.

**Comment by bryevdv** [comment]
Plan  to merge once TravisCI passes.

**Pull request merged**
