### PR TITLE
fix Rect rendering with log axis

### LINKED ISSUE #5336: Strange behaviour of Rect-Glyph
Hello,
It looks like the `Rect` glyph has buggy behavior somewhere!!!
See attached example where you can `draw` a rectangle via `Selectbox`. After selecting the CustomJS will update the source of the `Rect` and the `Scatter`. The `Scatter`-Points and the `Rect`-Corner-Points do not match when using logarithmic scale.
Is this a bug?

```
from bokeh.plotting import figure, show
from bokeh.models.tools import BoxSelectTool
from bokeh.models.sources import ColumnDataSource
from bokeh.models.callbacks import CustomJS
from bokeh.io import output_file
from bokeh.models.glyphs import Rect


plot = figure(plot_width=600, plot_height=600,
              x_range=(0,20), y_range=(0,20),
              y_axis_type="log"
              )

# Initial Data
x = [10, 15]
y = [10, 15]

# Scatter
sc_source = ColumnDataSource(data=dict(x=x, y=y))
plot.scatter(source=sc_source, x='x', y='y', size=20)

# Rect
rect_source = ColumnDataSource(data=dict(x=[(x[0]+x[1])/2], y=[(y[0]+y[1])/2], width=[[x[1]-x[0]]], height=[y[1]-y[0]]))
rect = Rect(x='x',
            y='y',
            width='width',
            height='height',
            dilate=True,
            fill_alpha=0.3)
plot.add_glyph(rect_source, rect)

callback = CustomJS(args=dict(rect_source=rect_source, sc_source=sc_source), code="""
            var geometry = cb_data['geometry'];
            console.log(geometry);

            var width = geometry['x1'] - geometry['x0'];
            var height = geometry['y1'] - geometry['y0'];
            var x = geometry['x0'] + width/2;
            var y = geometry['y0'] + height/2;

            console.log(width, height, x, y);
            rect_source.data = {'x': [x], 'y': [y], 'width': [width], 'height': [height]};
            rect_source.trigger('change');

            sc_source.data = {'x': [geometry['x0'], geometry['x1']], 'y': [geometry['y0'], geometry['y1']]};
            sc_source.trigger('change');

""")
t = BoxSelectTool(callback=callback)
plot.add_tools(t)
plot.toolbar.active_drag = t


output_file('select_log.html')
show(plot)
```

Have a nice week,
Raphael

### PR DESCRIPTION
**Pull request by clairetang6**
This PR is to make the Rect glyph behave better when used with log axes. 

Previously, Rect rendering relied on mapping the center point (x, y) to screen space and then rendering a rectangle with the top left corner point (sx - sw/2, sy - sh/2) and a width and height of sw and sh (mapped from w, h). This is a problem for log axis where the center point of the rectangle is not exactly in the center in screen space. 

This PR fixes this by computing the top left corner point in data space, then mapping that point to screen space, and using that mapped point for rendering.

I added some tests, but then realized we need a screenshot test here. Also, hit-testing is not working exactly right yet (because it also uses sw/2 and sh/2). 

- [x] issues: fixes #5336
- [x] tests added / passed
~~- [ ] release document entry (if new feature or API change)~~
- [x] fix hit-testing for log axis
- [x] add screenshot test

### CODE REVIEW

**Comment by clairetang6** [comment]
Here's a script to see what's going on. Log rendering works correctly (in the case of the angled rect, it's still rotated in screen space which may not be exactly "correct"). Hit-testing on the log axis when the height is not in screen units is slightly wrong. 

```
from bokeh.models import ColumnDataSource
from bokeh.models.glyphs import Rect
from bokeh.plotting import output_file, show, figure
from bokeh.layouts import gridplot

output_file('rect_hover.html', mode="relative-dev", root_dir="/users/claire/documents/bokeh/bokehjs/build/")

x = [2]
y = [30]
w = [10]
h = [20]
source = ColumnDataSource(dict(x=x, y=y, w=w, h=h))
tools = 'box_zoom,box_select,crosshair,resize,reset, hover'
kws = {'x':"x", 'y':"y", 'width':"w", 'height':"h", 'source':source}
fig_kws = {'plot_width': 350, 'plot_height': 350, 'tools': tools, 'y_range':(10, 80)}

plot1 = figure(title="linear axis", **fig_kws)
plot1.rect(**kws)

plot2 = figure(title="log axis", y_axis_type="log", **fig_kws)
plot2.rect(**kws)

plot3 = figure(title="linear axis, angled", **fig_kws)
plot3.rect(angle=-0.785398, **kws)

plot4 = figure(title="log axis, angled", y_axis_type="log", **fig_kws)
plot4.rect(angle=-0.785398, **kws)

plot5 = figure(title="linear axis, width in screen units", **fig_kws)
plot5.rect(width_units="screen", **kws)

plot6 = figure(title="log axis, width in screen units", y_axis_type="log", **fig_kws)
plot6.rect(width_units="screen", **kws)

plot7 = figure(title="linear axis, height in screen units", **fig_kws)
plot7.rect(height_units="screen", **kws)

plot8 = figure(title="log axis, height in screen units", y_axis_type="log", **fig_kws)
plot8.rect(height_units="screen", **kws)

for plot in [plot1, plot2, plot3, plot4, plot5, plot6, plot7, plot8]:
    plot.circle(x=x, y=y, color='black')

show(gridplot([[plot1, plot2], [plot3, plot4], [plot5, plot6], [plot7, plot8]]))
```

**Comment by mattpap** [comment]
> `output_file('rect_hover.html', mode="relative-dev", root_dir="(...)")`

Pro tip: use `BOKEH_DEV=true python script_name.py`, so that you don't have to configure things inline.

**Comment by mattpap** [comment]
The example you show should be added as some sort of test, though I'm not sure where.

**Comment by bryevdv** [comment]
@mattpap probably an image or selenium test for now

**Comment by bryevdv** [comment]
@clairetang6 can you drop a screen shot in here?

**Comment by clairetang6** [comment]
@mattpap, Thanks for the tip! That will be useful. 

I'm planning to add a log hit-testing test like the one I added for regular hit-testing, but the rendering test should be a screenshot test. @bryevdv, Looking at the documentation, it looks like I need SAUCELABS_USERNAME and SAUCELABS_API_KEY? I haven't ever run any screenshot tests.

**Comment by clairetang6** [comment]
In my last four commits, I made point hit_testing more correct, so that it works with log axes and also when the x and y axis are very different in scale. 

The point hit-testing code for the Rect has two steps:
1. use the spatial index to find all Rects that a point might be hitting (with a bbox created around the point)
2. further test if that point is in the Rect, accounting for an angle if there was rotation. 

There was a problem with the way that step 1 was being done before, because it didn't account for situations where the two axes are scaled very differently. When they are scaled differently, a fixed screen distance can be very different data distances. To fix this, I made it so that each Rect knows the length of its half-diagonal in screen space. This is the furthest distance a point can be away from the center and still hit the rect at some angle. Then I mapped this screen distance into data distances for the two axes separately to get a bbox to use in step 1.

**Comment by clairetang6** [comment]
I saw in an email that I could ask to not have my commits squashed on merge. I would like to keep my commit history and would also appreciate any advice/feedback to make them better.

**Comment by mattpap** [comment]
@clairetang6, I'm pretty sure we don't have a policy for this, but if you want to keep individual commits, it's not unreasonable to assume each commit must pass tests on travis ci, aka. must have green tick next to it. How to achieve this is a different story.

**Comment by clairetang6** [comment]
@mattpap, Ok, assuming I could write each commit error-free, does that mean that I would push each commit up one at a time so that they are run individually on travis? I also have been adding failing tests first as separate commits, before committing the code that would fix those tests. My thought was that it might be easier if anyone wanted to see the tests fail and pass themselves, they could just check out those specific commits.

**Comment by bryevdv** [comment]
@clairetang6 Yes if you want CI tests for each commit, you will need to push on each commit. But please be mindful of others. We only have a combined six workers, and full test runs take ~20 minutes. This approach will not scale during "high traffic" periods. 

Regarding adding failing tests first, I think the best strategy there is simply to get in the habit of running tests locally. Then you can observe the test fail locally, make changes, observe it pass, then push. 

@mattpap @clairetang6 I do think that squash and merge should be the *default*, but I am absolutely not opposed to having history preserving merges for those that 1) want them 2) take the time to make a very clean commit history. Perhap we can add a label `HISTORY REQUESTED` to indicate that an author does not want a squash merge. TBD: should the default in that case be "rebase and merge"? I think so.

**Comment by clairetang6** [comment]
@bryevdv, about the tests, I do test the tests (haha) locally first, but my thinking was if other people wanted to see the fail -> pass, it would be easier for them, but I think I realize now that probably no one has the time to be checking each of the tests that I'm writing like that. So I can include previously-failing tests and the code that fixes them in one commit from now on. 

The one thing about this PR is that in addition to fixing the rendering (which was the original issue), I also fixed hit-testing in certain circumstances. It was related to the issue because having a log axis made it very likely that those circumstances would happen, but also unrelated because it fixed that problem for linear axes too. 

If I were to change the commit history now, I would just make two commits, one for rendering and one for hit-testing, but it's not super important. I just wanted to know what the policy for keeping my commits was.

**Comment by bryevdv** [comment]
We don't need to do it now, but FYI eventually we might want to shove a few more log-related things into this one image test. Ideally we'd have separate tests, but the overhead and fragility of saucelabs means we have to be a but more frugal

**Comment by bryevdv** [comment]
> If I were to change the commit history now, I would just make two commits, one for rendering and one for hit-testing, but it's not super important. I just wanted to know what the policy for keeping my commits was.

Well it's up to you, if you'd like to rebase and re-organize I'm happy to not squash. The policy is what we decide it is and still up for discussion. As I said my pref would be squash as a default with a label to indicate a request to rebase merge.

**Comment by bryevdv** [comment]
As I expected there was a random error (I think there is currently an upstream issue) but this new test also reported failure (445 pixels different)

**Comment by clairetang6** [comment]
Ok, let's squash and merge this one and I'll keep this discussion in mind for next time. 

I see the error, should I restart it? The screenshot looks correct on SauceLabs.

**Comment by bryevdv** [comment]
can restart it, but I do think it's actually failing for some reason

**Comment by clairetang6** [comment]
Ok, I looked at the generated report [here](https://s3.amazonaws.com/bokeh-travis/192532654/tests/pytest-report.html), and it looks like the icons for the tools are slightly different sizes. Does anyone know why that might be or how to fix it?

**Comment by bryevdv** [comment]
@canavandl any ideas?

**Comment by mattpap** [comment]
> can restart it, but I do think it's actually failing for some reason

This is a new test. If the new image was generated in a different web browser than is used on sauce labs, then there may be trivial differences like this. @clairetang6, you should use the image generated in integration tests as the basis or use the same web browser for creating new tests.

**Comment by bryevdv** [comment]
I'm assuming @clairetang6 used
```
py.test -m integration -k test_arrow --driver=SauceLabs --set-new-base-screenshot
```
is that correct? That should set the screen shot using the suacelabs machinery, afaik. @birdsarah @canavandl  ?

**Comment by clairetang6** [comment]
Yes, I did use sauce connect and saucelabs to generate the screenshot. I could try generating another screenshot the same way and see what I get sometime later today.

**Comment by birdsarah** [comment]
it's hard for me to believe that it's this, but @clairetang6  - you could try running the base screenshot with python 3.4 as that's what's run on travis.

**Comment by birdsarah** [comment]
the test_arrow is failing for a non screenshot diff reason which is confusing because all the other tests work.

**Comment by bryevdv** [comment]
I believe  SL had a network issue last night, there were spurious errors (not failures) over all tests for a number of hours. I've restarted it. But here is the relevant actual failure tho:
```
______________________ test_rect_rendering_with_log_axis _______________________
[gw2] linux -- Python 3.4.5 /home/travis/miniconda/bin/python
---------------------------- Captured stderr setup -----------------------------
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): saucelabs.com
DEBUG:requests.packages.urllib3.connectionpool:http://saucelabs.com:80 "GET /rest/v1/bokehplots/jobs/cdf7ab47f7624162bd0d25203e19b4a0 HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): saucelabs.com
DEBUG:requests.packages.urllib3.connectionpool:http://saucelabs.com:80 "PUT /rest/v1/bokehplots/jobs/cdf7ab47f7624162bd0d25203e19b4a0 HTTP/1.1" 200 None
DEBUG:selenium.webdriver.remote.remote_connection:POST http://bokehplots:f7047da0-5e51-4f77-9761-cb741be552be@162.222.75.33:80/wd/hub/session {"desiredCapabilities": {"tunnel-identifier": "10836.7", "platform": "Linux", "name": "tests.integration.plotting.test_rect_glyph_with_log_axis.test_rect_rendering_with_log_axis", "browserName": "firefox", "tags": ["screenshot", "integration"]}}
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://bokehplots:f7047da0-5e51-4f77-9761-cb741be552be@162.222.75.33:80/wd/hub/session/6c977a9d2d344dd588f42f13bc687764/timeouts/implicit_wait {"sessionId": "6c977a9d2d344dd588f42f13bc687764", "ms": 10000.0}
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://bokehplots:f7047da0-5e51-4f77-9761-cb741be552be@162.222.75.33:80/wd/hub/session/6c977a9d2d344dd588f42f13bc687764/window/current/size {"sessionId": "6c977a9d2d344dd588f42f13bc687764", "width": 1200, "height": 600, "windowHandle": "current"}
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
----------------------------- Captured stdout call -----------------------------
FAIL: Images are visibly different
445 pixels are different
```

**Comment by birdsarah** [comment]
for the 445 pixel error i'm suggesting the following punts:
1) just retake the screenshot
2) retake it when running tests from py3.4 (claire's using py2.7)

these are just punts, i'm not sure why its broken

**Comment by bryevdv** [comment]
@clairetang6 I have restarted the selenium tests,  think the failures there were spurious.

The new JS test failures have to do with the recent PR to remove underscore. AFAICT Some small changes will be in order. @mattpap can you advise

**Comment by mattpap** [comment]
@clairetang6, merge `master` into this PR and replace `array_max` with `max` from `core/util/array`.

**Comment by canavandl** [comment]
So I investigated the integration test failure and couldn't figure it out. The test passes if I run it locally...

My non-solution suggest is to hide the toolbar (or not have tools) on the plot, as the tools aren't what's intended to be tested.

**Comment by bryevdv** [comment]
@canavandl that is actually the real solution :) these tests should minimally contain only the things being tested

**Comment by bryevdv** [comment]
Well the good news is the new selenium test is passing, the bad news is others are not, still trying restarts for the time being.

**Comment by bryevdv** [comment]
I'm at a loss. It is the same two selenium tests failing every time:
```
____________________ test_tap_with_callback_triggers_alert _____________________
___________________________ test_hover_changes_color ___________________________
```

**Comment by bryevdv** [comment]
Tests are green! merging now, thanks @clairetang6 !

**Comment by mattpap** [comment]
> Tests are green!

Unfortunately this means nothing. None of us looked at examples' report and there a lot of failures (https://s3.amazonaws.com/bokeh-travis/194275877/examples.html, see e.g. calendars example).

**Comment by bryevdv** [comment]
@mattpap I look at them often, but that's no substitute for automation. It's clear we need some kind of hard fail test for basic glyph drawing. I will make a separate issue. 

I will revert this for now, @clairetang6 I have restored the branch so a fix can go together with the original issue fix in a single PR.

**Pull request merged**
