### PR TITLE
Backport current sphinx theme to 2.4.3

### PR DESCRIPTION
**Pull request by bryevdv**
I really want at the last published 2.4.x version to match the 3.0 versions, at the very least. This PR backports docs theme changes to `branch-2.4` for manual re-deployment (no new release is planned, if CI fails I may not even merge this)

@tcmetzger please give this a quick once over, and then I will manually deploy to the real URL if it looks good. A test deployment is viewable at 

https://docs.bokeh.org/en/test/

If you want to build locally it's not too bad but it would probably be simplest to go through it in a call. 

Eventually I turned off strict (-W) mode since the warnings took longer and longer to fail out. I think there are some missing xrefs for a few classes like RGB and JSON. I can live with that. 

Ideally I would continue this process with other older versions but I am not sure I have the stamina for it.

### CODE REVIEW

**Comment by tcmetzger** [comment]
That sounds great, thanks for  putting this together! While we are at it, we could take this opportunity to also backport the updates to the Dev docs installation section (`pip install -e .`, etc.). The instructions in the current 2.4 docs won't work with the currently available 3.0 branch, so it would be great to have up to date info in the docs!

**Comment by tcmetzger** [comment]
I took a look at https://docs.bokeh.org/en/test/ and couldn't see anything that looks off. Good to go, unless we do want to add the dev docs backport!

**Comment by bryevdv** [comment]
OK the tests are pretty hopeless. I am not too concerned about the dev docs setup section, any one trying to do dev should work from the latest current docs and we can just direct anyone there if we need to. I will deploy these tomorrow. 

@mattpap do you have any preference to merge this (broken CI) or not?

**Comment by bryevdv** [comment]
I am inclined to merge this, even tho CI is broken on the branch:

* CI would be broken currently anyway
* There will probably never be another 2.4.x release
* We would lose the ability to reproduce this docs state otherwise

**Comment by mattpap** [comment]
> do you have any preference to merge this (broken CI) or not?

As my understanding goes, tests are broken anyway due to various reasons (e.g. lack of upper bounds in our deps) and this PR doesn't affect that additionally. In that case I don't see a reason not to merge.

**Pull request merged**
