### PR TITLE
Backports for 3.6.1

### PR DESCRIPTION
**Pull request by bryevdv**
This PR collects bug-fixes and tasks for a 3.6.1 release:

- [x] #14093 
- [x] #14109
- [x] #14125
- [x] 3.6.1 release notes
- [x] updated switcher.json

Release checklist:

- [x] do **not** squash merge
- [x] update milestone to `3.6.1` of relevant issues and PRs
- [x] remove `NEEDS BACKPORT` label

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap I'll leave this one backport PR open we can use it for whenever 3.6.1 happens (not as much urgency now)

**Comment by bryevdv** [comment]
@mattpap I think there are users waiting on #14109 fix I'd like to apply that and release by tomorrow, the others can wait for a 3.6.2 if they are not ready

**Comment by mattpap** [comment]
I removed the two issues from the TODO list. Given they require some more work, they will have to wait for 3.6.2.

**Comment by bryevdv** [comment]
@mattpap can you comment on the BokehJS CI failures?

**Comment by mattpap** [comment]
> can you comment on the BokehJS CI failures?

You will need to backport PR #14125. Failures on Ubuntu were spurious.

**Comment by mattpap** [comment]
@bryevdv, if you don't have time to spare, let me know if you would like me to finish this release.

**Comment by bryevdv** [comment]
@mattpap i would appreciate that this week is not great for me.

**Review by mattpap — APPROVED** [review]

**Pull request merged**
