### PR TITLE
Backports for 2.2.1

### PR DESCRIPTION
**Pull request by bryevdv**
This PR backports fixes for #10435 and #10426  from `branch-2.3` to `branch-2.2`

cc @mattpap @philippjfr I think just #10431 and #10436 and then we can release. 

As an aside PRs like this should not get milestones or be issue-PRs because they should not show up in the CHANGELOG (perhaps we could add a BACKPORT label and explicitly exclude them if we want to apply those other kinds of labels)

### CODE REVIEW

**Comment by bryevdv** [comment]
@philippjfr I have one more small fix to get in this, was there something else you wanted to go in?

**Comment by philippjfr** [comment]
I'd like to get this one in there: https://github.com/bokeh/bokeh/pull/10449

**Comment by bryevdv** [comment]
@mattpap @philippjfr this is ready in case you want to make any quick/final review. Not planning on any rc builds, just straight to 2.2.1

**Comment by bryevdv** [comment]
@mattpap seen several spurious BokehJS-CI failures suddenly today

**Pull request merged**
