### PR TITLE
Backports for 3.3.4

### PR DESCRIPTION
**Pull request by bryevdv**
* [x] #13503 
* [x] #13568 
* [x] #13588  
* [x] #13597
* [x] #13626
* [x] #13647 
* [x] #13655 
* [x] #13657 
* [x] #13659
* [x] #13661
* [x]  3.3.4 release notes
* [x] update switcher.json
* [ ] do not squash merge

### CODE REVIEW

**Review by philippjfr — APPROVED** [review]

**Comment by bryevdv** [comment]
@mattpap can you advise on this test failure for the last (clean) backport?
```diff
diff --git a/tests/baselines/cross/regressions/issue_13660.json5 b/tests/baselines/cross/regressions/issue_13660.json5
index 924c76e..499446d 100644
--- a/tests/baselines/cross/regressions/issue_13660.json5
+++ b/tests/baselines/cross/regressions/issue_13660.json5
@@ -89,7 +89,6 @@
                         },
                       ],
                     ],
-                    plain: true,
                   },
                 },
               },

```
Can I just add/delete the line?

**Comment by mattpap** [comment]
Cross integration tests' baselines need to be updated (due to lack of PR #13618 in this branch).
```diff
diff --git a/tests/baselines/cross/regressions/issue_13660.json5 b/tests/baselines/cross/regressions/issue_13660.json5
index 924c76e..499446d 100644
--- a/tests/baselines/cross/regressions/issue_13660.json5
+++ b/tests/baselines/cross/regressions/issue_13660.json5
@@ -89,7 +89,6 @@
                         },
                       ],
                     ],
-                    plain: true,
                   },
                 },
               },
```

**Comment by mattpap** [comment]
> Can I just add/delete the line?

Looks like we commented at the exact same time. It needs to be deleted.

**Comment by mattpap** [comment]
Those timeouts that happen in bokehjs' tests may be quite persistent, because new tests heavily rely on improved reliability of new UI event handling and related changes.

**Comment by bryevdv** [comment]
> Those timeouts that happen in bokehjs' tests may be quite persistent, because new tests heavily rely on improved reliability of new UI event handling and related changes.

I expect this will be the last 3.3.x release so I was just going to ignore any spurious failures, but cut an rc and examine the docs for a quick check before actual release.

**Comment by mattpap** [comment]
> (...) so I was just going to ignore any spurious failures (...)

That's the course of action I was going to suggest.

**Review by mattpap — APPROVED** [review]
Looks good.

**Pull request merged**
