### PR TITLE
Add __main__.py so we can do "python -m bokeh"

### PR DESCRIPTION
**Pull request by almarklein**
Being able to do `python -m bokeh` allows using the bokeh command unambiguously for a specific Python version. Plus it allows using the bokeh command when Bokeh is not installed (e.g. with `setup.py develop`). 

This may also be an alternative solution for the cmd on Windows (or did we fix that already?)

I think this should go into 0.11.1, unless we want to use it as a fix for the Win issue.

cc @damianavila

### CODE REVIEW

**Comment by bryevdv** [comment]
@bokeh/core any thoughts? seems fine to me tho I don't imagine ever using `python -m bokeh` personally

**Comment by havocp** [comment]
previous discussion at https://github.com/bokeh/bokeh/pull/3202#discussion_r46074258

I guess -m bokeh.command already works ?

**Comment by bryevdv** [comment]
yes `python -m bokeh.command` should already work. I am not sure I'd like to have both, since it's more to document and maintain. I'm +0 on one or the other, with a slight preference for `python -m bokeh`

**Comment by canavandl** [comment]
I'm a soft +1 on the PR. I think it'll preclude some Win issues related to issues of adding the `bokeh` command to the sys PATH.

Either way - I don't see any documentation for `python -m bokeh.command` and/or this PR. I think we'd do well to have a line explaining setup.py should add the bokeh command stuff to your PATH, what that means, and what to do if it doesn't work (for entry-level users).

**Comment by damianavila** [comment]
>I'm +0 on one or the other, with a slight preference for python -m bokeh

+1

>Either way - I don't see any documentation for python -m bokeh.command and/or this PR. I think we'd do well to have a line explaining setup.py should add the bokeh command stuff to your PATH, what that means, and what to do if it doesn't work (for entry-level users).

I have some ideas about how to support win entry points but I need to investigate a little bit more before proceeding with a PR... but it is in my todo list to enable `bokeh` command at win as well...

**Comment by fpliger** [comment]
I'm inline with previous thoughts... My first reaction would be to use what we have ( `bokeh.command`) but just having `python -m bokeh` is definitely more straightforward from an user pov..

**Comment by bryevdv** [comment]
I think we are in agreement. I'll have Maggie update this PR and we can get it merged today.

**Pull request merged**
