### PR TITLE
remove specific custom code that bypass end_aggregation on Interval g…

### LINKED ISSUE #3875: Error with histogram
I am trying to create a Histogram with Bokeh and I'm getting the following error. The histogram is completely wrong.

For example

I have this list:

[1205.0, 2527.0, 1745.0, 1556.0, 493.0, 2276.0, 556.0, 1928.0, 2641.0, 1897.0, 1891.0, 1545.0, 1307.0, 1692.0, 1543.0, 1282.0, 775.0, 2032.0, 1240.0, 473.0, 1612.0, 605.0, 327.0, 946.0, 541.0, 1539.0, 529.0, 628.0, 1453.0, 297.0, 703.0, 269.0, 751.0, 245.0, 1182.0, 515.0, 435.0, 383.0, 457.0, 730.0, 614.0, 414.0, 324.0, 776.0, 611.0, 544.0, 538.0, 579.0, 806.0, 459.0, 458.0, 626.0, 621.0, 544.0, 535.0, 385.0, 401.0, 614.0, 665.0, 488.0, 172.0, 142.0, 37.0, 453.0, 355.0, 22.0, 502.0, 273.0, 720.0, 582.0, 198.0, 198.0, 597.0, 516.0, 815.0, 402.0, 605.0, 711.0, 614.0, 468.0]

And when I try to create a histogram:

hist = Histogram(val)
show(hist)

I get: (the Y-axis is completely wrong) ... How can I solve this?
Thanks

### PR DESCRIPTION
**Pull request by fpliger**
issues: fixes #3875

### CODE REVIEW

**Comment by fpliger** [comment]
Marking this as `ready` since it doesn't seem to affect all our examples and tests...

**Comment by bryevdv** [comment]
Is this something we could add a test for?

**Comment by fpliger** [comment]
I'm not sure.. without context I can't tell why it was needed... But actually, I can (and should have) add a test to reproduce the Histogram issue that brought this to light.  Tnx! :+1:

**Comment by dennisobrien** [comment]
I just ran across this very issue and was about to file a bug when I found this.  Here are a few tests to see the bug visually.  You can see in the cases where there is only one data value in a bin, it uses the value instead of the count.

```
from bokeh.io import output_notebook
output_notebook()
import bokeh
print(bokeh.__version__)

from bokeh.charts import Histogram
from bokeh.plotting import figure
from bokeh.io import show, vplot, hplot
import numpy as np

values = np.arange(10)
hist, edges = np.histogram(values, density=True, bins=10)
hist_fig = figure(title='bokeh.plotting.figure', plot_width=400, plot_height=400)
hist_fig.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:])
hist_chart = Histogram(values, agg='count', title='bokeh.charts.Histogram', bins=10, plot_width=400, plot_height=400)

show(hplot(hist_fig, hist_chart))
```
image

```
from bokeh.charts import Histogram
from bokeh.plotting import figure
from bokeh.io import show, vplot, hplot
import numpy as np


k, theta = 1.0, 10.0
np.random.seed(42)
measured = np.random.gamma(k, theta, 1000)
hist, edges = np.histogram(measured, density=True, bins=50)
hist_fig = figure(title='bokeh.plotting.figure', plot_width=400, plot_height=400)
hist_fig.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:])
hist_chart = Histogram(measured, agg='count', title='bokeh.charts.Histogram', bins=50, plot_width=400, plot_height=400)
show(hplot(hist_fig, hist_chart))
```
image

**Comment by dennisobrien** [comment]
I just ran the above test against the latest master (0.12.0dev2-56-gc40071a) and verified that it is fixed.

image

**Pull request merged**
