### PR TITLE
Use math library instead of numpy for nan/inf checks

### PR DESCRIPTION
**Pull request by mrocklin**
Math is much faster than NumPy for scalar checks

### CODE REVIEW

**Comment by bryevdv** [comment]
@mrocklin Are you sending lists instead of arrays in your CDS? I would not actually expect you to hit this code path if you CDS columns are real arrays.

**Comment by mrocklin** [comment]
I frequently stream small lists

**Comment by bryevdv** [comment]
OK, fair enough. This change seems reasonable in any case I just wanted to check that nothing unexpected was happening.

**Comment by mrocklin** [comment]
You're right though that I should consider switching to numpy arrays when lists get large.  I don't suppose you have any intuition on where the tipping point is here?

**Comment by bryevdv** [comment]
Not offhand, it would be nice to measure. Roughly when the cost of JSON encoding exceeds the cost of base64 encoding. Though I would add a corollary that if you have non-finite values in your data it's probably always better to use real arrays, just so the nans are shipped as nans

**Comment by mrocklin** [comment]
Oh, that's interesting.  NumPy arrays avoid the JSON serialization costs?

**Comment by bryevdv** [comment]
> NumPy arrays avoid the JSON serialization costs?

Well, let me be precise. NumPy arrays are encoded using base64 and the resulting string is serialized in a JSON message. This turns out to scale *much* better, especially for > 1d arrays (JSON serialization of nested arrays is horrendously slow). This also allows non-finite values to be sent faithfully ("fake" handling them in lists can also be quite slow)

However , since the very lo level WS message protocol does allow for multi-part messages, there is still a possibility for true zero-copy sending of binary buffers (e.g. a numpy memory buffer) directly into a WS and then directly into a JS typed array. This is future work, though: https://github.com/bokeh/bokeh/issues/5984

**Pull request merged**
