### PR TITLE
Stream as ndarray if any of old or new is an ndarray

### LINKED ISSUE #7523: Out of range float values are not JSON compliant with numpy arrays
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh 0.12.14

#### Description of expected behavior and the observed behavior

I get an error on both the client and server like the following:

    ERROR:bokeh.server.protocol_handler:error handling message Message 'PULL-DOC-REQ' (revision 1): ValueError('Out of range float values are not JSON compliant',)

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.server.server import Server
from bokeh.plotting import figure, ColumnDataSource
import numpy as np

def handle_doc(doc):
    source = ColumnDataSource({'x': [], 'y': []})
    fig = figure()
    fig.line(x='x', y='y', source=source, line_width=1)

    data = {'x': np.array([  1.,   0.,  np.nan,   1.,   0.,  np.nan,
                             1.,   0.,  np.nan,   1.,   0.,  np.nan,
                             1.,   0.,  np.nan]),
            'y': np.array([  2.,   1.,  np.nan,   2.,   3.,  np.nan,
                             2.,   2.,  np.nan,   2.,   0.,  np.nan,
                             2.,   4.,  np.nan])}
    doc.add_root(fig)
    source.stream(data)
    # source.data.update(data)  # this works fine


apps = {'/': handle_doc}

server = Server(apps, port=5000)
server.start()

import tornado.ioloop
tornado.ioloop.IOLoop.current().start()
```

#### Stack traceback and/or browser JavaScript console output

```
[bokeh] setting log level to: 'info'
connection.js:194 [bokeh] Websocket connection 0 is now open
connection.js:188 Error: Error reply ValueError('Out of range float values are not JSON compliant',)
    at connection.js:131
    at es6-promise.js:281
    at f (es6-promise.js:290)
    at p (es6-promise.js:268)
    at MutationObserver.r (es6-promise.js:102)
(anonymous) @ connection.js:188
connection.js:189 [bokeh] Failed to repull session Error: Error reply ValueError('Out of range float values are not JSON compliant',)
(anonymous) @ connection.js:189
connection.js:221 [bokeh] Lost websocket 0 connection, 1006 ()
connection.js:105 [bokeh] Websocket connection 0 disconnected, will not attempt to reconnect
```

### PR DESCRIPTION
**Pull request by mattpap**
fixes #7523

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap there are tests for `_stream` here:

https://github.com/bokeh/bokeh/blob/master/bokeh/core/property/tests/test_containers.py

They are not great, alot of mocks, but adding with an array streaming to a list would ensure that this case does not fall over in the future.

**Comment by mattpap** [comment]
I wanted to add a test for this, but I couldn't wrap my head around what is going on in `test_containers` and backed out.

**Comment by bryevdv** [comment]
OK I will push on in a little while

**Comment by bryevdv** [comment]
sorry for the force push, my pre-commit hook caught a lint error then I thoughtlessly did a `commit --amend` after fixing it

**Pull request merged**
