### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### bokeh/bokeh now has a Chat Room on Gitter

@havocp has just created a chat room. You can visit it here: [https://gitter.im/bokeh/bokeh](https://gitter.im/bokeh/bokeh?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/bokeh/bokeh?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by havocp** [comment]
wow, that was an unexpected auto-PR that I didn't know would happen...

**Comment by bryevdv** [comment]
We do already have an experimental slack room up and running, but have not really committed to it. @bokeh/dev do folks have strong opinions slack vs gitter?

**Comment by damianavila** [comment]
I did not tried slack yet... so I can not make a comparison... but gitter is popular among open source projects, so if you open that channel, we will sure have a lot of people pinging us... not sure if we have the man power to deal with real time support....

**Comment by mistakevin** [comment]
I've used neither, but [here](http://blog.freecodecamp.com/2015/06/so-yeah-we-tried-slack-and-we-deeply-regretted-it.html?m=1)'s an interesting post I read the other day on that subject. (tl;dr: pro-gitter for large or open source teams)

**Comment by havocp** [comment]
I was thinking if we had a channel it could be for development discussion only (support requests are better directed to google-able forums)

**Comment by havocp** [comment]
I was thinking if we had a channel it could be for development discussion only (support requests are better directed to google-able forums)

**Comment by bryevdv** [comment]
Interesting, I was actually hoping that slack/gitter could (eventually) be a place for users to self-support. We definitely don't have the resources to put into real-time support, although there is the possibility that we could hire a "community liaison" that could help with this some. In any case, I think they both platforms support multiple channels tho, so maybe both support and dev chat.

My only concern with gitter: doesn't it require having a GH login? Slack can be open to anyone.

**Comment by mistakevin** [comment]
CircleCI used to have a public HipChat room in the browser anyone could join to ask questions to the devs. It was awesome for quick one-off questions

**Comment by havocp** [comment]
for dev discussion I think the GH login is kind of a win - no account to create. For support, it doesn't make as much sense.

dev chat can be really helpful in attracting contributors. Starting a chat discussion isn't as intimidating as writing an email / issue / PR.

For what it's worth I didn't actually intend to unilaterally make the chat room I was more trying to join it if it existed ... but it has worked well on other projects I've been part of.

**Comment by damianavila** [comment]
I agree on a dev chat... and i would use gitter (the github filtering could help as @havocp said).
We used hipchat in IPython and it was a painful experience... now we are with gitter... and we have TOO much movement there... so we are thinking to restrict the rooms (we have several opened)... finally, no experience with slack as I said before...

**Pull request closed without merging**
