### PR TITLE
deprecate doc.add

### LINKED ISSUE #3103: Mark Document.add deprecated or remove TODO comment above it
https://github.com/bokeh/bokeh/blob/5fab252f8fde29228b5a9bfafb53ece6c8d5d145/bokeh/document.py#L196-L210

This is a back-compat wrapper for `add_root()` - if we want to deprecate it at least document that it is, otherwise remove that TODO comment above it.

### PR DESCRIPTION
**Pull request by fpliger**
Start deprecation path for `document.add`

isses: fixes #3103

### CODE REVIEW

**Comment by fpliger** [comment]
ok.. TravisCI is happy :)

**Comment by bryevdv** [comment]
Why is there unrelated junk in the diff?

**Comment by fpliger** [comment]
grrr.. I guess it's due to the local rebase thing.

**Comment by fpliger** [comment]
seems to be ok now

**Comment by damianavila** [comment]
LGTM, but let's wait for another yes before merging...

**Comment by mattpap** [comment]
> (...) if we also allow adding other things besides roots

Do we actually? If not, then writing `root` all the time is just redundant. Otherwise this PR is fine. Maybe `Document(*roots)` constructor could be added?

**Comment by bryevdv** [comment]
I'd be +1 for ` for `Document(*roots)` (here or in another PR). I personally prefer the explicitness of `add_root` over `add` regardless.

**Comment by damianavila** [comment]
> I'd be +1 forDocument(*roots) (here or in another PR). I personally prefer the explicitness of add_root over add regardless.

@fpliger, your thoughts?

**Comment by mattpap** [comment]
@damianavila, just to make sure, this doesn't have to happen in this PR.

**Comment by havocp** [comment]
Diff looks great - it could be nice to squash the wild commit history here and make a new branch with just one commit ... I can do that for you if you want? Anyway the end result looks good!

**Comment by fpliger** [comment]
>> I'd be +1 forDocument(*roots) (here or in another PR). I personally prefer the explicitness of add_root over add regardless.

> @fpliger, your thoughts?

I'm +1 on that too but would do it on a following PR. This PR is already luck to be clean and merging to master with all the recent merges

> Diff looks great - it could be nice to squash the wild commit history here and make a new branch with just one commit ... I can do that for you if you want? Anyway the end result looks good!

@havocp if you don't mind doing it I won't mind for sure (I'm cursed with anything related to rebase and other "making git commit history look good" cmds)  :)

**Comment by bryevdv** [comment]
superseded by #3212

**Pull request closed without merging**
