### PR TITLE
Hot fixes for examples

### PR DESCRIPTION
**Pull request by damianavila**
@bokeh/core just add any comment or contribution in this PR...

### CODE REVIEW

**Comment by mattpap** [comment]
@damianavila, why `glyphs/trail` was removed? I see the "Not working with hover", but that isn't a valid reason. Perhaps it fails in some configuration? There should have been at least an issue started to fix the actual problem.

**Comment by bryevdv** [comment]
I think I was misunderstood in a discussion. When asked about it, I had said hovertool was not working and should be removed. I meant the hover tool lines should be removed, not that the example should be removed. The example should be restored.

**Comment by damianavila** [comment]
@mattpap You are right... it was planned but with the release I forgot to open the issue, sorry about that.
It was just a temporal removal until get fixed. I will open the issue here (#1978) to track the problem down.

@bryevdv 
Yes, I misunderstood you... I think you want to remove the example until it get fixed and seems reasonable to me because it was not fully working...

**Comment by bryevdv** [comment]
This is an example with real data that is interesting and useful as a demonstration. We are in short supply of those. :) It was overzealous to add a hover tool since hover tool does not yet work with lines, but that just means (to me) that those two lines should be removed. Or in other words, I'd wouldn't want to deprive users of the benefit of this example just because something that is currently not expected to work, does not work. Even just adding a comment "Hovertool here is in anticipation of selection Line glyphs" would be a fine solution.

**Comment by damianavila** [comment]
>It was overzealous to add a hover tool since hover tool does not yet work with lines, but that just means (to me) that those two lines should be removed. 

I agree... or never introduced until it is working ;-)

>Even just adding a comment "Hovertool here is in anticipation of selection Line glyphs" would be a fine solution.

Nop... just do not add the hover until is working... it causes confusion...

**Pull request merged**
