### PR TITLE
Crossfilter example refactor

### PR DESCRIPTION
**Pull request by brendancol**
This is a first version of a cross filter example which uses bokeh server.

A couple key features are missing, but will come on subsequent PRs:
- drag/drop faceting
- filtering

To run example:
```bash
cd examples/app/crossfilter
bokeh serve .
```

Couple of known issues, which I'm not sure warrant delaying merge.  I think they should be follow up fix PRs:

- invalid attribute WARNINGs:

```
WARNING:bokeh.core.properties:JSON had attr 'parent' on obj <bokeh.models.axes.LinearAxis object at 0x106603438>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr 'parent' on obj <bokeh.models.grids.Grid object at 0x1066034a8>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr 'parent' on obj <bokeh.models.axes.LinearAxis object at 0x1066034e0>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr 'parent' on obj <bokeh.models.grids.Grid object at 0x106603550>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr 'parent' on obj <bokeh.models.renderers.GlyphRenderer object at 0x1066035f8>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr 'parent' on obj <bokeh.models.axes.LinearAxis object at 0x106603438>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr 'parent' on obj <bokeh.models.grids.Grid object at 0x1066034a8>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr 'parent' on obj <bokeh.models.axes.LinearAxis object at 0x1066034e0>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr 'parent' on obj <bokeh.models.grids.Grid object at 0x106603550>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr 'parent' on obj <bokeh.models.renderers.GlyphRenderer object at 0x1066035f8>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr 'escape' on obj <bokeh.models.widgets.inputs.Select object at 0x105ec8b38>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr 'escape' on obj <bokeh.models.widgets.inputs.Select object at 0x10660f588>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr 'escape' on obj <bokeh.models.widgets.inputs.Select object at 0x10660f0f0>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr 'escape' on obj <bokeh.models.widgets.inputs.Select object at 0x10660f9b0>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr 'escape' on obj <bokeh.models.widgets.inputs.Select object at 0x10660f198>, which is a client-only or invalid attribute that shouldn't have been sent
```

- intermittent socket error saying could not deserialize glyph circle.  I see it sometimes but am having trouble repeating.
```
Bokeh: Unhandled ERROR reply to 9E990DBCA40346D1B2B619BAE93EE642: DeserializationError("Instance(Glyph) failed to deserialize reference to {'id': '3cad9205-b258-42f3-b89d-3c71eee88de8', 'type': 'Circle'}",)
```

### CODE REVIEW

**Comment by bryevdv** [comment]
@brendancol can you outline what is left to merge this?

**Comment by brendancol** [comment]
hey added some known issues above, but I think they should be fixed in follow up PRs

**Comment by bryevdv** [comment]
@brendancol it seems to pretty reliably stop responding after a dozen or so dropdown changes

**Comment by brendancol** [comment]
Regarding the "stopped responding" issue, I started getting a some what of a silent error in my JS console after a recent merge with master.  After monitoring web socket traffic, I decided to try sending only x-values and y-values as arrays instead of creating my own ColumnDataSource. This seems to have cleared up the issue, but I don't have good reason why.

As a separate item, I now only load numeric fields into the x-axis and y-axis selector.
As a separate item, I fixed a bug with bar plot which occurred when x_field == y_field.

I believe the "stop responding" issue is fixed.

**Comment by bryevdv** [comment]
> As a separate item, I now only load numeric fields into the x-axis and y-axis selector. 

That seems like a drastic reduction in functionality. What is the issue?

**Pull request merged**
