### PR TITLE
add method to retrieve sorted columns on DataTable in js

### PR DESCRIPTION
**Pull request by jgriffi6**
This is a pull request to implement the feature request documented below.

- [x] issues: feature #8444 
- [ ] tests added / passed
Let me know if you want more.  Attaching compilation log, and a python script that tests the altered DataTable in js.
[build.log](https://github.com/bokeh/bokeh/files/2629793/build.log)

[test_sort_table.py.txt](https://github.com/bokeh/bokeh/files/2629797/test_sort_table.py.txt)

The above script will create a static page which if you then open you can test that we can indeed see which columns are sorted.  sort columns, then press the button. Note, the script will write files into the [bokeh]/tests directory.

Please let me know if the tests should be done differently.

- [ ] release document entry (if new feature or API change)
Adding a function 'get_sort_columns()' to the DataTable object

Thanks,
Justin

### CODE REVIEW

**Comment by bryevdv** [comment]
@jgriffi6 I was not as verbose in my description as I could have been, but what I was thinking of was this pattern:
```
get sort_columns(): any[] { return this._sort_columns }
```

And then the view would set the private `_sort_columns`. I like this because it has a true property getter (and only a getter) so there is no way to even try to set the value (will raise a compile error)

**Comment by bryevdv** [comment]
@jgriffi6 do you have thoughts on the idea above?

**Comment by jgriffi6** [comment]
@bryevdv 

Yeah I like the idea.  Having unrelated problems now simply setting up the bokehjs compiler.  Will update once I've figured out.

Justin

**Comment by jgriffi6** [comment]
@bryevdv 

I've attempted to follow your suggestion.  One thing I am not clear on: are we trying to make it so that the '_sort_columns' member is unsettable at compile time? Or also at runtime as well?  In my testing script, I create a page, and am able to manipulate the _sort_columns property in the console and w/i js callbacks.  However, I am unable to affect the property through the sort_columns getter.  

Is this desired behavior?

Thanks,
Justin

**Comment by bryevdv** [comment]
> are we trying to make it so that the '_sort_columns' member is unsettable at compile time? Or also at runtime as well? 

From my POV we are trying to give as clear an indication as possible that the value is not intended to be set. Hopefully the leading underscore makes it clear that it is not meant for users to interact with, and if they do try, well, we have done our due diligence.

**Comment by bryevdv** [comment]
Thanks @jgriffi6 !

**Pull request merged**
