### PR TITLE
Copy files if symlinking fails in 'pack' build task

### LINKED ISSUE #12926: bokehjs' build fails on Windows 10 due to creating symlinks
See https://github.com/bokeh/bokeh/pull/12635#issuecomment-1455164138 for reference.

### PR DESCRIPTION
**Pull request by mattpap**
@muendlein, can you verify this works?

fixes #12926

### CODE REVIEW

**Comment by muendlein** [comment]
@mattpap Works me 👍

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
Quite a few of the outreachy folks are stumbling over this, given @muendlein's favorable report, I will plan to go ahead and merge this in the next few hours unless I hear otherwise.

**Comment by mattpap** [comment]
Thanks @muendlein.

**Comment by mattpap** [comment]
@bryevdv, do you want this in 3.1?

**Comment by bryevdv** [comment]
@mattpap I don't think that is necessary

**Pull request merged**
