### PR TITLE
add test to check for reserved windows filename roots

### LINKED ISSUE #7283: Windows install fails 0.12.12
I'm getting an error installing bokeh 0.12.12. Previous versions install okay on my PC. I did a fresh install of Python 3.6.3 and deleted the pip cache directory first.

Windows 10 32-bit
Python 3.6.3 32-bit

Running pip install yields:

```
> pip install bokeh==0.12.12
Collecting bokeh==0.12.12
  Using cached bokeh-0.12.12.tar.gz
Exception:
Traceback (most recent call last):
  File "k:\users\ed\appdata\local\programs\python\python36-32\lib\tarfile.py", line 2268, in utime
    os.utime(targetpath, (tarinfo.mtime, tarinfo.mtime))
OSError: [WinError 87] The parameter is incorrect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "k:\users\ed\appdata\local\programs\python\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "k:\users\ed\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "k:\users\ed\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "k:\users\ed\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "k:\users\ed\appdata\local\programs\python\python36-32\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "k:\users\ed\appdata\local\programs\python\python36-32\lib\site-packages\pip\download.py", line 663, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "k:\users\ed\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 605, in unpack_file
    untar_file(filename, location)
  File "k:\users\ed\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 581, in untar_file
    tar.utime(member, path)
  File "k:\users\ed\appdata\local\programs\python\python36-32\lib\tarfile.py", line 2270, in utime
    raise ExtractError("could not change modification time")
tarfile.ExtractError: could not change modification time
```

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #7283
- [x] tests added / passed

### CODE REVIEW

**Comment by bryevdv** [comment]
Failing test before I renamed the file:
```
>       assert len(bad) == 0, "Windows reserved filenames detected:\n%s" % "\n".join(bad)
E       AssertionError: Windows reserved filenames detected:
E         bokeh/server/static/js/tree/core/aux.js
E         bokeh/server/static/js/tree_ts/core/aux.ts
E       assert 2 == 0
E        +  where 2 = len(['bokeh/server/static/js/tree/core/aux.js', 'bokeh/server/static/js/tree_ts/core/aux.ts'])

tests/test_windows_reserved_filenames.py:48: AssertionError
```

**Comment by bryevdv** [comment]
So this only checks under `bokeh`, since that is what gets packaged. Could expand to the entire repo, but  I don't think that's advised unless there are some other thoughts?

**Comment by bryevdv** [comment]
I changed my mind, decided to have this test check every file in the repo.

**Comment by mattpap** [comment]
> (...) decided to have this test check every file in the repo.

Unless `walk()` can resolve symlinks, previous implementation wouldn't work for me. However, things like `node_modules` may slow this down considerably. Maybe we should use `git ls-files` instead (as in code quality tests)?

**Comment by bryevdv** [comment]
> However, things like node_modules may slow this down considerably. 

It seems to run acceptably fast, and I run all quality checks as a pre-commit hook. Report looks good I will merge this and cut RC2

**Comment by jakirkham** [comment]
If you get concerned about speed, would take a look at [`scandir`]( https://github.com/benhoyt/scandir ). This is used by default in Python 3.5+'s `os.walk`, but can be used as a backport package on Python 2.7 if needed.

**Pull request merged**
