### PR TITLE
rebuild package-lock.json

### PR DESCRIPTION
**Pull request by bryevdv**
@mattpap I have been having issues building from a clean setup for while, with complaints that the `nan` package is missing. I would have to install it by hand to get things going. I decided to try rebuilding `package-lock.json`. Things work with the addition of `"esquery": "1.1.0"`and as a bonus this also resolves our `minimist` security alert since it picks up a new point release of `mkdirp`. Please review/comment (e.g. the deps order was changed, if there is some configuration that keeps things grouped how you prefer, let me know)

### CODE REVIEW

**Comment by mattpap** [comment]
Before jumping ship let's start from the basics:

- update npm with `npm install -g npm`
- remove `bokehjs/node_modules`
- clear npm cache with `npm cache clean --force`

and see if you still have issues.

**Comment by mattpap** [comment]
>  the deps order was changed, if there is some configuration that keeps things grouped how you prefer, let me know)

You have to update `package.json` manually. If you want to install package locally and not update any package files, use `--no-save`.

**Comment by mattpap** [comment]
> Things work with the addition of "esquery": "1.1.0"

Adding random packages is not a good idea. This needs to be figured out. Also, things build correctly in CI (in PR #9933, which builds bokehjs on all three platforms in bokehjs-ci workflow), so in general whatever the problem is, it needs to be figured out.

**Comment by mattpap** [comment]
> `+368 −2,425`

This was suspicious to me, but apparently a patch release of nunjucks resulted in this nice reduction (as confirmed in PR #9976).

**Comment by mattpap** [comment]
I went ahead and rebuilt `package-lock.json` and updated all dependencies in PR #9976, to make sure any such updates are independent of any platform specific issues. Let's continue work on top of that and resolve any remaining issues, keeping in mind that bokehjs' dependencies install in CI just fine. We need to figure out what differs. I suspect this is a case between `npm install` and `npm ci`.

**Comment by bryevdv** [comment]
superseded b y #9976

**Comment by bryevdv** [comment]
`npm ci` / `npm install` working again with changes (and cache clear for good measure)

**Pull request closed without merging**
