### PR TITLE
remove deprecations and update tests and code that used decprecated APIs

### LINKED ISSUE #1571: remove deprecated plotting API

### PR DESCRIPTION
**Pull request by bryevdv**
issues: closes #1571 

Note: should be merged just prior to 0.8 release.

### CODE REVIEW

**Comment by damianavila** [comment]
I agree on merging as soon as possible... but I would take at least 24 hs after the release to be sure we don't miss something and actually need a 0.7.2 release... better to give us chance :wink:

**Comment by damianavila** [comment]
Btw, I restarted TravisCI... seemed to hit a *heisen* run...

**Comment by damianavila** [comment]
@bryevdv this one is not merging clean... probably needs master in and solve some conflict...

**Comment by bryevdv** [comment]
@damianavila I have resolved the conflict

**Comment by damianavila** [comment]
OK, let's get merged then...

**Pull request merged**
