### PR TITLE
Task/1594 numba kernels

### LINKED ISSUE #1594: Additional kernels for numba examples
References: #1585

Would like to extend existing [numba interact example](https://github.com/bokeh/bokeh/blob/master/examples/plotting/notebook/numba_interact.ipynb) with additional image processing kernels that are user-selectable. 

@sklam @siebert, @pzwang would like this demo (among several others) ready for the DARPA meeting in January. Can you or someone on the Numba team assist with some additional jitted image-processing kernels?

### PR DESCRIPTION
**Pull request by bryevdv**
issues: closes #1594 

~~~**NOTE** this notebook currently suffers from the problem described in #1592 For now, only execute the cells in the "gaussian blur" section, or the "3x3 kernels", or the "wavelets"  section, but **not more than one** (i.e., do not "run all" cells)~~~

### CODE REVIEW

**Comment by bryevdv** [comment]
@pzwang this should probably be dressed up with some expository text, but please let me know if this is what you are looking for in terms of examples.

**Comment by damianavila** [comment]
I am getting an error on the 13th cell...

```python

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-13-26cefe4ca26c> in <module>()
      1 palette = ['#%02x%02x%02x' %(i,i,i) for i in range(256)]
      2 cm = LinearColorMapper(palette=palette, low=0, high=256)
----> 3 width, height = img_kernel.shape
      4 p_kernel = figure(x_range=(0, width), y_range=(0, height))
      5 p_kernel.image(image=[img_kernel], x=[0], y=[0], dw=[width], dh=[height], color_mapper=cm, name="kernel")

NameError: name 'img_kernel' is not defined
```

Because your Note is strike-through, I thought you can running from top to bottom... that's the case?

**Comment by damianavila** [comment]
> @damianavila copy pasta error, should be fixed

OK, anything else you want to add here? I mean some expository text as you said above... If not, I will merge it today...

**Comment by bryevdv** [comment]
Let's get a comment from @pzwang, so shoot to merge tomorrow.

**Comment by damianavila** [comment]
>Let's get a comment from @pzwang, so shoot to merge tomorrow.

OK

**Comment by damianavila** [comment]
@bryevdv this is not mergeable as is from the Github UI... can you merge master in to see if it solves the problem?

**Comment by bryevdv** [comment]
Weird, there were no conlicts reported I am not sure why it would not be mergeable but master is merged in now in any case.

**Comment by bryevdv** [comment]
I am going to push a bare minimum of repository text in the next 30 minutes, after that this can be merged.

**Comment by damianavila** [comment]
> Weird, there were no conlicts reported I am not sure why it would not be mergeable but master is merged in now in any case.

Yep... weird...

> I am going to push a bare minimum of repository text in the next 30 minutes, after that this can be merged.

OK, sounds good... I will merge it in a few hours...

**Comment by damianavila** [comment]
OK... looked at it again... it is ready, merging...

**Pull request merged**
