### PR TITLE
Fixed merge conflicts in previous pull request - use numbro.js

### PR DESCRIPTION
**Pull request by dennisobrien**
Fixed the merge conflicts in the previous pull request #3043 (based on pull request #3025 and issue #2922 ).  The conflicts were in bokeh/test_embed.py -- I had to add `encode_utf8` in places to make the assert equals work.

### CODE REVIEW

**Comment by bryevdv** [comment]
Hmm, I am not sure what's going on with the commit history. I have occasionally seen GH throw up way too many commits like this, but then it usually seems to fix itself. @mistakevin @damianavila any ideas here? It might just be easier to make a completely new PR on current master, theres not any more big changes like the server PR coming.

**Comment by damianavila** [comment]
>Hmm, I am not sure what's going on with the commit history. I have occasionally seen GH throw up way too many commits like this, but then it usually seems to fix itself. @mistakevin @damianavila any ideas here?

It is just incorporating changes by the tornado branch... this is probably because the starting point of this branch was before the tornado one...

> It might just be easier to make a completely new PR on current master, theres not any more big changes like the server PR coming.

Yes, probably the best way to deal with is supersede this one with a new PR base on fresh master...

**Comment by mistakevin** [comment]
I agree with @damianavila

**Comment by mistakevin** [comment]
The only relevent line from my PR is 
`"numbro": "git://github.com/bokeh/numbro.git#026294f"`
in your `package.json` `dependencies` section

**Comment by dennisobrien** [comment]
Hi @mistakevin 

I just started a new branch and applied the changes from PR #3043 but in testing this I found an error when formatting any numbers.  The JS error in the console:
```
Uncaught TypeError: c.format is not a function
```

I see the changes were made to dist/numbro.js
https://github.com/bokeh/numbro/blob/bokeh/dist/numbro.js
 but not the top level numbro.js
https://github.com/bokeh/numbro/blob/bokeh/numbro.js

My guess is that gulp is using the top level numbro.js and not dist/numbro.js.  And the version it is using doesn't have the `module.exports = {"format": format};` at the end.

What's the easiest course of action here:  copy dist/numbro.js to numbro.js in bokeh/numbro repo?

thanks,
Dennis

**Comment by mistakevin** [comment]
Hey @dennisobrien, I updated the top level `numbro.js` file with your changes and ran `grunt build` (without `test`) to bubble the changes down to the proper channels in `dist/`. You should now be able to use `"numbro": "git://github.com/bokeh/numbro.git#37dd9fe"`. Let me know if that works.

**Pull request closed without merging**
