### PR TITLE
Drop broken Dialog widget

### LINKED ISSUE #4652: Dialog broken
* Dialog - not sure how to use it even (how to get it to appear); adding buttons list doesn't seem to work; adding plot for content gives solver error.

### PR DESCRIPTION
**Pull request by mattpap**
Joining the "removing things" themed party.

fixes #4652

### CODE REVIEW

**Comment by bryevdv** [comment]
It's a popular party (and I a good one).

**Comment by bryevdv** [comment]
LGTM will merge when green

**Comment by bryevdv** [comment]
ping @fpliger just as an FYI for this removal, I know this was used in some work a long time ago.

**Comment by kongchujun** [comment]
So if I need a Dialog, what can I do ?

**Comment by bryevdv** [comment]
@kongchujun That depends on the specifics of your situation, and the appropriate place to discuss it is not here, but on the [project Discourse](https://discourse.bokeh.org/)

**Pull request merged**
