### PR TITLE
Refine coverage reports

### PR DESCRIPTION
**Pull request by birdsarah**
To run inside bokeh main directory:

$ py.test --cov=.

From top level (as is done in .travis.yml)

$ py.test --cov=bokeh --cov-config=bokeh/.coveragerc

### CODE REVIEW

**Comment by birdsarah** [comment]
Is this the correct set of things to omit? @bryevdv

**Comment by bryevdv** [comment]
Why omit `__init__.py` files? Some of them do actually do things. Mostly just imports, but when we start locking down APIs we will want to maintain the set of exposed symbols precisely.

**Comment by bryevdv** [comment]
We should omit `mplexporter` too, it is a vendored library.

**Comment by birdsarah** [comment]
Thanks for the feedback @bryevdv, also need to update this since the new testing work that @damianavila did.

**Comment by birdsarah** [comment]
This should also include an update to the testing docs.

**Comment by bryevdv** [comment]
@birdsarah does this just need a  merge from master or is there additional work?

**Comment by birdsarah** [comment]
this needs additional work - sorry forgot this one this week.

**Comment by bryevdv** [comment]
Should we also exclude `sampledata` ? I do think there should be tests for these somewhere, but I think downloading data falls in the integration test category.

**Comment by bryevdv** [comment]
Apart from that question, LGTM

**Comment by birdsarah** [comment]
> Should we also exclude sampledata ? I do think there should be tests for these somewhere, but I think downloading data falls in the integration test category. 

agreed

**Comment by bryevdv** [comment]
Restarted spuriously failed test. So this brings out coverage up to 71%, and there is still some code that can be deleted outright. e.g. `bokeh/transforms` and `server/task`. Maybe we can even get to 80% by the release.

**Pull request merged**
