### PR TITLE
Changing MultiChoice shouldSort default to false

### LINKED ISSUE #11638: [FEATURE]  MultiChoice widget sorts options by default
**Is your feature request related to a problem? Please describe.**
I use the MultiChoice widget to display a list of options that are grouped in specific ways. By default, MultiChoice sorts these options and this can't be changed. This makes it difficult for me to find similar items in the dropdown. 

**Describe the solution you'd like**
Either: set sort to false by default and users can choose whether they want to pass in a sorted list, or pass through the option to set sorted. I think the first option is best, and this is consistent with similar widgets like Dropdown (and is a one liner code change). 

**Describe alternatives you've considered**
The only real alternative is using a different style of widget, eg. a MultiSelect

**Additional context**
The example on the widgets page in the documentation shows this happening: https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html#multichoice

### PR DESCRIPTION
**Pull request by PinkusFloyd**
Issue discussed here: https://github.com/bokeh/bokeh/issues/11638

This allows the user to pass in the list in the order they want it to be displayed in the MultiChoice menu rather than having it automatically sorted.

- [ ] issues: fixes #11638
- [ ] tests added / passed

### CODE REVIEW

**Comment by PinkusFloyd** [comment]
@bryevdv I'm not really sure why these are failling, something to do with 
`const choices_view = view.child_views[0] as MultiChoice["__view_type__"]`
`(choices_view as any /*protected*/).choice_el.showDropdown()`
in both these previous issue tests I imagine. But I don't really know JS well enough to understand.

**Comment by mattpap** [comment]
Different order results in different images generated for dropdown menus. Baseline images need to be updated. See https://docs.bokeh.org/en/latest/docs/dev_guide/writing_tests.html, section "Generate CI baselines and commit test" (in short download the artifact from bokehjs-ci, unzip, commit changes, repush).

**Comment by tupui** [comment]
This still seems to be an issue. I can reproduce it with Bokeh 3.2.2

**Comment by bryevdv** [comment]
@tupui Please open a new issue with full new details.

**Comment by tupui** [comment]
Oh no seems to actually be working just fine in Bokeh and not in panel. Sorry for the noise, on a panel issue they were throwing the ball at Bokeh and I did not check.

**Pull request merged**
