### PR TITLE
9064 - static typing - bokeh.util.hex.py

### LINKED ISSUE #9064: Add static typing to bokeh
This is a meta issue for adding static typing to bokeh:

- [x] `bokeh.palettes`
- [ ] `bokeh.embed.standalone`
- [ ] `bokeh.util.string` @mborus

### PR DESCRIPTION
**Pull request by w0rdsm1th**
bokeh.util.hex.py: added mypy typing to function inputs and return values. A lot of "Any" due to no numpy type stubs

setup.cfg: reference the module for mypy testing

- [x] issues: addresses #9064
- [ ] tests added / passed
N/A - use mypy to test
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap where is documentation on how to push to these branches without making a whole clone of the external repo? Things I have tried have not worked (only have been able to push changes from the UI). I'm going to finish all these so that you can focus on the big PR.

**Comment by mattpap** [comment]
It works like this:
```sh
git fetch git@github.com:w0rdsm1th/bokeh.git w0rdsm1th/landing-2.0/9064_bokeh_util_hex_typing:w0rdsm1th/landing-2.0/9064_bokeh_util_hex_typing
git push git@github.com:w0rdsm1th/bokeh.git w0rdsm1th/landing-2.0/9064_bokeh_util_hex_typing
```

**Comment by bryevdv** [comment]
Ah, I for some reason I thought the upstream would get set. 👍

**Comment by mattpap** [comment]
This particular PR I already fixed locally.

**Comment by bryevdv** [comment]
@mattpap did you intend to suppress these for now? or actually install `numpy-stubs`? 

```
bokeh/util/hex.py: note: In function "hexbin":
bokeh/util/hex.py:157:1: error: Return type becomes "Any" due to an unfollowed import  [no-any-unimported]
    def hexbin(x: np.array[float], y: np.array[float], size: float,
```

**Comment by mattpap** [comment]
> or actually install numpy-stubs

Unfortunately there is no conda package for numpy-stubs. It's also not possible to use `np.array[float]` syntax at this point, only `np.array`.

**Comment by w0rdsm1th** [comment]
superseded by 9064

**Pull request closed without merging**
