### PR TITLE
TableDataSource: the filterable CDS

### LINKED ISSUE #4070: Plotting with subsets (row-wise) of ColumnDataSources (like filtered data)
Currently, Bokeh only allows glyphs to take full columns of data from a ColumnDataSource. This means that you must have additional ColumnDataSources for any plots that only use a subset of the data. This causes data to be replicated and makes linked selection more complicated for users, who would have to keep track of indices themselves. 

It would be nice if Bokeh allowed glyphs to take subsets of columns as data. An application using multiple plots, each showing some subset (e.g. filtered by the value of some column, like the example @dennisobrien showed at the SF meetup) of the data (or the full set), would then be able to completely share the data in the same way that Bokeh allows plots to share the full ColumnDataSource now. Linked selection would work intuitively with selected data points (rows) showing up in whichever plots contain that point. Holding shift before selecting on any plot would add to the selection. 

One possibility for an API would be to include another parameter that picks the subset of data for a renderer to use by the indices (which could default to all). 

``` python
data_source = ColumnDataSource(df)
fig = figure()
r = fig.circle(x = ‘x’, y = ‘y’, source=data_source, indices=[0, 1, 2]) 
r = fig.circle(x = ‘x’, y = ‘y’, source=data_source, indices=np.arange(n)[df.weather == “sunny”])
r = fig.circle(x = ‘x’, y = ‘y’, source=data_source, indices=[i for i, val in enumerate(df.weather) if val == “sunny”])
```

Another possibility could be to make the data source “filterable” in a pandas-like way. 

``` python
r = fig.circle(x = ‘x’, y = ‘y’, source=data_source[ data_source.weather == “sunny” ]) 
```

I tried to look through the issues and google group to find some related posts. 
https://github.com/bokeh/bokeh/issues/2323
https://github.com/bokeh/bokeh/issues/2710
https://groups.google.com/a/continuum.io/forum/#!searchin/bokeh/data$20source%7Csort:date/bokeh/_DIOQGlC6ds/EbZL0KRfBwAJ
https://groups.google.com/a/continuum.io/forum/#!searchin/bokeh/data$20source%7Csort:date/bokeh/79eSMaDV39I/OTfZqZHIug0J

Is this something that would be in Bokeh’s scope?

### PR DESCRIPTION
**Pull request by clairetang6**
This PR is still in its early stages, so feedback on the more basic design and API would be appreciated. 

The goal of this PR is to create a filterable CDS. I wrote about the current pain point and a potential solution in [this wiki working document page](https://github.com/bokeh/bokeh/wiki/Filterable-Data-Source). I just updated it to make it current and to reflect the API I implemented in this PR so far. 

The most important thing for this feature is to separate the data from the filters, so that data would not need to be duplicated. The approach that I took was to create a new DataSource, the TableDataSource, which has an instance of a CDS as a property to hold its data, instead of having a data property. Another approach could be to separate Data and DataSources for all types of DataSources (i.e. make ColumnData into its own model that just holds the data). Then this type of filtering behavior can be given to the CDS.

The TDS is basically a data source with a `cds` and `filter` property. The `cds` is a CDS. The `filter` was initially implemented (first commit) as a `Seq(Int)` and was the row indices to use for the subset. I then made it so that the `filter` could also be a `Seq(Bool)` and also allowed it to be a callable when a TableDataSource is created through its own constructor. I would need some guidance on how to make a new property type that is a callable that returns some other type. 

I implemented a basic `__getitem__` that has two cases. `tds['a']` returns its cds's data['a']. `tds[bool_list]` returns a new tds with a filter of `bool_list` (a list of bools for filtering rows). This allows for the API:

```python
fig.circle(x='x', y='y', source=tds[tds['x'] > 10])
``` 

Example of the result:

tds

```python
from bokeh.plotting import figure
from bokeh.layouts import row, column
from bokeh.models.sources import ColumnDataSource, TableDataSource
from bokeh.io import output_file, show

output_file("tds.html")

data = {'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'y': [10, 5, 2, 6, 1, 4, 8, 2, 7, 3]}

# create a TDS from dict, creating another TDS through the first links them.
tds1_1 = TableDataSource(data)
tds1_2 = tds1_1[tds1_1['y'] == 4]

# create a TDS from a CDS. All TDS's associated with the same CDS are linked.
cds = ColumnDataSource(data)
tds2_1 = TableDataSource(cds)
tds2_2 = TableDataSource(cds, filter=[0, 1, 9]) # filter = Seq(Int)
tds2_3 = TableDataSource(cds, filter=[True, False]*5) # filter = Seq(Bool)
tds2_4 = TableDataSource(cds, filter=(lambda tds: tds['y'] < 4)) # filter = (self) -> Either(Seq(Int), Seq(Bool))
tds2_5 = tds2_1[tds2_1['y'] < 8] # created through __getitem__

plot_size_and_tools = {'plot_height': 220, 'plot_width': 220,
                        'tools':['box_select', 'reset'],
                        'x_range':[0, 11], 'y_range':[0, 11]}

fig1 = figure(title="TDS 1_1, created with data", **plot_size_and_tools)
fig1.circle(x='x', y='y', source=tds1_1, color='black')

fig2 = figure(title="TDS 1_2, created by TDS 1_1", **plot_size_and_tools)
fig2.circle(x='x', y='y', source=tds1_2, color='black')

fig3 = figure(title="Full data set, CDS", **plot_size_and_tools)
fig3.circle(x='x', y='y', source=cds, color='green')

fig4 = figure(title="Full data set, TDS 2_1", **plot_size_and_tools)
fig4.circle(x='x', y='y', source=tds2_1, color='green')

fig5 = figure(title="TDS 2_2, filter=Seq(Int)", **plot_size_and_tools)
fig5.circle(x='x', y='y', source=tds2_2, color='green')

fig6 = figure(title="TDS 2_3, filter=Seq(Bool)", **plot_size_and_tools)
fig6.circle(x='x', y='y', source=tds2_3, color='green')

fig7 = figure(title="TDS 2_4, filter -> Seq(Bool)", **plot_size_and_tools)
fig7.circle(x='x', y='y', source=tds2_4, color='green')

fig8 = figure(title="TDS 2_5, created by TDS 2_1", **plot_size_and_tools)
fig8.circle(x='x', y='y', source=tds2_5, color='green')

show(column(row([fig1, fig2, fig3, fig4]), row(fig5, fig6, fig7, fig8)))
```

- [ ] issues: fixes #4070
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by clairetang6** [comment]
I am also keeping groupby behavior in mind. I think groupby is more similar to selection/nonselection in that you are still dealing with the full column, just broken into groups, versus plotting only a subset of data. One possibility would be to do something similar to selection/nonselection, where you create glyphs for each group (used for their visuals in rendering). Then in the render function of the glyph_renderer, you get the group indices from somewhere (maybe the tds) and render the different groups with those indices.

**Comment by bryevdv** [comment]
>  Another approach could be to separate Data and DataSources for all types of DataSources (i.e. make ColumnData into its own model that just holds the data). Then this type of filtering behavior can be given to the CDS.

I will say that this idea is one that I have had for a long time, but have never had the chance to act on. I had imagined splitting CDS into `ColumnStore` (or something), which actually has the data/columns, and the CDS that has references to columns in the store (but would otherwise be identical from user's perspective). 

I think it's worth considering this approach, but I recognize it might end up being more work than we decide we want to do at the moment.

**Comment by bryevdv** [comment]
by #5933

**Comment by YunfengHu** [comment]
I like the TableDataSource idea a lost and the example on wiki is great. I was trying to import TableDataSource, but I got the error ImportError: cannot import name 'TableDataSource'. Can @clairetang6 you show me how to install it?

**Pull request closed without merging**
