### PR TITLE
Upgrade to TypeScript 3.8

### PR DESCRIPTION
**Pull request by mattpap**
This will get finalized when 3.8-final is released, which should be tomorrow. Tentatively adding to 2.0 milestone. If TypeScript's release is delayed, then I will move it to `next`.

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap it looks like it was released:

https://devblogs.microsoft.com/typescript/announcing-typescript-3-8/

What do you want to do about this PR / milestone issue?

**Comment by mattpap** [comment]
eslint needs to be released with 3.8 support. It's unfortunate that they don't make such releases preemptively, given how accommodating TypeScript's release process is for such workflow.

**Comment by mattpap** [comment]
There is also one real test failure (repeated in multiple scenarios):
```
E               bokeh.util.compiler.CompilationError: 
E               bokeh/server/static/js/types/models/glyphs/webgl/base.d.ts:1:39 - error TS2307: Cannot find module 'gloo2'.
E               
E               1 import { Program, VertexBuffer } from "gloo2";
E                                                       ~~~~~~~

bokeh/util/compiler.py:489: CompilationError
```

**Comment by bryevdv** [comment]
OK I will move it out of the milestone then.

**Pull request merged**
