### PR TITLE
Bokeh server django consumer session id get param

### LINKED ISSUE #9814: [BUG] 'bokeh.server.django' ignores &bokeh-session-id url parameter
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh 2.0.0
django 3.0.4
channels 2.4.0
python 3.6.8

#### Description of expected behavior and the observed behavior

I was expecting `&bokeh-session-id=` GET param to work when embedding bokeh into django using the bokeh-provided `bokeh.server.django` django-app, but it ignores it. My project depends on this GET param in order to allow multiple browser windows connected to the same bokeh document (using [golden layout](https://github.com/golden-layout/golden-layout)) for user pop-in/out of dockable bokeh compenents. So I think if this is not considered as a [BUG] then maybe it should then be considered as a worthwhile [FEATURE].

#### Complete, minimal, self-contained example code that reproduces the issue

Simply run https://github.com/bokeh/bokeh/blob/master/examples/howto/server_embed/django_embed/ and experiment with `&bokeh-session-id=` in the URL.

#### Stack traceback and/or browser JavaScript console output

n/a

#### Screenshots or screencasts of the bug in action

n/a

### PR DESCRIPTION
**Pull request by chrisbarber**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [ ] issues: fixes #9814 
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

I believe this is the proper way to fix #9814. Open to feedback.

### CODE REVIEW

**Comment by bryevdv** [comment]
@philippjfr any thoughts on this? Seems fine and in line with what was left in the reference tornado Bokeh server after the token work.

**Comment by philippjfr** [comment]
Yeah seems fine.

**Comment by bryevdv** [comment]
Thanks @chrisbarber !

**Comment by bryevdv** [comment]
BTW @chrisbarber if you are interested to improve more and this and ensure that it is maintained through future releases, it would be good to make a follow-up PR to put things under test. I don't know a lot of the django server code actually, but happy to discuss

**Pull request merged**
