### PR TITLE
added render line to allow programatic change of tabs, fixes Issue #6502

### LINKED ISSUE #6502: Programmatically setting the active Tab does not change the tab in 0.12.6 & 0.12.7
When moving from Bokeh 0.12.5 to 0.12.6 on python 3.6, setting the active tab programmatically no longer changes the tab in the browser.  Clicking on the "Switch Tabs" button generated by the below code should cause the active tab to switch to Tab 2, but no longer does this under Bokeh 0.12.6. Maybe this is related to Issue #6501 ?

```python
from bokeh.layouts import column, widgetbox
from bokeh.models.widgets import Div, Tabs, Panel
from bokeh.plotting import curdoc
from bokeh.models import Button

label1 = Div(text='Tab 1')
label2 = Div(text='Tab 2')
panel1 = Panel(child=widgetbox(label1), title='Tab 1')
panel2 = Panel(child=widgetbox(label2), title='Tab 2')
tabs = Tabs(tabs=[panel1, panel2])


def callback():
    print('before', tabs.active)
    tabs.active = 1
    print('after', tabs.active)


button = Button(label="Switch Tabs")
button.on_click(callback)

curdoc().add_root(column(widgetbox(button), tabs))
```

### PR DESCRIPTION
**Pull request by Zyell**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes #6502
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by Zyell** [comment]
Fixes issue #6502

**Comment by bryevdv** [comment]
@Zyell Just to set expectiations, I'd like @mattpap to look at this, given his comment about wanting to understand why infinite event ping-pong was not happening. He will be gone for another ~10 days but we will get this evaluated when he returns.

**Comment by bryevdv** [comment]
@mattpap woudl you oppose merging this for `0.12.10` ?

**Comment by bryevdv** [comment]
ping @mattpap

**Comment by mattpap** [comment]
I have reservations about this change, but if it works then lets proceed. I will revisit tabs later on anyway, because it needs a proper implementation as a first-class layout.

**Comment by bryevdv** [comment]
Thanks @Zyell !

**Pull request merged**
