### PR TITLE
WebGL markers and rects reuse arrays and buffers

### PR DESCRIPTION
**Pull request by ianthomas23**
Improvements to performance of WebGL rect and marker glyphs by reusing rather than recreating `Float32Array`/`Uint8Array`s and ReGL `Buffer` objects. Similar to PR #11277 that applied to line glyphs; together the two PRs close the 5th item of issue #11052. No change in functionality or tests.

There is a new TypeScript file `webgl/buffer.ts` which brings functionality that was in `base.ts`, `regl_wrap.ts` and `webgl_utils.ts` together into a number of `WrapperBuffer` classes that wrap ReGL `Buffer` objects (which in turn wrap WebGL buffer objects) and is a more elegant solution.

To demonstrate the performance of WebGL vs canvas, I have used a similar approach to #11277 of rendering a set of `rect`s and using the chrome FPS counter whilst panning in small circular motions.  Test code is
```python
import numpy as np
np.random.seed(8417)
from bokeh.plotting import figure, curdoc, show

N = 10_000
backend = 'canvas'
#backend = 'webgl'

p = figure(width=800, height=800, output_backend=backend, title=backend, lod_threshold=None)
x = np.random.uniform(size=(N,))
y = np.random.uniform(size=(N,))
w = np.random.uniform(0.001, 0.003, size=(N,))
h = np.random.uniform(0.001, 0.003, size=(N,))
fc = np.random.randint(0, 0xffffffff, size=(N,), dtype=np.uint32)
lc = np.random.randint(0, 0xffffffff, size=(N,), dtype=np.uint32)
p.rect(x, y, width=w, height=h, fill_color=fc, line_color=lc)
show(p)
```
so each `rect` has a random width, height, line color and fill color.  On my dev laptop with integrated graphics the FPS results are:
screenshot

Other performance improvements are possible and I'll get to them in due course.

### CODE REVIEW

**Comment by bryevdv** [comment]
@ianthomas23 this LGTM as far as my expertise goes. Should this be labeled `ready`?

**Comment by ianthomas23** [comment]
@bryevdv Yes it is ready now that CI has passed.

**Comment by bryevdv** [comment]
@ianthomas23 I see there are some line-specific webgl tests in `integration/glyphs/line.ts` would it be appropriate now to add similar tests in a `rect.ts`?

**Comment by ianthomas23** [comment]
@bryevdv There is a rect test in `integration/glyphs/webgl.ts` that I added in a previous PR:
https://github.com/bokeh/bokeh/blob/e98b8b7907b7ad34fd39f0985a71cfcab811b8f0/bokehjs/test/integration/glyphs/webgl.ts#L45
It tests all 3 backends (canvas, svg and webgl) so I agree that it is in the wrong place and should be in `integration/glyphs/rect.ts` instead, particular as that is where you looked for it.  Do you want it added to this PR or in a new one?

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
> Do you want it added to this PR or in a new one?

I'm fine with a follow-up issue to organize webgl tests, but leave it to you. Either way, PR is approved, so please merge yourself immediately, or after moving the tests, if you decide to move the tests here.

**Comment by ianthomas23** [comment]
rect integration tests moved to new file `integration/glyphs/rect.ts`.

**Comment by bryevdv** [comment]
Thanks @ianthomas23 !

**Pull request merged**
