### PR TITLE
remove old ad-hoc callback properties

### PR DESCRIPTION
**Pull request by bryevdv**
This PR removes the `callback` property for almost all Bokeh models except for some tools.

cc @mattpap @philippjfr The only thing I am even  close to ambivalent about here is the `callback` for range. It's slightly more work to now either add individual start/end callbacks, or use a reset event. But they are workable, and I would rather make this clean slate and then find new conveniences that are more appropriate to the current codebase. 

@philippjfr please do check if you are using any of these on your end.

### CODE REVIEW

**Comment by mattpap** [comment]
> It's slightly more work to now either add individual start/end callbacks, or use a reset event.

One can always implement an API to listen to multiple properties, so let's consistently remove everything.

**Comment by bryevdv** [comment]
@mattpap @philippjfr Also just to summarize what keeps a `callback` attr:

* `OpenURL` and `CustomAction`. These actually seem fine. Their whole purpose is just to run a callback, it might as well be named.

* `HoverTool` We would need to add a "Hover` event of some kind before we can get rid of this. 

* `TapTool` Same here, the tap callback only executes on a hit, which is different than a SeletionGeometry event (which happens on every tap)

**Comment by bryevdv** [comment]
@mattpap any ideas?
```
    at Receiver.dataMessage (/home/runner/work/bokeh/bokeh/bokehjs/node_modules/ws/lib/receiver.js:422:14)
    at perMessageDeflate.decompress (/home/runner/work/bokeh/bokeh/bokehjs/node_modules/ws/lib/receiver.js:379:23)
    at _decompress (/home/runner/work/bokeh/bokeh/bokehjs/node_modules/ws/lib/permessage-deflate.js:298:9)
    at _inflate.flush (/home/runner/work/bokeh/bokeh/bokehjs/node_modules/ws/lib/permessage-deflate.js:376:7)
  request:
   { method: 'Page.captureScreenshot',
     params: { format: 'png', clip: [Object] } },
  response:
   { code: -32000,
     message: 'Cannot take screenshot with 0 height.' } }

FAILED
```

**Comment by bryevdv** [comment]
Well chrome reports this running locally:

> Did not parse stylesheet at 'https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.1.4/img/sprite-skin-flat.png' because non CSS MIME types are not allowed in strict mode.

**Comment by p-himik** [comment]
This PR doesn't have any issue attached to it and doesn't have any motivation behind such change.
Can you outline why this change was necessary?

The release notes say: "Instead, the more general `js_on_change` or `js_on_event` methods should be used."
I have a very concrete example where it wouldn't work: a box select tool that notifies other code on when the selection was made, along with the data range. `js_on_event` won't help me here because it can only be attached to a plot, not a tool. And listening to the `selected` ColumnDataSource property change is not useful as well because I can have multiple data sources.

What should people that have been relying on `callback` do now? Write custom tool models?

**Pull request merged**
