### PR TITLE
implement a scheme to be able to select active gesture tools programatically

### LINKED ISSUE #3054: Toolbar Improvements: Active is programmable
@brendancol just hit the example where he wanted to hide the toolbar (`toolbar_location=None`) but wanted zooming on.

We recently just turned zoomwheel (#3003) off by default, but the only way to turn it on is by clicking the toolbar icon.

We could add an argument to WheelZoomTool `active=True` for example, but it seems like we'd want something that worked across all tools and was consistent.

The challenge is that you should only have one tool active in a group at any one time. For WheelZoom this doesn't matter. It lives in the `scroll` group and there's only one tool in the `scroll` group, but for `pan` events in particular it's a problem.

I'm not entirely sure what a clean / obvious spelling is. We could have `active=True` on the invidivual models assuming that if you're using the Model interface you should know what you're doing and then have `figure` and `chart` have something like active_tools='list,of,tools' and it makes checks on it?

Worth noting that you can programmatically click the WheelZoomTool with if your toolbar is visible (but not if you've set `toolbar_location=None`)
````html
<script>
    Bokeh.$('.bk-button-bar-list[type="scroll"] button').click()
</script>
````

Update: if you have set `toolbar_location=None` you can reach into the guts of Bokeh to turn your WheelZoom on as follows:

````js
for (plot_index in Bokeh.index) {
 var plot_tools = Bokeh.index[plot_index].tools;
 for (tool_index in plot_tools) { 
   var tool = plot_tools[tool_index];
   if (tool.mget('tool_name') == 'Wheel Zoom') {
     tool.mset('active', true);
   }
 }
}
````

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #3054
- [x] tests added / passed
- [x] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
ping @pzwang Is this enough for now, or do we need to build out more convenience? With this initial commit, you can do:
```
import numpy as np

from bokeh.plotting import figure, show, output_file

N = 4000
x = np.random.random(size=N) * 100
y = np.random.random(size=N) * 100
radii = np.random.random(size=N) * 1.5
colors = [
    "#%02x%02x%02x" % (int(r), int(g), 150) for r, g in zip(50+2*x, 30+2*y)
]

TOOLS="resize,crosshair,pan,wheel_zoom,box_zoom,undo,redo,reset,tap,save,box_select,poly_select,lasso_select"

p = figure(tools=TOOLS)

p.scatter(x, y, radius=radii,
          fill_color=colors, fill_alpha=0.6,
          line_color=None)

from bokeh.models.tools import *
p.toolbar.active_drag = p.select(type=LassoSelectTool)[0]
p.toolbar.active_tap = None

output_file("color_scatter.html", title="color_scatter.py example")

show(p)  # open a browser
```
yielding
screen shot 2016-06-16 at 11 13 46 pm

**Comment by pzwang** [comment]
p.toolbar.active_drag = p.select(type=LassoSelectTool)[0]
    p.toolbar.active_tap = None

This all makes sense, but I can't help but notice the asymmetry in the initial tool specification list (strings) and the code it takes to activate a tool.

Maybe if `figure()` also accepted an `active_*` set of kwargs that could take strings?  I dunno...

**Comment by bryevdv** [comment]
@pzwang sure I had kwargs to `Figure` and `Chart` in mind too. I don't want the property to accept strings because then all that logic for deciding what to do with the strings has to move to BokehJS and I'd like to avoid that. I guess my main question is, if this is the correct low-level interface, and will not be expected to change, would that be enough for now, adding the convenience later.

**Comment by pzwang** [comment]
OK that makes sense.  In the docs, though, I would recommend showing creation of a tool instance, and then adding it to the plot, and setting it to active.  The `p.select()` approach should be shown as a separate/second approach for existing tools.

People tend to cut-and-paste, and syntax where we're grabbing `[0]` and stuff just seems kind of magical unless someone is familiar with the architecture of Bokeh.  So, a couple of extra lines of examples would be useful.

**Comment by bryevdv** [comment]
OK, this now works:
```
TOOLS="crosshair,pan,wheel_zoom,box_zoom,undo,redo,reset,tap,save,box_select,poly_select,lasso_select"

p = figure(tools=TOOLS, active_tap="pan")
```

**Comment by bryevdv** [comment]
re: test on `plotting.helpers` I want to clean up/refactor/add tests as part of the pre-1.0 work as one task

**Comment by bryevdv** [comment]
@bokeh/dev if anyone happens to have time for a quick review, it's appreciated. If not, I plan to merge soon.

**Comment by birdsarah** [comment]
I always get confused on this, but something seems off on the visual hierarchy of the docs

screen shot 2016-06-17 at 4 30 37 pm

**Comment by bryevdv** [comment]
Nice catch, I'll add a `Built-in Tools` header

**Comment by bryevdv** [comment]
screen shot 2016-06-17 at 6 37 02 pm

**Comment by birdsarah** [comment]
and remove the colon? :)

**Comment by birdsarah** [comment]
i'm actively testing btw

**Comment by bryevdv** [comment]
was just doing that

**Comment by birdsarah** [comment]
Testing went well. I'm fine with merging as is, its a great step in the right direction. Couple of things:

* You have only implemented on Toolbar and not on ToolbarBox (which is the multi-plot toolbar - actually MultiPlotToolbar is a much better name - hmpf). Any particular reason? It wonder whether you could just share the code via ToolbarBase?

* I tried to updated the active_scroll property programatically using server and failed - did you expect that to work? Probably not but just checking.

* No JS tests, but the Toolbars aren't well tested at all so I'm not going to give you a hard time about it :D.

**Comment by birdsarah** [comment]
I feel pretty sure you could share the code via ToolbarBase and have it available to both kinds of toolbar.

https://github.com/bokeh/bokeh/blob/4a74af2c9dbd996fec6d8857ae419d248f7ec543/bokehjs/src/coffee/models/tools/toolbar_box.coffee#L112-L113

Is exactly the same code you took out of `toolbar.coffee`. 

I can explain more about toolbar and toolbar_box if it's not clear.

**Comment by birdsarah** [comment]
The reason to do all this is that then gridplots (or custom multiplot layouts) will also be able to use this functionality.

**Comment by bryevdv** [comment]
I didn't do it because I didn't think it would work out of the box. If you think it is a simple thing to make it work in the grid case, we can try. 

AFAIK the primary use-case of this is as an initialization. I am not opposed to making it respond to changes but I'd rather make an issue and do it later.

**Comment by birdsarah** [comment]
> AFAIK the primary use-case of this is as an initialization. I am not opposed to making it respond to changes but I'd rather make an issue and do it later. 

Agreed

> I didn't do it because I didn't think it would work out of the box.

You're right. Tried quickly but failed because I forgot we make proxy tools when we merge all the tools together.

**Comment by birdsarah** [comment]
Added follow-on issues #4567 #4568.

LGTM.

**Comment by tommycarstensen** [comment]
When I do:
```
from bokeh.plotting import figure
from bokeh.models import WheelZoomTool
p = figure(tools=WheelZoomTool(), active_scroll='wheel_zoom')
```
then I get this `ValueError`:
```
  File "/Users/tc9/lib/python3.6/site-packages/bokeh/plotting/helpers.py", line 404, in _process_active_tools
    raise ValueError("Got unknown %r for 'active_scroll', which was not a string supplied in 'tools' argument" % active_scroll)
ValueError: Got unknown 'wheel_zoom' for 'active_scroll', which was not a string supplied in 'tools' argument
```

I'm using version 0.12.4. Is this a bug or am I using it incorrectly? Thanks.

Would you prefer, if I ask a question like this on the mailing list? Thanks.

**Comment by tommycarstensen** [comment]
Please ignore my comment. The reason I had to do it this way, was because I was also using `HoverTool`. I solved it this way:

```
from bokeh.plotting import figure
from bokeh.models import WheelZoomTool, HoverTool
hover = HoverTool(tooltips=[('y', '$y')])
wheel = WheelZoomTool(dimensions='width')
p = figure(tools=[hover, wheel], active_scroll=wheel)
```

**Comment by PrateekArya** [comment]
> OK, this now works:
> 
> ```
> TOOLS="crosshair,pan,wheel_zoom,box_zoom,undo,redo,reset,tap,save,box_select,poly_select,lasso_select"
> 
> p = figure(tools=TOOLS, active_tap="pan")
> ```

Hello!

I am using this approach to set `box_zoom` as active for a grid plot with multiple `figure`. It works, but there are 2 things which make me think that I am not using it the correct way:

1. I get the following warning:

`....py:208: UserWarning: found multiple competing values for 'toolbar.active_drag' property; using the latest value`

2. The box zoom icon in the tool box is not highlighted, but it is active!

Please let me know if I am doing something wrong here :)

**Pull request merged**
