### PR TITLE
Remove hash from elementid.

### PR DESCRIPTION
**Pull request by damianavila**
It was breaking the notebooks with sintax errors in the JS console about.

### CODE REVIEW

**Comment by damianavila** [comment]
@bokeh/core... and specially @birdsarah who, IIRC, make the last changes to embed.

**Comment by fpliger** [comment]
LGTM, fix is quite limited and fixes the problem locally for me

**Comment by Maggie-M** [comment]
LGTM, as well.

**Comment by birdsarah** [comment]
If you just do this. Other things will break I believe.

**Comment by birdsarah** [comment]
See https://github.com/bokeh/bokeh/pull/2636/files#diff-17c0ba2d2e03ea4330e6bcb9e60d4cb0L13 - we also need to update `bokeh/_templates/plot_js.js` I believe - I will look at this first thing in the morning.

**Comment by birdsarah** [comment]
@damianavila - sorry for all the noise. I was very tired yesterday and shouldn't have commented. I misunderstood the fix. This LGTM.

**Comment by damianavila** [comment]
OK, let's merge it!

**Pull request merged**
