### PR TITLE
Backports for 3.2.1

### PR DESCRIPTION
**Pull request by mattpap**
- [x] https://github.com/bokeh/bokeh/pull/13236
- [x] https://github.com/bokeh/bokeh/pull/13242
- [x] https://github.com/bokeh/bokeh/pull/13239
- [x] https://github.com/bokeh/bokeh/pull/13161
- [x] https://github.com/bokeh/bokeh/pull/13253
- [x] https://github.com/bokeh/bokeh/pull/13256
- [x] https://github.com/bokeh/bokeh/pull/13254
- [x] https://github.com/bokeh/bokeh/pull/13250
- [x] https://github.com/bokeh/bokeh/pull/13270
- [x] https://github.com/bokeh/bokeh/pull/13266
- [x] https://github.com/bokeh/bokeh/pull/13263
- [x] https://github.com/bokeh/bokeh/pull/13232
- [x] https://github.com/bokeh/bokeh/pull/13273
- [x] https://github.com/bokeh/bokeh/pull/13274

### CODE REVIEW

**Comment by bryevdv** [comment]
FY  #13242 is listed twice (looks like a pure duplicate rather than an accidental replacement of something else, based on the commits)

**Comment by mattpap** [comment]
It was a duplicate, due to me fighting with github's primitive UI.

**Comment by mattpap** [comment]
@bokeh/dev, this is ready. When approved, I will start 3.2.1 release build.

**Comment by ianthomas23** [comment]
It looks like this includes some of the regression tests added in #13195 but we don't have the new functionality of that PR so the tests fail. That PR is probably too significant to add in here, so maybe we should just remove the regression tests?

**Comment by bryevdv** [comment]
>  When approved, I will start 3.2.1 release build.

You'll want update `switcher.json` with the  new version first

**Comment by mattpap** [comment]
> You'll want update switcher.json with the new version first

OK. Shouldn't this be done automatically by the release build? Actually, I don't see it being updated in the preview backports PR (https://github.com/bokeh/bokeh/pull/13103).

**Comment by mattpap** [comment]
>  (...), so maybe we should just remove the regression tests?

Yes. That was a bad cherry-pick with conflicts.

**Comment by mattpap** [comment]
I see `switcher.json` was updated in a follow-up commit in 3.1.1. This also reminds me about release notes.

**Comment by bryevdv** [comment]
> Shouldn't this be done automatically by the release build?

It would be nice for this to be done automatically, yes.

> I don't see it being updated in the preview backports PR 

Sometimes it happens in a separate docs/release notes PR

**Review by ianthomas23 — APPROVED** [review]

**Pull request merged**
