### PR TITLE
Minor Fix: boxplot example indexing

### LINKED ISSUE #5061: Minor: box plot example indexing
I've been studying and adapting the box plot example a lot recently and, IMO, the calls to `df.loc` and `df.iloc` in `boxplot.py` are a little confusing and could be made more explicit/readable/transferable by removing the numeric indexing and replacing with the string name of the column being accessed. To explain, what I'm proposing is that:

```Python
# boxplot.py, lines 24-27
def outliers(group):
    cat = group.name
    return group[(group.score > upper.loc[cat][0]) | (group.score < lower.loc[cat][0])]['score']
out = groups.apply(outliers).dropna()
```
should become
```Python
# boxplot.py, lines 24-27
def outliers(group):
    cat = group.name
    return group[(group.score > upper.loc[cat]['score']) | (group.score < lower.loc[cat]['score'])]['score']
out = groups.apply(outliers).dropna()
```
, and
```Python
# boxplot.py, lines 45 & 46
upper.score = [min([x,y]) for (x,y) in zip(list(qmax.iloc[:,0]),upper.score) ]
lower.score = [max([x,y]) for (x,y) in zip(list(qmin.iloc[:,0]),lower.score) ]
```
should become
```Python
# boxplot.py, lines 45 & 46
upper.score = [min([x,y]) for (x,y) in zip(list(qmax.loc[:,'score']),upper.score)]
lower.score = [max([x,y]) for (x,y) in zip(list(qmin.loc[:,'score']),lower.score)]
```
(note removal of trailing space character from list comprehensions on lines 45 & 46.)

### PR DESCRIPTION
**Pull request by tobyhodges**
Fixes #5061

### CODE REVIEW

**Comment by bryevdv** [comment]
@tobyhodges This seems reasonable, can you post a screenshot of it working just for the record here?

**Comment by tobyhodges** [comment]
I've run it through v3.5 & v2.7, both with the same outcome. Plot from v3.5 attached below.
boxplot_screenshot

**Comment by canavandl** [comment]
LGTM (I built and ran the example locally). Merging as tests pass except for integration failures for external contributor.

**Comment by canavandl** [comment]
thanks for the PR @tobyhodges !

**Pull request merged**
