### PR TITLE
Revert "Some canvas and layout improvements"

### PR DESCRIPTION
**Pull request by birdsarah**
Reverts bokeh/bokeh#3913

This PR appears to have broken crossfilter. @bryevdv plans to add small bits back incrementally.

### CODE REVIEW

**Comment by mattpap** [comment]
Is this a non-trivial bug? This change interferes with my work greatly.

**Comment by bryevdv** [comment]
Let me try using this branch to identify the problem by working forward. Then maybe we can apply a simple fix to current master. @birdsarah hold off on merging

**Comment by birdsarah** [comment]
> Is this a non-trivial bug? This change interferes with my work greatly.

@mattpap, I believe it's something to do with the crossfilter.

**Comment by bryevdv** [comment]
It's completely not rendering whole-plot replacements, and I was not able to figure out a fix working backwards from master.

**Pull request closed without merging**
