### PR TITLE
WIP: Vbar hbar hittest

### LINKED ISSUE #4924: Tooltips unavailable for `vbar` and `hbar` glyphs
## Expected behavior and the observed behavior
Using the hover tools on `vbar` and (I assume) `hbar` glyphs currently does not work.

## Example
via http://stackoverflow.com/questions/38750508/using-the-hover-tool-with-vbar-glyphs
```python 
import numpy
import pandas
from bokeh import charts, plotting, models
plotting.output_notebook()

blue = 'STEELBLUE'
green = 'FORESTGREEN'

datalist = [
    {'month': 'Oct', 'rain': 131., 'snow':  0.0, 'wy_month': 1},
    {'month': 'Nov', 'rain': 12.4, 'snow':  0.0, 'wy_month': 2},
    {'month': 'Dec', 'rain': 43.0, 'snow': 13.5, 'wy_month': 3},
    {'month': 'Jan', 'rain': 63.0, 'snow':  9.2, 'wy_month': 4},
    {'month': 'Feb', 'rain': 72.6, 'snow': 35.3, 'wy_month': 5},
    {'month': 'Mar', 'rain': 13.5, 'snow':  4.2, 'wy_month': 6},
    {'month': 'Apr', 'rain': 107., 'snow':  1.5, 'wy_month': 7},
    {'month': 'May', 'rain': 77.0, 'snow':  0.0, 'wy_month': 8},
    {'month': 'Jun', 'rain': 107., 'snow':  0.0, 'wy_month': 9},
    {'month': 'Jul', 'rain': 216., 'snow':  0.0, 'wy_month': 10},
    {'month': 'Aug', 'rain': 76.8, 'snow':  0.0, 'wy_month': 11},
    {'month': 'Sep', 'rain': 76.4, 'snow':  0.0, 'wy_month': 12}
]

data = pandas.DataFrame(datalist).assign(total=lambda df: df['rain'] + df['snow'])
source = plotting.ColumnDataSource(data)

tooltips = [
    ("month", "@month"),
    ("rain", "@rain"),
    ("snow", "@snow"),
]

hover_bar = models.HoverTool(tooltips=tooltips)
TOOLS_bar = [hover_bar, models.ResizeTool(), models.ResetTool()]

fig = plotting.figure(width=600, height=300, y_range=(0, 250),
                      x_range=data['month'].tolist(),
                      tools=TOOLS_bar)
fig.vbar(x='wy_month', bottom=0, top='rain', width=0.5, color=blue, source=source)
fig.vbar(x='wy_month', bottom='rain', top='total', width=0.5, color=green, source=source)
plotting.show(fig)
```
## Console output
N/A -- this is known to not be implemented

## System info
```
λ bokeh info
Python version      :  3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
IPython version     :  5.0.0
Bokeh version       :  0.12.1
BokehJS static path :  C:\Users\phobson\Miniconda3\envs\tahoe\lib\site-packages\bokeh\server\static
```

## Desired behavior
I would like to implement the necessary `_hit_test` and `_index_data` methods to allow tooltips via a `HooverTool` on `vbar` and `hbar` glyphs.

### PR DESCRIPTION
**Pull request by phobson**
- [ ] issues: fixes #4924
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

This is a very rough draft and first pass. I'm still working on getting a good development environment setup.

### CODE REVIEW

**Comment by phobson** [comment]
Just a heads up and a proactive apology.

I fear I'm going to need a lot of hand-holding with this. I've never really worked with coffee/java script before and I'm still not clear on how to debug the coffee script code when I've made changes.

I've worked through all the setup here:
http://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html#devguide-building-bokehjs

But I'm still figuring out the nitty-gritty development workflow details of what to do after I've modified the coffeescript and how to debug it when I'm not satisfied with the results.

**Comment by bryevdv** [comment]
@phobson we are here to help. :) Some notes that might help: 

* to run scripts with your local built BokehJS, set then env var `BOKEH_RESOURCES=inline`
* you can put a `debugger` line anywhere in the coffeescript code
* if you do that, rebuild and run with the env var `BOKEH_MINIFIED=no`, then if you run the script with the browser dev tools open, it will drop you down into a debugger console (where you can look at variable values, single-step code, etc)

**Comment by bryevdv** [comment]
Assuming you have the bandwidth, I'd suggest: 
* get it working basically as it is, then
* factor out common code from `quad` / `vbar` / `hbar` as much as possible

**Comment by phobson** [comment]
@bryevdv 1 more warningand a question:
warning: I have no clue how to write a test for this kind of thing and i haven't yet found an example of such a test

question: at the moment I'm on Windows. Is development more easily done on my Mac or a Linux VM?

**Comment by bryevdv** [comment]
@phobson we can help with the tests when we get to the "factoring out" part, I think. I'm not really a windows user so I am not sure if it is appreciably more difficult. We definitely have some folks who do dev on windows. @almarklein can you offer any thoughts or advice?

**Comment by bryevdv** [comment]
Also ping @ericmjl just FYI!

**Comment by almarklein** [comment]
> Is development more easily done on my Mac or a Linux VM?

It shouldn't be :) Let me know if you run into problems.

A fresh bokehjs build is certainly recommended after a pull. Though when you make small changes yourself, I like `gulp watch` in combination with `BOKEH_RESOURCES=inline` so that you can make a change, save it, <gulp auto-builds>, hit F5 in your browser.

Tests for bokehjs are [here](https://github.com/bokeh/bokeh/tree/master/bokehjs/test).

**Comment by bryevdv** [comment]
@phobson just checking in, do you expect to be able to work on this again? If not we can close this but cherry-pick your commits into another PR (with an author tag) for @birdsarah to pick up from.

**Comment by phobson** [comment]
Sorry for the radio silence @bryevdv adn @birdsarah . 

The paying gig is just nuts right now and I won't be able to look at this again for at least 2 more weeks. 

If the existing commits are useful, I'd be happy to have my name in the commit log of such an awesome project. But don't feel shy about scrapping them if they're not useful.

**Comment by bryevdv** [comment]
@phobson no apologies needed, understand completely. I'll go ahead and close this PR for now, will come back an mark it superseded once a new PR is available to build off of it. Thanks for getting this started and pushing on the feature request!

**Comment by bryevdv** [comment]
superseded by #5034

**Pull request closed without merging**
