### PR TITLE
Fix box select for reversed ranges

### LINKED ISSUE #3996: Box Select tool doesn't work when x or y range is reversed
Example below. Box select only works in the top-left plot, where both the x and y ranges are in the "normal" direction. Lasso select works on all of the plots though. 

```python 
from bokeh.plotting import Figure, output_file, show
from bokeh.models.sources import ColumnDataSource
from bokeh.io import gridplot

output_file('test_box_select.html')

data = ColumnDataSource({'x': [1, 2, 3, 4], 'y': [10, 5, 2, 6]})
plot_size_and_tools = {'plot_height': 200, 'plot_width': 200, 'tools':['lasso_select', 'box_select', 'reset']}

fig1 = Figure(x_range=[0, 5], y_range=[1, 11], x_axis_label="normal", y_axis_label="normal", **plot_size_and_tools)
fig1.circle(x='x', y='y', source=data)

fig2 = Figure(x_range=[0, 5], y_range=[11, 1], x_axis_label="normal", y_axis_label="reverse", **plot_size_and_tools)
fig2.circle(x='x', y='y', source=data)

fig3 = Figure(x_range=[5, 0], y_range=[1, 11], x_axis_label="reverse", y_axis_label="normal", **plot_size_and_tools)
fig3.circle(x='x', y='y', source=data)

fig4 = Figure(x_range=[5, 0], y_range=[11, 1], x_axis_label="reverse", y_axis_label="reverse", **plot_size_and_tools)
fig4.circle(x='x', y='y', source=data)

show(gridplot([[fig1, fig2], [fig3, fig4]]))
```

### PR DESCRIPTION
**Pull request by clairetang6**
This PR fixes the bug where the box select tool doesn't work if any of the ranges are reversed. 

I added a function ```validate_bbox_coords([x0, x1], [y0, y1])``` to the hittest module, which takes x and y coords and returns the correct bounding box coordinates for [rbush](https://github.com/mourner/rbush), making sure it's ```[minX, minY, maxX, maxY]```.

I also added some tests for the selection manager. The last test, ```it "should work when mappers are reversed"```, fails before the fix.  

- [x] issues: fixes #3996 
- [x] tests added / passed

~~- [ ] release document entry (if new feature or API change)~~

### CODE REVIEW

**Comment by bryevdv** [comment]
Awesome! I restarted what appear to be spurious tests failures

**Comment by bryevdv** [comment]
@clairetang6 it looks like there are a few other places the new function could be applied:
```
bryan@0199-bryanv (git:master) ~/work/bokeh/bokehjs/src/coffee $ grin index.search
./models/glyphs/annular_wedge.coffee:
   77 :     for i in (pt[4].i for pt in @index.search([x0, y0, x1, y1]))
./models/glyphs/annulus.coffee:
   72 :     for i in (pt[4].i for pt in @index.search([x0, y0, x1, y1]))
./models/glyphs/circle.coffee:
   61 :     return (x[4].i for x in @index.search([x0, y0, x1, y1]))
  104 :     candidates = (pt[4].i for pt in @index.search([x0, y0, x1, y1]))
  166 :       hits = (xx[4].i for xx in @index.search([x0, y0, x1, y1]))
  175 :     result['1d'].indices = (x[4].i for x in @index.search([x0, y0, x1, y1]))
./models/glyphs/patches.coffee:
   72 :     return (x[4].i for x in @index.search([x0, y0, x1, y1]))
  128 :     candidates = (x[4].i for x in @index.search([x, y, x, y]))
./models/glyphs/quad.coffee:
   38 :     hits = (x[4].i for x in @index.search([x, y, x, y]))
./models/glyphs/rect.coffee:
   82 :     result['1d'].indices = (x[4].i for x in @index.search([x0, y0, x1, y1]))
  109 :     for i in (pt[4].i for pt in @index.search([x0, y0, x1, y1]))
./models/glyphs/wedge.coffee:
   61 :     for i in (pt[4].i for pt in @index.search([x0, y0, x1, y1]))
./models/markers/marker.coffee:
   45 :     return (x[4].i for x in @index.search([x0, y0, x1, y1]))
   60 :     candidates = (x[4].i for x in @index.search([x0, y0, x1, y1]))
   80 :     result['1d'].indices = (x[4].i for x in @index.search([x0, y0, x1, y1]))
```

**Comment by clairetang6** [comment]
Hi @bryevdv, I added the validation calls to all of the `index.search`'s. Originally I left them out because some of those calls were after code where there was something like:

```python
    vx0 = vx - @max_size
    vx1 = vx + @max_size
    [x0, x1] = @renderer.xmapper.v_map_from_target([vx0, vx1], true)

    vy0 = vy - @max_size
    vy1 = vy + @max_size
    [y0, y1] = @renderer.ymapper.v_map_from_target([vy0, vy1], true)
```

where it seems to be guaranteed that x0 < x1 and y0 < y1, but I think it is nice to have the validation explicit. It's only two additional if statements to execute and could potentially prevent other bugs.

**Comment by bryevdv** [comment]
@clairetang6 thanks again for another great PR!

**Pull request merged**
