### PR TITLE
functioning but poorly styled datepicker

### PR DESCRIPTION
**Pull request by bryevdv**
partially addresses #4204 

This PR provides a functioning (but unstyled) date picker. It is attached to an `<input>` and the input shows the currently selected date. If someone else can get the styling working, great. Otherwise at least it functions correctly. 

Note: I removed the code from the "render" method because it seems to be getting called alot, unnecessarily, and there is no reason to recreate the objects every time (also doing so cleared the input so that the date did not show)

### CODE REVIEW

**Comment by bryevdv** [comment]
My hunch is that to get the styling working we would have to fork/vendor jquery-ui. AFAICT there is no control over the css classes used on the DOM items created internally by the date picker function.

**Comment by jbrambleDC** [comment]
This looks good to me. Just for clarification does the styling issue itself boil down to jquery-ui itself? forking could be a bit drastic, no? I see the jquery-ui project itself does not support github issues it seems. 

However I did notice this PR open related to DatePicker: https://github.com/jquery/jquery-ui/pull/1698

seems the purpose of this PR is to add change events and callbacks to the datepicker class, so may in all likelihood be related.

**Comment by bryevdv** [comment]
@jbrambleDC I think it has to do with our CSS prefixing. 

@mattpap @birdsarah @mistakevin is everything is always under a `bk-root` element now, could that provide an avenue to stop prefixing altogether?

**Comment by mistakevin** [comment]
Everything I've used seems to be namespaced under `.bk-root` in the latest dev build. I have not used every widget though, and there was an issue with the "save" modal which has been taken care of with an inline download option (which is great)

**Pull request merged**
