### PR TITLE
Replace deprecated jinja2.Markup with jinja2.tojson

### LINKED ISSUE #11175: Replace jinja2.Markup deprecated with Jinja 3.1
As [pointed out in the source](https://github.com/pallets/jinja/blob/d77a91b1cba05d9dc78d4b03d312fcff3ca91ebb/src/jinja2/utils.py#L835-L843) `jinja2.Markup` will be deprecated with Jinja 3.1. Switching to `markupsafe.Markup` is recommended.

Refs: https://github.com/bokeh/bokeh/pull/11174

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh 2.3.1
<!--### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh 2.3.1
#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

```

### PR DESCRIPTION
**Pull request by kernc**
Avoid deprecated `jinja2.Markup` and use `markupsafe.Markup` instead.
https://github.com/pallets/jinja/blob/d77a91b1cba05d9dc78d4b03d312fcff3ca91ebb/src/jinja2/utils.py#L835-L843
This introduces a new direct dependency, but it _is_ the designated replacement.

Found this while looking why [my `--pre` cron CI run fails](https://github.com/kernc/backtesting.py/runs/2369549640?check_suite_focus=true#step:11:238) all of a sudden. It obviously can't be this, but maybe you know better — ideas appreciated. :pray: 

<!--All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes #11175
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@kernc I'm not sure why your CI runs were failing (have not had a chance to investigate yet) but I do not think this is related or necessary. Jinja itself already uses markupsafe itself, internally:

https://jinja.palletsprojects.com/en/2.11.x/intro/#markupsafe-dependency

**Comment by bryevdv** [comment]
I also can't find anything about `jinja2.Markup` being deprecated: 

https://jinja.palletsprojects.com/en/2.11.x/api/#jinja2.Markup

If you would like assistance investigating your CI issues with Bokeh, please open a topic on the community Discourse:

https://discourse.bokeh.org/

**Comment by bryevdv** [comment]
Well, guess there is nothing in the docs about it being deprecated because it is not deprecated in any official release yet (but will be, in Jinja 3.0) So we will need to do this at some point, but I would rather take things together and bump the Jinja version to >=3 at the same time. @kernc can you open an issue about that, so we can keep track of it in the near future? In the mean time we might want to set <3 for jinja in our requirements

cc @bokeh/dev

**Comment by bryevdv** [comment]
@kernc Can you rebase this against `branch-2.3` ?

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
cc @mattpap before this is merged. I don't recall what the custom `json` filter is used for, if there are any options to avoid adding another dependency I am interested to hear them.

**Comment by bryevdv** [comment]
Just noting that the filter was added in https://github.com/bokeh/bokeh/pull/5603

I will confess is is used in places that don't immediately make sense to me:
```
./core/_templates/autoload_js.js:
   23 :   const force = {{ force|default(False)|json }};
   35 :     const element = document.getElementById({{ elementid|json }});
  113 :   const js_urls = {{ bundle.js_urls|json }};
  114 :   const css_urls = {{ bundle.css_urls|json }};
  116 :   const js_urls = {{ js_urls|json }};
  117 :   const css_urls = {{ css_urls|json }};
  123 :       inject_raw_css({{ css|json }});
./core/_templates/autoload_nb_js.js:
  135 :     root._bokeh_timeout = Date.now() + {{ timeout|default(0)|json }};
  156 :     const el = document.getElementById({{ elementid|json }});
  184 :       const cell = $(document.getElementById({{ elementid|json }})).parents('.cell').data().cell;
```
which makes me wonder if our `json` filter and `tojson` in fact do the same thing (and secondarily, perhaps our `json` filter needs a better descriptive name?)

**Comment by bryevdv** [comment]
@kernc Thank you for the correction. Assuming this works I think we could just remove our custom `json` filter and use `tojson` directly throughout. But I'm still not yet sure they are equivalent.

**Comment by mattpap** [comment]
> I will confess is is used in places that don't immediately make sense to me:

This `json` filter is there to convert python values to valid javascript literals without resorting to gross hacks (as it was done previously). This could have been called `tojs` as well.

**Comment by bryevdv** [comment]
> This json filter is there to convert python values to valid javascript literals without resorting to gross hacks (as it was done previously). This could have been called tojs as well.

OK, I think then I would be in favor of just adding the `markupsafe` dependency and keeping our custom filter, but renaming it to `tojs`.

@kernc I realize there's been a fair amount of back and forth. If you are interested in making the change I just described that would be great, but if not, no worries just let us know (We will close this PR and update the issue with this plan accordingly)

**Comment by bryevdv** [comment]
@mattpap it looks like the built in `safe` filter just calls `Markup` 

https://github.com/pallets/jinja/blob/b98182fc376548493ee0c1d70d3f962356cfeada/src/jinja2/filters.py#L1315-L1319

So perhaps we could make a `dumps` filter that does the `obj.dumps` and then chain that with` |safe` ? That would avoid needing to add a dependency.

**Comment by mattpap** [comment]
> (...) and then chain that with |safe

The idea was that it would be all in one, but given that those templates change rarely, then I suppose it's a fine change.

**Comment by kernc** [comment]
So what's the verdict here? Why not just bump and use `|tojson`? Why wouldn't the tests pass?

**Comment by bryevdv** [comment]
> So what's the verdict here? Why not just bump and use |tojson? Why wouldn't the tests pass?

@kernc I guess it's just not clear to me that it does exactly the same thing. But I could easily be wrong. I will have to actually check out the PR branch and run some things locally to convince myself that things are working. I can do that in the next few days. However, if it turns out that things *are* interchangeable, then I would want to remove this:
```
_env.filters["json"] = _env.filters["tojson"]
```
as unnecessary, and just use `tojson` directly in all the templates directly.

**Comment by bryevdv** [comment]
@mattpap I am inclined to merge this. I tested apps, all the embeds, various notebooks with both minified and unminified as well as inline resources and everything seems to be all in order. 

@kernc you will just need to update the one test that is failing due to our checksum on the autoload template:
```
______________________ test_autoload_template_has_changed ______________________

    def test_autoload_template_has_changed() -> None:
        """This is not really a test but a reminder that if you change the
        autoload_nb_js.js template then you should make sure that insertion of
        plots into notebooks is working as expected. In particular, this test was
        created as part of https://github.com/bokeh/bokeh/issues/7125.
        """
        with open(join(TOP_PATH, "_templates/autoload_nb_js.js"), mode="rb") as f:
            current_template_sha256 = compute_sha256(_crlf_cr_2_lf_bin(f.read()))
>           assert pinned_template_sha256 == current_template_sha256, """\
                It seems that the template autoload_nb_js.js has changed.
                If this is voluntary and that proper testing of plots insertion
                in notebooks has been completed successfully, update this test
                with the new file SHA256 signature."""
E           AssertionError:             It seems that the template autoload_nb_js.js has changed.
E                         If this is voluntary and that proper testing of plots insertion
E                         in notebooks has been completed successfully, update this test
E                         with the new file SHA256 signature.
E           assert '7ef90f10663a...df916787a8554' == '5e9585eaa2b4...164d2e4d73305'
E             - 5e9585eaa2b4cb01e7733e611c4fd6b5f68cbbd56152ddc778f164d2e4d73305
E             + 7ef90f10663ac0168363c95050a718ad5a0caa27a69145b2b4cdf916787a8554

```

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
Thanks @kernc !

**Comment by bryevdv** [comment]
Just noting that this is not trivial to forward port, I may do it manually in a fresh PR.

**Pull request merged**
