### PR TITLE
Add OpenGraph metadata to docs

### PR DESCRIPTION
**Pull request by tcmetzger**
As part of Google's Season of Docs, this pull request will add [OpenGraph metadata](https://ogp.me/) to Bokeh's docs. OpenGraph metadata is used by services like Facebook, Twitter, LinkedIn or Discourse to generate rich previews of links.

### CODE REVIEW

**Comment by tcmetzger** [comment]
@bryevdv as discussed, it would be great if you could make the html generated by this branch available with some sort of testing URL. I plan to using this URL to do some very first testing and experimenting.

**Comment by bryevdv** [comment]
@tcmetzger I get this error trying to build 
```
~/work/bokeh/sphinx timo/opengraph-metadata
(dev) ❯ BOKEH_DOCS_CDN=2.1.1 BOKEH_DOCS_VERSION="test" GOOGLE_API_KEY="junk" make clean html serve
rm -rf build/*
rm -rf source/docs/gallery/*
sphinx-build -b html -d build/doctrees  source -W build/html
Running Sphinx v3.1.1
making output directory... done
creating gallery file entries... [100%] logaxis.rst

Warning, treated as error:
The config value `ogp_image_alt' has type `str', defaults to `bool'.
make: *** [html] Error 2
```

**Comment by tcmetzger** [comment]
This is actually "just" a warning, and a bit of a bug in the extension (I'll try to fix this with a pull request there) - the docs should build normally if you ignore this warning.

**Comment by bryevdv** [comment]
> the docs should build normally if you ignore this warning.

How are you doing this? We have the docs config set to strict -- no warnings allowed

**Comment by tcmetzger** [comment]
I see - I'll push a new commit that should run without this warning/error.

**Comment by bryevdv** [comment]
Great, for now I just ran `sphinx-build` manually with different options. Results deployed here:

http://docs.bokeh.org/en/test/

**Comment by bryevdv** [comment]
@tcmetzger is adding the image alt tag back when upstream is fixed the only thing left to do? (The content looked pretty good in an online tester site)

**Comment by tcmetzger** [comment]
@bryevdv I'd like to add some more specific tags (for twitter, for example) over the next few days. And optimize the size of the og:image! 😀

**Comment by tcmetzger** [comment]
Just added some Twitter-specific metadata. Also, there really seems to be no definitve information on the dimensions for og:image ([good overview here](https://iamturns.com/open-graph-image-size/)). I have reduced the size a little bit to 1200 x 630 (1.9:1 ratio):
logotype-on-hex
@bryevdv Please update the image and publish this pr's branch on the testing server, thanks!

**Comment by bryevdv** [comment]
> Please update the image and publish this pr's branch on the testing server, thanks!

@tcmetzger this is done

**Comment by tcmetzger** [comment]
@bryevdv Thank you very much! The metadate seems to look fine (http://opengraphtools.com/report.php?url=https%3A%2F%2Fdocs.bokeh.org%2Fen%2Ftest%2F) - we can merge anytime now, I think!

**Comment by bryevdv** [comment]
@tcmetzger things are not showing up well on LinkedIn:

https://www.linkedin.com/post-inspector/inspect/http:%2F%2Fdocs.bokeh.org%2Fen%2Ftest%2F

They say they want to see:

```
<meta name="image" property="og:image" content="[Image URL here]">
```
and AFAICT our docs are missing the `'name="image"` part of the meta tag. Is  it possible to add that?

**Comment by bryevdv** [comment]
Wow that's annoying, I guess the baked link requires login You should be able to go here and enter the URL manually:

https://www.linkedin.com/post-inspector/inspect/

**Comment by tcmetzger** [comment]
Well, if that's what they want, I can manually add that. It might take a few days or weeks until all relevant webpages have updated their databases with our new metadata, so we might need more adjustments down the line. I will also try to address the LinkedIn issue with the people maintaining the sphinx-opengraph extension.

**Review by bryevdv — APPROVED** [review]

**Pull request merged**
