### PR TITLE
W0rdsm1th/master/9064 bokeh command typing

### LINKED ISSUE #9064: Add static typing to bokeh
This is a meta issue for adding static typing to bokeh:

- [x] `bokeh.palettes`
- [ ] `bokeh.embed.standalone`
- [ ] `bokeh.util.string` @mborus

### PR DESCRIPTION
**Pull request by w0rdsm1th**
resubmission of #9390 after fixing and running unit tests. small changes to logic as per below

- [X] issues: addresses #9064 
- [X] tests passed

bokeh.bokeh.command.subcommands.__init__.py
[x] fix failed unit test by removing typ_checking conditional from import Subcommand

[x] in import Subcommand in bokeh.command.subcommands._collect(), changed hasattr(attr, 'name') to getattr(attr, 'name'). because typing added empty string "name" attribute to abstract bases

bokeh.tests.unit.command.subcommands.test_serve.py
[x] changed the default None tuple in --log-level args to ("None", ) to align with subcommands.serve.py due to typing and combining tuples of strings

### CODE REVIEW

**Comment by bryevdv** [comment]
@w0rdsm1th  Here are the current linter errors:
```
       assert proc.returncode == 0, "Flake8 issues:\n%s" % out.decode("utf-8")
E       AssertionError: Flake8 issues:
E         ./bokeh/command/bootstrap.py:46:1: F401 'typing.Any' imported but unused
E         ./bokeh/command/bootstrap.py:46:1: F401 'typing.Optional' imported but unused
E         ./bokeh/command/bootstrap.py:46:1: F401 'typing.Sequence' imported but unused
E         ./bokeh/command/bootstrap.py:46:1: F401 'typing.Tuple' imported but unused
E         ./bokeh/command/bootstrap.py:57:1: F401 '.subcommand.Subcommand' imported but unused
E         ./bokeh/command/util.py:25:1: F401 'typing.Union' imported but unused
E         ./bokeh/command/subcommands/build.py:21:1: F401 'typing.Sequence' imported but unused
E         ./bokeh/command/subcommands/serve.py:415:1: F401 'typing.Optional' imported but unused
E         
E       assert 1 == 0
E        +  where 1 = <subprocess.Popen object at 0x7fa96ef7e5d0>.returncode
```
Also the indentation in the `file_contents` function breaks the sphinx build (sphinx is very picky)

**Comment by bryevdv** [comment]
I've also resolved the small merge conflict here, you'll want to do a pull

**Comment by w0rdsm1th** [comment]
thanks @bryevdv 

I appreciate the patience, this my first time submitting PR to a proper library! I have been using bokeh for last ~6mos on the day job and enjoying it. got a fun D3.js extension to submit soon

**Comment by bryevdv** [comment]
@w0rdsm1th Thank you for the kind words. Did you mean to close this PR? I think it was very close, just a few small formatting changes, before it could be merged. Would you like me to re-open it?

**Comment by w0rdsm1th** [comment]
@bryevdv thanks for the feedback and re-opening the PR. I was going on vacation and was in a rush to close out loose ends. Sorry for the radio silence. I'm back now and have rebased from master, fixed the last few things and plan to commit changes to this PR tomorrow.

The last item before committing is testing sphinx. Both "make clean html serve" or "make all" on Windows 10 give errors as below. Do you have any ideas or suggestions? Else I am happy to investigate.

make clean: (still trying to find how to set sphinx log level to find out which file is missing)
`The system cannot find the file specified.`

make all: (The module definitely exists and I'm running from \bokeh\sphinx directory)
`Could not import extension bokeh.sphinxext.bokeh_settings (exception: No module named 'bokeh.sphinxext.bokeh_settings')`

**Comment by w0rdsm1th** [comment]
have fixed the sphinx issue. bokeh 1.3.4 was installed in my conda virtualenv and sphinx was trying to use the sphinx config.py in bokeh project folder but the site-packages bokeh to make the docs.

I am unsure if this issue is specific to windows 10? I definitely setup my conda environment following https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html#devguide-setup. After I have fully validated I'll post details of the fix

**Comment by bryevdv** [comment]
@w0rdsm1th I'm not sure offhand, though it looks like everything is passing except a new check that now enforces import sort order. If you want to fix that up you would need to:

* `pip install channels` (not documented well but necessary)
* run `isort` on the codebase

I can also push a change to this PR branch, though if that is simpler.

**Comment by w0rdsm1th** [comment]
thanks @bryevdv. I am getting better at reading the CI output but really helpful to know the quick fix. and I probably would have ended up down a rabbit hole about black formatting without it! :)

**Comment by bryevdv** [comment]
@w0rdsm1th happy to help. This PR is very nearly there. I am not sure why there is a small discrepancy between your local `isort` output and the CI, but this small diff will fix it up and then we can merge:
```
diff --git a/bokeh/command/subcommands/build.py b/bokeh/command/subcommands/build.py
index 08af7898c..2835535a8 100644
--- a/bokeh/command/subcommands/build.py
+++ b/bokeh/command/subcommands/build.py
@@ -21,6 +21,7 @@ from argparse import Namespace

 # Bokeh imports
 from bokeh.ext import build
+
 # Bokeh imports
 from ..subcommand import Subcommand

diff --git a/bokeh/command/subcommands/init.py b/bokeh/command/subcommands/init.py
index 50a9529d6..1f4e4847c 100644
--- a/bokeh/command/subcommands/init.py
+++ b/bokeh/command/subcommands/init.py
@@ -21,6 +21,7 @@ from argparse import Namespace

 # Bokeh imports
 from bokeh.ext import init
+
 # Bokeh imports
 from ..subcommand import Subcommand

diff --git a/bokeh/util/hex.py b/bokeh/util/hex.py
index 50872904b..55fbf584b 100644
--- a/bokeh/util/hex.py
+++ b/bokeh/util/hex.py
@@ -23,7 +23,7 @@ log = logging.getLogger(__name__)
 #-----------------------------------------------------------------------------

 # Standard library imports
-from typing import Tuple, Any
+from typing import Any, Tuple

 # External imports
 import numpy as np
```

**Comment by bryevdv** [comment]
@w0rdsm1th  the blank lines between import sections in `build.py` and `init.py` (shown in the diff) are also required.

**Comment by bryevdv** [comment]
Well, I made those small whitespace edits here, but now a bunch of new mypy errors have suddenly shown up.

**Comment by bryevdv** [comment]
OK Travis is now green so this can be merged. @mattpap I plan to merge tomorrow unless there is objection. The only think I turned off were function calls outside the area of concern.

**Comment by bryevdv** [comment]
Thanks @w0rdsm1th !

**Pull request merged**
