### PR TITLE
Redesign resource management

### LINKED ISSUE #3529: Unify dev and non-minified resources
There was a distinction when we used requirejs (loading individual files), but now it's only confusing. By default all resources should point to minified versions and under `dev` should point to non-minified.

### PR DESCRIPTION
**Pull request by mattpap**
This is an early WIP preview.

The goal of this work is to bring some sanity to resource management (and later embedding). This splits up resources in more manageable pieces, introduces static typing, defines terminology and in general overhauls how we define and consume resources across bokeh.

Terminology:

- `Asset` - a concrete JS, CSS (or other) file or inline content
- `Bundle` - a concrete collection of assets
- `Artifact` - a collection of assets resolvable by a resolver
- `Resolver` - a method to produce assets from artifacts
- `Resources` - defines how to resolve artifacts (produces a resolver)

Resources are now split into well defined chunks:

- `CDNResources`
- `ServerResources`
- `FileResources`
  - `InlineResources`
  - `RelativeResources`
  - `AbsoluteResources`

Those are classes, which can be initialized and configured. Note that all classes are now immutable and configuration is updated by cloning. For users' convenience, `CDN` and `INLINE` global instances are preserved, so for an average user any changes in this PR won't be noticeable

I will updated this description with more details as work progresses.

fixes #3529

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap since we are still not quite ready to freeze, I'd really like to try and get this PR in. Is there anything I can do to help move things along?

**Comment by bryevdv** [comment]
@mattpap  I am going to rebase this on master later today to get off fast-fail tests, and start fixing up any small issues (codebase otherwise) to move this along.

**Comment by mattpap** [comment]
@bryevdv, I'm currently in the middle of big changes to this branch, so please don't rebase it unnecessarily.

**Comment by mattpap** [comment]
This will have to be re-implemented given the extent of intermediate changes. I will keep the branch.

**Pull request closed without merging**
