### PR TITLE
Fix Karel/7788 rangeslider minmax

### LINKED ISSUE #7788: DateRangeSlider error not logged nor shown in CLI
I noticed the following bug:  If you have a DateRangeSlider of which max and min are the same date, the browser shows a blank page client side, and the CLI and error loggers don't show anything unusual.

It took me a while to find the origin of the problem due to the lack of logging.

Conditions hwere this bug was found:

- Tested on both Windows 10 and Ubuntu 16.04
- Python 3.6, tornado 4.5.2, bokeh 0.12.15 (on both systems)
- Firefox (on both systems)

How to reproduce: 
- Put this file in a local folder (e.g. softfocus/): https://github.com/hyamanieu/softfocus/blob/master/softfocus/main.py
- change lines 224 to 227 from (after the bug fix)
```
last_date = self.df['last modification'].max() 
first_date = self.df['last modification'].min()
if last_date == first_date:
    last_date = first_date + timedelta(days=1)
```

to these two lines:
```
last_date = self.df['last modification'].max() 
first_date = last_date
```
With your CLI, cd into the parent folder and execute
`bokeh serve softfocus --show --log-level debug`

Output: blank page on your browser, no errors/warnings in your CLI
Expected output: a working webpage with a frozen DateRangeSlider.

### PR DESCRIPTION
**Pull request by Karel-van-de-Plassche**
- [x] issues: fixes #7788
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by Karel-van-de-Plassche** [comment]
What do you mean with validation check, do you have an example somewhere in bokeh? I was not exactly sure how to hook into the bokeh way of defining attributes to the javascript <> python interface.

**Comment by Karel-van-de-Plassche** [comment]
Also, is it possible to raise an Exception from TypeScript? Wasn't sure.

**Comment by bryevdv** [comment]
Here is an example:

https://github.com/bokeh/bokeh/blob/9bf4ff0b47734b2d3d184c9c7690e8b013893a36/bokeh/models/tickers.py#L171-L174

You can decorate a method with `error` or `warning` decorator (and the validation code it checks) and then at serialization time the check is performed. This is the only way to catch some problems that are a result of e.g. how the entire collection of Bokeh models is arranged or configured. In this case, the current check will not catch:

```
s = RangeSlider(start=1, end=2)
s.start = 2
```

But a validation check will. I would suggest having both. Might as well fail early when we can. 

The method should return `None` if there is no problem, or a descriptive string if there is a problem. We don't currently raise hard exceptions on ERROR conditions but we might in the future. Presently we just try as hard as possible to make the messages loud an unavoidable.

**Comment by Karel-van-de-Plassche** [comment]
> Certainly, or we can log a console error... most people just don't know how to access this information in their browser though, so it's of limited use. Best to try and catch known error conditions on the python side when at all possible.

A console error is already logged by noUiSlider itself, so don't think anything is needed there. 

> Also, is it possible to raise an Exception from TypeScript? Wasn't sure.

AH, sorry, I meant is it possible to raise a bokehjs error to Python? I guess this wouldn't work anyhow if no server is running, so the validation check you suggested is better

**Comment by Karel-van-de-Plassche** [comment]
I have added the validation checks. Unfortunately, I did not manage to write tests for this. I tried copying `bokeh/application/tests/test_application.py`, but no luck. Example:

``` python
import bokeh.models.widgets.sliders as mws 

from datetime import datetime
import logging
import pytest

from bokeh.util.serialization import convert_datetime_type
from bokeh.util.logconfig import basicConfig

# needed for caplog tests to function
basicConfig()

#### SNIP ####

def test_rangeslider_equal_start_end_validation(caplog):
    start = 0 
    end = 10
    s = mws.RangeSlider(start=start, end=end)
    #with caplog.at_level(logging.ERROR, logger='bokeh.core.validation.check'):
    with caplog.at_level(logging.ERROR):
        assert len(caplog.records) == 0
        s.end = 0 
        assert len(caplog.records) == 1
```

**Comment by Karel-van-de-Plassche** [comment]
And shameless self-plug: ionRangeSlider does support equal start and end https://github.com/Karel-van-de-Plassche/bokeh-ion-rangeslider!

**Comment by bryevdv** [comment]
I would switch to ion in a heartbeat if they would add a vertical orientation option.

**Comment by bryevdv** [comment]
@Karel-van-de-Plassche validation does not happen  every time a property is set, that would be too expensive. It only happens once, right when the document is serialized. For tests you will need to call `validate` manually.

**Comment by bryevdv** [comment]
I would also suggest making the name more specific, e.g. `EQUAL_SLIDER_START_END`

**Comment by bryevdv** [comment]
Thanks @Karel-van-de-Plassche !

**Pull request merged**
