### PR TITLE
[NO SQUASH] 2.4 backports

### PR DESCRIPTION
**Pull request by bryevdv**

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap Do we need to backport the chrome update PR? Or can chrome be pinned `branch-2.3`?

**Comment by mattpap** [comment]
> Do we need to backport the chrome update PR? Or can chrome be pinned branch-2.3?

It would be preferable to pin, but right now we rely on the most recent version available in CI, so it means backporting.

**Comment by bryevdv** [comment]
Yikes. Ok I will try to add it to this branch and see what happens.

**Comment by bryevdv** [comment]
Well, as expected trying to cherry-pick that commit back to `branch-2.3` is a nightmare. I don't really have   confidence the latest commit will work at all but 🎲 🎲

**Comment by bryevdv** [comment]
@mattpap looks like somehow these baselines went missing:
```
Line_glyph__should_support_NaN_in_coords.png
Line_glyph__should_support_closed_line_loops.png
Line_glyph__should_support_crossing_line.png
Line_glyph__should_support_dashed_lines_with_named_patterns.png
Line_glyph__should_support_dashed_lines_with_numerical_patterns.png
Line_glyph__should_support_dashed_lines_with_offsets.png
Line_glyph__should_support_dashed_lines_with_round_caps.png
Line_glyph__should_support_dashed_lines_with_square_caps.png
Line_glyph__should_support_solid_lines_with_caps_and_joins.png
webgl__should_support_rect.png
```
@mattpap I could use your help to sort the last part of this out

**Pull request merged**
