### PR TITLE
Improve docs example in first_steps_8.rst

### PR DESCRIPTION
**Pull request by cdeil**
This is a tiny improvement to a docs example, adding a show() call to have a full working example and be consistent with the other examples in the getting started guide.

Filing a [BUG] for such small docs improvements that aren't really bugs seems overkill. Hope it's OK as an exception.

### CODE REVIEW

**Comment by bryevdv** [comment]
cc @tcmetzger IIRC omitting the `show` here was an intentional choice.

**Comment by tcmetzger** [comment]
I honestly don't remember why there is no `show()` in this example, I don't really see a reason why it shouldn't be added. This example looks quite boring if rendered, and the point of using a different data structure as input isn't really illustrated by displaying the plot, but none of that should stop us from having `show()` in there for consistency. 

If we do add `show()`, how about we make the figure a little smaller (by defining `height=250`) and make the circles a little bigger (size=20), for example like this:

```
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource
# create dict as basis for ColumnDataSource
data = {'x_values': [1, 2, 3, 4, 5],
        'y_values': [6, 7, 2, 3, 6]}
# create ColumnDataSource based on dict
source = ColumnDataSource(data=data)
# create a plot and renderer with ColumnDataSource data
p = figure(height=250)
p.circle(x='x_values', y='y_values', size=20, source=source)
show(p)
```

**Comment by cdeil** [comment]
@tcmetzger - I applied your suggestion in 4546f65b195f8ba621bd124736b50dbbe4aa47af

**Comment by cdeil** [comment]
> the point of using a different data structure as input isn't really illustrated by displaying the plot

True. The key question isn't explained: "Why does ColumnDataSource and the other classes exist? Even if they exist internally, why should I as user care or use them?"

> none of that should stop us from having show() in there for consistency

I think simply having full working examples that newbies can copy & paste is the biggest advantage. This actually happened to me: I copy & pasted the example and didn't get a plot. Took me a minute to figure out that I was simply missing the "show" call, but the example otherwise was working perfectly.

---

I do think it would be good to have some information on "why" ColumnDataSource and the filters exist, and "when" I have to or should use them over simple pandas DataFrames, and also what the performance implications are when bokeh makes copies. But that's a different possible aspect of the docs that could be improved. At least I don't know the answer and can't add it here (if you agree something could be added).

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
Thanks for the PR @cdeil !

**Pull request merged**
