### PR TITLE
Support special colors on image glyph

### LINKED ISSUE #5323: ColorMapper special colors are not respected for images
The (Continuous)ColorMapper classes allow defining special colors for the ``nan_color``, ``low_color`` and ``high_color``. However it seems like these are either not respected at all or in some cases even cause errors. Here is a minimal example, I've used named colors here but nothing changes if I use hex colors for example:

```python
import numpy as np
from bokeh.plotting import figure, output_notebook, show
from bokeh.models import LinearColorMapper
from bokeh.palettes import viridis

output_notebook()

p = figure(plot_width=400, plot_height=400, x_range=(0, 10), y_range=(0, 10))

array = np.random.rand(10,10)
array[3:6, 3:6] = np.NaN
cmapper = LinearColorMapper(viridis(256), low=0.25, high=0.75, nan_color='blue', low_color='red', high_color='green')
p.image(image=[array], x=[0], y=[0], dw=[10], dh=[10], color_mapper=cmapper)

show(p)
```

bokeh_plot 20

When using an RGB(A) tuple for a color bokeh breaks completely and I have to refresh the page before any plot will render again. The JS console provides the following error message:

```
Uncaught TypeError: t.toLowerCase is not a function
```

Bokeh 0.12.3rc2
OSX 10.11.6
Chrome Version 53.0.2785.143 (64-bit)

### PR DESCRIPTION
**Pull request by canavandl**
- [x] issues: fixes #5323
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

~~Todo: add tests~~

~~This PR is probably more proof that we need to outline our needs for the color mappers and then refactor.~~ was able to make relatively small changes

~~Note: only hex colors are now supported for Image glyph special colors (nan/high/low)~~ Resolved

### CODE REVIEW

**Comment by canavandl** [comment]
example from #5323 

code:
```
import numpy as np
from bokeh.plotting import figure, show
from bokeh.models import LinearColorMapper
from bokeh.palettes import viridis

p = figure(plot_width=400, plot_height=400, x_range=(0, 10), y_range=(0, 10))

array = np.random.rand(10,10)
array[3:6, 3:6] = np.NaN
cmapper = LinearColorMapper(viridis(256), low=0.25, high=0.75, nan_color='blue', low_color='red', high_color='green')
p.image(image=[array], x=[0], y=[0], dw=[10], dh=[10], color_mapper=cmapper)

show(p)
```

screen shot 2016-10-12 at 12 35 04 pm

**Comment by birdsarah** [comment]
Ran some examples locally and they look good to me.

**Comment by bryevdv** [comment]
@canavandl this is just intended as a band-aid for `0.12.4` ? That flag is not a long-term fix.

**Comment by canavandl** [comment]
Yes - a bandaid. I'll open a new issue to track resolving this better.

**Comment by jbednar** [comment]
Just to be clear, is there currently any way that works for me to specify "clear" as a color, so that the background shows through where blue shows above?  Tuples are broken, and hex strings are limited to 6 characters, right?, so is there any other way to make this area transparent?

**Pull request merged**
