### PR TITLE
Hotfix/division by zero in logmapper

### LINKED ISSUE #4639: divide by zero error in LogColorMapper
Here: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/mappers/log_color_mapper.coffee#L28

In instances were the low values is zero, causes a silent "divide-by-zero" that causes the colormap to be all black.

### PR DESCRIPTION
**Pull request by canavandl**
- [x] issues: fixes #4639 
- [x] tests added / passed

Refactor as: `Math.log1p(x/y)` -> `Math.log1p(x) - Math.log1p(y)`

### CODE REVIEW

**Comment by canavandl** [comment]
Sorry for the git shenanigans - I'd accidentally had a stray commit against master.

**Comment by jbednar** [comment]
Hopefully this can be applied for the 0.12 release!

**Comment by philippjfr** [comment]
Just tested it, all working now.

**Comment by bryevdv** [comment]
Yes, let's have an rc3 tomorrow.

**Comment by bryevdv** [comment]
LGTM

**Pull request merged**
