### PR TITLE
add kwargs documentation for DirectoryHandler

### PR DESCRIPTION
**Pull request by n-west**
- [ ] issues: none
- [x] tests added / passed: none
- [x] release document entry (if new feature or API change)

Added so that the required filename keyword is exposed to docs in https://bokeh.pydata.org/en/latest/docs/reference/application/handlers/directory.html#bokeh.application.handlers.directory.DirectoryHandler.__init__

### CODE REVIEW

**Comment by bryevdv** [comment]
Thanks for the PR @n-west, as long as you are updating this file, could you add the optional `argv` keyword arg as well?

**Comment by n-west** [comment]
Sure. What's your preference for commits here? Just add a new one or squash them together?

BTW, bokeh has been mostly great to work with-- really nice job by the dev team and contributors :-)

**Comment by bryevdv** [comment]
@n-west we ultimately do squash merges on our end, so we are pretty flexible with however people want to submit. This PR is fine now as is so I plan to merge when CI goes green

**Comment by bryevdv** [comment]
Also, thanks!

**Pull request merged**
