### PR TITLE
Webgl: make selections work also for over 65k points

### PR DESCRIPTION
**Pull request by almarklein**
issues: #2590

Implements a workaround to deal with the fact that the indexbuffer is 16 bit.

### CODE REVIEW

**Comment by bryevdv** [comment]
Is there a test or example that exercise this new code?

**Comment by almarklein** [comment]
Ah yes, the `examples/plotting/file/glyphs.py` was broken with webgl, with this PR it works again.

**Comment by bryevdv** [comment]
@almarklein Sorry no I meant is there an example that I can run to test selection on more than 65k points?

**Comment by almarklein** [comment]
Doh, my mistake; I was mixed up with the orger PR. The scatter10k.py should do, if you crank up `N` a bit.

**Comment by bryevdv** [comment]
I hit a resource limit on Safari with 80k points. On Chrome it works, but I only see selected points, the non-selection (typically "grayed out") does not show up:

screen shot 2015-07-30 at 12 35 42 pm

**Comment by bryevdv** [comment]
Ah! because the `nonselection_alpha` is set to `0.001`. Changing it to `0.01` gives:
screen shot 2015-07-30 at 12 38 25 pm

Will merge after lunch.

**Pull request merged**
