### PR TITLE
fixes #9446

### LINKED ISSUE #9446: Misname/copypasta: login_hander?
Are these supposed to be `login_handler` and `logout_handler` instead of `hander`?
https://github.com/bokeh/bokeh/blob/master/bokeh/server/auth_provider.py#L110

### PR DESCRIPTION
**Pull request by timkpaine**
- [x] issues: fixes #9446

### CODE REVIEW

**Comment by bryevdv** [comment]
Thanks for the catch and the fix @timkpaine

**Comment by bryevdv** [comment]
BTW I was debating if this needs any documentation support about an API change, and decided there isn't actually one. Everything that *uses*  subclass of `AuthHandler` is actually looking at/for `login_handler` (correctly spelled) so to actually use this functionality they would need to define the property correctly spelled even with previous releases. Basically these mis-spelled properties are harmles but also useless appendages. But if someone has written a working AuthProvider subclass already, then it will not need to change.

**Comment by timkpaine** [comment]
Yep I made sure to grep for any other uses

**Comment by bryevdv** [comment]
The one CI error is unrelated and spurious (something currently happening on PRs from forks, we just discovered) It will resolve on merge, so I will merge now. thanks @timkpaine !

**Pull request merged**
