### PR TITLE
Make all tests compatible with xdist

### LINKED ISSUE #7679: Make it possible to use pytest-xdist for all tests
Currently, running something like `pytest -n auto` results in an error - different nodes collect different test.

### PR DESCRIPTION
**Pull request by p-himik**
Fixes #7679

### CODE REVIEW

**Comment by bryevdv** [comment]
@p-himik FWIW I am willing to entertain the notion of scrapping the API spec. I guess we don't have to do that now, but in any case why is the `OrderedDict` only needed in one place but not everywhere?

**Comment by p-himik** [comment]
@bryevdv Yeah, working around unordered members of a class was rather simple.
Ah, good catch - that's just me being sloppy.

**Comment by bryevdv** [comment]
Noting: will need merge/rebase on master after #7732

**Comment by bryevdv** [comment]
FYI I've resolved the merge conflict.

**Comment by bryevdv** [comment]
I'm going to go ahead and close this, given the conflict and inactivity. @p-himik please feel free to open a new PR for this anytime. Also note the API tests have been removed, in case that makes things simpler

**Pull request closed without merging**
