### PR TITLE
FIx CI Miniconda download

### LINKED ISSUE #9895: CI build is broken (suddenly using Python 2)
Overnight, for some reason the build step is seeing Python 2, even though the PATH is appended with the `anaconda3/bin` directory:
```
Run BUILD_DEPS=`python scripts/deps.py build`
Traceback (most recent call last):
  File "scripts/deps.py", line 18, in <module>
    exec(setup_src)
  File "<string>", line 68, in <module>
  File "/home/runner/work/bokeh/bokeh/_setup_support.py", line 278
    print("Building BokehJS... ", end="")
                                     ^
SyntaxError: invalid syntax
##[error]Process completed with exit code 1.
```
ref: https://github.com/bokeh/bokeh/runs/571207510

### PR DESCRIPTION
**Pull request by bryevdv**
- [ ] issues: fixes #9895

### CODE REVIEW

**Comment by bryevdv** [comment]
AFAICT an Anaconda python is not yet actually installed at the point the `deps.py` script is called, and was not in previous working builds either, though. Did GH switch `/usr/bin/python` to Python2??

**Comment by bryevdv** [comment]
The curl for Miniconda is failing (but for some reason that build step is not failing):
```
Run if [[ "Linux" = "Linux" ]]; then
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```

**Comment by mattpap** [comment]
> didn't know that exists.. maybe new?

Apparently they added Miniconda (conda 4.8.2) (https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md).

**Comment by bryevdv** [comment]
I guess we had never updated the old `repo.continuum.io` link and also not enabled re-directs (maybe anaconda started issuing 301s overnight)

**Comment by mattpap** [comment]
curl apparently doesn't follow the redirect from continuum to anaconda domain. wget doesn't have that problem.

**Comment by bryevdv** [comment]
`curl -L` will follow, so I updated the command as well as the URL

**Comment by bryevdv** [comment]
slightly longer term maybe we can use the system conda and avoid the miniconda download. I'l make a separate issue.

**Pull request merged**
