### PR TITLE
#2487 - London Postcodes

### PR DESCRIPTION
**Pull request by ciacicode**
This pull request refers to discussion: https://github.com/bokeh/bokeh/issues/2487

Added modules involve the sample data folder:
- london_postcodes.csv
- london_postcodes.py

### CODE REVIEW

**Comment by canavandl** [comment]
Hi @ciacicode 

The Travis build failed because you have a syntax error in your london_postcodes.py file (you're missing a closing parenthesis on line 18). Are you able to make and edit and commit it?

Thanks again for contributing!

**Comment by ciacicode** [comment]
Argh, what a silly mistake! I will do the change and commit immediately :)

**Comment by canavandl** [comment]
I cloned the branch locally and ran the import. LGTM.

**Comment by ciacicode** [comment]
I realised i could do some improvements, especially to the csv. Up to you if you want to merge already but there may be a new commit this week-end.

**Comment by ciacicode** [comment]
I will open a new

**Pull request closed without merging**
