### PR TITLE
Make bokehjs work in IE again and improve tests

### LINKED ISSUE #6212: Issue with test build 0.12.6dev3 on Windows 7 with IE11
I encountered an issue with test build 0.12.6dev3 uisng IE11 on Windows 7 with Python 3.5.3

Using the code below from the User Guide Getting Started page.

```python
from bokeh.plotting import figure, output_file, show

# prepare some data
x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]

# output to static HTML file
output_file("lines.html")

# create a new plot with a title and axis labels
p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')

# add a line renderer with legend and line thickness
p.line(x, y, legend="Temp.", line_width=2)

# show the results
show(p)
```

Expected result
good_simple_line

Actual result:

bokeh_obj_doesnt_support

In Chrome, with the above configuration, the result is as expected.

Build 0.12.6dev2 does not have this issue.

### PR DESCRIPTION
**Pull request by mattpap**
fixes #6212

### CODE REVIEW

**Comment by bryevdv** [comment]
What versions of IE do not support `Event`?  having a "renderered" event that e.g. `js_on_event` can respond to would be useful on all platforms.

**Comment by mattpap** [comment]
This is event is for testing purpose, so it doesn't matter. This will be replaced anyway with proper rendering heuristic. Event constructors are supported only in Edge. It's possible to construct those events in IE with other methods, but once again, no need for this.

**Comment by al6ayb** [comment]
Hi,
the issue of IE not supported still persists. Even on 0.12.6. Latest I could manage to produce working output on IE is on 0.12.6dev2

**Comment by bryevdv** [comment]
@al6ayb please make a new separate issue, with more information (exact library, OS, browser versions) as well as JavaScript console output

**Pull request merged**
