### PR TITLE
Allow to recompute layout when panels' dimensions change

### LINKED ISSUE #4394: Axis label size change does not trigger a re-alignment
When @bryevdv was testing the new layout, he was surprised that when he interacted with a grid of plots and zoomed to the point where axis labels were longer than before that other plots didn't update their alignment.

Should we implement / provide an option for that - I worry that it might decrease performance.

### LINKED ISSUE #6356: Colorbar tick labels truncated
Tick labels on the colorbar are truncated.

bokeh_tick_label_truncation

This only occurs for some lengths of tick label, changing the data column which controls the color of the glyphs changes the layout of the plot and the tick labels are no longer truncated.

bokeh_tick_trunc_gif

Code to reproduce the top image:
```python
from bokeh.layouts import row, widgetbox
from bokeh.models import ColumnDataSource, LinearColorMapper, Select, ColorBar
from bokeh.plotting import figure, curdoc
from bokeh.palettes import Viridis256
from bokeh.sampledata import iris

df = iris.flowers

data_options = sorted(df.columns)[:-1]

p = figure(plot_height=400, plot_width=500, toolbar_location=None, id='fig')

# Select widgets
color_select = Select(title='Color', options=data_options, value=data_options[0])


def update_color(attr, old, new):
    source.data.update({'color': df[color_select.value]})
    color_mapper.high = df[color_select.value].max()
    color_mapper.low = df[color_select.value].min()


# set the on_change functions
color_select.on_change('value', update_color)


color_mapper = LinearColorMapper(low=df[color_select.value].min(),
                                 high=df[color_select.value].max(),
                                 palette=Viridis256,
                                 id='cmpr')

source = ColumnDataSource({'x': df['petal_length'],
                           'y': df['petal_width'],
                           'color': df[color_select.value]})
 

# add circle glyphs
r = p.circle('x', 'y',
             size=8,
             color={'field': 'color', 'transform': color_mapper},
             source=source, id='circles')

color_bar = ColorBar(color_mapper=color_mapper,
                     label_standoff=5,
                     location=(10, 0))

# put the pieces together
p.add_layout(color_bar, 'right')
controls = widgetbox([color_select],
                     width=200)
layout = row(controls, p)

curdoc().add_root(layout)
```

bokeh version: 0.12.5
python: 3.5

Reproduced in chrome, firefox, and the notebook.

Discussed in https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/lZKC74AR6qo

### LINKED ISSUE #6676: Axes' tick labels are trimmed when moving plot
According to the output of `Bokeh.version` in the JS console, the page at https://demo.bokehplots.com/apps/sliders uses Bokeh 0.12.3. If you move the plot around (say, move it up to see negative values on the Y axis), you'll see that the plot width changes to make all axes' tick labels visible.

Now, if you serve the same app with Bokeh 0.12.6, you'll notice that the behavior is different - the width is not changed and the labels get trimmed.

Probably it's normal as many people desire a constant size of the plot itself. In this case, is there any way to make sure that the axes' tick labels are not trimmed at least within some range?

### PR DESCRIPTION
**Pull request by mattpap**
fixes #4394
fixes #6676 
~~~fixes #6356~~~

### CODE REVIEW

**Comment by mattpap** [comment]
This is useful for testing:
```python
import numpy as np

from bokeh.plotting import figure, show, output_file
from bokeh.models import NumeralTickFormatter
from bokeh.layouts import column

def plot(n):
    x = np.linspace(0.1, 5, 100)

    p = figure(title="log axis example: %s" % n, y_axis_type="log",
               y_range=(0.001, 10**22))

    p.yaxis.formatter = NumeralTickFormatter(format="0,0")

    p.line(x, np.sqrt(x), legend="y=sqrt(x)",
           line_color="tomato", line_dash="dotdash")

    p.line(x, x, legend="y=x")
    p.circle(x, x, legend="y=x")

    p.line(x, x**2, legend="y=x**2")
    p.circle(x, x**2, legend="y=x**2",
             fill_color=None, line_color="olivedrab")

    p.line(x, 10**x, legend="y=10^x",
           line_color="gold", line_width=2)

    p.line(x, x**x, legend="y=x^x",
           line_dash="dotted", line_color="indigo", line_width=2)

    p.line(x, 10**(x**2), legend="y=10^(x^2)",
           line_color="coral", line_dash="dashed", line_width=2)

    p.legend.location = "top_left"

    p.xaxis.axis_label = 'Domain'
    p.yaxis.axis_label = 'Values (log scale)'
    return p

output_file("logplot.html", title="log plot example")

show(column(plot(1), plot(2)))  # open a browser
```

**Comment by bryevdv** [comment]
Guessing you already know, but`iris_splom.py` becomes entirely unresponsive to pan/zoom with just this change

**Comment by bryevdv** [comment]
Just as a point of comparison, `0.12.4` is very responsive to pan/zoom, but also does make room for axis labels:

screen shot 2017-11-10 at 17 26 33

Are we over-computing layout now, or has the number of constraints increased?

**Comment by mattpap** [comment]
> Are we over-computing layout now, or has the number of constraints increased?

Both. I will be looking into this.

**Comment by mattpap** [comment]
> > Are we over-computing layout now, or has the number of constraints increased?

> Both. I will be looking into this.

Though this is true, the real reason the original approach didn't work is because it didn't make sense. `_get_size()` gives the preferred size of a panel, but actual `_{width,height}.value` may be different, e.g. a title and toolbar sharing a panel.

**Comment by bryevdv** [comment]
@mattpap this does not actually fix the color bar case #6356 It does fixes the main plot axes labels when resizing. It's possible there is just another event handler to hook up, the colorbar code is somewhat duplicative of axis. I will take a quick look

**Comment by bryevdv** [comment]
@mattpap well its not something I will be able to figure out in short order. My inclination is to merge this now and move the color bar issue to the next milestone. Do you have any thoughts?

**Comment by mattpap** [comment]
#6356 seems to be a different issue after all. I think this will get fixed together with issues like #6932.

**Comment by mattpap** [comment]
I tested this with my previous approach and it worked, but the reason was that I enabled full relayout by mistake. Obviously full relayout will make examples like iris_splom unresponsive.

**Comment by bryevdv** [comment]
OK I will merge this as is then and move the last issue to the next milestone, then cut an RC

**Pull request merged**
