### PR TITLE
Compute content size with subpixel precision

### LINKED ISSUE #8654: Text wrapping in Div after layout PR
On current master after the layout PR the sizing behavior for ``Div`` is hugely improved however there is one new behavior which is quite frustrating. By default it seems the Div now wraps any text in it depending on the length of the string. Here's a reproducible example of the issue:

```python 
tinput = TextInput(value='Some text')
div = Div(text='Some Text')

tinput.js_link('value', div, 'text')

Row(children=[tinput, div])
```

div_text

Since Divs can be quite helpful for adding labels, titles and short snippets of instructions this can be quite annoying. Even if there was a convenient workaround here that would be very helpful.

### PR DESCRIPTION
**Pull request by mattpap**
@philippjfr, can you try this out? This should resolve issue with unnecessary wrapping.

fixes #8654

### CODE REVIEW

**Comment by bryevdv** [comment]
Setting up new email accounts and notifs, this is a test

**Comment by bryevdv** [comment]
I'll plan to merge this Monday unless I hear otherwise

**Comment by philippjfr** [comment]
I'll test this shortly.

**Comment by philippjfr** [comment]
I can confirm this fixes the text wrapping issues I was seeing.

**Pull request merged**
