### PR TITLE
Use fixed period when accessing Yahoo's finance data

### LINKED ISSUE #1610: Examples using yahoo's finance data should use a fixed period
Start and end bounds should be configured. Then examples will generate the same images for every point in time, reducing false positives in image diff.

### PR DESCRIPTION
**Pull request by mattpap**
fixes #1610

### CODE REVIEW

**Comment by damianavila** [comment]
This is failing in the gallery...
```
Traceback (most recent call last):
  File "build_gallery.py", line 133, in <module>
    make_gallery(gallery_info['details'])
  File "build_gallery.py", line 79, in make_gallery
    page_infos = [page_desc(desc) for desc in module_descs]
  File "build_gallery.py", line 36, in page_desc
    eval(code, namespace)
  File "source/tutorial/solutions/stocks.py", line 16, in <module>
    parse_dates=['Date'])
  File "/home/travis/miniconda/lib/python2.7/site-packages/pandas/io/parsers.py", line 465, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/travis/miniconda/lib/python2.7/site-packages/pandas/io/parsers.py", line 229, in _read
    encoding)
  File "/home/travis/miniconda/lib/python2.7/site-packages/pandas/io/common.py", line 118, in get_filepath_or_buffer
    req = _urlopen(str(filepath_or_buffer))
  File "/home/travis/miniconda/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/travis/miniconda/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/home/travis/miniconda/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/travis/miniconda/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/home/travis/miniconda/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/travis/miniconda/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
make: *** [tutorial_gallery] Error 1
```

**Comment by mattpap** [comment]
> urllib2.HTTPError: HTTP Error 404: Not Found

btw. That's yet another case of batteries included. Why it can't tell me up front what the address was?

**Comment by damianavila** [comment]
>btw. That's yet another case of batteries included. Why it can't tell me up front what the address was?

Yep, sometimes there is a price to pay for the batteries...

**Comment by damianavila** [comment]
And removing GOOG fixed it... I remember having faced the same problem with the yahoo api some time ago plating with some stocks... anyway, this is ready, merging now...

**Comment by mattpap** [comment]
Yeah, it tried all combinations for all datasets we use and GOOG simply doesn't work. Others (IBM, etc.) work perfectly fine. So, now I have to take care of notebook image-diff and we will have finally reliable reports generated for each PR.

**Comment by bryevdv** [comment]
Rejoicing.

**Pull request merged**
