### PR TITLE
enhance datetimetick formatting

### LINKED ISSUE #13186: [FEATURE] datetime formatting: enhance default formatting
### Problem description

Note: This probably needs some discussion.

Currently the default formatting provides ticks with mixed formats (see screenshots below). In my opinion this makes it extremely difficult to read the axis and to be honest I don't see any benefit over just having the same formatting for all ticks.
The first screenshot is probably an extreme example with three different formats but it highlights pretty well what the problem is.

bokeh_formatter_dt_3
bokeh_formatter_dt_2

Code for reference:

```
import pandas as pd
from bokeh.io import curdoc
from bokeh.models import DatetimeTickFormatter
from bokeh.plotting import figure

import numpy as np

t = pd.date_range("2023-06-01", periods=11).tz_localize("US/Pacific") #.tz_localize(None)
print(t)
y = np.linspace(0, 10, 11)

fig = figure(x_axis_type="datetime")
fig.line(t, y)

doc = curdoc()
doc.add_root(fig)
```

### Feature description

Improve default formatting by avoiding mixed formats. Perhaps it might also be possible to adapt a Matlab style formatting which provides an additional label for the whole axis.

bokeh_formatter_dt_4

### Potential alternatives

keep it as it is

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by muendlein**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [ ] issues: fixes #13186
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@muendlein There seems to be three things in this PR:
 
* hiding repeats
* scaling up on boundaries
* adding default contexts

is that accurate? If so, I would suggest splitting this into 3 chunks of work. The first two seem fairly straightforward, but the third may require some thought so it will be easier to evaluate and iterate on isolation.

**Comment by muendlein** [comment]
@bryevdv Yes that's accurate, should I provide three separate pull requests for each chunk?

**Comment by bryevdv** [comment]
@muendlein I think that would ideal I think we can speed through things more quickly with smaller individual PRs

**Comment by muendlein** [comment]
Closing this PR as it will be split up into separate ones.

**Pull request closed without merging**
