### PR TITLE
Organize  Axis and MathText visual tests

### PR DESCRIPTION
**Pull request by IuryPiva**
Axis tests is generating too many baseline images. I made some changes to move some tests out and only generate baseline to tests where they are relevant.

- [x] issues: relates to https://github.com/bokeh/bokeh/pull/11636#issuecomment-924196901
- [x] tests added / passed

### CODE REVIEW

**Comment by bryevdv** [comment]
I think we need even more subdivistion, i.e. `axes.ts` should be come an `axes/` directory with the test files including math-text tests *specific to axes* underneath

**Comment by bryevdv** [comment]
@IuryPiva looks like the location of the baselines will also need to be moved accordingly

**Comment by IuryPiva** [comment]
> @IuryPiva looks like the location of the baselines will also need to be moved accordingly

Yes, I'm waiting on everyones feedback so that I don't add more baselines to the repo history

**Comment by bryevdv** [comment]
It's OK w/ me tho I did earlier underestimate the number of affected files. I do think we very soon need to figure out a git-lfs solution for baselines (or submodule perhaps).

**Review by bryevdv — DISMISSED** [review]

**Comment by bryevdv** [comment]
An issue with merging this now is that it makes any backports related to this area of code substantially more difficult. Could we wait to do this re-arrangement right before the 3.0 release?

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
OK we will merge this now, and immediately backport tomorrow.

**Comment by mattpap** [comment]
> (...) immediately backport tomorrow.

Backport to what? This is purely 3.0 thing and not ready yet. We will discuss those changes in the tomorrow's CZI metting.

**Comment by mattpap** [comment]
This is still too many cases being tested. It would be good to have text annotations done at this point, as it would be be a good place to offload some of those cases.

**Comment by bryevdv** [comment]
> Backport to what?

Back port to `branch-2.4` so that future backports are not made more complicated by file locations that don't match up. This is a purely internal change there that has zero effect on users, there is no reason not to backport it.

**Comment by bryevdv** [comment]
> This is still too many cases being tested. It would be good to have text annotations done at this point, as it would be be a good place to offload some of those cases.

What is the actual goal here? I thought the point was to break up existing tests to be in more manageable chunks. This does that. Coupling this work to future yet TBD work complicates life for multiple people and is not necessary. It is fine, good in fact, to be more incremental. i.e. merge this now, update text annotation work based on this in the context of a PR specific to text annotations.

**Comment by bryevdv** [comment]
> We will discuss those changes in the tomorrow's CZI meeting.

@mattpap @IuryPiva what was the decision?

**Comment by mattpap** [comment]
We've decided to postpone this PR, finish text annotations first, write extensive tests there, then update this PR to include only axis specific tests, and then progress with other related PRs (styling, `MathTextView` reorganization).

**Comment by IuryPiva** [comment]
Superseded by https://github.com/bokeh/bokeh/pull/11708

**Pull request closed without merging**
