### PR TITLE
Refresh gallery thumbnails

### PR DESCRIPTION
**Pull request by bryevdv**
This PR refreshes all the gallery thumbnails with new 300x300 thumbnails that are taken from current versions of the plots. The naming scheme for the gallery images has also become more explicit e.g. `examples-plotting-marker_map.png` There are currently a handlful of existing gallery entries that are deleted because they are currently broken (#12404, #12405) I have also pre-emptively added some thumbnails for the @ianthomas23's great contour examples that are only in the user guide. They really should be in the galley we just need to see if there is a way to do it without duplicating source files. 

@tcmetzger the thumbs are currently in a tight grid. I think they need space and perhaps a drop shadow, what do you think?

Edit: I guess these thumbnails were captured at "retina" resolutions of 600x600 rather than 300x300 I could resize them all, or perhaps we could ship `@x2` versions but I am not sure how those get used on retina systems, exactly. Or we could just keep really big thumbnails. I am open to ideas.

### CODE REVIEW

**Comment by bryevdv** [comment]
I guess to use two thumbnail sizes we would need to update our gallery template to use media queries, e.g. 

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

Or perhaps there is a sphinx extensions for image grids with links we could leverage. E.g. there is `sphinx-gallery` but it is nominally tilted heavily towards scraping matplotlib images. But it does support [custom image scrapers](https://sphinx-gallery.github.io/stable/advanced.html#custom-scraper) so maybe we could just "scrape" by using the file path to look up checked-in manual thumbnails.

**Comment by ianthomas23** [comment]
The first user guide contour example is maybe a bit too simple for the gallery. We could create a new example based on it that is more complicated/interesting and use that instead? This would also conveniently avoid the problem of the example code being duplicated.

**Comment by bryevdv** [comment]
> The first user guide contour example is maybe a bit too simple for the gallery

I disagree here, that example is very visually compelling and attractive *because* it is simple. Many of the thumbnails are very busy and have too much going on in a small image. That contour example will immediately draw anyone looking for "contour" i the gallery. I actually think our gallery needs to move much more towards the MPL style of gallery, that is more, simple examples, arranged within a handful of categories

**Comment by mosc9575** [comment]
Because there is a discussion about the number of images in the gallery I want to mention that [bar_nested](https://docs.bokeh.org/en/dev-3.0/docs/examples/plotting/bar_nested.html) and [bar_nested_colormapped](https://docs.bokeh.org/en/dev-3.0/docs/examples/plotting/bar_nested_colormapped.html) are duplicates in my opionion and that I would remove the one without colormapping from the gallery. The other can be still there in the more detailed [Exmaple-Index](https://docs.bokeh.org/en/dev-3.0/docs/examples.html#example-index).

**Comment by bryevdv** [comment]
I disagree that they are duplicates. Both versions are used, and they differ in complexity, so both versions should be individually demonstrated. Our gallery problem is not that we have too many entries, it is that we have too many entries *without any organization*. I would easily like to triple there gallery size, with appropriate subdivisions.

**Comment by ianthomas23** [comment]
> I disagree here, that example is very visually compelling and attractive _because_ it is simple.

OK, I am fine with this then.

**Comment by bryevdv** [comment]
Closing this, I will submit a new PR soon

**Pull request closed without merging**
