### PR TITLE
Fix recent layout regressions

### LINKED ISSUE #11057: [BUG] Sizing mode example layout broken in docs
ref: https://docs.bokeh.org/en/latest/docs/user_guide/layout.html#sizing-modes

Starting in 2.3 the layout of the examples above is broken:

---

Screen Shot 2021-03-13 at 8 57 52 PM

cc @mattpap

### PR DESCRIPTION
**Pull request by mattpap**
This is more a workaround than a fix, but it seems it works (unless I missed some cases).

fixes #11057

### CODE REVIEW

**Comment by mattpap** [comment]
Marking this as tentatively ready. /cc @philippjfr

**Comment by philippjfr** [comment]
Thanks will test tomorrow.

**Comment by bryevdv** [comment]
restarted tests, I think networkx has maybe already sorted their dependency issue.

**Comment by philippjfr** [comment]
Sorry unrelated but I'm having trouble testing this against Panel since I'm getting this error: `Uncaught Error: Cannot find module '../../core/visuals'`.

**Comment by mattpap** [comment]
> Sorry unrelated but I'm having trouble testing this against Panel since I'm getting this error: Uncaught Error: Cannot find module '../../core/visuals'

@philippjfr, this seems to be a build cache issue (at some point `core/visuals` were split, which requires a full rebuild). `node make build --rebuild` or remove the cache (`node make clean`).

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
This fixes the issue noted in the docs and examples. I am going to go ahead and merge to try and get 2.3.1rc out tomorrow @philippjfr if you encounter issues w/ panel we can re-open or open new issue as appropriate.

**Pull request merged**
