### PR TITLE
Handle WebGL line indices

### LINKED ISSUE #12357: [BUG] webgl breaks shared brushing
### Software versions

Python version      :  3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
IPython version     :  7.31.1
Tornado version     :  6.1
Bokeh version       :  2.4.3
BokehJS static path :  C:\Users\ajhenryson\AppData\Local\Continuum\anaconda3\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19041-SP0

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

A shared columndatasource should have shared brushing for selections. Selecting circle glyphs should change the appearance of lines plotted from the same source.

### Observed behavior

Only the circle glyphs showed selection, not the lines.

### Example code

```Python
from bokeh.io import output_file, show
from bokeh.layouts import gridplot
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

output_file("brushing.html")

x = list(range(-20, 21))
x2 =list(range(-30, 10))
y0 = [abs(xx) for xx in x]
y1 = [xx**2 for xx in x2]

# create a column data source for the plots to share
source = ColumnDataSource(data=dict(x=x, x2=x2, y0=y0, y1=y1))

TOOLS = "box_select,lasso_select,help"

# create a new plot and add a renderer
left = figure(tools=TOOLS, width=300, height=300, title=None,output_backend="webgl" )
left.circle('x', 'y0', size=0, color='red', source=source) #size zero used to illustrate other unexpected behavior of glyphs
left.line('x', 'y0', source=source)


p = gridplot([[left]])

show(p)
```

### Stack traceback or browser console output

_No response_

### Screenshots

image
circles are affected, but lines are not.
image
Removing the webgl backend option restores expected function.

It also seems to cause size 0 circles to be shown rather than hidden, but I don't know if that's a separate bug.

### PR DESCRIPTION
**Pull request by ianthomas23**
Fixes #12357.

This PR handles selection indices for WebGL line glyphs so that shared brushing for WebGL lines gives the same results as for canvas.
indices

Note that strictly speaking they are both incorrect. The line segment just beyond the selected circles is not displayed, either in `selected` or `unselected` appearance. This is because the selection indices apply to the circles not the line segments, and a particular line segment is only displayed if both end points are in the sequence of selected indices. To fix this will require special behaviour for unselected lines. I will create a separate issue for this.

### CODE REVIEW

**Comment by ianthomas23** [comment]
There is a change to `HexTile_glyph__should_support_'pointytop'_orientation_and_aspect_scale=0.5.blf` that I don't understand.

**Comment by mattpap** [comment]
See https://github.com/bokeh/bokeh/issues/12379, just rerun failing tests.

**Comment by mattpap** [comment]
What's the plan for this PR, 3.0 or later? Assign the milestone with your planned or estimated merge target (in the issue as well).

**Comment by ianthomas23** [comment]
> What's the plan for this PR, 3.0 or later? Assign the milestone with your planned or estimated merge target (in the issue as well).

I don't have a plan for when this should be merged. In the absence of definitive information about when 3.0 will be released and what work is required before then I am not able to make any judgement on the subject.

**Comment by bryevdv** [comment]
@ianthomas23 FYI tomorrow I am going to propose we cut a release candidate next week with whatever we have at that point, and simply note existing deficiencies as known issues.

**Comment by ianthomas23** [comment]
> @ianthomas23 FYI tomorrow I am going to propose we cut a release candidate next week with whatever we have at that point, and simply note existing deficiencies as known issues.

OK, all the tests are passing and I think there is nothing controversial here, so I'll target 3.0 for this. The new issues I created today I'll bump to 3.1.

**Pull request merged**
