### PR TITLE
docs: fix code snippet in Label

### PR DESCRIPTION
**Pull request by lucach**

### CODE REVIEW

**Comment by bryevdv** [comment]
@lucach why do you regard the existing code snippet as broken?  As it already was, it seems to demonstrate that units *can* be set to "screen", but do not have to be set to "screen".

**Comment by lucach** [comment]
Oh, I'm sorry: now I see the rationale. Then it's definitely not broken, but I think it's still misleading, especially if you compare with the full example presented a few lines after (which is exactly the same except for the `y_units` argument):

```python
citation = Label(x=70, y=70, x_units='screen', y_units='screen',
```

It reinforces the idea that (70,70) is a pair of pixel coordinates, which will be always shown. Instead, 70 data units is a measure that often lies outside the viewing area, creating a potential confusion. I'd at least use a different value for the y coordinate, and possibly even not rely on the default value for the argument (i.e., passing explicitly `y_units='data'`). Just my humble suggestion.

**Comment by bryevdv** [comment]
> I'd at least use a different value for the y coordinate

@lucach this sounds reasonable, can you update the PR to do this instead?

**Comment by lucach** [comment]
Done: now the example doesn't trigger the mental association with the full code below.

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
Thanks @lucach  I was off last week, will merge when green

**Pull request merged**
