### PR TITLE
Use [bokeh fork of] numbro.js instead of Numeral.js

### PR DESCRIPTION
**Pull request by mistakevin**
Precedes https://github.com/bokeh/bokeh/pull/3025

### CODE REVIEW

**Comment by bryevdv** [comment]
@mistakevin there is a merge conflict in `bokeh/tests/test_embed.py`

**Comment by bryevdv** [comment]
As an aside I think we need to audit our utf-8 encode/decode boundaries. I think there are some inconsistencies. I think I erred earlier on and had conversions happening sooner than is probably advised.

**Comment by mistakevin** [comment]
Yeah, I see the conflict. I was hoping @dennisobrien could resolve it. I just wanted to show how to pull in the forked Numbro repository. I haven't looked at the rest of the PR.

**Comment by dennisobrien** [comment]
Hi @mistakevin

Sorry I've busy the last few days and missed this discussion.  I don't see the merge conflict mentioned.  I see the branch conflict message in this PR but I don't see any details.  Let me know what I can do to help get this done.

cheers,
Dennis

**Comment by mistakevin** [comment]
@dennisobrien Create a local branch of this branch. Pull in the latest bokeh master branch and you'll see the conflict. If you aren't set up to pull branches directly from the base bokeh repository, you can do it following these steps:
1. In your terminal inside your forked bokeh directory, set your "upstream"
`git remote add upstream https://github.com/bokeh/bokeh.git`
2. Create a branch from this branch 
`git checkout -b dennisobrien/fix/2922_use_numbrojs upstream/dennisobrien/fix/2922_use_numbrojs`
3. Pull the master branch from "upstream" into your branch
`git pull upstream master`
4. You'll see the conflict. It'll be in `bokeh/tests/test_embed.py`. Go to the file, resolve the conflict, then add and commit all the changes.
5. Push up the branch to your forked repo, then create a PR against this branch.

**Comment by dennisobrien** [comment]
@mistakevin I finally took some time to do resolve this merge conflict.  It's deeper in the weeds of git than I am used to, and the notes in PR #3128 make it look like I've made 250+ commits, so I'm not very confident that I've done this all correctly.  Thanks for stepping me through this and apologies if I botched this.

cheers,
Dennis

**Pull request closed without merging**
