### PR TITLE
Invalidate computed renderers when HoverToolView.plot_model.renderers changes

### LINKED ISSUE #10612: Hovertool does not work for dynamically added glyphs
#### Context : First I added a blue scatter plot to a figure and an hover tool. Then, I dynamically added an other scatter plot (a red one) thanks to a callback attached to a Button widget. I'm running the script on Bokeh server.
Expected behavior : The hover tool works for both scatter plots.
Observed behavior : The hover tool only works for the first scatter plot. (the blue one)
This issue does not appear when I directly add an other scatter plot without using a callback.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.models import Button
from bokeh.io import curdoc, show
from bokeh.layouts import row
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.io import show

def update_button(click):
    source2 = ColumnDataSource({'x': [1, 2, 3], 'y': [3, 1, 2]})
    plot.circle(x='x', y='y', source=source2, line_color='red', fill_color='red', size=5)

TOOLTIPS = [('Ordinate ', '@y'),
            ('Abscissa ', '@x')]

plot = figure(tools = [], tooltips = TOOLTIPS)

source1 = ColumnDataSource({'x': [1, 2, 3], 'y': [1, 2, 3]})

plot.circle(x='x', y='y', source=source1, line_color='blue', fill_color='blue', size=5)

button = Button(label="Add scatter plot", button_type="default")

button.on_click(update_button)

curdoc().add_root(row(button, plot))

```
#### Screenshots or screencasts of the bug in action
Enregistrement-_2

### PR DESCRIPTION
**Pull request by mattpap**
This fixes also fixes memory leak when connecting views' slots and adds support for selectively disconnecting senders, which could be generalized to disconnect signals of removed models.

- [x] tests

fixes #10612

### CODE REVIEW

**Comment by bryevdv** [comment]
👍 for fixing the memory leak but worth asking if we even need to cache computed renderers at all? I would even support deprecating the `names` field so they are not computed at all anymore (just a list, or `auto`)

**Comment by mattpap** [comment]
> if we even need to cache computed renderers at all

Given that computed renderers are used on every inspect and their computation (even without names) is pretty expensive (when used that frequently), then I think caching them makes sense.

**Comment by bryevdv** [comment]
> Given that computed renderers are used on every inspect and their computation (even without names) is pretty expensive (when used that frequently), then I think caching them makes sense.

But if we get rid of `names` there is nothing to compute, right? The computation is mostly only to mediate between the explicit renderer list and the indirect names list? For the case of `"auto"` we could compute once at init and replace the value with the actual computed list (and then e.g. appending later would "just work") Just an idea.

**Comment by mattpap** [comment]
@bryevdv, see my last commit. Is this what you expected (more or less)?

**Comment by bryevdv** [comment]
@mattpap yes, however:

* I was proposing to start getting rid of the `names` property everywhere, not just hover tool
* Ideally a (Python) `names` property would emit a deprecation and add renderers based on name *on the Python side*. We would remove this altogether at 3.0
* But on the assumption that `names` has never been demonstrated anywhere and is mostly-disused, I would be  also be OK to just remove with Python property that emits a sufficiently informative error message

**Comment by mattpap** [comment]
> (...) add renderers based on name on the Python side

I'm not sure at what point in model's life cycle this would happen? I also think that it would be too much effort anyway. The easiest would be just to keep things as-is and deprecate. Otherwise, we could proceed with the last option, especially that I couldn't find any references to `names` (tests, docs, examples).

**Comment by bryevdv** [comment]
> I'm not sure at what point in model's life cycle this would happen?

Yes, there's not a great solution, I was proposing a half-measure. The ideas that came to my mind were:

* Make `names` a Python property setter that looks for and adds the named renderer immediately (this will not work if the name is set before the renderer exists)

* Abuse a validation step to search for names and add then renderers (this is in lieu of a proper pre-serialization transform step, which we have never implemented)

Anyway, my only hard ask is: deprecate `names` everywhere now and remove everywhere at least by 3.x  However you want to proceed immediately is fine with me.

**Pull request merged**
