### PR TITLE
Execute range callbacks on reset_range (called by reset_tool)

### LINKED ISSUE #4614: Reset tool does not trigger x/y_range callback events
The reset tool obviously changes the extents of the axes, which should trigger any callback events attached to them but it does not appear to. I could swear there was an issue about this that was closed recently, but I can't find it now so I'm probably misremembering. I've tested it as part of 0.12rc1 and it still appears to be an issue there. This functionality is important for downsampling or any other callbacks that depend on the zoom level such as we make use of in datashader.

### PR DESCRIPTION
**Pull request by canavandl**
- [x] issues: fixes #4614
- [ ] tests added / passed (in progress)

ping @philippjfr for testing

### CODE REVIEW

**Comment by bryevdv** [comment]
Should be possible to add JS tests for this

**Comment by canavandl** [comment]
You think it's better to write a selenium test or stub the `execute` callback method and assert it's called?

**Comment by philippjfr** [comment]
Just tested it in datashader and holoviews, works well for me.

**Comment by philippjfr** [comment]
Actually, shouldn't the callback happen after the reset so the ranges are adjusted? Currently my callbacks only update along one of the ranges and I can't figure out if that's due to throttling of the second event or due to the order of resetting.

**Comment by canavandl** [comment]
Yes! Looking at when the callback is executed on a range change event (i.e. via panning), the callback is executed after updating the range data. I'll update the reset callback to match.

**Comment by philippjfr** [comment]
Just switched myself, can confirm that fixes it.

**Comment by canavandl** [comment]
I added a selenium test to check that a CustomJS alert is triggered on clicking the `ResetTool`. Should be a good starting point for additional reset tool testing. Should be merge-able when tests pass.

**Comment by bryevdv** [comment]
Well, I was actually thinking of a gulp unit test, but this probably is ok too

**Pull request merged**
