### PR TITLE
Add support for specifying CSS classes on all LayoutDOM

### LINKED ISSUE #5471: [ENH] Add custom classes to elements
It would be great if you could add custom classes for plots, widgets, layouts and etc.
For example:

```
buttomDiscard = Button(label="Discard", button_type="success", className="customButton")
confirmDialog = widgetbox([buttomDiscard], className="customBox")
```

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #5471
- [x] tests added / passed
- [x] release document entry (if new feature or API change)

Adds .css_classes property to LayoutDOM, which accepts a sequence of strings. These are added as-is to the LayoutDOM element.

### CODE REVIEW

**Comment by bryevdv** [comment]
ping @mattpap @birdsarah 

It would be nice to add an example someplace, if anyone has any simple ideas please let me know.

**Comment by bryevdv** [comment]
Also this could probably be made to work:
```
thing.css_classes = "foo"
```
worthwhile?

**Comment by birdsarah** [comment]
Tried this out. 

It added to a Column fine, a Slider fine, but I then added it to Paragraph and it didn't attach.

Probably going to need to audit all widgets.

**Comment by bryevdv** [comment]
@birdsarah it's working fine for me with `Paragraph`, can you double-check? 
```
from bokeh.plotting import output_file, show
from bokeh.models import Paragraph

p = Paragraph(text="foo")
p.css_classes = ["STUFF"]

output_file("foo.html")
show(p)
```

screen shot 2016-12-02 at 8 26 57 pm

**Comment by bryevdv** [comment]
`Paragraph` uses `$el.html(...)` to render inside the `LayoutDOM` div, were you looking at the inside div? I think putting on the outermost `LayoutDOM` div is best because it is the most consistent thing that could be done, is that not correct?

**Comment by bryevdv** [comment]
OK I am going to merge this when green

**Pull request merged**
