### PR TITLE
breaking out inline plot examples in user guide into files

### PR DESCRIPTION
**Pull request by msarahan**
For the sake of easier reuse of these examples here and elsewhere.  Some PEP8 fixes throughout with flake8.

### CODE REVIEW

**Comment by damianavila** [comment]
This is really nice, @msarahan, thanks for working on this one :+1:

**Comment by bryevdv** [comment]
Choropleth timeout, restarted. I think we should exclude that example from out tests for now (in another PR)

Some followup ideas for other PRs:
* Adding links and inline render directives to docstrings so that plots show up in reference guide as well
* auto-generating note books that demonstrate various properties 
* using (a subset of) these as a basis for strict image diff testing

Thanks @msarahan

**Comment by Maggie-M** [comment]
Everything looks good to me

**Comment by bryevdv** [comment]
@Maggie-M thanks for checking it out! Merging now

**Comment by damianavila** [comment]
>Choropleth timeout, restarted. I think we should exclude that example from out tests for now (in another PR)

I agree...

**Pull request merged**
