### PR TITLE
Keep italics when rendering bold LaTeX variable names

### LINKED ISSUE #12531: [BUG] latex in titles - upright characters that should be italic
When LaTeX-style mathtext is used in title, it looks like many symbols are rendered upright that should be italic. This is also inconsistent with the labels, which look ok. I noticed this in these docs examples:

* https://docs.bokeh.org/en/latest/docs/examples/styling/mathtext/latex_schrodinger.html
* https://docs.bokeh.org/en/latest/docs/examples/styling/mathtext/latex_bessel.html

<details><summary>Screenshots</summary>

image
image
</details>

Also the ASCII letters and numbers that are part of the title mathtext look almost bold, which could make it hard to differentiate ones that are really supposed to be bold.

### PR DESCRIPTION
**Pull request by ianthomas23**
- [x] issues: fixes #12531
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

This fixes the bug that variables in LaTeX titles are rendered incorrectly because variables should still be italicized even when bold. See issue #12531 for examples and analysis.

There are no new tests as every test that involves a LaTeX title, and there are many, are affected by this.

I still need to visually check each of the baseline image changes, and also update some of the images in the docs, but I want to pass it through CI first.

### CODE REVIEW

**Comment by ianthomas23** [comment]
I've checked all the baseline image changes and they are all correct.

I've also update the latex example images in the docs that are affected by this fix. These probably need @bryevdv to check them on another mac as I've generated the images manually and I'm not entirely comfortable with my new retina display yet.

**Comment by mattpap** [comment]
I understand this fixed rendering of bold typesetted text. However, this doesn't look right to me (right/green is new, left/red is old; opposite of bokehjs' test reports):

image

Perhaps we should change the default to a non-bold font?

**Comment by mattpap** [comment]
Or maybe it's just this example that overuses plot title for what it looks like a block of text. Initially I thought this was a `Div`.

**Comment by ianthomas23** [comment]
> Or maybe it's just this example that overuses plot title for what it looks like a block of text. Initially I thought this was a `Div`.

Yes, it is a fabricated example to show that titles can include a mixture of latex and normal text, and over multiple lines. It is something that Bokeh supports, but we wouldn't recommend anyone doing this for say actual scientific work as it would not be appropriate.

Here we are rendering the whole title using latex, including the text. We could do a better job by rendering the text as normal and only the equations using latex. But I've just tried it and we don't support it, the titles has to have the `"$$"` at the very start and end of the string or it doesn't work. I remember some discussion about compound labels/titles containing normal text and latex but I assume that is still on a wishlist.

**Comment by mattpap** [comment]
I think I would just change this example to use a normal font, especially given that (most likely) we don't have any title tests that would use a different style of font.

**Comment by ianthomas23** [comment]
Yes, I'll do that.

The more I think about this the less clear situation becomes! One shouldn't really apply bold to equations in general because a bold mathematical symbol usually means a vector rather than scalar quantity. So a bold title containing both text and equations should probably have the text in bold but the equations not. But then in the latex you can have a `\text{Some text}` to drop back to text, so we'd have to think about whether that should be bold or not. So let's just get this italicising fixed and we can delay dealing with bold or not until we have full support for compound text and equations.

**Comment by mattpap** [comment]
There is however slight concern with repeated changes to many images regarding the repository size. So, baseline images are actually a small contributor in this case, but's going on with docs' images:

image

**Comment by bryevdv** [comment]
I've been running all these thumbnail images through av optimizer first, before adding them. Perhaps that's the difference?

**Comment by ianthomas23** [comment]
I can see if I can make the doc images smaller without reducing perceived quality.

**Comment by ianthomas23** [comment]
If you remove the bold from the title using `p.title.text_font_style = "italic"` then only the first line is rendered correctly, the other 2 lines are still in bold.
err

It looks like we have two options:

1. Leave this fix as it is, leave the title as bold, and return to this later to fix the various latex multiline and style problems.
2. Close this without merging, and fix it all at in one go later.

I'd probably opt for 2 as at least that will minimise the repo image churn.

**Comment by mattpap** [comment]
It's just one test case, so let's leave it as-is, open an issue and fix it later.

**Comment by mattpap** [comment]
Still if you could optimize those large png files before merging.

**Comment by ianthomas23** [comment]
Example images compressed via Linux command line using `pngquant`. Files are much smaller and still look OK to me.

**Pull request merged**
