### PR TITLE
fix for https://github.com/bokeh/bokeh/issues/6822

### PR DESCRIPTION
**Pull request by AaronWatters**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [ ] issues: https://github.com/bokeh/bokeh/issues/6822
- [ ] tests passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap do you have any thoughts? Offhand it seems like this change would break standard text input property events. If this change fixes autocomplete then perhaps auto complete view should not inherit from text input view. 

In any case @AaronWatters FYI any code that is no longer needed or appropriate should be deleted, not commented out.

**Comment by AaronWatters** [comment]
Closing with intent to reopen because the travis tests timed out...

**Comment by AaronWatters** [comment]
reopening to restart travis build

**Comment by bryevdv** [comment]
ping @mattpap

**Comment by AaronWatters** [comment]
If I understand it correctly the problem is that the render() operation sometimes happens before the value is updated due to a race condition in the event handlers.  The render() has the effect of cancelling the other event since it destroys the object associated with the event (I think). Any fix that guarantees the render() happens after the value update should work.  I was not certain that the proposed changes did not adversely effect other subclasses of text_input, but I couldn't find any problems.

**Comment by bryevdv** [comment]
@AaronWatters thanks for the edit, @mattpap and I are both heads down in other work over the next week or so but we would both like to get a fix in for autocomplete before the next release (especially now that it is possible to create some selenium tests that will fully exercise these widgets under automated test). I appreciate your patience and your contribution, we will get back to you as soon as we are able.

**Comment by bryevdv** [comment]
Just as an update, waiting to look at this until after the current big WIP PR for layout is done/merged

**Comment by mattpap** [comment]
@bryevdv, given we are waiting here for the layout PR, which rewrites autocomplete widget almost from scratch, fixing isssue #6822 as a side effect, I think we can close this PR (unless we want to change the order of merges).

**Comment by bryevdv** [comment]
I'm fine with that, @AaronWatters thank you very much for taking the time to submit this. Given the other large ongoing PR work around all widgets and layout, I am going to go ahead and close this since it will be addressed in time by that work.

**Pull request closed without merging**
