### PR TITLE
Use numbro.js instead of numeral.js to fix NaN and Infinity handling.

### PR DESCRIPTION
**Pull request by dennisobrien**
This is temporarily using git://github.com/dennisobrien/numbro.git#916d3398 for the source of numbro.js.  Assuming bokeh/numbro PR3 (https://github.com/bokeh/numbro/pull/3) is fine, once that is merged, I can change the reference to numbro in package.json to point to bokeh/numbro.

This is another attempt to get this change into the release. The previous attempts in 0.10 failed due to some CI errors that I never resolved.

For reference: #3153

### CODE REVIEW

**Comment by dennisobrien** [comment]
Supersedes PR #3840 #3153 #3128 and PR #3043 and PR #3025

Addresses issues #2922 and #3120

Currently this uses the fork of numbro.js from git://github.com/dennisobrien/numbro.git#916d3398
but once bokeh/numbro#3 is merged I will change this to point to bokeh/numbro.git#COMMIT_TBD

**Comment by bryevdv** [comment]
Hi @dennisobrien just to let you know I've been seeing these go by, I'm away on travel this week, so it might be a few days before I can take a look. @mattpap may be able to provide a quicker look

**Comment by dennisobrien** [comment]
Thanks Bryan.

**Comment by dennisobrien** [comment]
Any advice on this CI build error?  There were 23 errors from this error being raised:

```
raise pytest.UsageError('Sauce Labs username must be set')
```

My guess is that this is an error in CI since that has been the case many times before.  Is there a way to force another try at the CI build?

**Comment by bryevdv** [comment]
That's a limitation of TravavisCI and forked repos. It's not giving your build access to the saucelab credentials. We are still debating the longer term possible changes or workarounds for that. Another good reason to add you to @bokeh/dev though I think. :) If you are amenable I will put that question to the team

**Comment by mattpap** [comment]
I presume this is ready. LGTM.

**Comment by mattpap** [comment]
@bryevdv, as to external contributors, one approach is to make CI ask in a PR for confirmation whether to run tests or not (confirmation happens after manual inspection of a submission). I'm not sure if you can do it with travis ci thought (I doubt it) (works e.g. with jenkins).

**Comment by dennisobrien** [comment]
@bryevdv - I'd be happy to be added to @bokeh/dev but I still have a lot to learn about the design and development of Bokeh and would still appreciate advice and review by other developers before merging.  I also don't mind waiting and putting a few more PRs under my belt first.

It would be great to get this in the next release train.  I've been using a custom patched version of 0.10 to work around this.

**Comment by mattpap** [comment]
> (...) and would still appreciate advice and review by other developers before merging.

@dennisobrien, we always review and don't allow merging otherwise, so there's no risk something very bad being merged.

**Comment by bryevdv** [comment]
@dennisobrien exactly as @mattpap says, we always review PRs, being in @bokeh/dev is mostly an aid to collaboration. Making PRs on branches of the main repo works better with our CI machinery, and also let's two people work on the same branch which is occasionally very helpful

**Comment by bryevdv** [comment]
Also I think this can definitely go in the next release. The only think I'd like to see is a little bit of documentation. There have been some questions on the mailing list, e.g. about exactly what formats are supported and I have not know where to send people. Even just a link to the Numbro docs (http://numbrojs.com/format.html) in a few appropriate places would be an OK start.

**Comment by birdsarah** [comment]
@dennisobrien can you merge in latest master so we can get rid of the integration test errors?

**Comment by dennisobrien** [comment]
I added a reference to the numbro documentation for both NumberFormatter and NumeralTickFormatter.  The reference is beneath the table of formatting examples.

E.g.
http://bokeh.pydata.org/en/0.11.1/docs/reference/models/formatters.html#bokeh.models.formatters.NumeralTickFormatter
http://bokeh.pydata.org/en/0.11.1/docs/reference/models/widgets.tables.html#bokeh.models.widgets.tables.NumberFormatter

Once the tests complete I will do the merge.

**Pull request merged**
