### PR TITLE
Allow to configure selection tool mode

### PR DESCRIPTION
**Pull request by mattpap**
The following modes are supported:

- replace (no modifiers)
- append (Shift)
- intersect (Ctrl)
- subtract (Shift+Ctrl)

Press (~300 ms) on a selection tool button (box, poly, lasso, tap) to reveal a menu where you can set the active mode or clear the current selection. Activating a mode automatically activates the associated tool, if it's currently inactive. Modifiers take precedence over selected mode.

Example:

image

For now I only covered selection tools, but this is a generic mechanism that can be used with other tools and elsewhere (e.g. context menus).

addresses #8512

### CODE REVIEW

**Comment by mattpap** [comment]
One thing to consider is that intersect and subtract modes are no-op if there is no current selection (mind no selection != empty selection). So you have to start with replace or append modes to make an initial selection and then switch to the aforementioned modes to be able to take advantage of them. If that happens, I think it may be reasonable to select all indices first and apply intersect or subtract mode selection to it. This way intersect mode would work like replace mode on the first usage, and subtract mode selection would allow to poke a hole in all indices.

**Comment by philippjfr** [comment]
>This way intersect mode would work like replace mode on the first usage, and subtract mode selection would allow to poke a hole in all indices.

Those seem like reasonable semantics.

The other thing we discussed yesterday was being able to control the select mode from Python by making it a public property. This would also be very valuable for HoloViews linked selections which are handled server side.

**Comment by mattpap** [comment]
@philippjfr, I exposed `mode` property.

**Comment by mattpap** [comment]
> Those seem like reasonable semantics.

I will implement that in another PR.

**Pull request merged**
