### PR TITLE
Split up and streamline bokeh.plotting refdocs

### LINKED ISSUE #11428: Reorganize bokeh.plotting in ref guide
Currently, all glyph methods of [bokeh.plotting.figure](https://docs.bokeh.org/en/latest/docs/reference/plotting.html) are on one single page in the reference guide. This means that the page is extremely long and takes a long time to load.

As discussed with @bryevdv, we would like to find a way to reorganize this information, probably creating individual subpages for all of the glyph methods (similar to how [bokeh.models](https://docs.bokeh.org/en/latest/docs/reference/models.html) is currently organized).

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #11428
- [x] release document entry (if new feature or API change)

This PR: 

* removes the duplication of enormous (rendered) docstrings for figure/Figure and gmap/GMap
* removes the live examples in every glyph method (now static code block)
* splits chapter into figure, gmap, and helpers sub chapters
* removes some cruft junk showing up in every model class that does not concern users
* fixes a mis-render of property links for `Instance` and `Null` properties
* The intentional transitive imports in `bokeh.plotting` (e.g. show, output_file, etc)  aree documented

I'm not sure how much more time I will have to devote to this. Some things that could use a little attention:

* The top level page for `bokeh.plotting` and also for all the subpages have no narrative text. A small paragraph would likely improve

This PR does not go as far as splitting up every glyph method. That would be a very large undertaking, really merit some kind of automation, and I am somewhat on the fence about it. I would like to try to find a way to condense enormous duplication in the glyphy method docs without sacrificing the "reference" quality of the reference guide. But there is still lots of room for improvement, even with the changes above the smaller pages are still quite large.

### CODE REVIEW

**Comment by bryevdv** [comment]
I also pushed a change to condense default/type info for properties:

## before

Screen Shot 2021-09-05 at 16 12 10

## after 

Screen Shot 2021-09-05 at 16 20 58

---

Given that there are thousands of properties. this actually saves a non-trivial amount of vertical space and page weight. Also I think it reads easier.

**Comment by bryevdv** [comment]
Another change: I made it so that glyhp method defaults that were showing up as `{'field': 'x'}` etc now just show up as `"x"`. Although it is a fib, it is only a slight one since we automatically convert the latter into the formers, and the latter is what users will normally experience almost all the time, and it also just makes the docstring far more readable (the interposed dicts were just un-parseable by humans). 

## before 
Screen Shot 2021-09-05 at 19 08 37


## after 

Screen Shot 2021-09-05 at 19 08 04

**Comment by bryevdv** [comment]
Also note I've submitted a theme issue about the bad rendering of the parameters headings: https://github.com/pydata/pydata-sphinx-theme/issues/464

**Review by tcmetzger — APPROVED** [review]
This looks great! I built the docs locally and took a look around. I agree that it would be nice to have short intros for the .rst files - especially for plotting.rst which currently renders as a mostly empty page. However, that should not stop us from merging that for 2.4, I think!

**Pull request merged**
