### PR TITLE
get_reference_point can look up and index (w/tests)

### PR DESCRIPTION
**Pull request by birdsarah**
Add capacity for get_reference_point to look-up an index based on a field and value. This is currently not used as only call to get_reference_point does not yet take advantage of this feature.

Partially fixes: #3856

Should be merged after #5087

### CODE REVIEW

**Comment by bryevdv** [comment]
@birdsarah is this the second PR that should merged?

**Comment by birdsarah** [comment]
Yes.

**Comment by birdsarah** [comment]
#5087, #5088 (this) and #5089 are the chained three. #5090 is independent.

**Comment by bryevdv** [comment]
conflicts after merging #5087

**Comment by birdsarah** [comment]
@bryevdv - merge when green?

**Pull request merged**
