### PR TITLE
Pan the webpage on touch pan events when no tools are selected

### LINKED ISSUE #5918: Touch scroll the page when no tools are active
# Version :

Tested on Bokeh 0.12.3.

# Expected behavior :
When no tools are active in the toolbar and you slide your finger up and down starting on a plot on an Android Tablet, the web page should scroll up and down.

# Observed behavior :
The page does not scroll.

# My solution :

1. Change the default Hammer option touchAction from TOUCH_ACTION_COMPUTE to TOUCH_ACTION_PAN_Y.
2. if a 'pan' event_type is received, call preventDefault on the event (code in bold below).

<pre>
UIEvents.prototype._trigger_event = function(event_type, active_tool, e) {
    if (active_tool.active === true) {
      if (event_type === 'scroll') {
        e.preventDefault();
        e.stopPropagation();
      }<b>
      if (event_type === 'pan') {
        e.preventDefault();
      }</b>
      return this.trigger(event_type + ":" + active_tool.id, e);
    }
  };
</pre>

# References :
https://github.com/hammerjs/hammer.js/issues/241
https://github.com/hammerjs/hammer.js/wiki/How-to-fix-Chrome-35--and-IE10--scrolling-(touch-action)

# Discussion

When using Bokeh on a tablet, I disable all the tools by default and I want the page to scroll using touch when no tools are selected. I use long webpages with a Bokeh plot at the top that takes almost all width and can take more than the screen height. I plot large Gantt charts using quad glyphs.

I leave the proper implementation to the more experienced Bokeh developpers. I don't have a deep enough understanding of Bokeh to be sure that the above fix does not break something else.

### PR DESCRIPTION
**Pull request by samaust**
issues: fixes #5918

### CODE REVIEW

**Comment by bryevdv** [comment]
@samaust Thanks for the PR! I'm extremely time constrained the next week (new job) but I would love to get this in 1.1 if possible. Do you have a test script/page that you tested this with?  Can you put the output HTML somewhere publicly reachable so that I can check it on some tablets we have? That would be am immense help to accelerate evaluation of this PR

**Comment by samaust** [comment]
I made a simple Django project that serves a Bokeh plot to test this
https://github.com/samaust/bokeh_mobile_tests

**Comment by bryevdv** [comment]
OK there are some JS unit tests failing so this will require a deeper look, we will plan to pick it up after the 1.1 release.

**Comment by bryevdv** [comment]
@samaust FYI all the JS test failures look like this:

>  1) ui_events module
       _event methods
         _pan_start method should handle panstart event:
     TypeError: srcEvent.preventDefault is not a function
      at UIEvents._trigger (build/js/lib/core/ui_events.js:262:30)
      at UIEvents._pan_start (build/js/lib/core/ui_events.js:355:14)
      at Context.it (test/core/ui_events.ts:382:21)

I'm not sure what the proximate cause is offhand, I won't be able to look more deeply until the weekend (unless you get to it first)

**Comment by bryevdv** [comment]
@samaust Good catch, I didn't realize the objects were mocked in the tests themselves. This is almost there, but now there are just a few TS linter failures:

> [02:43:57] ERROR: 377:45  object-literal-shorthand  Expected method shorthand in object literal ('{preventDefault() {...}}').
[02:43:57] ERROR: 378:46  semicolon                 Unnecessary semicolon
[02:43:57] ERROR: 393:45  object-literal-shorthand  Expected method shorthand in object literal ('{preventDefault() {...}}').
[02:43:57] ERROR: 394:46  semicolon                 Unnecessary semicolon
[02:43:57] ERROR: 409:45  object-literal-shorthand  Expected method shorthand in object literal ('{preventDefault() {...}}').
[02:43:57] ERROR: 410:46  semicolon                 Unnecessary semicolon
[02:43:57] ERROR: 559:48  object-literal-shorthand  Expected method shorthand in object literal ('{preventDefault() {...}}').
[02:43:57] ERROR: 560:46  semicolon                 Unnecessary semicolon
[02:43:57] ERROR: 568:48  object-literal-shorthand  Expected method shorthand in object literal ('{preventDefault() {...}}').
[02:43:57] ERROR: 569:46  semicolon                 Unnecessary semicolon

I appreciate your working through this issue, as I mentioned in the issue things are much quicker/easier for the person with the right experience, so your help is very appreciated!

**Comment by samaust** [comment]
I just pushed a commit. 

Before accepting the PR, I strongly suggest to test on mobile manually and make sure the behavior is as intended with all the tools active and inactive and all the touch and mouse gestures.

I tested on safari on iOS. 
* When all tools are inactive, a slow touch and drag of the finger causes a scroll of the webpage. 
* When the pan tool is active, a slow touch and drag of the finger causes a pan of the plot. 
* When the pan tool is active, a quick up or down touch causes a swipe and that causes a vertical scroll of the webpage.

The tests might need to be updated. You might want to test that srcEvent.preventDefault() is only called when the pan tool is active.

**Comment by bryevdv** [comment]
@philippjfr @jlstevens this seems like a nice PR to get in, if either of you has time to actually test manually on mobile and browser.

**Comment by bryevdv** [comment]
@samaust I took a quick look at the django app but even after correcting for the windows path sep difference, the directories to copy to did not exist. I'm not sure if this is expected or not, and I don't really know anything about django at all to try and speculate or debug. This is definitely more of an effort than I can look into further right now. However, I'd love to merge this PR for the next release. What would be necessary is a static HTML output that exercises the change, created with inline resources (i.e with `BOKEH_RESOURCES=inline`), hosted somewhere public that could be inspected/tested.

**Comment by samaust** [comment]
@bryevdv I added the directories to copy to. Testing locally is useful vs online because you can connect the tablet to the pc by usb and use remote debugging. On an iPad, you enable Safari Web Inspector, then you use a tool on pc to inspect the Safari webpage.

**Comment by bryevdv** [comment]
Ok now 1.1 is out so I am just going to merge this and cut a dev build, which will deploy a dev version of the docs, which I can inspect easily on mobile devices. If there's an issue there is plenty of time to revert or fix.

**Pull request merged**
