### PR TITLE
Canavandl/pin build deps

### PR DESCRIPTION
**Pull request by canavandl**
potential hotfix

### CODE REVIEW

**Comment by canavandl** [comment]
This pins to:

conda=4.1.11 
conda-env=2.5.2 
conda-build=1.21.14

and seems to work (I, poorly, added a line to echo the contents of the noarch build dir):
https://travis-ci.org/bokeh/bokeh/jobs/161837104#L966

To prevent this regression, we should probably add a travis_install line that checks that the noarch build files exist, and break/kill the build (before installing the build and running the tests) if not.

**Comment by canavandl** [comment]
Added logic to check that noarch package exists in expected location and will fail build if not.

screen shot 2016-09-22 at 10 56 22 am

confirmed to work here: https://travis-ci.org/bokeh/bokeh/jobs/161949273#L935

**Comment by canavandl** [comment]
confirmed to pass when the build files exist:

screen shot 2016-09-22 at 11 01 55 am

https://travis-ci.org/bokeh/bokeh/jobs/161954666#L973

**Comment by damianavila** [comment]
I would love to see actually some code looking for the bokeh package you just build... but this could be a temporary fix, if you want... in case of this one being accepted, please open an issue to track an enhancement later.

**Comment by canavandl** [comment]
I'm going to merge and open an enhancement issue about writing a better noarch check. thanks for the review @damianavila

**Pull request merged**
