### PR TITLE
Image diff based on committed set of baselines

### LINKED ISSUE #5800: Hard pass/fail test of some kind of basic glyph drawing
The examples reports are useful but are no substitute for automation. The project needs test(s) for basic glyph drawing that will actually result in a hard failure if results are not pixel-matched to expected results. 

To start, perhaps this could be a single large plot with no grids, axes, toolbar, etc, that simply draws a few representatives of each glyph. This does not give fine resolution into problems immediately, but would be a "canary in the coalmine" that at least indicates when *some* problem with basic rendering has been introduced.

### PR DESCRIPTION
**Pull request by mattpap**
This currently only affects `node make test:integration`. The set of baseline images was committed along existing textual baselines (`bokehjs/test/baselines`). The total size of artifacts is 300 kB for textual baselines and 650 kB for images (roughly 9 kB per image per test). The testing procedure is the same as with textual baselines. A committed baseline (text/image) is compared with the working tree, where each baseline was overwritten by the test framework. If there's a difference, then it will be visible both in test output and git. Textual baselines are compared with `git diff` and images by simple pixel-by-pixel comparison. The test framework generates `report.json`, which contains tests' metadata and base64 encoded images (baseline, diff, current). The report and all modified (or new) baselines are stored as `integration-report` artifact in github actions, which can be downloaded and the report visualized, and baselines copied-over to deal with platform differences. To view the report, one needs to start devtools server (`node test/devtools server`) and go to `localhost:5777/integration/report`. 

Currently image diff tests randomly fail (at least locally) on certain widget tests. Round corners of buttons and inputs are affected. This weird and requires further investigation.

addresses #5800

### CODE REVIEW

**Comment by bryevdv** [comment]
>  To view the report, one needs to start devtools server (node test/devtools server) and go to localhost:5777/integration/report.

Just being able click or copy/paste a link in the build log to see the report immediately and directly is an important feature for me. I wish we would make proposals and have discussions for changes like this.

**Comment by mattpap** [comment]
> Just being able click or copy/paste a link in the build log to see the report immediately and directly is an important feature for me.

I don't disagree. The problem is of technical nature. With the implementation in this PR, we don't need external storage like S3, thus we don't have issues with credentials, among other things, and external contributors can finally participate in image diff testing. Given that you have to download something anyway, then starting a server (which btw. can work continuously in the background, because it uses a different port than the server used in `test` task) and rendering the json report, shouldn't be too inconvenient, and the advantages of having data separated from presentation should be fairly obvious. If github allows to upload single file artifacts without zipping, then generating HTML report in CI will make much more sense. I suppose the report could be generated anyway, but you would need to unzip it, so not that much more convenient. Though the current approach isn't that direct either, given that you have to find the S3 url deep in the test logs.

**Comment by mattpap** [comment]
Another option is that github actions' annotations will allow richly formatted failure information, that could embed image diff, etc. Though that's a fairly remote option.

**Comment by bryevdv** [comment]
How about a script that fetches and displays reports locally, and a pre-constructed command displayed in the build log that will fetch and display *that* report?

**Comment by mattpap** [comment]
That's also a possibility. One caveat is that artifacts require downloader to be logged in, so we will have to use artifacts API (https://developer.github.com/v3/actions/artifacts/) with credentials.

**Comment by mattpap** [comment]
If fact we will need some scripts anyway to deal with platform differences, because it's highly unlikely that we will be able to maintain a single set of images that are reproducible outside CI on multiple platforms. Right now I can't get that working in my own VM and in my VM and on CI (the same version of Ubuntu and exactly the same version of Chromium). How bad this is, I already had a taste of in PR #9331, where simple things like setting background color to red and expecting red in a screenshot is way too much.

**Comment by mattpap** [comment]
At this point this PR is still just a prelude to fixing issue #5800, because not all platform differences are resolved and the overall testing process is not fully developed yet. For now images will be generated in CI and available for download and local comparison, but baseline images won't be committed, so tests won't be failing of visual aspects of test output change. I will finalize this over next couple weeks.

**Pull request merged**
