### PR TITLE
Fix up spectrogram

### LINKED ISSUE #4589: Spectrogram example needs fixing up
There are some small CS changes to make but also the layout needs to be fixed as well

### PR DESCRIPTION
**Pull request by bryevdv**
issues: fixes #4589

### CODE REVIEW

**Comment by bryevdv** [comment]
As of now the spectrogram runs, but the layout now looks bad:

screen shot 2016-06-19 at 1 26 47 pm

ping @birdsarah

**Comment by birdsarah** [comment]
Cool. Should be straight forward to change. We'll probably switch from using components to just using a fixed layout and a custom template to embed some of our own css (which will probably only be a background). I can take a look next week.

**Comment by birdsarah** [comment]
Feel free to open a new issue and assign me to it.

**Comment by birdsarah** [comment]
Actually, better yet, I made a comment on #4397.

**Comment by bryevdv** [comment]
I have a bokeh server version of the spectrogram in the works that is infinitely better, closing this.

**Pull request closed without merging**
