### PR TITLE
add support for server-sent events

### LINKED ISSUE #8663: Add support for data source using server-sent events
Currently bokeh uses Ajax polling or web sockets to receive data from a backend server. It would be nice to use server-sent events in some situations, since they can simplify the backend-code and are a good option for one way data streaming.

### PR DESCRIPTION
**Pull request by alhoo**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes #8663
- [ ] tests added / passed
- [x] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
appears to be spurious test failure, I've restarted

**Comment by bryevdv** [comment]
@mattpap I will merge this later today unless you want to comment

**Comment by mattpap** [comment]
Looks good.

**Comment by bryevdv** [comment]
Thanks @alhoo !

**Comment by bryevdv** [comment]
@alhoo There is now a long-running `landing-2.0` branch active for collecting changes that will happen right at 2.0 Would you be interested in submitting a PR to fix up the `RemoteDataSource` hierarchy the way we previously discussed? Since this is the last window for breaking changes for some time it would be nice to get it cleaned up

**Comment by alhoo** [comment]
I'll try to get it done this week.

**Comment by bryevdv** [comment]
@alhoo any updates on this?

**Comment by alhoo** [comment]
Yeah this too a bit longer than I hoped since I had to re-setup my dev env.

**Pull request merged**
