### PR TITLE
Improve test matrix

### LINKED ISSUE #2282: TestMatrix script not in sync with BEP 2
The issue is that we should use it to test against the RC which is installable/testable following #1107 (basically dev channel) but the script cmds do not specify the right channel for conda or pip. The result is that the script ends up always installing the previous version and doesn't correctly pick up the newest RC build.

Should be enough to change [envs](https://github.com/bokeh/bokeh/blob/master/scripts/test_matrix.py#L168) dict to add the right channel to the cmds being executed.

### PR DESCRIPTION
**Pull request by fpliger**
Issues: fixes #2282

### CODE REVIEW

**Comment by bryevdv** [comment]
`skip-tests` vs `dry-run` is pretty  confusing. Let's go ahead and strip the script down in this PR, make it much simpler and have **just** create the desired envs and not try to do anything else.

**Comment by Maggie-M** [comment]
@bryevdv That should be a fairly easy fix.  After taking out the tests, we'd just have to remove the cleaner function, which deletes the envs at the end of the script.

These changes are great, @fpliger!

**Comment by Maggie-M** [comment]
I just noticed that on line 74, **OPTIONS["channel"]** is still being passed to call_wrapper, but you've removed **OPTIONS["channel"]** from everywhere else in the script.

**Comment by bryevdv** [comment]
@fpliger any more updates to this before merging? @Maggie-M can split it into two scripts in another PR.

**Pull request merged**
