### PR TITLE
try using --self-contained-html to fix report CSS

### LINKED ISSUE #6535: py.test reports for integration tests are broken
See e.g. https://s3.amazonaws.com/bokeh-travis/246847534/tests/pytest-report.html. No CSS is applied.

### PR DESCRIPTION
**Pull request by bryevdv**
issues: fixes #6535

### CODE REVIEW

**Comment by bryevdv** [comment]
This change fixes: https://s3.amazonaws.com/bokeh-travis/247109026/examples.html

Will merge when green. Not sure what changed to make this necessary, the `pytest-html` version is the same AFAICT

**Comment by mattpap** [comment]
@bryevdv, wrong link. examples tests don't use this. Here's https://s3.amazonaws.com/bokeh-travis/247109029/tests/pytest-report.html the correct link and this doesn't fix the problem.

**Comment by bryevdv** [comment]
I'm not familiar at all with this other report. Can you link to a working one? What creates it and where?

**Comment by mattpap** [comment]
This is from integration tests' job, see https://travis-ci.org/bokeh/bokeh/jobs/247109029#L1861 (link to this report isn't very prominent at all, compared to examples tests where you get big "UPLOADED REPORT").

**Pull request merged**
