### PR TITLE
Pin sphinx to version >=5,<5.1

### PR DESCRIPTION
**Pull request by mattpap**
Otherwise fails with:
```
sphinx.errors.ExtensionError: Handler <function _process_docstring at 0x7fb3ba4ab550> for
event 'autodoc-process-docstring' threw an exception (exception: pop from an empty deque)
```

### CODE REVIEW

**Comment by bryevdv** [comment]
Rather than the failing file, it would actually be more helpful to know which extension is failing.

**Comment by mattpap** [comment]
Full traceback:
```py
Traceback (most recent call last):
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/ext/napoleon/__init__.py", line 385, in _process_docstring
    docstring = NumpyDocstring(result_lines, app.config, app, what, name,
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/ext/napoleon/docstring.py", line 1147, in __init__
    super().__init__(docstring, config, app, what, name, obj, options)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/ext/napoleon/docstring.py", line 214, in __init__
    self._parse()
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/ext/napoleon/docstring.py", line 594, in _parse
    res = self._parse_attribute_docstring()
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/ext/napoleon/docstring.py", line 626, in _parse_attribute_docstring
    _type, _desc = self._consume_inline_attribute()
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/ext/napoleon/docstring.py", line 303, in _consume_inline_attribute
    line = self._lines.popleft()
IndexError: pop from an empty deque

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/cmd/build.py", line 277, in build_main
    app.build(args.force_all, filenames)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/application.py", line 349, in build
    self.builder.build_update()
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 300, in build_update
    self.build(to_build,
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 316, in build
    updated_docnames = set(self.read())
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 423, in read
    self._read_serial(docnames)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 444, in _read_serial
    self.read_doc(docname)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 497, in read_doc
    publisher.publish()
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/io.py", line 104, in read
    self.parse()
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/parsers.py", line 78, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/docutils/statemachine.py", line 240, in run
    context, next_state, result = self.check_line(
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/docutils/statemachine.py", line 452, in check_line
    return method(match, context, next_state)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2779, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/docutils/statemachine.py", line 240, in run
    context, next_state, result = self.check_line(
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/docutils/statemachine.py", line 452, in check_line
    return method(match, context, next_state)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2352, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2364, in explicit_construct
    return method(self, expmatch)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2101, in directive
    return self.run_directive(
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2151, in run_directive
    result = directive_instance.run()
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/ext/autodoc/directive.py", line 148, in run
    documenter.generate(more_content=self.content)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 954, in generate
    self.document_members(all_members)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 830, in document_members
    documenter.generate(
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 1788, in generate
    return super().generate(more_content=more_content,
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 954, in generate
    self.document_members(all_members)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 1779, in document_members
    super().document_members(all_members)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 830, in document_members
    documenter.generate(
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 951, in generate
    self.add_content(more_content)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 602, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 547, in process_doc
    self.env.app.emit('autodoc-process-docstring',
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/application.py", line 460, in emit
    return self.events.emit(event, *args, allowed_exceptions=allowed_exceptions)
  File "/home/mateusz/conda/envs/bk_py310/lib/python3.10/site-packages/sphinx/events.py", line 105, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function _process_docstring at 0x7f6e25d6f640> for event 'autodoc-process-docstring' threw an exception (exception: pop from an empty deque)
```

**Comment by mattpap** [comment]
> (...) it would actually be more helpful to know which extension is failing.

Based on the full traceback, it's `sphinx.ext.napoleon`.

**Comment by mattpap** [comment]
It's going to be fixed in 5.1.1.

**Comment by bryevdv** [comment]
Yah if it is `sphinx.ext.napoleon` that is a sphinx bug, thanks for running this down

**Pull request merged**
