### PR TITLE
Backports for 3.4.1

### PR DESCRIPTION
**Pull request by mattpap**
This PR collects bug-fixes and tasks for a 3.4.1 release:

- [x] https://github.com/bokeh/bokeh/pull/13808
- [x] https://github.com/bokeh/bokeh/pull/13807
- [x] https://github.com/bokeh/bokeh/pull/13805
- [x] https://github.com/bokeh/bokeh/pull/13783
- [x] https://github.com/bokeh/bokeh/pull/13788
- [x] https://github.com/bokeh/bokeh/pull/13793
- [x] https://github.com/bokeh/bokeh/pull/13798
- [x] https://github.com/bokeh/bokeh/pull/13776
- [x] https://github.com/bokeh/bokeh/pull/13781
- [x] https://github.com/bokeh/bokeh/pull/13775
- [x] https://github.com/bokeh/bokeh/pull/13818
- [x] https://github.com/bokeh/bokeh/pull/13819 
- [x] https://github.com/bokeh/bokeh/pull/13821
- [x] https://github.com/bokeh/bokeh/pull/13820
- [x] 3.4.1 release notes
- [x] updated switcher.json

Release checklist:

- [x] do **not** squash merge

### CODE REVIEW

**Comment by bryevdv** [comment]
someone pointed out that 3.3.x release notes are currently missing (there may be an issue as well but I'm afk and can't search easily right but)

**Comment by mattpap** [comment]
> someone pointed out that 3.3.x release notes are currently missing (there may be an issue as well but I'm afk and can't search easily right but)

Indeed it's missing. I also need to fix this https://github.com/bokeh/bokeh/issues/13725 issue.

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
Switcher needs to be manually uploaded to AWS. It's easy but I can't do it just at the moment, I will try to later today

**Comment by bryevdv** [comment]
S3 upload and CDN invalidation are complete FYI @mattpap I usually only leave one latest release in `switcher.json` for each minor branch level. I don't think we need to worry about changing it until/unless there is a 3.4.2 though.

**Pull request merged**
