### PR TITLE
use numbro.js from bokeh/numbro for fix formatting issues with NaN and Infinity

### PR DESCRIPTION
**Pull request by dennisobrien**
Supersedes PR #3128 and PR #3043 and PR #3025

Addresses issues #2922 and #3120 

This uses the fork of numbro.js from git://github.com/bokeh/numbro.git#37dd9fe

### CODE REVIEW

**Comment by dennisobrien** [comment]
The CI job is failing with the error:
```
+conda config --add channels bokeh
scripts/travis_install: line 32: conda: command not found
The command "scripts/travis_install" failed and exited with 127 during .
```

Possibly related, PR #3152 made a couple hours before this one also failed with the same error.

**Comment by bryevdv** [comment]
Actually I think that is a spurious failure, possibly related to TravisCI caching (seen it a few other times recently) I have restarted the build. Thanks for you patience @dennisobrien Can you remind me, is this is a drop-in replacement for numeral.js, are there any example or documentation updates that are needed?

**Comment by dennisobrien** [comment]
Thanks for fixing the build @bryevdv 

This is a drop-in replacement for Numeral.js.  No changes in documentation.  I ran across fork when Numeral.js threw exceptions when formatting columns with JavaScript Infinity or NaN in them.  Their changelog since forking from Numeral.js does not mention any formatting or API changes.
https://github.com/foretagsplatsen/numbro/blob/develop/CHANGELOG.md

**Comment by bryevdv** [comment]
That's awesome. OK ping @bokeh/core I'd like to merge this as-is. @mattpap @mistakevin any thoughts? Otherwise I will merge in a few hours.

**Comment by bryevdv** [comment]
@dennisobrien @mistakevin looks like there is still a small issue remaining, I tried the code from #3120 and get this error:

screen shot 2015-11-18 at 5 20 59 pm

screen shot 2015-11-18 at 5 20 41 pm

**Comment by dennisobrien** [comment]
Ugh.  I just verified the issue you reported.  I'll look at this tonight and make sure I have tested all the entry points.

**Comment by dennisobrien** [comment]
It looks like `defaultLanguage` was changed to `currentCulture` in Numbro.js.  I'll make a PR in the fork @mistakevin created, then update this PR to use that version.

**Comment by dennisobrien** [comment]
It looks like the change from `language` to `culture` in Numbro.js is more involved that I thought.  Previous language codes were strings like "en", now they are "en-US".  The current NumberFormatter (and several other classes) have default value of "en" for `language`, so more testing will be needed.  I was hoping I could knock this out tonight, but it looks like it will have to wait for the weekend.

**Comment by bryevdv** [comment]
@dennisobrien no worries, thanks for working on this!

**Comment by dennisobrien** [comment]
I just made a PR to the bokeh/numbro fork to fix this.
https://github.com/bokeh/numbro/pull/1

I tested this change and again with 0.10.0.

With 0.10.0, passing any language other than "en" results in a JavaScript error 
```
Uncaught TypeError: Cannot read property 'delimiters' of undefined
```

With this PR, passing other locales do not result in a JS error, but every locale falls back to "en-US".  Not ideal, but it's not a new regression as far as I can tell.

Here is some code for a Jupyter notebook to test other locales.
```
from bokeh.io import output_notebook
output_notebook()

from bokeh.enums import NumeralLanguage
from bokeh.io import show
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, TableColumn, NumberFormatter
from ipywidgets import interact
import numpy as np
import pandas as pd

@interact(locale=NumeralLanguage._values)
def display_table_with_locale(locale='en'):
    df = pd.DataFrame(
        data=[
            [1, 2, 3], 
            [1,2,3], 
            [10000, 20000, 30000]
        ], 
        columns=['x', 'y', 'z']
    )
    source = ColumnDataSource(df)
    columns = [
        TableColumn(field='x', title='x', formatter=NumberFormatter(format="$0,.0", language=locale)),
        TableColumn(field='y', title='y', formatter=NumberFormatter(format="$0,.0", language=locale)),
        TableColumn(field='z', title='z', formatter=NumberFormatter(format="$0,.0", language=locale)), 
    ]
    data_table = DataTable(source=source, columns=columns, editable=False)

    show(data_table)

display_table_with_locale()
```

It would be great to add locale support to the formatting in a future PR.

**Comment by dennisobrien** [comment]
I made the change to use the updated version of bokeh/numbro (thanks @mistakevin ) but I'm getting strange test failures.  The first failure is "PhantomJS has crashed." so all the other oddities might be related to that.  If someone can restart the Travis build I would appreciate it.  If this error persists I'll look into it, perplexing as it is.

**Comment by bryevdv** [comment]
I've restarted

**Comment by dennisobrien** [comment]
Another build error.  Not sure if it is real or not, but I'll take a look tonight.

```
>>> Testing /home/travis/build/bokeh/bokeh/examples/glyphs/airports_map.py ...
Wrote airports_map.html
Shutting down bokeh-server ...
Shutting down ipython-notebook ...
Traceback (most recent call last):
  File "/home/travis/build/bokeh/bokeh/tests/travis/test", line 613, in <module>
    result = test_example(example, flags)
  File "/home/travis/build/bokeh/bokeh/tests/travis/test", line 366, in test_example
    result = json.loads(proc.stdout.read().decode("utf-8"))
  File "/home/travis/miniconda/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/home/travis/miniconda/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 20 column 1 (char 479 - 2045)
```
...
```
=================================== FAILURES ===================================
__________________________ TestExamples.test_examples __________________________
self = <travis.test_examples.TestExamples testMethod=test_examples>
    def test_examples(self):
        script = join(dirname(__file__), "test")
        proc = subprocess.Popen(["python", script])
>       self.assertEqual(proc.wait(), 0, "examples do *NOT* work properly")
E       AssertionError: examples do *NOT* work properly
tests/travis/test_examples.py:22: AssertionError
```

**Comment by bryevdv** [comment]
This perhaps seems like it might be a real issue. @fpliger the failure is in the airports map demo, can you comment?

**Comment by dennisobrien** [comment]
The test is failing on parsing the output to stdout from the phantomjs line.  The fact that it is failing on line 2 of the JSON suggests that it expects one JSON object but the output is actually one JSON object per line.  I'm just speculating since I haven't run the tests locally to see the output myself.

```
ValueError: Extra data: line 2 column 1
```

I'm also baffled why the Python 3.4 version passed but the 2.7 version failed.

**Comment by dennisobrien** [comment]
My wife and I are in the hospital having our first baby! So I won't get a chance to look deeper into this for a few weeks. I was hoping I could get this into the 0.11.0 release but it might have to wait. Pardon my radio silence for the next few weeks and thanks to all for the help in getting my feet wet with contributing to Bokeh.

**Comment by bryevdv** [comment]
Congratulations! I think we may end up pushing the 0.11 release until after the holidays, in any case we look forward to your future contributions when you have time again!

**Comment by bryevdv** [comment]
@dennisobrien I'm going to go ahead and close this one for now, in the interest of cleaning up our PR list, since you will be away for a while. We can re-open it again any time you are ready!

**Pull request closed without merging**
