### PR TITLE
Remove as much of src/vendor as is practical

### PR DESCRIPTION
**Pull request by tswicegood**
There's still some room for improvement, but those are going to require more handholding to get through.

### CODE REVIEW

**Comment by hhuuggoo** [comment]
how does this work - when we do the build it gets loaded in via npm?

**Comment by bryevdv** [comment]
Yes

**Comment by tswicegood** [comment]
Hey @hhuuggoo -- some of these pieces were already being pulled via `npm`, other's weren't.  That's why the PR is kind of spotty as to what has code that was added in addition to being removed and so on.

**Comment by damianavila** [comment]
Just for quick reference, this PR was merged into #2109, not master...

**Comment by mattpap** [comment]
Among other things, numeraljs in vendor was customized version that was about to be moved to `src/coffee`. You have to bring this back. Having all dependencies in vendor was intentional, it would have been nice to first discuss going back to npm.

**Comment by bryevdv** [comment]
@tswicegood can you restore the old numeraljs today? I will update the test to mocha. @mattpap having all the dependencies in vendor was an unfortunate compromise, I'm not sure I'd call it intentional.

**Comment by mattpap** [comment]
To follow up on numeral.js. This was a customized version, mainly with garbage removed. This was first step to rewrite numeral.js in coffeescript and then beef it up with features, see #1879.

**Comment by mattpap** [comment]
I see you also removed jquery ui. This has to be reverted as well, because this is also a customized version, that uses `bk-` prefix for CSS classes, events, etc. This is closely related to UI's CSS files which where modified as well. You could prefix CSS automatically (at least in less), but prefixing in JS is (I believe) beyond any automation. Note also that bootstrap was patched as well. I will give `git log` a shot to see if other dependencies didn't receive some special treatment as well (I recall some more).

**Comment by mattpap** [comment]
> having all the dependencies in vendor was an unfortunate compromise, I'm not sure I'd call it intentional.

Perhaps at the beginning it was incidental, but I maintained `vendor` this way on purpose. The main reason is that we often needed/need modified versions of dependencies. Secondly I distrust npm on multiple levels, I would like to see its usage reduced in the company, not increased.

**Comment by bryevdv** [comment]
What all do we use jqui for btw? I would love to get rid of it entirely

**Comment by hhuuggoo** [comment]
definitely sliders, possibly the date picker, not sure what else

**Comment by mattpap** [comment]
And date/range sliders, slick grid and perhaps more.

**Comment by bryevdv** [comment]
OK, well it was a pleasant wishful thought.

**Comment by tswicegood** [comment]
Sorry for silence here -- been heads down in my editor the last few days at a computer.  I'm massively :+1: on removing any dependencies on jQuery UI.  In many cases there are better alternatives and the pain it brings as a library tend to outweigh the benefits.

--- 

> You could prefix CSS automatically (at least in less), but prefixing in JS is (I believe) beyond any automation.

There is a way to do it.  It's a little clunky, but if avoids having to maintain an entirely patched version of jQuery UI.  You can see the code in [this commit][1] and the [final implementation here][2].  As noted in #2109, I think we probably should adjust the various `View` objects' `render` method to do that before returning.

> I will give git log a shot to see if other dependencies didn't receive some special treatment as well (I recall some more).

This one's on me.  I should have checked rather than assuming they were simply copied in.  That's one of the dangers of having a `vendor/some_lib-X.Y.Z` directories, however.  It makes it easy to assume that it's simply a drop-in.

> Perhaps at the beginning it was incidental, but I maintained vendor this way on purpose. The main reason is that we often needed/need modified versions of dependencies.

A better route to go here is to fork the project.  Packaging in JavaScript is pretty decent at this point and npm is perfectly happen to install from a Git repository.  Once we get #2109 merged and have everything running through Browserify, there's little reason to keep these forks inside the main repository.  This let's us pull those libraries across other tools as we need them.

Take Numeral for example.  It's reasonable to think that we might want to use that in other places.  Any project that deals with numbers and their display should format them so they look good.  Having a Bokeh specific version of Numeral that's not immediately accessible outside of the project means that developers would need to know both the publicly documented Numeral package that they can use *and* the internal one for Bokeh.

The fork route also affords us the opportunity to contribute back to the community as a whole.  Are the changes you've made to Numeral so vastly different that they need to be a separate project?  I only feel like I have a cursory understanding of the changes that have been made, so I don't know.  The ability to set a language at format time seems like an extremely valuable change.

All that said, we need to be very careful about forking projects because we want little tweaks here and there (especially if they can be adjusted at runtime the way I did jQuery UI or simply wrapped in an API that provides the facade that makes interaction easier).

Forking a project makes it much much harder to merge in future fixes and enhancements that they will undoubtedly create.  We become responsible for maintaining those fixes and changes and making sure they fit with the changes we've made.  In short, we take on all of the technical debt of the project and remove a lot of the benefit of using open source / third-party libraries.

> Secondly I distrust npm on multiple levels, I would like to see its usage reduced in the company, not increased.

Could you elaborate here?  npm is two distinct things: a package manager and repository of packages.  The former is not something that can be escaped when doing JavaScript.  The community's tried building alternatives (Require.js, Bower, and so on), but ended up back to npm for package management because it's the best that there is so far.

The repository of packages on npmjs.org is another issue.  It's not as stable as it needs to be to be on the critical path for test / release.  There are [ways to mitigate][3] the issues, however, including my [docker-npm-cache][4] which sets up a simple nginx cache in a Docker instance.  It's not entirely fool-proof, but it does mean you only need one GET to make it from npmjs.org and you're set.

[1]: https://github.com/bokeh/bokeh/commit/66922c96ac39f5eb4365ee3f05ed7c547dede02a
[2]: https://github.com/bokeh/bokeh/commit/607c9204926e8d319541f570a3fcda85adebcaf7#diff-9c86689fe7bbec6c1819224ddd1c1d04
[3]: http://eng.yammer.com/a-private-npm-cache/
[4]: https://github.com/tswicegood/docker-npm-cache

**Pull request merged**
