### PR TITLE
Replace plot_width and plot_height properties 

### PR DESCRIPTION
**Pull request by satishjasthi**
issues: #10980 

 in following files

<details>
 CHANGELOG
 bokeh/command/util.py
 bokeh/core/property/alias.py
 bokeh/core/query.py
 bokeh/io/export.py
 bokeh/layouts.py
 bokeh//plots.py
 bokeh/plotting/figure.py
 bokeh/plotting/gmap.py
 bokeh/sphinxext/bokeh_plot.py
 bokeh/themes/__init__.py
 bokehjs/src/lib/api/gridplot.ts
 bokehjs/src/lib//plots/plot.ts
 docker-tools/hello_nodejs.py
 examples/app/clustering/theme.yaml
 examples/app/crossfilter/main.py
 examples/app/dash/main.py
 examples/app/faces/main.py
 examples/app/fourier_animated.py
 examples/app/gapminder/main.py
 examples/app/movies/main.py
 examples/app/ohlc/main.py
 examples/app/ohlc/theme.yaml
 examples/app/population.py
 examples/app/selection_histogram.py
 examples/app/simple_hdf5/main.py
 examples/app/sliders.py
 examples/app/spectrogram/main.py
 examples/app/stocks/main.py
 examples/app/taylor.py
 examples/app/weather/main.py
 examples/custom/latex_extension_base/latex_extension_base.py
 examples/custom/latex_extension_full/latex_extension_full.py
 examples/embed/arguments/bokeh_server.py
 examples/embed/embed_multiple.py
 examples/embed/embed_multiple_responsive.py
 examples/embed/embed_responsive_width_height.py
 examples/embed/file_html.py
 examples/embed/json_item.py
 examples/embed/json_item_themed.py
 examples/howto/Categorical Data.ipynb
 examples/howto/Linked panning.ipynb
 examples/howto/MultiPolygons.ipynb
 examples/howto/Range update callback.ipynb
 examples/howto/ajax_source.py
 examples/howto/layouts/dashboard.py
 examples/howto/layouts/manual_grid.py
 examples/howto/layouts/words_and_plots.py
 examples/howto/notebook_comms/Basic Usage.ipynb
 examples/howto/notebook_comms/Jupyter Interactors.ipynb
 examples/howto/patch_app.py
 examples/howto/server_auth/app.py
 examples/howto/server_sent_events_source.py
 examples/integration/annotations/band.py
 examples/integration/annotations/label.py
 examples/integration/annotations/label_set.py
 examples/integration/annotations/title.py
 examples/integration/annotations/whisker.py
 examples/integration/axes/cat_labels_rotate.py
 examples/integration/embed/css_grid_simple.py
 examples/integration/embed/css_grid_simple_no_extend.py
 examples/integration/embed/referencing_roots.py
 examples/integration/glyphs/categorical_multi_glyphs.py
 examples/integration/glyphs/frame_clipping_multi_backend.py
 examples/integration/glyphs/log_scale_multi_backend.py
 examples/integration/glyphs/rect_log_axis.py
 examples/integration/layout/grid_axis_alignment.py
 examples/integration/layout/grid_axis_alignment_nested.py
 examples/integration/layout/grid_axis_alignment_no_toolbar.py
 examples/integration/layout/plot_fixed_frame_size.py
 examples/integration/plots/no_border_or_background_fill.py
 examples//file/anscombe.py
 examples//file/calendars.py
 examples//file/choropleth.py
 examples//file/colors.py
 examples//file/data_tables.py
 examples//file/dateaxis.py
 examples//file/daylight.py
 examples//file/donut.py
 examples//file/gauges.py
 examples//file/graphs.py
 examples//file/iris.py
 examples//file/iris_splom.py
 examples//file/latex_extension.py
 examples//file/legends.py
 examples//file/maps_cities.py
 examples//file/panels.py
 examples//file/tile_source.py
 examples//file/toolbars2.py
 examples//file/trail.py
 examples//file/widgets.py
 examples/plotting/file/airports_map.py
 examples/plotting/file/aspect.py
 examples/plotting/file/bar_basic.py
 examples/plotting/file/bar_colormapped.py
 examples/plotting/file/bar_colors.py
 examples/plotting/file/bar_dodged.py
 examples/plotting/file/bar_intervals.py
 examples/plotting/file/bar_mixed.py
 examples/plotting/file/bar_nested.py
 examples/plotting/file/bar_nested_colormapped.py
 examples/plotting/file/bar_pandas_groupby_colormapped.py
 examples/plotting/file/bar_pandas_groupby_nested.py
 examples/plotting/file/bar_sorted.py
 examples/plotting/file/bar_stacked.py
 examples/plotting/file/bar_stacked_grouped.py
 examples/plotting/file/bar_stacked_split.py
 examples/plotting/file/burtin.py
 examples/plotting/file/candlestick.py
 examples/plotting/file/categorical_scatter_jitter.py
 examples/plotting/file/choropleth.py
 examples/plotting/file/color_data_map.py
 examples/plotting/file/color_sliders.py
 examples/plotting/file/custom_datetime_axis.py
 examples/plotting/file/custom_tooltip.py
 examples/plotting/file/customjs_transform.py
 examples/plotting/file/dynamic_color_mapping.py
 examples/plotting/file/eclipse.py
 examples/plotting/file/elements.py
 examples/plotting/file/fixed_axis.py
 examples/plotting/file/glyphs.py
 examples/plotting/file/graphs.py
 examples/plotting/file/grid.py
 examples/plotting/file/hatch_custom_image.py
 examples/plotting/file/hatch_grid_band.py
 examples/plotting/file/hatch_patterns.py
 examples/plotting/file/histogram.py
 examples/plotting/file/hover_glyph.py
 examples/plotting/file/interactive_legend.py
 examples/plotting/file/jitter.py
 examples/plotting/file/legend.py
 examples/plotting/file/les_mis.py
 examples/plotting/file/linked_brushing.py
 examples/plotting/file/linked_panning.py
 examples/plotting/file/multi_legend.py
 examples/plotting/file/multi_line.py
 examples/plotting/file/periodic.py
 examples/plotting/file/pie.py
 examples/plotting/file/range_tool.py
 examples/plotting/file/rect.py
 examples/plotting/file/ridgeplot.py
 examples/plotting/file/scatter_selection.py
 examples/plotting/file/slider.py
 examples/plotting/file/sprint.py
 examples/plotting/file/stocks.py
 examples/plotting/file/text.py
 examples/plotting/file/theme_glyphs.py
 examples/plotting/file/tile_demo.py
 examples/plotting/file/unemployment.py
 examples/plotting/file/us_marriages_divorces_hover.py
 examples/plotting/file/vector.py
 examples/reference//AnnularWedge.py
 examples/reference//Annulus.py
 examples/reference//Arc.py
 examples/reference//Bezier.py
 examples/reference//Circle.py
 examples/reference//Ellipse.py
 examples/reference//HArea.py
 examples/reference//HBar.py
 examples/reference//HexTile.py
 examples/reference//ImageURL.py
 examples/reference//Line.py
 examples/reference//MultiLine.py
 examples/reference//MultiPolygons.py
 examples/reference//Oval.py
 examples/reference//Patch.py
 examples/reference//Patches.py
 examples/reference//Quad.py
 examples/reference//Quadratic.py
 examples/reference//Ray.py
 examples/reference//Rect.py
 examples/reference//Scatter.py
 examples/reference//Segment.py
 examples/reference//Step.py
 examples/reference//Text.py
 examples/reference//VArea.py
 examples/reference//VBar.py
 examples/reference//Wedge.py
 examples/reference//button_server.py
 examples/reference//checkbox_button_server.py
 examples/reference//checkbox_server.py
 examples/reference//data_table_server.py
 examples/reference//dropdown_menu_server.py
 examples/reference//multi_select_server.py
 examples/reference//radio_button_group_server.py
 examples/reference//radio_group_server.py
 examples/reference//range_slider_server.py
 examples/reference//select_server.py
 examples/reference//slider_server.py
 examples/webgl/clustering.py
 examples/webgl/line_compare.py
 examples/webgl/marker_compare.py
 sphinx/source/docs/first_steps/examples/first_steps_4_add_tools.py
 sphinx/source/docs/first_steps/examples/first_steps_4_axes_customizing.py
 sphinx/source/docs/first_steps/examples/first_steps_4_axes_logarithmic.py
 sphinx/source/docs/first_steps/examples/first_steps_4_background.py
 sphinx/source/docs/first_steps/examples/first_steps_4_bands.py
 sphinx/source/docs/first_steps/examples/first_steps_4_datetime_axis.py
 sphinx/source/docs/first_steps/examples/first_steps_4_grid_lines.py
 sphinx/source/docs/first_steps/examples/first_steps_4_plot_axis_ranges.py
 sphinx/source/docs/first_steps/examples/first_steps_4_plot_size.py
 sphinx/source/docs/first_steps/examples/first_steps_4_plot_size_responsive.py
 sphinx/source/docs/first_steps/examples/first_steps_4_resize_plot.py
 sphinx/source/docs/first_steps/examples/first_steps_4_themes.py
 sphinx/source/docs/first_steps/examples/first_steps_4_tick_formatter.py
 sphinx/source/docs/first_steps/examples/first_steps_4_toolbar.py
 sphinx/source/docs/first_steps/examples/first_steps_4_toolbar_autohide.py
 sphinx/source/docs/first_steps/examples/first_steps_4_tools.py
 sphinx/source/docs/first_steps/examples/first_steps_4_tooltips.py
 sphinx/source/docs/first_steps/examples/first_steps_5_color_mapping.py
 sphinx/source/docs/first_steps/examples/first_steps_5_vectorize_color.py
 sphinx/source/docs/first_steps/examples/first_steps_5_vectorize_color_and_size.py
 sphinx/source/docs/first_steps/examples/first_steps_6_row_layout.py
 sphinx/source/docs/first_steps/examples/first_steps_6_row_layout_responsive.py
 sphinx/source/docs/first_steps/examples/first_steps_7_export_html.py
 sphinx/source/docs/first_steps/examples/first_steps_7_export_png.py
 sphinx/source/docs/first_steps/examples/first_steps_8_filter.py
 sphinx/source/docs/first_steps/examples/first_steps_9_widgets.py
 sphinx/source/docs/first_steps/first_steps_4.rst
 sphinx/source/docs/first_steps/first_steps_9.rst
 sphinx/source/docs/user_guide/bokehjs.rst
 sphinx/source/docs/user_guide/embed.rst
 sphinx/source/docs/user_guide/examples/annotations_arrowheads.py
 sphinx/source/docs/user_guide/examples/categorical_bar_basic.py
 sphinx/source/docs/user_guide/examples/categorical_bar_colormapped.py
 sphinx/source/docs/user_guide/examples/categorical_bar_colors.py
 sphinx/source/docs/user_guide/examples/categorical_bar_dodged.py
 sphinx/source/docs/user_guide/examples/categorical_bar_intervals.py
 sphinx/source/docs/user_guide/examples/categorical_bar_mixed.py
 sphinx/source/docs/user_guide/examples/categorical_bar_nested.py
 sphinx/source/docs/user_guide/examples/categorical_bar_nested_colormapped.py
 sphinx/source/docs/user_guide/examples/categorical_bar_pandas_groupby_colormapped.py
 sphinx/source/docs/user_guide/examples/categorical_bar_pandas_groupby_nested.py
 sphinx/source/docs/user_guide/examples/categorical_bar_sorted.py
 sphinx/source/docs/user_guide/examples/categorical_bar_stacked.py
 sphinx/source/docs/user_guide/examples/categorical_bar_stacked_grouped.py
 sphinx/source/docs/user_guide/examples/categorical_bar_stacked_hover.py
 sphinx/source/docs/user_guide/examples/categorical_bar_stacked_split.py
 sphinx/source/docs/user_guide/examples/categorical_heatmap_periodic.py
 sphinx/source/docs/user_guide/examples/categorical_heatmap_unemployment.py
 sphinx/source/docs/user_guide/examples/categorical_offset.py
 sphinx/source/docs/user_guide/examples/categorical_ridgeplot.py
 sphinx/source/docs/user_guide/examples/categorical_scatter_jitter.py
 sphinx/source/docs/user_guide/examples/concepts_plotting.py
 sphinx/source/docs/user_guide/examples/data_filtering_boolean_filter.py
 sphinx/source/docs/user_guide/examples/data_filtering_group_filter.py
 sphinx/source/docs/user_guide/examples/data_filtering_index_filter.py
 sphinx/source/docs/user_guide/examples/data_linked_brushing_subsets.py
 sphinx/source/docs/user_guide/examples/data_transforming_customjs_transform.py
 sphinx/source/docs/user_guide/examples/extensions_example_latex.py
 sphinx/source/docs/user_guide/examples/extensions_example_widget.py
 sphinx/source/docs/user_guide/examples/graph_interaction.py
 sphinx/source/docs/user_guide/examples/graph_node_and_edge_attributes.py
 sphinx/source/docs/user_guide/examples/interaction_callbacks_for_hover.py
 sphinx/source/docs/user_guide/examples/interaction_callbacks_for_range_update.py
 sphinx/source/docs/user_guide/examples/interaction_callbacks_for_selections.py
 sphinx/source/docs/user_guide/examples/interaction_callbacks_for_selections_lasso_mean.py
 sphinx/source/docs/user_guide/examples/interaction_callbacks_for_tools.py
 sphinx/source/docs/user_guide/examples/interaction_callbacks_for_widgets.py
 sphinx/source/docs/user_guide/examples/interaction_callbacks_js_on_change.py
 sphinx/source/docs/user_guide/examples/interaction_colorpicker.py
 sphinx/source/docs/user_guide/examples/interaction_legend_hide.py
 sphinx/source/docs/user_guide/examples/interaction_legend_mute.py
 sphinx/source/docs/user_guide/examples/interaction_linked_brushing.py
 sphinx/source/docs/user_guide/examples/interaction_linked_panning.py
 sphinx/source/docs/user_guide/examples/interaction_linked_properties.py
 sphinx/source/docs/user_guide/examples/interaction_open_url.py
 sphinx/source/docs/user_guide/examples/interaction_tab_panes.py
 sphinx/source/docs/user_guide/examples/js_events.py
 sphinx/source/docs/user_guide/examples/layout_grid.py
 sphinx/source/docs/user_guide/examples/layout_grid_convenient.py
 sphinx/source/docs/user_guide/examples/layout_horizontal.py
 sphinx/source/docs/user_guide/examples/layout_sizing_mode_multiple.py
 sphinx/source/docs/user_guide/examples/layout_vertical.py
 sphinx/source/docs/user_guide/examples/plotting_annular_wedge.py
 sphinx/source/docs/user_guide/examples/plotting_annulus.py
 sphinx/source/docs/user_guide/examples/plotting_arcs.py
 sphinx/source/docs/user_guide/examples/plotting_arrow.py
 sphinx/source/docs/user_guide/examples/plotting_datetime_axis.py
 sphinx/source/docs/user_guide/examples/plotting_ellipses.py
 sphinx/source/docs/user_guide/examples/plotting_figure_range.py
 sphinx/source/docs/user_guide/examples/plotting_hbar.py
 sphinx/source/docs/user_guide/examples/plotting_hbar_stack.py
 sphinx/source/docs/user_guide/examples/plotting_hex_tile_basic.py
 sphinx/source/docs/user_guide/examples/plotting_image.py
 sphinx/source/docs/user_guide/examples/plotting_image_rgba.py
 sphinx/source/docs/user_guide/examples/plotting_legend_field.py
 sphinx/source/docs/user_guide/examples/plotting_legend_group.py
 sphinx/source/docs/user_guide/examples/plotting_line_missing_points.py
 sphinx/source/docs/user_guide/examples/plotting_line_multiple.py
 sphinx/source/docs/user_guide/examples/plotting_line_single.py
 sphinx/source/docs/user_guide/examples/plotting_line_steps.py
 sphinx/source/docs/user_guide/examples/plotting_log_scale_axis.py
 sphinx/source/docs/user_guide/examples/plotting_multiple_glyphs.py
 sphinx/source/docs/user_guide/examples/plotting_multipolygon_simple.py
 sphinx/source/docs/user_guide/examples/plotting_multipolygon_with_holes.py
 sphinx/source/docs/user_guide/examples/plotting_multipolygon_with_separate_parts.py
 sphinx/source/docs/user_guide/examples/plotting_multipolygons.py
 sphinx/source/docs/user_guide/examples/plotting_patch_missing_points.py
 sphinx/source/docs/user_guide/examples/plotting_patch_multiple.py
 sphinx/source/docs/user_guide/examples/plotting_patch_single.py
 sphinx/source/docs/user_guide/examples/plotting_ray.py
 sphinx/source/docs/user_guide/examples/plotting_rectangles.py
 sphinx/source/docs/user_guide/examples/plotting_rectangles_rotated.py
 sphinx/source/docs/user_guide/examples/plotting_scatter_circle.py
 sphinx/source/docs/user_guide/examples/plotting_scatter_square.py
 sphinx/source/docs/user_guide/examples/plotting_segments.py
 sphinx/source/docs/user_guide/examples/plotting_slope.py
 sphinx/source/docs/user_guide/examples/plotting_title_additional.py
 sphinx/source/docs/user_guide/examples/plotting_title_basic.py
 sphinx/source/docs/user_guide/examples/plotting_title_location.py
 sphinx/source/docs/user_guide/examples/plotting_title_toolbar.py
 sphinx/source/docs/user_guide/examples/plotting_title_visuals.py
 sphinx/source/docs/user_guide/examples/plotting_varea.py
 sphinx/source/docs/user_guide/examples/plotting_varea_stack.py
 sphinx/source/docs/user_guide/examples/plotting_vbar.py
 sphinx/source/docs/user_guide/examples/plotting_vline_stack.py
 sphinx/source/docs/user_guide/examples/plotting_wedge.py
 sphinx/source/docs/user_guide/examples/plotting_whisker.py
 sphinx/source/docs/user_guide/examples/simple_line.js
 sphinx/source/docs/user_guide/examples/styling_axis_properties.py
 sphinx/source/docs/user_guide/examples/styling_background_fill.py
 sphinx/source/docs/user_guide/examples/styling_bounds.py
 sphinx/source/docs/user_guide/examples/styling_dimensions.py
 sphinx/source/docs/user_guide/examples/styling_fixed_ticker.py
 sphinx/source/docs/user_guide/examples/styling_func_tick_formatter.py
 sphinx/source/docs/user_guide/examples/styling_glyph_hover.py
 sphinx/source/docs/user_guide/examples/styling_glyph_properties.py
 sphinx/source/docs/user_guide/examples/styling_glyph_selections_plotting_glyph.py
 sphinx/source/docs/user_guide/examples/styling_glyph_selections_plotting_params.py
 sphinx/source/docs/user_guide/examples/styling_grid_band_fill.py
 sphinx/source/docs/user_guide/examples/styling_grid_band_hatch.py
 sphinx/source/docs/user_guide/examples/styling_grid_bounds.py
 sphinx/source/docs/user_guide/examples/styling_grid_lines.py
 sphinx/source/docs/user_guide/examples/styling_labels.py
 sphinx/source/docs/user_guide/examples/styling_legend_title.py
 sphinx/source/docs/user_guide/examples/styling_linear_mappers.py
 sphinx/source/docs/user_guide/examples/styling_min_border.py
 sphinx/source/docs/user_guide/examples/styling_minor_grid_lines.py
 sphinx/source/docs/user_guide/examples/styling_numerical_tick_formatter.py
 sphinx/source/docs/user_guide/examples/styling_plot_outline_line_color.py
 sphinx/source/docs/user_guide/examples/styling_printf_tick_formatter.py
 sphinx/source/docs/user_guide/examples/styling_tick_label_orientation.py
 sphinx/source/docs/user_guide/examples/styling_tick_lines.py
 sphinx/source/docs/user_guide/examples/styling_title.py
 sphinx/source/docs/user_guide/examples/styling_tool_overlays.py
 sphinx/source/docs/user_guide/examples/styling_visible_annotation_with_interaction.py
 sphinx/source/docs/user_guide/examples/styling_visible_property.py
 sphinx/source/docs/user_guide/examples/tools_hover_custom_tooltip.py
 sphinx/source/docs/user_guide/examples/tools_hover_tooltip_formatting.py
 sphinx/source/docs/user_guide/examples/tools_hover_tooltips.py
 sphinx/source/docs/user_guide/examples/tools_position_toolbar.py
 sphinx/source/docs/user_guide/examples/tools_position_toolbar_clash.py
 sphinx/source/docs/user_guide/layout.rst
 sphinx/source/docs/user_guide/styling.rst
 tests/integration//test_datarange1d.py
 tests/integration//test_plot.py
 tests/integration//test_sources.py
 tests/integration/tools/test_box_edit_tool.py
 tests/integration/tools/test_box_zoom_tool.py
 tests/integration/tools/test_freehand_draw_tool.py
 tests/integration/tools/test_pan_tool.py
 tests/integration/tools/test_point_draw_tool.py
 tests/integration/tools/test_poly_draw_tool.py
 tests/integration/tools/test_poly_edit_tool.py
 tests/integration/tools/test_range_tool.py
 tests/integration/tools/test_reset_tool.py
 tests/integration/tools/test_wheel_zoom_tool.py
 tests/integration/tools/test_zoom_in_tool.py
 tests/integration/tools/test_zoom_out_tool.py
 tests/integration/widgets/tables/test_source_updates.py
 tests/integration/widgets/test_autocomplete_input.py
 tests/integration/widgets/test_button.py
 tests/integration/widgets/test_checkbox_button_group.py
 tests/integration/widgets/test_checkbox_group.py
 tests/integration/widgets/test_color_picker.py
 tests/integration/widgets/test_datepicker.py
 tests/integration/widgets/test_daterange_slider.py
 tests/integration/widgets/test_dateslider.py
 tests/integration/widgets/test_dropdown.py
 tests/integration/widgets/test_multi_choice.py
 tests/integration/widgets/test_numeric_input.py
 tests/integration/widgets/test_password_input.py
 tests/integration/widgets/test_radio_button_group.py
 tests/integration/widgets/test_radio_group.py
 tests/integration/widgets/test_range_slider.py
 tests/integration/widgets/test_select.py
 tests/integration/widgets/test_slider.py
 tests/integration/widgets/test_spinner.py
 tests/integration/widgets/test_text_input.py
 tests/integration/widgets/test_textarea_input.py
 tests/integration/widgets/test_toggle.py
 tests/unit/bokeh/command/test_util__command.py
 tests/unit/bokeh/core/test_properties.py
 tests/unit/bokeh/io/test_export.py
 tests/unit/bokeh/plotting/test_figure.py
</details>

### CODE REVIEW

**Comment by bryevdv** [comment]
Hi @satishjasthi Thanks for the PR. This task will involve a little more than an unconditional search/replace. There are a few places that should *not change*. Specifically, we intend to maintain backward compatibility and accept `plot_width` and `plot_height` to avoid breaking lots of old code. We just want to make sure we don't *promote* those as the best names to use going forward. 

So my suggestion is to back up a little and take this in stages:

* update all the files under `examples` I think this is safe for search/replace
* update all the files under `sphinx` this is probably safe for search/replace, or nearly so
* update all the files under `tests` this will take some discretion. We want to make sure to keep testing that `plot_width` etc *still work* (backward compatibility) so we can't just search/replace
* consider if anything under `bokeh` needs to change. Probably little or no changes

Specifically, I think it would be good to do all the stages above in *separate commits* so that they can be more easily reviewed in isolation. Are you interested to pursue this different approach?

**Comment by bryevdv** [comment]
In terms of the actual PR, the options are:

* force push changes to this PR to split up commits
* close this PR in favor of a new PR with split-out commits

**Comment by bryevdv** [comment]
Also just an FYI for very long content like that file list there is a useful `<details>` option for GitHub markdown to hide them behind a collapsible div.

**Comment by satishjasthi** [comment]
Sure will do thank you

**Comment by satishjasthi** [comment]
Ill close this PR and re create a new PR

**Comment by satishjasthi** [comment]
> Hi @satishjasthi Thanks for the PR. This task will involve a little more than an unconditional search/replace. There are a few places that should _not change_. Specifically, we intend to maintain backward compatibility and accept `plot_width` and `plot_height` to avoid breaking lots of old code. We just want to make sure we don't _promote_ those as the best names to use going forward.
> 
> So my suggestion is to back up a little and take this in stages:
> 
> * update all the files under `examples` I think this is safe for search/replace
> * update all the files under `sphinx` this is probably safe for search/replace, or nearly so
> * update the files under `tests` this will take some discretion. We want to make sure to keep testing that `plot_width` etc _still work_ (backward compatibility) so we can't just search/replace everything. But if a test is not related to compatibility, it can be updated.
> * consider if anything under `bokeh` needs to change. Probably little or no changes here but worth looking to see if there are some appropriate to change
> 
> Specifically, I think it would be good to do all the stages above in _separate commits_ so that they can be more easily reviewed in isolation. Are you interested to pursue this different approach?

Hi bryevdv 
Im trying to run the test cases on master branch as well as branch2.4 but I'm not able to run all the test cases even after following the installation instruction mentioned in developer blog, Can you please help me resolve this issue, I think I'm doing something wrong in setting up my env, because usually all of the test cases in the master should pass when I take a fork

**Comment by bryevdv** [comment]
I'm going to go ahead and close this PR due to the combination of 

* lack of activity 
* new merge commit from other work
* starting fresh along the lines described in https://github.com/bokeh/bokeh/pull/10989#issuecomment-789881967

@satishjasthi if you are still interested to work on this please open a new clean  PR on top of  current latest `branch-2.4` and we can take things from there.

**Comment by bryevdv** [comment]
@mattpap I am not aware of another PR should this simply be `declined`?

**Pull request closed without merging**
