### PR TITLE
Allow to configure `origin` and `anchor` on `Image` and `ImageRGBA`

### LINKED ISSUE #1666: Flip images when ranges are reversed
Hello,

I'm new to Bokeh, and it might be that I'm using the library wrong, but in most of the image libraries the [0,0] pixel refers to the top left pixel of the image, while in Bokeh (I have not been able to change it) the [0,0] coordinate refers to the bottom left pixel of the image. This simple script to load and plot an image:

```
import bokeh.plotting as plt
from skimage.io import imread
lenna = imread('/tmp/lenna.png', flatten=True)
p = plt.figure(x_range=[0,10], y_range=[0,10])
p.image(image=[lenna], x=0, y=0, dw=10, dh=10, palette='Greys9')
plt.show(p)
```

Results with the image plotted upside down, as seen in the attached images (image is also converted to grayscale but this is not relevant):
lenna
lennaplot

I've tried reversing the range to `[10, 0]` but this results in displacing the image, not fliping the y axis. The only way I've found to plotting it right is by flipping the numpy array `lenna[::-1]` before sending it to plot (but I guess it should be a better way).

Is there a way of doing it? Is it a bug? Or am I using the library wrong?

Thank you

### LINKED ISSUE #1763: Support anchor property for Image and ImageRGBA
I thought we already did but apparently not:

```
bryan@laptop (git:task/1747_model_docs) ~/work/bokeh/bokehjs/src/coffee/renderer/glyph $ grin anchor
./image_url.coffee:
   52 :       anchor = @mget('anchor') or "top_left"
   54 :       switch anchor
```

### PR DESCRIPTION
**Pull request by mattpap**
image

fixes #1666
fixes #1763

### CODE REVIEW

**Comment by mattpap** [comment]
So far this PR deals with `Image` and `ImageRGBA`, solidifying their common base. I didn't include changes to `ImageURL`, so its behavior and implementation is quite different from the former glyphs.

**Comment by bryevdv** [comment]
This looks great. My only comments suggestions would be:

* I think users could benefit from a bit more information / description of `origin` and `anchor` and how they interact
* An example that uses `CustomJS` to let users explore changing different values for `origin` and `anchor` would be great for the docs

cc @tcmetzger for thoughts

**Comment by bryevdv** [comment]
@mattpap if you can resolve the conflict I will push some minimal additional docs and merge tonight/tomorrow

**Comment by bryevdv** [comment]
Here is a little explorer script:
```
import numpy as np

from bokeh.core.enums import Anchor, ImageOrigin
from bokeh.models import Select
from bokeh.palettes import Sunset4
from bokeh.plotting import column, figure, show

Sunset4 = [[0xff9a4b36, 0xffe5d2a5], [0xff72c0fd, 0xff2600a5]]
img = np.array(Sunset4, dtype=np.uint32)

p = figure(
    title="Different anchors and origins for image placed at coordinates (0, 0)",
    tools="", toolbar_location=None,
    x_range=(-10, 10), y_range=(-10, 10),
    background_fill_color="#efefef"
)
r = p.image_rgba(image=[img], x=0, y=0, dw=9, dh=9)
p.circle(0, 0, size=12, fill_color="black", line_color="white", line_width=3)

anchor = Select(title="anchor", options=list(Anchor), value=r.glyph.anchor)
anchor.js_link("value", r.glyph, "anchor")

origin = Select(title="origin", options=list(ImageOrigin), value=r.glyph.origin)
origin.js_link("value", r.glyph, "origin")

show(column(p, anchor, origin))
```
This should definitely go in `examples/plotting` but I'd like to also put it in the users guide somewhere. Thoughts @mattpap  @tcmetzger ?

**Comment by tcmetzger** [comment]
@bryevdv https://docs.bokeh.org/en/latest/docs/user_guide/plotting.html#images seems like a good place to me, since these features are specific to images. If we put the information there, we'll just need to make clear that origin and anchor are only available on `Image` and `ImageRGBA` (since this section of the docs is talking about all three image glyphs, including `image_url`)

**Review by bryevdv — APPROVED** [review]

**Pull request merged**
