### PR TITLE
Improve mouseover information in Texas example.

### PR DESCRIPTION
**Pull request by PetterS**
For issue #2496.

I am not sure how to handle the metadata information in the notebook.

### CODE REVIEW

**Comment by PetterS** [comment]
Travis test failure appears to be unrelated.

**Comment by bryevdv** [comment]
Yup, have had problems recently with one example causing spurious timeouts. Have restarted.

**Comment by PetterS** [comment]
Ready to merge?

**Comment by damianavila** [comment]
LGTM, merging now...

**Pull request merged**
