### PR TITLE
Subtract padding when calculating dims for responsive modes

### LINKED ISSUE #7645: sizing_mode='scale_width' makes plot 1 or 2 pixels too wide in notebook
screenshot from 2018-03-17 15-58-15

Any plot with `sizing_mode='scale_width'` in jupyter notebook has a scroll bar underneath it.

Tested on:
* Firefox (Linux and OSX)
* Chrome (OSX)
* Safari (OSX)

It is the broken on 0.12.6, 0.12.7, 0.12.9 0.12.10, 0.12.14 and 0.12.15dev3

It is good on 0.12.5 

screenshot from 2018-03-17 15-58-51

The problem does not show up in nbviewer for me, only in live notebooks.

While briefly investigating, I did notice that test `test_scale_width_plot_starts_at_correct_size` had been marked with @pytest.mark.xfail between 0.12.5 and 0.12.6. - https://github.com/bokeh/bokeh/blob/master/tests/integration/interaction/test_sizing_mode.py#L106

### PR DESCRIPTION
**Pull request by mattpap**
fixes #7645

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap can you attach a screen shot here for documentation of the fix

**Comment by mattpap** [comment]
Better I will add an image diff/integration test for this (this isn't exclusively related to the notebook)

**Comment by mattpap** [comment]
Anyway, here's how it looks in the notebook:

image

**Comment by bryevdv** [comment]
@mattpap are you still planning on adding the image test, or should this be merged now?

**Comment by mattpap** [comment]
I've been working on a test, but this requires a custom template, which is currently tedious to do. So, effectively I started working on #4986. Lets merge this and I will add a test in another PR.

**Pull request merged**
