### PR TITLE
Add support for Less/CSS to extensions

### PR DESCRIPTION
**Pull request by mattpap**
This allows to compile `*.less` and `*.css` files into CSS modules that are linked together into JS bundles.

### CODE REVIEW

**Comment by mattpap** [comment]
Test failure is unrelated.

**Comment by philippjfr** [comment]
Are there any instructions on how to start using this?

**Comment by mattpap** [comment]
@philippjfr, instructions not yet, but `examples/custom/latex_extension_{base,full}` should help for now.

**Comment by philippjfr** [comment]
Perfect thanks!

**Pull request merged**
