### PR TITLE
change image_url onload callback to render request

### LINKED ISSUE #2785: ImageURL glyph initial render is incorrect
The initial render of an ImageURL glyph, renders the glyph last (independent of rendering level) and incorrectly (in the wrong level, incorrectly clipped and sometimes in the wrong place). Clicking the reset tool (or any plot interaction that triggers a new render) corrects the plot.

```python
from bokeh.plotting import figure, save, output_file, show
from bokeh.models import Range1d, Rect, ImageURL, ColumnDataSource, Grid, HoverTool, Circle
output_file('cie.html')

url = ['http://raw.githubusercontent.com/colour-science/colour/develop/colour/plotting/resources/CIE_1931_Chromaticity_Diagram_CIE_1931_2_Degree_Standard_Observer.png']

source = ColumnDataSource(data=dict(url=[url,]))

hover = HoverTool(tooltips=[("(x,y)", "($x, $y)"), ], point_policy='follow_mouse')

fig = figure(title='CIE 1931 Chromaticity Diagram',
             x_range=Range1d(start=0, end=0.8),
             y_range=Range1d(start=0, end=0.9),
             plot_width=450,
             plot_height=400,
             tools = [hover, 'reset']
            )

fig.image_url(x=0.0,
              y=1.0,
              h=1.0,
              w=1.0,
              url="url",
              name='cie',
              level='image',
              source=source)

fig.image_url(x=0.0,
              y=1.0,
              h=1.0,
              w=1.0,
              url="url",
              name='cie',
              level='image',
              source=source)

fig.scatter([.1,.2,.3],[.4,.5,.6], fill_color="red", name='points')

show(fig)
```

### PR DESCRIPTION
**Pull request by canavandl**
issues: fixes #2785 

Current behavior unconditionally renders the image as part of the onload callback. This changes the render to a render_request, which uses the whole bokeh render sequence.

Question: Is it worth adding any sort of logic in the case of a 404 for the image?

### CODE REVIEW

**Comment by bryevdv** [comment]
Yes, there was a FD discussion about adding both `retry_attempts` and `retry_timeout` (or similar). Also I think the border clipping logic needs to be preserved (in the `render_image` method) other wise the images will draw over the plot outline.

**Comment by canavandl** [comment]
I experimented with the clipping logic and think it's best to not include it the _render_image logic. The Plot render logic seems to appropriately clip the image based on the render level, so that the behavior mirrors how Rect models are rendered. I can post screenshots to demonstrate this.

I'll look into implementing retry_attempts/retry_timeout logic

**Comment by bryevdv** [comment]
Hrm, perhaps axis rules were being rendered earlier before glyphs in the past. It definitely used to be that case that url images ended up on top of the axis, obscuring it, but that does not seem to be happening anymore.

**Comment by bryevdv** [comment]
@canavandl can you merge master into this then I think tests should pass

**Comment by bryevdv** [comment]
LGTM

**Pull request merged**
