### PR TITLE
Add star marker - webgl extension

### PR DESCRIPTION
**Pull request by sebacastroh**
This PR extends the PR #10846 

The algorithm was adapted from https://iquilezles.org/www/articles/distfunctions2d/distfunctions2d.htm and the current results are

image

image

### CODE REVIEW

**Comment by mattpap** [comment]
@sebacastroh, you need start working off topic branches instead off the main branch (`branch-2.3` currently), so that commit history is kept simple and no duplicated changes are included. I fixed this PR. After this is merged, reset your main branch with `git checkout branch-2.3; git reset --hard origin/branch-2.3`. Then you can continue working on other things by starting new branch each time, e.g. `git checkout -b 10846_webgl_star_marker` (per our branch naming attitude).

**Comment by bryevdv** [comment]
@sebacastroh This is really great, thank you. Would you be interested to be added to @bokeh/dev ?

**Review by bryevdv — APPROVED** [review]

**Comment by sebacastroh** [comment]
@bryevdv You're welcome!

I will gladly help if I can, however this was a very small problem related to a specific project at my work. If you think I can help with any other issue, I will gladly try. This is far from my experience (structural engineer) but I really enjoy these types of projects and I think I can learn a lot 😄

**Comment by bryevdv** [comment]
@sebacastroh Well, you jumped right in to some more complex areas of Bokeh so we'd definitely love to have more help if you are inclined to continue contributing! https://github.com/bokeh/bokeh/issues/10751 is a recent request that proposed added a new kind of "indicator" glyph. That would be similar to this work, so it might be a natural next issue to look at

**Pull request merged**
