### PR TITLE
Add test_axis_label_extra_x_ranges integration test

### LINKED ISSUE #7164: Axes labels misplaced on multiple extra_x_ranges
I have tried to add multiple extra_x_ranges on a plot and the labels failed to be placed on the correct position. Probably related to the offset used when more than one extra_x_ranges is used.

I am using python 2.7 with Bokeh 0.12.10
In the example bellow axis label 'foo2' is misplaced over axis foo3 and label 'foo3' is missing.
Code to replicate:
untitled
```
from bokeh.plotting import figure, show
from bokeh.models import Range1d, LinearAxis


plot = figure(title=None, x_axis_location=None, y_axis_location=None)
plot.extra_y_ranges ['MD'] = Range1d(start=0, end=1)
plot.add_layout(LinearAxis(y_range_name='MD', axis_label = 'MD [m]'), 'left')
plot.extra_x_ranges ['foo1'] = Range1d(start=0,end=1)
plot.add_layout(LinearAxis(x_range_name='foo1', axis_label = 'foo1'), 'above')
plot.extra_x_ranges ['foo2'] = Range1d(start=0,end=10)
plot.add_layout(LinearAxis(x_range_name='foo2', axis_label = 'foo2'), 'above')
plot.extra_x_ranges ['foo3'] = Range1d(start=0,end=1)
plot.add_layout(LinearAxis(x_range_name='foo3', axis_label = 'foo3'), 'above')


plot.line(x = [0,1], y = [0,1], legend = 'foo1', x_range_name='foo1', y_range_name='MD')   
plot.line(x = [10,0], y = [0,1], legend = 'foo2', x_range_name='foo2', y_range_name='MD', color='red')   
plot.line(x = [0,0.5], y = [0.5,0], legend = 'foo3', x_range_name='foo3', y_range_name='MD')   

show(plot)
```

### PR DESCRIPTION
**Pull request by mattpap**
fixes #7164

### CODE REVIEW

**Comment by bryevdv** [comment]
I'm still getting this on a fresh build of master, in Safari and Chrome

screen shot 2017-12-28 at 11 20 03

**Comment by bryevdv** [comment]
OK I added a `console.log` and am not seeing it. This is a new laptop to replace my old one, so perhaps there's still some re-setup to figure out.

**Comment by bryevdv** [comment]
New anaconda install had a Bokeh package install and `setup.py develop` does not notice/complaint/replace. All working as expected now

**Comment by bryevdv** [comment]
Not sure what's going on with the failing tests though, I restarted in case it was a spurious issue but they seem to have failed again.

**Comment by mattpap** [comment]
@bryevdv, it's py.test's fault. I will submit a fix in a moment.

**Comment by mattpap** [comment]
@bryevdv, I presume you didn't check examples' test report. I forgot to add `integration/layout` to `examples.yaml`.

**Comment by bryevdv** [comment]
Nope, not after it was working locally

**Pull request merged**
