### PR TITLE
Documentation cleanup

### PR DESCRIPTION
**Pull request by mbrown1413**
I'm glad Bokeh is really well documented, but there's a lot more documentation than I thought!

This fixes lots of typos and places where classes/code were referenced without using double backticks. A few docstring rewordings to make them "verb first" style. Some minor formatting fixes too.

Also fixed some formatting typos where `.. code-block::` was used with one colon instead of two. It would be nice if Sphinx/rst would error when that happens, instead of silently displaying nothing.

- [ ] issues: addresses #8448

### CODE REVIEW

**Comment by mattpap** [comment]
Thanks @mbrown1413.

**Comment by bryevdv** [comment]
Just FYI I think some of the back-ticking was a bit agressive. The validation messages, e.g. are only ever displayed in the console, there is no point to add backticks there (thanks @mbrown1413 !)

**Comment by mattpap** [comment]
Changes to validation module are limited to its docstring, which may appear in documentation (I'm not sure if it actually does) and already has some other minor formatting. Or maybe you were referring to something different, because I didn't see any excessive changes when reviewing this?

**Comment by mbrown1413** [comment]
I think the confusion is just that there are two descriptions for each error code: the message itself displayed on the console, and description in the docstring, which appears in the documentation for [bokeh.core.validation](https://bokeh.pydata.org/en/latest/docs/reference/core/validation.html).

**Pull request merged**
