### PR TITLE
Fix for issue #2098

### LINKED ISSUE #2098: decimal.Decimal cannot be sent across session
When trying to give data of type decimal.Decimal as data sources to plots, the BokehJSONEncoder does tries to serialise the Decimal object with the standard built-in JSON encoder. This causes an exception "Decimal('...') not JSON serializable". The solution is to edit BokehJSONEncoder.trasnform_python_types to account for this possibility. I have tested the solution and it works.

### PR DESCRIPTION
**Pull request by lukebarnard1**
issues: closes #2098 

Fix the issue with BokehJSONEncoder not being able to encode decimal.Decimal correctly. Casting to a float solves the issue, although, it very very slightly inaccurate and maybe casting to a string would be better?

### CODE REVIEW

**Comment by bryevdv** [comment]
FYI we are prepping for a point release so this won't be reviewed/merged for a few days.

**Comment by bryevdv** [comment]
Regarding the accuracy, everything gets converted to a 64bit float by JS anyway, so I am not sure that it matters that the casting happens here rather than on the client.

**Comment by lukebarnard1** [comment]
Ah, valid point

**Comment by bryevdv** [comment]
LGTM

**Comment by bryevdv** [comment]
LGTM

**Pull request merged**
