### PR TITLE
don't upload to s3 on py27 tests

### LINKED ISSUE #9165: Update dataset for parallel coords plot examples
The example currently does this:
```
df = pd.read_csv("https://raw.githubusercontent.com/bcdunbar/datasets/master/parcoords_data.csv")
```

Which is not really great. We should add a data set to `sampledata` and use that.

### PR DESCRIPTION
**Pull request by bryevdv**
fixes #9165 

Not sure what is causing the sudden failure of the s3 examples report on just the py27 build, but since the report doesn't actually have any images anyway, I'm also not interested in finding out. This PR just removes the upload from the py27 build. 

cc @mattpap just FYI

### CODE REVIEW

**Comment by mattpap** [comment]
In general, test report without images is pretty much pointless, so +1.

**Comment by bryevdv** [comment]
One test that dowloads data directyl from GH (shouldn't do that) is also failing with the same SSL error:
```
tests/test_examples.py::test_file_examples[/home/travis/build/bokeh/bokeh/examples/custom/parallel_plot/parallel_plot.py-example38-config38] 
[INFO] Example run in 0.780s
[PY] Traceback (most recent call last):
[PY]   File "<string>", line 13, in <module>
[PY]   File "/home/travis/build/bokeh/bokeh/examples/custom/parallel_plot/parallel_plot.py", line 112, in <module>
[PY]     df = pd.read_csv("https://raw.githubusercontent.com/bcdunbar/datasets/master/parcoords_data.csv")
[PY]   File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
[PY]     return _read(filepath_or_buffer, kwds)
[PY]   File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/pandas/io/parsers.py", line 413, in _read
[PY]     filepath_or_buffer, encoding, compression)
[PY]   File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/pandas/io/common.py", line 202, in get_filepath_or_buffer
[PY]     req = _urlopen(filepath_or_buffer)
[PY]   File "/home/travis/miniconda/envs/testenv/lib/python2.7/urllib2.py", line 154, in urlopen
[PY]     return opener.open(url, data, timeout)
[PY]   File "/home/travis/miniconda/envs/testenv/lib/python2.7/urllib2.py", line 429, in open
[PY]     response = self._open(req, data)
[PY]   File "/home/travis/miniconda/envs/testenv/lib/python2.7/urllib2.py", line 447, in _open
[PY]     '_open', req)
[PY]   File "/home/travis/miniconda/envs/testenv/lib/python2.7/urllib2.py", line 407, in _call_chain
[PY]     result = func(*args)
[PY]   File "/home/travis/miniconda/envs/testenv/lib/python2.7/urllib2.py", line 1241, in https_open
[PY]     context=self._context)
[PY]   File "/home/travis/miniconda/envs/testenv/lib/python2.7/urllib2.py", line 1198, in do_open
[PY]     raise URLError(err)
[PY] urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
FAILED
```
won't be able to do anything about this till late tonight

**Comment by bryevdv** [comment]
@mattpap I got home late from the meetup. Can you make it skip this test (ideally just for py2 but for both for now if we have to) in the morning?

**Comment by bryevdv** [comment]
@mattpap I added 
```
# remove for 2.0
- path: "examples/custom/parallel_plot"
  skip: all
```

It's skipping the test correctly on Py3 but still running the test on Py2. Is there something I am missing about `examples.yaml`?

**Comment by bryevdv** [comment]
Well guessing it is because there is also 
```
- path: "examples/custom"
``` 
up above in the file and Python 2 handles that badly somehow.

**Pull request merged**
