### PR TITLE
Make annulus glyph work on IE too

### LINKED ISSUE #3543: Annulus glyph does not render correctly in IE and Edge
Instead of a "donut" it shows an opaque circle that seems to correspond to the inner circle of the donut. Can be seen in e.g. `plotting/notebooks/glyphs.ipynb` and `plotting/file/glyphs.py`.

Confirmed on Win7, Win10 / IE 11, Edge

This might very well be a bug/feature of the IE canvas engine. Can we work around it?

### PR DESCRIPTION
**Pull request by almarklein**
issues: fixes #3543

IE was confused about what part of the annulus should be filled, which granted, is not an easy task :)  By drawing the glyph in two parts, IE knows how to do it too.

To test, check e.g. `examples/glyphs/glyphs.py`

### CODE REVIEW

**Comment by bryevdv** [comment]
merge master to try and get tests passing

**Comment by almarklein** [comment]
ah, thanks. Travis is green.

**Comment by bryevdv** [comment]
Unfortunately it looks like this can leave artifacts:

screen shot 2016-01-14 at 10 30 21 am

(from the the test report at ttps://s3.amazonaws.com/bokeh-travis/0.11.0-c312cf8/plotting/file/glyphs.png)

**Comment by almarklein** [comment]
Arg, I had such artifacts before, but they are gone on the browsers that I tested with the current implementation. Mmm, I'll try a bit further ...

**Comment by bryevdv** [comment]
Well, perhaps it's a phantomJS issue then, if we can demonstrate that it actually works across the real major platform browsers I think it would be OK to proceed.

**Comment by almarklein** [comment]
Here's a link to a static plot with the new implementation. You can zoom out to get more overlap to validate if that works out correctly: https://dl.dropboxusercontent.com/u/1463853/bokeh/annulus.html

I verified that it works correctly on Win10 with FF, Chrome, Edge, IE.

**Comment by bryevdv** [comment]
Still visible on OS X / safari:

screen shot 2016-01-15 at 5 10 49 pm

Starting to wonder if  browser detection (as much as that sucks) is the way to go.

**Comment by almarklein** [comment]
Mmm.... I tested on Linux with Chrome and FF. And also on a OSX VM with a (rather old version of) Safari. All look fine. So it looks like it breaks for the newer version of Safari.

How hard is it to detect either Safari or IE?

**Comment by almarklein** [comment]
@bryevdv I added browser detection for IE. Can you try again (same link)?

**Comment by bryevdv** [comment]
Yup looks perfect on OSX/safari now

**Comment by almarklein** [comment]
Great. Ready to go then, from my end.

**Pull request merged**
