### PR TITLE
Add aspect example

### PR DESCRIPTION
**Pull request by DuCorey**
Add example for the new aspect ratio control behavior introduced in #6784 

- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
Thanks @DuCorey !

**Comment by mattpap** [comment]
I think it would be useful to add other plots showing various aspect ratios from #6784.

**Comment by DuCorey** [comment]
@mattpap Would you like examples that distort the plot dimensions as well as show various aspect ratios?

**Comment by bryevdv** [comment]
@DuCorey I think having a good selection do different scenarios is good, e.g tall/wide plots etc

**Comment by mattpap** [comment]
@DuCorey, yes, this is what I had in mind.

**Comment by bryevdv** [comment]
Thanks @DuCorey !

**Pull request merged**
