### PR TITLE
Add bokeh multi_line script

### PR DESCRIPTION
**Pull request by MubarakElrayah92**
The script target is to draw devices data traffic (Upbytes + Downbytes).
The Data.csv contain the concatenated data from multi CSV file.

- [x] issues: #7969 
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
Hi @MubarakElrayah92 Is this PR intended for a different repository? It contains local file paths, etc. We are happy to accept contributions of new examples, but there would need to be some work to make this code and data fit into our existing conventions.

**Comment by MubarakElrayah92** [comment]
Hi @bryevdv it seems like I did a little mistake here, i'm kinda new to GitHub community, your advice will be highly appreciated. 
**Note:** I uploaded the script file and the CSV file to the bokeh master repository.

**Comment by bryevdv** [comment]
@MubarakElrayah92 sure I am happy to try and advise, but what exactly is it you are wanting to do? This repo is for the development and maintenance of the Bokeh project for all users, so the only things that can be added are those that serve the project or all users in general. Are you intending to add to this script to the repo as a helpful example? Or do you mean to accomplish something else?

**Comment by MubarakElrayah92** [comment]
@bryevdvI appreciate your kindness here, I'm trying to add a helpful example on how to add hover on multiline. beside creating widgets to select each data separately.

**Comment by bryevdv** [comment]
@MubarakElrayah92 OK well that would be great, just to clear up front there are a good amount of changes that will be necessary first, but I am happy to work through them with you. Here are some changes to start:

* The script needs to be moved under the `examples` directory. Offhand, I would suggest `examples/plotting/file/multi_line_hover.py` 
* There are currently alot of code qualiity/linter violations. Tests will not pass until these are resolved. Mostly it looks like you need to:
  - convert all tabs to spaces
  - remove and trailing whitespace at the end of all lines
  - end the file with a single newline
  Depending on what editor you use you may be able to change a setting to do these things automatically. 
* To be consistent with existing examples, the script structure should be "flattened" i.e. get rid of the function `run_graph` just have all the code a the top level
* there is some magic numbers  and repetitive constants (e.g. 1024**3), as well as some repetitive blocks of code. Ideally this can be factored lightly to shorten the script somewhat
* the full-line comments are unnecessary

Additionally, the data file will have to move into the `sampledata` module, but let's get this first batch of changes completed then we can move on to that.

**Comment by MubarakElrayah92** [comment]
Sounds Great 👍.

Kindly check the changes and let me know if i missed something @bryevdv

**Comment by bryevdv** [comment]
@MubarakElrayah92 great start, a few more comments:

* all examples must support both python 2 and 3 so the current old style print statements can't stay. I would just suggest removing all print statements. 

* It looks like only the "juniper" variables are actually used? If that is the case then all the unused variables (for cisco, hp, dell) should be removed. Our code linter will also fail the tests on unused variables 

I also meant to ask earlier but forgot: Where did this data come from? We need to know provenance and that it is suitably licensed for use to be able to legally distribute

**Comment by bryevdv** [comment]
Also I don't have the bandwidth at the moment to check out this PR locally. Can you attach a screenshot here in the PR comments for my benefit?

**Comment by MubarakElrayah92** [comment]
@bryevdvI  I just finished the requested changes, and don't worry about the provided data, I am the provenance of it and it's not related to any company from the above list.

**Comment by MubarakElrayah92** [comment]
screen shot 2018-06-07 at 10 47 48 am

**Comment by bryevdv** [comment]
@MubarakElrayah92 Sorry, in case I was not clear, I am asking for a screen shot of the plot that this code generates. A few more changes still needed before moving on to adding the sample data:

* There are currently syntax errors in the script:
  ```
  tests/examples/test_examples.py::test_file_examples[/home/travis/build/bokeh/bokeh/examples/plotting/file/multi_line_hover.py-example103] 
  [INFO] Example run in 0.155s
  [PY] Traceback (most recent call last):
  [PY]   File "<string>", line 13, in <module>
  [PY]   File "/home/travis/build/bokeh/bokeh/examples/plotting/file/multi_line_hover.py", line 67
  [PY]     p.multi_line(xs = [juniper_time, juniper_time], ys = [juniper_up, juniper_down] color=['red', 'blue'] line_width=1, legend='juniper')
  [PY]                                                                                         ^
  [PY] SyntaxError: invalid syntax
  FAILED
  ```

* there are still some linter errors: 

```
    @pytest.mark.quality
    def test_files():
        errors = collect_errors()
>       assert len(errors) == 0, "Code quality issues:\n%s" % "\n".join(errors)
E       AssertionError: Code quality issues:
E         File does not end with a newline: Data.csv, line 223
E         File contains tabs instead of spaces: examples/plotting/file/multi_line_hover.py, line 17.
E         File contains tabs instead of spaces: examples/plotting/file/multi_line_hover.py, line 18.
E         File contains tabs instead of spaces: examples/plotting/file/multi_line_hover.py, line 19.
E         File contains tabs instead of spaces: examples/plotting/file/multi_line_hover.py, line 20.
E         File contains tabs instead of spaces: examples/plotting/file/multi_line_hover.py, line 21.
E         File contains tabs instead of spaces: examples/plotting/file/multi_line_hover.py, line 22.
E         File contains trailing whitespace: examples/plotting/file/multi_line_hover.py, line 41.
E         File contains trailing whitespace: examples/plotting/file/multi_line_hover.py, line 57.
E       assert 9 == 0
E        +  where 9 = len(['File does not end with a newline: Data.csv, line 223', 'File contains tabs instead of spaces: examples/plotting/file...hover.py, line 20.', 'File contains tabs instead of spaces: examples/plotting/file/multi_line_hover.py, line 21.', ...])
tests/test_code_quality.py:95: AssertionError
_________________________________ test_flake8 __________________________________
    @pytest.mark.quality
    def test_flake8():
        chdir(TOP_PATH)
    
        proc = Popen(["flake8"], stdout=PIPE, stderr=PIPE)
        out, err = proc.communicate()
    
>       assert proc.returncode == 0, "Flake8 issues:\n%s" % out.decode("utf-8")
E       AssertionError: Flake8 issues:
E         ./examples/plotting/file/multi_line_hover.py:24:1: E101 indentation contains mixed spaces and tabs
E         
E       assert 1 == 0
E        +  where 1 = <subprocess.Popen object at 0x7fad246e36d8>.returncode
tests/test_flake8.py:16: AssertionError
============= 2 failed, 3 passed, 3335 deselected in 28.71 seconds =============
```

**Comment by bryevdv** [comment]
Lastly, these blocks of code repeat almost verbatim five times:
```
 +hp = result[(result.DeviceName == 'Hp') & (result.TypeId == 932)]
 +hp_up = hp["UpBytes"]
 +hp_down = hp["DownBytes"]
 +hpconv = hp["StatTime"]
 +hp_time = pandas.to_datetime(hpconv, unit='s')
```
can you refactor this into a small function that you *call* five times to get each to of the sets of data for the plot?

**Comment by bryevdv** [comment]
@MubarakElrayah92 Do you expect to be able to continue to work on this example? I understand if other priorities have come up, but in that case we should close this to clear up the GH tracker.

**Comment by MubarakElrayah92** [comment]
Dear @bryevdv I apologize for the delay here. I will continue working on the example before EOT because like you mentioned in an upper comment there are some priorities came up recently.

**Comment by MubarakElrayah92** [comment]
screen shot 2018-06-14 at 9 51 56 pm

**Comment by MubarakElrayah92** [comment]
i just made some changing on my original code. instead of "DeviceName" I put protocol. but like you can see on attached screenshot the protocol is not defined and the time is appearing with timestamp format instead of readable time.

**Comment by bryevdv** [comment]
@MubarakElrayah92 docs on formatting tooltips is here:

https://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#formatting-tooltip-fields

For the "???" case the "@" name has to refer to a column that exists in your data, so unless you added a "Protocol" column, then it doesn't exist and that is why it shows "???"

**Comment by bryevdv** [comment]
@MubarakElrayah92 I appreciate your interest in contributing to Bokeh, but for the sake of keeping our GH tracker up to date and uncluttered, I am going to close this PR due to inactivity.

**Pull request closed without merging**
