### PR TITLE
Fix density parameter of streamlines function to accept tuples.

### PR DESCRIPTION
**Pull request by mborus**
small fix found during pyconde19 sprints.

### CODE REVIEW

**Comment by bryevdv** [comment]
Though to be perfectly honest, I would also not mind just leaving the example the way it is. If `streamlines` were some built-in facility of Bokeh then it certainly make sense for it to be as general as possible, but it's not that. It's just a function that only exists to be called inside one example&mdash;accordingly it only really needs to support just the usage in the example.

**Comment by bryevdv** [comment]
Right, so the actual only usage in the example is with a homogenous density:
```
xs, ys = streamlines(xx, yy, U.T, V.T, density=2)
```
The purpose of the example is to demosntrate bokeh multiline  glyphs, not how to streamline in the most general way. I would much prefer to update the docstring to the function instead, and state that it only takes a single number as a `density` (no sequences at all)

**Comment by bryevdv** [comment]
Thinking even more out loud: I'd be happy to take in an optional dependency e,g. to `scipy` if we could shave 150 lines off this example. Not doing e.g. an rk4 integration by hand in the example, would be the best sort of improvement.

**Comment by mborus** [comment]
> 
> 
> `collections.abc` does not exist on python 2.7, which is still supported for one more upcoming Bokeh 1.x release. The best solution at this point is to update the PR to be against the `landing-2.0` branch, instead of `master`. (Please don't update the PR to use `six`, that would just make more work to undo on the `landing-2.0` branch which does not use `six` anymore)

Applying this to "landing-2.0 " makes sense. This came up when I was adding type hints to for the landing-2.0 branch, when after adding the hints mypy suggested that this is wrong. To the point of the request mainly is to allow type hinting the landing-2.0 branch.

**Comment by mborus** [comment]
> 
> 
> Right, so the actual only usage in the example is with a homogenous density:
> 
> ```
> xs, ys = streamlines(xx, yy, U.T, V.T, density=2)
> ```
> 
> The purpose of the example is to demosntrate bokeh multiline glyphs, not how to do streamlining in the most general way. Making the example longer only obscures the pedagogical intent around using mulit-lines. I would much prefer to update the docstring to the function instead, and state that it only takes a single number as a `density` (no mention or handling of sequences at all).

OK, that is probably the easiet fix.

**Pull request closed without merging**
