### PR TITLE
fix tooltip rendering with CDSview

### PR DESCRIPTION
**Pull request by Zyell**
fixes issue #7189

### CODE REVIEW

**Comment by bryevdv** [comment]
Thanks @Zyell I am going to hold off on this until @clairetang6 is able to comment. At a minimum there are a couple of other places in the same file that this change should be made. Thanks for your patience

**Comment by clairetang6** [comment]
@bryevdv @Zyell, this fixes the tooltips for all of the non-line and non-multilines including patches, but the issue is there for multi-lines. To fix that, the following lines should be placed at line 236 after the `switch @model.line_policy` block. 

```python
          if renderer_view.model instanceof GlyphRenderer
            index = renderer_view.model.view.convert_indices_from_subset([i])[0]
          else
            index = i
```
Then, the next two lines should be changed to use `index` instead of `i`, in the same way. 
```python
          vars = {index: index, segment_index: jj, x: x, y: y, sx: sx, sy: sy, data_x: data_x, data_y: data_y}

          tooltip.add(rx, ry, @_render_tooltips(ds, index, vars))
```

**Comment by bryevdv** [comment]
@Zyell FYI if you can make these changes in the next day or two, I can include them in the release Monday. Otherwise it will be the following release.

**Comment by Zyell** [comment]
@bryevdv & @clairetang6 I will make these changes today. I'm traveling home now, so it will be later this evening. Thanks!

**Comment by Zyell** [comment]
@bryevdv & @clairetang6 I have made the requested changes.  Let me know if there is anything else.  Thanks!

**Comment by bryevdv** [comment]
I am going to go ahed and merge this but we definitely need to find a way to maintain these many different cases better under test. @clairetang6 we should discuss testing strategy as part of your current work on refactoring selection

**Comment by bryevdv** [comment]
Thanks for the PR @Zyell !

**Pull request merged**
