### PR TITLE
some coarse plumbing for responding to visual property changes

### LINKED ISSUE #2682: Updating glyph style from JavaScript not working
Here is a minimal example that triggers the issue. Basically the change of alpha level is not taken into account (same goes for colors).

```
from bokeh.document import Document
from bokeh.plotting import show, vplot, output_file
from bokeh.models import Plot, ColumnDataSource, DataRange1d, Callback
from bokeh.models.widgets import Slider
from bokeh.models.glyphs import Line
import numpy as np

x = np.arange(0, 10)
y = np.random.rand(10)
output_file('test.html')
ds = ColumnDataSource(dict(x=x, y=y))
xdr = DataRange1d()
ydr = DataRange1d()

plot = Plot(x_range=xdr, y_range=ydr, plot_width=400, plot_height=300)


l = Line(x='x', y='y', line_alpha=0.2)

alpha_cb = Callback(args=dict(line=l), code="""
    //alert(line.get('line_alpha')['value'])
    new_alpha = cb_obj.get('value');
    alpha = line.get('line_alpha');
    alpha['value'] = new_alpha;
    line.set('line_alpha', alpha);
""")

alpha_slider = Slider(start=0.0, end=1.0, step=0.1,  title='line alpha', callback=alpha_cb)

plot.add_glyph(ds, l)
doc = Document()
doc.add(vplot(plot, alpha_slider))
show(doc)
```

### PR DESCRIPTION
**Pull request by bryevdv**
issues: fixes #2682

**This is intended as a stopgap measure**

I would like feedback about whether this is a reasonable short-term solution to make Bokeh plots responsive to JS changes to visual properties. Ultimately the BokehJS property system should be cleaned up and clarified even more, and more precise event handling constructed, but this at least gets the example below working. Thoughts @mattpap @mistakevin @bokeh/core

### CODE REVIEW

**Comment by bryevdv** [comment]
```
from bokeh.document import Document
from bokeh.plotting import show, vplot, output_file
from bokeh.models import Plot, ColumnDataSource, DataRange1d, Callback
from bokeh.models.widgets import Slider
from bokeh.models.glyphs import Line
import numpy as np

x = np.arange(0, 5000)
y = np.sin(x/500)
output_file('test.html')
ds = ColumnDataSource(dict(x=x, y=y))
xdr = DataRange1d()
ydr = DataRange1d()

plot = Plot(x_range=xdr, y_range=ydr, plot_width=400, plot_height=300)


l = Line(x='x', y='y', line_width=3, line_color="navy", line_alpha=0.2)

alpha_cb = Callback(args=dict(line=l), code="""
    new_alpha = cb_obj.get('value');
    line.set('line_alpha', { 'value': new_alpha });
""")

alpha_slider = Slider(start=0.0, end=1.0, step=0.01, value=0.2, title='line alpha', callback=alpha_cb)

plot.add_glyph(ds, l)
doc = Document()
doc.add(vplot(plot, alpha_slider))
show(doc)
```

**Comment by damianavila** [comment]
>This is intended as a stopgap measure

As a stopgap, I am not against that, but please also add a note in the code about the temporary nature of the solution...

**Comment by fpliger** [comment]
+1 on @damianavila thoughts

**Comment by bryevdv** [comment]
OK I will add a comment and then merge. @mattpap any final comments?

**Comment by bryevdv** [comment]
seeing if merging master fixes test

**Pull request merged**
