### PR TITLE
[WIP] Move functionality from Server to BaseServer and BokehTornado

### LINKED ISSUE #9813: [FEATURE] Compose Bokeh server with other Tornado HTTP Servers
So I have an application that has a tornado.web.HTTPServer .  I would love to run my Bokeh application on this web server, rather than have two different servers running on two different ports.

Currently Bokeh creates a Tornado HTTPServer within the `bokeh.server.server.Server` class, which takes in a set of `http_server_kwargs`, and then makes it's own server.  It would be swell if it could optionally take in a running tornado HTTPServer.

But wait!  There is this BaseServer class which seems to do exactly this:

```python
class BaseServer:
    def __init__(self, io_loop, tornado_app, http_server):
```

So now I'm wondering if using that class instead is a reasonable approach.  It looks like there is some other non-trivial setup in `Server.__init__` (binding sockets and whatnot) as well as some other properties like index, prefix, address, and port.  Some of these properties seem to be used upstream within BaseServer (such as `BaseServer.show`).  Should they be moved up to that class?

To be even more opinionated, I could imagine a future where there was just one class, call it `BaseServer` for now, and a function `Server` which included the logic within `Server.__init__`.  That's probably no longer possible today (presumably many people have `isinstance(foo, bokeh.server.server.Server)` calls in code, but maybe it provides motivation to move some functionality around, like the properties currently on Server.

### PR DESCRIPTION
**Pull request by mrocklin**
This makes it easier to use Bokeh Server with existing HTTPServers
by moving some logic from the Server constructor (which assumes that it
creates an HTTPServer) off to BaseServer and BokehTornado, which don't
make that assumption.

Fixes #9813

- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap are any of the changes in `server.py` necessary for your use case? I realize leaving them in is slightly duplicative, but I think that leaving them in still gets you what you need, and also avoids any breaking API changes. If we wanted to be tidy then the duplicated code for handling the `applications` argument could be factored into a shared utility function. What do you think?

**Comment by bryevdv** [comment]
@mrocklin  are any of the changes in `server.py` necessary for your use case? I realize leaving them in is slightly duplicative, but I think that leaving them in still gets you what you need, and also avoids any breaking API changes. If we wanted to be tidy then the duplicated code for handling the `applications` argument could be factored into a shared utility function. What do you think?

**Comment by mrocklin** [comment]
Sorry to let this linger a bit, I'm also working on this during off hours over at https://github.com/dask/distributed/pull/3658 (where I'm again duplicating these lines).  

We could duplicate, yes.  My guess is that there is a nice way to manage things without duplication, but I haven't gotten too deep in here yet.

**Comment by bryevdv** [comment]
@mrocklin no worries and no time frame (except your own!) IMO it would suffice to pull this block:
```
        from bokeh.application.handlers.function import FunctionHandler
        from bokeh.application.handlers.document_lifecycle import DocumentLifecycleHandler

        if callable(applications):
            applications = Application(FunctionHandler(applications))

        if isinstance(applications, Application):
            applications = { '/' : applications }

        for k, v in list(applications.items()):
            if callable(v):
                applications[k] = Application(FunctionHandler(v))
            if all(not isinstance(handler, DocumentLifecycleHandler)
                   for handler in applications[k]._handlers):
                applications[k].add(DocumentLifecycleHandler())
``` 
into some helper function that both places can use:
```
applications = _process_applications_argument(applications)
```

**Comment by bryevdv** [comment]
But if you do find a compatibility-preserving way to improve without duplication that's certainly great too :)

**Comment by bryevdv** [comment]
@mrocklin Just an FYI if you want to make the quick change described in https://github.com/bokeh/bokeh/pull/9833#issuecomment-609449335 for the next 2.1 release, the code freeze is next friday (the 29th)

**Comment by bryevdv** [comment]
superseded by #10070

**Pull request closed without merging**
