### PR TITLE
Restructure documentation landing page

### PR DESCRIPTION
**Pull request by tcmetzger**
As part of Google's Season of Docs, this pull request restructures the [landing page for Bokeh's documentation](https://docs.bokeh.org/en/latest/). As discussed with @bryevdv, @hyles-lineata, and @pavithraes.

### CODE REVIEW

**Comment by tcmetzger** [comment]
Well, seems like the CI is not able to install the new Sphinx extension correctly: [Could not import extension sphinx_panels (exception: No module named 'sphinx_panels')](https://github.com/bokeh/bokeh/runs/1156648952) - even though the extension is included in [environment.yml](https://github.com/bokeh/bokeh/pull/10519/files#diff-b7cb75ca59993a879e29bed8cd8469b8). @bryevdv, do you have an idea what is happening here - is this an issue of CI or an issue of installing the package in the environment?

**Comment by bryevdv** [comment]
@tcmetzger the CI build uses the env files in the `ci` ditectory. Specifically the docs build uses `environment-test-3.7.yml` but I would update all the test env files.

**Comment by bryevdv** [comment]
Is there a way to change the sizing column breaks for the images?

Screen Shot 2020-09-23 at 1 19 14 PM


Screen Shot 2020-09-23 at 1 19 34 PM

**Comment by bryevdv** [comment]
Other comments: 
* really like the plain search bar up top 👍 
* I like the responsive mini-gallery at the bottom, assuming the sizing issues can be fixed, it adds a nice finish to the page
* I l personally liked colors on the cards, did you decide against using them?
* Do we actually need the big header that states "Bokeh Documentation" ?

I definitely think we'll need to find something at the top too, maybe a single more abstracted here image instead lots of tiles. But *some* kind of visual splash is routine (I would say expected) for plotting libraries
  * https://matplotlib.org/
  * https://plotly.com/
  * https://seaborn.pydata.org/
  * https://d3js.org/
  * http://holoviews.org/
  * https://www.anychart.com/

  The project can work with chris on this or (I think) NF is also getting an in-house designer, which might be a possibility. But that's also outside he scope of GSoD so I think the task for now is just to decide and document what approach is best for us, so we can plan for later

**Comment by tcmetzger** [comment]
@bryevdv Something seems to have gone wrong with my changes to the CSS - this is why the thumbnails look strange and why we lost the colors. All of these things work in my local environment, so I'll check what went wrong with my commits.

**Comment by tcmetzger** [comment]
The issues @bryevdv head with the CSS seem to be a local problem. Force reloading the page in the browser (Shift+reload or Ctrl+reload) seems to fix this. As far as I can tell, the CSS in this PR works as it should.

**Comment by pavithraes** [comment]
The cards look super nice! Yayy! Thank you @tcmetzger ! ^>^

I see the mini gallery is hidden on small screens, maybe we can open an issue for any new contributor to take a look at it in the future. What do y'all think?

**Review by pavithraes — APPROVED** [review]

**Comment by tcmetzger** [comment]
Thanks, @pavithraes! Yes, I could not get the boxes to behave properly on the smallest screens. I forgot to fix this in time, sorry about that. I just opened a new pull request on a new branch (#10532) to fix the CSS for this.

**Pull request merged**
