### PR TITLE
Feature/blaze blueprint

### PR DESCRIPTION
**Pull request by hhuuggoo**

### CODE REVIEW

**Comment by hhuuggoo** [comment]
#1635

**Comment by hhuuggoo** [comment]
@bryevdv this is mostly ready - the only outstanding issue is that on Travis, the function scipy.misc.imresize does not exist - I think this is because PIL is not installed - but I'm not sure how we should handle this because I couldn't find a PIL package for python 3.

maybe we just skip the test alltogether for now?

The syntax for using the blaze data sources is a bit clunky right now cause you have to specify the json expr.  We can add a routine for generating the blaze data source directly from a blaze object which will make it nicer, but I was going to add that afterwards in a separate PR

**Comment by bryevdv** [comment]
Is PIL only needed for the test? If so, ideal to skip only for py3 but ok to skip altogether for now. If PIL is a real dependency we need to find a py3 pkg or find an alternative.

**Comment by pzwang** [comment]
Can we monkeypatch `imresize` to work with Pillow on Py3k?
https://github.com/python-pillow/Pillow

In any case, I don't think this test is worth holding up the merge.  But definitely create an issue for this.

**Comment by hhuuggoo** [comment]
oh great!  looks like if we install pillow then scipy.misc.imresize exists in both py3 and py2

**Comment by damianavila** [comment]
Just a corner comment: Nice to see Pillow enable the `imresize`... some time ago I tested with Pillow and it was not working so I switched to PIL... Pillow is better, so great it is working!

**Comment by bryevdv** [comment]
@hhuuggoo is this ready? It needs some docs for the examples, I can add some tomorrow but it would be good to merge this tomorrow if possible.

**Comment by hhuuggoo** [comment]
you mean comments on examples?  I was going to add some sphinx docs, but I wanted to do that separately (unless you prefer in same pr, but this is getting large)

Yes I think this is ready after a review - there are some usability enhancements to make, but again - separate PR.

Before merging we should have a discussion about dependencies.  The additional dependencies are 
-  blaze (current production release)
-  into (based on master - I have a conda package in the bokeh channel)
- multiuserblazeserver (based on master - I have a conda package)

Not sure if you want to wait for a real into release - I can talk to @mrocklin about that, he said it would not take long to push one out.  I can release the multiuserblazeserver immediately

**Comment by mrocklin** [comment]
I technically did a release for into a couple hours ago (version 0.1.4).  I didn't publicize it though (well except for [this blogpost about into generally](http://matthewrocklin.com/blog/work/2015/02/03/Into/)) and will likely release again before strata.

I've also been thinking about making two blaze packages, one with minimal dependencies (`numpy`, `pandas`, `into`, `sqlalchemy`) and one with everything (`hdf5`, `bcolz`, ...)  If this would ease hearts and minds in bokeh-land let me know.

**Comment by bryevdv** [comment]
BTW can we just call it `blaze-server` or if we must, `multiuser-blaze-server`

**Comment by hhuuggoo** [comment]
@JosephCottam can you have a look?

thanks

**Comment by JosephCottam** [comment]
The changes look solid, but not all of the server examples are updated as yet. 

Of the files in examples/plotting/server that use remote data sources, only blaze_source.py and abstractrender.py are currently working.  census.py, remote_image.py, serversource.py all fail on client-side execution due to changes in datasource setup parameters.

**Comment by hhuuggoo** [comment]
@JosephCottam I think census was the only one I didn't update - serversource, remote_image should have all been updated i thought?  what is the error you are getting?  I am getting additional errors on a few examples due to color maps being missing - I think this is unrelated and we should merge and then fix that problem later

**Pull request merged**
