### PR TITLE
Don't rely on test markers

### PR DESCRIPTION
**Pull request by bryevdv**
The way I updated the files left some extra vertical space but it will be changed anyway when black formatting is applied.

### CODE REVIEW

**Comment by bryevdv** [comment]
It's going to take a little doing to get the tests that need nonblocking subprocess stdout working (they were just being skipped silently and unintentionally before)

**Comment by mattpap** [comment]
> It's going to take a little doing to get the tests that need nonblocking subprocess stdout working (...)

Is this relevant to keep this PR open?

**Comment by mattpap** [comment]
> The way I updated the files left some extra vertical space but it will be changed anyway when black formatting is applied.

Let's not rely on things that weren't agreed on. This could have been removed easily by a simple `sed` command (`sed -i '/@pytest\.mark\.unit/d' $(git ls-files | grep '\.py$'`),  On a side note (there is no issue for this for me to comment on, just a stray PR) I changed my mind to a definitive no.

**Comment by bryevdv** [comment]
> Let's not rely on things that weren't agreed on. 

I don't insist on very much, but I am in the Python codebase much more than anyone else and I I'm going to be insistent on this one. It is quickly becoming standard and expected, removes doubt and room for disagreement, improves diff performance, is automatible and maintainable,  under test. I don't love everything about it myself, but it is the right thing to do.

**Comment by bryevdv** [comment]
> Is this relevant to keep this PR open?

To answer the first question: the tests, now that they are running, are failing.

**Pull request merged**
