### PR TITLE
Feature/arrow annotation

### PR DESCRIPTION
**Pull request by canavandl**
Extreme WIP for arrow annotation. Opened PR to share issue.

### CODE REVIEW

**Comment by canavandl** [comment]
example:

```
from bokeh.plotting import figure, show, output_file

from bokeh.models.annotations import Arrow

output_file('web.html', mode='absolute-dev')

p = figure(width=600, height=600)
p.scatter(x=[1,2,3], y=[1,2,3], size=25)

arrow = Arrow(plot=p, xs=[200,200,300], ys=[100,200,200])
p.renderers.append(arrow)

show(p)
```

**Comment by bryevdv** [comment]
I wonder if we should make some small types to encapsulate different arrow types (V, triangle, diamond, swept/curvy, just a few that come to mind, I am sure there are others). On the JS side these would all have a common interface that can accept: canvas context, tip position, angle, and size. These would not be full fledged renderers, but just little objects that the `Arrow` renderer could delegate to. Then it's easy to add new arrowhead types (even as user extensions) but it does not have to be a heavy weight renderer.

**Comment by damianavila** [comment]
This is WIP since a month ago... @canavandl do you intent to continue working on this right now... otherwise I will close it (per BEP-1) and you can reopen when you have some time to asdress it...

**Comment by bryevdv** [comment]
@damianavila I am going to try to finish up this and the other annotation PR this weekend, they are both very close to ready.

**Comment by damianavila** [comment]
> @damianavila I am going to try to finish up this and the other annotation PR this weekend, they are both very close to ready.

OK!

**Comment by bryevdv** [comment]
@canavandl @damianavila Actually I am going to try to bring some of the JS and python project and class structures into closer alignment to support some more general ideas I have had about annotations first. I will close this after all for now (but keep the branch to possibly use later)

**Comment by canavandl** [comment]
thanks guys!

**Pull request closed without merging**
