### PR TITLE
Add support for zero-latency tap

### LINKED ISSUE #6826: Tap events not registering during MouseMove events
I'm working on an interactive animation running on the bokeh server. Glyphs move around the figure and users are instructed to click on these while in transit. I noticed that Tap events only registered back on the server when the mouse was stationary. I figured this was due to some kind of bottleneck sending events back to the python environment from the client.  Thus, I modified the CustomJS example found [here](https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/callbacks.html#userguide-interaction-jscallbacks) to see if these Tap events registered on the client side (see below). This does not seem to make a difference—if you slowly move the mouse around the figure and click (or double-click) you will not see tap (or double-tap) events register. The mouse must be stationary to register taps.

This behavior was described as unexpected by @bryevdv  on the [google group](https://groups.google.com/a/continuum.io/d/msg/bokeh/CZ_gy1KV3UM/rpaImvEDCgAJ).

Is it possible to glean tap events while moving the mouse?

Minimal example:
```
import numpy as np
from bokeh.io import show, output_file
from bokeh.plotting import figure
from bokeh import events
from bokeh.models import CustomJS, Div
from bokeh.layouts import row

def display_event(div, attributes=[], style = 'float:left;clear:left;font_size=0.5pt'):
    "Build a suitable CustomJS to display the current event in the div model."
    return CustomJS(args=dict(div=div), code="""
        var attrs = %s; var args = [];
        for (var i=0; i<attrs.length; i++ ) {
            args.push(attrs[i] + '=' + Number(cb_obj[attrs[i]]).toFixed(2));
        }
        var line = "<span style=%r><b>" + cb_obj.event_name + "</b>(" + args.join(", ") + ")</span>\\n";
        var text = div.text.concat(line);
        var lines = text.split("\\n")
        if ( lines.length > 35 ) { lines.shift(); }
        div.text = lines.join("\\n");
    """ % (attributes, style))

p = figure(tools="")
div = Div(width=1000)
layout = row(p, div)

## Events with attributes
point_attributes = ['sx','sy']                     # Point events
point_events =  [events.Tap, events.DoubleTap]
for event in point_events:
    p.js_on_event(event,display_event(div, attributes=point_attributes))

output_file("js_events.html", title="JS Events Example")
show(layout)
```

My environment that produces this behavior:
OSX 10.12
python 3.6.1
bokeh 0.12.5, 0.12.6, 0.12.7
chrome 60.0.3112.101, safari 10.0, firefox 55.0.3

### LINKED ISSUE #8508: Tap event latency
The Tap event does not kick in directly. It takes place after a short timeout which can be unwanted for some applications (see below). Apparently, as discussed [here](https://groups.google.com/a/continuum.io/d/msgid/bokeh/62C55C5B-4D99-4897-BFB9-EFB7FC7DA6B3%40gmail.com?utm_medium=email&utm_source=footer) the underlying gesture event library used probably has to delay recognition of single tap events long enough to determine that the tap is not actually just the start of a double tap. It would be nice if the user could choose to remove this timeout for more reactive click interactions.  

Here an example where things do not work as expected:
I want to fit curves on a background image. For that purpose I plan to:
1) use the MouseMove event to update on real time some (quite complex) curve which pass where the mouse is. 
2) use the Tap event to freeze/unfreeze the curve to stop updating the curve shape when at the right location. 

Due to this timeout, when I click at the wanted curve position and then move the mouse some where else some MouseMove events occur before the Tap event kicks in, which is very frustrating.

A minimal code with screencast below. I click on the purple square and move the mouse to the right. Instead of staying at the tap location, the curve follow the mouse during the Tap timeout. 

```
import numpy as np
from bokeh.plotting import figure, curdoc
from bokeh.models import Span
from bokeh.models.widgets import Div
from bokeh.events import Tap, MouseMove

# controls if mouse positions update shape property
active = False 

p = figure(x_range=(0, 1), y_range=(0, 1))

# any background image 
img = np.random.randint(0, 255, (3, 3, 4), 'uint8') 
p.image_rgba(image=[img], x=[0], y=[0], dw=[1], dh=[1]) 

# any (complicated) shape
shape = Span(location=0, dimension='height') 
p.renderers.extend([shape])

# freeze/unfreeze shape
def tap_callback(event):
    global active
    active = not active
    
def shape_callback(event):
    if active:
        # any (complicated) shape update 
        shape.location = event.x
    
p.on_event(Tap, tap_callback, shape_callback)
p.on_event(MouseMove, shape_callback)

curdoc().add_root(p)
curdoc().add_root(div)

```

### LINKED ISSUE #13071: [BUG] Pinching zoom-in on touch devices
### Software versions

Python version      :  3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
IPython version     :  7.34.0
Tornado version     :  6.1
Bokeh version       :  3.1.0
BokehJS static path :  ...\anaconda3\lib\site-packages\bokeh\server\static
node.js version     :  v18.15.0
npm version         :  9.5.0
Operating system    :  Windows-10-10.0.19041-SP0

### Browser name and version

Google chrome for android: version 111.0.5563.116

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

Pinch zoom in and out in android device (google chrome browser).

### Observed behavior

When zoom scroll is activated, pinching to zoom in a 2D plot on touch android browser result in zooming in of the browser viewport instead of the plot. 

### Example code

```Python
import numpy as np
from bokeh.plotting import figure, show
from bokeh.plotting import figure, output_file, save

a = np.array([[1,2], [3, 4]])
p = figure(x_range=(0, 2), y_range=(0, 2))

p.image(image=[a], x=0, y=0, dw=2, dh=2, palette="Spectral11")

output_file("test_pinch_screen.html", mode="inline")
save(p)
```
```


### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by mattpap**
Currently tap latency is defined by the time required to detect double tap. This makes the more common gesture (tap) annoying to work with. With the new approach, tap and double tap are not disambiguated, and if double tap occurs, it's always preceded by a tap.

This new behavior is perfectly fine in certain tools like `TapTool`, where only one of tap or double tap is handled, so disambiguation is not necessary, or `BoxZoomTool` where double tap is used to zoom out, but in that case tap event is not used. However, the new approach changes behavior of other tools like `PolySelectTool`, where it would add an additional point to the selection polygon. Most or all draw/edit tools are affected as well. All affected tools need to be redesigned to not rely on the disambiguation.

TODO:

- [x] `PolySelectTool`
- [x] `BoxEditTool`
- [x] `LineEditTool`
- [x] `PolyEditTool`
- [x] `PolyDrawTool`

fixes #13071
fixes #8508 
fixes #6826

### CODE REVIEW

**Comment by bryevdv** [comment]
I am :-1: on including this in for 3.1 so late in the cycle.

**Comment by mattpap** [comment]
I came to the conclusion that trying to figure out a better design for poly select and edit tools in this PR is waste of effort, because they need tooling that's being currently developed for the broad "tool modality and annotations" tasks. Thus I figured that the simplest way to finalize this PR is to change double tap gesture to press gesture (together with some minor UI event handling changes). This way we finally get zero latency tap and tools that function exactly as before, except for the changed gesture. There will be a follow-up to this PR in near future, thus I consider this PR a step towards a goal and not the final product for bokeh 3.4.

**Comment by bryevdv** [comment]
@philippjfr this seems like a pretty significant change for the UX of edit tools, can you comment?

**Comment by mattpap** [comment]
The original approach wasn't robust enough, mixing our logic with hammerjs'. Thus I incorporated some of the changes I planned for removal of hammerjs into this PR. With these changes, handling of single point gestures, i.e. tap (doubletap), press (pressup) and pan gestures, is solely handled by us (via pointer events). What remains to be done in a future PR, is to implement two point gestures (pinching and rotation) and replace usage mouse events for hover with pointer events, which will give us a completely unified gesture handling solution.

**Comment by bryevdv** [comment]
@mattpap maybe I am misunderstanding the changes in the PR. Two questions:

* double-tap still exists in general? 
* edit tools now use press instead of double-tap?

**Comment by mattpap** [comment]
> double-tap still exists in general?

Yes it still exists, but now double-tap always consists of two events, a tap event followed by a double-tap event, thus the "no disambiguation" part of this change. Tools can still use either one (no change here) or both, but in the case of both they must implement behaviors for those gestures that aren't at odds with each other. Preferably double-tap functionality should be an extension of tap functionality. For example, let's say we have a tree widget representing a directory structure with files. Tapping on a tree item may select a directory or file, while double tapping would open its contents, if applicable. It's natural to assume that showing a file's contents should be preceded by selection of that file. That's contrary to how some of the existing tools implement those gestures, thus the need for replacing double-tap gesture with press gesture. 

> edit tools now use press instead of double-tap?

Yes, that's the simplest change that can be made to keep affected tools working without a major redesign and thus resulting in minimal breaking change in tool behavior. In the longer term those tools will be redesigned (that's already in progress), because  if those tools weren't so complex, they wouldn't need additional gestures (like previously double-tap and now press) in the first place.

**Comment by mattpap** [comment]
Partially dropping hammerjs doesn't actually work, as it breaks mobile support, so I had to move forward with a full replacement in this PR. So now this PR removes the need for hammerjs completely and unifies all gesture handling under one consistent implementation using pointer events.

**Comment by philippjfr** [comment]
Sorry it's taken me so long to chime in here. We discussed this briefly on Thursday and in general I agree with the goal of the PR because the latency issue is a real annoyance. In the case of the annotation tools I am a little concerned that press worsens the UX of the tool even further. 

Overall the UX of the draw/edit tools was poorly designed, partially because the gesture affordances we had at the time was poor and partially because I didn't put forward a sufficiently detailed design document that we all could have iterated on. 

Now that leaves us in a pickle, the tools do exist and are useful. What I think is missing here is a full breakdown of which tools are actually affected and how they might be redesigned now that the double tap disambiguation is no longer possible. I'd be happy to have a very rough outline of that and then merge this PR with the explicit agreement that we either all agree that the press based interaction actually is acceptable from a UX perspective or agree to a plan for a redesign to improve the UX before the 3.4 release.

**Comment by mattpap** [comment]
This is now fully ready. Everything that worked before should work now, though some tweaking may be needed in the long term.

**Comment by mattpap** [comment]
> (...) press based interaction actually is acceptable from a UX perspective or agree to a plan for a redesign to improve the UX before the 3.4 release.

I think we should do both. Double tap has its usefulness, but I view press gesture as all round more robust and especially so on touch devices. However, ultimately we should simplify and robustify affected tools, which, as I said, is work in progress and isn't that hard to achieve, but for that I need tooling I'm developing for annotations. I'm hoping we can get this settled today, so I can start building on top of this.

**Review by philippjfr — APPROVED** [review]

**Pull request merged**
