### PR TITLE
change "static" to "locally executing"

### LINKED ISSUE #3196: Retitle "Static" descriptor for serverless (server-free) examples
bokeh-gallery-server-free

Suggested by @electronwill

### PR DESCRIPTION
**Pull request by electronwill**
change "static" to "locally executing" for interactive but non server plots

Closes #3196

### CODE REVIEW

**Comment by bryevdv** [comment]
"Standalone" is the terminology we last agreed on as a team unless I'm mistaken

**Comment by electronwill** [comment]
Not sure if this is really appropriate, or if the terminology "static" is used extensively elsewhere in the project and we need to either stay consistent with it or change it everywhere. Can anyone please review this and let me know?

**Comment by electronwill** [comment]
Oh, "standalone", that's much better. Fixing now...

**Comment by bryevdv** [comment]
Are there any other places that be updated?

**Comment by electronwill** [comment]
If you don't know of any other places, I think it's ready to merge.

**Comment by damianavila** [comment]
LGTM... merging now...

**Pull request merged**
