### PR TITLE
Add method for streaming data to multi-dimensional CDS arrays

### LINKED ISSUE #13079: More efficient way to append ColumnSourceData for the figure.multi_line plot?  [FEATURE]
### Problem description

I have a `figure.multi_line` plot and would like to grow each of the lines as new streaming data comes in.  The number of lines stays constant throughout the life of the plot.  However, it is awkward to update the associated `ColumnDataSource`.  At the moment, here is a minimal example:

```python
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource
from bokeh.io import curdoc
import math

fig = figure(title='multiline-stream')
three_lines = { 'x': [ [], [], [] ], 'y': [ [], [], [] ] }
cds = ColumnDataSource(three_lines, name='mls')
fig.multi_line(xs='x', ys='y', source=cds)

global_x = 0

def append_to_lines():
    global global_x
    cds = doc.get_model_by_name('mls')
    if cds is None:
        print(f'cds is None')
        return
    data = cds.data
    offsets = (2.3, 3.1, 0.5)
    for line in range(3):
        data['x'][line].append(global_x)
        data['y'][line].append(math.sin(offsets[line] + global_x))
    global_x += 1

    # This works - but, does it do a deepcopy of `data`?  If not, then I suppose it's fine but it seems
    # weird.
    cds.data.update(data)


def work():
    doc.add_next_tick_callback(append_to_lines)

doc = curdoc()
doc.add_root(fig)

doc.add_periodic_callback(work, 1000)
```

### Feature description

I would like to avoid a deepcopy when calling `ColumnDataSource.data.update`.  Perhaps a more natural way to express line data for a `figure.multi_line` would be a nice alternative as well.

### Potential alternatives

I have a minimal working example of an alternative.

Broadly speaking, my sense is that the intention behind the `ColumnDataSource.stream` method was for streaming data.  The most natural notion of a multi-line plot to "stream" data is not to add new lines, but to grow existing lines.  So, my proposal would be to have a second option for how the multi-line data actually consumes the data in `ColumnDataSource` from the server side such that this growing of lines works naturally with `ColumnDataSource.stream`.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by benrussell80**
- [ ] issues: fixes #13079 
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by benrussell80** [comment]
Example usage of new method. Works for the happy path (correct sizes) and only for lists.

```py
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource
from bokeh.io import curdoc
import random

def rand():
    return random.randint(0, 10)

fig = figure(title='multiline-stream')
source = ColumnDataSource({
    'xs': [ [0, 1, 2], [0, 1], [0, 1] ],
    'ys': [ [1, 2, 3], [5, 4], [10, 9] ]
})

fig.multi_line(source=source)

def work():
    xs = source.data['xs']
    source.multi_stream({
        'xs': [ [len(xs[0]), len(xs[0]) + 1], [len(xs[1])], [] ],
        'ys': [ [rand(), rand()], [rand()], [] ]
    })

doc = curdoc()
doc.add_root(fig)

doc.add_periodic_callback(work, 1000)
```
Need to
- [ ] Account for non-list array types
- [ ] Account for and catch cases when inputs' lengths are not acceptable
- [ ] Emit correct event
- [ ] Document methods
- [ ] Accept rollover/rollovers parameter (?)

**Comment by bryevdv** [comment]
Hi @benrussell80 you dived right into a very low-level part of Bokeh 😄 I don't think that using `ColumnDataChangedEvent` is going to satisfy the "efficient" part of the originating issue, unfortunately, since it will re-send the entire `.data` dict every time. The defining characteristic of streaming is that it only sends marginal updates for the new portion of data. So, I think we will want to create a new `ColumnsMultiStreamedEvent` to complement `ColumnsStreamedEvent`. 

I'm happy to help collaborate or offer additional guidance, what do you think?

Edit: 

> and only for lists.

And we will need to handle arrays/series as well, which is probably where a good amount of complexity will come from, tho the current `.stream` should offer a blueprint that can be repeated at a sub-series level

**Comment by benrussell80** [comment]
Hey @bryevdv yeah I figured that a new event type would be needed. That was the only one that would make the update work when I tested it out. I'd be happy to continue contributing with your help. I don't know much about BokehJS. Would this method need to be added there as well?

**Comment by benrussell80** [comment]
@bryevdv one hurdle I'm running into is how to validate the columns passed in new_data.

Take this example. multi_stream can't require that all columns are passed in (like stream does) because some are not multidimensional.
```py
source = ColumnDataSource({
    'color': ['red', 'blue'],
    'xs': [ [0, 1, 2], [3, 4, 5] ],
    'ys': [ [7, 6, 5], [2, 3, 4] ],
})

p = figure()

p.multi_line(source=source, color='color')

...

source.multi_stream({
    'xs': [ [3], [6] ],
    'ys': [ [4], [5] ],
    # colors is not passed in because the number of lines doesn't change
})
```
How do you think this should work from a UX perspective? Should it just be on the user to ensure that the data they are passing is valid, and Bokeh will do the appends to whatever they pass. Also tied into this is validating lengths. What if the user only passes in 'xs'?

**Comment by benrussell80** [comment]
@bryevdv Can you take a look at the JS side when you get a chance? I basically copied the types and methods for streaming. It runs without error, but I don't know what to do to get the `.emit()` method to work.

I still need to do some length checking, and get the Python side to work with Pandas types.

**Comment by bryevdv** [comment]
@benrussell80 deep apologies this fell off my radar and then I got over-busy elsewhere. If you are amenable to picking this back up I can commit to shepherding it more closely. Regarding UX this is a use-case that you are close to so I am inclined to start with whatever makes sense to you as a concrete draft and then go from there. 

@mattpap can you give this a quick once-over from the BokehJS side?

**Comment by benrussell80** [comment]
Hey @bryevdv no worries at all. Yeah I can work on this some more.

**Comment by bryevdv** [comment]
@benrussell80 do you still expect to be able to pick this PR back up? If not I understand, but it's starting to gather conflicts so it should probably best be closed at this point, in that case.

**Comment by benrussell80** [comment]
Sorry as much as I'd like to I don't think I can

**Comment by bryevdv** [comment]
Understood @benrussell80 we'll keep the issue open since it seems like a reasonable thing for someone to work on if they have the opportunity.

**Pull request closed without merging**
