### PR TITLE
Update `plotting/css_classes.py` to use stylesheets

### LINKED ISSUE #12883: css_classes example not working
Styles are no longer being applied in the ouput:

Screenshot 2023-03-02 at 11 58 50

I noticed this when trying to include this example in the docs but it happens when run directly as well. (OSX, Safari and Chrome)

### PR DESCRIPTION
**Pull request by mattpap**
image

fixes #12883

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap I expect almost all usage of `css_classes` to be with users using their own templates with their own stylesheets directly in their template, e.g. corporate branding styles etc. That's been 100% of historical usage until this point. Is that no longer possible?

**Comment by mattpap** [comment]
CSS classes from global stylesheets are not visible in shadow DOM. The only way to influence style within a shadow DOM component is to either add a stylesheet to the shadow element (what's done here), use CSS variables, or rely on CSS inheritance where applicable. The old-style approach of having a single CSS file with a mixture of different classes and complex selectors isn't going to work anymore.

However, one can get pretty close to this if said stylesheet is added to every relevant component (can be done via a theme) and assuming that host elements (the ones that contain shadow elements) aren't styled (which is not the case in this example; thus `:host` pseudo selector is needed). If you're styling only inner elements, e.g.:
```html
<div class="bk-Div">
  <shadow>
    <style>
    .inner_element {
      // styles  
    }
    </style>
    <div class="inner_element>Content</div>
  </shadow>
</div>
```
then existing CSS should mostly work (fonts won't and can be added only globally).

**Comment by mattpap** [comment]
There's a possibility to create a compatibility mode, where a CSS stylesheet would be parsed and `:host` selector applied, but it may be hard to do with complex selectors.

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
@mattpap can you start and switch to branch-3.2 after you merge this? I will forward port any docs/release  PRs

**Comment by mattpap** [comment]
Sure, I was about to do it soon anyway. Just to note, I started rc1 build 14 minutes ago.

**Pull request merged**
