### PR TITLE
Tornado 5 Compatibility 

### LINKED ISSUE #7308: Tornado 5.0 compatibility
Note that the next verion of Tornado, 5.0, will include breaking changes which break the existing Bokeh test suite.

### PR DESCRIPTION
**Pull request by bryevdv**
- [ ] issues: fixes #7308
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@mrocklin did you have a chance to test with this PR? I am going to do some more but it would be good to have more data points. I'd like to merge this then make a separate issue for updating the CI to test with both tornado 4 and 5 later.

**Comment by mrocklin** [comment]
No, I haven't.  I invested the time to set up a decent bokeh dev setup on
this machine.

**Comment by mrocklin** [comment]
I *haven't* invested

**Comment by bryevdv** [comment]
Unit tests pass and a selection of app examples seem to run as expected in both t4 and t5 environments, so I am going to go ahead and merge to get into a dev build

**Comment by mrocklin** [comment]
Thanks Bryan

**Comment by mrocklin** [comment]
Dev builds happen nightly or on merge to master?

**Comment by bryevdv** [comment]
They are explicitly triggered. I will try to get one out today.

**Comment by bryevdv** [comment]
@mrocklin `0.12.14dev7` is available

**Comment by mrocklin** [comment]
Thanks, I'll try things out and report back.

**Comment by mrocklin** [comment]
From a dask perspective bokeh + tornado 5.0 run well.  Thanks for the
efforts here.

**Pull request merged**
