### PR TITLE
Refactor Charts for Table-like (x,y) Inputs

### PR DESCRIPTION
**Pull request by birdsarah**
Supercedes  #2720 with a branch on bokeh repo.

### CODE REVIEW

**Comment by bryevdv** [comment]
OK, @birdsarah can you supersede the other PR?

@damianavila @fpliger @rothnic @birdsarah Here is my plan: I will spend the rest of today cleaning up this PR, adding `_legacy_charts`, making examples work, etc. Then hopefully in the morning (CST) we merge and @damianavila will feel more reassured about the state of things. :) Does this sound agreeable to everyone?

**Comment by fpliger** [comment]
:+1:

**Comment by damianavila** [comment]
:+1:

**Comment by birdsarah** [comment]
As something of an aside but as there's been some test jiggling lately. I'm surprised that we don't run the charts examples when we do our examples testing. More than half of them fail when run manually - as documented in my comment on #2870.

**Comment by bryevdv** [comment]
Collecting (non-blocking) issues here.

[ ] `continuous_range` on `Histogram` does not seem to work, should also accept tuples as a convenience

**Comment by fpliger** [comment]
@bryevdv as suspected the donut fixes have been lost in some merge.. I've added them back.

**Comment by pzwang** [comment]
This looks awesome!

A few comments:

[ ] The stacked_bar example still imports stuff from `bokeh._legacy_charts`
[ ] Can I do groups of BoxPlots?  It doesn't seem to work.

Can we have at least one example that shows the kind of *outer* plot customization (e.g. turning off the toolbar, etc.)?

**Comment by bryevdv** [comment]
@pzwang can update the first point in the open docs PR, later this week. Might just remove it in factor of the other example that has several subplots. 

The other point will probably have to be a later release if it does not work now.

**Pull request merged**
