### PR TITLE
Fix range_tool selection bug

### LINKED ISSUE #9267: [BUG] range_tool selection is over-responsive in y direction
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh.version: 1.3.4
Python version: 3.7.3
OS: GNU/Linux x86_64
Browser: Google Chrome 77.0.3865.90
JupyterLab version: 1.1.3

#### Description of expected behavior and the observed behavior

When the range tool is used in the y-direction, something odd happens. When the border of the selected range is dragged with a mouse, the selected border moves _twice as far_ as the mouse is moved.

In the example below, if the top of the selection is dragged down 2cm, the selected border actually goes down by 4cm.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np
import pandas as pd
from bokeh.layouts import row
from bokeh.models import ColumnDataSource, RangeTool
from bokeh.plotting import figure, show

# Prep dummy data
df = pd.DataFrame({'Y': np.linspace(0, 20), 'X': np.sin(np.linspace(0, 20))})
source = ColumnDataSource(df)

# Closeup figure
f = figure(tools="ypan", x_range=(-1, 1), y_range=(0, 20))
f.line('X', 'Y', source=source)
f.xaxis.axis_label = 'closeup'

# Selection figure
select = figure(tools="")
select.line('X', 'Y', source=source)
select.xaxis.axis_label = 'select'

# Add range tool
range_tool = RangeTool(y_range=f.y_range)
select.add_tools(range_tool)

show(row(f, select))
```
 
#### Screenshots or screencasts of the bug in action
range_tool

### PR DESCRIPTION
**Pull request by Connossor**
- [x] issues: fixes #9267
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

Edits as suggested by @bryevdv on issue #9267 . Thanks for the support getting the bug fixed!

### CODE REVIEW

**Comment by bryevdv** [comment]
@Connossor Thank you for the PR, there's just one small issues:

* The changed function name needs to be updated in the test file as well (I forgot to include this in the diff when I was in a hurry this morning)

```
          1) range_tool module
3718       compute_end_side
3719         should not flip if new end > start:
3720     TypeError: range_tool_1.compute_end_side is not a function
3721      at Context.it (test/models/tools/gestures/range_tool.ts:149:20)
3722
3723  2) range_tool module
3724       compute_end_side
3725         should flip if new end <= start:
3726     TypeError: range_tool_1.compute_end_side is not a function
3727      at Context.it (test/models/tools/gestures/range_tool.ts:157:20)
```

Changing the function name in the test file will also fix the reported linter error:

> test/models/tools/gestures/range_tool.ts:3:86 - error TS2305: Module '"../../../../build/js/types/models/tools/gestures/range_tool"' has no exported member 'compute_end_side'.

**Comment by Connossor** [comment]
Thanks for the guidance, much appreciated. I made this PR on my phone whilst waiting for a train, which is a first..

**Comment by bryevdv** [comment]
Thanks @Connossor !!

**Comment by Connossor** [comment]
Miracles do happen

**Pull request merged**
