### PR TITLE
Update cli.rst

### LINKED ISSUE #13644: Users Guide sections for server CLI is not useful
It merely links to the refguide, but even the refguide links are still a non-obvious click or two away from actual information. 

Screenshot 2024-01-08 at 10 29 26

It would be good to replicate the information here, one way or another, directly in the user's guide:

https://docs.bokeh.org/en/latest/docs/reference/command/subcommands/serve.html#bokeh-command-subcommands-serve

### PR DESCRIPTION
**Pull request by xmaniic**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [ ] issues: fixes #13644 
:no-index:

Updated CLI documentation to replicate serve information.

### CODE REVIEW

**Comment by bryevdv** [comment]
Hi @xmaniic thanks for the PR, FYI just duplicating the refguide section here results in errors:

> /usr/share/miniconda3/envs/bk-test/lib/python3.10/site-packages/bokeh/command/subcommands/serve.py:docstring of bokeh.command.subcommands.serve.Serve.name:1: WARNING: duplicate object description of bokeh.command.subcommands.serve.Serve.name, other instance in docs/reference/command/subcommands/serve, use :no-index: for one of them

As suggested you could add `:no-index:` to the top of this page to prevent the warnings. 

Alternatively, we can move almost all the ReST content out of the `serve.py` module, and into `cli.rst` insted. Arguable, the reference guide for `bokeh.commands.subcommands.serve` should really cover the API usage and not the CLI usage. 

I 'd actually suggest trying the second approach (moving everthing to `cli.rst`) but I will accept the current PR with `:no-index` added if you don't have more bandwidth.

**Comment by bryevdv** [comment]
Also, FYI I think the linked issue at the top is incorrect (this link is to this PR itself)

**Comment by xmaniic** [comment]
I added :no-index: to my pull request message, is that the spot you were referring to?

And yes, I can go ahead and move the REST info over to cli.rst.

**Comment by bryevdv** [comment]
> I added :no-index: to my pull request message, is that the spot you were referring to?

No the `:no-index:` would be added to `cli.rst` however if you are going to move the ReST content out of `serve.py` and into `cli.rst` then it will not be necessary.

**Comment by bryevdv** [comment]
@xmaniic did you intend to continue working on the PR?

**Comment by bryevdv** [comment]
@xmaniic checking one more time, do you expect to continue on this PR? If not that's fine but should be closed.

**Comment by bryevdv** [comment]
Closing for lack of response.

**Pull request closed without merging**
