### PR TITLE
Executing range callbacks on reset_range (additional fix) and initialization (new)

### LINKED ISSUE #4614: Reset tool does not trigger x/y_range callback events
The reset tool obviously changes the extents of the axes, which should trigger any callback events attached to them but it does not appear to. I could swear there was an issue about this that was closed recently, but I can't find it now so I'm probably misremembering. I've tested it as part of 0.12rc1 and it still appears to be an issue there. This functionality is important for downsampling or any other callbacks that depend on the zoom level such as we make use of in datashader.

### PR DESCRIPTION
**Pull request by schlichtanders**
I experienced update issues with #4615, concretely the range callbacks are not executed correctly. I had to call reset twice for my callbacks to work correctly. This pull request fixes this.

Additionally I added the analog calls to the callbacks within the initialization such that dynamic ``update_datarange`` is followed by a call to the callbacks here too.

It may be preferable to move the callback executions to ``update_datarange`` directly

- [x] issues: fixes #4614 #4615
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
ping @canavandl @mattpap

**Comment by canavandl** [comment]
hi @schlichtanders 

I think the solution to range callbacks not executing properly is to move the `execute` logic onto the range models themselves. That'd simplify the several places in the code where range attributes (often pertaining to ranges of different types) are changed.

I think it would be as simple as adding an `change` eventListener to the range models and making sure that the public methods (`update` and `reset`) cause the callback to be called once and only once.

Also - do you have a [mcve](http://stackoverflow.com/help/mcve) that you can share, where the range callbacks aren't executed? That way we can make sure that your use case is corrected by any changes.

thanks again for contributing!

**Comment by schlichtanders** [comment]
thanks @canavandl
it is good to hear, that this in fact could become an improvement of bokeh

I agree, putting everything into the range model seems appropriate. Next
week I have more time and will look into this probably. However, these are
indeed my first true javascript/coffeescript experiences. So might be that
I get stuck soon.

I thought a kind of minimal working example is
http://bokeh.pydata.org/en/latest/docs/user_guide/interaction/callbacks.html#customjs-for-range-update
(because I copied from it) however, that one seems to work properly with
*reset. *(initialization still does not update the rectangle).
Don't know, what I did differently... maybe it is the use of concrete times
as x-axis. Will check that out

best,
Stephan

**Comment by schlichtanders** [comment]
one weak later, I have to admit, that I won't have enough time to fix by myself.

would be great if someone else could bring the callback executions to the right place within the range model

**Comment by canavandl** [comment]
superceded by #5253

**Pull request closed without merging**
