### PR TITLE
Fix resizing of embedded plots

### LINKED ISSUE #4110: Plot resizing is broken
In particular the example `embed_responsive_width_height.py`. This also breaks our phosphor+Bokeh demo.
In v0.11.1, the DOM looks like:
```
<div class='bk-plot'>  <-- this is what @el refers to
  <div class='bk-plot-wrapper'>
       <table> ... etc.
```

In master, the DOM looks like:
```
<div class='bk-root'>
    <div>  <-- this is what @el refers to
        <div class='bk-plot-wrapper'>
             <table> ... etc.
```

To resize, the plot queries the `clientWidth`and `clientHeight` of the parent node of its element. But this now fails, because of the extra layer.

As for a solution, I tried two things that both seem to work:
* Use the client size of `@el.parentNode.parentNode`. Or maybe safer: traverse upwards until meeting a node that is `bk-root`.
* Use client size of `@el.parentNode`, but set the CSS `height`of the `bk-root` to 100%.

Tasks:
* [x] @birdsarah @mattpap is that `<div>` intended? --> Yes
* [ ] Maybe not crucial for this issue, but somewhat related: there are still references to bk-plot in the code, was that supposed to be removed, or should the classless div above be a `bk-plot`
* [x] Fix the issue.
* [x] Selenium test to avoid having another regression like this (working on it)
* [x] Shortcut to allow (Phosphor) to set the width height to specific values, to avoid a DOM measurement.
* [x] Typing for `plot.resize_width_height()`

### PR DESCRIPTION
**Pull request by almarklein**
fixes #4110, supersedes #4120

### CODE REVIEW

**Comment by almarklein** [comment]
cc @mattpap @birdsarah 

@mattpap you want me to put back some of the improved styling that you did? Or do you want to do that?

**Comment by mattpap** [comment]
> You want me to put back some of the improved styling that you did? Or do you want to do that?

No and no. I need to rethink those.

**Comment by almarklein** [comment]
I was planning to add back in some of the improvements that @mattpap did, but I'm out of time now. I propose we merge this now, so that Dave can proceed with a working plot.

**Comment by mattpap** [comment]
Sure, lets merge. As to the other modifications, I think we will have to wait for @birdsarah's PR(s). We have to reduce the number of embedding possibilities and perhaps always use a layout (even a trivial one) and then embed a plot.

**Comment by bryevdv** [comment]
> Sure, lets merge. 

OK, looks good as far as I can tell, though I am not an expert in this area. I do like the smaller scope of this PR.

**Comment by birdsarah** [comment]
> We have to reduce the number of embedding possibilities and perhaps always use a layout (even a trivial one) and then embed a plot.

I think that's the direction I'm going in. I'm writing something up at the moment.

**Pull request merged**
