### PR TITLE
Update docs CSS

### PR DESCRIPTION
**Pull request by tcmetzger**
This PR is related to #12203 and fixes some theme-related issues.

### CODE REVIEW

**Comment by tcmetzger** [comment]
@bryevdv This PR adds the config option `"default_mode": "light"` to make the docs default to light mode (https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html#configure-default-theme-mode).

I have also looked into the search results, but I haven't found an easy way to remove the extra whitespace. I have added some minimal styling to make the results a little more legible, but it seems like search will see a major overhaul in the upcoming version of the theme (https://pydata-sphinx-theme.readthedocs.io/en/latest/search.html), so I wouldn't want to invest too much time here.

**Comment by bryevdv** [comment]
I think the heavy looking attr values in the docs might also be a CSS tweak.

**Comment by tcmetzger** [comment]
@bryevdv Which attr values do you mean, can you post a screenshot/example?

**Comment by bryevdv** [comment]
That's weird I added the info to the misc issue, but somehow it never got saved. I mean the values on the RHS of equals sighs on e.g. this page: https://docs.bokeh.org/en/dev-3.0/docs/reference/core/enums.html

Screen Shot 2022-07-08 at 13 39 41

I think the values would be a lot more distinguishable from the var names with a lighter weight. Currently things just really run together.

**Comment by tcmetzger** [comment]
Got it! I've updated them to be less heavy!
image

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
LGTM

**Pull request merged**
