### PR TITLE
Replace mpl.show(...) with show(...)

### PR DESCRIPTION
**Pull request by mattpap**
Followup on PR #1634.

### CODE REVIEW

**Comment by damianavila** [comment]
LGTM, it needs master merged in... but we can merge as is after TravisCI finished...

**Comment by mattpap** [comment]
>  it needs master merged in

Why? Github doesn't indicate anything. There was spurious travis-ci failure (conda fetch hanged).

**Comment by damianavila** [comment]
>Why? Github doesn't indicate anything. There was spurious travis-ci failure (conda fetch hanged).

Sorry, I miscommunicate my thoughts... it does not need master because it will merge cleanly... what I wanted to say was that if master is merge in the "actual" last changes can be seen... but forget about that... I will merge this as soon as TravisCI succeed.

**Comment by mattpap** [comment]
Conda fetch hanged again.

**Comment by damianavila** [comment]
build 3259 passed https://travis-ci.org/bokeh/bokeh/builds/46327887, so merging this one now...

**Comment by mattpap** [comment]
That's just magic. When I checked, it was in failure state, thought now it shows it passed. Note that the commit still has grey cross indicating timeout failure.

**Comment by damianavila** [comment]
Remember you have two build runs: one for the branch 3258 and the other for the PR 3259... they are testing essentially the same... the grey cross is pointing to 3258, I don't know why is not pointing to 3259 which was successful... I guess probably inform us the first one to complete, but not sure...

**Pull request merged**
