### PR TITLE
Interactive example: U.S. marriages and divorces chart with tooltips

### PR DESCRIPTION
**Pull request by rhiever**
I'd like to add my Bokeh chart from [this post](http://www.randalolson.com/2015/06/15/144-years-of-marriage-and-divorce-in-1-chart/) to the example gallery. I think it would be helpful to have a working example of a chart with custom tooltips with real data so people can copy-and-paste and mash in their own data from there.

I've committed the following files:

* bokeh/sampledata/us_marriages_divorces.csv: The data file that I compiled for the project

* bokeh/sampledata/us_marriages_divorces.py: Loads the data file from the `sampledata` module

* examples/interactions/us_marriages_divorces/us_marriages_divorces_interactive.py: Python script that generates the interactive chart with tooltips

* examples/interactions/us_marriages_divorces/us_marriages_divorces_interactive.ipynb: IPython Notebook version of the above

* examples/interactions/us_marriages_divorces/us_marriages_divorces_per_capita.html: The output of the Python script for your review

I've added (probably-more-than-necessary) comments throughout the scripts so the readers have a general idea of what the code blocks are doing.

Thank you for your consideration.

### CODE REVIEW

**Comment by chendaniely** [comment]
The test is failing due from a flake8 failure:

`bokeh/sampledata/us_marriages_divorces.py:22:8: F821 undefined name 'md_data'`

https://travis-ci.org/bokeh/bokeh/jobs/70526599#L2159


and per @bryevdv, we do not need the html file

**Comment by birdsarah** [comment]
Hi @rhiever, thanks for the awesome example.

It's interesting that you said it would be "helpful to have a working example of a chart with custom tooltips," there are at least three examples already:
* /glyphs/colors.py
* /glyphs/sprint.py
* /interactions/interactive_bubble/gapminder.py (although that one's a little thin!)

The problem clearly is that they weren't findable. Maybe we can rename your example something like `custom_tooltips.ipynb` to make it clear that this is what this example is showing off.

We have an outstanding issues to better tag & index examples  #1032

**Comment by damianavila** [comment]
To proceed with this...

@birdsarah, since you upload some data to S3 lately... can you upload the data on this PR in that bucket?

@rhiever can you please remove the generated html file and also make the modifications to be flake8 compatible?

Thank you both!!

PS: @birdsarah, when I talked with @rhiever, he told me that he was interested in better maps support and I know you are/will be working on this soon. He seems to have experience in that matter, can you ping him when the conversations happens? Thanks!

**Comment by damianavila** [comment]
Also, one more thing @rhiever, the example should be updated to use 0.9.1 instead of 0.9.0... thanks again!!

**Comment by rhiever** [comment]
This is on my to do list. I agree with @birdsarah that the example gallery could use more organization - I didn't see those examples on the web site. Perhaps an issue for the (near?) future. :+1:

**Comment by rhiever** [comment]
@damianavila: I hope the recent commit fixes all of those things, including the version used. Should I also rename the files as per @birdsarah's comments above? I see the value of naming the example according to what it's showing, but it could also be useful to know what the example is.

**Comment by bryevdv** [comment]
@rhiever this is only failing from a pyflakes check:

https://travis-ci.org/bokeh/bokeh/jobs/71825892#L2143

**Comment by rhiever** [comment]
Oh! I thought the error was in the main example, but it seems the error is in the sample data file. Hopefully this commit fixed it.

**Comment by fpliger** [comment]
restarted a spurious failing test and now TravisCI is happy :-)

**Comment by bryevdv** [comment]
@birdsarah regarding the "hard to find them question" I agree but I don't think the solution is going to be found in a directory layout. Anywhere we put anything is "less obvious" for one reason, or another. Quoting @pzwang "A filesystem is not an index" So I am not too concerned about the filesystem location. The better solution (a little longer term) is to make our online gallery richer and more searchable an cross referencable. There's no reason the same plot couldn't show up in multiple categories, if the plot is tagged with some metadata in a comment or whatever. 

Given that, I'd personally (slightly) rather see this example just go in `plotting/notebook` and 'plotting/file` for now, rather than create a whole new directory under `examples` but if others like this directory structure that's ok too.

**Comment by damianavila** [comment]
After thinking a little bit on this... I think I slightly agree with you @bryevdv

**Comment by rhiever** [comment]
Agree w/ @bryevdv - directory structure isn't the issue; finding the examples on the web site (w/ working demos) is the issue.

**Comment by bryevdv** [comment]
First, apologies to @birdsarah I think I made it sound like she was advocating for solving this with directories, but that was not actually her position. 

I just realized that `examples/interactions` already exists. Given that, I guess my proposal is to merge as-is and try to schedule a time sooner rather than later to think about indexing and organizing the gallery better.

**Comment by damianavila** [comment]
>I only just realized that examples/interactions already exists. Given that, I guess my proposal is to merge as-is and try to schedule a time sooner rather than later to think about indexing and organizing the gallery better.

Sound OK to me as well.. let's get this merged.
Thanks @rhiever for your contribution, I hope to see you again here :wink:

**Comment by damianavila** [comment]
Well, I merge this one too early... I am finding some bugs now... simple to fix... I will open a PR for those changes. Sorry for the early merge...

**Comment by rhiever** [comment]
Please tag me in the PR so I know what the bugs were.

On Wednesday, August 12, 2015, Damián Avila <notifications@github.com>
wrote:

> Well, I merge this one too early... I am finding some bugs now... simple
> to fix... I will open a PR for those changes. Sorry for the early merge...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bokeh/bokeh/pull/2537#issuecomment-130413776>.
>


-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by damianavila** [comment]
Done :wink:

**Comment by birdsarah** [comment]
Great to see this in - thanks @rhiever 

@bryevdv - totally agree that we have a bigger picture issue of a better gallery. This would be a fun project!

**Pull request merged**
