### PR TITLE
VBox/HBox accepts single list as well

### LINKED ISSUE #1786: VBox/HBox should accept single list as well
Seen in the wild:
```
# `foo` is a dict with Plots as values
VBox(foo.values())
```

Need checks in these two places:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/widgets/layouts.py#L31
https://github.com/bokeh/bokeh/blob/master/bokeh/models/widgets/layouts.py#L48

to check if `len(args)==1` and if `args[0]` is a sequence (list, tuple, etc), then set `kwargs["children"] = args`

Edit: docstrings should also be updated to reflect the different ways to initialize the `children`.

### PR DESCRIPTION
**Pull request by almarklein**
issues: closes #1786

### CODE REVIEW

**Comment by almarklein** [comment]
What about testing. Are all examples run during the test?

I modified one example (graph/scatter.py) to pass a list of plots.

**Comment by bryevdv** [comment]
Yes all the python and js unit tests are run for py2 and py3 on travis on every push to a PR. Also most of the examples are run as well, and on the first travis build, images are generated and uploaded to S3 (with diffs against reference images). We aren't quite at the point of passing/failing tests based on the image diffs but they are still useful to look at. Click the link above to go to TravisCI, open up the first build, and then search for "report" to see the S3 report.

**Comment by bryevdv** [comment]
LGTM will merge when Travis passes.

**Comment by almarklein** [comment]
>  images are generated and uploaded to S3 (with diffs against reference images).

Sweet, we've been wanting that for vispy for quite a while ...

**Comment by bryevdv** [comment]
@mattpap did that work, our testing infrastructure is about 1000% better now thanks to his efforts.

**Comment by damianavila** [comment]
LGTM too...

**Comment by fpliger** [comment]
LGTM

**Comment by bryevdv** [comment]
restarted single failing test, probably spurious

**Pull request merged**
