### PR TITLE
Support bokeh app in Apache Zeppelin

### LINKED ISSUE #6788: Make notebook display extendible by external libraries
#### Description of expected behavior and the observed behavior
I'd like to embed bokeh app into Apache Zeppelin just as embed bokeh app in Jupyter

### PR DESCRIPTION
**Pull request by zjffdu**
- [ ] issues: fixes #6788
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

Manually verify it. 
screen shot 2017-08-23 at 10 18 01 am

Known issue: Server is not stopped when cell is removed.

### CODE REVIEW

**Comment by bryevdv** [comment]
@zjffdu I've already merged #6799 that provides a clean way for external libraries or projects to add their own hooks without needing to add anything to core bokeh. Zeppelin support should go though that mechanism (in an external repo or project)

**Comment by bryevdv** [comment]
To elaborate, you'll want to call:
```
bokeh.io.install_notebook_hook('zeppelin', load_func, show_doc_func, show_app_func, overwrite=True)
```
You'll need `overwrite=True` for now since I left the existing show doc machinery for now.

**Comment by zjffdu** [comment]
Thanks @bryevdv , I will do it in a separate package.

**Comment by zjffdu** [comment]
@bryevdv I created bkzep, I have manaully verify it, could you help review it ? Thanks
https://github.com/zjffdu/bkzep

**Pull request closed without merging**
