### PR TITLE
Sphinx bokeh-plot directive

### LINKED ISSUE #1305: `cd sphinx; make html` fails
Expects gallery to be in-place, but fails to depend on appropriate tasks.

### LINKED ISSUE #1694: sphinx plot extension directive
Reference: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/sphinxext/plot_directive.py

### PR DESCRIPTION
**Pull request by bryevdv**
issues: closes #1694 closes #1305

### CODE REVIEW

**Comment by bryevdv** [comment]
@bokeh/dev this is not quite ready, but it will be tomorrow. Feedback is appreciated.

**Comment by bryevdv** [comment]
I am going to try and add more error checking, logging, and some cleanup, but I think this is suffciently ready for review. I have deployed docs based off this PR here:

http://bokeh.pydata.org/en/dev/

**Comment by bryevdv** [comment]
OK there is one more missing feature, right now it can't display plots that require pulling out a specific symbol.

**Comment by bryevdv** [comment]
@mattpap docs now build with zero warnings. @bokeh/core this is ready for review, would like to merge ASAP.

**Comment by bryevdv** [comment]
Right now it is a bit chatty:
```
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  1%] docs/dev_guide
writing output... [  3%] docs/gallery
writing output... [  4%] docs/gallery/anscombe
using cached plot for '/Users/bryan/work/bokeh/examples/glyphs/anscombe.py'
writing output... [  6%] docs/gallery/area_chart
using cached plot for '/Users/bryan/work/bokeh/examples/charts/area.py'
writing output... [  8%] docs/gallery/boxplot
using cached plot for '/Users/bryan/work/bokeh/examples/plotting/file/boxplot.py'
writing output... [  9%] docs/gallery/boxplot_chart
using cached plot for '/Users/bryan/work/bokeh/examples/charts/boxplot.py'
writing output... [ 11%] docs/gallery/brewer
using cached plot for '/Users/bryan/work/bokeh/examples/plotting/file/brewer.py'
writing output... [ 13%] docs/gallery/burtin
using cached plot for '/Users/bryan/work/bokeh/examples/plotting/file/burtin.py'
writing output... [ 14%] docs/gallery/candlestick
```
I could change the messages about plot generation to debug messages if desired.

**Comment by bryevdv** [comment]
OK I went ahead and made them debug statements

**Comment by mattpap** [comment]
This is great, thought a lot to review (I didn't see any major issues). How does error reporting with `bokeh-plot` directive work? I presume we get full traceback with reliable line numbers to fix any issues with code?

**Comment by mattpap** [comment]
One thing, mostly unrelated to this PR, I noticed when checking out bokeh.pydata.org/en/dev, is that wheel scroll in examples and documentation is a bad combination.

**Comment by mattpap** [comment]
Future idea: create conda package for sphinx extensions, so that we could use those in other projects.

**Comment by bryevdv** [comment]
@mattpapp right now you get a big red error admonition block in the rendered document with the location (file, line number) of the directive in the ReST source, plus the exception message. You get his for missing file, error in file, or error in inline source. I think a full traceback would be more suited for a console warning. I'd live to add that but that and some other enhancements (mode to turn warnings into errors, etc.) can go in a follow on, I think.

**Comment by mattpap** [comment]
> (...) can go in a follow on, I think.

Sure.

**Comment by bryevdv** [comment]
> Future idea: create conda package for sphinx extensions, so that we could use those in other projects.

I absolutely want to submit `bokeh-plot` to sphinx-contrib (in isolation, the other directives are very specific to our docs). Once this is merged and in a dev release I plan to mention it on the mailing list, etc. and I I want to write two blogs about it: one to just demonstrate it (including a minimal GH repo with sphinx docs) and another more in depth describing how to write extensions like these (maybe help people having to trawl for information)

**Comment by bryevdv** [comment]
> One thing, mostly unrelated to this PR, I noticed when checking out bokeh.pydata.org/en/dev, is that wheel scroll zoom in examples and documentation is a bad combination.

Agreed, for the non-gallery plots. I'll make an issue to collect small improvements to this later and include that.

**Comment by mattpap** [comment]
> I'll make an issue to collect small improvements to this later and include that.

OK.

**Comment by mattpap** [comment]
LGTM.

**Comment by damianavila** [comment]
LGTM too...

**Pull request merged**
