### PR TITLE
Fix for issue with functools @wraps and partial in python 2.7

### LINKED ISSUE #4783: Using functools.partial in combination with add_next_tick_callback() throws exception in py2
There is example in the user guide which shows how we can update plots from blocking threads. It is suggested to run this example with `bokeh serve --show` and that works fine.  [full example](https://github.com/bokeh/bokeh/blob/008e63812da2655bb6331b9338a116a6ccd8ba47/sphinx/source/docs/user_guide/server.rst#updating-from-threads)

The problem is when we try to extend this example with `bokeh.client` and run it with py2. With py3 it works fine, but with py2 we get an exception.

Here is full code which can reproduce the issue. Run `bokeh serve` and run following python code with python2.

``` python
#!/usr/bin/python2
from functools import partial
from random import random
from threading import Thread
import time

from bokeh.client import push_session
from bokeh.models import ColumnDataSource
from bokeh.plotting import curdoc, figure, show

from tornado import gen

source = ColumnDataSource(data=dict(x=[0], y=[0]))

doc = curdoc()
session = push_session(doc)

@gen.coroutine
def update(x, y):
    source.stream(dict(x=[x], y=[y]))

def blocking_task():
    while True:
        time.sleep(0.1)
        x, y = random(), random()

        doc.add_next_tick_callback(partial(update, x=x, y=y))

p = figure(x_range=[0, 1], y_range=[0, 1])
l = p.circle(x='x', y='y', source=source)

doc.add_root(p)

thread = Thread(target=blocking_task)
thread.start()

session.show(p)
session.loop_until_closed()
```

This is the exception:
``` python
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "bokeh_test.py", line 32, in blocking_task
    doc.add_next_tick_callback(partial(update, x=x, y=y))
  File "/usr/local/lib/python2.7/dist-packages/bokeh/document.py", line 1040, in add_next_tick_callback
    return self._add_session_callback(cb, callback, one_shot=True)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/document.py", line 965, in _add_session_callback
    @wraps(callback)
  File "/usr/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'functools.partial' object has no attribute '__module__'
```

I'm not saying that there is a problem with documentation (like in previous issue I reported). I just didn't expect this to happen and I am not sure if I am doing something wrong or there is indeed a bigger problem. Thanks!

### PR DESCRIPTION
**Pull request by Atlantic777**
- [ ] issues: fixes #4783

### CODE REVIEW

**Comment by bryevdv** [comment]
@Atlantic777 awesome, if yo are up for it, a test for this would make the PR truly complete. I think you could basically copy and paste this part of this test (renaming the new test function to `test_add_partial_callback` or something):

https://github.com/bokeh/bokeh/blob/master/bokeh/tests/test_document.py#L425-L436

but just wrap the `cb` callback with `partial` first.

**Comment by bryevdv** [comment]
@Atlantic777 also our code style check has flagged something:
```
E       AssertionError: Code quality issues:
E         File contains trailing whitespace: bokeh/document.py, line 13.
E       assert 1 == 0
E        +  where 1 = len(['File contains trailing whitespace: bokeh/document.py, line 13.'])
```
so the whitespace at the end of that file needs to be deleted.

**Comment by bryevdv** [comment]
@Atlantic777 will you have time to make the changes described above? No worries if you don't have time, I understand. If so I can open a new PR based on this one to finish and close this one, just let me know.

**Comment by Atlantic777** [comment]
@bryevdv yes, I will be happy to do it! I was on a trip for couple of days, I'm sorry for not responding. I need some time to see how testing infrastructure works for your project and I will make change in next few days. I prefer to do it by myself because there are more things I want to contribute. :)

**Comment by bryevdv** [comment]
@Atlantic777 no apologies needed we are all busy, was just checking in :)

**Comment by Atlantic777** [comment]
@bryevdv, ok I think I did it. I fixed that trailing whitespace and added the regression test. There are still some failing tests on Travis but I think that they are not related to my changes.

**Comment by bryevdv** [comment]
@Atlantic777 yup, the failing integration test is something for us to fix on our end. It will pass once the PR is merged. LGTM, thanks for the contribution!

**Pull request merged**
