### PR TITLE
Put server into its own distutils distribution

### PR DESCRIPTION
**Pull request by mcdonc**
This PR creates a "server" subdirectory of the bokeh distutils project, which houses a setup.py that can be used to create a distutils distribution named ``bokeh_server``.  It removes the ``server`` subdirectory of the bokeh package.  If this pull request is merged, when the ``bokeh`` library is installed, the server component will no longer be installed.  To install the server component, a user will need to install the ``bokeh_server`` distribution. 

Notable changes as a result:

- A new directory has been added to the ``bokeh`` package named ``static``.  This
  is where generated static files will be dropped when ``--install_js`` is used as
  an argument to bokeh's ``setup.py``.  These files used to be copied into
  ``bokeh.server/static``, but the directory no longer exists.

- The ``bokeh_server`` package has been changed to look for the generated static
   files in ``bokeh/static``.

- Currently the ``bokeh_server`` distribution relies on ``setuptools`` for both
  its ``package_data`` feature and its ``console_scripts`` feature (the ``bokeh-server``
  script is now a console script).  No scripts are installed now when the ``bokeh``
  distribution is installed; only when ``bokeh_server`` is installed.

### CODE REVIEW

**Comment by mcdonc** [comment]
The travis tests currently fail because

1) I need to figure out how to change ``travis_install`` to install bokeh_server too.

2) I need to change the test script to use the bokeh-server script installed into
    the Python bindir instead of the (no longer existing) bokeh-server.py in
    the root of the checkout.

**Comment by bryevdv** [comment]
One idea would be having the current tests not run any of the server examples or tests anymore, and then go back and add a new test config to the matrix that runs the server tests and examples separately. That would allow the non-server set of tests to finish much more quickly. Thoughts, @bokeh/core ?

**Comment by bryevdv** [comment]
@damianavila do you have any bandwidth to help with some of the build/test changes to support this? I think Ian would be ok with that. @mcdonc another idea would be to resubmit this PR as a branch off the master repo, so that collaboration could be a little more direct/easy.

**Comment by mcdonc** [comment]
@bryevdv I don't appear to have access to create a branch in bokeh/bokeh but I'd be happy to reapply the PR against such a branch if one were created.

**Comment by damianavila** [comment]
>One idea would be having the current tests not run any of the server examples or tests anymore, and then go back and add a new test config to the matrix that runs the server tests and examples separately. That would allow the non-server set of tests to finish much more quickly. Thoughts, @bokeh/core ?

Sound good...

>@damianavila do you have any bandwidth to help with some of the build/test changes to support this? I think Ian would be ok with that.

I guess I can help with this a little bit next week.

**Comment by damianavila** [comment]
Closing this one according to BEP-1 (and some discussions about the server status quo).

**Pull request closed without merging**
