### PR TITLE
Make widgets optional and refactor bokeh.resources

### PR DESCRIPTION
**Pull request by mattpap**
The main objective is to make `bokeh-widgets.{js,css}` optional. Currently this is done for `file_html()`. Server support is out of question until @bryevdv's PRs are merged.

### CODE REVIEW

**Comment by mattpap** [comment]
There is still a lot more to improve, but lets proceed with what we have here.

**Comment by bryevdv** [comment]
Looks like a couple of test are failing:

https://travis-ci.org/bokeh/bokeh/jobs/84922928#L1521

I will try to look at the whole PR more closely in the next few hours.

**Comment by mattpap** [comment]
This is strange. Unfortunately I can't run tests locally. @birdsarah, can you help with this: `453 tests deselected by "-m 'nondestructive'"`? I asked in PR #2800, but didn't get any response.

**Comment by mattpap** [comment]
@bokeh/dev, this needs review.

**Comment by havocp** [comment]
This looks good to me, I would support merging it now.  I will have to redo the part in embed.py on the tornado branch but it shouldn't be a big deal, I'll merge master to the tornado branch again once this PR lands.

**Comment by fpliger** [comment]
LGTM (we know the current status and it's probably better to have it landing on the tornado branch sooner)

**Comment by mattpap** [comment]
OK. If there will be no objections, I will merge within an hour.

**Pull request merged**
