### PR TITLE
Update model on server when the plot is panned/zoomed.

### PR DESCRIPTION
**Pull request by ivmi**
This addition propagates pan/zoom changes of the plot in the browser to the server.
It provides possibility to update the plot data according to the current x,y ranges.
Possible uses: dynamic plotting, level of detail etc.
Disadvantages: data is send during pan, maybe pan:end would be a better place.

### CODE REVIEW

**Comment by bryevdv** [comment]
@ivmi Thanks for the PR. I think this is a good idea, but as you mention there are different policies that might be desirable. Maybe it would be best to expose these policies as a configurable property, so that saving to the server can be: i) always on, ii) always off, iii) only on `:end`, etc. What do you think?

**Comment by ivmi** [comment]
I agree it should probably be a property. This was a quick solutions to a feature I needed. Implementing a configurable property would probably be over my head, unfortunately. 
There could also be other properties that might benefit from saving to the server?

**Comment by bryevdv** [comment]
If you are able to make a small time commitment I am happy to work through how to make this a configurable parameter in small steps, in this PR. If not, let's open up a feature request issue so that someone on the core team can take a look at it at some point.

**Comment by ivmi** [comment]
Let's see what we can do.

In pan_tool.coffee, there is no event triggered on pan:end, so we should probably add a new function in plot.coffee (eg. on_pan_end) and then call it from pan_tool: @plot_view.on_pan_end(). Or is there a better general way to do this?

What would be the best place to put property? Does it have to be configured on the server side (python) too?

**Comment by bryevdv** [comment]
Well all the tools that update the range do so by calling `update_range` so let's start by making that method configurable at the call level, then we can figure out how to make individual tools have policies on how to call `update_range`. I would add an optional param `push=false` (or similar) to `update_range` then inside you can test `if push?` and if true, call `.save

One thing, you need to save ***all*** the ranges, not just `x_range` and `y_range`. So basically inside the for loops that update all the ranges, call `rng.save()`

**Comment by ivmi** [comment]
IMO, push should be a property of plot, not a param to the update_range. Update_range is called from the pan_tool (among others) which shouldn't care whether the data is saved on the server. 
However, I can't find how the options are passed to the plot upon init.

**Comment by bryevdv** [comment]
@ivmi making it a parameter of `update_range` is an implementation detail, a first "plumbing" step towards exposing a configurable policy that tools can make happen. 

Making it a proper of `Plot` is another option, but then you lose all resolution on to the state of the tool interaction. (i.e., is it mid-flight? is it ending?) In that case you only have two possibilities: always update, or never update. If you want finer grained control, such as "only update at the end of the interaction" then you will have to drive that from the tool itself, because only the tool has that information. 

I'm open to either alternative, I just wanted to draw out the tradeoffs explicitly.

**Comment by ivmi** [comment]
Now I understand your point. My idea was to signal pan operation to the plot (pan:end) and to use that to save ranges (if the parameter is set to 'pan_end'). If param is set to 'pan_move', save the model in update_range function. This way, the figure doesn't care how the range was changed (by which tool), only that it has to save data.

I tried cloning and installing bokehjs locally, but there is no gruntfile. Should I create it myself? It's not mentioned in the guide.

**Comment by bryevdv** [comment]
@ivmi no, we switched to using `gulp` since the last official release. You can see a test deployment of the latest docs here:

http://bokeh.pydata.org/en/test/docs/dev_guide/building.html#building-bokehjs

**Comment by damianavila** [comment]
@ivmi, first thanks for your PR... now a question, do you have plans to continue working on this? Thanks.

**Comment by ivmi** [comment]
Unfortunately, no. I would like to see it implemented, but I currently can not devote enough time to do it. 

Furthermore, I have noticed some negative side effects of this addition (wheel zoom response is jittery, with multiple refreshes). The feature would probably have to be implemented in a different way.

**Comment by damianavila** [comment]
OK, I will close this one and open an issue with a `feature` labels (#2389) and link this implementation so others can know about the idea and also know about your problems. But thank you very much for you time trying the PR, it helps a lot!!

**Pull request closed without merging**
