### PR TITLE
Remove double colons from field lists

### PR DESCRIPTION
**Pull request by jarrodmillman**
Fix https://github.com/pydata/pydata-sphinx-theme/issues/860 and addresses a checkbox here #12203.

See https://github.com/sphinx-doc/sphinx/issues/10594

You need 5.1.1+ due to a napoleon issue (#12265):
https://github.com/sphinx-doc/sphinx/issues/10594

### CODE REVIEW

**Comment by jarrodmillman** [comment]
I noticed you use napoleon instead of numpydoc. Is there a reason you don't use numpydoc?

**Comment by jarrodmillman** [comment]
Hmm, according to the build it is still "Running Sphinx v5.0.2".

**Comment by bryevdv** [comment]
>  is there anything we can fix in numpydoc to make it more attractive for you than napoleon?

Our preference is not napoleon, per se, rather it is a preference for Google docstring format. I am very against the heavyweigh ReST-style section underlines, and the vertical space they take up, in numpy docstring format. If numpydoc can parse google style docstrsings these days then switching might be possible.

**Comment by jarrodmillman** [comment]
The failing examples test seem to be unrelated to this PR:
```
2022-08-13 20:55:24 URL:https://raw.githubusercontent.com/bokeh/chromium/main/linux/103.0.5060.53/chromium_2020.assert [5423/5423] -> "chromium_2020.assert" [1]
https://media.githubusercontent.com/media/bokeh/chromium/main/linux/103.0.5060.53/chromium_2020.snap:
2022-08-13 20:55:24 ERROR 503: backend read error.
Error: Process completed with exit code 8.
```

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
Thanks for the fix @jarrodmillman

**Pull request merged**
