### PR TITLE
Better names for the devel builds

### PR DESCRIPTION
**Pull request by damianavila**
Using `TRAVIS_JOB_ID` to have smaller number than now... BUT also changing to a tag-based name for devel builds... so the `TRAVIS_JOB_ID` is only relevant for the testing machinery without conflicting with conda...

### CODE REVIEW

**Comment by damianavila** [comment]
ping @bokeh/core, I want to merge this one ASAP to trigger a new devel build...

**Comment by bryevdv** [comment]
Restarted single test failure.

**Comment by bryevdv** [comment]
LGTM AFAICT

**Comment by bryevdv** [comment]
@damianavila tests now passing, I would say merge whenever you want.

**Pull request merged**
