### PR TITLE
Document Refs Cleanup (part 1)

### PR DESCRIPTION
**Pull request by bryevdv**
ref: #11477

This is the first of a few PRs that will eventually #11477 Only the first items directly relates to that issues, but the rest is some very overdue cleanup that needs to happen before the bigger follow-on PRs.

#### Avoid superflous `curstate` doc  in apps

This streamlines "curdoc patching" woith a context mananger that avoids the single dangling doc that gets reported as uncollected in Bokeh apps due to how `State` functions. This also makes the code paths better by no longer requiring explicit cleanup/un-patching. (The same treatment was given to `bokeh.io` monkey patching)

#### Factor `HasDocumentRef` mixing. 

This removes bad duplication in the callback manager mixins and will allow for more easily moving to weakrefs for docs later. 

#### Remove some cruft from `bokeh.core.query`

Callable queries with contexts add compllexity but appear completely unused and have never been demonstrated. 

#### Split up `model.py`

Gets it down from 1 kLOC to a "manageable" 600 lines. Also now explicitly list public API which is goo

##### Add some missing tests

Some of the most low-level funcs in `model.py` have never had any tests. This PR is by no means complete but at least now there is some coverage.

### CODE REVIEW

**Comment by bryevdv** [comment]
@philippjfr I'll make sure to look at downstream tests, but please check out this PR with HV/Panel/etc if you can. I'll also manually test with Dask.

**Comment by bryevdv** [comment]
FYI some next steps will be:

* make events a proper protocol message handled the same as property changes, which will eliminate the need to store event callbacks on Documents (circular ref)
* remove circular refs to doc in other wrapped callbacks
* (probably) make models only carry a weakref to their doc

**Comment by bryevdv** [comment]
@philippjfr I manually ran the Panel tests with this PR and the results were identical to #11485 so I don't think there is any apparent impact to Panel from this PR.

**Comment by bryevdv** [comment]
I'll plan to merge this tomorrow and put get out a dev build unless more time is requested

**Comment by philippjfr** [comment]
Great, agree this seems safe with the Panel tests being unchanged. If you have to make deeper changes don't hesitate because of failing Panel tests though, can always follow up with compatibility fixes.

**Comment by mattpap** [comment]
> Split up model.py

It would have been much easier to find the relevant changes of this PR, if this happened in a separate PR.

**Comment by bryevdv** [comment]
> It would have been much easier to find the relevant changes of this PR, if this happened in a separate PR.

Commits are split: https://github.com/bokeh/bokeh/commit/bb104064b7240504c4dd5baa0cf31d66cd6fd09a

**Pull request merged**
