### PR TITLE
evaluate rbush spatial indexes lazily

### LINKED ISSUE #1542: Lazy evaluation for spatial indexes
References: #736, #1536 

First cut pass, suggest:
* [x] make indexing lazy by default
* [x] ~~~allow tools that will use indexing a short-circuit option to trigger indexing at plot creation time~~~

This should prevent plots that do not need indexing from having to pay the cost, and also allow tools that will be using indexing to trigger an indexing earlier (at plot creation) rather than, say, the first mouse hit event (worry is visual stutter)

@mattpap, thoughts?

### PR DESCRIPTION
**Pull request by bryevdv**
issues: closes #1542 

Performance seems to be OK just evaluating lazily all the time. Can add tool hinting for pre-indexing later if necessary. 

Update: I'm no longer convinced this actually addresses the issue in #1542 (more investigation needed) but lazy eval of indices is probably a reasonable thing to do in any case.

### CODE REVIEW

**Comment by damianavila** [comment]
ping @paddymul ;-)

**Comment by bryevdv** [comment]
However, please also see #1599

**Comment by damianavila** [comment]
Changing milestone to 0.8 accordingly to the issue reference at the top...

Btw, we probably need to build a control test case example to see the performance differences with the lazy evaluation *per se*.

**Comment by damianavila** [comment]
@bryevdv, can you remember me the status of this one? You said something today at the meeting but I could not take notes about it and I forgot what you said :wink:

**Comment by bryevdv** [comment]
I want to think about this one some more.

**Comment by damianavila** [comment]
I am going to close this one accordingly to [BEP 1](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management#pull-requests), but I will leave the branch in the remote so you can re-open this PR when it is ready to review again.

**Pull request closed without merging**
