### PR TITLE
A basis for sub-coordinate systems

### PR DESCRIPTION
**Pull request by mattpap**
This is an internal and partial "refactoring" that lays the ground for a proper implementation of sub-coordinate systems. From users' perspective nothing changes for now. Internally, renderers now access their coordinate system information (ranges, scales) and transforms through a "scope". Global `map_{to,from}_screen()` methods are gone. `{x,y}_range_name` is only used for scope creation and renderers should not query the frame directly anymore. For now "scope" it a simple mapping between data and screen coordinate systems, derived from `CartesianFrame`. However, in future this will allow for (user) configurable coordinate system, and, in particular, mapping or nesting coordinate systems.

### CODE REVIEW

**Comment by bryevdv** [comment]
Happy to see work that rationalizes and unifies coordinate system handling, since various parts of it were added at very different times and it shows. I thing we will need to iterate on the name `scope` to try an find something a bit less generic, and more descriptive.

**Comment by mattpap** [comment]
> I thing we will need to iterate on the name scope to try an find something a bit less generic, and more descriptive.

I chose `scope` because it was unique across the repository, but I'm open to suggestions.

**Comment by bryevdv** [comment]
Well, the thing called `scope` is not a coordinate system, it's really a mapping between two coordinate systems. So the type should probably be `CoordinateSystemMapping` or `LinearCoordinateSytemMapping` to be even more verbose. In the other direction, `FrameMapping` seems nice, but it clashes somewhat with the existing usage of "frame" in `CartesianFrame`. 

For the values, instead of `scope` (which evokes nothing to do with coordinates or geometry to me) we could lightly abuse some mathematical terms like `bundle` or `sheath`.

If I had all this to do over from the beginning, I think the relevant concepts are:

* Range - represents intervals
* Scale - maps from one range to another 
* CoordinateSystem - represents a space
  - CartesianCoordinateSystem - split via two ranges
  - RadialCoordinateSystem - not separable
* Frame - a mapping between two CoordinateSystems (e.g. using scales on specified ranges)

I am not sure how close we can get to that now, but maybe useful as context

**Comment by mattpap** [comment]
I renamed `CoordinateSystem` to `CoordinateTransfrom`. Let's continue this discussion in an issue, so that this can be addressed in future PRs in 2.2 cycle. For now I'm going ahead and merge this PR, to unblock my other work.

**Pull request merged**
