### PR TITLE
remove spurious curplot

### LINKED ISSUE #1914: remove spurious curplot
missed one: reference #1810

### PR DESCRIPTION
**Pull request by bryevdv**
issues: fixes #1914

### CODE REVIEW

**Comment by bryevdv** [comment]
Evidence:
```
bryan@laptop (git:bug/1914_curplot) ~/work/bokeh $ grin curplot
./CHANGELOG:
   40 :     - #1809 Seems to be some curplot leftover in the codebase
  708 :     - #466 Figure() kwargs don't match curplot() attributes
```

**Comment by damianavila** [comment]
LGTM

**Comment by bryevdv** [comment]
@damianavila assuming tests pass and some sanity had tests pass do you want to include this in the fixes for 0.8.1? It's a pretty annoying bug if people run into it.

**Comment by bryevdv** [comment]
S3 test report looks good. I think we should consider including it.

**Comment by damianavila** [comment]
I agree... milestone updated.

**Comment by damianavila** [comment]
I re-revisit this one... I think is in good shape...

**Pull request merged**
