### PR TITLE
Add deprecation warning if user supplies iterables and user-defined s…

### LINKED ISSUE #2056: deprecate glyph functions accepting datasource and sequence literals simultanously
Right now, when user passes datasource and passed in data on glyph functions [checks for a passed in source](https://github.com/bokeh/bokeh/blob/master/bokeh/_glyph_functions.py#L9) and [tries to figure out](https://github.com/bokeh/bokeh/blob/master/bokeh/_glyph_functions.py#L40) what the pile of parameters correspond to, given whatever glyph we are and then in that function it actually sets columns on the data source.

We should just disallow it. If you pass in a data source, you only get to refer to constant values, or column names and if you pass data in, then you should not specify datasource.

### PR DESCRIPTION
**Pull request by Maggie-M**
issues: fixes #2056

### CODE REVIEW

**Comment by bryevdv** [comment]
@bokeh/dev I propose to deprecate this now in `0.12.3`, and raise a `RuntimeError` in the very near future (and add a test for the exception at that time)

**Comment by bryevdv** [comment]
@bokeh/dev any comments on this before merging?

**Comment by mattpap** [comment]
@bryevdv, if this is a deprecation, then it should use appropriate machinery we have in bokeh for this.

**Comment by bigreddot** [comment]
@mattpap we have deprecation machinery for functions and modules, what machinery would cover this case?

**Comment by bryevdv** [comment]
@mattpap do you mean this? 
```
warn(message, BokehDeprecationWarning, stacklevel=2)
```
? If so, sure that seems reasonable

**Comment by mattpap** [comment]
@bryevdv, at minimum this, because `BokehDeprecationWarning` gets special treatment to be always visible. However, I thought we had a function for this `bokeh.util.deprecate`.

**Comment by bigreddot** [comment]
@mattpap That's just a function decorator

@Maggie-M can you change the warning as shown above?

**Comment by mattpap** [comment]
@bryevdv, unfortunately examples weren't updated, so there is some annoying text output (e.g. `plotting/server/hover`).

**Comment by bigreddot** [comment]
Ah, I think that was the only one, thanks for the catch

**Comment by bigreddot** [comment]
Just going to have @Maggie-M delete it as part of #5154 since it is the only `output_server` example as well

**Pull request merged**
