### PR TITLE
Utilizing numpy arrays to speed up column data scrubbing

### PR DESCRIPTION
**Pull request by mistakevin**
Related to issue https://github.com/bokeh/bokeh/issues/2582

### CODE REVIEW

**Comment by mistakevin** [comment]
Here some comparisons:
BEFORE
screen shot 2015-07-20 at 8 57 19 am


AFTER
screen shot 2015-07-20 at 9 59 11 am

**Comment by damianavila** [comment]
:+1:

**Comment by bryevdv** [comment]
LGTM

**Comment by bryevdv** [comment]
@damianavila @mistakevin actually taking a step back, this makes NumPy a hard dependency for any plot. Perhaps the conversion and import should be wrapped in a `try` block with a fallback to the original code.

**Comment by mattpap** [comment]
PRs like this one, i.e. touching fundamentals of bokeh (in this case serialization protocol), should not be allowed without tests. Also, personally I don't follow the logic in `traverse_data()` and tests (I mean unit tests) would help a lot.

**Comment by mattpap** [comment]
@bryevdv, I started https://github.com/bokeh/bokeh/issues/2596 regarding `numpy`.

**Comment by bryevdv** [comment]
@mattpap thanks that is a very good idea. I also agree merging was hasty, thanks for your attention to process and discipline.

**Comment by mistakevin** [comment]
@damianavila @bryevdv I can put in a try block to remove NumPy as a hard dep. Should I get that in for this next release?

**Comment by bryevdv** [comment]
@mistakevin yes I think it would be advised (it should be fairly simple). Apologies that we did not provide close enough scrutiny to catch this earlier.

**Pull request merged**
