### PR TITLE
allow plot ranges to accept (start, end) tuples

### LINKED ISSUE #1112: line tutorial Range ValueError
I just worked through the lines tutorial (I like it - thanks), but encountered problems with the very end exercise of setting x_range and y_range parameters.  I first tried passing a list [-10,10](which is what is done in the solutions).  I got a ValueError:

ValueError: expected an instance of type Range, got [-10, 10] of type list

OK, so perhaps I'm stubborn, so I tried a tuple, wondering if better conversion existed for it:

ValueError: expected an instance of type Range, got (-10, 10) of type tuple

However, it looks like I really should be using bokeh.objects.Range1D objects, as pointed out in the next (scatter.py) example.

I've read in other issues (searching for duplicate issues) that this tutorial will be replaced soon.  Is this a general issue (bug) that lists and tuples _should_ work for this argument - or should the tutorial rework include a step to create Range1D objects?

This was done with Bokeh 0.5.2 - please disregard if the master branch fixes this behavior.

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #1112
- [x] tests added / passed
- [x] release document entry (if new feature or API change)

Just trying to pass over old tickets to close or complete if they are trivial. This should be uncontroversial.

### CODE REVIEW

**Comment by canavandl** [comment]
So I'm a soft -1 on this PR. It's counter to my "no magic" bokeh.models API feelings.

Additionally, ``bokeh.plotting.figure`` accepts a list of strings and generates a FactorRange, so this change doesn't fully reflect that API either. I'd rather just close the parent issue as won't fix.

**Comment by bryevdv** [comment]
> Additionally, bokeh.plotting.figure accepts a list of strings and generates a FactorRange, so this change doesn't fully reflect that API either. I'd rather just close the parent issue as won't fix.

It would be easy enough to accept a list of strings and create a factor range. The main reason I am +1 on this is that it alot of examples are getting fairly import-heavy, and this would allow users to do something simple and common thing without having  to reach for yet another import. Apart from that I think being able to set a range as a tuple is just a very reasonable ask that is probably supported by almost any other library.

**Comment by canavandl** [comment]
Ok - if we add support for creating FactorRanges in the same way, i'm ok with this change.

For consistency, should Title ``accept`` a string? Was there a reason why we didn't do that before? (The docstring is out of date there at least).

Am I correct in assuming there's minimal likelihood of user confusion by setting a tuple and creating a new range instead of updating a current one.

```python
p.x_range.callback = some_callback
p.x_range = (0,1) # creates a new range without the above callback
```

**Comment by mattpap** [comment]
> ```
> p.x_range.callback = some_callback
> p.x_range = (0,1) # creates a new range without the above callback
> ```

This and linked plots. I'm not against this feature, but I would prefer to update existing range instead of creating a new one. I think we don't have support for this pattern in properties.

**Comment by bryevdv** [comment]
OK I can agree with the notion that it would be better to update existing ranges in place, in cases where that is feasible. But I think that would require some additional machinery to pass more information to the `.accepts` converter in order to implement. I will close this PR but leave the original issue open.

**Pull request closed without merging**
