### PR TITLE
Don't use unminified resources in bokeh.plotting

### LINKED ISSUE #1627: Resources(..., minified=False) in bokeh.plotting
Pointed out in #1605.

### PR DESCRIPTION
**Pull request by mattpap**
issues: fixes #1627

### CODE REVIEW

**Comment by bryevdv** [comment]
Let's add a test that checks these values.

**Comment by damianavila** [comment]
LGTM, and I agree on test request...

**Comment by bryevdv** [comment]
I wan to clear this out, I will add a test and merge.

**Comment by bryevdv** [comment]
@damianavila plan to merge as soon as tests pass unless comments

**Comment by damianavila** [comment]
No comments, LGTM, just go ahead after TravisCI...

**Pull request merged**
