### PR TITLE
Check docs with CI (individual pull requests)

### LINKED ISSUE #10728: [FEATURE] Linting for docs
I'd like to add some basic automatic checking of narrative documentation to the CI by adding the Vale GitHub action https://github.com/errata-ai/vale-action. I have been using this system locally for a few months and have configured it to work with all the .rst files I have been editing and creating for Bokeh. With the configuration I have created, the linter would be a helpful tool to support consistency according to the style guidelines in the documentation section of the developers guide.

I created this issue to work on how to best integrate this with Bokeh's CI. CC @bryevdv

### PR DESCRIPTION
**Pull request by tcmetzger**
closes #10728 

I am opening this pull request to add automated quality checks of the docs to the CI. This specific pull request uses a configuration that will check any modified RestructuredText files in a pull request. I will open a separate pull request to enable continuous routine checks, as [proposed ](https://github.com/bokeh/bokeh/pull/10735#issuecomment-736186258) by @bryevdv.

### CODE REVIEW

**Comment by bryevdv** [comment]
@tcmetzger I think the unit test failure is likely spurious but it looks like there are real Vale errors?

**Comment by tcmetzger** [comment]
Well, for some reason an old version of styling.rst still gets checked and results in an error - even though styling.rst has never been part of this pull request. I really don't know how that happens. I'll have to dig deeper into the inner workings of GitHub actions and specifically lots0logs/gh-action-get-changed-files@2.1.4 (which is supposed to determine which files have been changed and should therefore be checked by Vale).

**Comment by bryevdv** [comment]
@tcmetzger thesis still labeled `WIP` what is remaining?

As an aside this is a pretty spurious warning:

Screen Shot 2021-01-04 at 10 45 55 AM

not sure if there is a way to teach it that is not text to consider.

**Comment by tcmetzger** [comment]
The only thing remaining was me finding some time to go over the rules one more time - which I just did. With my most recent commit, I also improved the ignore regex to exclude paths like `bokeh.models.tools.PanTool` from being checked.

**Review by bryevdv — APPROVED** [review]

**Review by bryevdv — APPROVED** [review]

**Pull request merged**
