### PR TITLE
Update GroupFilter docs and example to use penguins dataset

### LINKED ISSUE #13126: [BUG] Mismatch in GroupFilter documentation example between text and code
### Software versions

Python version      :  3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]
IPython version     :  8.13.2
Tornado version     :  6.1
Bokeh version       :  3.1.0
BokehJS static path :  /global/common/software/lsst/gitlab/desc-python-prod/84904/py/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-5.14.21-150400.24.46_12.0.71-cray_shasta_c-x86_64-with-glibc2.31

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

The documentation text and the plot created by the example code say the output of the group filter in the example code should be the `setosa` labelled data.

### Observed behavior

But the example filter selects the `versicolor` labelled data

### Example code

```Python
(From https://github.com/bokeh/bokeh/blob/branch-3.2/examples/basic/data/filter_group.py)

from bokeh.layouts import gridplot
from bokeh.models import CDSView, ColumnDataSource, GroupFilter
from bokeh.plotting import figure, show
from bokeh.sampledata.iris import flowers

source = ColumnDataSource(flowers)
###
### ***Here the filter selects data that doesn't match documentation or plot label below***
###
view = CDSView(filter=GroupFilter(column_name="species", group="versicolor")) 

opts = {"height": 300, "width": 300, "tools": "box_select,reset,help"}

p1 = figure(title="Full data set", **opts)
p1.circle(x="petal_length", y="petal_width", source=source, color="black")

p2 = figure(title="Setosa only", x_range=p1.x_range, y_range=p1.y_range, **opts)
p2.circle(x="petal_length", y="petal_width", source=source, view=view, color="red")

show(gridplot([[p1, p2]]))
```
```


### Stack traceback or browser console output

_No response_

### Screenshots

![image](https://github.com/bokeh/bokeh/assets/4755090/eb36f063-f85b-4864-9a44-2fdf5b256764)

### PR DESCRIPTION
**Pull request by jbkalmbach**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [ ] issues: fixes #13126 
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@jbkalmbach as long as you are looking at this, would you be amenable to looking at updating the example and docs further to use the [penguins](https://docs.bokeh.org/en/3.1.1/docs/reference/sampledata.html#sampledata-penguins) dataset, instead of iris? We are trying to phase out the use of that data set. The relevant docs file is here:

https://github.com/bokeh/bokeh/blob/branch-3.2/docs/bokeh/source/docs/user_guide/basic/data.rst?plain=1#L470-L489

The color palette and marker size for the example could also be improved. Let me know what you think.

**Comment by jbkalmbach** [comment]
Yeah, I can take that on.

**Comment by bryevdv** [comment]
Hi @jbkalmbach did you expect to be able to continue working on this PR?

**Comment by jbkalmbach** [comment]
Yeah, sorry, this fell off my radar. I'll make some time and finish it off tomorrow afternoon.

**Comment by jbkalmbach** [comment]
Ok, I think this is ready to go with the requested changes.

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
@jbkalmbach Thanks and sorry for the delay! I missed a notif for your last comment and then got a bit busy.

**Pull request merged**
