### PR TITLE
adapt to pandas changes

### LINKED ISSUE #8585: TypeError: index is not a valid DatetimeIndex or PeriodIndex
Looks like pandas 0.24.0 brought some backwards incompatible changes, e.g. https://travis-ci.org/bokeh/bokeh/jobs/484595447#L1287.

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #8585
- [x] tests added / passed

### CODE REVIEW

**Comment by bryevdv** [comment]
OK I think this and the other PR should get all tests passing on both Travis and Appveyor

**Comment by bryevdv** [comment]
OK this change works on Py3 but now fails on Py2:
```
[PY] Traceback (most recent call last):
[PY]   File "<string>", line 13, in <module>
[PY]   File "/home/travis/build/bokeh/bokeh/examples/plotting/file/categorical_scatter_jitter.py", line 4, in <module>
[PY]     from bokeh.sampledata.commits import data
[PY]   File "/home/travis/miniconda/lib/python3.5/site-packages/bokeh/sampledata/commits.py", line 70, in <module>
[PY]     data = _read_data()
[PY]   File "/home/travis/miniconda/lib/python3.5/site-packages/bokeh/sampledata/commits.py", line 60, in _read_data
[PY]     datetime = pd.to_datetime(data.index, utc=True).tz_convert('US/Central')
[PY]   File "/home/travis/miniconda/lib/python3.5/site-packages/pandas/core/indexes/datetimes.py", line 2295, in tz_convert
[PY]     raise TypeError('Cannot convert tz-naive timestamps, use '
[PY] TypeError: Cannot convert tz-naive timestamps, use tz_localize to localize
```

just changing to `tz_localize` fails with:
```
Traceback (most recent call last):
  File "categorical_scatter_jitter.py", line 4, in <module>
    from bokeh.sampledata.commits import data
  File "/Users/bryanv/work/bokeh/bokeh/sampledata/commits.py", line 70, in <module>
    data = _read_data()
  File "/Users/bryanv/work/bokeh/bokeh/sampledata/commits.py", line 60, in _read_data
    datetime = pd.to_datetime(data.index, utc=True).tz_localize('US/Central')
  File "/Users/bryanv/anaconda/lib/python3.7/site-packages/pandas/core/accessor.py", line 91, in f
    return self._delegate_method(name, *args, **kwargs)
  File "/Users/bryanv/anaconda/lib/python3.7/site-packages/pandas/core/indexes/datetimelike.py", line 721, in _delegate_method
    result = operator.methodcaller(name, *args, **kwargs)(self._data)
  File "/Users/bryanv/anaconda/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 1049, in tz_localize
    raise TypeError("Already tz-aware, use tz_convert to convert.")
TypeError: Already tz-aware, use tz_convert to convert.
```

@ TomAugspurger can you comment on the best way to deal with these breaking changes in Pandas 0.24 across old/new versions?

**Comment by TomAugspurger** [comment]
Looks like the change was in pandas' handling of mixed timezones in read_csv. Previously, a CSV with a mixture of timezones would (IIUC) convert the timezones to UTC and discard the tzinfo

```python
import pandas as pd
import io

content = """\
Sat, 22 Apr 2017 15:11:58 -0500
Fri, 21 Apr 2017 14:20:57 -0500
Thu, 9 Mar 2017 11:15:30 -0600"""

df = pd.read_csv(io.StringIO(content), parse_dates=True, header=None, names=['day', 'datetime'], index_col='datetime')	
```

On 0.23.4 that's

```python
In [7]: df.index
Out[7]:
DatetimeIndex(['2017-04-22 20:11:58', '2017-04-21 19:20:57',
               '2017-03-09 17:15:30'],
              dtype='datetime64[ns]', name='datetime', freq=None)
```

On 0.24 that's

```python
In [7]: df.index
Out[7]:
Index([2017-04-22 15:11:58-05:00, 2017-04-21 14:20:57-05:00,
       2017-03-09 11:15:30-06:00],
      dtype='object', name='datetime')
```

I assume that's just a regression in pandas, but I'll need to verify the expected behavior.

To get the previous output, you'll want to mimic pandas' old behavior.

```
In [18]: pd.to_datetime(df.index, utc=True).astype('datetime64[ns]')
Out[18]:
DatetimeIndex(['2017-04-22 20:11:58', '2017-04-21 19:20:57',
               '2017-03-09 17:15:30'],
              dtype='datetime64[ns]', name='datetime', freq=None)
```

You can assign that to `df.index = pd.to_datetime(...`, I believe that will give you the correct output for any recent version of pandas, including 0.23.4.

**Comment by TomAugspurger** [comment]
https://github.com/pandas-dev/pandas/issues/24987 for the change in `read_csv` on pandas' side.

**Comment by bryevdv** [comment]
@TomAugspurger thank you for the info and links. However, now the plot is shifted:

NEW:

screen shot 2019-01-28 at 11 42 03


OLD:

screen shot 2019-01-28 at 11 41 48


I have tried various variations on this code:
```
    data = package_csv(module, 'commits.txt.gz', parse_dates=True, header=None, names=['day', 'datetime'], index_col='datetime')
    data.index = pd.to_datetime(data.index, utc=True).astype('datetime64[ns]')

    # datetime = pd.to_datetime(data.index, utc=True).tz_localize('US/Central')
    # data.set_index(datetime)
    data['time'] = data.index.time
```
i.e. with or without commented part, with `tz_localize` removed, etc. Plot is always shifted.

**Comment by bryevdv** [comment]
I suppose it's worth mentioning, what I'd like to get is the local time

**Comment by bryevdv** [comment]
This seems to work:
```
    data = package_csv(module, 'commits.txt.gz', parse_dates=True, header=None, names=['day', 'datetime'], index_col='datetime')
    data.index = pd.to_datetime(data.index, utc=True,).astype('datetime64[ns]').tz_localize('utc').tz_convert('US/Central')
    data['time'] = data.index.time
```

**Comment by AbdessamadAz** [comment]
Hello,
Is it possible to update the movies database please ?
Thanks in advance

**Pull request merged**
