### PR TITLE
Remove confusing aliases from LayoutCanvas

### LINKED ISSUE #6197: Remove confusing aliases from LayoutCanvas
Follow up on PR #5976.

### PR DESCRIPTION
**Pull request by mattpap**
fixes #6197

### CODE REVIEW

**Comment by bryevdv** [comment]
Should `_left` etc just be made public? Hate to see `foo._private.value` all over the place.

**Comment by mattpap** [comment]
> Should _left etc just be made public?

Currently it's not possible due to confusion between `width` vs. `_width` in multiple places. Member starting with `_` are layout variables. When layout variables are moved to views, there will be clear separation between those.

**Comment by bryevdv** [comment]
OK LGTM then

**Comment by mattpap** [comment]
Also, `_value` will be soon replaced with `value`, but I have to clean up kiwi and use getters and setters across the code base.

**Comment by mattpap** [comment]
@bryevdv, I went ahead and renamed `_value` to `value`. That's all changes for this PR.

**Comment by mattpap** [comment]
I've been seeing this error lately:
```
Exception occurred:
  File "/home/travis/miniconda/lib/python3.4/ssl.py", line 620, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```
It's from `flake_docs` job. Restarting the job helps.

**Comment by bryevdv** [comment]
> It's from flake_docs job. Restarting the job helps. 

The sphinx GH extensions like `:bokeh-pull:` currently try to check that the link is valid and reachable. We can probably relax this.

**Pull request merged**
