### PR TITLE
Refactor WebGL code and provide as bokeh-gl.js

### LINKED ISSUE #4321: Put WebGL functionality in separate bokeh-gl.js?
Currently, we have a `bokehgl.coffee` which kept growing as features were added. With over 1400 lines, its time to split it up into a few separate files. Further we could build a separate `bokeh-gl.js` (similar to `bokeh-widgets.js` to reduce the size of the main `bokeh.js`, though this needs some discussion to establish when WebGL support should be included.

Tasks:
- [x] Refactor into smaller chunks (#4341)
- [ ] Decide on building a separate `bokeh-gl.js`
- [ ] Build a separate `bokeh-gl.js` (#4331)?

### PR DESCRIPTION
**Pull request by almarklein**
Fixes #4321

This basically splits the `bokehgl.coffee` code into a few smaller files. No actual changes to that code, other than the gulp files.

### CODE REVIEW

**Comment by almarklein** [comment]
@bokeh/dev I could use some help with the gulp files (see 2nd commit). As it is, I get an error in `gulp build`:
```
$ gulp build
[15:39:49] Using gulpfile d:\dev\pylib\bokeh\bokehjs\gulpfile.js
[15:39:49] Starting 'typings:install'...
[15:39:49] Finished 'typings:install' after 838 ms
[15:39:49] Starting 'build'...
[15:39:49] Starting 'scripts'...
[15:39:49] Starting 'scripts:coffee'...
[15:39:49] Starting 'scripts:eco'...
[15:39:49] Starting 'scripts:ts'...
[15:39:49] Starting 'styles'...
[15:39:49] Starting 'styles:build'...
[15:39:51] Finished 'scripts:eco' after 1.74 s
[15:39:53] Finished 'scripts:ts' after 3.15 s
[15:39:54] Finished 'styles:build' after 4.21 s
[15:39:54] Starting 'styles:minify'...
[15:39:54] Finished 'styles:minify' after 148 ms
[15:39:54] Finished 'styles' after 4.37 s
[15:39:57] Finished 'scripts:coffee' after 7.09 s
[15:39:57] Starting 'scripts:compile'...
[15:39:57] Finished 'scripts:compile' after 9.03 μs
[15:39:57] Starting 'scripts:build'...
d:\dev\pylib\bokeh\bokehjs\node_modules\browserify\node_modules\module-deps\index.js:327
            return cb(null, undefined);
                   ^

TypeError: cb is not a function
  at d:\dev\pylib\bokeh\bokehjs\node_modules\browserify\node_modules\module-deps\index.js:327:20
  at onresolve (d:\dev\pylib\bokeh\bokehjs\node_modules\browserify\node_modules\module-deps\index.js:178:14)
  at d:\dev\pylib\bokeh\bokehjs\node_modules\browserify\node_modules\module-deps\index.js:173:17
  at onpkg (d:\dev\pylib\bokeh\bokehjs\node_modules\browserify\node_modules\module-deps\index.js:496:27)
  at d:\dev\pylib\bokeh\bokehjs\node_modules\browserify\node_modules\module-deps\index.js:486:13
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

E.g. what is that `preludePath` and should I do something with it?

**Comment by bryevdv** [comment]
ping @mattpap 

FYI @almarklein i thought we might have a discussion first since there are some implications. In particular splitting things off means we need to detect when to include these resources automatically, (i.e., when `webgl=True`) but AFAICT this would also mean `?webgl=1` couold not longer function.

**Comment by almarklein** [comment]
Yes, that was going to be my next step. Not sure how to go about that. Probably only enable it when a plot has been set to use WebGL. We could introduce an environment var to include WebGL regardless such that `?webgl=1` could be used. Alternatively, we could include it by default by allow turning it off for users who want leaner plots.

**Comment by almarklein** [comment]
Closing, but not deleting. Will revive if we decide to do this.

**Pull request closed without merging**
