### PR TITLE
Preliminary work to get bokehjs working in node.js

### PR DESCRIPTION
**Pull request by mattpap**
This doesn't allow to render plots (see #1589 for details).

### CODE REVIEW

**Comment by bryevdv** [comment]
ping @tswicegood as he may have good comments to add

**Comment by mattpap** [comment]
This should be fixed now.

**Comment by bryevdv** [comment]
why not leave this for 0.8.2?

**Comment by mattpap** [comment]
Just clicked 0.8.1 too eagerly.

**Comment by damianavila** [comment]
This has an associated issue at the top, let's milestone the issue, not the PR... unless the issue encompass several tasks, and this is one them, then label this as a standalone-PR...

**Comment by tswicegood** [comment]
This just popped up in my feed again because of the activity.  FWIW, I would seriously consider [browserify][] when you head down the route of moving to Node.  I know @mattpap has some custom build tooling in place that relies on Require.js, but I believe the benefits of Browserify are pretty significant:

* Uses Node/io.js's internal module loader CommonJS: this means no changes are necessary for code to run inside Node.
* Tests can be run in a Node process rather than the browser.  This should simplify testing logic.
* Removes one indention layer (not as big of a deal, but they do add up).
* CommonJS provides a more natural means of loading code -- I've never read a defense of `define(["foo", "bar"], (foo, bar) ->…` as a sane syntax.
* Allows you to use CoffeeScript's [object destructuring][1] when loading code (think of it as `from foo import bar`).

And most importantly: Brings Bokeh and the [new Anaconda Launcher][2] platform together on the same build chain.  You can see a full project written out using CommonJS + Browserify in [this part of the tree][3] (note that it's node-webkit, so `nodeRequire` is a hack to make sure we're talking to the Node process, not the rewritten one from Browserify).

---

I played around with switching to Browserify back last fall without a full development environment setup.  I was able to get it to compile within an afternoon, though, as I said, I didn't have a dev environment setup so I'm not sure how much additional work would be necessary.

[1]: http://coffeescript.org/#destructuring
[2]: https://github.com/ContinuumIO/anaconda-launcher
[3]: https://github.com/ContinuumIO/anaconda-launcher/tree/master/static/coffee
[browserify]: http://browserify.org/

**Comment by bryevdv** [comment]
@mattpap this is ready to go?

**Comment by mattpap** [comment]
I merged-in master yet again. Can this get merged as soon as tests pass?

**Comment by bryevdv** [comment]
Yes

**Pull request merged**
