### PR TITLE
Clip MercatorTicker coordinates to officially defined bounds

### PR DESCRIPTION
**Pull request by philippjfr**
This PR fixes issues with poorly defined behavior of the MercatorTicker when the axis ranges exceed the officially defined bounds of the pseudo-mercator projection (as described in 
https://github.com/bokeh/bokeh/issues/6986). The coordinates the ticks are drawn between are clipped to the officially defined bounds defined [here](https://epsg.io/3857), resulting in consistent behavior when zoomed out.

screen shot 2017-09-30 at 1 13 25 pm

### CODE REVIEW

**Comment by bryevdv** [comment]
@philippjfr this is failing due to whitespace:
```
  where 1 = len(['File contains trailing whitespace: bokehjs/src/coffee/core/util/proj4.coffee, line 28.'])
```

However, there should also be simple unit tests for `clip_mercator` and `mercator_bounds` and a unit test exercising the ticker with out of bounds values.

**Comment by jbednar** [comment]
Seems like a reasonable approach, thanks!

**Comment by philippjfr** [comment]
>However, there should also be simple unit tests for clip_mercator and mercator_bounds and a unit test exercising the ticker with out of bounds values. I think you'll need to add new test files for this.

Sounds good, I'll add those shortly.

**Comment by philippjfr** [comment]
@bryevdv I'm pretty confused, I've been trying to write tests for the MercatorTicker when set to ``dimension='lat'`` but keep running into this error:

>TypeError: Cannot read property 'x' of null

I've even tried copying the exact arguments that get passed into the method when I interactively zoom in the notebook where I don't see errors, but when run as a test it always breaks. Is it possible that the browser does something differently?

**Comment by philippjfr** [comment]
Nevermind figured it out.

**Comment by philippjfr** [comment]
The issue was that for small ``desired_n_ticks`` the computed ticks would also sometimes fall outside the bounds resulting in errors while projecting. I'm now also dropping ticks which are not within the bounds, but that only seems to occur for ``num_ticks=2`` when you're zoomed out beyond the bounds.

**Comment by jbednar** [comment]
Looks good to me; eager to see it merged!

**Comment by bryevdv** [comment]
@mattpap this jusst failed when merged to master:
```
    @pytest.mark.quality
    def test_files():
        errors = collect_errors()
>       assert len(errors) == 0, "Code quality issues:\n%s" % "\n".join(errors)
E       AssertionError: Code quality issues:
E         File contains trailing whitespace: bokehjs/src/coffee/core/util/proj4.coffee, line 28.
E       assert 1 == 0
E        +  where 1 = len(['File contains trailing whitespace: bokehjs/src/coffee/core/util/proj4.coffee, line 28.'])
```
 But was green before then, what's going on?

**Pull request merged**
