### PR TITLE
Fix `super` call in "contexts.py"

### LINKED ISSUE #10536: Bad `super` call in "contexts.py"
I get the error 

>   File "/usr/local/lib/python3.6/dist-packages/bokeh/server/contexts.py", line 343, in __getattr__
>     return super.__getattr__(name)
> AttributeError: type object 'super' has no attribute '__getattr__'

when calling `print(doc.session_context.request.aruments)` inside the callback passed to `bokeh.server.server.Server` (terrible name-spacing, BTW).  As far as I understand, the call should be to `super().` rather than `super.`. 

Thanks

### PR DESCRIPTION
**Pull request by nils-werner**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes #10536
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

This is a very simple PR, fixing issue #10536.

### CODE REVIEW

**Comment by bryevdv** [comment]
Thanks for the PR @nils-werner ! Just checking your interest for a little further work:  It looks like the place that has tests for `request.cookies` and `request.arguments` but is missing a test for `request[....]` (which is why this bug went unnoticed) is here:

https://github.com/bokeh/bokeh/blob/branch-2.3/tests/unit/bokeh/server/test_server__server.py#L452-L493

Would you be interested to also add a test to this PR?  (A minimal test would just make sure the method is invoked and does not raise unexpected exceptions)

**Comment by nils-werner** [comment]
Yes, I'd absolutely be interested to do that, once I get the environment running.

**Comment by bryevdv** [comment]
@nils-werner fantastic, let me know  there are any questions I can help with. In this case you would only need to worry about Python unit tests running locally, which greatly simplifies things.

**Comment by bryevdv** [comment]
Another PR has all unit tests failing and I suspect it is some dependency or downstream issue. I am going to restart the tests here to test that hypothesis.

**Comment by bryevdv** [comment]
@nils-werner if you can merge/rebase on latest `branch-2.3` then the CI errors should go away. Do you still expect to be able to add a basic test?

**Comment by nils-werner** [comment]
I've rebased the branch.

> has tests for `request.cookies` and `request.arguments` but is missing a test for `request[....]`

Are you sure? We are talking about `__getattr__()` here, which is called for `request.foo` if the attribute `foo` wasn't defined...

**Comment by bryevdv** [comment]
@nils-werner you are correct, I spoke in haste, this would be a test for attributes of the request, not `[...]`

**Comment by bryevdv** [comment]
@nils-werner also I am afraid you will have to rebase one more time, there was also a new version of `mypy` released that broke our CI as well, and the latest changes pin `mypy` to resolve that for now.

**Comment by nils-werner** [comment]
Of course, I have rebased the branch.

> this would be a test for attributes of the request

I couldn't find any attributes that would trigger these lines of code, can you give me a hint which one to use?

**Comment by bryevdv** [comment]
@nils-werner I will have to do some investigation, Given the OP, I think any test accessing 
```
doc.session_context.request.aruments
```
would suffice, but the existing tests *already* do that, and were not failing before, so something is amiss.

**Comment by bryevdv** [comment]
@nils-werner I only just recalled the OP actually was due to a typo:
```
print(doc.session_context.request.aruments)
```
i.e. `aruments` instead of `arguments`. This results in an `AttributeError` for `getattr` but even now with the fix, the result of calling that code is still an `AttributeError`, just for `aruments` now instead of `getattr`. I'm not sure of good way to test that. It's probably not impossible, but would be very hacky, and it's not like we have hacky tests to guard against "uncalled super" anywhere else, so why have just here? So, I will just merge now. Thanks for the PR!

**Review by bryevdv — APPROVED** [review]

**Pull request merged**
