### PR TITLE
Docker image build and use

### PR DESCRIPTION
**Pull request by ianthomas23**
This PR updates the docker image to the point that it is usable, although probably not by end users yet. It closes issue #11352.

I will write a new "Working document" in the wiki to explain how it is used and built. Here is a summary of the improvements:

  * Image is built on demand in github actions using `.github/workflows/bokeh-docker-build.yml`. There is an option to build and run the tests or not, if you do then the failed visual test images are saved in an artifact as usual.
  * Image is tagged with 3 tags: `latest`, the date of building and major version of chrome. So a new image built today would be known as all of `bokeh-dev:latest`, `bokeh-dev:chrome_96` and `bokeh-dev:2021-12-06`.
  * Image is stored in an artifact for download. Need to add option to upload to docker hub.
  * Use of image is fully tested on Ubuntu and Windows 10. Care is needed with line endings on Windows.
  * There is now a script used to start the docker container so that users do not need to deal with uids/gids/paths, etc.
  * There is an option to use a particular version of python in conda via a particular `ci/environment-test-3.x.yml` file.
  * Conda is installed in user's home directory in docker container so that there are no problems with this being on a different filesystem.
  * When you close the docker container it is retained on disk for restarting so that you don't have to reinstall conda every time.

Test workflow now:
  1. Download latest docker image as artifact from https://github.com/bokeh/bokeh/actions/runs/1521258068
  2. Unzip `artifact.zip` to extract `bokeh-dev.tar`
  3. `docker load -i bokeh-dev.tar`
  4. `cd` to base directory of `bokeh` git repo on your local machine.
  5. `ci/docker/docker_run.sh bokeh-dev:latest` to start new container. May need to use `bash ci/docker/docker_run.sh bokeh-dev:latest` on Windows.
  6. The container will start, and download and install the `conda` requirements.
  7. When this is done, you will get a `bash` prompt in the container.
  8. Build bokeh (including installing `npm` etc) using `bash ci/install_node_modules.sh` then `python setup.py install`.
  9. Run tests as usual, e.g. `cd bokehjs; node make test:integration -k "Blackbody"`
  10. `exit` to leave the container and return to host command-line.
  11. If you want to restart the container, identify the container id using `docker ps -a` and start it using `docker start -i <container_id>`

Problems:
  * Cannot obtain old version of google-chrome for Ubuntu (`deb` file) from a reliable source, so we will need to build the image often enough to always have at least one tagged image for each chrome major version.
  * Need bokeh to work with chrome 96.
  * There are some visual test failures in the docker container relating to missing ellipses … and null ∅ characters. Need to check if these are unicode issues.

To do
  * Fully test use of image on macOS.
  * Add option to automatically upload to docker hub via github actions when build new image. It looks like this needs a username and password in GHA `secrets`.

### CODE REVIEW

**Comment by ianthomas23** [comment]
Wiki page is here: https://github.com/bokeh/bokeh/wiki/Docker-dev-container

**Comment by bryevdv** [comment]
> Cannot obtain old version of google-chrome for Ubuntu (deb file) from a reliable source, so we will need to build the image often enough to always have at least one tagged image for each chrome major version.

I guess at this point wider things need some consideration. As I've mentioned in passing before, I think we should consider picking a chrome version for each release branch, and sticking with that one version the entire length of the branch. I.e. I would propose

* A new `branch-x.y` is created
* At the same time, a new `bokeh-dev-x.y` image is also published
* This image is both the "user dev" image as well as the image that runs the test in CI
* If there is some exception need, we can rev to `bokeh-dev-x.y-1`, etc 

I am proposing an  a tradeoff here, namely that we stop running the baseline tests on OSX and Windows, and we stop updating to follow chrome all the time, in order to get our ongoing ops/maintenance burden town to manageable levels. I am really, truly OK with this tradeoff. I can't point to a single issue that was detected ***only***  due to baseline differences that affect OSX or Windows, but did not affect Linux. But I can point to an *enormous* amount of time expended on painful ops churn just for its own sake. 

This is an explicit recognition of *the reality of our limited organizational capacity*, and the fact that we are stuggling heavily under the current system. The value provided by the amount of baseline testing we currently do is not justified by its cost. If we adopt the above scheme, then:

* Anyone can generate ay new baseline and reference images completely locally, and not have to go through a multi-CI-run process, downloading artifacts from arcane GH pages and unzipping them in precise locations. This is almost worth the change all by itself
* We will only have one image to maintain at a time (per active release branch). Users using the docker workflow will be guaranteed to be in sync with CI, and ready to go without more work from us.
* Docker image can also potential be an option of last resort for folks who can't get webdrivers working 
* Exploding baseline and image storage and bandwidth costs will be reduced. 

cc @bokeh/dev

**Comment by bryevdv** [comment]
One untested assumption above is that the container could be used to run the tests in CI. However, from GH documentation I believe this should be fairly straightforward:

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idcontainer

We might need to add some scripts that are meant to be run inside the contaiter that actually run the tests but that also e.g. ensure the container and release branch are in agreement

**Comment by ianthomas23** [comment]
I like the idea of dropping the osx and windows baseline images and only using the linux ones. I think this will be particularly helpful in getting new contributors through their first PR.

For naming of the version-specific images, it would be more docker-like to use `bokeh-dev:x.y` rather than `bokeh-dev-x.y`, i.e. keeping the same image name (before the colon) but changing the tag (after the colon). But this is just a detail, the system is flexible enough to support either way of working or indeed to change it in future if we have a better/different idea.

I agree that using a docker image to run the tests in CI should be pretty easy.

One feature I have added is setting an environment variable `BOKEH_IN_DOCKER=1` whenever the image is run in a container, so it may be possible to keep a single set of scripts for testing, etc, that can be used both inside and outside of an image and just have additions based on whether the env var is set or not. This might be better than duplicating scripts.

**Comment by bryevdv** [comment]
I've copied and started a proper discussion here https://github.com/bokeh/bokeh/discussions/11893

**Pull request merged**
