### PR TITLE
Task/move travis from example

### PR DESCRIPTION
**Pull request by damianavila**
This supersede #1778 because I did not use `git mv` before causing a mess...

### CODE REVIEW

**Comment by damianavila** [comment]
This is WIP, still I have to fix some paths...

**Comment by bryevdv** [comment]
Is that `__init__.py` actually needed?

**Comment by damianavila** [comment]
probably not... I have to check...
Btw, @mattpap I am getting some errors we saw before... some time ago... do you remember the problem? It is something related with the splitjs and those options, IIRC, because locally it is working for me with `BOKEH_DEFAULT_NO_DEV=True`

```
>>> Testing /home/travis/build/bokeh/bokeh/examples/glyphs/buttons_server.py ...
[WARN] Timeout
[FAIL] http://localhost:5006/bokehjs/static/css/bokeh.css: 404 (NOT FOUND)
[FAIL] http://localhost:5006/bokehjs/static/js/vendor/requirejs/require.js: 404 (NOT FOUND)
[FAIL] http://localhost:5006/bokehjs/static/js/config.js: 404 (NOT FOUND)
ReferenceError: Can't find variable: require
    http://localhost:5006/bokeh/doc/buttons_server/show: 19
[FAIL] /home/travis/build/bokeh/bokeh/examples/glyphs/buttons_server.py
```

**Comment by mattpap** [comment]
@damianavila, I will have a look at this.

**Comment by damianavila** [comment]
Btw, there is an issue with the nbconversion of ipynb that I will solve today and push the fix, but it is not related with the issue I asked above...

**Comment by damianavila** [comment]
I guess the problem comes from here: https://github.com/mattpap/bokeh/commit/93beaaadebb0c3e079758b8ca75d03278ffcda5b

**Comment by damianavila** [comment]
> I guess the problem comes from here: mattpap@93beaaa

Well does not seem to be any problem there...

This is really weird, because locally, setting specifically `BOKEH_DEFAULT_NO_DEV=false` works as expected:
```
(py34devel)[damian@damian-S400CA][bokeh](task/move_travis_from_example)$ BOKEH_DEFAULT_NO_DEV=false nosetests

Using configuration:
--- patterns      = []
--- bokeh-port    = 5006
--- ipython-port  = 6007
--- phantomjs     = phantomjs
--- timeout       = 10
--- verbose       = False
--- dev           = True
--- all-notebooks = False
--- output-cells  = complain
--- log-file      = examples.log
--- diff          = None
--- upload        = False
Bokeh version: 0.7.1-ebd1eaa
```
And the server examples seems to work :disappointed: 

```
>>> Testing /media/datos/Desarrollos/bokeh/examples/plotting/server/line.py ...
Using saved session configuration for http://localhost:5006/
To override, pass 'load_from_config=False' to Session
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
INFO:bokeh.session:No documents found, creating new document 'line'
INFO:bokeh.session:got read write apikey
[OK] /media/datos/Desarrollos/bokeh/examples/plotting/server/line.py
```

**Comment by damianavila** [comment]
pinging @mattpap again (I don't want to be annoying, just pinging you as a reminder :wink:), any idea where could be the problem?

**Comment by mattpap** [comment]
@damianavila, sorry, I overlooked you pinging me before.

The issue was that debug mode on the server assumed a development environment, i.e. `bokehjs/build`, but on travis-ci, we install dev build using conda, so all files are in `bokehs/server/static`. Now settings code will check whether `bokehjs/build` exists, and if not, it will use `static` directory.

**Comment by damianavila** [comment]
>The issue was that debug mode on the server assumed a development environment, i.e. bokehjs/build, but on travis-ci, we install dev build using conda, so all files are in bokehs/server/static. Now settings code will check whether bokehjs/build exists, and if not, it will use static directory.

ohh... how I missed that!! Now I see what why I did not understood... I saw bokehjs building and I could not understood why the files were not there, but the building was to create the conda package which is installed later by conda... that was the source of my confusion... grrr.... 
Well, at least I was near the problem when I first referenced your commit (mattpap@93beaaa)... now I understand better the issue, thanks for the help! :+1: and the fix!

**Comment by damianavila** [comment]
>The issue was that debug mode on the server assumed a development environment, i.e. bokehjs/build, but on travis-ci, we install dev build using conda, so all files are in bokehs/server/static. Now settings code will check whether bokehjs/build exists, and if not, it will use static directory.

ohh... how I missed that!! Now I see what why I did not understood... I saw bokehjs building and I could not understood why the files were not there, but the building was to create the conda package which is installed later by conda... that was the source of my confusion... grrr.... 
Well, at least I was near the problem when I first referenced your commit (mattpap@93beaaa)... now I understand better the issue, thanks for the help! :+1: and the fix!

**Comment by mattpap** [comment]
Added missing import. Let's see if it works now.

**Comment by damianavila** [comment]
OK, this is ready and working as expected, I will merge it tomorrow morning unless there is any objections...

**Pull request merged**
