### PR TITLE
More gallery / user guide improvements

### PR DESCRIPTION
**Pull request by bryevdv**
This PR adds bare-bones content for stats and pie charts sections. Mostly, this was just to get relevant plots situated in the docs and/or gallery. As part of this, the anscombe and splom plots were re-added now that their layout issues are resolved. Additionally, some of the examples were streamlined and simplified in order to make them suitable for the user's guide. 

@tcmetzger any quick edits/corrections would be welcome. Assuming we have a week or two before release, hopefully these sub sections can be expanded. 

Still TBD (future PR) is a timeseries section.

### CODE REVIEW

**Comment by bryevdv** [comment]
Noting that the splom example could be improved: we currently share ranges across *all*plots, but really we should broadcast a separate x range across every plot in each column, and similar for y ranges and rows. That would allow data scaling to function better, letting the data fill the plots better.

**Comment by bryevdv** [comment]
OK I fixed the splom docs issue (🤞 ) and at the same time made the improvements described above.

**Comment by tcmetzger** [comment]
@bryevdv This looks great! I added a few small fixes and style suggestions in my commit, I can take another look tomorrow!

**Comment by bryevdv** [comment]
@tcmetzger I will go ahead and merge this, we can add/edit more in future PRs.

**Pull request merged**
