### PR TITLE
Fixed empty plot in the sample codes of section Updating fom unlocked callbacks

### LINKED ISSUE #14196: [BUG] Documentation - sample codes in Application > Updating from unlocked callbacks shows an empty plot.
### Software versions

In the user guide of Application > Updating from unlocked callbacks, the sample codes have a bug such that the plot appears to be not working.

https://docs.bokeh.org/en/latest/docs/user_guide/server/app.html#updating-from-threads

https://github.com/bokeh/bokeh/blob/5be848f0e7fa34301cd7b390426328dbf7a78d6c/docs/bokeh/source/docs/user_guide/server/app.rst?plain=1#L528

It is missing `radius`, and should be something like:
```python
l = p.circle(x="x", y="y", radius=0.5, color="color", source=source)
```

Without `radius`, users simply an empty plot.

---

Version: 3.6.2

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

The plot should progressively show more data.

### Observed behavior

The plot is empty.

### Example code

```Python
N/A (see the buggy sample codes in the doc).
```

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by orionlee**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes #14196
- [ ] tests added / passed
- [x] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
Hi @orionlee thanks for the PR. This was due to an API change awhile back. This code block was missed for update because it's inline in the docs file and got overlooked. 

I'd like to propose a slightly different fix, though. Rather than add a `radius` parameter to the `circle` call, I think it would be preferable to change the `circle` call to`scatter`. That will be completely equivalent to the original code, i.e. a scatter plot of circles with *pixel* size. Do you mind pushing that change to your branch?

**Comment by orionlee** [comment]
@bryevdv Use `scatter()` in the latest commit. 

Note: Replacing `circle()` with `scatter()` is slightly non-automatic, because `scatter(marker='circle', radius=3, ...)` is also deprecated. So I had to use  `scatter(marker='circle', size=...)` instead. But the scales of `radius` and `size` are different.

**Comment by bryevdv** [comment]
@orionlee sorry I should have been more explicit, I was suggesting:
```
p.scatter(marker='circle', x='x', y='y', source=source)
```
with neither `size` nor `radius`. That will use the default size for scatter (8px, I think)

As for the difference: scatter markers have a size in pixels, which does not scale at all regardless of zoom level. Radius is in "data units" and scales according to zoom.

**Comment by orionlee** [comment]
@bryevdv Does this PR need to be changed? The size (10) I use makes the circles larger (similar to the `radius=0.02` in the existing sample codes.)

**Comment by bryevdv** [comment]
@orionlee the appearance is not at all the focus of this example, so I would prefer to keep things as simple as possible without any extraneous settings that don't relate to updating from unlocked callbacks

**Comment by orionlee** [comment]
@bryevdv Done. `size` is now removed from the example.

**Comment by bryevdv** [comment]
Thanks @orionlee !

**Pull request merged**
