### PR TITLE
New charts interface

### PR DESCRIPTION
**Pull request by fpliger**
Continuation of work in #2088 

It's a first step in the direction of #2442 and https://github.com/bokeh/bokeh/wiki/Bokeh-Days-Working-Document

### CODE REVIEW

**Comment by fpliger** [comment]
@bryevdv @rothnic It's a super experimental approach for now... but would love to hear your thoughts about it. 
Specially regarding the new builders design (see https://github.com/bokeh/bokeh/pull/2694/files#diff-a3a015b8efa6858fac7d8c9800a34e5aR34 for instance) and this new "High Level Glyph". Of course now it's not really a "Glyph" but just making things a little more componentized.

**Comment by rothnic** [comment]
Will take a look at the composite glyph concept. Couldn't tell from first glance, but my thought behind it was that the composite glyph would represent a subset (or group) within the primary data source.

So, if I created boxes for each 'cyl' (3,4,5,6,8) in the autompg dataset using values of 'mpg', then the collection of glyphs are all associated with the specific value of 'cyl' (e.g. 3). 

However, what if we decided to also pass into the box plot color='origin'. Then we'd have a composite box for each combination found in `df[['cyl', 'origin']].drop_duplicates()`. 

For scatter it is the same thing, the composite glyph represents the lowest level of unique visual attributes associated with the grouping. So color by 'cyl' and marker by 'origin' would apply the same `df[['cyl', 'origin']].drop_duplicates()` to assign attributes to each unique group of data.

When looking at the BoxPlotBuilder it appears to require grouped data? [Here](https://github.com/bokeh/bokeh/wiki/Bokeh-Days-Working-Document#boxplot-violin) is the section about box/violin plots in the wiki. To avoid pre-plotting data manipulation for table data, you would have to provide the column associated with the splitting of the boxes, then the col that contains the values to be used to generate the box attributes.

I'll take a look at it tonight.

**Comment by fpliger** [comment]
> Will take a look at the composite glyph concept. Couldn't tell from first glance, but my thought behind it was that the composite glyph would represent a subset (or group) within the primary data source.

> So, if I created boxes for each 'cyl' (3,4,5,6,8) in the autompg dataset using values of 'mpg', then the collection of glyphs are all associated with the specific value of 'cyl' (e.g. 3).

@rothnic  what the composite glyph there does is take the primary data source and which subset of the datasource to consider (i.e. mpg), creates an independent datasource [with the computed data needed create the glyph] only for the data it's operating on and create it's glyphs and renderers. As we have discussed recently the idea is that we tag this new independent datasource to identify it and somehow "link" the primary data source that it's being generated from (so that we can then somehow build a syntax that can be useful to use for, i.e., hover tool to access this original data source).

It's a really thin design prototype and it's missing all the grouping and filtering functionality to support things like color by 'cyl' and marker by 'origin'. I'd like to discuss the idea (add this new Composite Glyph Layer) and see if it's a good base to then add the juicy functionality we have been discussing about and where (i.e., on the Composite Glyph or on the Builders?).


> However, what if we decided to also pass into the box plot color='origin'. Then we'd have a composite box for each combination found in df[['cyl', 'origin']].drop_duplicates().

Mmm... that's actually something I've overseen on the wiki. In that case how different are:

```Box(data, 'val', 'cat1', grouped='cat2')```

and

```Box(data, 'val', 'cat1', color='cat2')```

?

> For scatter it is the same thing, the composite glyph represents the lowest level of unique visual attributes associated with the grouping. So color by 'cyl' and marker by 'origin' would apply the same df[['cyl', 'origin']].drop_duplicates() to assign attributes to each unique group of data.

> When looking at the BoxPlotBuilder it appears to require grouped data? Here is the section about box/violin plots in the wiki. To avoid pre-plotting data manipulation for table data, you would have to provide the column associated with the splitting of the boxes, then the col that contains the values to be used to generate the box attributes.

I didn't change anything regarding the current input supported by Line/Scatter/Boxplot. I actually wanted to see the same previous examples running with this new design to have an evaluation of the architecture without changing the inputs. The goal at this stage is not to decide the shape of the data we need to consume but instead evaluate the implementation details.

Sorry, I should have been more explicit about this. The scope of this branch (specially at this point) is not to propose a complete implemented solution for everything we have been discussing (neither I believe we'll be able to do to in just one iteration). It is instead to provide a very minimal approach to the problem and receive feedback if the direction is shared by the team. So, in this case the very focused goal is to evaluate if a `Composite Glyph` like this is a good choice or not.

You made me remember another important question: if the `Composite Glyph` implementation is in the good direction should we keep the data preparation on the `Builder` or move it to the `Composite Glyph`? If we keep it on the `Builder` we'll need to change the `Composite Glyph` and make it more "data agnostic" otherwise we, if we take the data preparation out of the builder in favor a richer composite glyph, then we probably just need one "main" `Builder` that just uses the right `Composite Glyph`.

**Comment by rothnic** [comment]
OK, there are two things I guess I addressed:

1. What level does the composite glyph operate
2. Non-grouped input into charts (x, y input)

Sounds like for 2, you want to address that later. That's ok.
For 1, this is where we'd need to consider what it represents. What I was assuming was this flow:

`Table -> ScatterBuilder -> Data Manipulation -> Loop over each thing we've called an index in the past -> Create ScatterGlyph for each index`

The thought being that you want to separate all the grouping operations out of building these composite glyphs. If you provide something like `mpg` to it, then grouping functionality must exist in composite glyph.

So, if I had these mpgs associated with a cylinder of `4`, `[34, 45, 22, 33, 36, 35, 33, 26]`, that is the array I think we'd pass to the box composite glyph. That way you don't deal with the grouping problem in the same place as the statistics and various lower level glyph creation.

**Comment by fpliger** [comment]
Cool. We are definitely on the same page. Separating glyph manipulation from data manipulation so chart builder handles grouping for the table-oriented inputs, then would create a composite glyph for each subset of data.

I'll improve the current code in the next days by turning `CompositeGlyphs` even more data agnostic and by adding more of the data manipulation to the builders.

**Comment by bryevdv** [comment]
This was closed because `dev_0.10` was deleted. Resubmit against master if there is something that should still be merged.

**Pull request closed without merging**
