### PR TITLE
Bryanv/4363 notebook unminified

### LINKED ISSUE #4363: Bokeh Server w/ multiple processes
Optionally run Bokeh Server with multiple process.  This is useful when scaling an application especially when there are larger computational loads

```
bokeh serve file.py --nprocs N
```

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #4363

ping @mattpap OK this sucks for sure, but it works to let un-minified inline resources work in the notebook. I'd like to propose merging this for now, until you figure out what to do longer term for `bokeh-compiler.js`

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap I have to look at #3639 again, I think this has to be merged. There is zero chance of debugging without being able to use unminified resources.

**Comment by bryevdv** [comment]
I will merge in the next hour or so unless there's comment.

**Comment by mattpap** [comment]
This isn't great, but we can live with this. The `replace` line will be removed when compiler is removed.

**Comment by bryevdv** [comment]
Agreed

**Pull request merged**
