### PR TITLE
Remove old deprecations

### PR DESCRIPTION
**Pull request by bryevdv**
This PR removes all the 3.0 deprecations. 

There is also still the HSL deprecation from 2.3.1 present. Do we want to just un-deprecate this? The lighten/darken are useful in and of themselves and some folks have asked to keep it. 

Otherwise as far as I can tell, all remaining deprecations are recent from 3.4

### CODE REVIEW

**Comment by mattpap** [comment]
> There is also still the HSL deprecation from 2.3.1 present. Do we want to just un-deprecate this? The lighten/darken are useful in and of themselves and some folks have asked to keep it.

I would keep it for now and perhaps redesign/simplify the code in spare time while keeping the core functionality.

**Review by mattpap — APPROVED** [review]

**Comment by bryevdv** [comment]
> I would keep it for now and perhaps redesign/simplify the code in spare time while keeping the core functionality.

Just making it clear for myself, you would keep HSL and *remove the current deprecation around it*?

**Comment by mattpap** [comment]
> Just making it clear for myself, you would keep HSL and remove the current deprecation around it?

I'm not sure right now. I really need to have a look a the current state there.

**Comment by bryevdv** [comment]
Well, I removed the deprecation for now. We can always re-add if need be.

**Pull request merged**
