### PR TITLE
Remove references to gen.coroutine from docs and update without_document_lock decorator

### LINKED ISSUE #11716: [BUG] Docs still mention @gen.coroutine
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.4, python 3.7.6, OS Big Sur 11.5, Chrome

#### Description of expected behavior and the observed behavior
Unlocked callbacks work with Bokeh 1.4.0 any version above the callbacks just execute after the "locking code" has finished.  The issue was replicated using the attached code from Bokeh 2.4.0 online manual, it work with Bokeh 1.4.0, I have not been able to make it work with any version above that.

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

from functools import partial
import time

from concurrent.futures import ThreadPoolExecutor
from tornado import gen

from bokeh.document import without_document_lock
from bokeh.models import ColumnDataSource
from bokeh.plotting import curdoc, figure

source = ColumnDataSource(data=dict(x=[0], y=[0], color=["blue"]))

i = 0

doc = curdoc()

executor = ThreadPoolExecutor(max_workers=2)

def blocking_task(i):
    time.sleep(1)
    return i

# the unlocked callback uses this locked callback to safely update
@gen.coroutine
def locked_update(i):
    source.stream(dict(x=[source.data['x'][-1]+1], y=[i], color=["blue"]))

# this unlocked callback will not prevent other session callbacks from
# executing while it is running
@gen.coroutine
@without_document_lock
def unlocked_task():
    global i
    i += 1
    res = yield executor.submit(blocking_task, i)
    doc.add_next_tick_callback(partial(locked_update, i=res))

@gen.coroutine
def update():
    source.stream(dict(x=[source.data['x'][-1]+1], y=[i], color=["red"]))

p = figure(x_range=[0, 100], y_range=[0,20])
l = p.circle(x='x', y='y', color='color', source=source)

doc.add_periodic_callback(unlocked_task, 1000)
doc.add_periodic_callback(update, 200)
doc.add_root(p)

```

#### Screenshots or screencasts of the bug in action

*Note: Everyone interacting in the Bokeh project's codebases, issue trackers, and discussion forums is expected to follow the [Code of Conduct](https://github.com/bokeh/bokeh/blob/master/CODE_OF_CONDUCT.md).*

### PR DESCRIPTION
**Pull request by benrussell80**
# Changes
Remove references to `tornado.gen.coroutine` in docs in favor of async functions.
Change `bokeh.document.locking.without_document_lock` to work for async functions and functions decorated with `asyncio.coroutine`.

- [ ] issues: fixes #11716
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@benrussell80 this is great, do you have any more bandwidth to continue a little further on this? Ideally there would be a minimal test of `without_document_lock` acting on a coroutine, and an update to the docstring to make it clear that coroutines are acceptable.

**Comment by benrussell80** [comment]
@bryevdv Yeah can do

**Comment by benrussell80** [comment]
Test and docstring modification added. Let me know if they are up to snuff.

I got this warning from pytest when using asyncio.

```
DeprecationWarning: The 'asyncio_mode' default value will change to 'strict' in future, please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.
    config.issue_config_time_warning(LEGACY_MODE, stacklevel=2)
```

**Review by bryevdv — APPROVED** [review]

**Comment by benrussell80** [comment]
No problem @bryevdv! I love bokeh, and I'm hoping to be able to contribute more

**Pull request merged**
