### PR TITLE
Support embed bokeh app in Zeppelin

### LINKED ISSUE #6788: Make notebook display extendible by external libraries
#### Description of expected behavior and the observed behavior
I'd like to embed bokeh app into Apache Zeppelin just as embed bokeh app in Jupyter

### PR DESCRIPTION
**Pull request by zjffdu**
- [ ] issues: fixes #6788 
- [ ] tests added / passed, I didn't find a proper way to add unit test for this feature. I just manually verify it in Apache Zeppelin.
- [ ] release document entry (if new feature or API change)

Screenshot of my verification in Zeppelin. I run the same example of embedding bokeh app in Jupyter.
image

### CODE REVIEW

**Comment by bryevdv** [comment]
@zjffdu There's another PR #6774 to get Bokeh working with JupyterLab that deletes `_server_cell` and all of that gorpy cell mutation in favor of Jupyter's mime extension mechanism.  I'd like for apps to work in Zeppelin as well, but rather that add all that back to the main repo, I am wondering if a new `bokeh/bokeh-zeppelin` might not be a reasonable way forward. Then code that is zeppelin-specific can have a proper home. I think a small focused issue would make it easier for you and hopefully others in the future to continue maintenance of it. 

This will have to wait until after `0.12.7` in any case, we are too close to freeze. 

ping @canavandl

**Comment by zjffdu** [comment]
Thanks @bryevdv It's a good idea to have `bokeh-zeppelin` for zeppelin specific stuff. 
Will #6774 be merged into 0.12.7 ? Is it possible to merge this PR into 0.12.7 and move zeppelin stuff into `bokeh-zeppelin` in 0.12.8 ?

**Comment by bryevdv** [comment]
#6774 will definitely be merged for `0.12.7` and that PR changes and removes things that this PR depends on, which is why I don't think this can be included in `0.12.7`

**Comment by zjffdu** [comment]
@bryevdv I rebase the PR, and it works in Zeppelin. I can do the improvements in the next version. But do you mind to merge it into `0.12.7` ? I'd like to have zeppelin community use this feature as early as possible.

**Comment by bryevdv** [comment]
@zjffdu The problem with the current code is that nothing will clean up anything when cells are re-run or deleted. If there are periodic callbacks, or threads, or large data structures allocated, they will just continually pile up. I think that is a bad experience that will reflect poorly on Bokeh. Thinking about it, I'm not certain the original PR would have done clean up either, since the cell-mutation watcher code was somewhat tuned to the DOM structure of Jupyter notebooks. In any case I am -1 on intentionally adding such a gaping resource leak. 

Here is a plan I could support: All the places where the code switches on "notebook type" and calls a built-in function, have it look for and call a function that could be "installed" by a separate project instead. That makes the next release future-ready for a `bokeh-zeppelin` extension at any time as soon as its ready, without having to wait for another full Bokeh release.

**Comment by bryevdv** [comment]
To elaborate on the idea:

have `io.py` have a module level dict:
```
_notebooks = {
    'jupyter' : { 
        'show_standalone_with_state' : show_jupyter_standalone_with_state,
        'show_app_with_state' : show_jupyter_app_with_state,
    }
}
```
That much would be built in. A `bkzep` package could install more when it is imported:
```
_notebooks = {
    'jupyter' : { 
        'show_standalone_with_state' : show_jupyter_standalone_with_state,
        'show_app_with_state' : show_jupyter_app_with_state,
    },
     'zeppelin' : { 
        'show_standalone_with_state' : bkzep.show_zeppelin_standalone_with_state,
        'show_app_with_state' : bkzep.show_zeppelin_app_with_state,
    }
}
```
Then all the code that switches on notebook type can be generic, it can look up the notebook type can then call the appropriate function for showing a satandalone doc or an app. If this code went into `0.12.7` then a new `bkzep` package could work immediately as soon as it is ready.

**Comment by bryevdv** [comment]
I am actually going to bang out a PR for these changes now.

**Comment by bryevdv** [comment]
@zjffdu I am marking this as superseded by #6799 and closing. 

With the changes in that PR, you an immediately distribute a small function to install any display hook you like for zeppelin (e.g. even if it leaks resources but otherwise works or is suitable to your needs) That's a little clumsy bust serviceable in the immediate term. Then slightly further out I would recommend a separate project to maintain the zeppelin notebook hook (or maybe it could be part of some other existing zeppelin project)

**Pull request closed without merging**
