### PR TITLE
Backports for 3.3.3

### PR DESCRIPTION
**Pull request by mattpap**
This PR collects bug-fixes and tasks for a 3.3.3 release:

- [x] https://github.com/bokeh/bokeh/pull/13572
- [x] https://github.com/bokeh/bokeh/pull/13577
- [x] https://github.com/bokeh/bokeh/pull/13603
- [x] https://github.com/bokeh/bokeh/pull/13559 
- [x] https://github.com/bokeh/bokeh/pull/13602 
- [x] https://github.com/bokeh/bokeh/pull/13627
- [x] https://github.com/bokeh/bokeh/pull/13640
- [x] https://github.com/bokeh/bokeh/pull/13596
- [x] https://github.com/bokeh/bokeh/pull/13527
- [x] https://github.com/bokeh/bokeh/pull/13630
- [x] https://github.com/bokeh/bokeh/pull/13633
- [x] https://github.com/bokeh/bokeh/pull/13639
- [x] https://github.com/bokeh/bokeh/pull/13549
- [x] https://github.com/bokeh/bokeh/pull/13528
- [x] https://github.com/bokeh/bokeh/pull/13514
- [x] https://github.com/bokeh/bokeh/pull/13609
- [x] https://github.com/bokeh/bokeh/pull/13613
- [x] https://github.com/bokeh/bokeh/pull/13615
- [ ] https://github.com/bokeh/bokeh/pull/13635
- [x] 3.3.3 release notes
- [x] updated `switcher.json`
- [ ] do **not** squash merge

### CODE REVIEW

**Comment by bryevdv** [comment]
There's quite a few small docs/examples PRs that could probably also go in.

**Comment by mosc9575** [comment]
I think the [LICENSE.txt](https://github.com/bokeh/bokeh/blob/branch-3.4/LICENSE.txt) should be updated to 2024 for this release. I guess there are some more places where the year has to change.

**Comment by mattpap** [comment]
This is now fully ready.

**Comment by mosc9575** [comment]
Hi @mattpap, if there is no rush, we could also add some improvements to the docs.

I am thinking of the issues @bryevdv mentioned in https://github.com/bokeh/bokeh/pull/13553#issuecomment-1830471930
> If there is a hurry, that's fine with me, otherwise I'd have a quick look at these as well

* https://github.com/bokeh/bokeh/pull/13549
* https://github.com/bokeh/bokeh/pull/13528
* https://github.com/bokeh/bokeh/pull/13514
* https://github.com/bokeh/bokeh/pull/13501
* https://github.com/bokeh/bokeh/pull/13496

**Comment by mattpap** [comment]
I want to release today, but I still need to get this https://github.com/bokeh/bokeh/pull/13635 one in, so I can add more along the way, if the don't cause problems.

**Comment by mattpap** [comment]
I included PR #13635, tough it wasn't merged yet, to expedite the process.

**Comment by bryevdv** [comment]
LGTM

**Comment by mosc9575** [comment]
I took a look into the logs of the docs pipeline and I found a `ThemeError` and a link `https://docs.bokeh.org/en/3.3.2+21.gc3bb7e92/docs/dev_guide.html`, but opening the page it gives a 404 warning. To me it looks like the process was not successful.

<details>
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 1127, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/jinja2glue.py", line 200, in render
    return self.environment.get_template(template).render(context)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html", line 10, in top-level template code
    {% set remove_sidebar_secondary = (meta is defined and meta is not none and 'html_theme.sidebar_secondary.remove' in meta) or not theme_secondary_sidebar_items %}
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/themes/basic/../basic/layout.html", line 114, in top-level template code
    {%- block css %}
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html", line 21, in block 'css'
    {{- css() }}
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/themes/basic/../basic/layout.html", line 95, in template
    {{ css_tag(css) }}
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 1063, in css_tag
    if checksum := _file_checksum(outdir, css.filename):
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/html/_assets.py", line 138, in _file_checksum
    raise ThemeError(msg)
sphinx.errors.ThemeError: Local asset file paths must not contain query strings: '_static/custom.css?v=3.3.2+21.gc3bb7e92'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/cmd/build.py", line 298, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/application.py", line 355, in build
    self.builder.build_update()
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 363, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 571, in write
    self._write_serial(sorted(docnames))
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 581, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 655, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 1134, in handle_page
    raise ThemeError(__("An error happened in rendering the page %s.\nReason: %r") %
sphinx.errors.ThemeError: An error happened in rendering the page docs/dev_guide.
Reason: ThemeError("Local asset file paths must not contain query strings: '_static/custom.css?v=3.3.2+21.gc3bb7e92'")

Theme error:
An error happened in rendering the page docs/dev_guide.
Reason: ThemeError("Local asset file paths must not contain query strings: '_static/custom.css?v=3.3.2+21.gc3bb7e92'")
</details>


I believe we have to add #13560, too.

**Comment by mosc9575** [comment]
There is still an error in the docs pipeline:

```The HTML pages are in build/html.
cp: cannot stat '../../src/bokeh/server/static': No such file or directory
```

but the original problem is solved.

There are also some warnings in the logs that are already solved, but they are hard to cherry pick.
```
/home/runner/work/bokeh/bokeh/docs/bokeh/source/docs/examples/topics/categorical/correlogram.rst:3: WARNING: undefined label: 'sampledata_forensic_glass'
/home/runner/work/bokeh/bokeh/docs/bokeh/source/docs/examples/topics/categorical/correlogram.rst:5: WARNING: undefined label: 'ug_topics_categorical_scatters'
/home/runner/work/bokeh/bokeh/docs/bokeh/source/docs/examples/topics/categorical/slope_graph.rst:3: WARNING: undefined label: 'sampledata_emissions'
/home/runner/work/bokeh/bokeh/docs/bokeh/source/docs/examples/topics/categorical/slope_graph.rst:5: WARNING: undefined label: 'ug_topics_categorical_scatters_segment'
/home/runner/work/bokeh/bokeh/docs/bokeh/source/docs/examples/topics/stats/pyramid.rst:3: WARNING: undefined label: 'sampledata_titanic'
/home/runner/work/bokeh/bokeh/docs/bokeh/source/docs/examples/topics/stats/pyramid.rst:5: WARNING: Failed to create a cross reference. A title or caption not found: 'ug_topics_stats_pyramid'
/home/runner/work/bokeh/bokeh/docs/bokeh/source/docs/examples/topics/stats/sinaplot.rst:3: WARNING: undefined label: 'sampledata_lincoln'
/home/runner/work/bokeh/bokeh/docs/bokeh/source/docs/examples/topics/stats/sinaplot.rst:5: WARNING: Failed to create a cross reference. A title or caption not found: 'ug_topics_stats_sinaplot'
```

These are silenced in #13613 and #13615.

**Comment by mattpap** [comment]
> `cp: cannot stat '../../src/bokeh/server/static': No such file or directory`

This fails in 3.4-dev as well, e.g. in https://github.com/bokeh/bokeh/actions/runs/7416176428/job/20180761135?pr=13635.

**Comment by mattpap** [comment]
Out of curiosity I deployed 3.4.0-dev.5, which involves the same error in docs' CI, and it looks like it deployed fine and examples work. Then perhaps we can ignore this error for now, release 3.3.3 and figure out this in 3.4.

**Comment by mattpap** [comment]
> LGTM

@bryevdv, is this a formal approval? I would like to publish 3.3.3 preferably today or tomorrow.

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
> is this a formal approval? 

Yes, sometimes the "Files changed" tab loads just slowly or badly when there are hundreds of changed files, making it harder to leave a review (unless there is some other place it can be done)

**Comment by mattpap** [comment]
I should have merged this instead of squash merged. Next time I need to use a more complete checklist.

**Comment by bryevdv** [comment]
I wish there was a technical measure to help with this, since it is easy to forget, but there is not, AFAIK. We could also just decide it's not worth the effort, and start using SOP squash merges for backports instead. We typically only have a handful of point releases on a branch and then we never revisit the branch.

**Pull request merged**
