### PR TITLE
Update helpers.py #6951

### LINKED ISSUE #6951: y_range doesn't understand numpy arrays
in the example below, `source2` works, but `source` does not. In order to get `source` to work, I have to add a `tolist()` clause (i.e. `y_range=source.data['fruits'].tolist()`)

    import pandas as pd
    import numpy as np
    import random
    from bokeh.io import push_notebook, show, output_notebook, show
    from bokeh.plotting import figure
    from bokeh.models import ColumnDataSource
    output_notebook()

    f = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']
    c = random.sample(range(0,100), 6)
    df = pd.DataFrame({'fruits':f, 'counts':c})

    source = ColumnDataSource(df)
    source2 = ColumnDataSource(data=dict(fruits=f, counts=c))

    p = figure(y_range=source.data['fruits'], plot_height=250, title="Fruit Counts",
           toolbar_location=None, tools="")
    p.hbar(y='fruits', right='counts', height=0.9, source=source)
    show(p)

    print(type(source.data['fruits'])) ## <class 'numpy.ndarray'>
    print(type(source2.data['fruits'])) ## <class 'list'>

### PR DESCRIPTION
**Pull request by hiramf**
Allow range_input to be an np.ndarray

All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes #6951 
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@hiramf this is great! Do you need any help with adding a test?

**Comment by bryevdv** [comment]
@hiramf actually regarding the imports: we use relative imports in all the implementation modules, and only use absolute imports in the test modules (just a hedge on the off chance we ever want to distribute the tests separately) Can you put them back to relative imports?

**Comment by hiramf** [comment]
Oops, was looking at the testing guide and missed the part where explicit imports applied only for test scripts.

**Comment by bryevdv** [comment]
> Oops, was looking at the testing guide and missed the part where explicit imports applied only for test scripts.

It should probably be state more clearly, thanks for reading through it!

**Comment by bryevdv** [comment]
@hiramf I closed the the other PR, the test needs to go in this PR (this is the branch that has the new code that the test should test)

**Comment by bryevdv** [comment]
Thanks @hiramf !

**Pull request merged**
