### PR TITLE
Streamline / Cleanup Properties System

### LINKED ISSUE #10867: Simplify HasProps and MetaHasProps
See discussion here:

ref: https://github.com/bokeh/bokeh/pull/10860#discussion_r563421156

### PR DESCRIPTION
**Pull request by bryevdv**
This is just WIP for preview. I will rebase on `branch-2.4` when it is made. 

- [x] issues: fixes #10867
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

There is indeed *lot* of cruft and/or unnecessary code around properties that can be jettisoned or cleaned up.

### CODE REVIEW

**Comment by bryevdv** [comment]
BTW @mattpap I am not sure about adding static annotations to our own properties. The visual result in an IDE is pretty insufferable:

Screen Shot 2021-01-29 at 12 09 54 PM

**Comment by mattpap** [comment]
>  I am not sure about adding static annotations to our own properties. The visual result in an IDE is pretty insufferable:

If you want to have any statically typed code that uses models and properties, then they have to be typed. The reason you are getting an error, is that models are not statically typed yet. They have some type annotations, but only to make other statically typed modules type check. If you enable `bokeh.models.*` in mypy (`mypy` section in `setup.cfg`), then you will see all those errors. I discussed this in another issue/PR. We need special support for our models, similar to what mypy provides for dataclasses.

Now, what is pylance and why it doesn't respect our configuration? I don't know. An orthogonal issue with (I'm guessing) vscode, is that it likes to lit up the screen with bright red underline, where it actually makes things harder to read. It's a common issue, e.g. try to change property types in bokehjs, without changing definitions, you will see nothing but red lines.

**Comment by bryevdv** [comment]
Let's keep things in smaller chunks and review and merge this is it is now. I will make a follow-on issue for other improvements.

**Comment by bryevdv** [comment]
@mattpap I'll plan  to merge this tomorrow morning unless you ask for more time.

**Pull request merged**
