### PR TITLE
Port 2.2.2 changes

### PR DESCRIPTION
**Pull request by philippjfr**
Ports changes from 2.2.2 onto branch-2.3

### CODE REVIEW

**Comment by mattpap** [comment]
Codebase failures are due to mypy update (0.790). We can either ignore and proceed or disable mypy type checks for now (I won't be able to fix those error right now).

**Comment by bryevdv** [comment]
Did this literally just updated in the two hour window between 2.2.2 release (and successful merges then) and this PR? IN any case I think pinning is the simplest temp solution.

**Comment by bryevdv** [comment]
removing from milestone, otherwise this ends up in the changelog. I'll have to create an issue to discuss tweaks to automation/process to handle multiple branches more smoothly

**Comment by bryevdv** [comment]
Also just noting: this PR did not capture the 2.2.2 CHANGELOG entry. We will need to figure out how to handle that as well since it might be non-trivial to automate

**Pull request merged**
