### PR TITLE
Make exports consider current theme

### LINKED ISSUE #10804: [BUG] export does not respect current theme
#### ALL software version info
bokeh: 2.2.3
Python: 3.8.6
OS: Windows 10
Browser: Chrome 87.0.4280.88

#### Description of expected behavior and the observed behavior
The theme of the the current document is not considered, if a svg export is used.

Part of expected result via save() (or show())
image
Part of unexpected result via export_svgs()
image

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.io import curdoc, export, save
from bokeh.plotting import figure
from bokeh.themes import Theme
from selenium import webdriver

CHROMEDRIVER_PATH = "chromedriver.exe"

curdoc().theme = Theme(json={'attrs': {
    'Figure': {
        'background_fill_color': '#2F2F2F'
    }
}})

p = figure()
p.line(x=[0, 1], y=[0, 1])

p.output_backend = "svg"
export.export_svgs(p, filename="export.svg", webdriver=webdriver.Chrome(CHROMEDRIVER_PATH))
save(p, filename="export.html")
```

#### Possible bug location / solution

According to the call of file_html
https://github.com/bokeh/bokeh/blob/d7a31e9a9604661bee0912633615c332732079ef/bokeh/io/saving.py#L148
triggered by
https://github.com/bokeh/bokeh/blob/d7a31e9a9604661bee0912633615c332732079ef/bokeh/io/saving.py#L80-L86

I assume that in get_layout_html (used by all export functions) the call
https://github.com/bokeh/bokeh/blob/d7a31e9a9604661bee0912633615c332732079ef/bokeh/io/export.py#L304-L305
should be extended:
```python
    from .state import curstate
    try:
        html = file_html(obj, resources, title="", template=template, suppress_callback_warning=True, _always_new=True, theme=curstate().document.theme)
```

If this is right, I could try to create a pull request - either as shown above (with import moved to the top) or with an additional param theme on all export methods to allow manual setting of the theme. Or did I miss something and the missing theme param was by intention?

### PR DESCRIPTION
**Pull request by HolleJ**
This PR should make exports consider the current theme.
- [x] issues: fixes #10804
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

Should I add a test to https://github.com/bokeh/bokeh/blob/branch-2.3/tests/unit/bokeh/io/test_export.py which checks that e.g. the export function works as excepted using a similar example as given in the issue?

### CODE REVIEW

**Comment by bryevdv** [comment]
OK Now that I'm looking at this as an actual diff, I can  definitely imagine some problematic scnearios. First off, `get_layout_html` can accept a `Document` directly, in which case that passed-in document's theme should be used, not whatever `cursate().document` might happen to be.

Also noting that the codebase error is because `curstate()` is currently untyped. If we go down this road then type annotations will need to be added  to `state.py`

Also for ref, here is the changes that happened around themes for 2.0 release: https://github.com/bokeh/bokeh/pull/9729 I will have to go back and study that a bit in detail to recall all the considerations.

**Comment by jeremy9959** [comment]
I'll have to go back and remember what's happening, but this sounds like the whole "state" issue rearing its head again as @bryevdv says.

**Comment by HolleJ** [comment]
Thanks for the feedback. The codebase error should now be fixed. 

Regarding the other problem: Did I get it right, that it is more an higher-order problem and a simple case distinction is not the way to go?
```python
        if isinstance(obj, Document):
            theme = obj.theme
        else:
            theme = curstate().document.theme
```
I further checked how save() behaves and if save is called using a Document, it uses the curdoc() theme - and not the one in the document.

**Comment by bryevdv** [comment]
@HolleJ a condition there will probably fix the local problem, but I guess I'd regard it as a bandaid. I'm worried somewhat about unintended consequences, but even more that we've already kicked the can down the road for a while with regards to theme problems. My concern is that adding local fixes everywhere just makes things that much more complicated to fix "for real" and incentivizes putting off a comprehensive solution even more, a vicious cycle...

I don't know how interested you are are in becoming involved, but if you are interested, the absolute best first step to start would be for someone to do as complete a census as possible. Take a single simple themed example plot, and run it through all the different APIs to see what cases are actually broken. These examples could also then form the basis of tests later to comprehensively keep theming under test. 

> I further checked how save() behaves and if save is called using a Document, it uses the curdoc() theme 

Offhand, that seems like a mistake, then

Also wondering if this is a duplicate of https://github.com/bokeh/bokeh/issues/10268

**Comment by bryevdv** [comment]
Actually I guess step zero would be to just try and enumerate what all the cases are, he's a first stab at that

#### Accept a model or a document
* `export_png` 
* `export_svg` 
* `export_svgs`
* `get_screenshot_as_png`
* `autoload_static`


#### accept a model or a document and also optionally an explicit theme
* `components`(also directly accepts a theme)
* `file_html` (also directly accepts a theme)
* `json_item` 

#### only accepts a model
* `save`
* `show` (file and notebook output)

#### server related
* `server_document`
* `server_session`

Maybe it would be good to start a Wiki page around this? I you are interested we could collaborate there around compiling results.  Another good thing to document better is what functions rely on or are implemented in terms of other functions. I used to know all that but it's been a long time and some things have changed. I expect there are redundant code paths at this point.

**Comment by HolleJ** [comment]
@bryevdv Thanks for the detailed starting points. But unfortunately I'm currently busy with lots of other work. Therefore I don't think that I will be able to take such a deep dive into Bokeh until April.

**Comment by bryevdv** [comment]
OK, I am going to go ahead and close this and try to consolidate the existing theme issues so that this can be tackled more systematically

**Pull request closed without merging**
