### PR TITLE
Addresses #7937 Add support for ajax data source in TableWidget

### LINKED ISSUE #7937: Add support in TableWidget for AjaxDataSource
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 0.12.16, python 3.6.5, linux, chrome

#### Description of expected behavior and the observed behavior
plugging source=AjaxDataSource... in DataTable does not populate the table with query result

#### Complete, minimal, self-contained example code that reproduces the issue
In [ajax_source.py](https://github.com/bokeh/bokeh/blob/master/examples/howto/ajax_source.py) replace lines 15-20 and 27 with creating table 
```
from bokeh.models.widgets import DataTable, TableColumn
colx = TableColumn(field="x", title="x")
coly = TableColumn(field="y", title="y")
table = DataTable(source=source, columns=[colx, coly])

#line 27
show(table)
```
Here is the full code in a [gist](https://gist.github.com/2torus/36605e7c2e7a6ef672e4b345ad2c88d7)

#### Screenshots or screencasts of the bug in action
No data:
image

### PR DESCRIPTION
**Pull request by 2torus**
Invokes source.setup() if the source has such a method, similar to [GlyphRenderer.ts#106](https://github.com/bokeh/bokeh/blob/965989c1335d64ea9742560c15feabfe72f6c1d9/bokehjs/src/lib/models/renderers/glyph_renderer.ts#L106)

issues: fixes #7937

### CODE REVIEW

**Comment by bryevdv** [comment]
@2torus I believe you should be acting on `this.source`(which there should always be) and not `this.view.source` otherwise this won't work if a view is not defined.

**Comment by bryevdv** [comment]
@2torus do you think you can try the idea suggested by @mattpap above?

**Comment by 2torus** [comment]
@bryevdv @mattpap I created setup as an abstract method of RemoteDataSource. My thought is that anybody who wants to RemoteDataSource must implement setup().

**Comment by bryevdv** [comment]
thanks @2torus !

**Pull request merged**
