### PR TITLE
Add test matrix script

### LINKED ISSUE #1739: Create Test Matrix script
Something to automate several parts of the test matrix and speed the process up before each release.

### PR DESCRIPTION
**Pull request by Maggie-M**
issues: closes #1739

### CODE REVIEW

**Comment by bryevdv** [comment]
This is really great! A few ideas for enhancements:
* [ ] --keep-envs (don't delete them at the end)
* [ ] option to skip pip or skip conda
* [ ] a --dry-run option that shows for each env all the commands that will be run (but doesn't actually run them)
* [ ] output options. By default, print a human readable table, with` --json` flag, output the JSON data it does now
* [ ] option to suppress console output from all the commands

**Comment by damianavila** [comment]
>Bigger feature would be to update gdoc spreadsheet automatically but that may be a pain.

Probably a pain... and you have to deal with multi-user input...

Btw, one more thing to add... it support anaconda/envs... but I am a miniconda user :wink: I would be nice to take into account miniconda installations too...

**Comment by Maggie-M** [comment]
Thanks for the suggestion, Damian!  I've made a commit that I think fixes this, but I've never worked with miniconda before.

**Comment by damianavila** [comment]
>Thanks for the suggestion, Damian! I've made a commit that I think fixes this, but I've never worked with miniconda before.

Well, I guess I will be your guinea pig... je... thanks for adding this... I will let you know any problem after some testing.

**Comment by damianavila** [comment]
I did not have time to test it... I will do it tomorrow... btw, I restarted a sporious failure in TravisCI

**Comment by bryevdv** [comment]
I'm going to go ahead and merge this, more improvements can go in follow-on PRs.

**Pull request merged**
