### PR TITLE
Transform data with ColorMapper

### LINKED ISSUE #4981: Support a ColorMapper as a data transform
Support the following spelling so users don't have to manually transform data to colors.

```python
import numpy as np

from bokeh.io import show
from bokeh.models.sources import ColumnDataSource
from bokeh.model import LinearColorMapper
from bokeh.palettes import Viridis5
from bokeh.plotting import figure

p = figure(plot_width=500, plot_height=400, x_range=(0, 3), y_range=(0, 10))
x = np.random.random(2500) * 10
y = np.random.normal(size=2500) * 2 + 5

mapper = LinearColorMapper(palette=Viridis5)
source = ColumnDataSource(dict(x=x, y=y))

p.circle(x='x', y='y', fill_color={'field': 'x', 'transform': mapper}, source=source)

show(p)
```

(I would have thought there was an open issue for this but can't find it)

### PR DESCRIPTION
**Pull request by birdsarah**
- [x] issues: fixes #4981
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

```python
import numpy as np

from bokeh.io import show
from bokeh.models.sources import ColumnDataSource
from bokeh.models.mappers import LinearColorMapper, LogColorMapper
from bokeh.palettes import Viridis3
from bokeh.plotting import figure

x = np.random.random(2500) * 10
y = np.random.normal(size=2500) * 2 + 5
source = ColumnDataSource(dict(x=x, y1=y, y2=y - 10))

log_mapper = LogColorMapper(palette=Viridis3)
lin_mapper = LinearColorMapper(palette=Viridis3)

p = figure()
opts = dict(x='x', line_color=None, source=source)
p.circle(y='y1', fill_color={'field': 'x', 'transform': log_mapper}, legend="Log mapper", **opts)
p.triangle(y='y2', fill_color={'field': 'x', 'transform': lin_mapper}, legend="Lin mapper", **opts)

show(p)
```

bokeh_plot 1

### CODE REVIEW

**Comment by birdsarah** [comment]
When merged with @canavandl's colorbar work get:

bokeh_plot 2

```python
import numpy as np

from bokeh.io import show
from bokeh.models import ColumnDataSource, LinearColorMapper, ColorBar
from bokeh.palettes import Viridis3
from bokeh.plotting import figure

x = np.random.random(2500) * 100
y = np.random.normal(size=2500) * 2 + 5
source = ColumnDataSource(dict(x=x, y=y))

mapper = LinearColorMapper(palette=Viridis3, low=0, high=100)
color_bar = ColorBar(color_mapper=mapper, location=(0,0))

p = figure(toolbar_location='above')
opts = dict(x='x', line_color=None, source=source)
p.circle(y='y', fill_color={'field': 'x', 'transform': mapper}, **opts)
p.add_layout(color_bar, 'right')

show(p)
```

**Comment by birdsarah** [comment]
@bryevdv @mattpap: I am not convinced about the way I have modded DataSpec (https://github.com/bokeh/bokeh/pull/4983/commits/a1f1053e7ab978243c83fccc1ef69ca2f068df07). I would appreciate another pair of eyes.

Once I get feedback on that, I'll:
* add some tests
* update some of the examples that do manual color mapping to use this new technique (e.g. chloropleth maps)

**Comment by birdsarah** [comment]
Do we just expect this to work with server - or should i check it with new data being added - say in a streaming data source.

**Comment by bryevdv** [comment]
I expect it to work (or else updating any data wouldn't work too) but a check would be reassuring.

**Comment by canavandl** [comment]
LGTM - it's surprisingly straightforward.

**Pull request merged**
