### PR TITLE
Add templating with components to spectrogram

### PR DESCRIPTION
**Pull request by birdsarah**

### CODE REVIEW

**Comment by bryevdv** [comment]
Wow something odd going on with GH history/diff for this PR. Did you not want to just make changes directly to #2434 ? I left it open so everything could go in one PR, but if you want to work in a new PR I will just go ahead and merge #2434 now.

**Comment by bryevdv** [comment]
Tho if you do want to work in a separate PR we should figure out why GH is vomiting months of commits into this one (or make a new one fresh).

**Comment by birdsarah** [comment]
yes - that's super weird.

at the moment i'm all setup working from birdsarah. maybe it would be easiest to merge #2434 and then I can submit a new PR with the templating?

**Comment by bryevdv** [comment]
I'll merge it now.

**Comment by bryevdv** [comment]
Done. Note https://github.com/bokeh/bokeh/issues/2433 is still open (close then the new PR is completed)

**Comment by birdsarah** [comment]
#2433 is closed?

**Comment by birdsarah** [comment]
I re-opened it.

**Comment by bryevdv** [comment]
The other PR auto-closed it because I had "closes: #xxxx" in the description and forgot to remove it

**Pull request closed without merging**
