### PR TITLE
Fix updating of MultiChoice widget

### LINKED ISSUE #9927: [BUG] MultiChoice displayed value is not updating
Bokeh Version: 2.0.1

I want to load the selections into MultiChoice programmatically, but the widget UI doesn't update.
I'm sure the MultiChoice value is set correctly, and the on_change('value') event is triggered as expected.

Example
```
import random

from bokeh.io import curdoc
from bokeh.layouts import column
from bokeh.models import MultiChoice, Button, Paragraph

options = [str(i) for i in range(1, 10)]
multi_choice = MultiChoice(options=options)

load_random_choices_button = Button(label='Load From the external resource')
debug_paragraph = Paragraph()

def on_load_choices():
    choices = random.sample(options, k=3)
    multi_choice.value = choices
    debug_paragraph.text = ', '.join(choices)

load_random_choices_button.on_click(on_load_choices)

widgets = column([multi_choice, load_random_choices_button, debug_paragraph])
curdoc().add_root(widgets)
```

### PR DESCRIPTION
**Pull request by mattpap**
fixes #9927

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap what is left on this PR?

**Comment by bryevdv** [comment]
👍 have moved to `next`

**Comment by bryevdv** [comment]
As long as this is being fixed the widget should be added to the docs here (it is missing):

https://docs.bokeh.org/en/dev/docs/user_guide/interaction/widgets.html

**Comment by ItamarShDev** [comment]
@mattpap if any help is needed, i will be happy to give it a try


can you share your current view and understanding of the issue?

**Comment by bryevdv** [comment]
@mattpap I rebased this on `branch-2.2` and the example from the issue is working for me on OSX/safari can you be more specific about what "this PR doesn't work" means?

**Comment by ItamarShDev** [comment]
Any chance of merging it?

**Comment by fischja** [comment]
Would be awesome to have this merged guys!

**Comment by philippjfr** [comment]
+1 would love to see this in 2.2.

**Comment by bryevdv** [comment]
cc @mattpap  can you elaborate on the issues remaining?

**Comment by mattpap** [comment]
I will try to get this finished later today.

**Comment by bryevdv** [comment]
@mattpap is this still `wip` after the latest commit?

**Comment by mattpap** [comment]
Yes, I'm still working on this.

**Comment by mattpap** [comment]
Updating should work. I also improved interaction with layout. Still not great though.

**Comment by bryevdv** [comment]
> Still not great though. 

OK, please just make any follow on issues as necessary and this will still be a really good improvement for 2.2

**Pull request merged**
