### PR TITLE
Use <div> instead of <button> for tool buttons

### LINKED ISSUE #5661: tool labels appears empty on hover
On the [development version of the docs](http://bokeh.pydata.org/en/dev/docs/gallery/stocks.html) when you hover over a tool the tool label shows up as blank:

screen shot 2017-01-06 at 10 52 09 am

In the [latest release](http://bokeh.pydata.org/en/latest/docs/gallery/stocks.html) this does not seem to occur:

screen shot 2017-01-06 at 10 52 19 am

### PR DESCRIPTION
**Pull request by mattpap**
fixes #5661

### CODE REVIEW

**Comment by bryevdv** [comment]
LGTM, tested locally. Will merge when green so this can go in to `0.12.4`. Thanks @jsignell for identifying the root cause.

**Comment by bryevdv** [comment]
@mattpap it looks like some of the selenium tests will need minor updates, e.g.:

```
        pan_buttons = selenium.find_elements_by_css_selector('.bk-button-bar-list[type="pan"] button')
>       pan_button = pan_buttons[0]
E       IndexError: list index out of range
```
Let me know if I can help with this.

**Comment by mattpap** [comment]
One of integration test images needs to be updated. Issue #5670 doesn't help with that.

**Comment by bryevdv** [comment]
@mattpap are you asking for help with that? Would it be possible to match the old styling instead?

**Comment by bryevdv** [comment]
ping @canavandl who knows where/how to update the images I believe

**Comment by bryevdv** [comment]
Update on this? this is the only other PR besides the docs one waiting to merge for release. We can also: 

* disable the test temporarily
* remove the feature altogether for now

**Comment by canavandl** [comment]
I'll look at it now.

**Comment by mattpap** [comment]
I'm not sure if this a new GitHub's feature, but there is a nice image diff available.

**Comment by mattpap** [comment]
> Would it be possible to match the old styling instead?

The old styling was actually wrong, because button border wasn't maintained between between highlight and normal modes. However, the issue was that the failing test shouldn't have the toolbar visible in the first place.

**Comment by mattpap** [comment]
@canavandl, thanks. @bryevdv, this is ready.

**Pull request merged**
