### PR TITLE
upadated rgb values in color_scatter.py

### PR DESCRIPTION
**Pull request by KesharwaniArpita**

### CODE REVIEW

**Comment by bryevdv** [comment]
@KesharwaniArpita can you post before/after screenshots of how the plot looks with this change? I am not sure we are going to want to change this particular example, as it is just random data and the scatter quality is evident regardless, also this plot as it is now has been used in various promotional materials for the project. But if we are going to update it, then we should probably ditch the random RGB generation altogether since there is no way to guarantee that fully accessible color combinations emerge from a random process. Instead we could generate random numbers, and colormap those random numbers from one of the accessible palettes.

**Comment by KesharwaniArpita** [comment]
The main change is reversal of the colours :
After:
image
Before:
image

**Comment by bryevdv** [comment]
Right, I am not sure that is a distinct improvement, in terms of accessibility specifically. It's still dominated by large red-ish and green-ish regions that look similar under some common color deficiencies. I would say options are:

* leave this plot at the status quo, i.e. no changes for now, and pick a different plot to update (plots with colors for different categorical values are probably good to look at for their palette selection)
* go further, and change the structure of the example to geneate random *numbers* rather than colors, then use one of the built-in accessible colormaps on the numbers (that includes some MPL palettes, viridis, etc)

**Comment by KesharwaniArpita** [comment]
Sure @bryevdv , I'll look to that.

**Comment by bryevdv** [comment]
I am going to go ahead and close this PR @KesharwaniArpita if you still want to work on this example *specifically*, let's please discuss on Slack chat, otherwise there are still many examples that an be updated (examples that have a few categorical colors are often a good choice to look at)

**Pull request closed without merging**
