### PR TITLE
clean up notebooks examples

### LINKED ISSUE #3583: remove some example notebooks that are superfluous
Notebooks in the main repo examples dir should:
* illustrate something in particular about Bokeh+Notebook, or
* be discursive / tutorial-like 

Notebooks that simply duplicate existing script examples in a notebook are a burden to testing and maintenance and should be removed.

### PR DESCRIPTION
**Pull request by bryevdv**
issues: closes #3583

### CODE REVIEW

**Comment by bryevdv** [comment]
So far this PR removes all the `compat` notebooks, which were superfluous. This will also allow testing *all* of the compat very quickly with the interactive tester, e.g. Here are the remaining notebooks in `examples`:
```
./charts/notebook/bar.ipynb
./charts/notebook/boxplot.ipynb
./charts/notebook/donut.ipynb
./charts/notebook/dots.ipynb
./charts/notebook/excel.ipynb
./charts/notebook/heatmap.ipynb
./charts/notebook/histograms.ipynb
./charts/notebook/horizon.ipynb
./charts/notebook/lines.ipynb
./charts/notebook/palettes.ipynb
./charts/notebook/scatter.ipynb
./charts/notebook/steps.ipynb
./charts/notebook/timeseries.ipynb
./glyphs/custom.ipynb
./glyphs/data_tables.ipynb
./glyphs/glyph.ipynb
./interactions/Hover callback.ipynb
./interactions/interactive_bubble/gapminder.ipynb
./interactions/Linked panning.ipynb
./interactions/Notebook comms basic.ipynb
./interactions/Notebook comms continuous updates.ipynb
./interactions/Range update callback.ipynb
./interactions/us_marriages_divorces/us_marriages_divorces_interactive.ipynb
./plotting/notebook/bollinger.ipynb
./plotting/notebook/boxplot.ipynb
./plotting/notebook/brewer.ipynb
./plotting/notebook/burtin.ipynb
./plotting/notebook/candlestick.ipynb
./plotting/notebook/color_scatterplot.ipynb
./plotting/notebook/correlation.ipynb
./plotting/notebook/glyphs.ipynb
./plotting/notebook/interact_basic.ipynb
./plotting/notebook/interact_numba.ipynb
./plotting/notebook/linked_brushing.ipynb
./plotting/notebook/linked_panning.ipynb
./plotting/notebook/lorenz.ipynb
./plotting/notebook/rect.ipynb
./plotting/notebook/scatter.ipynb
./plotting/notebook/stocks.ipynb
./plotting/notebook/texas.ipynb
./plotting/notebook/vector.ipynb
```

**Comment by bryevdv** [comment]
I'd like to propose this: 
* move `plotting/notebook/interact*` to `examples/interactions`
* remove most of the others in `plotting/notebook`
* remove all notebooks in `examples/glyphs` except possibly `glyph.ipynb`
* remove most of the `charts` notebooks, move ones that are "tutorial-like" to `bokeh-notebooks` repo

@bokeh/core thoughts?

**Comment by bryevdv** [comment]
We obviously need to have notebook code to test our continued support for notebook functionality, but I would argue that these types of notebooks should be moved out of examples (because they are not very good examples) and into a place where boring but important-to-test purpose-built test scripts and notebooks are collected.

**Comment by birdsarah** [comment]
> need to have notebook code to test our continued support for notebook functionality, but I would argue that these types of notebooks should be moved out of examples

+ 1 

> a place where boring but important-to-test purpose-built test scripts and notebooks are collected

I would say that's the integration tests folder(s)

**Comment by rothnic** [comment]
What is considered an example vs a tutorial? I guess I considered a tutorial to be a step by step build-up, while an example being one or many discrete examples of using the API. See [ggplot's documentation](http://docs.ggplot2.org/0.9.3.1/geom_bar.html) for reference.

I found when creating the charts notebooks that you naturally put together something that is probably more useful to the type of person that would reference it because you have a better medium for explanations to go with the examples. I then had to take those changes I realized and apply them to the scripts to be consistent.

Whether the notebooks are removed or not, there still would be duplicated code. Ideally, the examples would be produced in either a script or a notebook and could be converted to either. With using the scripts, you end up losing the experience I had, where I think it helped produce better examples. With the notebooks, you are tied to the notebooks, unless it is converted to a script.

Another note is that there are sphinx extensions that extract the python code for either the entire notebook or the cells that you specify, so I could see a bokeh sphinx extension could do something similar if we wanted to avoid the duplicated code issue.

**Comment by bryevdv** [comment]
@rothnic grid questions, first  here is what I think are the things that are definitely showing some special "Bokeh+notebook" things:
* need a few just to demonstrate `output_notebook` at all
* notebook comms
* bokeh + ipython interactors
* notebook + bokeh server

Things that could would probably make sense (to me) as more in-depth expositions (i.e. with explanatory text in the cells throughout):

* interactions (linked panning, brushing)
* hover tools how-to

The thing is, almost everything above could reasonably go in `examples\interactions` which is why I'd like to consolidate most notebooks there. 

And then we have more in-depth longer form tutorials or notebooks that develop sophisticated examples. I guess my initial feeling is that most of these could go into `bokeh-notebooks`. The charts I will grant is more of a grey are. The duplication I first thinking go is say, `plotting/notebook/rec.ipynb` where nothing is gained by having a notebook version of `rect.py`.

**Comment by damianavila** [comment]
@bokeh/core thoughts?

:+1: on the idea...

> The thing is, almost everything above could reasonably go in examples\interactions which is why I'd like to consolidate most notebooks there.

:+1: as well...

And eventually, we need to do the same with server and files... we have to avoid duplication of "similar" code, I mean, if I plot a rect and then circle with the same code but consider those two different examples, we are playing with duplicate info... we should eentually clean the files and server examples to show "meaningful" things... there are a lot of good and different examples, but there are also duplication... in any case, this PR goes in the direction I like to see, so :+1:

**Comment by bryevdv** [comment]
@damianavila agreed but `plotting/server` has already been cleaned? There's no more dupes of `plotting/file` in there only things that actually demonstrate something specifically related to the server (and that's what I am driving for for notebook examples too). 

Actually maybe that sums up my feelings on a split:

* notebooks that demo something special about notebooks wrt bokeh go in the main repo
* notebooks that demo something about bokeh (but not necessarily notebooks) go in `bokeh-notebooks`

**Comment by damianavila** [comment]
> @damianavila agreed but plotting/server has already been cleaned? There's no more dupes of plotting/file in there only things that actually demonstrate something specifically related to the server (and that's what I am driving for for notebook examples too).

Yes, server was cleaned... I was referring mainly to files (mentioned server just thinking in some previous times, but you are right, they were cleaned and I feel very good about that at "testing the matrix" time), although I still see some "conceptual" duplication in files... but we are far better than before...

>Actually maybe that sums up my feelings on a split:
>
>notebooks that demo something special about notebooks wrt bokeh go in the main repo
notebooks that demo something about bokeh (but not necessarily notebooks) go in bokeh-notebooks
with the caveat/exception that some smaller "conceptual" notebooks can go in examples/interactions as described above

I agree...

**Comment by fpliger** [comment]
+1 on the cleaning up and on trying to not repeat what we have on `file` also on `notebook`... 

I really like the idea of pushing more on having notebooks that cover what @bryevdv mentioned and add more "history telling" notebooks.. Maybe just leave 1 or 2 for pure "basic testing" purpose (like... glyphs?)

**Comment by bryevdv** [comment]
OK so for now I am just going to confine this PR to deleting ones that I think are clearly redundant, and make a BEP to discuss a broader examples/demos re-org, IA, strategy

**Comment by bryevdv** [comment]
New list, if this PR is accepted as-is:

```
./charts/notebook/bar.ipynb
./charts/notebook/boxplot.ipynb
./charts/notebook/donut.ipynb
./charts/notebook/dots.ipynb
./charts/notebook/excel.ipynb
./charts/notebook/heatmap.ipynb
./charts/notebook/histograms.ipynb
./charts/notebook/horizon.ipynb
./charts/notebook/lines.ipynb
./charts/notebook/palettes.ipynb
./charts/notebook/scatter.ipynb
./charts/notebook/steps.ipynb
./charts/notebook/timeseries.ipynb
./glyphs/glyph.ipynb
./interactions/Hover callback.ipynb
./interactions/interactive_bubble/gapminder.ipynb
./interactions/Linked panning.ipynb
./interactions/Notebook comms basic.ipynb
./interactions/Notebook comms continuous updates.ipynb
./interactions/Range update callback.ipynb
./interactions/us_marriages_divorces/us_marriages_divorces_interactive.ipynb
./plotting/notebook/color_scatterplot.ipynb
./plotting/notebook/glyphs.ipynb
./plotting/notebook/interact_basic.ipynb
./plotting/notebook/interact_numba.ipynb
./plotting/notebook/linked_brushing.ipynb
./plotting/notebook/linked_panning.ipynb
```

**Comment by bryevdv** [comment]
OK, I am going to merge this one as-is and leave the larger cleanup/re-org described in the wiki to a different PR.

**Pull request merged**
