### PR TITLE
docs: makes first steps box annotations example code and figure agree

### LINKED ISSUE #11730: [DOCS] Box Annotation figure and code snippet don't match
I've been working through the "first steps" material. In the [Using annotations](https://docs.bokeh.org/en/latest/docs/first_steps/first_steps_3.html#using-annotations) section of First Steps 3, there is a mis-match between the 'Box annotation example' figure and the step by step code snippet. The full finished code section matches the figure, but not the earlier snippet.

The code snippet sets `BoxAnnotation` arguments suggesting a mid-box between 80 and 180. The figure and final code have a mid-box between 20 and 80.

Suggested solution: update the step by step code snippet to reflect the image and final code.

To the maintainers: I'd be delighted to make this contribution myself if you agree it's appropriate/desirable.

### PR DESCRIPTION
**Pull request by danoscarmike**
Reconciles code snippets with final code and figure (and improves color contrast for accessibility):
- https://docs.bokeh.org/en/latest/docs/first_steps/first_steps_3.html#using-annotations

Additionally improves color contrast for accessibility in the following places:
- https://docs.bokeh.org/en/latest/docs/user_guide/annotations.html#box-annotations
- https://docs.bokeh.org/en/latest/docs/user_guide/styling.html#visible-property (2nd example)
- https://docs.bokeh.org/en/latest/docs/user_guide/annotations.html#spans

Used this [color grid](https://contrast-grid.eightshapes.com/?version=1.1.0&background-colors=&foreground-colors=%23FFFFFF%0D%0A%23008000%0D%0A%23FFFF00%0D%0A%230000FF%0D%0A%23FFdF00&es-color-form__tile-size=compact&es-color-form__show-contrast=aaa&es-color-form__show-contrast=aa&es-color-form__show-contrast=aa18) to assess contrast, as recommended by [accessibility.digital.gov](https://accessibility.digital.gov/visual-design/color-and-contrast/)

fixes #11730 addresses #10974

### CODE REVIEW

**Comment by bryevdv** [comment]
cc @tcmetzger I don't mind closing #10974 with this since it was marked GFI and circumscribed, but sometime soon we should get together and make and/or collect accessibility related issues more broadly

**Comment by danoscarmike** [comment]
@bryevdv these are great resources. Thank you for sharing. I'll select some combinations from there, adjust the alphas and push some changes here in a bit.

**Comment by danoscarmike** [comment]
Sure thing...
Screen Shot 2021-10-11 at 11 26 29 AM
Screen Shot 2021-10-11 at 11 27 05 AM
Screen Shot 2021-10-11 at 11 27 22 AM

**Comment by bryevdv** [comment]
LGTM @tcmetzger any final thoughts or comments?

**Pull request merged**
