### PR TITLE
bugfix: w_units, h_units support for ImageURL glyph

### LINKED ISSUE #4984: h_units="screen" and w_units="screen" not respected in ImageURL
The following code aims to place an image in a bokeh plot by specifying its location and size in "screen" units. But it seems to use "data" units instead and rescales with zoom (which is not what I want).

```
import numpy as np
from bokeh.models import ColumnDataSource, Range1d
from bokeh.models.widgets import Panel, Tabs
from bokeh.models.glyphs import ImageURL
from bokeh.plotting import figure, show, output_file

N = 1000

x = np.linspace(0, 10, N)
y = np.sin(x) * np.exp(-x/5)

url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Olympic_rings_without_rims.svg/220px-Olympic_rings_without_rims.svg.png'

def add_bkgimage(p):
    """Add a bkgimage to Bokeh plot p."""

    img_source = ColumnDataSource(
            dict(url=[url],
            x=[0], y=[0], w=[200], h=[100])
    )
    bkgimage = ImageURL(url="url", x="x", y="y", anchor="bottom_left",
                         global_alpha=0.2, w="w", h="h",
                         w_units="screen", h_units="screen")
    p.add_glyph(img_source, bkgimage)


p = figure(x_range=[5, 10], y_range=[-1, 1], x_axis_type='log')
p.line(x, y)
add_bkgimage(p)

show(p)  # open a browser

```

### PR DESCRIPTION
**Pull request by canavandl**
- [x] issues: fixes #4984 
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

Refactor ImageURl.Model 's w, h attributes to be DistanceSpecs (not NumberSpec), to match Bokeh model. Also implement support for data/screen units.

### CODE REVIEW

**Comment by canavandl** [comment]
ping @xnx for review

example code:

```python
import numpy as np
from bokeh.models import ColumnDataSource, Range1d
from bokeh.models.widgets import Panel, Tabs
from bokeh.models.glyphs import ImageURL
from bokeh.plotting import figure, show, output_file

N = 1000

x = np.linspace(0, 10, N)
y = np.sin(x) * np.exp(-x/5)

url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Olympic_rings_without_rims.svg/220px-Olympic_rings_without_rims.svg.png'

def add_bkgimage(p):
    """Add a bkgimage to Bokeh plot p."""

    img_source = ColumnDataSource(
            dict(url=[url],
            x=[0], y=[0],
            w=[200], h=[100],
            )
    )
    bkgimage = ImageURL(url="url", x="x", y="y", anchor='bottom_left',
                        global_alpha=0.2, w="w", h="h",
                        w_units="screen", h_units="screen"
                         )
    p.add_glyph(img_source, bkgimage)


p = figure(x_range=(0,10), y_range=(-2,2))
p.line(x, y)
add_bkgimage(p)

output_file('image.html')

show(p)  # open a browser
```

**Comment by canavandl** [comment]
example output:

screen shot 2016-08-22 at 11 12 50 am

**Comment by canavandl** [comment]
from @xnx in #4988 

>Dear Luke,
That's brilliant, thank you so much: I couldn't have fixed that myself, but
now it does just what I want.
Your PR build seems to have stalled with some unrelated network problem but
I expect it will go just fine.
Thanks again,
Christian

**Comment by birdsarah** [comment]
Tests? Just some simple ones for the little bits you've added?

@bryevdv - should we think about extending the properties checker to check that the property types match?

**Comment by bryevdv** [comment]
@birdsarah possibly but first we need to make all the property types match more, we use `p.Any` and `p.String` fairly often on the BokehJS side when there is no matching property type for the one on the python side.

**Pull request merged**
