### PR TITLE
Test out codecov action

### PR DESCRIPTION
**Pull request by bryevdv**
cc @bokeh/core This PR adds support for the GH codecov upload action and applies it to the Python unit and integration tests. You can see our repo reports at

https://app.codecov.io/gh/bokeh/bokeh

Additionally, codecov can add a comment to the top of PRs (AFAICT it adds a single comment and updates that as needed). There are plenty of options we can play with, but I am inclined to merge this PR as-is to see how it perfoms and then we can consider what if any tweaks we want to make. 

FYI @mattpap codecov can accept and merge reports for multiple languages, so we could potentially generate BokehJS coverage reports as well in the future.

### CODE REVIEW

**Comment by mattpap** [comment]
Are those auto-generated comments going to be added to every PR and spam notifications as well? I'm guessing so, at least based on my experience with panel development. If that's the case then I'm absolutely against this change. I'm fine with some form of coverage reports, as long as they are not that verbose and annoying. I'm generally against anything that spams PRs for no good reason.

**Comment by bryevdv** [comment]
> . If that's the case then I'm absolutely against this change. I'm fine with some form of coverage reports, as long as they are not that verbose and annoying

@mattpap It posts a single comment, and updates that comment. It does not post multiple comments. I have also not received any extra notifs on this PR. I am 100% OK with a single comment in PRs. That is not spam, that is information I want to see without having to dig through test logs (also individual test logs are not merged like this is).

**Comment by bryevdv** [comment]
@mattpap the contents and layout of the comments can be configured:

https://docs.codecov.com/docs/pull-request-comments

I'm fine with the comment above, but I am happy to consider any configuration change suggestions (but the onus is on you if you are the one who does not like the format above) *except* for `require_changes: true` I want one comment per PR, consistently.

**Comment by bryevdv** [comment]
I'll plan to merge this Monday AM PST unless there is further detailed comment

**Comment by bryevdv** [comment]
And actually I have reconsidered `require_changes: true` I am willing to consider it, but I want to see how things go without it for at least a short time. So I will merge this tomorrow as-is and we can tweak the configuration as needed in the next few weeks based on actual experience with the default.

**Comment by mattpap** [comment]
As I said, I'm generally against any automated PR comments of this kind, whether this is codecov, LGTM, etc., especially when they are as verbose as this. If this can be configured, great, but any tweaking needs to be done in this PR. But even then, it's still an annoyance, based on my experience with other projects that use this the way it's configured right now. Perhaps there's a [better way](https://docs.codecov.com/docs/commit-status), which seems to me to be the way it should be done, perhaps coupled with a hard failure mode. I'm not sure, but it would be worthwhile to explore such options before merging.

To me, code coverage is a pretty weak metric. Yes, it's useful to have higher coverage than lower. However, even 100% coverage doesn't mean that a project is any good. It usually helps with infrequent code paths, like exception handling, but good static typing can be more useful there. So perhaps we should enable static type coverage instead or as well? If this is meant to encourage people to write more tests, then there should be a threshold set for how much coverage can degrade and tests should fail if such degradation happens. Otherwise this will be tuned out as anything else is, that doesn't have a hard failure mode (e.g. examples' report or existing coverage reports).

**Comment by bryevdv** [comment]
> any tweaking needs to be done in this PR 

We literally need a baseline established first (i.e. a PR needs to be merged) in order to effectively experiment withe some of the options and  configurations. Considering this, considering that the tool only ever  makes a single comment in a PR (the opposite of spammy), and given that you have control over your own notifications, I think the demand above is unreasonable.

I'd like to ask you to reconsider. I'll wait until noon PST to either, and then I will either

* merge this PR with your 👍 in order to evaluate and improve over the next week
* write up my full position and open a discussion poll for a formal decision

**Pull request merged**
