### PR TITLE
Redesign text rendering in text annotations

### LINKED ISSUE #7317: Add support for line breaks in Label
The code below does not render the \n as a new line (Bokeh 0.12.13)

```python
from bokeh.plotting import figure, output_file, show
from bokeh.models import  Label

output_file("test.html")
fig = figure()
fig.line(x=range(10), y=range(10))
label = Label(x=2, y=8, text="New\nLine")
fig.add_layout(label)
show(fig)
```
A similar issue (#994) was solved by #6879.

### PR DESCRIPTION
**Pull request by mattpap**
image

fixes #7317

### CODE REVIEW

**Comment by bryevdv** [comment]
This is terrific. But closing a years old, long-asked for issue needs  a mention in the release notes. It also needs documentation support, an example, and consideration for the blog announcement. You don't necessarily have to do all that, that's the benefit of growing a team. But we can all help each other by communicating. Immediately opening a  follow-up issue will help others be aware of these things, and prioritize.

**Comment by bryevdv** [comment]
@mattpap how is this new functionality accessed? I tried changing 
```
meters_back = Label(..., text="Meters behind\n2012 Bolt", ...)
```
in `sprint.py` but am not seeing a multil-ine label.

**Comment by mattpap** [comment]
This is how is should work and it works:
image

**Comment by bryevdv** [comment]
Yep, local env issue, sorry for the noise. I will update some examples in a new PR shortly.

**Pull request merged**
