### PR TITLE
try forcing inline resources for notebooks

### PR DESCRIPTION
**Pull request by bryevdv**
Just a test

### CODE REVIEW

**Comment by bryevdv** [comment]
@damianavila @mattpap this seems to fix the problem (tests still running but notebooks appear to be passing now). Is this the right solution? FWIW I can't run notebooks at all with "relative" resources, it tries to load resources from a relative URL unsurprisingly.

**Comment by damianavila** [comment]
LGTM as a temporary patch... we need to explore the problem further...

**Comment by bryevdv** [comment]
OK, tests pass and report looks good (modulo known issues). Merging as a hotfix.

**Comment by mattpap** [comment]
Apparently this is the right workaround, because everything else is either broken or sometimes works by coincidence (`relative` resources can be made usable).

**Pull request merged**
