### PR TITLE
Fix #9562

### LINKED ISSUE #9562: [BUG] Impossible to create a custom model while extending and existing one and using JavaScript
```python
from bokeh.models import Expression
from bokeh.util.compiler import JavaScript


class MyExpression(Expression):
    # language=JavaScript
    __implementation__ = JavaScript("""
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    const {Expression} = require("models/expressions/expression");
    
    class MyExpression extends Expression {
        static __name__ = 'MyExpression';
    }

    exports.MyExpression = MyExpression;
    """)
```

Using this custom model results in 
```
TypeError: Class constructor n cannot be invoked without 'new'
```

Root cause: incompatible compiler targets. `compile_typescript` uses the one that's specified in the `tsconfig.json` (ES2017 right now) but `compile_javascript` uses a hard-coded `ES5`.

### PR DESCRIPTION
**Pull request by p-himik**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes #9562
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@p-himik thanks for the PR, is there a test that could exercise this fix?

**Comment by p-himik** [comment]
Added a test. Checked that it fails before the main changes.

Hmm, seems like the `test_point_drag_syncs_to_server` can spuriously fail. Well, seems good now (writing this before the examples are checked - they have been checked before with no issues).

**Comment by bryevdv** [comment]
> Hmm, seems like the test_point_drag_syncs_to_server can spuriously fail.  

Yes until about a week ago the selenium tests were extremely flaky and now there are merely slight so 🙄 A work in progress, always

**Comment by bryevdv** [comment]
And examples job got stuck. Have never seen that before.

**Comment by bryevdv** [comment]
@mattpap based on our convo at the weekly sync I'll merge this tomorrow unless there's further comment.

**Comment by mattpap** [comment]
Hopefully I will manage to remove the old compiler for 2.0, so that this code becomes irrelevant.

**Pull request merged**
