### PR TITLE
Add HoverTool Callback examples

### PR DESCRIPTION
**Pull request by birdsarah**
This should only be merged after @canavandl's #2386.

(I thought it was better to do a PR against master so that #2386 can be worked on separately and to not conflate the two).

### CODE REVIEW

**Comment by canavandl** [comment]
I built the docs (and example) locally and it looks good. Thanks for adding the examples/interaction file. The hover interaction is pretty laggy (ref issue: #2386), we can discuss a fix on the feature PR

**Comment by birdsarah** [comment]
I have merged in the fix from #2386 and updated the examples to use `tooltips=None`

**Comment by canavandl** [comment]
The performance concerns appear to be solved (I built the example locally). LGTM

**Comment by damianavila** [comment]
I fixed some of the sphinx warning, merging now...

**Comment by birdsarah** [comment]
Thanks so much @damianavila

**Pull request merged**
