### PR TITLE
Add support for setting the DataTable row height

### LINKED ISSUE #8411: Feature request: add support for setting the DataTable row height
The current implementation of `DataTable` does not allow the user to override the default row height (25px).  This has been requested a few times on in the google group ([here](https://groups.google.com/a/continuum.io/forum/#!searchin/bokeh/datatable$20row$20height|sort:date/bokeh/QLCbnzX1cFY/uWZUxDAEBAAJ) and [here](https://groups.google.com/a/continuum.io/forum/#!searchin/bokeh/datatable$20row$20height|sort:date/bokeh/ItFqOH3iRac/Pr2T58K2AgAJ)).  It doesn't seem to be solvable with custom CSS.  SlickGrid does expose `rowHeight` as a [grid option](https://github.com/6pac/SlickGrid/wiki/Grid-Options).

I'll make a PR to add this option.

### PR DESCRIPTION
**Pull request by dennisobrien**
This adds a parameter row_height to DataTable which defaults to 25 matching the current behavior.

- [ ] issues: fixes #8411
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

I have not added any tests for this since I'm not sure what to test.  I've seen the existing [integration tests for DataTable](https://github.com/bokeh/bokeh/blob/master/tests/integration/widgets/tables/test_data_table.py) but I'm not sure how to test this.  I'm open to suggestions on testing.

### CODE REVIEW

**Comment by dennisobrien** [comment]
Here's the code from the notebook I used to test this fix.

```python
# load bokehjs from locally built sources rather than the CDN
import os
os.environ['BOKEH_RESOURCES'] = 'inline'

from bokeh.io import output_notebook
output_notebook()

from bokeh.io import show
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, TableColumn, HTMLTemplateFormatter

from bokeh.sampledata.periodic_table import elements

elements['name_lower'] = elements['name'].str.lower()
source = ColumnDataSource(elements)

html_font_template = '<font color="<%= CPK %>"><%= value %></font>'
html_image_template = """
<a href="http://images-of-elements.com/<%= value %>.php" target="_blank">
  <img src="http://images-of-elements.com/<%= value %>.jpg" style="width:40px;height:40px;border:0">
</a>
"""
columns = [
    TableColumn(field='atomic number', title='Atomic Number'),
    TableColumn(field='symbol', title='Symbol'),
    TableColumn(field='name', title='Name', 
                formatter=HTMLTemplateFormatter(template=html_font_template)),
    TableColumn(field='name_lower', title='Image',
                formatter=HTMLTemplateFormatter(template=html_image_template))
]
data_table = DataTable(source=source, columns=columns, editable=False, row_height=45)

show(data_table)
```

And a screenshot of the datatable with row_height=45 (instead of the default 25).
image

**Comment by mattpap** [comment]
@dennisobrien, can you add this example as a static integration test under `examples/integration/widgets`, let's call it `data_table_customization.py`. You will have to make a few changes, remove the `os` and `notebook` related code, and replace `show()` with `save()`. You can take any example from that directory as a template.

**Comment by dennisobrien** [comment]
Thanks @mattpap -- I added the integration tests as you suggested. Let me know if you have any suggestions for changes to this example.

**Comment by jundl77** [comment]
@mattpap Is this going to be merged in at some point?

**Pull request merged**
