### PR TITLE
Exposed Range1d initial start/end properties

### PR DESCRIPTION
**Pull request by philippjfr**
This PR does two things, first of all it exposes the ``initial_start`` and ``initial_end`` attributes as properties on the ``Range1d`` model. Secondly it ensures that tile sources override these properties since they sometimes adjust the initial ranges on initialization to enforce the correct aspect ratio.

Setting the initial ranges is generally useful since you often want to toggle between different views and currently the reset tool is not very useful in these scenarios. The remaining question is whether to expose these properties on the ``DataRange1d`` model as well, I'm leaning towards not exposing them but I'm not entirely sure.

- [x] issues: fixes https://github.com/bokeh/bokeh/issues/6320 and https://github.com/bokeh/bokeh/issues/7936
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
They should be called `reset_start` in order to avoid confusion. For users, `initial_start` sounds like something that makes something happen when the plot is first rendered. What about my other concerns in https://github.com/bokeh/bokeh/pull/6321 ? How does this interact with bounds, following, or data ranges?

**Comment by philippjfr** [comment]
>They should be called reset_start in order to avoid confusion.

Sounds good.

>How does this interact with bounds, following, or data ranges?

I assume they would have to be validated against the bounds, I'll make sure to add that. There is currently no interaction with following or data ranges since this is currently not implemented for ``DataRange1d``, would be happy to add that if you think it's a good idea though. I'm not entirely sure what the correct behavior would be though, I would guess it should update the values for both ``following`` and ``data_range`` options.

**Comment by bryevdv** [comment]
Let's leave it off data ranges for now

**Comment by philippjfr** [comment]
>Let's leave it off data ranges for now

To be clear, do you mean for me to implement it for ``DataRange1d`` but not update the ``reset_start`` and ``reset_end`` on data_range changes or do you mean that we shouldn't implement it for ``DataRange1d`` at all for now?

**Comment by bryevdv** [comment]
Don't implement anything for data ranges

**Comment by philippjfr** [comment]
I think there is no special handling needed for the ``bounds``, as far as I could tell the ranges ``start`` and ``end`` values are only clipped on the plot canvas so the clipping would still apply.

**Comment by bryevdv** [comment]
> I think there is no special handling needed for the bounds, as far as I could tell the ranges start and end values are only clipped on the plot canvas so the clipping would still apply.

Fair enough, I was thinking that might be confusing to people but if thats already the precedent we should just go with that. It might do to make an explicit note of that in the properties help strings.

I think this change is also amenable to some unit JS unit tests.

**Comment by philippjfr** [comment]
I've added a very simple unit test. I was hoping to add more, e.g. for the tile source update to the range, but I'm having quite some trouble setting that test up, because I have to create a plot, plot view, plot canvas, some ranges and more to even set it up. I also noticed that very few tests do that kind of thing. Would it make sense to have some testing utilities which create a fully configured plot instance for you?

**Comment by bryevdv** [comment]
> Would it make sense to have some testing utilities which create a fully configured plot instance for you?

Probably, and it's probably partly done in various places. We don't have to do that here, my main interest now was in testing `Range1d` which can be accomplished easily. It's maybe worth adding another test that makes sure that changes to those properties after init also have the desired effect. 

For the general issue what we should really do is factor out "view models" so that views that require lots of logic or state can be tested more thoroughly by testing the view model (which would be creatable and testable in isolation without a ton of scaffolding)

**Comment by philippjfr** [comment]
>For the general issue what we should really do is factor out "view models" so that views that require lots of logic or state can be tested more thoroughly by testing the view model (which would be creatable and testable in isolation without a ton of scaffolding)

This sounds great, although it seems quite difficult. Definitely would make a difference though, I just couldn't figure setting up the views correctly at all.

>It's maybe worth adding another test that makes sure that changes to those properties after init also have the desired effect.

Will do.

**Comment by bryevdv** [comment]
> This sounds great, although it seems quite difficult. Definitely would make a difference though, I just couldn't figure setting up the views correctly at all.

I expect it's mostly just a large amount of work as opposed to being difficult work, in and of itself. But really it's something we have to get to at some point, BokehJS is not nearly well tested enough

**Pull request merged**
