### PR TITLE
Fix rendering of legends for ellipse glyph

### LINKED ISSUE #11367: [BUG] Ellipse glyph does not render properly in figure legend
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
* Bokeh version 2.3.2
* Python version 3.9.4
* Chromium version 90.0.4430.72 (Brave browser)

#### Description of expected behavior and the observed behavior
* Expected: Legend shows ellipse glyph next to label, plot tool menu and figure interactivity the same as if the circle glyph was used instead.
* Observed: Ellipse is missing from legend, tool menu is missing, and interacting with the figure does some weird zooming/overwriting thing.

Additional discussion on Discourse [here](https://discourse.bokeh.org/t/drawing-a-legend-with-an-ellipse-glyph-errors/8019).

#### Complete, minimal, self-contained example code that reproduces the issue

```
import os
from bokeh.plotting import figure, show

os.environ["BOKEH_MINIFIED"] = "false"
os.environ["BOKEH_PRETTY"] = "true"
figure_object = figure(height=400, width=400)
figure_object.circle([0, 1, 2], [0, 1, 2], radius=0.1, legend_label="circles")
figure_object.ellipse([2, 1, 0], [0, 1, 2], width=0.1, height=0.05, angle=0.0, legend_label="ellipses")

show(figure_object)
```

#### Stack traceback and/or browser JavaScript console output

```
Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
    at EllipseView._render (bokeh-2.3.2.js:32593)
    at EllipseView.draw_legend_for_index (bokeh-2.3.2.js:32663)
    at GlyphRendererView.draw_legend (bokeh-2.3.2.js:8318)
    at LegendView._draw_legend_items (bokeh-2.3.2.js:24445)
    at LegendView._render (bokeh-2.3.2.js:24398)
    at LegendView.render (bokeh-2.3.2.js:6029)
    at PlotView._paint_levels (bokeh-2.3.2.js:37479)
    at PlotView.paint (bokeh-2.3.2.js:37453)
    at PlotView.after_layout (bokeh-2.3.2.js:37386)
    at PlotView.compute_layout (bokeh-2.3.2.js:36069)
```

#### Screenshots or screencasts of the bug in action
The observed plot, as rendered:
bad_plot

The observed plot, when you try to interact with it:
bad_plot_interacted

*Note: Everyone interacting in the Bokeh project's codebases, issue trackers, and discussion forums is expected to follow the [Code of Conduct](https://github.com/bokeh/bokeh/blob/master/CODE_OF_CONDUCT.md).*

### PR DESCRIPTION
**Pull request by mattpap**
fixes #11367

### CODE REVIEW

**Comment by bryevdv** [comment]
It seems at least plausible this might affect other glyphs, probably worth a quick surgery before merging.

**Comment by mattpap** [comment]
Other look fine. The problem in general with this code is that it can't be statically typed due to using pseudo sparse arrays. Otherwise it would be trivial to catch such mistakes.

**Comment by bryevdv** [comment]
I don't disagree, this code dates back to earliest coffeescript days.

**Comment by AndrewRook** [comment]
I pulled these commits and this fix seems to be working, thanks so much for your quick effort! I really appreciate it.

**Comment by bryevdv** [comment]
@mattpap FYI need to remove `NEEDS BACK PORT` once port PRs is merged

**Pull request merged**
