### PR TITLE
Hotfix for files encryption

### PR DESCRIPTION
**Pull request by damianavila**
For some weird reason, in my testing builder, multiples files encryption was working... but not in the bokeh repo. And TravisCI said that is not possible unless you use some workaround I am using here now (ref: http://docs.travis-ci.com/user/encrypting-files/#Encrypting-multiple-files)

### CODE REVIEW

**Comment by damianavila** [comment]
Since the odds are against me :rage4: about triggering the devel build, I will not merge this one immediately, so all of you can take a look on the PR.

**Comment by damianavila** [comment]
pinging @bryevdv, since you had look the previous related PRs :wink:

**Comment by bryevdv** [comment]
This just puts all the secrets in one file? That seems fine to me.

**Comment by damianavila** [comment]
> This just puts all the secrets in one file? 

Yes... because if you try to use more than one file, the second encryption override the primary one, making the decryption of the first file unsuccessful... because it seems fine, then I will merge it. Thanks!

**Pull request merged**
