### PR TITLE
Bugfix donut chart line

### PR DESCRIPTION
**Pull request by fpliger**
Issues: #1578

### CODE REVIEW

**Comment by fpliger** [comment]
@bryevdv @mattpap @damianavila I've added the `donut_exp` notebook that reproduces the issue. Apparently it's not strictly related to charts. In the notebook there's an example that reproduces the issue with plot/glyphs. Could you guys please try the it and share your thoughts before I start digging further?

**Comment by damianavila** [comment]
Going to the example...

I don't know why you have data for 4 wedges when the last one have almost the same start and end... but there is the problem... 

```python
import numpy as np
end = np.array(data[0]['end']) 
start = np.array(data[0]['start'])
end - start

array([  2.95183202e-01,   3.37352231e-01,   2.53014173e-01,
        -1.11022302e-16])
```

In the last wedge the end < start which makes the wedge goes and complete almost all the circle...
Probably your problem is a point precision problem when you calculate the angles or something like that... helps?

**Comment by fpliger** [comment]
Ah, yeah. I guess so. I didn't notice that. Will follow that path.. still don't get why it randomly works well on Py3 (same script ran 10x gives different outputs). Thanks!

**Comment by fpliger** [comment]
As I was debugging I also removed implementation dependency on pandas/numpy...

**Comment by damianavila** [comment]
This LGTM... and tested in depth to be sure the fix it is working.
TravisCI in a false positive, so merging this one now...

**Pull request merged**
