### PR TITLE
Fix types of Gear.{angle,module} properties

### LINKED ISSUE #2665: Gear.{angle,module} have their types mixed up

### PR DESCRIPTION
**Pull request by mattpap**
fixes #2665

### CODE REVIEW

**Comment by bryevdv** [comment]
API tests needs updating: https://travis-ci.org/bokeh/bokeh/jobs/76273522#L1438

**Comment by damianavila** [comment]
ping @mattpap

**Comment by mattpap** [comment]
@damianavila, I updated tests.

**Comment by damianavila** [comment]
Tested locally, seems fine, let's merge it...

**Pull request merged**
