### PR TITLE
Use Element.dataset instead of $(...).data()

### LINKED ISSUE #5778: autoload_static uses Jquery .data()
This function

https://api.jquery.com/jquery.data/

was used in `embed.coffee`:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/embed.coffee#L147

### PR DESCRIPTION
**Pull request by mattpap**
fixes #5778

### CODE REVIEW

**Comment by mattpap** [comment]
@bryevdv, in the issue you said this needs tests and there are such, but what we really need is an example in `examples/embed` showing how to use this and this will test if this works on all levels. Just I'm not sure exactly how this is supposed to work.

**Comment by bryevdv** [comment]
I'm not sure, such an example will need to save a file, and then run a server. I'm no sure how easily such a thing would fit into our examples testing. I agree such an example would be valuable in any case. I was more thinking of some unit tests for `embed.coffee` (of which there are currently zero)

**Comment by bryevdv** [comment]
@mattpap here is a self-contained example you can add, it does not save any files, and running just the one script is all that is needed:
```
from jinja2 import Template

from tornado.ioloop import IOLoop
from tornado.web import Application, RequestHandler

from bokeh.embed import autoload_static
from bokeh.plotting import figure
from bokeh.resources import CDN
from bokeh.sampledata.iris import flowers
from bokeh.util.browser import view

template = Template("""
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
</head>

<body>
  <div>HERE IS SOME CUSTOM STUFF</div>
  {{ script|safe }}
</body>
</html>
""")

class IndexHandler(RequestHandler):
    def initialize(self, script):
        self.script = script
    def get(self):
        self.write(template.render(script=self.script))

class JSHandler(RequestHandler):
    def initialize(self, js):
        self.js = js
    def get(self): self.write(self.js)

def make_plot():
    colormap = {'setosa': 'red', 'versicolor': 'green', 'virginica': 'blue'}
    colors = [colormap[x] for x in flowers['species']]

    p = figure(title = "Iris Morphology")
    p.xaxis.axis_label = 'Petal Length'
    p.yaxis.axis_label = 'Petal Width'

    p.circle(flowers["petal_length"], flowers["petal_width"],
             color=colors, fill_alpha=0.2, size=10)

    return p

if __name__ == '__main__':
    print('Opening Tornado app with embedded Bokeh plot on http://localhost:8888/')

    js, script = autoload_static(make_plot(), CDN, "embed.js")

    app = Application([
        (r"/", IndexHandler, dict(script=script)),
        (r"/embed.js", JSHandler, dict(js=js))
    ])
    app.listen(8888)

    io_loop = IOLoop.current()
    io_loop.add_callback(view, "http://localhost:8888/")
    io_loop.start()
```

**Comment by bryevdv** [comment]
@mattpap please make a separate issue to add tests/examples. #5801 is a critical issue with GMaps has come out of nowhere and is affecting multiple versions of Bokeh. I have a possible, potential fix but the problem is only showing in more complicated embeds like docs, which I can't currently view because of this issue. I am merging this immediately to unblock work on #5801

**Pull request merged**
