### PR TITLE
fix a typo

### PR DESCRIPTION
**Pull request by kyang922**
sr.data_source -> cr.data_source

### CODE REVIEW

**Comment by bryevdv** [comment]
Thanks for the catch and fix @kyang922

**Comment by kyang922** [comment]
@bryevdv 
Sorry, it seems not to be a typo. I found the original there
https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/callbacks.html#customjs-for-hover

the 'sr' is used to draw the link line. but in this notebook version, here is no those lines. so it may not be necessary to write this arg here.

**Comment by kyang922** [comment]
@bryevdv 
by the way, I found interaction selection examples in the user guide not works.
https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/callbacks.html#customjs-for-selections

I tried it in my Firefox(63.0.3) and Chrome(70.0.3538), neither worked. I also tried those code in my jupyter with bokeh 1.0.1, same result.

**Comment by bryevdv** [comment]
@kyang922 Yes the example needs to be updated (there is already another open issue for it)

**Comment by kyang922** [comment]
@bryevdv oh, I just saw that issue. Thanks a lot.

**Pull request merged**
