### PR TITLE
Bryanv/013 docs

### PR DESCRIPTION
**Pull request by bryevdv**

### CODE REVIEW

**Comment by numpynewb** [comment]
I am not sure if this is the right place to comment on the `/examples/app/dash/README.md` file, but to execute this example, does one simply run `bokeh serve --show main.py`? I think it would improve the README.md file to include the method by which this example is run. Apologies if this instruction is found elsewhere and I just missed it, or if this is not the correct place to comment on this. Thank you!

**Comment by bryevdv** [comment]
for directory apps you should run using the directory name: `bokeh serve --show dash` If you try to run `main.py` you will see a warning:
```
(base) ❯ bokeh serve --show main.py
/Users/bryanv/work/bokeh/bokeh/command/util.py:91: UserWarning:
It looks like you might be running the main.py of a directory app directly.
If this is the case, to enable the features of directory style apps, you must
call "bokeh serve" on the directory instead. For example:

    bokeh serve my_app_dir/

If this is not the case, renaming main.py will supress this warning.

  warnings.warn(DIRSTYLE_MAIN_WARNING)
```

**Comment by numpynewb** [comment]
Thank you so much!

**Comment by bryevdv** [comment]
If you'd like to update the README with more info, a small pull request would certainly be welcome and  appreciated

**Comment by numpynewb** [comment]
Absolutely! I just added a pull request, I believe. So sorry if I am doing this wrong, I am new and learning how to contribute on GitHub.

**Pull request merged**
