### PR TITLE
added tile provider demo to showcase all basemap providers including newly contributed OSM, WIKIMEDIA, and ESRI_IMAGERY tile providers

### LINKED ISSUE #9704: [FEATURE] need to add tile provider demo
This Issue is to request a tile provider demo to showcase all Bokeh tile providers.

In particular, it would be nice to compare the newly added OSM, WIKIMEDIA, and ESRI_IMAGERY tile providers to each other and the existing STAMEN and CARTODBPOSITRON tile providers.

This tile provider demonstration will allow Bokeh to provide open-source alternatives to Google Maps with Open Street Maps as the standard basemap with streets, buildings and other features along with the ESRI_IMAGERY for the satellite view of the same location.

bokeh_tile_demo_screenshot

### PR DESCRIPTION
**Pull request by comperem**
New PR from updated fork to resolve this issue.

Adding new tile provider demo illustrating all tile provider maps.

- [ x ] issues: fixes #9704 
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

Lady Bird Johnson park, downtown running trail, Austin Texas
bokeh_tile_demo_screenshot

### CODE REVIEW

**Comment by comperem** [comment]
Ok, @bryevdv , I'm not able to get the updated version to pass the tests. The imports are listed alphabetically and there are other issues I don't understand.

Take it or leave it. I'm done.

Thanks for your help.

**Comment by bryevdv** [comment]
@comperem I've tried to fix the linting issues here in the GH UI. The other message is about the bare except:
```
     try:
         #              from: WGS84, lat/lon, EPSG:4326    to: Web Mercator, EPSG:3857 in meters
         easting, northing = transform( Proj('epsg:4326'), Proj('epsg:3857'), lat, lon) # from WGS-84 to Web Mercator Easting/Northing
         return easting, northing # meters
     except:
         return None, None
```

That really needs to be something more specific as it is generally not good practice to use bare excepts (that catches, e.g. keyboard interrupts and other things which is not usually desired). 

However, looking at that I also noticed that adding this will impose a new dependency on pyproj. We will have to weigh whether to really do that, or if it would be better/simpler for users to just pre-project any coordinates ahead of time ourselves so that users do not have to install that extra dependency. Since you have indicated that you are't able to continue, I'll close this and leave the issue open. Whoever can take this up will have the PR to reference and pick up from.

**Comment by comperem** [comment]
Thanks for your help Bryan.

I understand pyproj would certainly be a new dependency. Convenient
coordinate transformations are an important part of handling geospatial
data. The web mercator reference frame is prevalent in the GIS community
and pyproj is mature and fast.

If Bokeh is going to address GIS data then some type of coordinate
transformation API needs to be easily accessible.

**Comment by comperem** [comment]
@bryevdv , I'm not sure how to re-submit this PR. I've updated the earlier `bokeh_tile_demo.py` with the new `lnglat_to_meters()` function to provide coordinate transformation from geographic (lat/lon) in decimal degrees to Web Mercator's Easting and Northing values.

The Easting and Northing values are required for plotting maps with Mercator projection in `Bokeh`.

Previously when I tried to get this PR submitted and completed it had linting problems (probably still does) and also had a dependency on a non-Bokeh `pyProj` library for coordinate conversions.

With the `lnglat_to_meters()` function from @jbednar  from [this thread](https://github.com/bokeh/bokeh/issues/10009), it seems this Geographic tile provider demo might be ready for completion.

I'm probably not the best person to iron out the linting issues. If someone can help this would make a good addition to showcase `Bokeh`'s geographic plotting capability that's already built-in.

Marc

**Pull request closed without merging**
