### PR TITLE
Upgrade to TypeScript 4.9

### PR DESCRIPTION
**Pull request by mattpap**
This updates to TypeScript 4.9 and Chromium 109 for testing (fixing test issues in other PRs).

### CODE REVIEW

**Review by ianthomas23 — APPROVED** [review]

**Comment by ianthomas23** [comment]
Merging this to see if it deals with CI failures in other PRs.

**Comment by ianthomas23** [comment]
Noting that whenever we update the version of chrome used to generate visual baseline images then the docker image also needs to be rebuilt so that it is using the same version. This means that we cannot use a single docker image per Bokeh release unless we only ever change the chrome version just after release.

**Comment by bryevdv** [comment]
>  This means that we cannot use a single docker image per Bokeh release unless we only ever change the chrome version just after release.

IIRC the expectation was always one image per chrome version, and then, secondarily, that we might try to coordinate chrome updates at the beginning of a dev branch, as an ideal, but optional, preference. Or is the concern about being able to easily "go back" to earlier revisions on a given branch?

**Comment by ianthomas23** [comment]
I'm not particularly concerned, I just wanted the dependency documented somewhere.

There was a time when we labelled the docker images with the version of chrome that they contained, but I took this out. Probably it should go back in so that we can easily find the latest image that corresponds to a specific chrome version.

**Pull request merged**
