### PR TITLE
Fixed updating of setup_events

### PR DESCRIPTION
**Pull request by bald**
Bugfix for Issue #2124
https://github.com/bokeh/bokeh/issues/2124

### CODE REVIEW

**Comment by hhuuggoo** [comment]
oh does py3 keys() return an iterator?  the py2 one returns a list so it works ok

**Comment by hhuuggoo** [comment]
There was a sporadic failure on one of the travis builds - I restarted it, once it passes I'll merge this

**Comment by bald** [comment]
Can this be merged?

**Comment by bald** [comment]
Can this be merged?

**Comment by fpliger** [comment]
LGTM. If there are no objections will merge it later today

**Pull request merged**
