### PR TITLE
Drop support for Python 3.6

### LINKED ISSUE #10839: Drop Python 3.6
targeting for 2.4

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #10839 
- [x] release document entry (if new feature or API change)

### CODE REVIEW

**Review by tcmetzger — APPROVED** [review]
Looks great!

**Comment by tcmetzger** [comment]
Two somewhat related questions/thoughts:

- in the repo root folder there is the script versioneer.py. In the docstring it says it is `Compatible With: python2.6, 2.7, 3.2, 3.3, 3.4, 3.5, 3.6, and pypy` - this makes we wonder if this script might need to be updated as well, given that the latest Python version supported by the script will be dropped for Bokeh? Is this tool being used at all anymore?
- The example in the docstring in `bokeh\command\subcommands\info.py` seems very outdated. Not only does it mention Python 2.6, it also uses Bokeh 0.12.15 as an example. This is of course entirely optional, but maybe this PR is a good chance to update that example as well...

**Comment by bryevdv** [comment]
@tcmetzger `versioneer` is a third-party tool. It is what automatically generates versions based on Git commits in the dev state:
```
2.3.0rc2-6-g0c5607dee
```
and also hard-codes tag versions when releases are bundled. It is meant to be vendored in like we have done, and in general it is a black box and we should not touch it. We *could* consider reving to a more recent version of versioneer:

https://github.com/python-versioneer/python-versioneer

But I am not sure it is a huge priority. If our current vendored version ever stops working with some newer python, we will know in CI immediately. 

I will update the docstring in `bokeh\command\subcommands\info.py` though.

**Comment by bryevdv** [comment]
@mattpap I'll plan to merge this tomorrow morning unless you ask for more time

**Pull request merged**
