### PR TITLE
Add new layout functions for row & column

### PR DESCRIPTION
**Pull request by birdsarah**
Partially fixes: #4384 

The other part of #4384 is for layout functions to accept arbitrarily nested lists. But this can wait till later. These functions should make it quick enough to spell out layouts.

### CODE REVIEW

**Comment by birdsarah** [comment]
Note this doesn't have tests, but I do have an open issue saying that we need them: #4388.

**Comment by birdsarah** [comment]
Forgot to add a widgetbox function.

**Comment by birdsarah** [comment]
ping @bryevdv - ok to merge?

**Comment by birdsarah** [comment]
i need to merge this so can then fix up the sizing_mode pr

**Comment by bryevdv** [comment]
looks OK at a quick glance

**Comment by birdsarah** [comment]
I'm going to be updating these functions in the sizing_mode PR as they should behave differently when  we have responsive and sizing_mode, so we can take a closer look in that PR.

**Pull request merged**
