### PR TITLE
Exploration on splitting our tests

### PR DESCRIPTION
**Pull request by damianavila**
Trying some things where I research how speed up our testing machinery...

### CODE REVIEW

**Comment by mattpap** [comment]
Just to note, preparation for running tests, i.e. installing software, building bokehjs, etc., is pretty expensive, so too many groups may not be a good idea.

**Comment by damianavila** [comment]
> Just to note, preparation for running tests, i.e. installing software, building bokehjs, etc., is pretty expensive, so too many groups may not be a good idea.

I know... I just want to test the split after trying to cache the dependencies... I am just testing in the incorrect order :wink:

**Comment by damianavila** [comment]
But I agree that too many groups is not a good idea probably...

**Comment by damianavila** [comment]
Well, this ones is doing:

* Cache dependencies (conda and npm ones)
* Split the runs into smaller groups
* Defaulting to avoid examples runs unless you specified `[ci enable examples]` in your commit message.

When the examples are run, we don't have reduction in the total time spent, BUT if you don't run the examples (for instance, because you are in the middle of a PR and you want a rapid iteration) the total time dimished even running several groups...

Without examples...

notenableexample

With examples...

enable_examples


I like the groups because you can actually see quickly where is the issue... but we can have less groups (put js and integration in the same group) and probably only test js and integration with python 3 to reduce the number of build (which takes time... regrettably, conda build does not have a option to "keep" the _build environment which could potentially be cached to reduce the time even more) thoughts?

**Comment by damianavila** [comment]
@bokeh/core ^^^ I forgot the mention :wink:

**Comment by bryevdv** [comment]
My personal first inclination would be to group both the python on JS unit tests together, rather than JS and integration. They are both the same "kind" of test, and they are also both very fast once things are built. But maybe there is a dependency/ordering issue that would make something else make more sense.

**Comment by damianavila** [comment]
I want to merge this one today... any blockers?

**Comment by damianavila** [comment]
@bokeh/core ^^^

**Pull request merged**
