### PR TITLE
Error prompt

### LINKED ISSUE #2392: Alerts for the "white screen of death"
Sometimes your python code runs without errors, but the plot is empty. You need to know/remember to got the console to figure out what went wrong.

It would be great if we had some kind of warning, or flag to get warnings about this.

ping @mattpap @canavandl

### PR DESCRIPTION
**Pull request by mistakevin**
Closes #2392

### CODE REVIEW

**Comment by bryevdv** [comment]
Won't this catch any and all errors, even ones that aren't Bokeh related?

**Comment by mistakevin** [comment]
Can anyone consistently create the "White Screen of Death"?

**Comment by damianavila** [comment]
@mistakevin did the @chdoig example work like a nice test case?

**Comment by mistakevin** [comment]
Yep, seems like a JSON problem. We aren't encoding the NaN types to proper JSON null types, causing issues on the return from the server. Not sure what we should support, deep JSONifying of data or an exception being raised notifying the user of NaN values. Any thoughts?

**Comment by bryevdv** [comment]
`null` is also used for `None`. We have to be able to distinguish `NaN` values somehow, so we have to find some encoding that can be understood by BokehJS and converted specifically to a true `NaN`

**Comment by mistakevin** [comment]
Related PR https://github.com/bokeh/bokeh/pull/2445

**Comment by birdsarah** [comment]
@mistaken also show(Plot()) as per #2441

**Comment by damianavila** [comment]
I remember from a comment in a closed PR that this is very annoying... @mistakevin if that's the case, do you wan to continue with this direction or we should close this one?

**Comment by mistakevin** [comment]
This PR can probably be closed, as we are working on incorporating this issue into https://github.com/bokeh/bokeh/pull/2445

**Comment by damianavila** [comment]
>This PR can probably be closed, as we are working on incorporating this issue into #2445

Sound reasonable, closing here...

**Pull request closed without merging**
