### PR TITLE
Added support for vertex snapping to PolyDrawTool and PolyEditTool

### PR DESCRIPTION
**Pull request by philippjfr**
This PR will implement vertex snapping for the PolyDrawTool and PolyEditTool (not yet implemented), allowing for more complex draw actions. Here is it in use for the PolyDrawTool:

snapping
 
- [x] issues: fixes https://github.com/bokeh/bokeh/issues/8148
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
@philippjfr I am seeing some tslint messages on the codebase build on master, I am not sure why they didn't fail the build, but can you look at cleaning them up in this PR? (some are for edit tools)

```
+node make scripts:compile --emit-error
[19:41:03] Starting 'scripts:ts'...
[19:41:24] Finished 'scripts:ts' after 20.08 s
[19:41:24] Finished 'scripts:compile'
+node make test:compile --emit-error
[19:41:29] Starting 'test:compile'...
[19:41:45] Finished 'test:compile' after 15.42 s
+node make tslint
[19:41:50] Starting 'tslint:lib'...
[19:41:52] /home/travis/build/bokeh/bokeh/bokehjs/src/lib/models/glyphs/text.ts:29:3
[19:41:52] ERROR: 29:3  return-type  expected '_rotate_point' to have an explicit return type
[19:41:52] ERROR: 35:3  return-type  expected '_text_bounds' to have an explicit return type
[19:41:53] /home/travis/build/bokeh/bokeh/bokehjs/src/lib/models/tools/edit/box_edit_tool.ts:160:32
[19:41:53] ERROR: 160:32  trailing-comma  Missing trailing comma
[19:41:54] Finished 'tslint:lib' after 3.78 s
[19:41:54] Starting 'tslint:test'...
[19:41:54] /home/travis/build/bokeh/bokeh/bokehjs/test/models/tools/edit/box_edit_tool.ts:242:11
[19:41:54] ERROR: 242:11  prefer-const  Identifier 'drag_event' is never reassigned; use 'const' instead of 'let'.
[19:41:54] /home/travis/build/bokeh/bokeh/bokehjs/test/models/tools/edit/poly_draw_tool.ts:265:11
[19:41:54] ERROR: 265:11  prefer-const  Identifier 'drag_event' is never reassigned; use 'const' instead of 'let'.
[19:41:54] Finished 'tslint:test' after 509 ms
[19:41:54] Starting 'tslint:examples'...
[19:41:54] Finished 'tslint:examples' after 80 ms
[19:41:54] Finished 'tslint'
```

**Comment by mattpap** [comment]
>  am not sure why they didn't fail the build

At this point, tslint is run during tests, but doesn't fail if errors are present.

**Comment by philippjfr** [comment]
Happy to fix them here.

**Comment by philippjfr** [comment]
Ready to review and merge.

**Pull request merged**
