### PR TITLE
Use numbro.js instead of Numeral.js

### PR DESCRIPTION
**Pull request by dennisobrien**
Bokeh issue #2922 details issues with attempting to format Infinity and NaN.  This was fixed in Numbro.js, an active fork from Numeral.js.

This PR uses Numbro.js 1.6.2 with some modifications to make it work.  I was hoping to just drop it in to the vendor folder and have it work, but I can see that there were many changes to Numeral.js to make it work and to pare it down.

I have not done any paring down of this, just making it work.  But that might be a good next step.

Here's the test I've been using.  This breaks in Bokeh 0.10.0 and before with a Javascript error.

```
from bokeh.io import output_notebook
output_notebook()

from bokeh.io import show
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, TableColumn, NumberFormatter
import numpy as np
import pandas as pd


# create a data frame with some np.NaN and np.Infinity values
df = pd.DataFrame(data=[[1, 2, 3], [1, 0, 4], [np.Infinity, 0, np.NaN]], columns=['x', 'y', 'z'])
source = ColumnDataSource(df)

columns = [
    TableColumn(field='x', title='x', formatter=NumberFormatter(format="0.0")),
    TableColumn(field='y', title='y', formatter=NumberFormatter(format="0.0%")),
    TableColumn(field='z', title='z', formatter=NumberFormatter(format="$0.0")), 
]
data_table = DataTable(source=source, columns=columns, editable=False)

show(data_table)
```

### CODE REVIEW

**Comment by dennisobrien** [comment]
The failing test is `test_file_html_handles_js_only_resources` which compares the Javascript source from two different methods.  This warning points to an issue with unicode:
```
/home/travis/build/bokeh/bokeh/bokeh/tests/test_embed.py:159: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
```

It looks like `bokeh.embed.file_html` calls `encode_utf8` while the other side of the assert == does not.  It happens that the Javascript source for Numbro.js does include Unicode characters.  I'm including a change to the test that should fix this.

**Comment by bryevdv** [comment]
ping @mattpap

**Comment by bryevdv** [comment]
FWIW we've previously discussed reducing the number of vendored libraries. If there is a versioned, unmodified, maintained library that can replicated all the current functionality I think it could be good to use it, but not to check it in.

**Comment by mattpap** [comment]
@bryevdv, numeral.js was put in vendor because I intended to incorporate it into bokehjs' source code and start extending it there, but this was never accomplished. So, if numbro.js' functionality suites our needs, then lets use it from npm. Otherwise, we have to proceed as in this PR.

**Comment by mattpap** [comment]
If we proceed with this PR, then all `*.min.js` files have to be removed.

**Comment by bryevdv** [comment]
@dennisobrien any thoughts on these questions? I think it might be possible to create fork of a project on  GH then install from that fork? That would be preferable to vendorin in another library directly. ping @mistakevin

**Comment by mistakevin** [comment]
Yeah, if we can just use it as-is, pull it in with npm. If some changes need to be made, we should fork it and pull in our fork using npm.

**Comment by bryevdv** [comment]
@mistakevin it does look like there were some mods. Do you think this is something you could work on?  Basically: fork in bokeh org, apply the changes @dennisobrien made, get it working with our build. A demonstration of doing it would be very helpful for others to follow in the future.  We do need to verify that all existing capability is preserved.

**Comment by mistakevin** [comment]
@bryevdv Yeah, I can do that. I need more privileges in order to fork a repo in the Bokeh organization, or someone can do it for me and I can work on it from there. https://github.com/foretagsplatsen/numbro

**Comment by mistakevin** [comment]
@dennisobrien can you verify these changes? https://github.com/bokeh/numbro/commit/2b2bbfd70f885017799b797a7d0d12601dfde660

**Comment by mistakevin** [comment]
@dennisobrien Can you verify these changes https://github.com/bokeh/numbro/commit/026294f5b1e13894e17ca262dc4148e66dda0e65 ? If so, take a look at https://github.com/bokeh/bokeh/pull/3043 and resolve the conflicts.

note: [here](https://github.com/bokeh/bokeh/pull/3043) is where we are bringing it in via npm


cc @bryevdv @mattpap

**Comment by dennisobrien** [comment]
Hi @mistakevin - Catching up on several days of missed activity.

I can verify that these files are identical:
https://github.com/bokeh/numbro/blob/026294f5b1e13894e17ca262dc4148e66dda0e65/dist/numbro.js
https://github.com/dennisobrien/bokeh/blob/fix/2922_use_numbrojs/bokehjs/src/vendor/numbro.js-1.6.2/numbro.js

I'll continue the discussion on #3043 since that seems like the active PR here.

thanks,
Dennis

**Pull request closed without merging**
