### PR TITLE
Add support for `CategoricalSlider` widget

### LINKED ISSUE #9843: categorical slider
Similarly to the Dash slider (https://dash.plotly.com/dash-core-components/slider)
add a categorical (or ordinal) slider that allows to specify
1) values (e.g. values=[0,1,2,3]) and
2) labels (e.g. labels=['yearly','quarterly','monthly','weekly'])
that are both accessible from within the callback function.

The functionality is similar to a radio button group, but can be optically more pleasing.
image

### PR DESCRIPTION
**Pull request by mattpap**
Adds a pretty primitive `CategoricalSlider` widget. This PR is more an excuse to redesign and robustify sliders' implementation and view class structure.

image

fixes #9843

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap Am I correct that the categorical slider here does not render all the categories visible along the slider, so that a user can see what exactly they are setting the slider to in advance?  If so, I have to be honest and state that I don't think the slider is useful in its present form, and this should wait on merge until a slider "axis" can be implemented.

**Comment by mattpap** [comment]
Lack of visible categories is unfortunate. I actually implemented this, but it results in mangled CSS layout. This is peculiar design on nouislider's side. Given I'm working on CSS anyway, I will figure out soon enough how to do this properly. I also would prefer to PRs like this not linger around, just causing more work with fixing unnecessary merge conflicts.

**Comment by bryevdv** [comment]
> Given I'm working on CSS anyway, I will figure out soon enough how to do this properly. I also would prefer to PRs like this not linger around, just causing more work with fixing unnecessary merge conflicts.

Are you suggesting to merge this now with a follow-up (for 3.4) to add labels? That seems fine as long as there is a milestoned issue for the follow-up

**Review by bryevdv — APPROVED** [review]
👍 with a corresponding follow-up issue to add labels for 3.4

**Pull request merged**
