### PR TITLE
Issue 3943: vform should remove children from document root

### PR DESCRIPTION
**Pull request by clairetang6**
The layout generation methods in bokeh.io (gridplot, hplot, vplot, vform) allow a user to create a layout by passing in subplots, which can be other layouts. For convenience, these methods add the layout to the document root and "push or save" the new state. To allow for nesting of layouts, these methods also remove any of the subplots from the document root. This was done for gridplot, hplot, and vplot, but not for vform which caused bugs when other layouts were passed as children to vform. 

There's an example of the bug in the [issue (#3943)](https://github.com/bokeh/bokeh/issues/3943) that I posted. 

I just added a call to remove the children passed to vform from the document root. I also added some tests to test_io.py for the layout generation methods. There are two tests for each method, testing that the method produces a layout that is added to the document root and testing that its children are removed from the document root. This second test fails for vform before this fix.

### CODE REVIEW

**Comment by birdsarah** [comment]
@clairetang6, thanks for your pull request.

Please ignore the failed test, this is due to a problem with our build infrastructure that I introduced (#3927). I've opened a PR to fix the issue. Sorry for any inconvenience.

**Comment by birdsarah** [comment]
@clairetang6 the issue with testing has been resolved on master if you wouldn't mind updating this PR onto master that would be great.

**Comment by bryevdv** [comment]
Hi @clairetang6 I have not forgotten about this. There is some other work that is ongoing on a slightly longer timeline (several weeks at least) that intersects with this, but I think we can still proceed with this PE in the mean time.

**Comment by clairetang6** [comment]
@bryevdv I don't have anything else to add to it, unless you think the other widgets that have children, like the Tabs or Panels should be looked at. I saw the additional [comment](https://github.com/bokeh/bokeh/issues/3943#issuecomment-191460079) on the issue this pull request is supposed to address, but I haven't looked through any of the source code for that. Maybe you know if there would be easy wins there too? Otherwise, my one-line patch is an easy fix for the exact issue I found. 

I'm also looking forward to seeing how the layout work progresses!

**Comment by bryevdv** [comment]
@havocp do you have any thoughts about this?

**Comment by havocp** [comment]
Seems fine to me to make this consistent. We had the whole discussion about doing something better for all of these (I don't have the link handy), but in the meantime why not make them all match...

**Comment by bryevdv** [comment]
@clairetang6 I do think it would make sense to do `vplot`, `hplot`, and `gridplot` at the same time. Does that sound reasonable? Then we can merge this in the mean time while more comprehensive layout work is going on.

**Comment by clairetang6** [comment]
Hi @bryevdv, I'm not sure I understand what you mean. `vplot`, `hplot`, and `gridplot` in bokeh.io already remove the children from the document root before adding the layout (a new `VBox`, `HBox`, and `GridPlot`, respectively). `vform`, however, doesn't remove the children before adding the `VBoxForm`, which will cause extra plots to be displayed in some situations. Adding the `_remove_roots` to `vform` makes `vform` consistent with `vplot`, `hplot`, and `gridplot`.

**Comment by bryevdv** [comment]
Ah, my mistake, this looks good then.

**Pull request merged**
