### PR TITLE
Add scale factor to png export

### PR DESCRIPTION
**Pull request by golmschenk**
This is an attempt to solve https://github.com/bokeh/bokeh/issues/8807, though I feel this current solution adds quite a bit of clutter.

The main gist of the issue is to allow PNG exports to provide a scale factor to scale the image to allow higher resolutions while maintaining the relative proportions of all elements. This is particularly important for use in scientific publications.

I used the solution recommended by https://github.com/bokeh/bokeh/issues/8807#issuecomment-1025133009. Specifically, setting the Selenium web driver's device pixel ratio (DPR) to the desired scale factor.

There were multiple ways to approach this, and I picked what I thought was the safest choice. However, it's also the approach that results in the most clutter in the code. The scale factor is passed as a parameter to each function related to creating a new web driver for the screenshot. This means several functions were given the `scale_factor` parameter simply so they can pass it to another function. An alternative would be to set an attribute of the `_WebdriverState`. However, I felt this would be much more likely to cause unexpected side effects when the attribute is set somewhere and not reverted later.

Previously, Chromium drivers (that were not created manually by the user) were always forced to have a DPR of 1, while FireFox drivers did not set the DPR so that it would (presumably) select the DPR of the real device. Instead, to force consistency and enable the scale factor, I set both drivers to use a DPR equal to the passed scale factor, and if no scale factor was passed, to default to 1.

If the user passes a custom web driver, the DPR of that driver is checked, and an exception is raised if the DPR is not greater than or equal to the requested scale factor. When the DPR is greater than the requested scale factor, the image is resized after the screenshot is taken. It seems this is what was previously occurring for images from the FireFox drivers, while Chromium drivers were always forced to a DPR of 1. Allowing DPRs higher than the requested scale factor is important because user-created web drivers may have a DPR set by their display.

Please let me know if this approach seems reasonable or if it adds too much clutter.

### Example with output figures
```
from bokeh.plotting import figure
from bokeh.sampledata.penguins import data
from bokeh.transform import factor_cmap, factor_mark
from bokeh.io import export_png

species = sorted(data.species.unique())
markers = ['hex', 'circle_x', 'triangle']

figure_ = figure(title="Penguin size", background_fill_color="#fafafa", width=300, height=300)
figure_.xaxis.axis_label = 'Flipper Length (mm)'
figure_.yaxis.axis_label = 'Body Mass (g)'

figure_.scatter("flipper_length_mm", "body_mass_g", source=data,
                legend_group="species", fill_alpha=0.4, size=8,
                marker=factor_mark('species', markers, species),
                color=factor_cmap('species', 'Category10_3', species))

figure_.legend.location = "top_left"
figure_.legend.title = "Species"

export_png(figure_, filename="original.png")
export_png(figure_, filename="scaled.png", scale_factor=2.5)
export_png(figure_, filename="sized.png", width=750, height=750)
```
Original (low resolution):
original
Scaled (high resolution, PR added feature):
scaled
Sized (for comparison, using `width` and `height` of `export_png`):
sized

### CODE REVIEW

**Comment by bryevdv** [comment]
@golmschenk Thanks for the PR this seems pretty interesting. For the sake of comparisons can you add some before/after images to the OP?

**Comment by golmschenk** [comment]
> @golmschenk Thanks for the PR this seems pretty interesting. For the sake of comparisons can you add some before/after images to the OP?

Added.

**Comment by bryevdv** [comment]
Thoughts @bokeh/core ? I don't think this is especially cluttered, but I do wonder if we might explicitly want to make `scale` mutually exclusive to `width`/`height`

**Comment by golmschenk** [comment]
> I do wonder if we might explicitly want to make `scale` mutually exclusive to `width`/`height`

I don't have a strong opinion about this, but I think allowing `width` and `height` to be specified at the same time as `scale_factor` is reasonable. I could see cases where the user would want to use `export_png`'s `width` and `height` to change the aspect ratio for export but then still want to provide a scaled high-resolution version of that. I also think the likelihood of unexpected results is fairly low since they would need to set both explicitly. That said, I don't have a strong opinion on this, and I am happy to implement the mutual exclusion of options if that's the preferred route.

**Comment by golmschenk** [comment]
Please let me know if there are any changes required that I can perform to help finish this PR. I'm guessing the wait is due to limited core developer time. But I just wanted to confirm there's nothing I could be working on to progress this (especially since it's still tagged with WIP).

**Comment by bryevdv** [comment]
@golmschenk Thanks for your patience, there is a mypy issue that will need to be fixed:
```
mypy 1.2.0 (compiled: yes)
src/bokeh/io/webdriver.py: note: In function "create_firefox_webdriver":
src/bokeh/io/webdriver.py:73:5: error: "Options" has no attribute
"set_preference"  [attr-defined]
        options.set_preference('layout.css.devPixelsPerPx', f'{scale_facto...
        ^~~~~~~~~~~~~~~~~~~~~~
Found 1 error in 1 file (checked 728 source files)
Error: Process completed with exit code 1.
```
As long as you are fixing that up, it would be good to merge/rebase on latest `branch-3.3` and then I think we can merge when things are green.

**Comment by bryevdv** [comment]
Thanks for your diligence @golmschenk looks like just one last issue from `ruff`
```
E       AssertionError: ruff issues:
E         src/typings/selenium/webdriver/firefox/options.pyi:5:48: UP007 [*] Use `X | Y` for type annotations
E         Found 1 error.
```

**Comment by golmschenk** [comment]
> Thanks for your diligence @golmschenk looks like just one last issue from `ruff`

Sorry to make you spend so much time looking over the failing tests. I was just reading up a bit more on the code quality tools being used.

**Comment by bryevdv** [comment]
No worries these are thing it is simple to help with!

**Comment by bryevdv** [comment]
Thanks @golmschenk !

**Review by bryevdv — APPROVED** [review]

**Review by bryevdv — APPROVED** [review]

**Pull request merged**
