### PR TITLE
Allow to disable `DatePicker` (etc.) after creation

### LINKED ISSUE #13255: [BUG] Enabling/Disabled DatePickers does not work
### Software versions

``` yaml
Python version      :  3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
IPython version     :  8.14.0
Tornado version     :  6.3.2
Bokeh version       :  3.2.0
BokehJS static path :  /home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  v18.16.1
npm version         :  9.5.1
Operating system    :  Linux-6.2.6-76060206-generic-x86_64-with-glibc2.35
```

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

Expecting DatePicker and its family of models to be disabled like the TextInput.

First seen here https://github.com/holoviz/panel/issues/5254.

### Observed behavior

It does not disable it

### Example code

```Python
from bokeh.io import curdoc
from bokeh.models import Button, DatePicker, TextInput

date = DatePicker(title="DatePicker", value="2019-09-20")
text = TextInput(title="TextInput", value="2019-09-20")

# Bokeh button which disables the picker from python
button = Button(label="enable/disable")
button.on_click(lambda: setattr(date, "disabled", not date.disabled))
button.on_click(lambda: setattr(text, "disabled", not text.disabled))

curdoc().add_root(date)
curdoc().add_root(text)
curdoc().add_root(button)
```

### Stack traceback or browser console output

_No response_

### Screenshots

https://github.com/bokeh/bokeh/assets/19758978/31fcd03e-fab3-4488-94f5-880cfa26d108

### PR DESCRIPTION
**Pull request by mattpap**
fixes #13255

### CODE REVIEW

**Comment by mosc9575** [comment]
Hi,

it looks like the changes have no visual effect but the state changes. 

|visual effect|log|
|--|--|
|disable|grafik|

I was running the example below

```python
from bokeh.io import show, output_notebook
from bokeh.layouts import column
from bokeh.models import Button, DatePicker, TextInput, CustomJS
output_notebook()

date = DatePicker(title="DatePicker", value="2019-09-20")
text = TextInput(title="TextInput", value="2019-09-20")

# Bokeh button which disables the picker from python
button = Button(label="enable/disable")
button.js_on_event(
    "button_click",
    CustomJS(
        args=dict(date=date),
        code="""
        console.log(date.disabled);
        date.disabled = !date.disabled;
        """
    )
)
button.js_on_event(
    "button_click",
    CustomJS(args=dict(text=text), code="""text.disabled = !text.disabled;""")
)
show(column(date, text, button))
```

**Comment by mattpap** [comment]
Works for me:

https://github.com/bokeh/bokeh/assets/27475/786ff2fa-8cb3-4e5a-a11a-c1deba71d735

Let's make sure the JS resources are up-to-date, because this looks like a caching issue.

**Comment by mosc9575** [comment]
I have to apologize. Still can't reporduce the correct version on my maching but I added a log message and can't see the it.

**Review by bryevdv — APPROVED** [review]

**Comment by mattpap** [comment]
> (...) Still can't reporduce the correct version on my maching but I added a log message and can't see the it.

Do you have "Disable cache" in devtools enabled? E.g.:

image

If so, then it's probably resources' resolution that's the problem. This may be known knowledge, but I will reiterate just in case. To make sure you use the most recently compiled resources, I strongly recommend running bokeh scripts with `BOKEH_DEV=true BOKEH_RESOURCES=server-dev` (which in bokeh 3.3 hopefully will be the default and thus reduced to just `BOKEH_DEV=true`) and then have `BOKEH_DEV=true bokeh static` running in a separate process/terminal.

**Comment by mosc9575** [comment]
@mattpap Thanks for your help. Now I get the expected result.

**Pull request merged**
