### PR TITLE
added brute force handling of resize tool event.

### PR DESCRIPTION
**Pull request by brendancol**
I'm looking for the best way to handle a resize event within the tile renderer.  I added a "brute force" fix but am looking for alternatives.

### CODE REVIEW

**Comment by brendancol** [comment]
In the commit above, I am handling the result of the resize tool on tile renderer. When the plot resizes, I want to snap to the correct resolutions and prevent distortion of the tiles in either dimension.  

As a "brute force" approach, I am storing current height/width then checking if heigh/width has changed on each render cycle.  This seem too specific for my use case.  My just not sure how to use a "resize" event.

**Comment by almarklein** [comment]
Also see #2881 and #2950 for responsiveness to resizing. These apply to resizing the plot to the available space, while I think what you need is reacting to resizing via the resize tool. Maybe we need a unified approach. cc @birdsarah

**Comment by bryevdv** [comment]
@brendancol the "right" way to do this is to enforce an aspect ratio. Then on resize, you can either:

* adjust the margins to maintain aspect, or

* adjust the ranges to maintain aspect

The latter is the one @pzwang has mentioned before, where you make the plot bigger, and it just "uncovers" more area.

**Comment by bryevdv** [comment]
Technically there is some preliminary but never enabled or tested code already towards having an spect ratio constraint in here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/common/layout_box.coffee#L63

It is off by default, and there is no plumbing to expose it to the user. It is incomplete and can only handle enforcing a 1-1 aspect. Turning it on means answering: what is the best way way users to be able to spell a fixed aspect, how do we implement the second case above too, tests, examples, etc.

**Comment by brendancol** [comment]
This started as a `resize tool` fix for me but I realized I also needed the logic for create a wall-to-wall map and the box-zoom tool as discussed.  I still want the user to be able to change aspect-ratio using the mouse wheel on a single axis, just not for those tools or when setting initial plot size to fill the browser viewport.

**Comment by bryevdv** [comment]
Is is appropriate for users to be able to change the aspect in any situation? Google Maps, for instance, do not allow this. Certainly when tiles are showing non-GIS data, a free aspect might make sense but I think for tiled GIS data a strictly enforced aspect is what people will expect.

**Comment by brendancol** [comment]
In GIS-land...no, but other tile renderer use cases (seismic data) folks have requested ability to change aspect.

**Comment by damianavila** [comment]
Superseded by #3059

**Pull request closed without merging**
