### PR TITLE
Don't attach `Tooltip` to DOM if not positioned

### LINKED ISSUE #13894: `Tooltip` is initially attached to the DOM when it shouldn't be
See bottom left corner:

image

(from [color_scatter](https://github.com/bokeh/bokeh/blob/branch-3.5/examples/basic/scatters/color_scatter.py) example).

Goes away after the first hover.

### PR DESCRIPTION
**Pull request by mattpap**
fixes #13894

### CODE REVIEW

**Comment by mattpap** [comment]
There's no good way of testing this currently.

**Review by hoxbro — COMMENTED** [review]
Can you post the code used for testing this? Could not find it in the issue. 

As most of this PR (to me) looks like a refactor, it could be nice if you had a comment indicating this is the main change to fix the issue. I assume this is the `after_render` in `connect_signals` and updates in `_after_render` and `_after_resize`.

I assume the updated `.blf` file is showing the correct behavior, where it previously would show up in the 0,0 coordinate.

**Comment by mattpap** [comment]
Any example with hover tool would do. The one from the issue is `examples/basic/scatter/color_scatter.py`:
```py
import numpy as np

from bokeh.plotting import figure, show

N = 4000
x = np.random.random(size=N) * 100
y = np.random.random(size=N) * 100
radii = np.random.random(size=N) * 1.5
colors = np.array([(r, g, 150) for r, g in zip(50+2*x, 30+2*y)], dtype="uint8")

TOOLS="hover,crosshair,pan,wheel_zoom,zoom_in,zoom_out,box_zoom,undo,redo,reset,tap,save,box_select,poly_select,lasso_select,examine,help"

p = figure(tools=TOOLS)

p.circle(x, y, radius=radii,
         fill_color=colors, fill_alpha=0.6,
         line_color=None)

show(p)
```
Note that any movement on the canvas will make the problem disappear.

**Comment by mattpap** [comment]
> As most of this PR (to me) looks like a refactor, it could be nice if you had a comment indicating this is the main change to fix the issue. I assume this is the after_render in connect_signals and updates in _after_render and _after_resize.

Refactor only relates to changes to `TooltipView._anchor_to_align()`. Everything else is relevant, i.e. making sure is that `_reposition()` is called in `after_render()`, which makes sure `TooltipView.el` is removed from DOM if it was added there by `render_to()` and the tooltip isn't viable (no content, no position, etc.) and that it's called after resize, to make sure position is reflected after content changes (not necessarily by means of changing `content` property).

> I assume the updated .blf file is showing the correct behavior, where it previously would show up in the 0,0 coordinate.

The previous one didn't make sense. The current one looks suspiciously, but it's a side effect of adding `Tooltip` to the `body` and computing the `bbox` relative to the target of a tooltip. This is where negative positioning comes from.

**Comment by hoxbro** [comment]
> Refactor only relates to changes to `TooltipView._anchor_to_align().`

That is also what is causing the most line changes in this PR. I'm not saying you shouldn't refactor, but it would be nice to have left a comment about it in your first comment.

**Review by hoxbro — APPROVED** [review]

**Pull request merged**
