### PR TITLE
Move js_on_change() connections to connect_signals()

### LINKED ISSUE #6419: Restore events for "patch", "stream" and "do"
Previously, `js_on_event` etc. could accept string names of arbitrary Backbone events. This afforded a way for users to add callbacks to CDS `patch` and `stream` events as well as the `do` event when a toolbar button is clicked. When Backbone was removed, this capability was lost, breaking some users' code. Should add three explicit events:
```
Patching
Streaming
Do
```
to `bokeh.events` and have them trigger at the appropriate places on the JS side.

### PR DESCRIPTION
**Pull request by mattpap**
- [x] fix initialization order
- [ ] add tests for initialization order
- [x] add aliases for `streaming` and `patching`
- [x] add deprecation warning

fixes #6419

### CODE REVIEW

**Comment by mattpap** [comment]
@bryevdv, btw. this needs to be merged for 0.12.6.

**Comment by bryevdv** [comment]
I don't think it is mandatory, but I would like to see it go in if possible

**Comment by mattpap** [comment]
But this is a regression. At least what's already done should be merged, because this fixes `js_on_change()` to work with `streaming`, `patching` and `do`.

**Comment by bryevdv** [comment]
@mattpap Oh I see, I didn't realize that was already accomplished. I leave it to you: if you want to merge is as-is please go ahead, just make sure to create follow up issues. But it seems isolated and small so I am happy to merge it later today or early tomorrow

**Comment by bryevdv** [comment]
@mattpap do you plan to add to this PR?

**Comment by mattpap** [comment]
@bryevdv, yes, I will update it soon.

**Comment by bryevdv** [comment]
OK well FYI we would like to cut a last rc in the next 3 hours.

**Comment by mattpap** [comment]
@bryevdv, this is ready.

**Pull request merged**
