### PR TITLE
Fix painting of border/background visuals in SVG backend

### LINKED ISSUE #13362: [BUG] Inconsistent handling of background and border fill alpha
### Software versions

Python version      :  3.10.11 | packaged by conda-forge | (main, May 10 2023, 19:01:19) [Clang 14.0.6 ]
IPython version     :  8.14.0
Tornado version     :  6.3.2
Bokeh version       :  3.3.0.dev1+43.g310cb2cb
BokehJS static path :  /Users/iant/github/bokeh/src/bokeh/server/static
node.js version     :  v18.15.0
npm version         :  9.5.0
Operating system    :  macOS-13.4-arm64-arm-64bit

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

If you use fractional figure `background_fill_alpha` and `border_fill_alpha` I expect both canvas and SVG backends to look similar.

### Observed behavior

Color mixing is different for canvas and SVG backends.

### Example code

```Python
from bokeh.models import GlobalInlineStyleSheet
from bokeh.plotting import figure, row, show

stylesheet = GlobalInlineStyleSheet(css=".bk-Row { background-color: lightgreen; }")

ps = []
for backend in ('canvas', 'svg'):
    p = figure(
        width=250, height=250, title=backend, output_backend=backend,
        stylesheets=[stylesheet]
    )
    p.line(x=[0, 1], y=[0, 1], line_color="black", line_width=8)
    ps.append(p)

    p.background_fill_alpha = 0.25
    p.background_fill_color = "red"
    p.border_fill_alpha = 0.25
    p.border_fill_color = "blue"

show(row(ps))
```

### Stack traceback or browser console output

_No response_

### Screenshots

Screenshot 2023-09-04 at 11 51 46

### PR DESCRIPTION
**Pull request by mattpap**
image

fixes #13362

### CODE REVIEW

**Comment by mattpap** [comment]
> `images differ by 1px (0.00%)`

All of them (1px per plot).

**Comment by ianthomas23** [comment]
I've confirmed it fixes the issue, but I'm not sure it is worth the churn of so many baseline image changes :flushed:

**Comment by mattpap** [comment]
It definitely doesn't make sense to merge this in this state. I need to either figure out where this difference is coming from or combine this with some other large changes (e.g. switching to newer chromium for testing).

**Comment by mattpap** [comment]
Originally this PR required update of ~70% of baselines, thus I included also upgrade of Chromium, which on its own requires update ~50% of baselines.

In the context of PR #13453, this is size contribution of this PR:
```
$ git push -f
(...)
Writing objects: 100% (1187/1187), 21.14 MiB | 4.82 MiB/s, done.
(...)
```

**Review by ianthomas23 — APPROVED** [review]
I am happy to proceed with this.

**Pull request merged**
