### PR TITLE
Simplify shapefile (.shp) w/ Bokeh Server + GeoPandas

### PR DESCRIPTION
**Pull request by brendancol**
This example demonstrates consuming a shapefile and displaying it via a `GeoJSONDataSource`. Couple of things to note (which are also in README.md):

- installing geopandas can be a pain. Fortunately there is a conda channel with geopandas:
`conda install -c ioos geopandas` (this should be copied the bokeh channel)
- to get example shapefile...`import bokeh.sampledata; bokeh.sampledata.download()`

remaining items:
- [ ] move geopandas to bokeh channel: `anaconda copy ioos/geopandas/0.1.1  --to-owner bokeh`

### CODE REVIEW

**Comment by birdsarah** [comment]
waaahhhhh :D :D :D 

I know this is a WIP but I couldn't help myself and got it running locally - this is soooo cool.

**Comment by brendancol** [comment]
Yes so first thing I need is to remove the hardcoded shapefile path and add my shapefile to sampledata...coming soon.

**Comment by birdsarah** [comment]
@brendancol - my jumping in too early two cents:

1) mention the geopandas install in the README - when you `bokeh serve` something the import error doesn't work as you'd expect
2) i'm concerned that the geopandas install is non trivial - i had to use my "geo" env that if you recall we had some fun setting up previously.

Would definitely recommend testing this on clean env and clean machine and documented what is tested to work. I think it's worth it though - this is a really nice example of pulling a bunch of libraries together to do something non-trivial.

Also fwiw - I don't think you need the save button feature.

**Comment by brendancol** [comment]
@birdsarah 

> 1) mention the geopandas install in the README - when you bokeh serve something the import error doesn't work as you'd expect

Yes definitely need that in the README.  Regarding this import try/except, Im think maybe of adding a `Paragraph` instance to curdoc to display message in the browser

>  i'm concerned that the geopandas install is non trivial - i had to use my "geo" env that if you recall we had some fun setting up previously.

I talked to @hsparra about the install and he's going to serve as an impartial user to test the pain/lack-there-of for installing Geopandas.

> Also fwiw - I don't think you need the save button feature.

So not preserving shared boundaries is a bit lame, but I wanted this example to demonstration both reading and writing of shapefiles.

**Comment by brendancol** [comment]
https://github.com/geopandas/geopandas/issues/237

**Comment by hsparra** [comment]
Regarding this, I was able to run

conda install -c ioos geopandas

on a clean environment and the install went smoothly. I was then able tot
do "import geopandas" with no errors.

**Comment by bryevdv** [comment]
Resolved to locate in separate project

**Pull request closed without merging**
