### PR TITLE
Plot can be resized with more control over whether to use width and/or height

### LINKED ISSUE #2949: Allow plots to be responsive also for available height
continues #2678 

In the [flexx+ bokeh example](https://dl.dropboxusercontent.com/u/1463853/flexx-bokeh.html) that I made earlier, the plot would nicely scale when the available width got smaller, but not when the height did.

### PR DESCRIPTION
**Pull request by almarklein**
issues: closes #2949

This PR allows more control for resizing, allowing Flexx or Bokeh apps to resize the plot any way it likes.

I experimented a bit with automatically determining whether the height should also be taken into account, but this only got messy, so I went with a more explicit approach: expose a method `resize_width_height(use_width, use_height)`. This should not change the current behaviour of Bokeh plots by themselves.

So now, Flexx resizes using both width and height, unless the parent widget has a scrollbar in horizontal/vertical direction. See the [new example](https://dl.dropboxusercontent.com/u/1463853/flexx-bokeh2.html).

cc @birdsarah, @sccolbert

### CODE REVIEW

**Comment by almarklein** [comment]
Why is this failing? I already restarted Travis so this seems not to be a glitch. I don't understand the fail reported by Travis.

**Comment by almarklein** [comment]
Merged with master and tests pass now. This is ready AFAIC.

**Comment by bryevdv** [comment]
Not sure if it matters for Bokeh or Flexx, but the vertical resize does not seem to work. It initially resizes smaller, but then snaps back to a "too big" size

screen shot 2015-11-01 at 7 46 55 pm

**Comment by almarklein** [comment]
@bryevdv How did you tests that? The vertical resizing is not actually used yet in Bokeh itself. This PR basically provides a function to allow doing that, which is used in Flexx, and we should probably use it for some layouts in "Bokeh apps" as well.

**Comment by almarklein** [comment]
Oh, I now see you're running the example. (Github/my browser did not let me show the full extend of that screenshot, but my mail client does.)

Mmm, it seems to work when dragging splitters inside the app, but when resizing the browser window it sometimes snaps back. Looking into it ...

**Comment by almarklein** [comment]
@bryevdv Fixed. This was a bug in Flexx: Both Bokeh and Flexx tried to resize the plot. (https://github.com/zoofIO/flexx/commit/a9abb2d9b01c57b2bad6f7222e7513ea54272401)

**Comment by birdsarah** [comment]
i'm sorry i'm late to the party here, but:

* this adds loads of complexity with no tests
* i'm not seeing a change in functionality. are you expecting that other libraries will manually call resize?

can you elaborate @almarklein

**Comment by almarklein** [comment]
Indeed, there is no change in functionality, but it provides a way for code that embeds bokeh plots to control resize behavior. I suppose Bokeh itself will use it at some point when we get more of the Phosphor layouts in.

You're right that this should be tested. Working on it.

**Comment by almarklein** [comment]
#3079

**Pull request merged**
