### PR TITLE
Allow None/null in GlyphRenderer.{non}selection_glyph

### LINKED ISSUE #10913: [BUG] Error while testing 2.3.0dev13 with Dask
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh 2.3.0dev13, dask 2021.2.0, python 3.8, jupyter lab

#### Description of expected behavior and the observed behavior

The dashboard link should open a blank dashboard, it currently throws a 500 - Internal Server Error.

#### Complete, minimal, self-contained example code that reproduces the issue

Start a Dask Client and navigate to dashboard

```
from dask.distributed import Client
client = Client(n_workers=4)
client

```

#### Stack traceback and/or browser JavaScript console output

N/A

#### Screenshots or screencasts of the bug in action

Screenshot 2021-02-17 at 11 11 53 PM

cc @bryevdv @mattpap

### PR DESCRIPTION
**Pull request by mattpap**
fixes #10913

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap could this also potentially be handled with a `.accepts` that converts `None` to `"auto"`? It could also issue a deprecation warning not to set None.

**Comment by philippjfr** [comment]
Does None and auto have the same semantics? I assumed auto basically just mirrored .glyph, while I assumed None hides it entirely (I don't actually know though).

**Comment by mattpap** [comment]
Here's the logic:
https://github.com/bokeh/bokeh/blob/e6fed49a7fe5a576768989ab4da32a2042af3a93/bokehjs/src/lib/models/renderers/glyph_renderer.ts#L79-L91
`None` means use the base glyph as-is, whereas `"auto"` means use base glyph with predefined {non-}selection styling.

**Comment by bryevdv** [comment]
Fair enough, widening to nullable seems appropriate

**Pull request merged**
