### PR TITLE
added layouts to main.coffee

### PR DESCRIPTION
**Pull request by brendancol**
Related Issue: https://github.com/bokeh/bokeh/issues/3339

This PR adds layouts to `coffee/main.coffee` so they can be extended in User Defined Models.

### CODE REVIEW

**Comment by bryevdv** [comment]
LGTM, +1 to this, wanting to have only plots (no widgets), but also put them in a layout is a common use-case, this is a better division until we can make things more fine-grained.

**Comment by mattpap** [comment]
Obviously this doesn't fix anything, although tests will most likely pass.

**Comment by mattpap** [comment]
We can make layouts a special case, but then they should be moved to bokeh core.

**Comment by havocp** [comment]
If you do this I think you have to remove them from widget/main.coffee, or people will have two copies of these things when they include both bokeh.js and bokeh-widgets.js, right?

Removing them from widget/main.coffee should cause the unit test "have all Widget view models from Python in widget locations registry" in test_defaults.coffee to fail.

Currently the test wants to see a model in widget/main.coffee if the Python version of the model is a subtype of Widget. These links are to relevant code to follow how this happens:
https://github.com/bokeh/bokeh/blob/c218c1c9faa3e2a88c5433d48b3e469a902cfaae/bokehjs/gulp/tasks/generate_defaults.py#L65-L71
https://github.com/bokeh/bokeh/blob/c218c1c9faa3e2a88c5433d48b3e469a902cfaae/bokehjs/gulp/tasks/generate_defaults.py#L106-L107
https://github.com/bokeh/bokeh/blob/c218c1c9faa3e2a88c5433d48b3e469a902cfaae/bokehjs/test/test_common/test_defaults.coffee#L6
https://github.com/bokeh/bokeh/blob/c218c1c9faa3e2a88c5433d48b3e469a902cfaae/bokehjs/test/test_common/test_defaults.coffee#L84

Also, embed.py in Python decides whether to include bokeh-widgets.js in generated HTML based on whether any subtypes of Widget are in the Document. See:
https://github.com/bokeh/bokeh/blob/c218c1c9faa3e2a88c5433d48b3e469a902cfaae/bokeh/embed.py#L234-L243
I guess the failure mode here is simply that we'd include bokeh-widgets.js unnecessarily, but if we're going to pull in bokeh-widgets.js if we have any layouts, why put them in the core?

One way to fix both of these could be to create some sort of marker class in Python like CoreWidget, and have these layouts subtype CoreWidget. Then base the embed.py decision and the generate_defaults.py lists on things that subtype Widget but NOT CoreWidget.

There are certainly other ways to do it but bottom line the places that currently key off the Widget class will need to be updated.

**Comment by bryevdv** [comment]
In case it wasn't clear my proposal was to *remove* them from `widgets.coffee` entirely and *move* them to `main.coffee`, not that they should be in both.

**Comment by brendancol** [comment]
@havocp so i removed layouts from `widget/main.coffee`.  Not sure if that will do it, or whether this refactor should wait.  Basically I'm refactoring the crossfilter example and was extending widgets. For my purposes, I should also be able to extend `Model` and `HasParent` to achieve the same end.

**Comment by havocp** [comment]
generate_defaults.py and embed.py have to be fixed up afaik - I'd expect gulp tests fail?

**Comment by mattpap** [comment]
>  or people will have two copies of these things when they include both bokeh.js and bokeh-widgets.js, right?

That should not happen, because everything resolved in `bokeh.js` is removed from `bokeh-widgets.js`. However, to make future development sane, we must provide clean separation between bundles.

**Comment by mattpap** [comment]
>  Not sure if that will do it, or whether this refactor should wait.

No it won't. Hovoc listed the steps, more or less. tl;dr: you have to move entries from `widget/main.coffee` to `common/base.coffee`, update defaults accordingly and make sure layouts don't inherit from `Widget` (otherwise entire `bokeh-widgets.js` will be included). Preferably, you would need to add a new abstract base class to indicate a "core widget".

Whatever you do in this direction won't fix the underlying bug, where wrong `require()` is used in custom models that depend on `bokeh-widgets.js`.

I'm currently working on a very different implementation of custom models, where the above problem doesn't exist, but right now I can't give an ETA.

**Comment by brendancol** [comment]
@mattpap Ok yeah that sounds sounds clear.  I guess my feeling is that this PR should be `rejected` and that I should continue crossfilter work in a sandbox and then merge it when the different custom model implementation is ready.

**Comment by bryevdv** [comment]
>  I guess my feeling is that this PR should be rejected and that I should continue crossfilter work in a sandbox and then merge it when the different custom model implementation is ready.

Let's pause the crossfilter work for now, unless there is simple path that does not require Bokeh layout widgets at all.

**Comment by mattpap** [comment]
I still may be able to fix the underlying issue, but definitively not today.

**Comment by bryevdv** [comment]
@brendancol @mattpap this PR is to be closed then?

**Comment by brendancol** [comment]
Closing PR but issue #3339 remains

**Pull request closed without merging**
