### PR TITLE
Make the default hover tooltip work for Donut charts.

### PR DESCRIPTION
**Pull request by jonc125**
Also fix a typo in the documentation for these options.

Related to issue #3621, though doesn't address every aspect discussed there.

### CODE REVIEW

**Comment by bryevdv** [comment]
@jonc125 appreciate the PR, can you add some test code and screenshots to this PR? It will make it much quicker to evaluate (in the middle of a release crush this week)

**Comment by bryevdv** [comment]
@jonc125 can you provide a script you used to test with and a screen shot of the output?

**Comment by jonc125** [comment]
Sorry, been busy over the last week and didn't have a chance to do this. I used the example in the Donut docs, so you can see the pre-PR behaviour at http://bokeh.pydata.org/en/latest/docs/reference/charts.html#donut - no hover tooltips are shown there.

In contrast, with the PR you do see tooltips, e.g.:

donut_with_hover_patch

**Comment by bryevdv** [comment]
Brilliant, thanks for the PR!

**Comment by bryevdv** [comment]
Since this does not address all of #3621, making it a standalone "issue PR"

**Pull request merged**
