### PR TITLE
Changed docstring in stocks.py and us_marriages_divorces.py

### LINKED ISSUE #9329: Document bokeh.sampledata
The Reference Guide page is nearly empty. The `bokeh.sampledata` module should automatically include relevant submodules in its main docsring, and all the submodule docstrings should be updated/completed to be useful, e.g. explain what the module contains, or show example data, or link/include examples that use the data.

### PR DESCRIPTION
**Pull request by gowrijp**
- [ ] issues: addresses #9329 
- [ ] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by bryevdv** [comment]
Hi @gowrijp thanks for the PR. A couple of comments:

* I think the work "basic" in "basic structure of the data" should be removed. To me it implies uncertainty or imprecision. We are providing users with the *exact* structure of the data. 

*  I think the right hand side descriptions, e.g. "list of int" are also a  bit misleading. This is a Pandas DataFrame, so all the columns are Pandas series, and not plain Python lists. The types are more specific. E.g. he output of `dtypes` is this:
   ```
   In [7]: us_marriages_divorces.data.dtypes
   Out[7]:
   Year                    int64
   Marriages             float64
   Divorces              float64
   Population              int64
   Marriages_per_1000    float64
   Divorces_per_1000     float64
   dtype: object
   ```
   For DataFrames, maybe we can just start a convention of providing the output of `df.dtypes` in all cases so that the format and information is always presented in a consistent and precise way. 

* It might also be nice to include the output of `fd.head()` so that users can see an actual representative sample:
   ```
   In [8]: us_marriages_divorces.data.head()
   Out[8]:
      Year  Marriages  Divorces  Population  Marriages_per_1000  Divorces_per_1000
   0  1867   357000.0   10000.0    36970000                 9.7                0.3
   1  1868   345000.0   10000.0    37885000                 9.1                0.3
   2  1869   348000.0   11000.0    38870000                 9.0                0.3
   3  1870   352000.0   11000.0    39905000                 8.8                0.3
   4  1871   359000.0   12000.0    41010000                 8.8                0.3
   ```

Lastly, the main goal is to get this information automatically showing up in the reference guide for [`bokeh.sampledata`](https://docs.bokeh.org/en/latest/docs/reference/sampledata.html). To that end, I think we will want to make use of the Sphinx `data` directive. That will make the module docstring look more like this:

```

.. data:: data

    A data frame with the following structure:

    < dtypes info >

    With a representative sample:

    < df.head output >

    etc etc

```

Let me know if you have questions about these comments.

**Comment by gowrijp** [comment]
I read a bit about numpy style Python docstring and rewrote the part with what I understood from it.  Please let me know if this format is alright and about any further improvements required.
`#-----------------------------------------------------------------------------
# Copyright (c) 2012 - 2020, Anaconda, Inc., and Bokeh Contributors.
# All rights reserved.
#
# The full license is in the file LICENSE.txt, distributed with this software.
#-----------------------------------------------------------------------------
# -*- coding: utf-8 -*-
""" Provide U.S. marriage and divorce statistics between 1867 and 2011

Data from the CDC's National Center for Health Statistics (NHCS) database (http://www.cdc.gov/nchs/)

Data organized by Randal S. Olson (http://www.randalolson.com)

Data Structure
--------------

The entire data is available as a DataFrame on an attribute on the module - us_marriages_divorces.data

Datatype info:

>>> us_marriages_divorces.data.dtypes
Year                    int64
Marriages             float64
Divorces              float64
Population              int64
Marriages_per_1000    float64
Divorces_per_1000     float64
dtype: object

us_marriages_divorces.head output

>>> us_marriages_divorces.data.head()
   Year  Marriages  Divorces  Population  Marriages_per_1000  Divorces_per_1000
0  1867   357000.0   10000.0    36970000                 9.7                0.3
1  1868   345000.0   10000.0    37885000                 9.1                0.3
2  1869   348000.0   11000.0    38870000                 9.0                0.3
3  1870   352000.0   11000.0    39905000                 8.8                0.3
4  1871   359000.0   12000.0    41010000                 8.8                0.3
"""
`

**Comment by gowrijp** [comment]
I've added numpy style python docstring with the appropriate changes as you suggested before. Please do take a look and suggest further changes/improvements required.

**Comment by bryevdv** [comment]
@gowrijp can you merge or rebase on master? The lint error that is due to a new release of flake8 is resolved on master. 

Also, are you able to build the docs? The primary motivation for this issue was to get things in to the reference guide so I would suggest iterating on this first update to get it as good as possible so it can serve as a model for all the others. I do think we will want to use the Sphinx `.. data::` directive as mentioned above

**Comment by bryevdv** [comment]
Another thing we could consider is to make some new small Sphinx directives similar to what @santos22 did in #10075 that would actually render nice HTML tables to summarize dataframes

**Comment by bryevdv** [comment]
I'm going to go ahead and close this for inactivity. Also after some thought, I would really like to take a comprehensive approach to documenting the sample data all at once in a uniform way with any necessary tool support to make it really good.

**Pull request closed without merging**
