### PR TITLE
Fix #5524: fix --num-procs following Bokeh server refactor

### LINKED ISSUE #5524: --num-procs broken
Some of the recent Bokeh server refactoring is not compatible with `--num-procs`:

```
../../bin/bokeh serve  --num-procs=4 --show gapminder                                         (master)
2016-12-09 08:46:05,896 Starting Bokeh server version 0.12.4dev7-55-g9210f28
ERROR:Cannot run in multiple processes: IOLoop instance has already been initialized. You cannot call IOLoop.instance() before calling start_processes()
```

### PR DESCRIPTION
**Pull request by pitrou**
I gave up writing a test for this because it appears Tornado's bult-in process-forking is fragile and can leave processes around: https://github.com/tornadoweb/tornado/issues/1912

### CODE REVIEW

**Comment by pitrou** [comment]
Unrelated, but I'm unsure how "document locking" works in the face of support for `--num-procs`. @havocp

**Comment by pitrou** [comment]
Unrelated failure in https://travis-ci.org/bokeh/bokeh/jobs/183289071

**Comment by bryevdv** [comment]
restarted the tailed build, thanks for the Tornado issue, someone in the community reported this problem as well.

**Comment by havocp** [comment]
Each websocket (and thus each session) should be pinned to a proc if things work how I think they do. Shouldn't be a need for cross-process locking since the lock is really on the session.

**Comment by pitrou** [comment]
I see. Yes, using websockets should probably pin a given connection to a specific process.

**Comment by bryevdv** [comment]
@pitrou just flake8 remaining
```
E       AssertionError: Flake8 issues:
E         bokeh/command/subcommands/tests/test_serve.py:9:1: F401 'time' imported but unused
E         bokeh/command/subcommands/tests/test_serve.py:212:5: F841 local variable 'cmd' is assigned to but never used
E         
```

**Comment by pitrou** [comment]
Yes, I've just pushed the fixes for that.

**Comment by bryevdv** [comment]
Thanks @pitrou

**Pull request merged**
