### PR TITLE
register "freehand_draw" as alias

### LINKED ISSUE #10912: [BUG] 'freehand_draw' is not in name space for tools
#### software version
bokeh v.2.2.3

#### Description
I tried the `"FreehandDrawTool"` which is working fine if it is imported as a model. But right now it is not possible to activate the tool by the name "freehand_draw" because the name is not in the name space for tools. The two lines below raise a ValueError saying `unexpected tool name 'freehand_draw'`.
```
from bokeh.plotting import figure
p = figure(tools="freehand_draw")
```

### PR DESCRIPTION
**Pull request by mosc9575**
- [ ] issues: fixes #10912

### CODE REVIEW

**Comment by bryevdv** [comment]
Thanks for the PR @mosc9575 just FYI to push new updates, it's not necessary to close the PR and open a new one. You can add/commit/push new changes on the existing branch, and this PR will update to reflect those changes automatically.

**Comment by bryevdv** [comment]
Just a heads up (since the build logs are sometimes a paint to look through) the JS linter error is about some trailing whitespace:
> [19:39:30] /home/runner/work/bokeh/bokeh/bokehjs/src/lib/models/tools/edit/freehand_draw_tool.ts
[19:39:30]   105:1  error  Trailing spaces not allowed  no-trailing-spaces

**Comment by mosc9575** [comment]
Thanks for your kind support @bryevdv. I have to figure out how this works. I was looking for the option to update but I didn't find it.

**Comment by bryevdv** [comment]
@mosc9575 out pleasure, we are happy to help answer any questions. FYI the current single test failure appears to be unrelated/spurious so just ignore it for now. 

cc @mattpap any idea about that one MacOS image diff failure?

**Comment by mattpap** [comment]
> any idea about that one MacOS image diff failure?

Most likely it's spurious, but may require increasing pixel threshold in future.

**Comment by bryevdv** [comment]
@mosc9575 did you intend to complete this PR? The alias also needs to be added on the python side as described in https://github.com/bokeh/bokeh/issues/10912#issuecomment-780754592

**Comment by mosc9575** [comment]
I made a mistakt and opend a new PR #10988. I knew this is not best prectice. I will do better in future.

**Review by bryevdv — APPROVED** [review]

**Pull request merged**
