### PR TITLE
Ensure provided and expected signature strings have same encoding

### LINKED ISSUE #6653: TypeError: 'unicode' does not have the buffer interface
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh 0.12.6
python 2.7.12
64 bit Ubuntu 16.04
Chrome browser

#### Description of expected behavior and the observed behavior

I get `500: Internal Server Error` when I try to use signed sessions with bokeh. 

#### Complete, minimal, self-contained example code that reproduces the issue

I use `sliders.py` example from Bokeh Gallery. I use the following to run the app and generate the session id:

Run the app:
```bash
export BOKEH_SECRET_KEY=KKXYhtUJmQ5f8LiQJdeUGOF4HIeTzf5zOBZmlxrXtF6D
export BOKEH_SIGN_SESSIONS=True
bokeh serve sliders.py --session-ids external-signed
```

Generate session id:
```bash 
export BOKEH_SECRET_KEY=KKXYhtUJmQ5f8LiQJdeUGOF4HIeTzf5zOBZmlxrXtF6D
export BOKEH_SIGN_SESSIONS=True
python -c "from bokeh.util.session_id import generate_session_id; print(generate_session_id())"
```

Example url to access app:
http://localhost:5006/sliders?bokeh-session-id=4RJKVrnFVe60gB5urh9sE3jUnSGDkJAfCwvoaDsoMB8f-W6QAfyDoxORtN7mb6DHAzftAhpfnxVdzC-6gIT13uV0

#### Stack traceback and/or browser JavaScript console output

JavaScript console output:
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

Bokeh traceback:
```
2017-07-21 00:23:58,161 Uncaught exception GET /sliders?bokeh-session-id=4RJKVrnFVe60gB5urh9sE3jUnSGDkJAfCwvoaDsoMB8f-W6QAfyDoxORtN7mb6DHAzftAhpfnxVdzC-6gIT13uV0 (::1)
HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/sliders?bokeh-session-id=4RJKVrnFVe60gB5urh9sE3jUnSGDkJAfCwvoaDsoMB8f-W6QAfyDoxORtN7mb6DHAzftAhpfnxVdzC-6gIT13uV0', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'en-US,en;q=0.8,ru;q=0.6,de;q=0.4', 'Accept-Encoding': 'gzip, deflate, br', 'Host': 'localhost:5006', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/59.0.3071.109 Chrome/59.0.3071.109 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': '_xsrf=2|4ab25a11|f7d3fbdf1fab4d2b01135d63518a4f9a|1498856594; username-localhost-8888="2|1:0|10:1499014969|23:username-localhost-8888|44:ODVmNmU2NjIwYjUwNDlhYzk2MzY4OWQ5NDU2ZTExYjU=|3a908d5ba83bca558deae2665732f340eeef5ce69a2763c6cef367fd892e22b7"', 'Upgrade-Insecure-Requests': '1'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1469, in _execute
    result = yield result
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/server/views/doc_handler.py", line 27, in get
    session = yield self.get_session()
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/server/views/session_handler.py", line 36, in get_session
    signed=self.application.sign_sessions):
  File "/usr/local/lib/python2.7/dist-packages/bokeh/util/session_id.py", line 156, in check_session_id_signature
    return hmac.compare_digest(expected_signature, provided_signature)
TypeError: 'unicode' does not have the buffer interface
```

#### Screenshots or screencasts of the bug in action

eg

### PR DESCRIPTION
**Pull request by iaroslav-ai**
Fixes #6653

### CODE REVIEW

**Comment by bryevdv** [comment]
Thanks @iaroslav-ai this saves alot of overhead. If you have experience with unit-testing, adding a unit test for this here:

https://github.com/iaroslav-ai/bokeh/blob/master/bokeh/util/tests/test_session_id.py

would round this out. Otherwise I can push a test to your PR branch early next week.

**Comment by iaroslav-ai** [comment]
Added a unit test, which breaks with old session id check

**Comment by bryevdv** [comment]
@iaroslav-ai brilliant, should be able to get this merged in the next day or two, thanks!

**Comment by iaroslav-ai** [comment]
no problem :)

**Comment by bryevdv** [comment]
@iaroslav-ai two small test issues. First is a py2/py3 one:
```
>       self.assertTrue(check_session_id_signature(session_id.decode('utf-8'), secret_key="abc", signed=True))
E       AttributeError: 'str' object has no attribute 'decode'
```

The solution I think is to use the `bokeh.util.string.decode_utf8` function here which will handle the python version difference re: `.decode`

The second is just a linter issue, there is trailing whitespace on line 97 of the test file that just needs to be deleted.

**Comment by iaroslav-ai** [comment]
Seems to be some python 2 specific issue. Do you normally run the tests on python 3?

**Comment by iaroslav-ai** [comment]
As you suggest, `decode_utf8` does the job. Should work now on py2 and py3.

**Comment by bryevdv** [comment]
Thanks @iaroslav-ai !

**Pull request merged**
