### PR TITLE
Fixed some typos and changed wording for better tone

### PR DESCRIPTION
**Pull request by ArchaeotheriumSapienter**
Changed some typographical errors in some Python files and changed the word "some things" to more specific wordings for a more specific and better tone of communication.

### CODE REVIEW

**Comment by ArchaeotheriumSapienter** [comment]
It seems that the previous commit is still here. But the good news is I think I rebased this branch successfully than last time. I just need to force push for it to work :)

**Comment by mattpap** [comment]
I fixed your branch, so that there's only one commit there. You will still need to fix your fork of bokeh and reset local `branch-3.0`, so that it doesn't contain unrelated commits (assuming you will be submitting further PRs).

**Comment by ArchaeotheriumSapienter** [comment]
Thank you so much! I've been having a hard time with rebasing this one, but I'll fix my local repo :)

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
Thanks @ArchaeotheriumSapienter !

**Comment by g-parki** [comment]
Congrats on your first Bokeh PR @ArchaeotheriumSapienter! 🎉

**Comment by ArchaeotheriumSapienter** [comment]
Thank you so much, guys! Sorry for the rebase confusion @mattpap, hope it didn't take too much of your time :)

**Pull request merged**
