### PR TITLE
REF: Rename ci scripts, use dot (.) instead of colon (:) #8089

### LINKED ISSUE #8089: ci scripts with colon in filenames are not valid on windows
Replace with dot `.` instead.

### PR DESCRIPTION
**Pull request by pratapvardhan**
Rename ci scripts, use dot (.) instead of colon (:)

- [x] issues: fixes #8089

### CODE REVIEW

**Comment by bryevdv** [comment]
Not sure what the issue is offhand, the first build stage is failing with this:
```
/home/travis/.travis/job_stages: line 78: scripts/ci/install.build: Permission denied
```
which causes all subsequent stages to be aborted.

**Comment by mattpap** [comment]
> Permission denied

Executable bits were removed from scripts' permissions.

**Comment by bryevdv** [comment]
@pratapvardhan hopefully this will allow you to add the `+x` on windows:

https://www.jerriepelser.com/blog/execute-permissions-with-git/

**Comment by bryevdv** [comment]
Build stages seem to be proceeding now

**Comment by bryevdv** [comment]
@pratapvardhan it looks like a few of the files did not get updated back still:

screen shot 2018-07-20 at 08 20 01

looks like also `install.codebase` and `install.downtream`

**Comment by pratapvardhan** [comment]
@bryevdv -- 46cf7d2 did change the permissions for the 18 files, the diff seems to be misleading.. First build seems to have passed, I'll wait till the job finishes and take a lot, if something's amiss.

**Comment by bryevdv** [comment]
The diff is definitely misleading, but all the build stages and jobs have passed, so I will merge this now, thanks @pratapvardhan

**Pull request merged**
