### PR TITLE
Remove 'x' and 'y' aliases from Dimension enumeration

### LINKED ISSUE #5223: Span annotation rejects `x` or `y` for `dimension` argument
The `Span` annotation [documentation](http://bokeh.pydata.org/en/latest/docs/reference/models/annotations.html#bokeh.models.annotations.Span) lists four possible values for argument `dimension`

```
attr dimension

     property type: dimension:Enum(‘width’, ‘height’, ‘x’, ‘y’)

     The direction of the span.
```

But when I attempt to use `x` or `y` errors like this appear in the notebook:

```
Javascript error adding output!
Error: Dimension property 'dimension' given invalid value: x
See your browser Javascript console for more details.
```

And the console says things like:

```
Error: Dimension property 'dimension' given invalid value: x
  at e.V.n.validate (https://cdn.pydata.org/bokeh/release/bokeh-0.12.2.min.js:2:28698)
  at e._init (https://cdn.pydata.org/bokeh/release/bokeh-0.12.2.min.js:2:28310)
  at e.update (https://cdn.pydata.org/bokeh/release/bokeh-0.12.2.min.js:2:26502)
  at e.attach_document (https://cdn.pydata.org/bokeh/release/bokeh-0.12.2.min.js:2:17044)
  at t._recompute_all_models (https://cdn.pydata.org/bokeh/release/bokeh-0.12.2.min.js:3:21235)
  at t._pop_all_models_freeze (https://cdn.pydata.org/bokeh/release/bokeh-0.12.2.min.js:3:20574)
  at t.add_root (https://cdn.pydata.org/bokeh/release/bokeh-0.12.2.min.js:3:22140)
  at Function.t.from_json (https://cdn.pydata.org/bokeh/release/bokeh-0.12.2.min.js:3:27716)
  at Object.j [as embed_items] (https://cdn.pydata.org/bokeh/release/bokeh-0.12.2.min.js:4:1986)
  at HTMLDocument.eval (<anonymous>:94:25)
  at u (https://cdn.pydata.org/bokeh/release/bokeh-0.12.2.min.js:64:22570)
  at Object.add [as done] (https://cdn.pydata.org/bokeh/release/bokeh-0.12.2.min.js:64:22872)
  at st.fn.ready (https://cdn.pydata.org/bokeh/release/bokeh-0.12.2.min.js:64:24955)
  at st.fn.init (https://cdn.pydata.org/bokeh/release/bokeh-0.12.2.min.js:64:20461)
  at Object.st [as $] (https://cdn.pydata.org/bokeh/release/bokeh-0.12.2.min.js:54:12233)
  at Array.inline_js (<anonymous>:90:15)
  at run_inline_js (<anonymous>:105:23)
  at eval (<anonymous>:126:9)
  at eval (<anonymous>:45:67)
  at Array.forEach (native)
  at run_callbacks (<anonymous>:45:38)
  at load_libs (<anonymous>:57:9)
  at eval (<anonymous>:124:7)
  at eval (<anonymous>:129:4)
  at Function.globalEval (http://localhost:8888/static/notebook/js/main.min.js?v=dda91b55a04855a1c133b176c7a48905:87:4231)
  at x.domManip (http://localhost:8888/static/notebook/js/main.min.js?v=dda91b55a04855a1c133b176c7a48905:88:21391)
  at x.append (http://localhost:8888/static/notebook/js/main.min.js?v=dda91b55a04855a1c133b176c7a48905:88:18985)
  at OutputArea._safe_append (http://localhost:8888/static/notebook/js/main.min.js?v=dda91b55a04855a1c133b176c7a48905:20237:26)
  at OutputArea.append_display_data (http://localhost:8888/static/notebook/js/main.min.js?v=dda91b55a04855a1c133b176c7a48905:20358:18)
  at OutputArea.append_output (http://localhost:8888/static/notebook/js/main.min.js?v=dda91b55a04855a1c133b176c7a48905:20143:18)
  at OutputArea.handle_output (http://localhost:8888/static/notebook/js/main.min.js?v=dda91b55a04855a1c133b176c7a48905:20057:14)
  at output (http://localhost:8888/static/notebook/js/main.min.js?v=dda91b55a04855a1c133b176c7a48905:21698:52)
  at Kernel._handle_output_message (http://localhost:8888/static/notebook/js/main.min.js?v=dda91b55a04855a1c133b176c7a48905:23316:13)
  at i (http://localhost:8888/static/notebook/js/main.min.js?v=dda91b55a04855a1c133b176c7a48905:87:5488)
  at Kernel._handle_iopub_message (http://localhost:8888/static/notebook/js/main.min.js?v=dda91b55a04855a1c133b176c7a48905:23343:20)
  at Kernel._finish_ws_message (http://localhost:8888/static/notebook/js/main.min.js?v=dda91b55a04855a1c133b176c7a48905:23180:29)
  at http://localhost:8888/static/notebook/js/main.min.js?v=dda91b55a04855a1c133b176c7a48905:23171:44
```

This is using bokeh 0.12.2 with Anaconda 4.1.0 (Python 3.5) on Windows 7 with Chromium 53.0.2785.113 (64-bit)

### PR DESCRIPTION
**Pull request by mattpap**
fixes #5223

### CODE REVIEW

**Comment by canavandl** [comment]
we'll have to remove/deprecate the python enum values too: https://github.com/bokeh/bokeh/blob/master/bokeh/core/enums.py#L109

**Comment by canavandl** [comment]
do we need to add a deprecation or did this the x and y dimension never work anywhere?

**Comment by mattpap** [comment]
Actually we should go further. `Dimension` enumeration is used (most of the time) in `List(Enum(Dimension))` properties. This is cumbersome, because the only possibilities are either `width`, or `height` or both (so nonexistent `width_height`, which is the default). I presume empty list, so no dimensions, is technically possible, but doesn't make sense (e.g. pan in no dimension means it is disabled, but that's a pretty bad way of expressing this fact). @bryevdv?

**Comment by mattpap** [comment]
@bryevdv, I went ahead and made appropriate changes. Added proper deprecation as well. After this change, a lot of code looks more intuitive.

**Comment by bryevdv** [comment]
Agreed this is better.

**Comment by canavandl** [comment]
LGTM - i spot tested the affected tools and annotations.

**Comment by mattpap** [comment]
@canavandl, thanks.

**Comment by mattpap** [comment]
I had to repush, because I forgot to update typings.

**Pull request merged**
