### PR TITLE
Remove katex example

### LINKED ISSUE #11870: Remove katex example, test and docs
Now that we have LaTeX labels, etc, working, we no longer need to demonstrate the use of katex. There is an example, a test and some mentions in the docs about it.

I tried to remove it as part of PR #11869 when I converted the katex Bessel function example, but I ended up with a number of sphinx errors that I didn't understand so I am hoping that @tcmetzger might want to deal with this.

### PR DESCRIPTION
**Pull request by tcmetzger**
As discussed in #11879, this PR removes the old examples using Katex. fixes #11870

### CODE REVIEW

**Comment by tcmetzger** [comment]
@bryevdv @mattpap This PR removes both the Katex example and the unit test based on that example. There are two individual commits, in case we want to keep the unit test.

**Comment by bryevdv** [comment]
@tcmetzger I think the files under `tests/unit/bokeh/embed` can/should stay  for now. I didn't realize the unit tests used a latex example, but it is not at all user-facing so I am less concerned about anyone stumbling across it. But there should definitely be a new issue about replacing the user examples, and it should link to this PR so that the test example can also be updated at that time.

**Comment by tcmetzger** [comment]
@bryevdv I reverted the commit removing the unit test, should be all good now! 😀

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
Thanks @tcmetzger

**Pull request merged**
