### PR TITLE
Keep fixed listen to and solve zoom issue

### PR DESCRIPTION
**Pull request by birdsarah**
Fixes: #4611 #4488

### CODE REVIEW

**Comment by bryevdv** [comment]
This seems reasonable at a glance! Requesting a render on a pixel ratio change seems safe and proper to do in general.

**Comment by birdsarah** [comment]
I have only tested this on one browser on OSX. So could do with more testing to make sure it actually resolves the zoom issue over a wider set of browsers.

But yes, as you said, it does seem like a good thing to do anyway.

**Comment by birdsarah** [comment]
ping @mattpap

**Comment by birdsarah** [comment]
OK, fixed my vimrc so hopefully this happens less.

**Pull request merged**
