### PR TITLE
Add check for user supplied data source and literal data arrays

### PR DESCRIPTION
**Pull request by Maggie-M**

### CODE REVIEW

**Comment by Maggie-M** [comment]
@bokeh/dev 

Here's one potential solution for issue #2056.  It raises a RuntimeError when a user supplies both a datasource and explicit lists of data.

This does cause these examples to fail on Travis:

```
[FAIL]  /home/travis/build/bokeh/bokeh/examples/plotting/file/color_scatter.py
[FAIL]  /home/travis/build/bokeh/bokeh/examples/plotting/file/glyphs.py
[FAIL]  /home/travis/build/bokeh/bokeh/examples/plotting/file/hover.py
[FAIL]  /home/travis/build/bokeh/bokeh/examples/plotting/file/linked_panning.py
[FAIL]  /home/travis/build/bokeh/bokeh/examples/plotting/file/markers.py
[FAIL]  /home/travis/build/bokeh/bokeh/examples/plotting/file/scatter.py
[FAIL]  /home/travis/build/bokeh/bokeh/examples/plotting/file/tap.py
[FAIL]  /home/travis/build/bokeh/bokeh/examples/plotting/server/color_scatter.py
[FAIL]  /home/travis/build/bokeh/bokeh/examples/plotting/server/glyphs.py
[FAIL]  /home/travis/build/bokeh/bokeh/examples/plotting/server/hover.py
[FAIL]  /home/travis/build/bokeh/bokeh/examples/plotting/server/linked_panning.py
[FAIL]  /home/travis/build/bokeh/bokeh/examples/plotting/server/markers.py
[FAIL]  /home/travis/build/bokeh/bokeh/examples/plotting/server/scatter.py
[FAIL]  /home/travis/build/bokeh/bokeh/examples/plotting/server/selection_histogram.py
[FAIL]  /home/travis/build/bokeh/bokeh/examples/plotting/server/tap.py
```

Another alternative would be to just display a warning each time a user tries to do this.  Would that become too annoying, though?

**Comment by fpliger** [comment]
I think that keeping support the mix (even if warnings) may lead to odd behaviours. I think that being explicit (and strong) about how users should use that part of the API is a good thing. So I'm +1 on that.

**Comment by bryevdv** [comment]
I agree it definitely enables confusing behaviors, but just to be explicit about what this would give up. Things like this would no longer work:
```
p.circle('x', 'y', radius=[1,2,3])
```
Maybe that is not a huge deal, but it's obviously used in several examples. I guess the question is how much breakage is acceptable. Another option is to warn now and remove later.

**Comment by damianavila** [comment]
> Another option is to warn now and remove later.

Probably is a good idea going into a deprecate cycle... but I generally agree on the change.

**Comment by fpliger** [comment]
+1 for the deprecate cycle.. In general I think that in cases like the one @bryevdv mentioned the old behaviour is handy but probably it's better to promote consistency. :+1:

**Comment by damianavila** [comment]
@Maggie-M, can you update the PR to include a deprecate cycle here? Thanks.

**Comment by damianavila** [comment]
ping @Maggie-M ;-)

**Comment by Maggie-M** [comment]
Sure thing, @damianavila!

**Comment by damianavila** [comment]
@Maggie-M, I am doing PRs housekeeping (getting things ready the upcoming release), so I will close this one according to BEP-1, if you are working now on this, just reopen the PR when you have something to push... thanks!!

**Comment by bryevdv** [comment]
OK

**Pull request closed without merging**
