### PR TITLE
Various bokehjs testing fixes

### PR DESCRIPTION
**Pull request by mattpap**
addresses #9420

### CODE REVIEW

**Comment by bryevdv** [comment]
Win 3.6 appears to be a real failure due to some external change

**Comment by mattpap** [comment]
> Win 3.6 appears to be a real failure due to some external change

It appears so, but I checked all relevant dependencies and there weren't any major updates, unless I missed something (maybe some conda packages are very far behind). However, looking at the exceptions, something is completely messed up, because the code doesn't match anything that I could find in tornado's repository (especially for the allegedly installed version 6.0.3).

**Comment by mattpap** [comment]
Looks like the conda package of tornado 6.0.3 was altered to contain:
```
if sys.platform == 'win32':     
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```
in `tornado/platform/asyncio.py`, which is an obvious failure on 3.6 on Windows.

**Comment by mattpap** [comment]
Tornado's conda package was incorrectly patched. I started https://github.com/conda-forge/tornado-feedstock/issues/33 for this.

**Pull request merged**
