### PR TITLE
Lock closed issues/prs

### PR DESCRIPTION
**Pull request by hoxbro**
Resolves https://github.com/bokeh/bokeh/discussions/14114

Same as the one used on HoloViews [holoviz/holoviews@main/.github/workflows/lock.yaml](https://github.com/holoviz/holoviews/blob/main/.github/workflows/lock.yaml)

It is set to lock 100 issues/PRs every hour, every day. When the backlog is completed, it can be changed to run each Tuesday night (the commented-out cron job).

Example:
image

### CODE REVIEW

**Comment by philippjfr** [comment]
Thanks @hoxbro! @bryevdv as per your request.

**Comment by bryevdv** [comment]
🙏  Thanks @hoxbro @philippjfr!

@bokeh/dev I'd like to merge this by tomorrow, just a heads up this will probably trigger a deluge of emails for some people, until all the old issues are worked through, depending on your notification settings.

**Review by mattpap — APPROVED** [review]

**Comment by bryevdv** [comment]
@philippjfr @hoxbro things seem to be working as expected, but I keep getting notifs about job failures, e.g. 

https://github.com/bokeh/bokeh/actions/runs/11524707450/job/32085456140

any ideas?

**Comment by hoxbro** [comment]
No. I don't see that on HoloViews CI.

**Pull request merged**
