### PR TITLE
Added root_dir for absolute resource paths #2166

### PR DESCRIPTION
**Pull request by bkief**
We find it useful to host the bokehjs resource on a shared network location. This allows for lightweight HTML plots to use a predefined and static network location for the JS payload. Issue #2166

### CODE REVIEW

**Comment by bryevdv** [comment]
Hi @bkief, have you tried setting the root directory with `relative` resources? That is the configuration that is intended to cover the use-case you describe, unless I am misunderstanding something.

**Comment by bryevdv** [comment]
Also FYI to note you should be able to set it with the env var `BOKEH_ROOTDIR`, see:

https://github.com/bokeh/bokeh/blob/master/bokeh/settings.py#L51

**Comment by bryevdv** [comment]
@bkief I believe the functionality you describe and desire is covered by `relative` resources already, so I am going to close this PR. In any case I don't think we can change the meaning of `absolute` resources in this way because it contradicts the normal meaning of "absolute path" in a confusing way. If I have misunderstood your use-case, please comment and we can re-open/re-visit any changes that might be generally useful.

**Comment by bkief** [comment]
Relative did not work for my use case for two reasons,
1) Python's os.path.relative cannot traverse to another drive letter;
2) Nor can it transverse UNC paths.

The only work arounds I found were to use the server mode and use root_url="file://my/network/path/to/resources/" or use absolute mode and override the resource instance variable js_files and css_files. 

My users cannot always access the CDN and to keep static html files slim, I host the js and css on a network drive. Since I find it useful, I thought adding it as a convince to Resources.py would be beneficial. I used absolute mode since it is an absolute location on the network, regardless of the location of the static html.

**Comment by bryevdv** [comment]
@bkief OK I do think we should do something to support those use-cases, but I do think adding `root_dir`  in conjunction with an "absolute path" is too confusing, Let's continue discussion on #2166, I will ping a few other devs to participate.

**Comment by bkief** [comment]
Fair enough, I am happy to help.

**Pull request closed without merging**
