### PR TITLE
Improve inline/link colors for docs

### PR DESCRIPTION
**Pull request by tcmetzger**
As part of Google's Season of Docs, this pull request slightly changes the colors of inline code and links for Bokeh's documentation. The goal is to increase legibility and increase compliance with the [WCAG's contrast criterion](https://www.w3.org/TR/WCAG21/#contrast-minimum). As discussed with @bryevdv, @hyles-lineata, and @pavithraes.

### CODE REVIEW

**Comment by bryevdv** [comment]
Here's a screenshot with several of the changes present for folks:

Screen Shot 2020-09-23 at 11 50 49 AM

Some random comments: 

* Maybe we should inline-code quote fewer things? It's the background changes on tiny things like "x" that I just find very distracting.
* Just pointing out, I am not sure there is anything to do: the links to refdocs are the case that are in a bit of conflict. They are both code and links. Looks like here we get the monospace font with the link color/underline treatment, that seems fine to me
* Wondering if maybe the code font could be even more "code-y"? The font face itself seems quite similar despite being monospace, and now that the font-color is the same as the regular text, the "code-ness" just does not pop out as immediately for me anymore, maybe a different monospace font would help?

**Comment by tcmetzger** [comment]
Thanks @bryevdv for the screenshot! To summarize for everybody reading here: the most visible change concerns the design of `inline code snippets`. In Bokeh's current docs, they are the same color as hyperlinks. This makes it difficult to differentiate between inline and hyperlinks at first glance. Most other documentation projects out there use different designs/colors for inlines vs. hyperlinks. I propose to follow the example of (among others) Github, [Google's GCP](https://cloud.google.com/tools/powershell/docs/quickstart#navigate_with_powershell_provider) or the official [Python docs](https://docs.python.org/3/library/stdtypes.html#boolean-operations-and-or-not) and use a grey background under the monospace font for inline code. Differentiating by background/font instead of just differentiating by color also adds the benefit of making it easier to discern for people with colorblindness.

**Comment by tcmetzger** [comment]
Regarding the comments from above: 

- Yes, it would certrainly be helpful to limit the use of inline code. Finding a good design that works has to balance several requirements: inline code should stand out enough to be recognizable, but at the same time should not interrupt the flow of reading too much (like you describe with seeing things such as "the `x` coordinate"). 

- For words that are both inline code and links: I'd just keep going with the theme's standard behaviour (red color, monospace font), this is how other documentation projects tread those instances as well.

- Making inline more "code-y": there are limits to using different fonts on the web, I believe that we should use standard system fonts over Google fonts, whenever possible. I did change the sizing slightly and gave the grey background box a little more space, maybe that helps:

grafik

**Comment by tcmetzger** [comment]
I just committed a small change to the CSS to add more monospace fonts. This is based on how GitHub handles monospace display and does look a little more "code-y" in my mind:
grafik

**Comment by bryevdv** [comment]
@tcmetzger that looks like an improvement to me! Could possibly try *slightly* less vertical padding? Regardless I like that change better 👍

**Comment by tcmetzger** [comment]
Absolutely, the most recent commit has less vertical padding (your browser will probably needs another forced reload to pick up the updated CSS):
grafik

**Review by pavithraes — APPROVED** [review]

**Comment by pavithraes** [comment]
@tcmetzger I like how this looks! Thank you!

**Pull request merged**
