### PR TITLE
Redesign assertions in bokehjs' tests

### LINKED ISSUE #10083: bokehjs needs a better assertion framework
We currently use chaijs, which has two major issues:

1. When comparing non-trivial objects, this is the output if assertion fails:
```
AssertionError: expected {} to deeply equal {}
```
(two `Map()` objects were involved). There's an issue open regarding this since 2016, so I presume this will never get fixed.

2. Expressions like `expect(a).to.be.equal(b)` (with `deep`, etc.) are dynamically typed.

### PR DESCRIPTION
**Pull request by mattpap**
fixes #10083

### CODE REVIEW

**Comment by bryevdv** [comment]
If we are going to develop and maintain our own JS assertions library, can it be in a separate, published package?

**Comment by mattpap** [comment]
> (...)  can it be in a separate, published package?

Yes, as soon as I introduce lerna.

**Comment by bryevdv** [comment]
> Yes, as soon as I introduce lerna.

Why is that necessary for this? For all the actual BokehJS bundles, sure. For this a separate repo seems more appropriate.

**Comment by mattpap** [comment]
Having multiple repositories is too much maintenance burden. However, more importantly assertions depend on utility modules that bokehjs provides, so it wouldn't be just one extra repository. Thus having everything in a monorepo as interdependent npm packages is much more efficient.

**Comment by bryevdv** [comment]
I still think we take on too much tooling burden, but that's a discussion for another time. Is there any reason to wait to merge this?

**Comment by mattpap** [comment]
> Is there any reason to wait to merge this?

This PR significantly changes how structural equality works in bokehjs, so I wouldn't merge this just before the release. This needs some time to settle in.

**Pull request merged**
