### PR TITLE
Move files and get correct examples path.

### PR DESCRIPTION
**Pull request by damianavila**
Cleaning the example directory from other things... the other thing is our continuous integration plumbing, so I moved to a new top level `ci folder`. My first though was to have this `ci` folder inside the `examples` one, but later I remember we ship the examples folder with conda packages and I think is not a good idea to ship other things than just examples...

### CODE REVIEW

**Comment by bryevdv** [comment]
There's something I don't like about such a short directory name `ci` at the top level. Dumb, I know. What about `tests/ci` or `tests/travis`?

**Comment by mattpap** [comment]
@damianavila, did you use `git mv`?

**Comment by damianavila** [comment]
> There's something I don't like about such a short directory name ci at the top level. Dumb, I know. What about tests/ci or tests/travis?

I am OK with change in the dir... probably `tests/travis` 

>@damianavila, did you use git mv?

Nop... I copy files and add and del files with git... probably is better to use `git mv`, @mattpap I broke something making it in the palaeolithic way?

BTW, this is running slowly on TravisCI, around 10 more minutes... maybe I am missing something? Ideas?

**Comment by damianavila** [comment]
OK, using git mv in another branch I am seeing some problems... it seems I did not remove the files... grrr... ok... I will let you know when this is ready again to take a look...

**Comment by damianavila** [comment]
Close in favour of #1781

**Comment by mattpap** [comment]
>  it seems I did not remove the files...

That's precisely the issue. Technically you don't have to use `git mv`. You could just add new files and remove old, but in **one** commit. Otherwise, we would lose history (in the sense that `--follow`  flag wouldn't be able resolve moves). It's easy to spot the error when you look at diff stat (even on github). In this PR you shave `+1000 0` and in the new one `+5 -3` (could be `0 0`, but there were little changes to the test script).

**Comment by damianavila** [comment]
Yep... thx for the explanation... that's exactly what it happened :wink:

**Pull request closed without merging**
