### PR TITLE
Allow users to specify Jinja2 template variables

### PR DESCRIPTION
**Pull request by liambuchanan**
If you'd like to use this but would prefer I write a test first or make some stylistic changes let me know. Also feel free to shoot it down if you feel it's unnecessary.

### CODE REVIEW

**Comment by liambuchanan** [comment]
Oops, should've checked the tests first. I'll sort that out and write a new one for custom templates.

**Comment by bryevdv** [comment]
@liambuchanan thanks for your contribution! This is going to conflict with #2401 which will probably be merged today. Would you be willing to merge master and update your PR after #2401 is merged? 

ping @mistakevin

**Comment by mistakevin** [comment]
Should just need some rearranging at most.

**Comment by liambuchanan** [comment]
@bryevdv Sure thing. I'll take a look once #2401 is merged.

**Comment by damianavila** [comment]
@liambuchanan #2401 was merge :stuck_out_tongue_winking_eye:

**Comment by liambuchanan** [comment]
I've merged in the upstream master (might've been cleaner to rebase but that doesn't seem like the github way of doing things).

**Comment by damianavila** [comment]
LGTM

**Comment by bryevdv** [comment]
I think it would be nice to expand this to handle multiple components, but that could happen in another PR. This is already a clear improvement. LGTM

**Comment by damianavila** [comment]
OK, merging... @liambuchanan can you elaborate/expand this to handle multiple components in other PR? :stuck_out_tongue_winking_eye:

**Comment by liambuchanan** [comment]
I should get a chance to have a look this weekend.

**Pull request merged**
