### PR TITLE
Add visible property to LegendItem

### LINKED ISSUE #9261: [FEATURE]Make LegendItems Hideable
**Is your feature request related to a problem? Please describe.**
I have a plot with lots of traces (a few hundred) defined in non-server Bokeh, but only a few traces displayed at any given time based on some CDSView settings the user may select.  I'd like to have a legend for the plot, but due to the number of underlying traces the legend becomes unusably large because legend entries for all of the filtered-out traces are still visible.

**Describe the solution you'd like**
I can think of two possible solutions:
The first would be to simply add a .visible property to LegendItems that could be toggled via CustomJS to disable rendering.  The second would be to have some mechanic whereby legend items may auto-hide if no points from the given GlyphRenderer are visible (either due to hiding, filtering, or simply not being in the visible plot area).

**Describe alternatives you've considered**
I tried creating pre-computing each possible legend configuration and adding/removing legend items (or even whole legends) via CustomJS, but this gave me a lot of cryptic error messages and based on this other conversation, CustomJS that could modify the calculation graph is frowned upon:
https://discourse.bokeh.org/t/updating-legend-when-using-bokeh-js/3947/3

Thanks!

### PR DESCRIPTION
**Pull request by bryevdv**
- [x] issues: fixes #9261
- [x] tests added / passed
- [x] release document entry (if new feature or API change)

@tcmetzger could we find a time to pair on adding visual tests to this PR? I could work through the new instructions fresh.

### CODE REVIEW

**Comment by tcmetzger** [comment]
@bryevdv Absolutely, that sounds great! I have been planning on refining the visual testing instructions as part of the dev docs update anyways and would appreciate some input!

**Comment by bryevdv** [comment]
`minimal-deps` tests are failing across builds now. There is a new version of `networkx` and it is now getting removed along with the other packages that the minimal build removes. I'll push a fix in this PR later today or tomorrow.

@IuryPiva since @mattpap is away for the next few weeks can you take a quick look at this PR? (and @tcmetzger for any docs comments)

**Comment by bryevdv** [comment]
I've also made the `minimal-deps` build now explicitly remove `networkx`, which is actually the correct thing to have happen .

**Comment by bryevdv** [comment]
I'll plan to merge this in a few hours unless more time is requested, in order to get the build fixed.

**Pull request merged**
