### PR TITLE
Backports for 3.1.1

### PR DESCRIPTION
**Pull request by bryevdv**
cc @bokeh/core Here's a start for 3.1.1 backport

* https://github.com/bokeh/bokeh/pull/12973
* https://github.com/bokeh/bokeh/pull/12939
* https://github.com/bokeh/bokeh/pull/12963
* https://github.com/bokeh/bokeh/pull/13054
* https://github.com/bokeh/bokeh/pull/13084
* https://github.com/bokeh/bokeh/pull/13065
* https://github.com/bokeh/bokeh/pull/13082
* https://github.com/bokeh/bokeh/pull/12892
* https://github.com/bokeh/bokeh/pull/12899
* https://github.com/bokeh/bokeh/pull/12900
* https://github.com/bokeh/bokeh/pull/12901
* https://github.com/bokeh/bokeh/pull/12902
* https://github.com/bokeh/bokeh/pull/12903
* https://github.com/bokeh/bokeh/pull/12910
* https://github.com/bokeh/bokeh/pull/12928
* https://github.com/bokeh/bokeh/pull/12935
* https://github.com/bokeh/bokeh/pull/12955
* https://github.com/bokeh/bokeh/pull/12962
* https://github.com/bokeh/bokeh/pull/13002
* https://github.com/bokeh/bokeh/pull/13066
* https://github.com/bokeh/bokeh/pull/13100
* https://github.com/bokeh/bokeh/pull/13057
* https://github.com/bokeh/bokeh/pull/13003
* https://github.com/bokeh/bokeh/pull/13026
* https://github.com/bokeh/bokeh/pull/13086
* https://github.com/bokeh/bokeh/pull/13061
* https://github.com/bokeh/bokeh/issues/13053 (external work)
* https://github.com/bokeh/bokeh/pull/13041
* https://github.com/bokeh/bokeh/pull/13070
* https://github.com/bokeh/bokeh/pull/13062
* https://github.com/bokeh/bokeh/pull/13035
* https://github.com/bokeh/bokeh/pull/13009
* https://github.com/bokeh/bokeh/pull/13039
* https://github.com/bokeh/bokeh/pull/13109

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap do you know if eslint is failing because I didn't include the TS5 update PR? Should that PR be included?

**Comment by mattpap** [comment]
You need to apply this patch (from PR #12977):
```diff
diff --git a/bokehjs/eslint.json b/bokehjs/eslint.json
index 43bd5ab267..f74ba44b83 100644
--- a/bokehjs/eslint.json
+++ b/bokehjs/eslint.json
@@ -16,7 +16,7 @@
     "tsconfigRootDir": ".",
     "sourceType": "module"
   },
-  "plugins": ["@typescript-eslint", "deprecation"],
+  "plugins": ["@typescript-eslint"],
   "extends": [],
   "rules": {
     "@typescript-eslint/ban-types": ["error", {
@@ -124,7 +124,6 @@
       "anonymous": {"before": false, "after": true},
       "method": {"before": true, "after": false}
     }],
-    "yield-star-spacing": ["error", {"before": false, "after": true}],
-    "deprecation/deprecation": ["error"]
+    "yield-star-spacing": ["error", {"before": false, "after": true}]
   }
 }
```
Upgrading TypeScript, i.e. backporting the entire PR, is not a good idea.

**Comment by mattpap** [comment]
PR #13104 needs to be backported as well. I also need to backport changes to resources (e.g. `clone()` method).

**Comment by bryevdv** [comment]
I'm not sure why the docs build is still failing with #13086 merged. Also I think a baseline image is missing I think. My time this week is fairly constrained FYI @bokeh/core 

Edit: well, this is why, but the pin seems to be present, so then I don't know why the pin is not working
```
sphinx                    6.2.1                    pypi_0    pypi
```

Edit2: pin was not applied to 3.8 env which was dropped for `branch-3.2`

**Comment by bryevdv** [comment]
OK all the milestones should be re-targeted, but sometimes the GH web UI flakes out so it would be ideal if someone else can double-check all the linked PRs and issues. @bokeh/core This should be ready to go once someone updates the baseline image, barring any other new PRs that are desired to include.

**Comment by bryevdv** [comment]
Actually it looks like there might be a few other tasks/bug, e.g what about

* https://github.com/bokeh/bokeh/pull/13070

?

**Comment by bryevdv** [comment]
@mattpap I added those other PRs. Can you add the missing baseline image? FWIW I think https://github.com/bokeh/bokeh/issues/12913 (cc @ianthomas23 ) would be another good candidate but I won't have time to fix the conflict.

**Comment by bryevdv** [comment]
@philippjfr I think this is more or less ready, it would be good to cut an RC after the two small points about are resolved and even better for someone to so a little hands on testing (or at least dev docs review)

**Comment by bryevdv** [comment]
@mattpap I guess the resource PR would need some minor extra work for 3.8:
```
E           AttributeError: 'PosixPath' object has no attribute 'is_relative_to'
```

**Comment by mattpap** [comment]
> (..) PR would need some minor extra work for 3.8:

I will deal with this and the baselines.

**Comment by ianthomas23** [comment]
> FWIW I think #12913 (cc @ianthomas23 ) would be another good candidate but I won't have time to fix the conflict.

I can deal with this if everyone is happy with me pushing directly to this branch.

**Comment by ianthomas23** [comment]
I've added #13039, the fix for issue #12913, plus appended it to the list in the first comment of this PR and changed the milestones of both the issue and PR from 3.2 to 3.1.1.

**Comment by mattpap** [comment]
Adding PR #13039 resolved baseline failures.

**Comment by bryevdv** [comment]
@bokeh/core PR is green, if someone can submit a review approval, I propose to merge and cut an RC build today. 

Assuming the deployed docs look good, I will submit a separate PR for the release notes and version switcher tonight/tomorrow.

**Review by ianthomas23 — APPROVED** [review]

**Comment by mattpap** [comment]
I started 3.1.1rc1 build (https://github.com/bokeh/bokeh/actions/runs/4885437161)

**Comment by bryevdv** [comment]
3.1 dev docs are at https://docs.bokeh.org/en/dev-3.1/docs/user_guide/interaction.html

**Comment by bryevdv** [comment]
@bokeh/core I pushed the release notes, etc directly in commit https://github.com/bokeh/bokeh/commit/c3468b2e2a7a66d4c94d9cb2a37c180e5bd07777 (Edit: CI has passed)

I went through all the gallery examples and they looked good. 

I think we could do a release tomorrow, @philippjfr can you just confirm that the rc fixes everything you need?

**Pull request merged**
