### PR TITLE
possible solution to store model instead of view on 0d selections

### PR DESCRIPTION
**Pull request by bryevdv**
ping @mattpap @havocp 

This works. Is not great, but it works.

### CODE REVIEW

**Comment by havocp** [comment]
seems ok to me as a short-term plan.

**Comment by mattpap** [comment]
@bryevdv, so what is the underlying problem? This failed to serialize (as I recall from the meeting)?

**Comment by havocp** [comment]
right can't put nonserializable thing (a view) in attributes or we try to sync it to server

**Comment by mattpap** [comment]
As a temporary solution this PR is OK. Later we should proceed with making selection a class (or maybe a model).

**Comment by bryevdv** [comment]
@mattpap OK will merge then. I agree we could make selection a proper model. I also think we should move properties on to glyphs and not their views which would also solve this problem.

**Comment by bryevdv** [comment]
ping @almarklein  just so you are aware

**Pull request merged**
