### PR TITLE
Don't require CSS width/height for responsive sizing modes

### LINKED ISSUE #7014: The inherited width should be set to 100% and up to the user to implement margin and padding restrictions
**Here is a link to the line that is in contention:**
https://github.com/bokeh/bokeh/blob/08020a31393630a2bda1bb083564492d14669264/bokeh/core/_templates/file.html#L33

When inheriting a sizing parameter it should always be 100% up to the user to be in control of the restrictions. This should be done entirely via the users own HTML setup of the layout or via a set of control options in the doc object, I would think.

### PR DESCRIPTION
**Pull request by mattpap**
fixes #7014

### CODE REVIEW

**Comment by bryevdv** [comment]
FYI if you run the one failing example `dashboard.py` locally, this is the error:

> unsatisfiable constraint: SidePanel(5784ED1C1A3346DDABFBCF2CCD7794AE, above).height - 28.49453125 >= 0

**Comment by mattpap** [comment]
Yeah, but this isn't layout's fault, though it could handle this situation more gracefully. The problem is that I underestimated stupidity of CSS. There's a good reason why this `width` and especially `height` is there. CSS4 will close this gap, but maybe something can be done in the meantime, because it's so close to working.

**Comment by mattpap** [comment]
In fact there is a solution, though more a hack. Not rendering widgets in `initialize` fixes this. We shouldn't be doing any rendering in init anyway, so this would be a win-win.

**Comment by bryevdv** [comment]
testing now

**Comment by bryevdv** [comment]
@mattpap is there an easy way to expose this to be configurable, so .e.g our existing examples could be made to look like they did before? I agree that not-setting is the best default.

**Comment by bryevdv** [comment]
@mattpap any comment on the question above?

**Comment by mattpap** [comment]
>  is there an easy way to expose this to be configurable,

I would do this via resources by adding a raw CSS, but I'm not sure if this is currently actually feasible or not. It definitively would be feasible if I finally dig out code I wrote a few months ago, which was supposed to address such situation (abstract resource vs resource bundle separation).

**Comment by bryevdv** [comment]
I'd say we need to hold off on this until there is some proven mechanism to get back things the way they were if desired, and also a migration note would be appropriate.

**Comment by bryevdv** [comment]
@mattpap if you add a migration note now I'll merge and cut a dev build

**Comment by mattpap** [comment]
@bryevdv, I added migration note.

**Pull request merged**
