### PR TITLE
Feature/1792 grid bands

### LINKED ISSUE #1792: Allow grids to shade alternating bands

### PR DESCRIPTION
**Pull request by bryevdv**
issues: closes #1792 
 
Sometimes you realize there is a missing thing that is easy but also useful and you jump when the urge strikes. 

stocks

### CODE REVIEW

**Comment by bryevdv** [comment]
It could use slight improvements when panning/zooming, i.e. the ability to always shade or not shade the nearest band to zero.  Right night the bands "swap" as you pan, but that's ok for now.

**Comment by bryevdv** [comment]
Open to alternate attribute names, perhaps `band_fill_color`, `band_fill_alpha` would be better.

**Comment by damianavila** [comment]
> It could use slight improvements when panning/zooming, i.e. the ability to always shade or not shade the nearest band to zero. Right night the bands "swap" as you pan, but that's ok for now.

Yes, I think it is OK for now...

>Open to alternate attribute names, perhaps band_fill_color, band_fill_alpha would be better.

PLAEASE! Jeje... I don't like `alt_fill` at all...

Finally, code LGTM... I just would like to see other names as I said before.

**Comment by bryevdv** [comment]
oK I will make the change and merge when tests pass.

**Pull request merged**
