### PR TITLE
fix font-size css issue

### LINKED ISSUE #13281: font-size does not depend on --font-size css variable
### Software versions

python version      :  3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
IPython version     :  8.13.2
Tornado version     :  6.3.1
Bokeh version       :  3.2.0
BokehJS static path :  C:\repos\private\panel\.venv\lib\site-packages\bokeh\server\static
node.js version     :  v16.14.0
npm version         :  8.3.1
Operating system    :  Windows-10-10.0.19044-SP0

### Browser name and version

_No response_

### Jupyter notebook / Jupyter Lab version

_No response_

### Expected behavior

I would expect the css `font-size` to depend on the `--font-size` css variable such that I can set the font size globally or locally.

### Observed behavior

If you look in the source code of Bokeh you can see the `font-size` does not depend on the `--font-size` css variable. Its set to `13px`.

image

### Example code

For reproducible examples see https://github.com/holoviz/panel/issues/5314

### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Closes #13281

I've tried to identify additional places where `--font-size` should be used, but was not. This PR also fixes these issues.

### CODE REVIEW

**Comment by bryevdv** [comment]
I've restated the ubuntu job in order to re-generate the baselines artifact. @MarcSkovMadsen you'll need to download the artifact and update the baselines as described at the bottom of this section:

https://docs.bokeh.org/en/latest/docs/dev_guide/writing_tests.html#bokehjs-visual-tests

@mattpap do you have any comments beyond updating the baselines?

**Comment by mattpap** [comment]
It's too many baselines to update, that's why it was marked WIP.

**Comment by mattpap** [comment]
I also don't want users to depend on unprefixed CSS variables (unprefixed are private, `bk-` prefixed are public) and this change in its current form invites that.

**Comment by bryevdv** [comment]
Should this be declined and closed then? I was really asking about what the ultimate disposition or way forward should be

**Comment by mattpap** [comment]
No, this PR is a good starting point, it just needs to be refined. When I find some spare time, I will do that.

**Review by mattpap — APPROVED** [review]
Given the extent of my changes to this PR, I would recommend @bryevdv or @philippjfr to have a look at this as well.

**Review by philippjfr — COMMENTED** [review]
So did the font-size change from 13px -> 12px now and was the `--font-size` variable completely ignored before?

**Comment by mattpap** [comment]
> So did the font-size change from 13px -> 12px now and was the --font-size variable completely ignored before?

It's a bit more complicated because 13px was the font size but 12px was the baseline for line height computations, but yes it was mostly ignored. With this change all font sizing is unified under one CSS variable, which then can be used to adjust local font sizing by scaling with `calc(0.9*var(--font-size))` or by using CSS inheritance and a percent value, if applicable.

**Review by bryevdv — APPROVED** [review]
My only comment/ask is about the data table font size. I do think the tables looked better with a slightly smaller font for the cells. If that's possible, I'd suggest it. Otherwise everything LGTM

**Comment by mattpap** [comment]
> My only comment/ask is about the data table font size. I do think the tables looked better with a slightly smaller font for the cells. 

It looks better indeed. I restored the original font size in data tables.

**Comment by mattpap** [comment]
@MarcSkovMadsen, thanks.

**Pull request merged**
