### PR TITLE
patches should work with reversed ranges

### LINKED ISSUE #2366: Patches doesn't render with reversed ranges
See last chart on:

http://nbviewer.ipython.org/github/birdsarah/bokeh-miscellany/blob/master/notebooks/Patch%20%26%20Patches.ipynb

### PR DESCRIPTION
**Pull request by bryevdv**
issues: fixes #2366 

Issue was passing `(start, end)` to index search, needs to always be `(min, max)`

### CODE REVIEW

**Comment by bryevdv** [comment]
Test script:

```
import pandas as pd
from bokeh.plotting import output_file, show

output_file("foo.html")

from bokeh.models import Plot, Patch, Patches, ColumnDataSource, Range1d, LinearAxis, HoverTool, TapTool
from bokeh.palettes import Spectral3, Spectral4

patches_data = pd.DataFrame(
    {
        'xs'  : [[1, 2, 3, 1], [2, 4, 6, 2], [3, 6, 9, 3], [1, -1, -2, 0] ],
        'ys'  : [[0, 1, 5, -1], [8, -3, 4, 0], [3, 4, 5, 4], [1, 4, 0, 2]],
        'value': [Spectral4[0], Spectral4[1], Spectral4[2], Spectral4[3]]
    },
)

def make_patches_plot(xrange, yrange):
    source = ColumnDataSource(patches_data)
    plot = Plot(
        title=None,
        x_range=xrange, y_range=yrange,
        plot_width=300, plot_height=300,
        min_border=0, toolbar_location=None)

    glyph = Patches(xs='xs', ys='ys', fill_color='value', line_color='#CCC')
    plot.add_glyph(source, glyph)
    return plot

patches_rev = make_patches_plot(Range1d(10, -5), Range1d(-5, 10))
show(patches_rev)
```

**Comment by bryevdv** [comment]
screen shot 2015-06-26 at 2 49 39 pm

**Comment by bryevdv** [comment]
@bokeh/dev this is ready for review

**Comment by bryevdv** [comment]
Merging

**Comment by jakirkham** [comment]
+1

**Pull request merged**
