### PR TITLE
Implement a bokehjs development/diagnostics tool

### PR DESCRIPTION
**Pull request by mattpap**
This PR introduces a devtools-like tool for bokehjs, which allows for exploring models, model graphs, property values and other state, signals, etc. This is a very early WIP.

image

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap What do you think about having this tool be able to intercept Bokeh log messages? I ran into another user yesterday who did  not know about the JS console, or to look there for information. We could potentially even add an annotation to the toolbar icon (e.g. a red ❗ or something) if there have been errors or warnings to induce users to click it for information. Just really interested in finding ways to surface JS issues to users much more visibly. With something like that I'd be inclined to push very heavily on promoting this tool for general, standard usage practice.

**Comment by bryevdv** [comment]
Also I guess I initially took the "tool" in the title too literally, and e.g. a user would click a toolbar action to pop up this display. But just to confirm, this is just a "widget" to add to a layout?

**Comment by mattpap** [comment]
> What do you think about having this tool be able to collect Bokeh log messages?

Yes, which is what I intend to do at some point, among other things. The current implementation barely scratches the surface of what can be done.

**Comment by mattpap** [comment]
> Also I guess I initially took the "tool" in the title too literally, (...)

It will become a tool. I primarily intend it to be accessible via a content menu item, but also as an extra tool button on a toolbar (if requested). I also need support for dialogs, for this to look nicely, and so that it wouldn't require special treatment.

**Comment by bryevdv** [comment]
All sounds great, LGTM to merge as a start

**Pull request merged**
