### PR TITLE
Correct lots of defaults to match between Python and CoffeeScript

### PR DESCRIPTION
**Pull request by havocp**
These are cases where we were using the Coffee values in 0.10 and
the Python defaults were out of sync, the Coffee values look more
correct.

### CODE REVIEW

**Comment by havocp** [comment]
Bryan I set you as author of this commit because I think you made most of these changes originally on #3099

**Comment by havocp** [comment]
I added the coffee-side changes to the PR also, since the changes on either side may interrelate.

**Comment by havocp** [comment]
examples_flake_docs failed due to timeout again; I clicked restart several times but it doesn't seem to be restarting.

**Comment by bryevdv** [comment]
travis seems to be having some issues today

**Comment by bryevdv** [comment]
OK, tests pass, report looks good. @mattpap would appreciate a look from you. The best way to bring the widget defaults into alignment was to mirror the class structure.

**Comment by bryevdv** [comment]
@bokeh/core I plan to merge this tomorrow, unless I hear otherwise

**Pull request merged**
