### PR TITLE
#5691: Fix a typo in LayoutDOM

### LINKED ISSUE #5691: Fix a typo in LayoutDOM
`bokeh` `0.12.4`
https://github.com/bokeh/bokeh/blob/master/bokeh/models/layouts.py#L64
reads 
```
``"scale_both"`` elements will responsively resize to fir both the width and height available,
```

Expected:
```
``"scale_both"`` elements will responsively resize to for both the width and height available,
```

### PR DESCRIPTION
**Pull request by rs2**
All pull requests must have an associated issue in the issue tracker. If there
isn't one, please go open an issue describing the defect, deficiency or desired
feature. You can read more about our issue and PR processes in the
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).

- [x] issues: fixes #5691
- [x] tests added / passed
- [x] release document entry (if new feature or API change). See below

#5691: Fix a typo in LayoutDOM

### CODE REVIEW

**Comment by mattpap** [comment]
Before this is merged, the commit history of this PR needs to be straighten out. It seems to me that "squash and merge" approach gets into the way. But it may be submitter's fault as well, seeing that the PR originates from `master` branch.

**Comment by rs2** [comment]
@mattpap `Squash and merge` seems to be the right approach. As my local repo needs to be synchronized with `upstream/master` you will see my intermediate commits that lead to the `sha` identical to that of `upstream/master`. Any concerns - pls let me know.

**Comment by rs2** [comment]
@mattpap PS The key criteria is what you see in the `Files changed section`. Squash on merge. https://github.com/bokeh/bokeh/pull/5709/files

**Comment by bryevdv** [comment]
Yah I concur that a squash on merge will be fine. Thanks @rs2

**Pull request merged**
