### PR TITLE
Clean up toolbar's CSS

### LINKED ISSUE #4290: Clean up toolbar's CSS
The existing implementation is unmaintainable and needs replacement. This work will be the basis for further toolbar improvements. This is unrelated to making toolbar a standalone widget.

### PR DESCRIPTION
**Pull request by mattpap**
This is very preliminary work to make toolbar's CSS maintainable.  I'm submitting this is such early form so that @birdsarah will know what I'm doing to the toolbar.

fixes #4290

### CODE REVIEW

**Comment by birdsarah** [comment]
Thanks for the headsup @mattpap - much appreciated.

**Comment by bryevdv** [comment]
@mattpap I took a looks at this, the only part of the merge that looks tricky is `continuum.less` (it's beyond my CSS to fix up) the others are merges are fairly straightforward. I am sure @birdsarah can answer any questions to help resolve the conflicts here.

**Comment by mattpap** [comment]
It looks like I may as well start from scratch.

**Comment by bryevdv** [comment]
@mattpap do you want this PR closed then?

**Comment by mattpap** [comment]
This has to be implemented from scratch.

**Pull request closed without merging**
