### PR TITLE
Webgl - take 3

### PR DESCRIPTION
**Pull request by almarklein**
Heavy WIP. Compared to my earlier PR, this keeps a visible 2D canvas and an invisible webgl context. It also uses gloo.js (also a WIP) instead of vispy.js, making for easier dependencies.

### CODE REVIEW

**Comment by bryevdv** [comment]
@almarklein I get this trying to build:
```
bryan@laptop (git:webgl) ~/work/bokeh $ python setup.py develop --build_js
Building BokehJS... Failed.

ERROR: 'gulp build' returned error message:
    events.js:125
          throw er; // Unhandled 'error' event
                ^
    Error: ENOENT: no such file or directory, open '/home/almar/dev/build/vispy.js/scripts/lib/jquery.min.js'
      at Error (native)
```

**Comment by bryevdv** [comment]
Imagine this is the issue:

https://github.com/bokeh/bokeh/pull/2227/files#diff-3a70afdf73d2ab402f406c8a90df9b93R72

**Comment by almarklein** [comment]
@bryevdv mmm I thought that I got rid of that ... I think I forgot to push, sorry.

**Comment by almarklein** [comment]
@pzwang the birds demo works in the branch as well. Colors are just picked at random in the shader.

**Comment by bryevdv** [comment]
@almarklein OK it is building now. Where are the demo scripts?

**Comment by bryevdv** [comment]
ping @almarklein

**Comment by almarklein** [comment]
They're in `examples/glyphs/maps_x.py`

**Comment by almarklein** [comment]
@pzwang if you need anything changed, let me know and I can have a look tomorrow morning, which is before *your* morning.

**Comment by almarklein** [comment]
The cities data needs to be placed in the home dir: https://dl.dropboxusercontent.com/u/1463853/apps/us_cities.json

**Comment by bryevdv** [comment]
@almarklein I am not seeing `examples/glyphs/maps_x.py` in this branch.

**Comment by bryevdv** [comment]
Just to clarify, this is where I am looking:

https://github.com/almarklein/bokeh/tree/webgl3/examples/glyphs

**Comment by pzwang** [comment]
Almar, you forgot to check in the actual demo scripts.  I can't find them on any of the branches I looked at.

**Comment by almarklein** [comment]
Ah crap, sorry guys, I forgot to add those :/  (added now)

**Comment by damianavila** [comment]
Note: Extending the time for this one open as WIP because of @almarklein not availability for some days.

**Comment by almarklein** [comment]
Superseded by #2391. Leaving this branch because it has some benchmarks to back up the choice for the rendering-gl-into-2d-canvas approach.

**Pull request closed without merging**
