### PR TITLE
Replace INLINE with CDN.

### LINKED ISSUE #2572: output_notebook resources
I use gist frequently to share notebooks, code and ideas.  ``output_notebook`` uses ``INLINE`` Resources as a default and it creates an enormous file.  Files that are too large in a Gist will require the files to be edited locally and pushed to the Gist repository.

After some digging, I found how to use the ``CDN`` to render the notebooks.  Using the ``CDN`` Resource reduces the file size so that the gist can still be edited online.  

This [Gist](https://gist.github.com/tonyfast/fae0eacea79bbd28996d) describes this issue in a bit more detail.  But, ultimately the ``CDN`` reduces the file size by an order of magnitude for this particular example.

It might be valuable to consider a different default mode for the ``output_notebook`` method or at least provide a warning or message that there is a way to reduce the file size.

### PR DESCRIPTION
**Pull request by Maggie-M**
issues: fixes #2572

### CODE REVIEW

**Comment by bryevdv** [comment]
@bokeh/core any objections or comments?

**Comment by fpliger** [comment]
Replacing INLINE with CDN as default mode for output_file would mean that all our `output_file` example wouldn't pic the latest changes.. this would break the examples ci diff tests (they would always pass) and may be a but cumbersome to test local changes while working on example. Or not? I may be missing some internals.. :)

**Comment by bryevdv** [comment]
No, it would definitely add a burden to doing and testing BokehJS development. But it's also something that has been asked for over and over. A compromise might be to only make CDN the default for `output_notebook` and not for `output_file`. Or if we make the default everywhere, then the tests would probably need to set `BOKEH_RESOURCES` explicitly (as would anyone doing BokehJS dev)

**Comment by damianavila** [comment]
>Or if we make the default everywhere, then the tests would probably need to set BOKEH_RESOURCES explicitly (as would anyone doing BokehJS dev)

Probably the best option... this PR should include that in the test machinery and some notes in the dev docs about setting up BOKEH_RESOURCES.

**Comment by bryevdv** [comment]
@damianavila I'm not sure offhand where to set `BOKEH_RESOURCES` so that the examples get run with it. Can you point @Maggie-M in the right direction.

**Comment by damianavila** [comment]
Probably here: https://github.com/bokeh/bokeh/blob/master/tests/travis/test#L274...
But now looking into this, it is asking for relative resources... so not sure if will be affected by the change from INLINE to CDN...

**Comment by fpliger** [comment]
IIRC `output_*` does not consider `BOKEH_RESOURCES` at all..

**Comment by bryevdv** [comment]
It does, `output_file` says "I want an HTML file" and only incidentally says anything about how BokehJS is loaded (via the `mode` param). But `Resources` preferentially overrides its programmatic configuration with env var values.

**Comment by damianavila** [comment]
>It does, output_file says "I want an HTML file" and only incidentally says anything about how BokehJS is loaded (via the mode param). But Resources preferentially overrides its programmatic configuration with env var values.

So let's add a comment in the dev docs about using BOKEH_RESOURCES in development and then trigger the examples (add `[ci enable examples]` to your last commit message) to check if they are working properly...

**Comment by bryevdv** [comment]
@Maggie-M can you merge master into this? I think that will also get the examples tests running again.

**Comment by mattpap** [comment]
>  it would definitely add a burden to doing and testing BokehJS development

I think it doesn't. I don't remember last time I relied on the defaults for development. For development you should simply use `BOKEH_DEV=true` and you are set.

**Comment by bryevdv** [comment]
I didn't say it was a big one, I just wanted to acknowledge it. I'm +1 for merging this PR, with an appropriate note added to the dev guide.

**Comment by mattpap** [comment]
@bryevdv, done.

**Comment by bryevdv** [comment]
Restarted spuriously stopped test. Will merge when they pass this afternoon unless I hear otherwise (I perceive there to be agreement on this) @bokeh/dev

**Comment by damianavila** [comment]
LGTM, let's get this merged...

**Pull request merged**
