### PR TITLE
Filterable and groupable CDS with new model CDSView

### LINKED ISSUE #4070: Plotting with subsets (row-wise) of ColumnDataSources (like filtered data)
Currently, Bokeh only allows glyphs to take full columns of data from a ColumnDataSource. This means that you must have additional ColumnDataSources for any plots that only use a subset of the data. This causes data to be replicated and makes linked selection more complicated for users, who would have to keep track of indices themselves. 

It would be nice if Bokeh allowed glyphs to take subsets of columns as data. An application using multiple plots, each showing some subset (e.g. filtered by the value of some column, like the example @dennisobrien showed at the SF meetup) of the data (or the full set), would then be able to completely share the data in the same way that Bokeh allows plots to share the full ColumnDataSource now. Linked selection would work intuitively with selected data points (rows) showing up in whichever plots contain that point. Holding shift before selecting on any plot would add to the selection. 

One possibility for an API would be to include another parameter that picks the subset of data for a renderer to use by the indices (which could default to all). 

``` python
data_source = ColumnDataSource(df)
fig = figure()
r = fig.circle(x = ‘x’, y = ‘y’, source=data_source, indices=[0, 1, 2]) 
r = fig.circle(x = ‘x’, y = ‘y’, source=data_source, indices=np.arange(n)[df.weather == “sunny”])
r = fig.circle(x = ‘x’, y = ‘y’, source=data_source, indices=[i for i, val in enumerate(df.weather) if val == “sunny”])
```

Another possibility could be to make the data source “filterable” in a pandas-like way. 

``` python
r = fig.circle(x = ‘x’, y = ‘y’, source=data_source[ data_source.weather == “sunny” ]) 
```

I tried to look through the issues and google group to find some related posts. 
https://github.com/bokeh/bokeh/issues/2323
https://github.com/bokeh/bokeh/issues/2710
https://groups.google.com/a/continuum.io/forum/#!searchin/bokeh/data$20source%7Csort:date/bokeh/_DIOQGlC6ds/EbZL0KRfBwAJ
https://groups.google.com/a/continuum.io/forum/#!searchin/bokeh/data$20source%7Csort:date/bokeh/79eSMaDV39I/OTfZqZHIug0J

Is this something that would be in Bokeh’s scope?

### PR DESCRIPTION
**Pull request by clairetang6**
This PR is a third attempt to create a filterable CDS ([First](https://github.com/bokeh/bokeh/pull/5828) and [Second](https://github.com/bokeh/bokeh/pull/5933)). This attempt keeps the ColumnDataSource largely unchanged, so it continues to be in charge of its data. The filtering is instead done by the new CDSView, which represents a row-wise subset of a CDS used by a GlpyhRenderer when it renders glyphs. 

The CDSView is composed of individual Filters, a new model that represents subsets created by one type of filtering operation. In the initial PR (first commit), the Filter's `filter` can only be a `Seq(Int)` representing the indices of the subset, but this will be expanded to include `Seq(Bool)` and a new callable type that could operate on data values or data indices to return True or False. 

This PR also introduces GroupFilters which are a specific type of Filter that can be used for grouping. It has a `column_name` and `group` attribute. 

One important note is that the CDSView as it's implemented now is not optional in a sense (but looks optional from a user pov). The GlyphRenderer has to have both a source and a view. However, if a view is not passed in, then one is created on initialization that represents the full data set. If the view were to be truly optional, the internal code of the GlyphRenderer would need to be a bit messier (with checks to see if a view is there or not at potentially multiple points). 

Example:
cds_view

```python
from bokeh.plotting import figure
from bokeh.layouts import row, column
from bokeh.models.sources import ColumnDataSource, CDSView
from bokeh.models.filters import Filter, GroupFilter
from bokeh.models.tools import HoverTool
from bokeh.io import output_file, show

output_file("cds_view.html")

data = {'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'y': [10, 5, 2, 6, 1, 4, 8, 2, 7, 3],
        'z': ['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c', 'c']}

cds = ColumnDataSource(data)
view = CDSView(source=cds, filters=[Filter(filter=[0, 1, 2, 3, 4]),
                                    GroupFilter(column_name='z', group='b')])

plot_size_and_tools = {'plot_height': 220, 'plot_width': 220,
                        'tools':['box_select', 'reset'],
                        'x_range':[0, 11], 'y_range':[0, 11]}

fig1 = figure(title="", **plot_size_and_tools)
c1 = fig1.circle(x='x', y='y', source=cds, view=view, color='black', hover_fill_color='red')
fig1.add_tools(HoverTool(tooltips=None, renderers=[c1], mode='hline'))

fig2 = figure(title="", **plot_size_and_tools)
c2 = fig2.circle(x='x', y='y', source=cds, color='black', hover_fill_color='red')
fig2.add_tools(HoverTool(tooltips=None, renderers=[c2], mode='hline'))


show(row(fig1, fig2))
```

- [x] issues: fixes #4070 
- [x] tests added / passed
- [ ] release document entry (if new feature or API change)

### CODE REVIEW

**Comment by clairetang6** [comment]
Here is an example showing two scatter plots of the iris sample data, one with the full CDS plotted and another using the same CDS but different views, which make use of GroupFilter to filter by the species column. The datatable contains all the rows of the CDS where the petal length is > 3, using a view with a BooleanFilter.

group_datatable

```python
from bokeh.plotting import figure
from bokeh.layouts import row, column
from bokeh.models.sources import ColumnDataSource, CDSView
from bokeh.models.filters import GroupFilter, BooleanFilter
from bokeh.models.widgets import DataTable, TableColumn
from bokeh.io import output_file, show

from bokeh.sampledata.iris import flowers

output_file("group_datatable.html")

source = ColumnDataSource(flowers)
view1 = CDSView(source=source, filters=[GroupFilter(column_name='species', group='setosa')])
view2 = CDSView(source=source, filters=[GroupFilter(column_name='species', group='versicolor')])
view3 = CDSView(source=source, filters=[GroupFilter(column_name='species', group='virginica')])
view4 = CDSView(source=source, filters=[BooleanFilter(booleans=[d > 3 for d in source.data['petal_length']])])

plot_size_and_tools = {'plot_height': 300, 'plot_width': 300,
                        'tools':['box_select', 'reset']}

fig1 = figure(title="Full data set", **plot_size_and_tools)
fig1.circle(x='petal_length', y='petal_width', source=source, color='black')

fig2 = figure(title="Composed of grouped data", x_range=fig1.x_range, y_range=fig1.y_range, **plot_size_and_tools)
fig2.circle(x='petal_length', y='petal_width', source=source, view=view1, color='red')
fig2.square(x='petal_length', y='petal_width', source=source, view=view2, color='green')
fig2.diamond(x='petal_length', y='petal_width', source=source, view=view3, color='blue')

columns = [
        TableColumn(field="species", title="Species"),
        TableColumn(field="petal_length", title="Petal length"),
        TableColumn(field="petal_width", title="Petal width"),
        TableColumn(field="sepal_length", title="Sepal length"),
        TableColumn(field="sepal_width", title="Sepal width")
    ]
data_table = DataTable(source=source, view=view4, columns=columns, width=400, height=280)

show(column(row(fig1, fig2), data_table))
```

**Comment by clairetang6** [comment]
For the CustomJSFilter, I copied a lot of code from CustomJS and CustomJSTransform (probably could use a refactoring, but I'm not exactly sure where the code would go). The CustomJSFilter has a `code` parameter which is a JS snippet that has the variable `source` defined for it on the JS side. The `source` is the data source associated with the cds view that the filter is being used on. The `code` can either return the subset indices or a boolean array for filtering.

CustomJSFilter example:

customjsfilter

```python
from bokeh.plotting import figure
from bokeh.layouts import row, column
from bokeh.models.sources import ColumnDataSource, CDSView
from bokeh.models.filters import CustomJSFilter
from bokeh.models.tools import HoverTool
from bokeh.io import output_file, show

output_file("customjs_filter.html")

data = {'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'y': [10, 5, 2, 6, 1, 4, 8, 2, 7, 3],
        'z': ['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c', 'c']}

custom_filter = CustomJSFilter(code='''
var indices = [];
for (var i = 0; i <= source.data['z'].length; i++){
    if (source.data['z'][i] == 'a') {
        indices.push(true);
    } else {
        indices.push(false);
    }

}
return indices;
''')

custom_filter_coffee = CustomJSFilter.from_coffeescript(code='''
z = source.data['z']
indices = (i for i in [0...source.get_length()] when z[i] == 'b')
return indices
''')

def custom_python_filter():
    z = source.data['z']
    indices = [True if z[i] == 'c' else False for i in range(len(z)) ]
    return indices

custom_filter_pyscript = CustomJSFilter.from_py_func(custom_python_filter)

cds = ColumnDataSource(data)
view1 = CDSView(source=cds, filters=[custom_filter])
view2 = CDSView(source=cds, filters=[custom_filter_coffee])
view3 = CDSView(source=cds, filters=[custom_filter_pyscript])

plot_size_and_tools = {'plot_height': 220, 'plot_width': 220,
                        'tools':['box_select', 'reset'],
                        'x_range':[0, 11], 'y_range':[0, 11]}

fig1 = figure(title="CustomJSFilter", **plot_size_and_tools)
c1 = fig1.circle(x='x', y='y', source=cds, view=view1, color='black', hover_fill_color='red')
fig1.add_tools(HoverTool(tooltips=[("index", "$index"), ("(x,y)", "($x, $y)")], renderers=[c1], mode='hline'))

fig2 = figure(title="CustomJSFilter coffee", **plot_size_and_tools)
c2 = fig2.circle(x='x', y='y', source=cds, view=view2, color='black', hover_fill_color='red')
fig2.add_tools(HoverTool(tooltips=[("index", "$index"), ("(x,y)", "($x, $y)")], renderers=[c2], mode='hline'))

fig3 = figure(title="CustomJSFilter python", **plot_size_and_tools)
c3 = fig3.circle(x='x', y='y', source=cds, view=view3, color='black', hover_fill_color='red')
fig3.add_tools(HoverTool(tooltips=[("index", "$index"), ("(x,y)", "($x, $y)")], renderers=[c3], mode='hline'))


fig4 = figure(title="Full data set", **plot_size_and_tools)
c4 = fig4.circle(x='x', y='y', source=cds, color='black', hover_fill_color='red')
fig4.add_tools(HoverTool(tooltips=[("index", "$index"), ("(x,y)", "($x, $y)")], renderers=[c4], mode='hline'))

show(row(fig1, fig2, fig3, fig4))
```

**Comment by clairetang6** [comment]
Example with Bokeh server:
widget
```python
from bokeh.plotting import figure, curdoc
from bokeh.layouts import row
from bokeh.models.sources import ColumnDataSource, CDSView
from bokeh.models.filters import GroupFilter
from bokeh.models.widgets import RadioGroup

from bokeh.sampledata.iris import flowers

source = ColumnDataSource(flowers)
filter1 = GroupFilter(column_name='species', group='setosa')
filter2 = GroupFilter(column_name='species', group='versicolor')
filter3 = GroupFilter(column_name='species', group='virginica')
view1 = CDSView(source=source, filters=[filter1])
view2 = CDSView(source=source, filters=[filter2])
view3 = CDSView(source=source, filters=[filter3])

views = [view1, view2, view3]
filters = [filter1, filter2, filter3]

plot_size_and_tools = {'plot_height': 300, 'plot_width': 300,
                        'tools':['box_select', 'reset']}

fig1 = figure(title="Full data set", **plot_size_and_tools)
fig1.circle(x='petal_length', y='petal_width', source=source, color='black')

fig2 = figure(title="Subset", x_range=fig1.x_range, y_range=fig1.y_range, **plot_size_and_tools)
r = fig2.circle(x='petal_length', y='petal_width', source=source, view=view1, color='red')

radio_group = RadioGroup(labels=['Setosa', 'Versicolor', 'Virginica'], active=None)

def change_view1(view_index):
    r.view.filters = [filters[view_index]]

def change_view2(view_index):
    r.view = views[view_index]

radio_group.on_click(change_view2) #can be either change_view1 or change_view2

curdoc().add_root(row(fig1, fig2, radio_group))
```

Some quick notes: 
I originally had another connected signal where a change of the view's source would update it, but then I thought maybe the view shouldn't really have its source changed, because the glyph_renderer, source, and view should all be associated correctly. There maybe should be more checks/warnings there. 

Updating a source's data currently doesn't change the view's calculated subsets, but should.

**Comment by clairetang6** [comment]
The test that is failing now is the test for matching defaults between bokehjs and python. The two failing ones are for the GlyphRenderer and the DataTable. To those two models, I have added a `view` property which is a CDSView that should default to a CDSView created with that instance's data source. 

On the bokehjs side, I have:
```
@define{
    view =  [ p.Instance           ]
}

initialize: (options) ->
    super(options)

    if not @view?
      @view = new CDSView({'source': @data_source})
```

On the python side, I have: 
```
    view = Instance(CDSView, help="""...""")

    def __init__(self, **kw):
        super(GlyphRenderer, self).__init__(**kw)
        if "view" not in kw:
            self.view = CDSView(source=self.data_source)
```

Then the test says `GlyphRenderer.view: bokehjs defaults to null but python defaults to {"attributes":{"filters":[],"js_event_callbacks":{},"js_property_callbacks":{},"name":null,"source":null,"subscribed_events":[],"tags":[]},"type":"CDSView"}`

Does anyone know how I should resolve this? I want to have default value for view, but I need it to be associated with the correct data source.

**Comment by mattpap** [comment]
This is a bug (or a bad design decision) in defaults' tests, because those initialize models for collecting defaults. Which means that in your case, the default isn't `None` as it may seem from looking at model's properties, but `CDSView(...)`. However, bokehjs' defaults don't include initialization.

**Comment by bryevdv** [comment]
@clairetang6 Unless there is a dimension I am missing I think you can handle this the way that e.g. the lasso select tool handles its polygon overlay instance:

```
overlay:                [ p.Instance, DEFAULT_POLY_OVERLAY ]
```
with 
```
DEFAULT_POLY_OVERLAY = () -> new PolyAnnotation({
  level: "overlay"
  xs_units: "screen"
  ys_units: "screen"
  fill_color: {value: "lightgrey"}
  fill_alpha: {value: 0.5}
  line_color: {value: "black"}
  line_alpha: {value: 1.0}
  line_width: {value: 2}
  line_dash: {value: [4, 4]}
})
```

**Comment by bryevdv** [comment]
E.g. here is how the script ignores the `DatePicker` value, which defaults to the untestable "now" on one side:

https://github.com/bokeh/bokeh/blob/master/bokehjs/test/defaults.ts#L67-L69

**Comment by bryevdv** [comment]
If need be we could ignore `view` entirely, but perhaps something better can be done. Maybe you could make a partially initialized default on the JS side (identical properties except for the source) and then ignore only the view source property

**Comment by mattpap** [comment]
I would prefer to actually fix `generate_defaults.py` to not depend on instances. I think the current approach is just for implementer's convenience and can be replaced. I have some ideas, but need to experiment a bit.

**Comment by bryevdv** [comment]
> I would prefer to actually fix generate_defaults.py to not depend on instances. I think the current approach is just for implementer's convenience and can be replaced. I have some ideas, but need to experiment a bit.

This PR has been open a long time. We need to get it merged so we can get some experience with it in dev builds. I am not opposed to improving the defaults testing, but I am opposed to blocking this PR on that a this point.

**Comment by mattpap** [comment]
@bryevdv, PR #6573 has a sample implementation of what I mean. There four test failures to resolve there.

**Comment by clairetang6** [comment]
I changed the bokehjs to 
```
@define{
    view =  [ p.Instance, () -> new CDSView() ]
}

initialize: (options) ->
  super(options)

  if not @view.source?
    @view.source = @data_source
    @view.compute_indices()
```

 which fixes the test for now. But I will need to update it if the defaults tests no longer depend on initialization.

**Comment by bryevdv** [comment]
@clairetang6 @canavandl @mattpap I'd like to merge this tomorrow unless there is objection

**Comment by clairetang6** [comment]
I think this is ready to be merged. There may be some integration tests that should be added and we definitely need more documentation, but I can add those in follow up PRs.

**Comment by bryevdv** [comment]
Great, merging now.

**Comment by huileiw** [comment]
When will this be released?

**Comment by bryevdv** [comment]
> When will this be released?

Near the end of this month

**Comment by mshap09** [comment]
Do we have a better idea of when, specifically, 0.12.7 (which I believe contains this functionality) will be released?

**Comment by bryevdv** [comment]
just now

https://bokeh.github.io/blog/2017/8/29/release-0-12-7/

**Pull request merged**
