### PR TITLE
"Sticky" last item bug in dropdown

### PR DESCRIPTION
**Pull request by mistakevin**
resolves issue https://github.com/bokeh/bokeh/issues/2631

### CODE REVIEW

**Comment by bryevdv** [comment]
@mistakevin is this `ready`? I tested with branch the code from the issue, and it is working as expected. LGTM

**Comment by mistakevin** [comment]
I'm good if you are

**Comment by bryevdv** [comment]
Actually I do wonder if there is a reason for `action` instead of `value`? I think `value` would be more consistent with other widgets. @mattpap any input?

**Comment by mistakevin** [comment]
I have no issue changing it to `value`. The term `action` is little confusing.

**Pull request merged**
