### PR TITLE
Allow scroll in inspector's model/property panels

### PR DESCRIPTION
**Pull request by mattpap**
image

### CODE REVIEW

**Comment by bryevdv** [comment]
@mattpap is there currently any way to activate the `Inspector` tool on models other than plots? What if I want to examine the state of a `DataTable` or other widget?

**Comment by mattpap** [comment]
This will be possible via a context menu (including plots that don't have a toolbar), when that's finally implemented.

**Comment by bryevdv** [comment]
Well, actually `InspectorTool` is a bit awkward, given then we already have (and have had for many years) a category of tools called "Inspectors"

https://docs.bokeh.org/en/dev-3.0/docs/user_guide/interaction/tools.html#inspectors

I would actually otherwise document this tool under that category but it seems a bit confusing and redundant with the current name.

**Comment by bryevdv** [comment]
I do think we need to change the name.  "InspectorTool" is too generic, which is why it is a category of tools. `ModelExplorerTool` could work, or if we really want brevity, then even just `ExplorerTool` would at least not clash with the established usage.

**Comment by bryevdv** [comment]
I plan to start release build tomorrow morning so getting a name that does not conflict with existing concepts is somewhat time critical. I am stating my intent here to submit and merge a rename PR for `ModelExplorerTool`  tonight, unless you indicate a preference for something else before then.

**Comment by mattpap** [comment]
Just to note the UI component is called `Inspector`, thus the tool name `InspectorTool` (previously `SettingsTool`).  `Inspector` seems to me fitting for this. Perhaps `ModelInspector` would allow to disambiguate more from `InspectTool`, but the tool is not only about models (currently it handles signals as well, and I will be adding more view related stuff later on). Also, when context menus are finally implemented, my intention is to use `Inspect` menu item name for accessing the tool (same as in devtools). `Exporer` or `ModelExplorer` doesn't seem fitting in my opinion. To me it sounds like a help or documentation tool, as in explore what bokeh or this visualization/dashboard offers, or in a designer setting, what kinds of models could be added to an app. In any case, I will go ahead and merge this PR, as naming the tool/component is unrelated to the scope of this PR.

**Comment by bryevdv** [comment]
@mattpap I agree that "inspect" would otherwise be nice on its own. But I am just not  content to be in a situation with docs like "The `InspectorTool` is one of Bokeh's inspector tools". That's just terribly confusing. For a context menu, I think "Examine" would also work equally well? What about `ExamineTool` which does not tie specifically to models?

**Review by bryevdv — APPROVED** [review]

**Pull request merged**
