### PR TITLE
Added unsorted_label parameter to chart builder to don't sort labels

### PR DESCRIPTION
**Pull request by FabriceSalvaire**
This pull request solves the issue #3606.

I don't know if it is the right way to achieve this but it works.

Example to test:

    from bokeh.charts import Bar, output_file, show
    data = {
        'labels': ('EN', 'PD', 'AD'),
        'counts': (10, 20, 30),
    }
    p = Bar(data, values='counts', label='labels', unsorted_label=True)
    output_file("bar.html")
    show(p)

### CODE REVIEW

**Comment by bryevdv** [comment]
I think I'd like this better if were something like `label_sort=None`, with the reason that it would potentially be nice to supply a function to do the sorting (*ideally* that could be deferred to the browser). Adding an `unsorted_label` bool flag would easily be inconsistent with that kind of future work (i.e., of we add this now and `label_sort` later, what meaningful interpretation could be given to the combination `label_sort=mysort, unsorted_label=True`?)

**Comment by fpliger** [comment]
We have been using `AttrSpec`s for all charts attributes so I think we should stick with these... That's actually how you control ordering for other attributes like `color`, `group`, `stack`, etc.. I'd actually expect `label` to accept a a `CatAttr` as argument (just like the other attributes) but it doesn't. So I'd fix this behaviour instead of adding another special argument for this special attribute...

**Comment by fpliger** [comment]
@FabriceSalvaire actually it does work out of the box.. you just need to explicitly pass both `label` and `values` arguments. So in your case you can do with just:

```Python
from bokeh.charts import Bar, output_file, show
from bokeh.charts.attributes import  CatAttr
data = {
    'labels': ('EN', 'PD', 'AD'),
    'counts': (10, 20, 30),
}
label = CatAttr(df=df, columns='labels', sort=False)
p = Bar(data, values='counts', label=label)
output_file("bar.html")
show(p)
```

**Comment by FabriceSalvaire** [comment]
I felt this solution, then it is just a documentation issue. I agree we cannot add a parameter for each particular case.

Actually the chart API is fine for usual cases, but I think it would be nice to have an intermediate level between a low and high level API. I don't know how to use the low level API to make complex custom plots and  for the chart API the user guide presents a kind of processing on top of Panda data frame.

For example there are many ways to plot an histogram:
* from precomputed data
* using weighted counts
* using fixed / variable width binning
* with vertical bar 
* or like a polyline or with x/y error bar, in this case we interpret the histogram as a 1D function
* etc.

I believe there is no limitation in the BokehJS side, it is more a matter of examples.

**Comment by fpliger** [comment]
@FabriceSalvaire yes... totally agree it's a documentation issue. We already have this marked and are working on it. There is an open PR (#3417) that is tackles part of this work of generating documentation content and another PR to integrate mode content directly in the docs should be landing soon.. Any suggestions or contributions on this side are very very welcome. :)

Regarding the general concept of charte being high level and target for the usual use cases... that is. It is actually not an easy problem to try and cover all different kinds of inputs (and data shapes) and offer deep level of customization (like ordering labels, grouping, stacks, markers, colors, etc.. ) without blowing an API. My (very opinionated in this case :) ) opinion is that the new `Charts` design does do a good job about offerening a considerable vast level of expressiveness, maintaining still an fairly limited API. That said, we aim to make it more simple and at the same time powerful on every iteration..

Finally, regarding mid level API, plotting should be exactly what you are talking about. :)

**Comment by fpliger** [comment]
closed as feature is already build in and we just need to work on better docs

**Comment by b-trav** [comment]
@fpliger - your code snippet above does not work for me.

If I execute it, I get "NameError: name 'df' is not defined"

If I replace df=df with data=data, I get:

"ValueError: expected an instance of type ColumnDataSource, got {'counts': (10, 20, 30), 'labels': ('EN', 'PD', 'AD')} of type dict"

**Comment by b-trav** [comment]
For a code snippet that does work check out @fpliger's earlier answer in this post:

https://github.com/bokeh/bokeh/issues/2924

**Pull request closed without merging**
