### PR TITLE
Use x.x.xdev[rc] instead of xxx-dev[rc] for versioning devel builds

### LINKED ISSUE #1913: try to make y.y.yrc, not y.y.y.rc in dev build to avoid being listed above y.y.y release

### PR DESCRIPTION
**Pull request by damianavila**
Issues: fixes #1913 
I tested the generation of a devel build and everything seems to work OK:

log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/52365726/log.txt
binstar: OK
cdn: OK
docs: OK
installation: OK

I removed the CDN and binstar packages because it comes from a PR and not from master...

### CODE REVIEW

**Comment by bryevdv** [comment]
LGTM

**Comment by damianavila** [comment]
I forgot something I have to check, labelling as WIP to prevent an early merge...

**Comment by damianavila** [comment]
OK, this should be ready again for review...

**Comment by damianavila** [comment]
And to make @bryevdv  's day a little bit more happy, I added a test to check the correct url :wink:

**Comment by bryevdv** [comment]
great!

**Comment by bryevdv** [comment]
I suppose to be complete we might want to check that `0.8.2dev.whatever` sorts before `0.8.2rc1` but as far as I remember the verlib rules it will.

**Comment by damianavila** [comment]
>I suppose to be complete we might want to check that 0.8.2dev.whatever sorts before 0.8.2rc1 but as far as I remember the verlib rules it will.

As far as I know, yes... pretty sure we will know if it is not the case... je...

**Pull request merged**
