### PR TITLE
Optimise bokehjs (part 1)

### PR DESCRIPTION
**Pull request by mattpap**
This is first round of bokehjs optimisations. For now I tested this only on one example (scatter plot, 100k points), so bokehjs may be significantly broken.

### CODE REVIEW

**Comment by mattpap** [comment]
I rescheduled for 0.8 as this is too deep PR be finished for 0.7.1. However, the first commit is trivial and fixes the double rendering of plots issue, and could be merged earlier. I can prepare a PR if this is desirable.

**Comment by bryevdv** [comment]
@mattpap yes please do

**Comment by mattpap** [comment]
Created PR #1643.

**Comment by damianavila** [comment]
Closing accordingly with [BEP 1](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management#pull-requests). The branch will be available for you if you want to reopen this one with an updated status. Thanks!

**Pull request closed without merging**
