### PR TITLE
Correct spell mistakes

### PR DESCRIPTION
**Pull request by raghavgai**
Partially fixes issue: #8448

### CODE REVIEW

**Comment by bryevdv** [comment]
FYI @raghavgai the above long list of commits outside this PR is why I prefer to have a new branch for every PR. It's often the case that PRs should be reviewed on a per-commit basis and having extra commits from earlier PRs show up makes that task more difficult.

**Comment by raghavgai** [comment]
Hey @bryevdv, sorry i had not deleted the old branch let me close this, delete and resubmit, also i was searching to mark this pull request as draft, somehow i could not find that option.

**Comment by bryevdv** [comment]
@raghavgai no worries just wanted to mention for future reference!

**Comment by bryevdv** [comment]
superseded by #8845

**Pull request closed without merging**
