### PR TITLE
explicitly kill stray processes on travis

### PR DESCRIPTION
**Pull request by bryevdv**

### CODE REVIEW

**Comment by birdsarah** [comment]
Regarding my comment earlier about runnign a subset of examples. See:

https://github.com/bokeh/bokeh/blob/master/tests/examples/collect_examples.py#L89

You could have all those methods only return a slice of the list.

**Comment by bryevdv** [comment]
NOT Working:

screen shot 2016-12-14 at 5 04 47 pm

Working:

screen shot 2016-12-14 at 5 04 59 pm

The only difference seems to be in the *number* of jupyter related things

**Comment by bryevdv** [comment]
well, OK it was the conda nb changes somehow after all

**Comment by bryevdv** [comment]
worked with pinned notebook version but not conda nb changes. Putting back conda nb change to confirm thats  the problem.

ping @damianavila it appears that this change to disable the conda nb extension is breaking our build by making something not clean up properly.

**Comment by bryevdv** [comment]
Yup, adding the line back to remove the conda nb extensions breaks the build

**Comment by bryevdv** [comment]
So one option would be to just disable all notebook checks for now. If we revert the conda nb uninstall, then the nb tests are just worthless, so not point in doing that. I'd rather leave the conda nb uninstall, and just disable the notebook tests until there is a solution. Or we could try some kind of `killall` at the end of the script? open to suggestions @bokeh/dev

**Comment by bryevdv** [comment]
@bokeh/dev @damianavila adding `killall python` at the end seems to allow a successful termination:

https://travis-ci.org/bokeh/bokeh/jobs/184349786

This seems like a pretty crappy bandaid, but is it an acceptable one for now?

**Comment by damianavila** [comment]
I proposed this one: https://github.com/bokeh/bokeh/pull/5574, let see how it goes... btw, this is really weird...

**Comment by bryevdv** [comment]
#5574 did not solve the issue, I propose to merge this for now.

**Pull request merged**
